### ISSUE TITLE
sample-host 小bug

### ISSUE THREAD

**Issue by NemoHzy** [Tencent/Shadow#100]
sample-host 安装后打开崩溃，提示“从assets中复制apk出错”
如题，检查后发现是个小问题，sample-plugin/sample-plugin-app下的build.gradle 67行的 archivePrefix名字是 plugin，生成的debug包为 plugin-debug.zip。与sample工程中的build。gradle和PluginHelper类的sPluginZip上的名称无法对应，不会被拷贝到assets下和加载

**Comment by shifujun** [comment]
感谢反馈。像这样的小问题，也欢迎大家贡献代码的。
