### ISSUE TITLE
plugin中无法获取Host中的自定义属性

### ISSUE THREAD

**Issue by hc1991** [Tencent/Shadow#1003]
#1000 
基于这个场景修改了，API27 为MixResources，但是会遇到其他问题，plugin中获取不到Host的主题属性
 
case:
https://github.com/Tencent/Shadow/commit/81ba5a5ea93f8c415e698d7a22b91399dee0a587

API 27测试失败
API 31测试成功，能够在插件中读取到Host的主题属性

**Comment by hc1991** [comment]
我尝试将PluginContainerActivity继承类由Activity改成AndroidX的AppCompatActivity，也会遇到上述问题。AppCompatActivity在setContentView的时候会去检查主题，报如下错误：
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)

https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/appcompat/appcompat/src/main/java/androidx/appcompat/app/AppCompatDelegateImpl.java
![image](https://user-images.githubusercontent.com/17923307/176118266-6627c812-fee6-4480-9308-4cfc7df0d6ac.png)


PluginContainerActivity在setContentView的时候，获取到插件resource，主题校验出现异常

**Comment by shifujun** [comment]
https://github.com/hc1991/Shadow/blob/81ba5a5ea93f8c415e698d7a22b91399dee0a587/projects/test/plugin/androidx-cases/test-plugin-androidx-cases/src/main/java/com/tencent/shadow/test/plugin/androidx_cases/lib/ThemeValueTestActivity.java#L18-L26

你这里试图用插件的Resources加载宿主中的theme资源，这个不是Shadow支持的场景。混合插件和宿主资源的目的见： https://github.com/Tencent/Shadow/commit/f208e8be245e165f9753094fd2f6ef02f5208135 提交记录。

注意不可行的主要原因是宿主和插件版本的多对多关系。

**Comment by hc1991** [comment]
我们主要场景是插件是AndroixX的AppCompat场景（测试用例中的AndroidX，最终还并不是启动的AppCompatActivity）。但是由于宿主中已经集成了AndroidX，所以在插件中并没有将AndroidX打进APK，而是共用宿主的(打入AndroidX 包体增加好几兆)。
把shadow中的PluginContainerActivity改成继承自AppCompatActivity时，AppCompat中本身就有很多默认属性资源，在启动PluginContainerActivity执行setContentView时候，会有大量的AppCompat主题属性判断和获取，此时getResource和getTheme拿到的是插件的resource，会出现使用插件的Resource读取宿主中的AppComat主题资源场景(插件共用宿主的AndroidX包)
