### ISSUE TITLE
manage和plugin包远程服务下载，校验是否已下载和是否有更新

### ISSUE THREAD

**Issue by cq0702** [Tencent/Shadow#1004]
请问下，宿主app动态下载加载manage-project和插件plugin，目前shadow支持判断是否已经下载完manage和plugin包并且判断版本号，是否有新版本需要重新下载？还是说这些判断都是需要我这边自己去写代码做判断。感谢

**Comment by shifujun** [comment]
插件升级逻辑需要你自己写。对于core-manager来说，后安装的插件就是最新版本的。

可以用config.json中的`UUID_NickName`来标记业务版本号：
https://github.com/Tencent/Shadow/blob/e7988d6d26d4804d598fc64e5e9e9c852edbb2d2/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/PluginConfig.java#L43-L46

也完全重写core-manager满足自己的需要，重写manager逻辑是不会涉及loader的。

**Comment by cq0702** [comment]
好的，谢谢，还有一个问题，目前我已经在宿主里动态下载并加载manager包了，但是好像不能在manager里再去下载plugin-project包，manager不像其他项目是可运行可视化的页面，添加okhttp试了下有点问题。请问下在manager里怎么再去下载plugin包呢，就是普通的在manager里用okhttp去下载吗？还是有什么其他的处理方案会更好点呢?
