### ISSUE TITLE
startForegroundService  目前不支持吗？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#1005]
在插件中通过 startForegroundService  启动没有反应， 似乎目前不支持前台服务。
那么插件中启动一个需要在前台运行的服务有什么思路嘛？
1 . 如果要改shadow源码的话，要改哪些方面？
2. 或者服务注册在宿主，在宿主启动前面服务？

**Comment by shifujun** [comment]
前台服务更多的是跟系统进行交互，所以不太可能做到动态新增插件的前台服务。基本上只能考虑宿主注册一个前台服务，将其行为委托到插件中。这样的话，问题就变成了处于宿主中的前台服务代码和插件代码的通信问题。

Shadow中的Service并没有一个宿主中的Service壳子。插件Service都是被Loader持有和管理生命周期的，实现的也比较简单。其重点在于插件Service的binder是通过PPS这个真实的系统Service传递的，因此也都注册到系统中成为可以跨进程通信的binder。以此来支持的插件Service支持跨进程通信。
