### ISSUE TITLE
我在应用生成测试的时候发现bugly后台有这个偶发的问题，请教一下该怎么去避免呢，这个产生原因是什么呀

### ISSUE THREAD

**Issue by yexingyun** [Tencent/Shadow#1007]
连接Service超时 ,等待了：10001

com.test.plugin_manager.SamplePluginManager.onLoadClass(SamplePluginManager.java:115)

**Comment by norkmGitHub** [comment]
我也遇到了这个，老哥，问题解决了吗

**Comment by yexingyun** [comment]
并没有解决，也不知道如何解决，作者也没回我




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月11日(星期二) 中午1:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/Shadow] 我在应用生成测试的时候发现bugly后台有这个偶发的问题，请教一下该怎么去避免呢，这个产生原因是什么呀 (Issue #1007)





 
我也遇到了这个，老哥，问题解决了吗

**Comment by norkmGitHub** [comment]
好吧，真遗憾。。。

**Comment by yexingyun** [comment]
早就不做这个项目了，也就没管，建议去看看爱奇艺的插件化吧，比这个貌似好点

**Comment by luoxiong94** [comment]
> 早就不做这个项目了，也就没管，建议去看看爱奇艺的插件化吧，比这个貌似好点

谢谢老哥
