### ISSUE TITLE
启动插件过程没有报错，但是插件Activity无法启动

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#1010]
将Manaer的方法进行了拆分，通过FromId 将不同的功能暴漏到宿主。宿主只有一个Activity, 当宿主启动插件时，在成功的回调中 finish() 宿主唯一的Activity。 此时可以将插件 A 启动起来。 但是在插件 A 中，通过接口调用宿主中的方法，来启动插件 B 中的 Activity 或者  插件 A 中 其它 Activity 时，无法启动。 
但是当延迟一会儿finish() 时， 该现象又不存在了。 或者通过 Hander 将 finish() 动作 post 出去。 这个现象也不会出现。

改现象已在 [Demo](https://github.com/lks6123/ShadowPluginDemo/tree/master) 中复现 。 

大佬可以帮我看看嘛？

**Comment by lks6123** [comment]
> 你的Demo不是Shadow的fork，不方便看。
> 
> 由于插件Activity都有宿主Activity作为壳子，那么Activity的任何现象其实都只是普通的Activity操作。因此你可以观察Activity栈，在普通的无Shadow参与的应用中构造相同的Activity栈结构来理解遇到的现象。比如如果给两个插件Activity分配同一个SingleTask的壳子Activity，如果要启动这两个插件Activity，在系统看来就是重复启动同一个Activity。

不是SingTagk的Activity， 断点调试Shadow源码， mContext.startActivity(initent）这一步都已经走了。但是Activity 没有启动起来

**Comment by shifujun** [comment]
我看到你是通过这里启动的插件Activity：
https://github.com/lks6123/Shadow/blob/919fe396b74f011479d453f9e746084612259a63/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L141-L143

那应该是`FLAG_ACTIVITY_NEW_TASK`的缘故。

>When using this flag, if a task is already running for the activity
     * you are now starting, then a new activity will not be started; instead,
     * the current task will simply be brought to the front of the screen with
     * the state it was last in.  See {@link [#FLAG_ACTIVITY_MULTIPLE_TASK](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/Intent.java;drc=9f4eb48493739fb8975a236bce72865b8f82d5a7;l=6514)} for a flag
     * to disable this behavior.
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/Intent.java;l=6469-6473;drc=9f4eb48493739fb8975a236bce72865b8f82d5a7

所以加上FLAG_ACTIVITY_MULTIPLE_TASK应该就好了。

这里sample使用FLAG_ACTIVITY_NEW_TASK是因为PluginLoader启动插件Activity是用非Activity Context启动的。

至于finish为什么异步调用会影响这个现象，我估计仔细研究下Activity栈的差异应该就能明白了。

**Comment by lks6123** [comment]
> 我看到你是通过这里启动的插件Activity： https://github.com/lks6123/Shadow/blob/919fe396b74f011479d453f9e746084612259a63/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L141-L143
> 
> 那应该是`FLAG_ACTIVITY_NEW_TASK`的缘故。
> 
> > When using this flag, if a task is already running for the activity
> > * you are now starting, then a new activity will not be started; instead,
> > * the current task will simply be brought to the front of the screen with
> > * the state it was last in.  See {@link [#FLAG_ACTIVITY_MULTIPLE_TASK](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/Intent.java;drc=9f4eb48493739fb8975a236bce72865b8f82d5a7;l=6514)} for a flag
> > * to disable this behavior.
> > https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/Intent.java;l=6469-6473;drc=9f4eb48493739fb8975a236bce72865b8f82d5a7
> 
> 所以加上FLAG_ACTIVITY_MULTIPLE_TASK应该就好了。
> 
> 这里sample使用FLAG_ACTIVITY_NEW_TASK是因为PluginLoader启动插件Activity是用非Activity Context启动的。
> 
> 至于finish为什么异步调用会影响这个现象，我估计仔细研究下Activity栈的差异应该就能明白了。

测试了下，确实可以解决。  我再研究看看这个 Activity 栈的情况。
