### ISSUE TITLE
Maven依赖SDK

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#1011]
大佬，想问一下怎么把sdk推送到Maven仓库，按照文档操作了一下，没有成功

**Comment by cq0702** [comment]
+1 我报错
Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'apkName' for object of type com.tencent.shadow.core.gradle.extensions.PluginApkConfig. 
在plugin-app中找不到Shadow所添加的Dimension flavor
你什么错误

**Comment by TA-J** [comment]
> +1 我报错 Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'apkName' for object of type com.tencent.shadow.core.gradle.extensions.PluginApkConfig. 在plugin-app中找不到Shadow所添加的Dimension flavor 你什么错误

本地仓库没问题，但是推送远端仓库不行

**Comment by cq0702** [comment]
推送不成功，那就是配置不对。publishing下repositories里要配置好maven信息
maven {
                    name = "GitHubPackages"
                    credentials {
                        username = "xxx"
                        password = "xxx"
                    }
                    url "xxx"
                }
