### ISSUE TITLE
多插件的几个疑问

### ISSUE THREAD

**Issue by chenlin139** [Tencent/Shadow#1012]
需求：
项目中接入多个插件，每个插件支持单独更新，插件由外部提供
问题：
1、由于接入的插件都是外部开发后提供的，项目只提供下载插件和插件交互功能，多个插件的情形下是不是每个插件都要接入loader和runtime模块？这种情况是不是得给每个插件设置一个pps并且设置不同的uuid
2、每个插件支持单独更新的情况下，是不是每个插件都得写个manager模块。能否把manager移植到宿主工程中，将插件的下载和管理放到宿主中，不用单独打成apk

**Comment by shifujun** [comment]
你的问题在过去的issue中都有讨论过。

**Comment by shifujun** [comment]
你可以先向sample工程贡献你的场景，然后再和大家在这个场景下讨论技术实现问题。否则就根据sample已有的场景去理解现有代码，然后自己二次开发满足自己的场景。

**Comment by njzhangsan2013** [comment]
请问你那边解决了吗？我也有这方面的需求。其实manager.apk本来就在外部，主要是把runtime和loader打成独立的zip，然后就是每个插件都是一个独立产的zip。多个插件用的同一个runtimeloader。分包已经没有问题，只是加载有问题
