### ISSUE TITLE
宿主传参给manager和插件plugin

### ISSUE THREAD

**Issue by cq0702** [Tencent/Shadow#1013]
请问下宿主怎么传参给manager或者插件plugin啊 ,就是在宿主里启动插件的时候，同时传参给插件。

**Comment by cq0702** [comment]
看了demo里的shadow.sample.host.lib配置，不太明白，因为我只需要宿主传参给插件，所以用不到AIDL，我看sample，宿主和插件都配置了shadow.sample.host.lib，但是方法是怎么使用的呢，插件里怎么调用宿主里的类方法还是不太明白。

**Comment by shifujun** [comment]
多调试代码就明白了。
