### ISSUE TITLE
Shadow\buildScripts\gradle\common.gradle' line: 3

### ISSUE THREAD

**Issue by shuanglong520** [Tencent/Shadow#1014]
代码克隆下来 编译就报这个问题 运行不了
![111111](https://user-images.githubusercontent.com/20728137/178394489-edeb1a96-1fd2-475d-88d4-29ddff495b0d.png)

![22222](https://user-images.githubusercontent.com/20728137/178394501-f3e33add-d21c-4d28-a276-5e8018aa368a.png)

**Comment by shifujun** [comment]
你的git没有配置在运行ide的path环境变量里。实际上是gradle的运行环境，在你的场景中是ide决定的。

这个问题是Windows开发环境相关的，和shadow项目关系不大。

**Comment by shifujun** [comment]
你的git没有配置在运行ide的path环境变量里。实际上是gradle的运行环境，在你的场景中是ide决定的。

这个问题是Windows开发环境相关的，和shadow项目关系不大。

**Comment by shuanglong520** [comment]
环境我这应该配置了，之后直接克隆下来的项目，运行就是这个问题

我的配置 那个地方出现了问题，谢谢

![33333](https://user-images.githubusercontent.com/20728137/178414627-06d3322f-59c3-4dae-8ca0-6494bd62792a.png)
![4444](https://user-images.githubusercontent.com/20728137/178414645-38a4e8b2-3257-4c61-a2f4-20a62710cc51.png)



> 你的 git 没有配置在运行 ide 的环境变量里。实际上是 gradle 的运行环境，在你的场景中是决定的。
> 
> 这个是Windows开发环境相关的，和影子项目关系不大。

**Comment by shifujun** [comment]
帮你Google了一下：https://stackoverflow.com/a/53706956

**Comment by shuanglong520** [comment]
感谢，运行成功
