### ISSUE TITLE
请问如何修改maven文件夹下plugin-project的压缩包的名称，是要手动修改吗

### ISSUE THREAD

**Issue by Hackerofshi** [Tencent/Shadow#1015]
debug {
                loaderApkConfig = new Tuple2('sample-loader-debug.apk', ':sample-loader:assembleDebug')
                runtimeApkConfig = new Tuple2('sample-runtime-debug.apk', ':sample-runtime:assembleDebug')
                pluginApks {
                    pluginApk1 {//businessName相同的插件，context获取的Dir是相同的。businessName留空，表示和宿主相同业务，直接使用宿主的Dir。
                        businessName = 'plugin1'
                        partKey = 'plugin1'
                        buildTask = 'assemblePluginDebug'
                        apkName = 'plugin-app-plugin-debug0.apk'
                        apkPath = 'plugin-app/build/outputs/apk/plugin/debug/plugin-app-plugin-debug0.apk'
                    }
                }
            }
            
         将apk名称改成   plugin-app-plugin-debug0.apk，但是运行./gradlew packageReleasePlugin 后发现打包后的名称还是plugin-app-plugin-debug.apk。
         
         另外有没有交流群呀，有人踩过坑的话应该很好解决。

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/6614007e25e27a4f7855d43bd805adab36d08e40/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/CreatePackagePluginTask.kt#L80

代码在这里

**Comment by Hackerofshi** [comment]
谢谢
