### ISSUE TITLE
sample-host-lib里的类动态设置数据后，插件调用类方法获取值为空

### ISSUE THREAD

**Issue by cq0702** [Tencent/Shadow#1016]
我在宿主和插件里添加了一个类似sample-host-lib的配置，宿主可以动态传参给插件，但是仅限写死的数据。如果我在宿主里动态传参给类，在插件里再调用获取数据，会拿不到。是因为在2个进程的原因吗？这种情况应该怎么处理呢？
lib里的类
public class HostUiLayerProvider {
    private static HostUiLayerProvider sInstance;
    public static String QopenId = "";
    public static void setParams(String openId){
      QopenId = openId;
   }
  public static Bundle getParams() {
        final Bundle params = new Bundle();
        params.putString("openId", QopenId);
        return params;
  }
}
宿主里调用setParams，插件里调用getParams,会拿到空数据。大佬指点下

**Comment by shifujun** [comment]
建议复习《操作系统原理》课程中”进程间通信“相关内容。多进程不是Shadow引入的特性，你在普通App中也会遇到此问题。
