### ISSUE TITLE
宿主activity主进程，添加很多复杂的插件view，每个插件单独的apk。

### ISSUE THREAD

**Issue by anxiao521** [Tencent/Shadow#1018]

**Comment by anxiao521** [comment]
看着issues讨论的是在manager上实现的，我也尝试了实现，确实可以。但是这样需要让插件的同事把view单独拆出来给我，然后我在实现部分跳转插件的逻辑，重构很复杂。请问现有框架除了这样，还有其他好的方式么？

**Comment by anxiao521** [comment]
自己给自己回答一下吧，费劲把火的算是把产品的需求给实现了。一个宿主activity显示多个插件提供的view，宿主显示的view是不固定的，最后的思路，增加了各种限制，提供view的插件必须只提供view，不涉及到activity之类的的界面。剩下的就是模仿dynamic-apk的实现就好了。修改的地方在HelloImplLoader的ChangeApkContextWrapper，我重现实现了一个application的代理替换了ChangeApkContextWrapper，主要兼容一下三方会调用getApplicationContext后在拿context出现资源找不到的情况。最终算是实现动态view的更新显示，但是限制比较大，各种不支持。按照产品的逻辑还有几百上千个插件view可在宿主上动态配置，感觉最后开发了一个动态组件库。不知道有没有其他思路。

**Comment by senda58** [comment]
@anxiao521 你好，我想请较几个问题，能不能加个联系方式一起讨论一下呀 qq：164918226
