### ISSUE TITLE
死循环问题

### ISSUE THREAD

**Issue by yumdao** [Tencent/Shadow#1020]
在`InstrumentationTransform`中，原生的`Instrumentation`被替换成`ShadowInstrumentation`，`runtime`库中的`ShadowInstrumentation`类的父类被替换成自己。
![image](https://user-images.githubusercontent.com/93634445/179657028-89201e2a-9ef2-4462-b8a2-a6c2c6ba49fb.png)

导致在`FragmentSupportTransform`中调用`isClassOf`进入死循环的问题：
![image](https://user-images.githubusercontent.com/93634445/179657138-8b1f3e66-4584-434a-adc4-6df8f5606b4c.png)
![image](https://user-images.githubusercontent.com/93634445/179657154-02054b60-3fb0-40b0-9ad6-da56b162a5e5.png)

`ShadowInstrumentation`是否需要在Transform的时候进行豁免？

**Comment by shifujun** [comment]
runtime模块正常不应该被打包到插件apk中，因此不应该被transform修改。建议先看下sample的打包情况，对比下你的工程。

**Comment by yumdao** [comment]
插件中错误的使用了pluginImplementation，应该用pluginCompileOnly代替，感谢
