### ISSUE TITLE
项目使用Shadow框架，可以上google play吗？

### ISSUE THREAD

**Issue by tony-xian-2017** [Tencent/Shadow#1027]

**Comment by jiangwei18** [comment]
肯定上不了

**Comment by shifujun** [comment]
看你干什么用。按我的理解，苹果、Google等应用商店都是禁止应用动态更新软件功能的。插件或热更新等能动态更新软件代码的技术都有能力动态更新软件功能，同时也有能力动态修复bug。应用这些技术如果只用于修复bug，一般是能够通过审查的。

从技术对抗的角度看这个问题，shadow也只依赖dexclassloader，这个动态加载class的技术技术广泛存在于各种app中。所以shadow比较容易对抗技术审查。
