### ISSUE TITLE
如何复用其它插件的Fragment?

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#1029]
通过接口将 B 插件中的Fragment对象返回给 宿主中使用，如果使用androidx.fragment.app.Fragment的话， 会报 castException 。
这是两边使用了不同的classloader加载fragment。
如果把 androidx.fragment.app 加入白名单，运行会直接报错。
使用android.app.Fragment的话，倒是可以加载到，虽然会报找不到资源文件。 但是现在很少使用 android.app.Fragment 这个类了，基本上都是androidx里面的Fragment.
大佬有什么解决思路吗？

**Comment by shifujun** [comment]
shadow中插件fragment都是正常的fragment，它们实际上被添加到了宿主Activity上管理的。然后shadow是修改了一些对fragment方法的调用，使那些方法可以返回插件资源或者插件Activity类型。

androidx的fragment是相当于业务自己实现的代码。跟前面说的shadow对fragment的支持没什么关系。

但这两种fragment都有一个特点是，它们的不可修改的内置逻辑都将自己的资源和activity的资源绑定了。同时生命周期也是。因此跨apk，也就是跨资源，复用fragment和这一设计是有冲突的。

由此我建议对于跨插件复用activity部分公共代码的需求，不直接应用fragment来实现。针对多插件的多apk以及更进一步的多版本对应关系的特点，应该重新设计一种插件的类型。也许可以进一步自动编辑原本的fragment到这种新类型上。

**Comment by Daimhim** [comment]
自己定义一个接口，让两个fragment 实现，调用的时候转到这个接口就行  不要直接使用androidx中的fragment，记得把这个接口加到白名单

**Comment by budaowengd** [comment]
> 自己定义一个接口，让两个fragment 实现，调用的时候转到这个接口就行 不要直接使用androidx中的fragment，记得把这个接口加到白名单

请问下为啥不要直接使用androidx中的fragment，我现在用了androidx确实崩了，提示找不到
