### ISSUE TITLE
so库

### ISSUE THREAD

**Issue by shenhcen0614** [Tencent/Shadow#103]
能解决so库冲突吗？两个插件使用了相同的so，能否各个插件是用各自的so库

**Comment by shifujun** [comment]
不能。so冲突只能通过进程隔离解决。不过Shadow支持在多个进程中同时使用。

**Comment by shenhcen0614** [comment]
意思是只需要多进程就能解决是吗，A插件在A进程，B插件在B进程就能实现各个插件使用各自的so

**Comment by shifujun** [comment]
是的，A、B两个插件分在不同进程就可以避免so冲突。它们可以通过service相互通信。

**Comment by shenhcen0614** [comment]
shadow 现在已经实现了对吧 谢谢

**Comment by shifujun** [comment]
在不同进程可以避免so冲突不需要shadow特别实现。shadow已经实现支持service了。

**Comment by shenhcen0614** [comment]
你们这块有开发文档吗？

**Comment by shenhcen0614** [comment]
没有maven的接入文档吗
