### ISSUE TITLE
想请教一个问题，我看几乎所有的module都是java-library，而不是android-library？这样子做的目的？

### ISSUE THREAD

**Issue by jiangwei18** [Tencent/Shadow#1033]
我理解，可能是CodeGenerator那部分生成java部分需要用到android.jar，其他的module为啥也要用java-library？还请大佬帮忙解释下。十分感谢

**Comment by shifujun** [comment]
首先这个选择不是必要的，用android-library也是可以的。用android- library会引入很多不需要的构建过程，对应生成的产物就是aar包中除了jar之外的部分。我们的这些module都只需要jar的部分。所以用java-library可以加速构建，也省得设置那些android专用的属性了。早先也用过android-library，那时在构建出aar之后再从中复制出jar，然后丢弃其他部分也是一样的。
