### ISSUE TITLE
想问下 如何优雅的使用android:process这个属性

### ISSUE THREAD

**Issue by wlssing** [Tencent/Shadow#1037]
除了再host中写  有其他的办法嘛

**Comment by shifujun** [comment]
使插件的android:process生效还需要很多的开发工作。

首先需要一个工作于manager中插件process管理器，由它获取到插件的组件对应的process后，转调到对应process的PPS上。

读取插件组件的process也还需要一定的开发量。目前已经有编译期解析Manifest的代码了，最终可以把插件的process信息写到插件apk中的一个class中。如果保持这个设计，那就需要在manager所在进程就要加载一次apk，从中读取class了。所以还需要将组件的process信息优化到一个单独的持久化文件中。

插件内部的组件启动调用也需要重新设计，先将调用发回manager中的process管理器上，以便识别出跨进程的调用。

最后如果需要插件新增的process也能生效，我们还需要开发一套编译期工具自动生成宿主中所需的Manifest声明。

基于以上考虑，单一业务很难会选择开发这样一套通用的代码。因为单一业务一般process是比较固定的，宿主Manifest也不便动态更新。

**Comment by wlssing** [comment]
thx  大致了解了

**Comment by jacobchow** [comment]
> 
另外，ContentProvider也需要适配多进程。
1、在onBindContainerContentProvider中根据插件provider的process信息，将业务provider和用于进程占位的容器Provider建立映射关系
2、如果插件进程A中发起请求，转调给PluginContainerContentProvider（业务Provider和容器Provider均定义在进程B），则在B进程中转调给业务Provider前，需要加载loader和plugin。

@shifujun 大佬是否有更优雅的思路实现provider的多进程特性？
