### ISSUE TITLE
难道不考虑写一个快速集成指南吗？

### ISSUE THREAD

**Issue by xuexiangjys** [Tencent/Shadow#104]
能否把源码SDK放到jcenter，并写个简易的集成指南，不然用起来太费劲了，作为玩具玩玩还可以，真正想要用起来集成到项目中去还是需要考虑考虑的

**Comment by shifujun** [comment]
首先“快速集成”这种定义意味着接入的场景是固定的。而我们业务实际在用的场景非常复杂，我们做不到提供一个快速集成的说明。如果说只是一个单插件启动的最简单的场景，那也可以说代码即文档了，Sample就是最简单的场景，抄过去就行了。我们已经特别注意Sample中少写接入无关的代码了。对于接入场景的复杂性，你可能需要理解一下，使用方只有一种场景，而实现方需要考虑多种场景了。包括动态性、多进程、多插件，插件的依赖关系等等。

没有发布到jcenter就是因为我们认为这个SDK不能直接拿来给每个业务使用。不同业务是需要根据自身情况进行修改和裁剪的。所以可以认为Shadow是一个SDK的SDK。另外现在已经已经有maven发布的脚本了，你可以自己发布到自己的maven仓库中使用。

真正接入到项目中使用是需要彻底理解大部分原理和实现的，这也是开源项目的特点。这种开源项目要和*将成熟服务开源*区别来看。所以也要注意到Shadow并没有在腾讯云开发者服务中上线。目前Shadow既不是一个收费服务，也*不是一个免费服务*，只是一个开源项目。开源项目是把我们业务真正在用的代码拿出来和大家分享交流的。所以你说是一个玩具，那Sample确实只是一个玩具，但是我们可以保证这个玩具里面的核心代码和我们线上用的是一致的。所以开源出来的时候，保证这个玩具可用是我们的主要目标，希望大家可以比较方便的通过这个玩具研究Shadow的原理和实现。

把插件技术包装成简单易用的服务是需要大量工作的。我们没有必要包装成完善易用的服务后再拿出来开源。一是我们自身业务用不上，二是对插件技术有深入了解的人不需要那些包装代码就能看懂Shadow的核心代码。

这些包装工作，处于我们业务自身需求，也在慢慢做。但如果Shadow开源了以后，没有任何人参与共建，那这个开源意义就不大了。所以，也欢迎大家贡献易用性改进方面的代码。

**Comment by xuexiangjys** [comment]
那我可以将它理解为，目前只是个半成品，真正需要使用还需要二次开发喽，这样的话岂不是上手和改造成本会很大，难怪开源了那么久在网上也没找到更多相关的资料。主要是可用性实在是太差了。

一个开源项目从刚开始接触到接入，如果耗时超过3小时，基本90%的人都会选择放弃了。

但是我觉得这些事情还是有必要做的，不然你这样的开源是不会有人跟进的

**Comment by shifujun** [comment]
我不强求你理解哈。

你说的都对，只是没有意识到”服务“与”开源项目“的关系和区别。你讲的一切都是对”服务“的要求。”开源项目“不是拿出来给你接入的，是拿出来和你交流的。如果你跑Shadow提供的Sample或者自动化测试用例有问题，那是要解决的问题。如果你看哪部分代码觉得不够好，这是该交流的问题。

现在Shadow的Sample和自动化测试代码对于研究和继续开发Shadow来说是足够的。这是满足开源项目让大家参与进来的必要条件。有了这些必要条件，已经可以有一部分人跟进了。

90%的人放弃了，10%的人没放弃，那开源就是有意义的。否则如果要一直等服务完善再开源，可能就连10%的人参与进来的机会都没有了。当然完善的服务会吸引更多人参与进来，这是显然的事，只是有很大成本。

还有，以我对插件技术的了解，我们几乎是不可能提供一个不需要二次开发的SDK的。因为插件技术的应用场景实在是太复杂了。而且，我也用过其他插件技术，在维护的过程中，我也意识到，必须了解插件技术的实现原理细节，才能正常使用它。因为这种技术涉及到的Hook实在太多了。想根据一个文档简单接入，一键发布，跑起来是简单的，长期维护是不可能的。

**Comment by xuexiangjys** [comment]
如果你们没时间写的话,我可以帮你们写个快速集成指南,你看如何?

**Comment by shifujun** [comment]
当然欢迎啦！任何共建的事情，我都会抽出额外的精力支持的。

**Comment by xuexiangjys** [comment]
简单试了一下，发现使用起来还是比较麻烦，本来想写一个快速集成指南的，发现这插件化方案真的不太适合中小企业使用，上手成本太高，所以我觉得现阶段还是没有写的必要。下面是我简单接入的一个demo项目地址：

https://github.com/xuexiangjys/ShadowTest.git
