### ISSUE TITLE
有没有shadow沟通群啊

### ISSUE THREAD

**Issue by zhizhongbiao** [Tencent/Shadow#1044]

**Comment by zhizhongbiao** [comment]
在shadow中使用Arouter总是报错找不到path

**Comment by zhizhongbiao** [comment]
shadow支持使用Arouter进行跳转页面吗

**Comment by HeLiHuang** [comment]
![Shadow插件化框架交流群聊二维码](https://user-images.githubusercontent.com/7981470/200156994-888f72dd-f4ba-4a0c-a752-5d550c837a2d.png)
