### ISSUE TITLE
Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory

### ISSUE THREAD

**Issue by Heart-Beats** [Tencent/Shadow#1046]
确实是的，runtime 和 loader 按 Android 工程模板创建的，当时删除时对 `androidx.core:core` 这个依赖不确定作为 app 缺少此依赖是否可行就保留了，在没改 PluginClassLoader 加载之前是没问题的，也算是自己给自己挖了个坑，
![image](https://user-images.githubusercontent.com/33248551/122353739-eb946080-cf82-11eb-9804-8319286d37ec.png)

_Originally posted by @Heart-Beats in https://github.com/Tencent/Shadow/issues/529#issuecomment-863011041_

**Comment by Heart-Beats** [comment]
大佬，最近公司有需求把其他项目集成到一个基础 app 中，因为之前看过稍微接触过 Shadow，所以就打算以原生插件方式集成。

目前的现状：在以前的基础上我分别弄好了宿主和插件模块，但是启动插件时却报如下图的错误：
![image](https://user-images.githubusercontent.com/33248551/189484067-f4a971fd-c369-43d9-ad64-5c44431ef2f2.png)

因为之前接触过，所以宿主相关的集成我单独抽成了一个 shadow-init 模块可远程依赖，插件模块使用了我之前的 demo 进行改造，仓库地址：[ShadowPlugin](https://github.com/Heart-Beats/ShadowPlugin)，

为了方便找出相关问题，我在 fork 的 Shadow 仓库对 maven 示例的宿主进行了修改， 仓库地址：https://github.com/Heart-Beats/Shadow/tree/dev_zhanglei，  提交记录： [测试 2.2.1 版本打包插件启动异常的问题](https://github.com/Heart-Beats/ShadowPlugin/commit/4656e728c118988b36ccd832904a523d9d7fbd48)， 运行时截图如下：

![image](https://user-images.githubusercontent.com/33248551/189484371-0e819b7b-3b3c-4cea-bda5-929fa77d2860.png)

具体操作步骤：
1. 点击启动 2.2.1 打包插件，会从 assets 目录下加载 `plugin-release.zip ` 这个插件包；
2. 点击启动 89a753c5 打包插件，会从 assets 目录下加载 `plugin-89a753c5-release` 这个插件包；

都打开插件包中 sunflower 这个示例应用，但第一种方式直接就报截图中的堆栈错误，第二种方式可进行正常启动，正常启动后再点击第一种方式后无问题，除非清除整个应用数据。

两个插件都是由插件 demo 中生成，不同点为依赖的 Shadow 版本不同，可通过下图方式进行切换：
<img src="https://user-images.githubusercontent.com/33248551/189484371-0e819b7b-3b3c-4cea-bda5-929fa77d2860.png" alt="image" style="zoom:50%;" />

其中 `local-89a753c5-SNAPSHOT` 为去年我在该提交上打出的一个远程依赖包，`2.2.1`  为使用 Gitbub 上的版本。因为有一段时间未接触此项目，不太清楚大佬对这个作了何修改，因为我看最新的 `shadow.plugin` 版本会自动生成一个 plugin 的 flavor， 但我编译插件未选中该 flavor， 同时最新版本的 `ComponentManager ` 也去除了 getBroadcastInfoList 这个方法，我不太清楚是不是我的使用方式问题还是最新版本的未知问题导致的，希望大佬可以看下我描述的问题解答一下，我看这一年多 Shadow 有挺多提交，因此还是希望可以接入新的版本！

**Comment by shifujun** [comment]
> Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory

像这样的Cannot cast A to B的错误可以这样排查：

1. 确定Cannot cast 异常是根异常，没有进一步的caused by。
1. 检查A的字节码，确认其.super字段确实是B或B的子类。
1. 在运行时，拿到A的对象a，获取其ClassLoader，用这个加载A的ClassLoader查找B类。再拿到抛出cast异常的代码所属类的ClassLoader，用它也查找B类。对比两次查找到的B类是否是同一个对象。如果不是，注意它们的ClassLoader，进一步确定其所属的jar包、dex文件。这一检查流程关注的重点是JVM加载类的机制是用当前类的ClassLoader加载其引用的其他类。如果有多个ClassLoader中加载了同名的类，那它们对于JVM来说是不同的类。因此就算抛出异常Cannot cast X to X也是常见的情况。

**Comment by Heart-Beats** [comment]
![image](https://user-images.githubusercontent.com/33248551/190146470-eea3645b-b5ca-4b61-ad1e-9f8881f6905f.png)

切换为该 flavor 对应的变体打包，可成功启动插件，关闭该 issue
