### ISSUE TITLE
shadowContext的Resources 好像有问题

### ISSUE THREAD

**Issue by wlssing** [Tencent/Shadow#1048]
手机IQOO8  晓龙888  12+4G    型号V2136a
ANDROID 12
我的情况 我大致描述一下 
1.现在app 是由A.apk 依赖 B.apk   在A中我们使用了B中assets资源   我在B的application中 获取了一下 
```
 public AssetManager getBAssets(){
        return sInstance.getAssets();
    } 
```
sInstance为b的application单例
A中我将这个assets传递到jni中  而且这个assets只被jni引用，其他地方无任何调用。jni中
`AAsset* aa = AAssetManager_open(FileUtilsAndroid::assetmanager, s, AASSET_MODE_UNKNOWN);`
判断这个文件是不是在assets中
此功能在百分之九十九的情况下正常
但是某些特定的情况下  会死锁，会崩溃，刚进来的时候弹网页，会崩溃。 
不同手机不同，我的这台必崩溃
![image](https://user-images.githubusercontent.com/10703383/190412247-0abc34c0-4e2b-459d-b109-daed21be2791.png)

初步怀疑resources有问题   修改代码
```
 val pluginResource = packageManager.getResourcesForApplication(applicationInfo)

//            return if (Build.VERSION.SDK_INT > MAX_API_FOR_MIX_RESOURCES) {
//                pluginResource
//            } else {
                val hostResources = hostAppContext.resources
                return MixResources(pluginResource, hostResources)
//            }
```
必崩溃的问题  正常了。

**Comment by shifujun** [comment]
看起来不太合理。因为如果你只修改了你贴出来的那几行代码。由于`getAssets()`方法是`final`的，所以`MixResources`返回的也是`pluginResource.assets`。这和直接使用`pluginResource.getAssets()`是一样的。

如果说你也同时修改了`fillApplicationInfo`的if-else分支，那确实会有涉及Assets的实质变化。主要是插件的Assets不再包含宿主apk的资源了。如果是这种变化会触发问题，那么作为API 12的系统来说，肯定是系统Bug了。

**Comment by wlssing** [comment]
thx

**Comment by wlssing** [comment]
这个问题我说一下吧   这是sInstance被GC了  因为java这边没被强引用这个application  你把asset传给jni  jni一直认为asset是可用的，但是发生GC的时候 jni持有的asset  已经无效了 所有会有问题

**Comment by shifujun** [comment]
Java对象传给JNI使用不是必须要在Java侧保持有引用的，那样写得来得多麻烦，Java代码会多出好多看起来毫无道理的引用。JNI侧的Reference是分为Local和Global的。Local的生命周期只存在于进入JNI调用栈期间，如果JNI代码把Local Ref存起来了，再下次JNI调用进来时继续使用则会出错。如果时Global Ref则会始终有效，直到手工释放为止。
