### ISSUE TITLE
插件中通过context获取签名信息是空，能否将宿主的签名信息注入到插件PackageInfo呢，这样可以在插件中获取到应用签名

### ISSUE THREAD

**Issue by Tomgogo** [Tencent/Shadow#1051]
PackageInfo info = context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_SIGNATURES);

Signature[] signatures = info.signatures;

**Comment by shifujun** [comment]
一般我们应该只把确实宿主和插件一致的信息从宿主复制到插件中。这里插件的签名虽然没有支持，但是宿主和插件两个apk的签名显然是不一样的。我想不应该这样简单的复制过来。你的业务自己这样改应该没什么问题，但是合入作为通用逻辑好像不太说得通。

你这个场景应该可以override这个context的getPackageManager方法，然后返回特定的PackageInfo吧。这个PackageInfo可以让插件和宿主约定好接口直接获取的。

**Comment by Tomgogo** [comment]
如果是要区分插件和宿主的签名，这种设计也是合理的。但目前插件签名没有支持，而大多数场景插件里获取签名都是要获取当前app即宿主的，目前没有想到有其他的场景要校验插件的签名。单独的业务场景获取宿主签名的方式的确也有几种，比如可以从宿主传过来或者约定接口获取。

**Comment by jacobchow** [comment]
插件需要复用宿主签名的场景，可以自己修改下PluginPackageManagerImpl类中的方法： 
`override fun getPackageInfo(packageName: String, flags: Int): PackageInfo? {
        val hostPackageInfo = hostPackageManager.getPackageInfo(packageName, flags)
        return if (packageName.isPlugin()) {
            val packageInfo = hostPackageManager.getPackageArchiveInfo(pluginArchiveFilePath, flags)
            if (packageInfo != null) {
                packageInfo.applicationInfo = getPluginApplicationInfo(flags)
                packageInfo.permissions = hostPackageInfo.permissions
                packageInfo.requestedPermissions = hostPackageInfo.requestedPermissions
                packageInfo.signatures = hostPackageInfo.signatures  // 添加这一行
            }
            packageInfo
        } else {
            hostPackageInfo
        }
    }`
