### ISSUE TITLE
useHostContext使用问题

### ISSUE THREAD

**Issue by zhuqichao** [Tencent/Shadow#1052]
请问下useHostContext的作用是什么？需要怎么使用，可以达到配置哪些类的activity参数不替换为ShadowActivity的效果吗？

**Comment by shifujun** [comment]
这个其实没多大用处，这是较早的业务代码需要的，所以一直没有删除。

它实际上就是自动给符合规则的context参数套了一层`getBaseContext()`调用：
https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/KeepHostContextTransform.kt#L78

实际上应该让宿主和插件约定好如何获取宿主Context，以便插件代码可以按业务场景需要使用。
