### ISSUE TITLE
setFlags(FLAG_ACTIVITY_SINGLE_TOP)  启动不起来activity

### ISSUE THREAD

**Issue by wlssing** [Tencent/Shadow#1054]
[FLAG_ACTIVITY_SINGLE_TOP不支持 提交](https://github.com/Tencent/Shadow/commit/dcd329d6e1f3afd39d954407bc22f9b1a41ad127)

setFlags(FLAG_ACTIVITY_SINGLE_TOP)  启动不起来activity

**Comment by shifujun** [comment]
因为那个MainActivity和要启动的，比如TestActivityOnCreate，对系统来说都是PluginDefaultProxyActivity。所以PluginDefaultProxyActivity已经显示在最前面了，你再启动一个single top的PluginDefaultProxyActivity，当然就没反应了。

这个配对关系在这里：
https://github.com/Tencent/Shadow/blob/d27e984aff6caaa2cf6812c5edbc0aa817ade486/projects/sample/source/sample-plugin/sample-loader/src/main/java/com/tencent/shadow/sample/plugin/loader/SampleComponentManager.java#L50-L57

**Comment by wlssing** [comment]
> 因为那个MainActivity和要启动的，比如TestActivityOnCreate，对系统来说都是PluginDefaultProxyActivity。所以PluginDefaultProxyActivity已经显示在最前面了，你再启动一个single top的PluginDefaultProxyActivity，当然就没反应了。
> 
> 这个配对关系在这里：
> 
> https://github.com/Tencent/Shadow/blob/d27e984aff6caaa2cf6812c5edbc0aa817ade486/projects/sample/source/sample-plugin/sample-loader/src/main/java/com/tencent/shadow/sample/plugin/loader/SampleComponentManager.java#L50-L57

我想过改这个  但是改这个每个singletop的不都得需要添加  而且每个singletop对应不同的activity  如果前面已经是single top  也没反应。这个怎么处理
