### ISSUE TITLE
线上崩溃问题

### ISSUE THREAD

**Issue by zhuqichao** [Tencent/Shadow#1059]
我们的项目遇到较多线上崩溃，本地没有复现，请教一下可能是什么原因：
Inlined method resolution crossed dex file boundary: from void com.tencent.shadow.dynamic.manager.PluginManagerThatSupportMultiLoader.onPluginServiceConnected(android.content.ComponentName, android.os.IBind) in /data/user/0//files/miguplugins/plugin-manager-app.apk/0x6ed667cc40 to com.tencent.shadow.dynamic.host.MultiLoaderPpsController com.tencent.shadow.dynamic.host.MultiLoaderPluginProcessService.wrapBinder(android.os.IBinder) in /data/user/0/包名/Anonymous-DexFile@567269928.jar/0x6f7f2428c0. This must be due to duplicate classes or playing wrongly with class loaders. The runtime is in an unsafe state.

**Comment by shifujun** [comment]
` /data/user/0//files/miguplugins/plugin-manager-app.apk/0x6ed667cc40`这个apk看起来还像是shadow项目输出的manager.apk。但是` /data/user/0/包名/Anonymous-DexFile@567269928.jar/0x6f7f2428c0`就完全不是Shadow项目生成的了。所以我推断你的项目里有其他流程"duplicate classes or playing wrongly with class loaders"。

**Comment by zhuqichao** [comment]
> ` /data/user/0//files/miguplugins/plugin-manager-app.apk/0x6ed667cc40`这个apk看起来还像是shadow项目输出的manager.apk。但是` /data/user/0/包名/Anonymous-DexFile@567269928.jar/0x6f7f2428c0`就完全不是Shadow项目生成的了。所以我推断你的项目里有其他流程"duplicate classes or playing wrongly with class loaders"。

分析崩溃数据，发现崩溃100%是Android9设备，由日志看和Android9内联优化有关
排查代码发现，plugin-manager-app.apk打包了本应该在宿主里的MultiLoaderPluginProcessService这个类，是不是和这个有关系？
