### ISSUE TITLE
某个插件多个版本的时候。占用的存储空间是会越来越大是吧？

### ISSUE THREAD

**Issue by cyberau** [Tencent/Shadow#1065]
你好，我看了下，插件安装是解压zip包，然后存储信息到数据库。
如果某个插件有新版本安装，那旧版本解压的内容是不会删除的是吧，如果很多个版本的话，存储空间是会越来越多是吧？

**Comment by yexingyun** [comment]
你不是可以自行删除管理吗

**Comment by 1455033987** [comment]
反正插件是装在你的app下的，你可以在进入之前判断版本号，如果有出入就删除原有的插件，下载新的就好
