### ISSUE TITLE
问个简单的问题，支持多个插件运行在不同的进程吗？

### ISSUE THREAD

**Issue by byedo** [Tencent/Shadow#1066]
我看介绍是“跨进程使用插件Service”这个意思不会是只支持插件是只有service运行在独立的进程吧

**Comment by jacobchow** [comment]
支持每个插件分别运行在不同进程。不支持单个插件中的不同组件运行在多个进程。

**Comment by bbfxier** [comment]
> > > 支持每个插件分别运行在不同进程。不支持单个插件中的不同组件运行在多个进程。
> > 
> > 
> > 多问一句，插件中只有activity或者只有service，这个插件都是可以在自己独立的进程运行的，对吧，谢谢回复
> 
> 是的，参考demo代码SamplePluginManager#getPluginProcessServiceName方法，根据插件的partkey映射到指定PPS就行了

现在微信没有用shadow，手q在用，对吧，我反编译看了
