### ISSUE TITLE
关于Service解绑时onServiceDisconnected调用的疑问

### ISSUE THREAD

**Issue by jacobchow** [Tencent/Shadow#1068]
[https://github.com/Tencent/Shadow/pull/935/files](url)  
这笔提交中在正常解绑service时回调了onServiceDisconnected，但是按官方文档说法，此回调只有服务丢失时才会被调用：
[https://developer.android.com/reference/android/content/ServiceConnection](url)

> Called when a connection to the Service has been lost.

这里是否与原生逻辑不同？还是有其他考虑

**Comment by zhuqichao** [comment]
经过实际测试，原生系统在unbindService时是不会回调onServiceDisconnected的
