### ISSUE TITLE
修改shadow默认的so的储存路径可能存在的问题

### ISSUE THREAD

**Issue by Melody916** [Tencent/Shadow#1070]
在测试Android5.1的部分机型时，加载插件报了一个错，
 java.lang.UnsatisfiedLinkError: dlopen failed: library name "/data/data/com.haier.uhome.uplus/files/ShadowPluginManager/UnpackedPlugin/up-manager/lib/BB00C115-8195-416A-97B7-D8F95129C4C6_lib/libwxactive.so" too long

分析原因是Android5.1对64位的so库有路径长度限制，根据之前的issue号130里的备注，我修改了shadow默认的储存路径，
[https://github.com/Melody916/Shadow/blob/d7141522c2ff4639e57453dbbe29c2896f0c10a4/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/AppCacheFolderManager.java#L52-L58](url)

现在我想确认下，如果像我这样修改的话，对shadow的其他功能会不会有影响，是否存在其他风险？我需要着重测试哪些功能项才能确认这些风险是否都已规避。
辛苦大神，帮忙确认一下，非常感谢。

**Comment by zhuqichao** [comment]
完全可以自己实现manager相关逻辑，so存储路径只是一个路径而已，又会有什么问题呢
