### ISSUE TITLE
插件中xml包含TextClock标签，通过xml创建的View，add到父view，再removeView的时候 会报错Receiver not registered: com.tencent.shadow.core.runtime.BroadcastReceiverWrapper

### ISSUE THREAD

**Issue by hjqiaho** [Tencent/Shadow#1081]
我是用 (WindowManager) mContext.getSystemService(Context.WINDOW_SERVICE) add这个view 再移除出现的这个错误，
应该是TextClock中包含注册解注册广播导致，
这个用到的应该很少，不使用这个标签也可以

**Comment by hjqiaho** [comment]
shadow版本是2.3.0，我看之前有提到过这个错误#867，这个 版本应该是包含此代码的

**Comment by shifujun** [comment]
#1108
