### ISSUE TITLE
SamplePluginManager中getName的疑问

### ISSUE THREAD

**Issue by HeLiHuang** [Tencent/Shadow#1087]
SamplePluginManager中getName注释是这么写的：
/**
     * @return PluginManager实现的别名，用于区分不同PluginManager实现的数据存储路径
     */
意思是：如果多个插件用相同的存储路径，就可以用同一个SamplePluginManager实例对吗？
也就是说通常情况下，一个SamplePluginManager实例就可以管理多个插件了对吗？

**Comment by aa5279aa** [comment]
目前我的项目中，就是一个SamplePluginManager管理多个插件，前提这些插件是共享一份runtime和loader的。
按照我的理解，非官方的解释，一个SamplePluginManager好比一个管理者，一个管理者管理的是一类的业务范围。
