### ISSUE TITLE
Shadow可否实现组件的插件化

### ISSUE THREAD

**Issue by woojunfeng** [Tencent/Shadow#109]
看过了shadow源码，没太看懂是否能实现如下场景
将插件作为组件库，独立部署
例如：
PluginButton：View红色异型按钮
宿主界面，创建多个PluginButton并显示

**Comment by shifujun** [comment]
这个不是插件技术的目的。插件技术的主要目的是加载那些原本应该在AndroidManifest中定义才能启动的系统组件。

把一个View动态加载起来并不是太难。Shadow的Dynamic Manager在loading时显示的那个View就是这样动态加载的。

**Comment by woojunfeng** [comment]
感谢回复。

**Comment by woojunfeng** [comment]
感谢回复。
看了一下sdk的代码，ShadowRemoteViewCreator 可能是我想使用的实现方式，目前没太懂如何使用ShadowRemoteViewCreatorProvider，sample中好像也没有相关的例子，我再研究研究，也希望 @shifujun 能够提供一些帮助，谢谢

**Comment by woojunfeng** [comment]
@shifujun 
研究了一下ShadowRemoteViewCreator ，没有找到方法如何实现我的场景。

Host中持有ManagerImp 和 ManagerProcess(暂且叫这个，我理解是与Host独立的进程)
ManagerImp是可以通过直接调用，或者回调的方式将View实例提供给Host使用。
PluginLoaderImp是由ManagerProcess动态加载的
但是Plugin的PluginLoaderImp只能传回给ManagerProcess，不能跨进程传回给host使用

不知道我理解的对不对

**Comment by shifujun** [comment]
同#125 #131
