### ISSUE TITLE
shadow框架支持热更新吗？

### ISSUE THREAD

**Issue by 1455033987** [Tencent/Shadow#1092]
就是不关闭宿主APP的时候插件修改后进入插件可以直接执行修改后的插件？

**Comment by aa5279aa** [comment]
非官方的答复：
理论上是不可以的，shadow本身没有任何hook点，所以必须重启后才能加载新的类和插件。
但是有一种变通的方案，就是我把修改后的插件，当作一个新的插件进行加载，这样相关逻辑就会走到新的插件当中，当然有一个前提，就是必须离开当前插件所在的页面。

**Comment by byedo** [comment]
插件框架不就是能动态加载插件吗？你重启app就可以加载新的插件的逻辑
非官方回复

**Comment by 1455033987** [comment]
嗯，你说的那种算冷启动，就是app必须重启才可以，我说的就是不需要重启app

**Comment by aa5279aa** [comment]
之前已经说了，热启动的话用shadow可以实现，但是必须离开要被修复的模块，等于是加载一个新的修复过的插件。
就算官方过来，应该也是这个答案，这是框架选择类型的问题，基于类加载机制的，都这样

**Comment by shifujun** [comment]
前面说的对。

对于一个确定的Class对象来说，在Android平台我们无法修改它的代码。

对于”关闭App“、”执行插件“这种模糊的描述来说，可以利用重启进程的手段，辅以交互上的设计，达到预期效果。
