### ISSUE TITLE
java.lang.NoClassDefFoundError: 的错误处理建议

### ISSUE THREAD

**Issue by aa5279aa** [Tencent/Shadow#1094]
使用shadow加载插件，提示
`java.lang.NoClassDefFoundError:Failed resolution of: Landroid/app/PictureInPictureUiState;`
错误。
具体原因已经找到了，插件项目中使用了EventBus，而EventBus会遍历查找所有当前类及其父类中的方法。
android11时Activity增加了一个onPictureInPictureUiStateChanged方法，这个方法中参数引用到了android/app/PictureInPictureUiState;类。所以在安卓10及以下的手机上，插件中EventBus初始化时就会崩溃。
其实插件项目本身是没有使用到onPictureInPictureUiStateChanged这个方法的，所以，是否增加一个黑名单功能，在gradle中进行配置，黑名单中的方法不会打包到类似GeneratedPluginActivity这样的类更为合适？
只是一个建议，目前这个功能已经在我本地已经实现了，如果觉得有用，我希望提PR合并到shadow项目和大家一起分享。

**Comment by Heart-Beats** [comment]
老铁，这个是 EventBus 使用不当的问题，和 Shadow 没有关系，这个问题我遇到过都解决了， EventBus 正确的用法是需要配合 eventBusIndex 一起使用，你可以搜索相关

**Comment by aa5279aa** [comment]
> 老铁，这个是 EventBus 使用不当的问题，和 Shadow 没有关系，这个问题我遇到过都解决了， EventBus 正确的用法是需要配合 eventBusIndex 一起使用，你可以搜索相关

eventBus只是其中的一种表象，核心还是GeneratedPluginActivity中打包进了不属于其真是版本的方法和类，如果其它框架或者代码中就是用到了这个方法还是会有问题的，感觉核心还是区分打包版本来决定是否要打包对应的方法。

**Comment by zhuqichao** [comment]
宿主新建一个包名类名一致的空类就可以了

**Comment by hdjtdxwt** [comment]
我也遇到了，问题出在EventBus上，和 targetSdkVersion 31 上！
android/app/PictureInPictureUiState 这个类从sdk 31版本才有的，一开始项目 targetSdkVersion写的31，EventBus.regsiter(this);后，会一直从当前类以及当前类的父类里找有@Subscribe()的注解方法，找方法的代码在编译的时候应该会生成，所以apk里class字节码里应该就有去从PictureInPictureUiState 这个类找注解方法的代码，apk打包好放到了28的平板上跑时，28的平板上没有这一个类，就报错NoClassDefFoundError: Failed resolution of: Landroid/app/PictureInPictureUiState;了，不得以只得降低了targetSdkVersion 变成了28，平板上已经可以运行了

变成28后，androidx.appcompat:appcompat 和com.google.android.material:material的依赖版本有可能也需要降低些，不然有些系统的资源可能没有

android {
    compileSdkVersion 31
    buildToolsVersion "31.0.0"

    defaultConfig {
        applicationId "xxxx"
        minSdkVersion 26
        targetSdkVersion 31
        versionCode 105
        versionName "1.0.5"

    }
}

改成成了：

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.0"

    defaultConfig {
        applicationId "xxxx"
        minSdkVersion 26
        targetSdkVersion 28
        versionCode 105
        versionName "1.0.5"

    }
	dependencies {
		configurations.all {
			resolutionStrategy {
				force 'androidx.core:core:1.6.0'
			}
		}
		implementation 'androidx.appcompat:appcompat:1.4.1'
		implementation 'com.google.android.material:material:1.4.0'
	
	}
}

**Comment by hahajing9** [comment]
hello 这个问题的修复方案 同步一下 @aa5279aa

**Comment by hdjtdxwt** [comment]
> hello 这个问题的修复方案 同步一下 @aa5279aa

降低了targetSdkVersion 变成了28
