### ISSUE TITLE
java.util.zip.ZipException

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#1099]
经常会报zip异常
![image](https://user-images.githubusercontent.com/39261338/201053557-836ac4fe-0e85-4fed-9657-612935396a52.png)

**Comment by HeLiHuang** [comment]
解决了吗？

**Comment by TA-J** [comment]
没有哎，无从下手
![7 M_XPBS X$)Z IZRJXPY~7](https://user-images.githubusercontent.com/39261338/202361031-d6a37572-f3e5-41d0-ad40-f9b005e7a7f8.png)

**Comment by HeLiHuang** [comment]
你这样处理一下，zip包下载完之后Thread.sleep(500); 再执行打开动作

**Comment by TA-J** [comment]
> 你这样处理一下，zip包下载完之后Thread.sleep(500); 再执行打开动作

我这个直接打包在assets里面的，每次都是从这里面拿

**Comment by HeLiHuang** [comment]
一样的，从网上下载和从assets里拿是一样的

**Comment by shifujun** [comment]
如果你把SafeZipFile换回JDK的标准ZipFile能解决问题，那么要么是你的zip文件确实是有漏洞的，要么SafeZipFile确实有bug。如果是bug，你又不能给出复现路径，那issue也只能挂着等复现了。

**Comment by TA-J** [comment]
> 如果你把SafeZipFile换回JDK的标准ZipFile能解决问题，那么要么是你的zip文件确实是有漏洞的，要么SafeZipFile确实有bug。如果是bug，你又不能给出复现路径，那issue也只能挂着等复现了。

![image](https://user-images.githubusercontent.com/39261338/202938672-77874bf3-0202-44a3-b8af-6888cfa880de.png)
走到这里就直接抛异常了，出现的几率很少
