### ISSUE TITLE
下载后编译说找不到 ANDROID_HOME,但是我都设置了

### ISSUE THREAD

**Issue by ljk01200120** [Tencent/Shadow#11]
![image](https://user-images.githubusercontent.com/5901714/59902948-2f0a7180-9432-11e9-90bb-bf3d4474709b.png)

编译报错:ERROR: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
但是我上面图片显示环境变量都设置了，怎么回事？

**Comment by ideav5** [comment]
+1

**Comment by shifujun** [comment]
这应该是一个一般性的如何设置环境变量并使其生效的问题。简单说，设置之后重启一下是最省事的办法了。

**Comment by ljk01200120** [comment]
你看看我上面贴的那图，我都echo $ANDROID_HOME, 都显示路径了，我老早就设置了，不是一天两天了

**Comment by macarthor** [comment]
我的也是报错，用AS 3.4.1 x64打开的
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

## local.properties
ndk.dir=D\:\\ProgramsOthers\\Permanent\\AndroidSDK\\ndk-bundle
sdk.dir=D\:\\ProgramsOthers\\Permanent\\AndroidSDK

**Comment by shifujun** [comment]
> 你看看我上面贴的那图，我都echo $ANDROID_HOME, 都显示路径了，我老早就设置了，不是一天两天了

那大概是一个环境变量生效范围的问题。你执行`echo $ANDROID_HOME`能显示出来，说明你在Shell的环境变量里至少设置了。

Mac或者Linux的环境变量“最全局”的设置应该是在`/etc/profile`吧？加在这里试试吧。

再细说一下这个问题。可以在Shadow的源码中全局搜索一下`ANDROID_HOME `应该可以看出来，Shadow不是特别有什么逻辑需要这个环境变量。特别提到需要设置这个环境变量是因为Android Studio会自动创建`local.properties`文件，在里面自动填上sdk路径，这样就不需要设置`ANDROID_HOME `环境变量了。但是Android Studio才刚刚开始支持复合构建工程，它没能正确的自动为子构建创建`local.properties`文件。所以，我认为直接设置`ANDROID_HOME `环境变量是最省事的做法。另外一种解决方法是将`local.properties`文件复制到`projects/sdk/coding`、`projects/sdk/core`、`projects/sdk/dynamic`三个目录中。

**Comment by fso918** [comment]
我昨天也碰到这个问题，升级到AS3.4.1就好了

**Comment by HubertYoung** [comment]
我用的是Mac，终端执行下这行就没事了 launchctl setenv ANDROID_HOME /Users/hubert/opt/sdk    
把后面的路径换成你本机的sdk路径就ok了

**Comment by NoOneNo** [comment]
androidStudio 启动的环境和你设置ANDROID_HOME的环境不一致的问题.
在可以输出echo $ANDROID_HOME的环境下, 用命令行启动 androidstudio 应该就没问题了.

**Comment by jiasonwang** [comment]
如果 ANDROID_HOME 在.bashprofile 中定义，试着在它前面添加  export 指令。
