### ISSUE TITLE
如果宿主和插件的taskAffinity不同，当关闭宿主或插件中任意一个task，会不会影响另外一个task导致activity关闭呢？

### ISSUE THREAD

**Issue by dylanZk1** [Tencent/Shadow#1101]
这个问题主要是我在测试了Android12以上和以下的机型后发现的问题。我发现，将宿主和插件设置不同的taskAffinity和launchMode，关闭其中一个task时，Android12以下的机型就不会对其他task有影响，而Android12以上的就会强制关闭其他task的activity（Recent History列表没有去除）。而宿主之间的activity就不会有这个问题，请问这个问题该如何解决呢？

**Comment by 1455033987** [comment]
还有一个问题，就是如果我将插件作为入口放入桌面图标，该如何设置进入方式呢？是依托于宿主的activity还是？

**Comment by 1455033987** [comment]
说的再清楚些，就是如果要把插件放入桌面，点击桌面图标时如何获取到插件的状态呢，或者再简单些，就是获取到插件目前执行到哪个activity了？
