### ISSUE TITLE
解包一个下载好的插件 目录结构错误

### ISSUE THREAD

**Issue by tianguo1314** [Tencent/Shadow#1106]
解压出来的插件zip包缺少res文件夹
报：/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/2b5328c579dfb78e9fe78a46d0eac424/plugin-app-normal-debug.zip/res/layout/activity_main.xml: open failed: ENOENT (No such file or directory)

**Comment by qczgwxg** [comment]
大佬，您这个问题是咋解决的
。我也遇到这个问题啦
