### ISSUE TITLE
当前AGP版本是7.0.3，compile是31，SDK大概什么时候升级AGP-7.3.0，compile-33，目前只能本地去兼容么

### ISSUE THREAD

**Issue by chuyh163** [Tencent/Shadow#1107]

**Comment by shifujun** [comment]
你至少应该说清楚不升级会产生什么样的问题，以及这个问题如何复现。”只能本地去兼容“似乎表达了你有一种自行解决的方法，也应该描述清楚你的解决方法对代码做出了什么修改。

在指出代码位置时建议使用permalink引用：
https://github.com/Tencent/Shadow/blob/8d9c7a7f21629bf60ef7871323bb0f1512738e44/buildScripts/gradle/common.gradle#L11

更复杂问题可以fork代码后添加自己的修改，然后把代码push上来给大家看你的全部改动。
