### ISSUE TITLE
请教一下，ActivityTransform 之后，为什么插件 Activity 的 instanceof 结果还是 Activity 的子类

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#111]
在插件的 Activity 里执行以下代码:
```
var clz: Class<*> = this.javaClass
while (clz != Any::class.java) {
  clz = clz.superclass
  Log.d("MainActivity", "super class: $clz")
}
val thisActivity: Any = this
Log.d("MainActivity", "this is Activity:       ${thisActivity is Activity} ")
Log.d("MainActivity", "this is ShadowActivity: ${thisActivity is ShadowActivity} ")
Log.d("MainActivity", "this is PluginActivity: ${thisActivity is PluginActivity} ")
```
会得到以下结果：

```
D/MainActivity: super class: class androidx.appcompat.app.AppCompatActivity
D/MainActivity: super class: class androidx.fragment.app.FragmentActivity
D/MainActivity: super class: class androidx.core.app.ComponentActivity
D/MainActivity: super class: class com.tencent.shadow.core.runtime.ShadowActivity
D/MainActivity: super class: class com.tencent.shadow.core.runtime.PluginActivity
D/MainActivity: super class: class com.tencent.shadow.core.runtime.ShadowContext
D/MainActivity: super class: class com.tencent.shadow.core.runtime.SubDirContextThemeWrapper
D/MainActivity: super class: class android.view.ContextThemeWrapper
D/MainActivity: super class: class android.content.ContextWrapper
D/MainActivity: super class: class android.content.Context
D/MainActivity: super class: class java.lang.Object
D/MainActivity: this is Activity:       true
D/MainActivity: this is ShadowActivity: true
D/MainActivity: this is PluginActivity: true
```
这是```Kotlin``` 的代码，用```Java```实现也是一样的。为什么它父类没有```Activity```了，却还是 ```Activity``` 的实例。

**Comment by ruyingxiangsui** [comment]
因为插件instanceof Activity中的Activity引用也变成ShadowActivity了。所以实际代码是：
instanceof ShadowActivity



---原始邮件---
发件人: "东东东鲁"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 中午1:31
收件人: "Tencent/Shadow"<Shadow@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Tencent/Shadow] 请教一下，ActivityTransform 之后，为什么 instanceof 还是 Activity 的子类 (#111)



在插件的 Activity 里执行以下代码:
 var clz: Class<*&gt; = this.javaClass while (clz != Any::class.java) {   clz = clz.superclass   Log.d("MainActivity", "super class: $clz") } val thisActivity: Any = this Log.d("MainActivity", "this is Activity:       ${thisActivity is Activity} ") Log.d("MainActivity", "this is ShadowActivity: ${thisActivity is ShadowActivity} ") Log.d("MainActivity", "this is PluginActivity: ${thisActivity is PluginActivity} ")  
会得到以下结果：
 D/MainActivity: super class: class androidx.appcompat.app.AppCompatActivity D/MainActivity: super class: class androidx.fragment.app.FragmentActivity D/MainActivity: super class: class androidx.core.app.ComponentActivity D/MainActivity: super class: class com.tencent.shadow.core.runtime.ShadowActivity D/MainActivity: super class: class com.tencent.shadow.core.runtime.PluginActivity D/MainActivity: super class: class com.tencent.shadow.core.runtime.ShadowContext D/MainActivity: super class: class com.tencent.shadow.core.runtime.SubDirContextThemeWrapper D/MainActivity: super class: class android.view.ContextThemeWrapper D/MainActivity: super class: class android.content.ContextWrapper D/MainActivity: super class: class android.content.Context D/MainActivity: super class: class java.lang.Object D/MainActivity: this is Activity:       true D/MainActivity: this is ShadowActivity: true D/MainActivity: this is PluginActivity: true  
这是Kotlin 的代码，用Java实现也是一样的。为什么它父类没有Activity了，却还是 Activity 的实例。

**Comment by donglua** [comment]
噢，理解了。
