### ISSUE TITLE
用DexClassLoader加载插件中的类，提示找不到

### ISSUE THREAD

**Issue by HeLiHuang** [Tencent/Shadow#1110]
File file = new File(DockRemotePoolService.mContext.getFilesDir() + "/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/93c9e73c0138d3e13b2cc0f6c994d8c1/cup-plugin-app.zip/app-plugin-release-unsigned.apk");
        if(file.exists()){
            DexClassLoader classLoader = new DexClassLoader(file.getAbsolutePath(), null, null, DockRemotePoolService.mContext.getClassLoader());
            try {
                Class clazz = classLoader.loadClass("com.gwm.app.dock.devices.voice.VoiceHandler");
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }
        }

**Comment by shifujun** [comment]
Shadow没有对DexClassLoader做任何修改。

**Comment by HeLiHuang** [comment]
怎么把这个关了？其他的APK可以获取到apk中的类，就插件的获取不到
