### ISSUE TITLE
DexClassLoader获取APK中的类，宿主可以获取其他的APK中的类，就获取不到插件中的类

### ISSUE THREAD

**Issue by HeLiHuang** [Tencent/Shadow#1112]
File file = new File(getFilesDir() + "/plugin-app-debug.apk");
                if(file.exists()){
                    DexClassLoader classLoader = new DexClassLoader(file.getAbsolutePath(), getDir("dex", Context.MODE_PRIVATE).getAbsolutePath(), null, getClassLoader());
                    try {
                        Class clazz = classLoader.loadClass("com.shuwen.pluginapk.VoiceHandler");
                        System.out.println("aa");
                    } catch (ClassNotFoundException e) {
                        e.printStackTrace();
                    }

这个不是插件，就可以获取到，不会出现ClassNotFoundException 
但是插件的就会有ClassNotFoundException

**Comment by HeLiHuang** [comment]
不知道问题出在哪里？

**Comment by shifujun** [comment]
这个问题和Shadow没有关系。

如果你把你能复现问题的代码添加到Shadow项目中，那也可以说反馈了一个和开源项目有关的问题。比如添加到sample工程中。sample工程也是可以独立安装运行和插件方式运行的。你反馈说什么代码都没改，或者做了你认为合理的修改，但是工作不正常也行。

如果像你这样不停的把自己项目的问题发到开源issue中，没人能猜到你的项目写了什么。也没人对你的私有代码感兴趣。所以你的issue对别人来说都只是一个抱怨。不要再这样骚扰别人了。想想你用开源项目付出了什么？如果是交流学习，你分享了什么？

**Comment by HeLiHuang** [comment]
> 不知道问题出在哪里？

其实我这里打的是句号，不知道怎么成问号了，伤害到了你，不好意思！
