### ISSUE TITLE
构建失败：javassist.CannotCompileException: by javassist.bytecode.BadBytecode

### ISSUE THREAD

**Issue by hanxiao2018** [Tencent/Shadow#1113]
hi，在构建的时候依赖了第三方库，出现以下错误，帮看下如何解决：
**Execution failed for task ':plugin-app:transformClassesWithShadowTransformForPluginDebug'.
> javassist.CannotCompileException: by javassist.bytecode.BadBytecode: <init> (Lorg/webrtc/NetworkMonitorAutoDetect$Observer;Landroid/content/Context;)V in org.webrtc.NetworkMonitorAutoDetect: inconsistent stack height Index 12 out of bounds for length 12**

//NetworkMonitorAutoDetect构造方法
 public NetworkMonitorAutoDetect(NetworkMonitorAutoDetect.Observer var1, Context var2) {
        this.observer = var1;
        this.context = var2; 
       ...
}
//Observer接口
    public interface Observer {
        void onConnectionTypeChanged(NetworkMonitorAutoDetect.ConnectionType var1);
        ...
    }

**Comment by shifujun** [comment]
> org.webrtc.NetworkMonitorAutoDetect: inconsistent stack height Index 12 out of bounds for length 12

这很清楚，要么是org.webrtc.NetworkMonitorAutoDetect本身是坏的，要么是Shadow给改坏了。但是你藏着org.webrtc.NetworkMonitorAutoDetect不给人看，我就不明白你为啥要发个issue出来了。

如果你判断是Shadow给改坏了，你又没能力自己debug代码，那你只能把复现问题的代码开源出来。如果有人感兴趣，才有可能帮你解决。如果你压根没法开源代码。你就只能尽可能构造一个可以复现问题的开源代码。

一切都是建立在开源的基础上交流的。
