### ISSUE TITLE
在app中找不到Shadow所添加的Dimension flavor

### ISSUE THREAD

**Issue by lilidejing** [Tencent/Shadow#1114]
背景：我们项目用的shadow插件版本还是 2.1.0版本，现在想将项目插件版本提升为最新版本，本地运行java环境也改为了jdk11。
1，我将master分支的shadow代码下载下来后，通过gradlew publish即可将Shadow SDK发布到自己本地的Maven仓库。用demo宿主和demo插件依赖本地的仓库插件版本编译打包运行都没问题。 一切正常。
2，然后用我们的项目宿主APP依赖 刚发布的本地插件仓库，编译打包运行没问题。一切正常。
3，但是用我的插件APP依赖本地插件仓库版本，同步gradle文件时，会报如下错误,：
   `**在app中找不到Shadow所添加的Dimension flavor
当前所有flavor打印如下：
variant.name：iwristDebug
flavor.name：iwrist flavor.dimension：product 
variant.name：urovoDebug
flavor.name：urovo flavor.dimension：product 
variant.name：iwristRelease
flavor.name：iwrist flavor.dimension：product 
variant.name：urovoRelease
flavor.name：urovo flavor.dimension：product 
提示：添加flavorDimension时，不要覆盖已有flavorDimension
示例：flavorDimensions(*flavorDimensionList, 'new')**`

问题：请问 打包发布现在最新Shadow sdk到仓库时，除了修改版本号和发布的仓库地址，还会涉及到渠道号相关的改动吗？以上报错可能和什么有关？ 谢谢！

**Comment by shifujun** [comment]
你没什么没有反驳提示内容呢？

**Comment by lilidejing** [comment]
> 你没什么没有反驳提示内容呢？

谢谢！gradle 文件中有一句 flavorDimensions "product"  ，很老的代码，注释掉就行了
