### ISSUE TITLE
关于宿主白名单的匹配

### ISSUE THREAD

**Issue by zhuqichao** [Tencent/Shadow#1119]
阅读源码发现匹配类是否属于白名单中时有一个规则，并且白名单不支持指定具体类，只能指定包，为什么不直接用类名.startsWith进行判断是否处于白名单中，这样设计有什么考量吗？

**Comment by shifujun** [comment]
只能指定包是因为主要使用场景是添加一个包。这个包在宿主中是需要避免混淆和非兼容性修改的。所以这个包中类在宿主中有特殊的维护方式。也因此往往不能直接把宿主中的类添加到白名单中，需要在这个特别包中新建接口和适配器类。理解这一设计要注意宿主和插件版本的多对多关系。

startsWith肯定是第一直觉，好像早先的代码也是这样写的。但是这样实现在白名单列表比较长时速度比较慢。比如白名单里有很多规则，但都是com.tencent开头的。现在需要判断的类是org开头的。那在前缀匹配算法下只需要比较一次就能排除这个类类。

如果你在阅读源码，建议注意这些文件的提交历史记录，Shadow项目对于提交记录是比较注意的。搜索全部issue，而不是处于打开状态的，也是比较有用的。像这个白名单的问题有过很多issue。
