### ISSUE TITLE
你好，请问如果不需要多进程，把pps改成普通类，binder改为方法调用会有问题吗？

### ISSUE THREAD

**Issue by cyberau** [Tencent/Shadow#1125]
请问如果不需要多进程，把pps改成普通类，去掉binder，改为方法调用会有问题吗？

**Comment by shifujun** [comment]
什么是问题？是对你来说没有影响就算没问题，还是对所有场景来说都没有影响？后者的意思就是原本的代码是冗余的。

如果只关心对你有没有影响，为什么不直接试试呢？

**Comment by cyberau** [comment]
> 什么是问题？是对你来说没有影响就算没问题，还是对所有场景来说都没有影响？后者的意思就是原本的代码是冗余的。
> 
> 如果只关心对你有没有影响，为什么不直接试试呢？

我修改后，自测对目前业务没有影响。想问下大神，会不会有什么潜在的风险？
