### ISSUE TITLE
三方SDK中Activity的Theme问题

### ISSUE THREAD

**Issue by yumdao** [Tencent/Shadow#1127]
``如果我在引用了三方sdk中有Activity并且该Activity有theme的配置，会出现资源索引的问题。

例如：
我在插件工程中引入了BlankJ的工具库，库中有一个activity如下：
![image](https://user-images.githubusercontent.com/93634445/206672472-ea1a3434-b80d-4c4e-b781-6b593730c81b.png)

该Activity在编译生成ActivityInfo时，在处理Theme的时候会拼接包名，
![image](https://user-images.githubusercontent.com/93634445/206673389-d4676dc9-0136-4c25-832d-071641fa0780.png)

编译抛出如下异常：

```
ShadowComponent/app_plugin/build/generated/source/pluginManifest/pluginOfficeTstDebug/com/tencent/shadow/core/manifest_parser/PluginManifest.java:18: 错误: 找不到符号
  new com.tencent.shadow.core.runtime.PluginManifest.ActivityInfo("com.blankj.utilcode.util.UtilsTransActivity", com.shadow.test.plugin.biz.R.style.ActivityTranslucent ,android.content.pm.ActivityInfo.CONFIG_ORIENTATION|android.content.pm.ActivityInfo.CONFIG_KEYBOARD_HIDDEN|android.content.pm.ActivityInfo.CONFIG_SCREEN_SIZE ,android.view.WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN|android.view.WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN)
                                                                                                                                              ^
  符号:   变量 ActivityTranslucent
  位置: 类 style
```

请问针对这样的问题，有什么好的解决方案？

**Comment by yumdao** [comment]
目前我想到的方案是通过配置文件的方式，把三方SDK中的Activity和包名做一个映射，在拼接theme的时候，从通过Activity的className去找配置的包名，从而解决该问题，但这样需要对*PluginManifestGenerator*类进行修改。

**Comment by shifujun** [comment]
就是说PluginManifestGenerator有bug嘛。看起来是aar中的R文件的包名和apk自己的不一样，代码中没考虑到这一点。

你如果自己改不了PluginManifestGenerator，那至少应该能改一下sample复现问题吧？

**Comment by shifujun** [comment]
我自己试了半天也没能复现，又复习了半天这些id生成的流程，所以说没有代码真的是不行。

最后我想了一下，那除非是你开启`nonTransitiveRClass`了，才会在apk模块的R资源缺少lib的资源id。所以试了一下才能复现。

现在也不知道你到底是不是这个原因，因为你完全没提。

**Comment by shifujun** [comment]
如果不是nonTransitiveRClass的原因，提供下复现代码，再打开issue吧。

**Comment by yumdao** [comment]
确实是nonTransitiveRClass问题导致的😭，多谢大佬
