### ISSUE TITLE
两个不同进程之间的插件如何通过AIDL通讯

### ISSUE THREAD

**Issue by changhuai017** [Tencent/Shadow#1137]
插件A在进程a中 拥有服务AService
插件B在进程b中 bindService时如果传入clz传入AService会提示找不到服务，如果使用宿主中的，那如何关联到插件A中的服务呢？

**Comment by shifujun** [comment]
处于不同进程的loader没有相互交换数据的设计，因此不同进程的插件没有loader为它们建立连接。

单说一个进程的loader，它有一个对宿主暴露的bindPluginService接口（在PPS上。手机不方便引用代码，你自己搜一下吧。）。通过这个接口，loader可以通过PPS这个真实注册在系统中的service传递插件service的binder，从而实现插件外部代码使用插件service。

因此插件可以先绑定处于另外进程的PPS，然后进而绑定另外进程插件的service就可以了。

注意这里核心问题就是通过PPS的binder传递插件的binder，从而建立跨进程的插件binder。
