### ISSUE TITLE
InstrumentationTransform抛java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by wangyutao** [Tencent/Shadow#1139]
plugin是基于unity3d导出android studio工程
plugin，引用了第三方jar，SaaS_GameAnalytics_Android_SDK_V4.0.61.jar，plugin打包时，报错：
> Task :transformClassesWithShadowTransformForPluginRelease FAILED
InstrumentationTransform处理com.tendcloud.tenddata.game.bi时出错:java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

Execution failed for task ':transformClassesWithShadowTransformForPluginRelease'.
> java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

runtime引入是用的pluginCompileOnly方式

大神帮忙看看呢

**Comment by shifujun** [comment]
数组越界很可能就是shadow的bug了。最好能提供下com.tendcloud.tenddata.game.bi作为测试用例。否则复现不了问题，很难修复。当然我也会review一下代码的。

**Comment by wangyutao** [comment]
感谢您的及时回复，看别的问题单，unity3d不支持，我也试了，一样的错误
那么这个就关闭吧

**Comment by dawn25618** [comment]
> 感谢您的及时回复，看别的问题单，unity3d不支持，我也试了，一样的错误 那么这个就关闭吧

你的unity3d的项目最后解决了吗？怎么解决的？
