### ISSUE TITLE
BasePluginManager 的 deleteInstalledPlugin(String uuid) 方法调用结果总是 false

### ISSUE THREAD

**Issue by Heart-Beats** [Tencent/Shadow#1140]
大佬问题如上描述： 

deleteInstalledPlugin 的调用最终到 `deletePart(InstalledPlugin.Part part)` 这个方法里，方法的定义如下：
```java
    private boolean deletePart(InstalledPlugin.Part part) {
        boolean suc = true;
        if (!part.pluginFile.delete()) {
            suc = false;
        }
        if (part.oDexDir != null) {
            if (!part.oDexDir.delete()) {
                suc = false;
            }
        }
        if (part.libraryDir != null) {
            if (!part.libraryDir.delete()) {
                suc = false;
            }
        }
        return suc;
    }
```
经过调试发现 `part.libraryDir.delete()` 调用失败， 该路径实际如下：
/data/user/0/com.youma.yky/files/ShadowPluginManager/UnpackedPlugin/zxgl-manager/37f91493cc4dfd47d19e2d8b52508e9d/plugin-zxgl-release.zip/zxgl-plugin-release.apk!/lib/armeabi-v7a

实际插件解压后目录如图所示：
![image](https://user-images.githubusercontent.com/33248551/217486203-f5cd9018-d2a4-4ad8-8a24-ddec13afec72.png)

可以看到没有此目录，而且 `oDexDir ` 和 `libraryDir` 都表示为目录， 当目录下有文件时，直接调用 `file.delete()` 也是会失败的，这块逻辑是不是有些问题？

**Comment by wangkai4556** [comment]
java的file.delete不能删除非空文件夹。需要递归删除所有子内容之后再删除。
插件经过多个版本的迭代之后，遗留的so和odex垃圾文件占用大量用户手机空间，会被用户吐槽。
