### ISSUE TITLE
AGP 7.4.1 在引入com.tencent.shadow.plugin插件时报错

### ISSUE THREAD

**Issue by haikun-li** [Tencent/Shadow#1142]
An exception occurred applying plugin request [id: 'com.tencent.shadow.plugin', artifact: 'com.tencent.shadow.core:gradle-plugin:2.2.1']
> Failed to apply plugin 'com.tencent.shadow.plugin'.
   > Could not create an instance of type com.tencent.shadow.core.gradle.extensions.PackagePluginExtension.
      > Could not generate a decorated class for type PackagePluginExtension.
         > org/json/simple/JSONObject

错误的配置：
```
buildscript {
    ext.shadow_version = '2.2.1'
}

plugins {
    id 'com.android.application' version '7.4.1' apply false
    id 'com.android.library' version '7.4.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
    id 'com.tencent.shadow.plugin' version '2.2.1' apply false
}
```
改成7.1.1没有报错
```
buildscript {
    ext.shadow_version = '2.2.1'
}

plugins {
    id 'com.android.application' version '7.1.1' apply false
    id 'com.android.library' version '7.1.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
    id 'com.tencent.shadow.plugin' version '2.2.1' apply false
}
```

**Comment by LaoJiZhang** [comment]
该问题是shadow SDK maven文件pom中没有增加该json-simple相关依赖，低版本AGP引入了其他相关库，包含此依赖，所以正常运行；升级后高版本去除json-simple依赖导致引入插件无法正常使用；2个解决方案:
1、在shadow sdk中编译生成插件版本的pom中增加json-simple相关依赖，具体位置在 shadow/buildScripts/gradle/maven.gradle 文件中增加pom依赖节点
2、在宿主根build文件中增加 classpath json-simple的相关依赖
