### ISSUE TITLE
如何快速启动activity 的一点疑问

### ISSUE THREAD

**Issue by hrraohaohao** [Tencent/Shadow#1144]
现在遇到一个问题。 就是加载插件activity 的时候。 启动速度上第一次有一点慢， 第二次加载就很快了。（相差几百毫秒左右）  但是插件加载完成时间都是差不多的。 起初我比较怀疑应该是插件的activity预加载完事后并没有进行framwork的一系列初始化过程。 但是插件的activity 是通过宿主 PluginDefaultProxyActivity 代理的。 所以应该也是注册好的。 所以这块大家有什么优化的方案吗？
![image](https://user-images.githubusercontent.com/10896050/220021540-29ed26d5-d958-4b67-b3da-a169f228536d.png)

**Comment by shifujun** [comment]
可能是 fb2da721 造成的差异。
