### ISSUE TITLE
gradle升级到7.5报错

### ISSUE THREAD

**Issue by lzou** [Tencent/Shadow#1149]
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.tencent.shadow.core.transform_kit.ClassTransform, unresolved supertypes: com.android.build.api.transform.Transform
    class com.tencent.shadow.core.transform_kit.CodeConverterExtension, unresolved supertypes: javassist.CodeConverter
Adding -Xextended-compiler-checks argument might provide additional information.

本地环境  compileSDK 31  gradle 7.5 无法编译通过，是因为不支持gradle7.5吗？有什么办法解决吗？

**Comment by lzou** [comment]
e: /Users/zoulu/AndroidStudioProjects/QQReader_Android/shadow/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/ClassTransform.kt: (21, 20): Unresolved reference: SdkConstants

e: /Users/zoulu/AndroidStudioProjects/QQReader_Android/shadow/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/ClassTransform.kt: (26, 20): Unresolved reference: utils

e: /Users/zoulu/AndroidStudioProjects/QQReader_Android/shadow/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/ClassTransform.kt: (27, 19): Unresolved reference: common

e: /Users/zoulu/AndroidStudioProjects/QQReader_Android/shadow/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/ClassTransform.kt: (28, 19): Unresolved reference: common

**Comment by shifujun** [comment]
你二次开发不成功为啥来这提issue呢？

还是说你不清楚怎么使用编译好的Java库，只会把sdk代码复制到你的项目里？这种情况可以参考maven sample，再多翻翻gradle官网的教程。
