### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by jeesk** [Tencent/Shadow#1152]
在打包plugin-app 的时候，显示如下错误

* What went wrong:
Execution failed for task ':plugin-app:processPluginDebugResources'.
> 插件需要利用aapt2的修改资源ID前缀的选项使其与宿主不同。
  没有找到--package-id参数。示例：
  aaptOptions {
      additionalParameters "--package-id", "0x7E", "--allow-reserved-package-id"
  }

* What went wrong:
Execution failed for task ':plugin-app:processPluginDebugResources'.
> 插件需要利用aapt2的修改资源ID前缀的选项使其与宿主不同。
  没有找到--package-id参数。示例：
  aaptOptions {
      additionalParameters "--package-id", "0x7E", "--allow-reserved-package-id"
  }

这个怎么解决的？

**Comment by mm46468648** [comment]
同问，我也遇到了，gradle7.1.2版本
