### ISSUE TITLE
不支持AndroidX 

### ISSUE THREAD

**Issue by gaorenwei** [Tencent/Shadow#1163]
业务插件集成androidX后，导航图中的属性在执行任务时都找不到了
编译报错截图：
![image](https://user-images.githubusercontent.com/15045166/229664289-f1c2e2d2-5fbf-4ff6-9829-faf142838456.png)

**导航图 代码：**
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/holo_green_light"
    tools:context="com.constp.busy.plugin.app.demo.activity.Demo1HomeActivity">
    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/nav_host_fragment"
        android:name="androidx.navigation.fragment.NavHostFragment"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"

        app:defaultNavHost="true"
        app:navGraph="@navigation/nav_graph" />
</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by jayyuz** [comment]
看这个报错，和框架没有啥关系

**Comment by shifujun** [comment]
看起来aapt编译期就报错了。除非你说这个构建去掉shadow的gradle插件就能正常编译，才能说明是shadow引入的问题。如果是这样，还需要有个复现问题的例子才好定位问题。

androidx是支持的。

**Comment by luoxiong94** [comment]
> shadow仅仅重写了android Activity和NativieActiivty,用androidX中的Activity组件根本不行！你的壳都不支持！插件中用会编译出错！官方的代码并没有x的demo,如果谁坚持说androidX可以，请提供可运行的DEM O！

引入androidX相关的库就报错，原因是两个库中存在重复的类文件。具体来说，android.support.v4.app.INotificationSideChannel 这个类在两个不同的库中存在，一个是 androidx.core:core:1.8.0，另一个是 com.android.support:support-compat:27.1.1。

去掉v4库后，运行就崩溃，报错
