### ISSUE TITLE
代理activity的内存泄漏问题

### ISSUE THREAD

**Issue by BruceLiuTao** [Tencent/Shadow#1173]
独立编译运行插件没有内存泄漏问题，通过插件启动activity，代理activity发生内存泄漏，请问又遇到过这个问题么

**Comment by BruceLiuTao** [comment]
![image](https://user-images.githubusercontent.com/12950031/231692719-a4182099-211d-42be-9779-3afd08d20852.png)

**Comment by shifujun** [comment]
你这个截图中能看到并不是sample工程。所以要么你在sample中复现一下问题，要么你直接自己分析一下是哪个对象没有释放你的ProxyActivity。
