### ISSUE TITLE
插件gradle版本 和 shadow sdk的gradle版本 不一致报错，知道的同志麻烦告诉一下吧，谢谢

### ISSUE THREAD

**Issue by senda58** [Tencent/Shadow#1174]
我插件的gradle版本是 6.7.1  
集成shadow sdk的版本是7.0.2

这样会报错：

        * What went wrong:
        A problem occurred evaluating project ':coding:get-android-jar'.
        > Failed to apply plugin 'com.android.internal.version-check'.
           > Minimum supported Gradle version is 7.0.2. Current version is 6.7.1. If using the gradle wrapper, try editing the distributionUrl in /Users/senda/Desktop/hzs2/2021/work/android框架/android_big_ecp_plugin/dyFramework/sdk/coding/gradle/wrapper/gradle-wrapper.properties to gradle-7.0.2-all.zip

我不想修改插件的gradle 版本，请问有什么解决办法么

@shifujun

**Comment by senda58** [comment]
@shifujun 能帮忙看看这个问题么？想知道，在不改变插件 gradle 和 AGP版本的情况下 如何兼容shadow SDK 中gradle 与 AGP的版本

**Comment by shifujun** [comment]
你不应该把第三方SDK的构建和你的项目构建混合起来。第三方SDK可能使用更高版本的依赖，但并不代表它完全不兼容低版本的依赖。Shadow对低版本的Gradle和AGP的兼容性体现在这个自动化测试中：
https://github.com/Tencent/Shadow/blob/fb93248e55e8201b021eb0c7900bbd51c578afa2/projects/test/gradle-plugin-agp-compat-test/test.sh#L30-L55

你应该参考https://github.com/Tencent/Shadow/blob/08da57dd53ae76a002a1fa341b170fd469151e68/projects/sample/README.md#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven

**Comment by senda58** [comment]
> 你不应该把第三方SDK的构建和你的项目构建混合起来。第三方SDK可能使用更高版本的依赖，但并不代表它完全不兼容低版本的依赖。Shadow对低版本的Gradle和AGP的兼容性体现在这个自动化测试中：
> 
> https://github.com/Tencent/Shadow/blob/fb93248e55e8201b021eb0c7900bbd51c578afa2/projects/test/gradle-plugin-agp-compat-test/test.sh#L30-L55
> 
> 你应该参考https://github.com/Tencent/Shadow/blob/08da57dd53ae76a002a1fa341b170fd469151e68/projects/sample/README.md#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven

使用maven 依赖确实不会出现这种情况，这是为啥呢？
