### ISSUE TITLE
Linux 环境下 sdk 找不到 apkanalyzer.jar

### ISSUE THREAD

**Issue by LeonWu6** [Tencent/Shadow#1179]
基于下面这个 commit 后，manifest_parser 改为依赖 `apkanalyzer manifest print` 输出的已注入资源id值的manifest。
https://github.com/Tencent/Shadow/commit/a30a15c9755ef6502f8486778188b9ad5b2b4490

但在 Linux 下，高版本的 sdk 找不到 apkanalyzer.jar，只有 android_sdk/tools/bin/apkanalyzer 的 Linux 程序。
所以，在 Linux 下，最新版本 Shadow locateApyanalyzer 这个 task 编译不过。

**Comment by shifujun** [comment]
你应该提供下复现问题的具体环境，比如”高版本的sdk“的具体版本。理想的方式是直接提供一个可以复现问题的Dockerfile。

**Comment by LeonWu6** [comment]
> 你应该提供下复现问题的具体环境，比如”高版本的sdk“的具体版本。理想的方式是直接提供一个可以复现问题的Dockerfile。

Hi shifujun @shifujun 

我们是在 Jenkins 服务器上编译 apk，是Linux环境。
SDK_31,SDK_32,SDK_33 都是没有 apkanalyzer.jar ，只有 sdk/tools/bin/apkanalyzer 的 Linux 程序，不是 jar 包。
Android P 对应的 sdk 就有 apkanalyzer.jar。
我们是公司用的服务器，我无法拿到这个环境的 Dockerfile.

请参考我的截图，感谢！

**Comment by LeonWu6** [comment]
Hi shifujun @shifujun 
我看到你这个 commit 
https://github.com/Tencent/Shadow/commit/d1457e460268dc5672fa8a88a9dee3f80cd28d00

你的代码修改只是在找 apkanalyzer.jar 的同时也找 apkanalyzer-classpath.jar。
但 Linux 环境中，apkanalyzer-classpath.jar 不是一个完整的 jar 包，当你解压 apkanalyzer-classpath.jar 会发现，其中只有
只有 MANIFEST.MF 文件，没有 BinaryXmlParser.class 等文件，就算在 Linux 系统下找到 apkanalyzer-classpath.jar，可以当做 apkanalyzer.jar 使用吗？我想应该不可以吧？

（ 由于我网络限制，上传图片资源到这个贴子异常了，我借 CSDN 网站上传截图，请点击此CSDN链接，查看我上传到CSDN的图片。谢谢！https://blog.csdn.net/xiaoyu_wu/article/details/130277802 ）

**Comment by shifujun** [comment]
希望你试过之后再做出这样否定他人工作的评论。

**Comment by LeonWu6** [comment]
> 希望你试过之后再做出这样否定他人工作的评论。

Hi shifujun @shifujun , 

经自测，可以编译过了，感谢！
