### ISSUE TITLE
请问下有办法可以做到宿主调用插件的动态库方法吗

### ISSUE THREAD

**Issue by act262** [Tencent/Shadow#1180]
当前遇到个问题，我们需要在宿主层去调用插件里面的动态库方法，尝试了在宿主层System.load 插件so 的路径，但是发现宿主和插件是分别加载了两次so, 里面的数据是不通用的。

使用场景：
Unity C# 层使用dllimport 导入so， 在C#层调用so 定义的方法， 
so里面定义的对象是在插件层实例化出来的，通过把对象指针传递给C#

现在只能把插件里面的动态库放到宿主上去，同时给宿主和插件调用，这样就缺少了插件的灵活性了。

**Comment by shifujun** [comment]
如果你理解shadow插件的运行原理，你应该会发现插件里的so对于系统来说就是宿主assets或者运行时下载的so。插件中调用System.loadLibrary时，Shadow只是干预了一下so的查找路径。干预的手段在于设置了插件ClassLoader的lib目录和ApplicationInfo：

https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoader.kt#L44

https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreatePluginApplicationInfoBloc.kt#L21

你可能没有用宿主的ClassLoader加载插件的so，致使它们处于了不同的namespace中。这可能是Android 7.0引入的新机制带来的问题：https://source.android.com/docs/core/permissions/namespaces_libraries?hl=zh-cn

**Comment by act262** [comment]
我尝试过在宿主层去直接load 插件的so, 报错如下 

```
ava.lang.UnsatisfiedLinkError: Shared library "/data/data/com.xx.demo_1/files/ShadowDir/Unpacked/estv-dynamic-manager/lib/arm64-v8a/BBE4A3AE_lib/libcapture.so" already opened by ClassLoader 0x9ab(dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~x5JRXBejv10iOi_iL1gnRg==/com.xx.demo_1-8GRZuZotli2E7UXlNko1Hg==/base.apk"],nativeLibraryDirectories=[/data/app/~~x5JRXBejv10iOi_iL1gnRg==/com.xx.demo_1-8GRZuZotli2E7UXlNko1Hg==/lib/arm64, /data/app/~~x5JRXBejv10iOi_iL1gnRg==/com.xx.demo_1-8GRZuZotli2E7UXlNko1Hg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]); can't open in ClassLoader 0x7fe76adc9c(com.xxx.shadow.core.loader.classloaders.PluginClassLoader[DexPathList[[zip file "/data/user/0/com.xxx.demo_1/files/ShadowDir/Unpacked/xx-dynamic-manager/17b379ff4566d8ab61540bd7f6115902/xx-plugin-local.zip/shadow-app-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.xx.demo_1/files/ShadowDir/Unpacked/estv-dynamic-manager/lib/arm64-v8a/B07D761B_lib, /data/app/~~x5JRXBejv10iOi_iL1gnRg==/com.xx.demo_1-8GRZuZotli2E7UXlNko1Hg==/lib/arm64, /system/lib64, /system_ext/lib64]]])
```


不同的classloader不能重复加载同个动态库

**Comment by act262** [comment]
如果在宿主层load一次插件的so, 插件里面loadLibrary ，会出现两次 JNI_OnLoad

**Comment by shifujun** [comment]
所以你不要在插件中再重复load不就好了么？如果还有问题，建议脱离shadow写一个多classloader加载so的场景实验一下。

这个问题和shadow应该是不相关的。

**Comment by act262** [comment]
插件没有load的情况会出现找不到native方法而奔溃

**Comment by shifujun** [comment]
那我猜这涉及到JNI方法绑定时的namespace也和classloader有关。如果是这样，就不要宿主和插件这种位于不同classloader的类复用相同的so了。把JNI的类和so保持在同一个classloader中，然后提供一套wrapper类，可以跨classloader复用wrapper类。
提供这种对JNI的wrapper封装也不是shadow该解决的问题。

**Comment by act262** [comment]
好的，感谢shifu提供思路，我再尝试下这方面

**Comment by zhuqichao** [comment]
可以定义一套中间接口，宿主调用，插件实现，插件中的so只由插件加载就可以了

**Comment by act262** [comment]
试了定义中间层接口，dlopen 去调用插件so,  但最终和之前的问题一样，宿主加载的so 和插件加载的so 变成两个不同的实例。

我这里的环境是Unity加载so调用, 可能是unity dllimport 只能从宿主层加载到so

**Comment by act262** [comment]
Update：
1. Unity 下， 高版本C#可以设置属性`[SetDllImportResolver](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver)`，设置插件包so 路径即可。
 低版本C# 用`DllImport` 先打开dlopen、dlsym的方式映射符号表，`DllImport` 只能声明常量的地址，所以没法直接用插件的so路径。

2. UE 下， C++直接用`dlopen、dlsym 映射符号表方式。

PS: 由于我的场景是在plugin侧需要调用的System.load的方式加载so, 同时在host 侧也用到了so 方法，需要保证两边加载的so 为同一个实例，这样才能共享全局的数据，所以在dlopen 时需要使用`RTLD_GLOBAL`标记，不然会出现在plugin、host 两边加载不同实例的so。

eg  `dlopen(path, RTLD_LAZY | RTLD_GLOBAL)`

**Comment by idersan** [comment]
> Update：
> 
> 1. Unity 下， 高版本C#可以设置属性`[SetDllImportResolver](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver)`，设置插件包so 路径即可。
>    低版本C# 用`DllImport` 先打开dlopen、dlsym的方式映射符号表，`DllImport` 只能声明常量的地址，所以没法直接用插件的so路径。
> 2. UE 下， C++直接用`dlopen、dlsym 映射符号表方式。
> 
> PS: 由于我的场景是在plugin侧需要调用的System.load的方式加载so, 同时在host 侧也用到了so 方法，需要保证两边加载的so 为同一个实例，这样才能共享全局的数据，所以在dlopen 时需要使用`RTLD_GLOBAL`标记，不然会出现在plugin、host 两边加载不同实例的so。
> 
> eg `dlopen(path, RTLD_LAZY | RTLD_GLOBAL)`

有sample吗？看看哈
