### ISSUE TITLE
改造 shadow SpecificTransform，报错：iL2cpp failed to extract resources (assets/bin/Data/Managed /storage/emulated/O/Android/data/com.tencent.shadow.sample.host/files/ShadowPlugin sample-plugin-app/il2coo

### ISSUE THREAD

**Issue by XJiong** [Tencent/Shadow#1183]
跪求大佬帮忙看下，看看方案是否可行，可行的话，是不是还有哪些点需要适配修改。

1. 背景：同样的Unity插件集成情景，因为 shadow 会把插件里面的 activity 替换成 shadowActivity；
2. 思考：是不是可以针对 unity 包名，在ActivityTransform 里面添加过滤逻辑，如果出现 “com.unity3d.player”包名和需要过滤的类名“GoogleARCoreApi”，就不执行 replaceClassName
3. 修改点：SpecificTransform 类的 filterRefClasses 函数；
![image](https://user-images.githubusercontent.com/14952406/232799910-a233ae51-4a39-4edb-8502-4af8a1a264ef.png)
4. 打包后，在 sample-host 中添加 unity界面运行，报如下错误：
![image](https://user-images.githubusercontent.com/14952406/232800571-7cd23d71-b1c5-4222-8980-6a606eb6d09c.png)
![image](https://user-images.githubusercontent.com/14952406/232800283-8814b266-6949-4e9b-90b7-1d60191f7477.png)

**Comment by XJiong** [comment]
报错
![image](https://user-images.githubusercontent.com/14952406/232803815-95274aec-f8e9-4452-8289-f0688cccb2c0.png)
原因：还是 unity 内部针对资源路径校验，资源复制时报错

**Comment by XJiong** [comment]
@shifujun 大佬你好，就是改造过滤条件后，报了上面 资源拷贝错误，unity的资源我都是集成在 插件工程 内部的，按道理不应该出现这个复制资源报错。（因为我插件独立运行是可以正常跑起来的）。
不知道如何下手

**Comment by shifujun** [comment]
我不理解你的思路。我们不谈原理，只说shadow需要对所有activity进行一定处理。你了解这一点，但却认为对一些activity跳过这个处理可以使它们正常工作。如果跳过是可行的，为什么不跳过所有activity的处理呢？

因此余下的问题可能超出了我的技术能力。

**Comment by XJiong** [comment]
不是认为一些 activity 可以掉过这个处理就可以正常工作哈，跳过的这个类，因为里面有一些 native 方法入参为 activity，插件里面替换为 shadowActivity 的话，so 调用 Java 方法会找不到方法签名，所以才想到单独那个类不进行替换，然后只要 shadowActivity 拥有 activity 的能力，应该就是可以跑起来的。（当然都是基于这个理论的猜测）
![image](https://user-images.githubusercontent.com/14952406/233557547-623ebdf6-d99b-4d97-a420-5ca7ec9022a5.png)
