### ISSUE TITLE
以maven方式集成后出现 Plugin [id: 'com.tencent.shadow.plugin'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by senda58** [Tencent/Shadow#1185]
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/111741815/233878919-fa1e1704-6880-43ac-92bd-42bbceed6934.png">

我是使用的本地仓库：build.gradle文件如下：

       buildscript {
          repositories {
              if (!System.getenv().containsKey("DISABLE_TENCENT_MAVEN_MIRROR")) {
                  maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
              } else {
                  google()
                  mavenCentral()
              }
              mavenLocal()
          }
      
          dependencies {
              classpath "com.tencent.shadow.core:gradle-plugin:$dyFramework_version"
          }
      }
      
      plugins {
          id 'com.android.application'
          id 'com.tencent.shadow.plugin' //引用腾讯shadow插件
      }
      
      android {
          compileSdk project.COMPILE_SDK_VERSION
      
          defaultConfig {
              applicationId "com.cop.ronghw.plugin2-maven"
              minSdk 21
              targetSdk 32
              versionCode 1
              versionName "1.0"
      
              testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
          }
      
          flavorDimensions(*flavorDimensionList)
          buildTypes {
              release {
                  minifyEnabled true
                  proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
              }
      
          }
          compileOptions {
              sourceCompatibility JavaVersion.VERSION_1_8
              targetCompatibility JavaVersion.VERSION_1_8
          }
      
      
      // 将插件applicationId设置为和宿主相同
          productFlavors {
              plugin {
                  applicationId 'com.cop.ronghw.app'
              }
          }
      
          lintOptions {
              abortOnError false
          }
      
          // 将插件的资源ID分区改为和宿主0x7F不同的值
          aaptOptions {
              additionalParameters "--package-id", "0x7E", "--allow-reserved-package-id"
          }
      
      }
      
      dependencies {
          implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
          implementation 'androidx.appcompat:appcompat:1.3.0'
          implementation 'com.google.android.material:material:1.4.0'
          testImplementation 'junit:junit:4.13.2'
          androidTestImplementation 'androidx.test.ext:junit:1.1.3'
          androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
      
      
          //Shadow Transform后业务代码会有一部分实际引用runtime中的类
          //如果不以compileOnly方式依赖，会导致其他Transform或者Proguard找不到这些类
          pluginCompileOnly "com.tencent.shadow.core:runtime:$dyFramework_version"
      
      }
      
      shadow {
          packagePlugin {
              pluginTypes {
                  debug {
                      loaderApkConfig = new Tuple2('plugin-loader-debug.apk', ':plugin-loader:assembleDebug')
                      runtimeApkConfig = new Tuple2('plugin-runtime-debug.apk', ':plugin-runtime:assembleDebug')
      
                      // 打包的apk
                      pluginApks {
                          pluginApk1 {
                              businessName = 'plugin-maven-2'
                              partKey = 'plugin-maven-2'
                              buildTask = ':app:assemblePluginDebug'
                              apkPath = 'app/build/outputs/apk/plugin/debug/app-plugin-debug.apk'
                          }
                      }
                  }
              }
      
              loaderApkProjectPath = 'plugin-loader'
              runtimeApkProjectPath = 'plugin-runtime'
      
              archiveSuffix = System.getenv("PluginSuffix") ?: ""
              archivePrefix = 'plugin'
              destinationDir = "${getRootProject().getBuildDir()}"
              version = 5
              compactVersion = [1, 2, 3,4]
              uuidNickName = "1.1.5"
          }
      }

**Comment by senda58** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/111741815/233898432-87b1cb75-9b87-4699-b763-a7d917592401.png">

**Comment by shifujun** [comment]
`$dyFramework_version`就是你自己写的吧？那不就是吗？而且你这个问题完全就是gradle的使用问题，不应该来shadow提issue的。

**Comment by senda58** [comment]
是的，新手，还请谅解
