### ISSUE TITLE
部分机型上Monkey测试报出ShadowPackageItemInfo.loadXmlMetaData中的NPE异常

### ISSUE THREAD

**Issue by laizhiren19940409** [Tencent/Shadow#1190]
crash:
// CRASH: com.cn.xm.opert:plugin (pid 16478) (dump time: 2023-04-25 14:37:17
// Version: 
// Long Msg: java.lang.RuntimeException: partKey==ivliu-plugin className==com.cn.xm.opert.ivliu.LFileProvider authorities==com.cn.xm.opert.ivliu.fileProvider
// 	at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.createContentProviderAndCallOnCreate(PluginContentProviderManager.kt:110)
// 	at com.tencent.shadow.core.loader.ShadowPluginLoader.callApplicationOnCreate$realAction(ShadowPluginLoader.kt:121)
// 	at com.tencent.shadow.core.loader.ShadowPluginLoader.access$callApplicationOnCreate$realAction(ShadowPluginLoader.kt:43)
// 	at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$1.run(ShadowPluginLoader.kt:132)
// 	at android.os.Handler.handleCallback(Handler.java:938)
// 	at android.os.Handler.dispatchMessage(Handler.java:99)
// 	at android.os.Looper.loopOnce(Looper.java:211)
// 	at android.os.Looper.loop(Looper.java:300)
// 	at android.app.ActivityThread.main(ActivityThread.java:8285)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
// Caused by: java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference
// 	at com.tencent.shadow.core.runtime.ShadowPackageItemInfo.loadXmlMetaData(ShadowPackageItemInfo.java:38)
// 	at android.support.v4.content.FileProvider.loadXmlMetaData_shadow(Unknown Source:6)
// 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:605)
// 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:579)
// 	at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:392)
// 	at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.createContentProviderAndCallOnCreate(PluginContentProviderManager.kt:107)
// 	... 11 more
// crashend

**Comment by shifujun** [comment]
`ShadowPackageItemInfo.loadXmlMetaData`是`PackageItemInfoTransform`对`loadXmlMetaData`方法调用的一个转调处理。
因此你贴出的NPE中的null对象应该是原本就会出现NPE的`loadXmlMetaData`方法调用。因此`ShadowPackageItemInfo.loadXmlMetaData`中不需要对传入的`packageItemInfo`判空。

`FileProvider`在sample中有测试代码，也很早就被很多业务使用过，不太可能会在其`attachInfo`这个主路径中出错。

如果反馈`com.cn.xm.opert.ivliu.LFileProvider`的问题，应该在fork后在sample中提供它的实现来复现问题。

**Comment by laizhiren19940409** [comment]
那按照你的意思是，问题应该出现在LFileProvider中调用到了父类FileProvider.getUriForFile→getPathStrategy→parsePathStrategy
<img width="917" alt="image" src="https://user-images.githubusercontent.com/10131669/234216827-45f613ac-223e-465b-baf6-f07bef68feef.png">
这里的info是null？？是这个意思吗？？
主要是这个崩溃堆栈开始看着有点懵定位不到具体崩溃位置，这个也没有100%复现出来只是Money测试收集到的信息，所以想咨询一下这个堆栈怎么追踪定位崩溃位置
