### ISSUE TITLE
关于插件升级问题

### ISSUE THREAD

**Issue by 8492ll** [Tencent/Shadow#1198]
Shadow框架我已经成功集成并且调用成功，但是我搞不懂插件要如何升级？
issues中我也看了几个关于升级插件的，这边的需求没有这么复杂，只用到了一个插件，只要能做到插件升级即可
我目前知道的在App当中需要加入manage.apk 以及 plugin.zip
传统的升级思路：
下载文件并更新原有的文件即可
疑问：
我更新插件时，manage和plugin两个文件都需要重新下载升级？
我如何在主工程app当中获取plugin的版本号？用于对比本地插件是否需要升级
由于在app当中读取manage.apk路径以及名称都是是写死的，当我下载到新的manage是直接替换掉原有的manage？
还有就是是否有提供已经封装好的方法直接替换下载好的manage和plugin？

如果我的思路不正确，是否能帮忙调整？

**Comment by wh963572516** [comment]
manager.apk这个是不要去弄成动态的，你把它和宿主工程放在同一个项目中，当它构建出来时，你把它自动拷贝到宿主的assets目录下，然后在运行宿主时把它放到某个目录中（app或者sd卡中）。
只有插件apk的信息是动态的，这个需要动态下载，你在宿主调用时，通过bundle传动态的值。
