### ISSUE TITLE
可以直接加载第三方apk吗？

### ISSUE THREAD

**Issue by bhui** [Tencent/Shadow#12]
rt。还是说加载的模块必须依赖于shadow编译出来？

**Comment by shifujun** [comment]
这要看第三方apk是如何加载的。

如果是说拿一个应用市场上下载的、可以正常安装的apk作为“第三方apk”，那么不可以直接加载。必须是Shadow编译出来的。Shadow会在编译时插入Transform过程，修改应用的字节码，插入Shadow中间层。

如果是说通过另外一个其他的插件框架加载它原本可以支持的apk，那还是有可能支持的。我没有尝试过。但是可以这样理解，Shadow只是将宿主的一部分代码动态化了，插件代码相当于宿主代码的一部分。所以其他插件框架接入宿主还是接入Shadow插件中，其实是没区别的。

**Comment by GaoZhenGit** [comment]
哈哈，能直接加载第三方apk的话，估计就只有vitrual apk了

**Comment by onelittlebear** [comment]
> 哈哈，能直接加载第三方apk的话，估计就只有vitrual apk了

滴滴开源的vitrual apk可以加载第三方apk吗？看他的wiki说建议用回360的droidplugin
