### ISSUE TITLE
插件使用raw文件无法正常读取到资源

### ISSUE THREAD

**Issue by lgz1113** [Tencent/Shadow#1201]
大大，麻烦看下，插件项目中有使用raw里头的资源，在使用  Uri.parse("android.resource://" + getPackageName() + "/" + R.raw.xx);
   之后，一直报无法找到这个资源导致插件异常，独立的apk安装是正常的，请问这个怎么处理。[
![pic1](https://github.com/Tencent/Shadow/assets/136774902/3e19b014-abd2-41df-b8dd-1ba145e620ba)
](url)
[
![pic2](https://github.com/Tencent/Shadow/assets/136774902/ae2e186c-1edd-4e10-8a23-bbbed8844c81)
](url)

**Comment by shifujun** [comment]
看起来就是直接把插件的资源id交给系统类Imageview了。那么系统类肯定不会找到插件的apk在哪的。所以不能正常工作是好理解的。

我估计要支持这种场景还是需要hook这种用法，转调成从插件自己的resource对象先取出资源再交给系统类吧。

你可以试着实现一下，或者至少写出来比较完整的测试用例，我可以一起看一下怎么hook更合理。

**Comment by lgz1113** [comment]
您好，您的邮件我已收到，现在无法亲自回复您的邮件。但过后我会尽快给您回复。

**Comment by lgz1113** [comment]
您好，您的邮件我已收到，现在无法亲自回复您的邮件。但过后我会尽快给您回复。
