### ISSUE TITLE
插件加载宿主的Dialog时，无法加载inflate布局

### ISSUE THREAD

**Issue by Zjoke08** [Tencent/Shadow#1204]
API 版本22。
复现场景如下：
在sample-host-lib中新增 MDialog 。其布局使用 host_ui_layer_layout，在host_ui_layer_layout中根布局增加backround为drawable的。
示例代码如下：
```
public class MDialog extends Dialog {
    public MDialog(Context context) {
        super(context);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.host_ui_layer_layout);
    }
}
```

res/layout/host_ui_layer_layout内容

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:background="@drawable/bg_layout_a"
    android:layout_height="match_parent"
    android:layout_width="match_parent">

    <TextView
        android:id="@+id/textView"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:layout_width="wrap_content"
        android:text="Host UI Layer"
        android:textColor="@android:color/holo_red_dark" />
</LinearLayout>
```

res/drawable/bg_layout_a内容

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#00FF00" />

</shape>
```

在插件中调用new MDialog().show()。经过测试和断点，主要原因为这个drawble资源无法获取到。LayoutInflate.inflate时使用的Context是ShadowContext。
这个情况怎么处理？

**Comment by shifujun** [comment]
dialog或者其他view，如果是宿主提供的，它所需的资源也在宿主中，就应该让宿主inflate出来再交给插件使用。

要注意宿主和插件的多对多版本关系。如果不是通过稳定的Java接口相互调用，比如在插件中直接访问宿主的资源。那么可能在宿主的不同版本中这个资源就发生变化了。对于xml中依赖的资源id来说，就更不稳定了。所以插件inflate宿主的view在多对多版本模型下是不可行的。

**Comment by Zjoke08** [comment]
dialog的layout以及其中的drawable均是宿主的。插件中仅调用了dialog.show()。Layout的Inflate是宿主创建的，并且能够创建成功，但是其宿主的Layout中如果使用了宿主的drawable，则会Resources$NotFoundException。
总结就是
宿主：
MDialog、Layout、Drawable。
插件：
仅调用new MDialog(ShadowContext).show()

按照你的说法，我需要单独实现一个接口，该接口调用宿主的弹窗创建能力？但是我的Context使用容器的Context还是哪个？

另外，我有一点不明白的是，Mdialog的Layout我能正确infalte成功（如果布局里面不设置宿主的Drawable），但是加上宿主的Drawable就失败。Drawable只是示例，dimen也是一样的问题。
