### ISSUE TITLE
手Q相关提交的疑问

### ISSUE THREAD

**Issue by Invincibl-e** [Tencent/Shadow#1209]
https://github.com/Tencent/Shadow/commit/6783f4e533ecb027b97546d66146a03c2f11f1d3

发现了一个这个 commit 如果外部程序调用 app 出现非法，会直接把当前进程杀掉，这个 commit 是不是除了手 Q，其他程序并没有这个需求呢？

**Comment by shifujun** [comment]
那个提交注释不够规范，这个逻辑不是只适用于手Q的。

你可以注意下isIllegalIntent方法的注释。这是当时的分析记录，重点在于这种非法情况可能不是人为攻击产生的。升级Loader和旧版本的PendingIntent可能是无法解决的场景。

由于已经加载的类没法卸载，所以只好退出进程使所有状态恢复到预期情况，

如果你去掉这个退出进程的调用，未来遇到这种比较小概率复现的问题可能会比较难定位。这样做的话建议多加log。

**Comment by Invincibl-e** [comment]
大概理解您的意思了，如果更新的时候完全退出其实是不会遇到这个问题的。
我是通过 Intent 获取回调其他 App 的结果时刚好遇到了，如果二次点击 Intent 链接会直接导致插件进程全部退出，然后就定为到这里了
