### ISSUE TITLE
Publish to maven with source

### ISSUE THREAD

**Issue by boyan01** [Tencent/Shadow#121]
发现 `./gradlew publish` 只会将编译的产物发布到 maven 库中。

**能不能考虑一下将源文件也一并打包发布过去呢。**

java 字节码还能通过 IDE 反编译来查看实现细节， 但 kotlin 的字节码简直就没法看了。

**Comment by liupeng110** [comment]
kotlin的那个实现能不能换成java的,谁用kotlin自己转一下  java转kotlin方便

**Comment by boyan01** [comment]
> kotlin的那个实现能不能换成java的,谁用kotlin自己转一下 java转kotlin方便

为啥要把 Kotlin 的实现换成 java 的？既然会 java ，那么学习 kotlin 不是很容易吗？
