### ISSUE TITLE
关于再业务模块集成com.tencent.shadow.plugin的问题

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1210]
问题一：找不到怎么办？
`buildscript {
    repositories {
        maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
    }
    dependencies {
        classpath "com.tencent.shadow.core:gradle-plugin:1.0"
        classpath 'com.tencent.shadow.coding:aar-to-jar-plugin'
        classpath 'com.tencent.shadow.coding:common-jar-settings'
    }
}`
错误提示：
`ould not resolve all files for configuration ':classpath'.
   > Could not find com.tencent.shadow.coding:aar-to-jar-plugin:.
     Required by:
         project :
   > Could not find com.tencent.shadow.coding:common-jar-settings:.
     Required by:
         project :
`
问题二：还有再集成shadow插件的时候也会找不到
`buildscript {
    repositories {
        maven { setUrl("https://localhost:9224/repository/casic_group/") }
        maven { setUrl("https://mirrors.tencent.com/nexus/repository/maven-public/") }
        google()
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath "com.tencent.shadow.core:runtime:1.0"
        classpath "com.tencent.shadow.core:activity-container:1.0"
        classpath "com.tencent.shadow.core:gradle-plugin:1.0"
        classpath "org.javassist:javassist:3.28.0-GA"
    }
}
apply plugin: 'com.android.application'
apply plugin: 'com.tencent.shadow.plugin'
`
错误提示： Failed to apply plugin 'com.tencent.shadow.plugin'.

**Comment by EmptyPages** [comment]
是否有人可以留个联系方式帮忙看看，这个相关资料实在太少了

**Comment by shifujun** [comment]
参考maven sample向业务工程引入shadow。这其实是普通的gradle使用问题，没有具体的工程配置，没法知道你哪写错了。
