### ISSUE TITLE
PluginContainerActivity: DelegateProviderHolder没有初始化

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1218]
![image](https://github.com/Tencent/Shadow/assets/22334853/a39598e4-7bfb-43f2-8a13-05ce08c748e6)

**Comment by steven-gao** [comment]
i  was set "minifyEnabled true" and "shrinkResources true"  in plugin module gradle.This error occured.who can help me?

**Comment by steven-gao** [comment]
@EmptyPages how did you to make it run successfuly?

**Comment by EmptyPages** [comment]
> @EmptyPages how did you to make it run successfuly?yes ,I make it successful,but it is long time ago, I cant remeber it
