### ISSUE TITLE
从宿主Activity打开插件Actvity后，当关闭插件Actvity后，无法正常返回上一个宿主Actvity，直接返回到了桌面

### ISSUE THREAD

**Issue by itxiaox** [Tencent/Shadow#1220]
1. 从宿主界面MyActivity 打开插件Activty: PluginDefaultProxyActivity
Line 65:          #0 ActivityRecord{a06e7e2 u0 **com.example.sdk.demo/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity** t503} type=standard mode=fullscreen override-mode=undefined requested-bounds=[0,0][0,0] bounds=[0,0][1088,2400]
Line 67:          #0 ActivityRecord{65738f5 u0 **com.example.sdk.demo/.MyActivity** t503} type=standard mode=fullscreen override-mode=undefined requested-bounds=[0,0][0,0] bounds=[0,0][1088,2400]
Line 71:           #0 ActivityRecord{4a04a12 u0 com.huawei.android.launcher/.unihome.UniHomeLauncher t83} type=home mode=fullscreen override-mode=undefined requested-bounds=[0,0][0,0] bounds=[0,0][1088,2400]
2. 关闭插件界面，直接返回了桌面，返回栈出现了问题
Line 66:           #0 ActivityRecord{4a04a12 u0 com.huawei.android.launcher/.unihome.UniHomeLauncher t83} type=home mode=fullscreen override-mode=undefined requested-bounds=[0,0][0,0] bounds=[0,0][1088,2400]
Line 75:          #0 ActivityRecord{65738f5 u0 **com.example.sdk.demo/.MyActivity** t503} type=standard mode=fullscreen override-mode=undefined requested-bounds=[0,0][0,0] bounds=[0,0][1088,2400]

根据返回栈返回栈来看，不知道为什么UniHomeLauncher 出现到栈顶了，正常预期应该是MyActvity出现栈顶

**Comment by GrapefruitBrother** [comment]
我也遇到了 但不是必现的。
