### ISSUE TITLE
com.tencent.shadow.core.runtime.ShadowActivity中缺少方法

### ISSUE THREAD

**Issue by supeijin** [Tencent/Shadow#1223]
Class com.tencent.shadow.core.runtime.ShadowActivity中缺少方法:
getOnBackInvokedDispatcher:()Landroid/window/OnBackInvokedDispatcher;被这些类调用了:
androidx.appcompat.app.AppCompatDelegateImpl$Api33Impl
androidx.activity.ComponentActivity$Api33Impl
isLaunchedFromBubble:()Z被这些类调用了:
androidx.core.app.ActivityCompat$Api31Impl

**Comment by luoxiong94** [comment]
因为你 compileSdkVersion 调整成了33 ，这2个方法是33才有的方法，改成31 就可以了
