### ISSUE TITLE
宿主中公用代码和资源(base工程)，怎样在Shadow下进行动态化修复和更新

### ISSUE THREAD

**Issue by huanle19891345** [Tencent/Shadow#123]
对于项目的基础模块，如network，base等公共模块，插件和宿主都需要依赖它，通过Shadow的writeList进行控制时，公共模块会被打包在宿主中(插件是compileOnly)，这样就失去了这些公共模块的动态修复和更新能力，想请教一下怎样拥有这部分的能力，谢谢

**Comment by huanle19891345** [comment]
非常感谢回复，我理解具体做法了
之前我对这个问题的想法是(宿主中的公共代码和资源的更新和修复可行性方案)
方案1：利用热修复方案如Tinker中的java修复部分替换宿主dex elements(atlas的host更新也使用的类似修复方案)，资源更新也采用相应的热修复方式进行
方案2：将公共代码和资源从组件做成插件，动态加载

现在看来您推荐的是方案2，在Shadow的场景下我也很赞同这个方向，因为方案1从开发维护角度来说有额外的技术成本(技术路线差别较大),且稳定性也没法保证

如果选择方案2，那需要优化的方向就是插件的安装和加载速度，因为每个基础仓库都可能要作为插件被动态加载，这个耗时就非常关键了，dex2oat过程应该是其中重要的因素，后续我会考虑参考atlas的优化方向:
"在ART系统上首次使用时关闭了dex2oat走解释执行。同时后台通过异步任务走原生的dexopt过程，为下次使用做好准备"
进行相关优化，也希望能多多学习交流，感谢

**Comment by huanle19891345** [comment]
继续请教一下这个问题，项目中存在比较多的基础公共库，且有比较复杂的依赖关系，这种情况都做成插件的可行性不高，请问您对此类问题是怎样处理的呢，谢谢，我感觉动态更新基础公共库是很多项目都会面临的问题

**Comment by guok2046** [comment]
> 非常感谢回复，我理解具体做法了
> 之前我对这个问题的想法是(宿主中的公共代码和资源的更新和修复可行性方案)
> 方案1：利用热修复方案如Tinker中的java修复部分替换宿主dex elements(atlas的host更新也使用的类似修复方案)，资源更新也采用相应的热修复方式进行
> 方案2：将公共代码和资源从组件做成插件，动态加载
> 
> 现在看来您推荐的是方案2，在Shadow的场景下我也很赞同这个方向，因为方案1从开发维护角度来说有额外的技术成本(技术路线差别较大),且稳定性也没法保证
> 
> 如果选择方案2，那需要优化的方向就是插件的安装和加载速度，因为每个基础仓库都可能要作为插件被动态加载，这个耗时就非常关键了，dex2oat过程应该是其中重要的因素，后续我会考虑参考atlas的优化方向:
> "在ART系统上首次使用时关闭了dex2oat走解释执行。同时后台通过异步任务走原生的dexopt过程，为下次使用做好准备"
> 进行相关优化，也希望能多多学习交流，感谢

在ART系统上关闭dex2opt，目前只在5.0-7.0上有效果，8.0及以上Android系统已经优化了dex2oat逻辑，耗时也变得可以接受

**Comment by guok2046** [comment]
> 继续请教一下这个问题，项目中存在比较多的基础公共库，且有比较复杂的依赖关系，这种情况都做成插件的可行性不高，请问您对此类问题是怎样处理的呢，谢谢，我感觉动态更新基础公共库是很多项目都会面临的问题

这里提到的需求叫做动态更新，那显然使用动态加载技术是最合适的。可以定义抽象出公共库的接口，宿主本身一套实现，插件也实现对应接口，当下载到插件后，就使用插件的实现

**Comment by huanle19891345** [comment]
感谢回复，我明白这个问题的处理方向了
