### ISSUE TITLE
为什么plugin-debug.zip中没有生成activity类啊

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1233]
这个插件app里就写了个空的MainActivity，其他没写，就是做个示例嘛，功能都正常为什么dex文件里面MainActivity都没有，是我找错地方了吗？
![image](https://github.com/Tencent/Shadow/assets/22334853/c87a0627-4deb-44b1-851e-a82b3d297555)
![1](https://github.com/Tencent/Shadow/assets/22334853/23db9e69-eb28-4c80-a1da-1362ed014dab)

**Comment by shifujun** [comment]
那不还有`classes2.dex`和`classes3.dex`么？

https://developer.android.com/studio/build/multidex?hl=zh-cn#mdex-on-l

**Comment by EmptyPages** [comment]
> 那不还有`classes2.dex`和`classes3.dex`么？
> 
> https://developer.android.com/studio/build/multidex?hl=zh-cn#mdex-on-l

classes.dex2里有mainActivity但是是修改前的，修改后继承shadowActivity的没找到，我找错目录了吗
![image](https://github.com/Tencent/Shadow/assets/22334853/98fe42ea-5bc7-4a23-beea-00546ece1c45)
![image](https://github.com/Tencent/Shadow/assets/22334853/c0e11f5b-59e9-467c-b88d-1f944670c193)

**Comment by shifujun** [comment]
要把Activity的子类都改成ShadowActivity的子类，需要把所有Activity的子类的父类都改掉吗？继承难道不是传递的吗？

**Comment by EmptyPages** [comment]
> 要把Activity的子类都改成ShadowActivity的子类，需要把所有Activity的子类的父类都改掉吗？继承难道不是传递的吗？

不是啊，shadow再启动插件的时候不是会把插件的apk重新修改让原来继承的Android系统的AppCompatActivity改为继承ShadowActivity的普通类吗，然后加载插件的这个Activity呀，我是想看这个Activity修改后的这个类

**Comment by EmptyPages** [comment]
> 不是啊，shadow再启动插件的时候不是会把插件的apk重新修改让原来继承的Android系统的AppCompatActivity改为继承ShadowActivity的普通类吗，然后加载插件的这个Activity呀，我是想看这个Activity修改后的这个类

哦哦，我知道了他不是修改了MainActivity而是修改了最上层的androidx.core.app.ComponentActivity，感谢感谢，我懂了
