### ISSUE TITLE
为什么四大组件只有Activity需要再xml中注册代理Activity，其他三个为什么不需要

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1234]
shadow实际不就是吧插件中的Activity替换继承ShadowActivity成为一个普通类吗，然后复刻到真正的ContainerActivity中运行吗？那为什么runtime中没有广播、service、contentprovider的代理类呢？他们怎么实现AndroidManifest.xml中的注册问题的

**Comment by shifujun** [comment]
既然Android要求“四大组件”需要在Manifest中注册，那我们就不可能合法的跳过这一限制。我们能做的就是重新审视App自身对这“四大组件”的需求。比如App内部跳转的不同Activity真的需要是不同的Activity吗？对于Shadow适用的App来说，答案就是否定的。这些App中的多数Activity除了类名，在Manifest中注册的信息是完全一样的。所以它们可以被自动重构为一个ContainerActivity，由它持有原本的AppActivity。把ContainerActivity和Android系统的交互委托给AppActivity。这样多个AppActivity就可以复用同一个Manifest中注册的ContainerActivity了。

假如一个App中的多个Activity是针对不同其他App提供的程序入口，在Manifest中注册时有不同的属性，比如不同的Intent filter、键盘特性、横竖屏、悬浮窗等等。那么这些Activity就肯定无法重构共用同一个ContainerActivity。这种就不适合使用Shadow或同类插件技术。

Manifest中的属性有些是可以在运行时重新设置的，比如背景颜色如果在Manifest里设置为透明的。运行时就可以动态改为不透明的。反之不可以。那ContainerActivity注册为透明的就可以适用于透明和不透明的所有AppActivity。

所以要提前在宿主中注册好足够插件使用的、不可动态更新的Manifest信息。

上面讲的虽然是以Activity为例的，但实际上并没有什么特殊性。Manifest里注册的组件都只能这样合法的动态化它们的行为。只是“四大组件”中以Activity最为常用和复杂。其余组件是如何工作的，你调试一下就能理解了。

**Comment by EmptyPages** [comment]
> 既然Android要求“四大组件”需要在Manifest中注册，那我们就不可能合法的跳过这一限制。我们能做的就是重新审视App自身对这“四大组件”的需求。比如App内部跳转的不同Activity真的需要是不同的Activity吗？对于Shadow适用的App来说，答案就是否定的。这些App中的多数Activity除了类名，在Manifest中注册的信息是完全一样的。所以它们可以被自动重构为一个ContainerActivity，由它持有原本的AppActivity。把ContainerActivity和Android系统的交互委托给AppActivity。这样多个AppActivity就可以复用同一个Manifest中注册的ContainerActivity了。
> 
> 假如一个App中的多个Activity是针对不同其他App提供的程序入口，在Manifest中注册时有不同的属性，比如不同的Intent filter、键盘特性、横竖屏、悬浮窗等等。那么这些Activity就肯定无法重构共用同一个ContainerActivity。这种就不适合使用Shadow或同类插件技术。
> 
> Manifest中的属性有些是可以在运行时重新设置的，比如背景颜色如果在Manifest里设置为透明的。运行时就可以动态改为不透明的。反之不可以。那ContainerActivity注册为透明的就可以适用于透明和不透明的所有AppActivity。
> 
> 所以要提前在宿主中注册好足够插件使用的、不可动态更新的Manifest信息。
> 
> 上面讲的虽然是以Activity为例的，但实际上并没有什么特殊性。Manifest里注册的组件都只能这样合法的动态化它们的行为。只是“四大组件”中以Activity最为常用和复杂。其余组件是如何工作的，你调试一下就能理解了。

懂了，Service广播等都是通过动态注册去实现的同样也是替换父类的方式

**Comment by EmptyPages** [comment]
> 既然Android要求“四大组件”需要在Manifest中注册，那我们就不可能合法的跳过这一限制。我们能做的就是重新审视App自身对这“四大组件”的需求。比如App内部跳转的不同Activity真的需要是不同的Activity吗？对于Shadow适用的App来说，答案就是否定的。这些App中的多数Activity除了类名，在Manifest中注册的信息是完全一样的。所以它们可以被自动重构为一个ContainerActivity，由它持有原本的AppActivity。把ContainerActivity和Android系统的交互委托给AppActivity。这样多个AppActivity就可以复用同一个Manifest中注册的ContainerActivity了。
> 
> 假如一个App中的多个Activity是针对不同其他App提供的程序入口，在Manifest中注册时有不同的属性，比如不同的Intent filter、键盘特性、横竖屏、悬浮窗等等。那么这些Activity就肯定无法重构共用同一个ContainerActivity。这种就不适合使用Shadow或同类插件技术。
> 
> Manifest中的属性有些是可以在运行时重新设置的，比如背景颜色如果在Manifest里设置为透明的。运行时就可以动态改为不透明的。反之不可以。那ContainerActivity注册为透明的就可以适用于透明和不透明的所有AppActivity。
> 
> 所以要提前在宿主中注册好足够插件使用的、不可动态更新的Manifest信息。
> 
> 上面讲的虽然是以Activity为例的，但实际上并没有什么特殊性。Manifest里注册的组件都只能这样合法的动态化它们的行为。只是“四大组件”中以Activity最为常用和复杂。其余组件是如何工作的，你调试一下就能理解了。

您好，我还有个小小的疑问，关于ContainerActivity代理壳子为什么要放在单独的module中，是不是为了动态化，假如有比较复杂的场景而shadow源码中没有复刻到的一些方法就可以通过修改runtime中的ContainerActivity的方法去实现，这样可以不修改宿主代码，是这个原因吗，我理解的对不对

**Comment by shifujun** [comment]
DynamicRuntime类做的这部分动态化。这些壳子的动态化主要是为了减少合入宿主dex的方法数增量。这些壳子的代码更新频率并不高，因为主要是根据CompileSDK中的对应系统类Activity的方法自动生成的代码，所以一般是全的，不需要经常更新。

**Comment by EmptyPages** [comment]
懂了谢谢
