### ISSUE TITLE
manager会将插件解压“安装”到宿主目录下，这个目录地址是多少呀，就是博客上提到的这个地址

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1239]
![image](https://github.com/Tencent/Shadow/assets/22334853/42552e23-28b7-4670-bff8-b6a45ba9b147)

**Comment by SunnyLy** [comment]
/data/data/xxx.xxx..pluginclub/files/ShadowPluginManager/UnpackedPlugin/
