### ISSUE TITLE
PluginClassLoader 为什么要设置成默认不能访问宿主类呢？

### ISSUE THREAD

**Issue by boyan01** [Tencent/Shadow#124]
发现插件是默认无法访问宿主的类的，想问一下这是出于什么样的考虑呢？

如果说是 Shadow 的目标是把宿主当做“系统”、插件当做”应用”，那么 “应用” 不是应该默认能访问 “系统” 中的类吗？

**Comment by shifujun** [comment]
在我们的业务需求中，插件和宿主的版本是多对多的关系的。插件直接访问宿主的类没什么用，访问的类随时可能因为宿主版本更新就不见了。

还有就是类冲突的问题，也会因为多对多的版本关系变得不可控。

多对多的版本关系的好处是宿主和插件的发布节奏可以相互独立，谁都不用考虑谁。

**Comment by boyan01** [comment]
理想情况是宿主和插件完全解耦。大公司中可能各个组件的负责的团队不同，于是各组件对宿主的依赖较少，可以做到宿主和插件独立。

但对于很多非大公司的组件化项目来说，各个组件无论是 resource 还是 class 都几乎完全依赖于宿主（lib）。那么这些项目如果想使用 Shadow 作为插件化框架，可能就会非常的麻烦。

但毕竟没有一种框架能够解决所有问题，Shadow 也能出色的达成自己的需求。

哈哈，感觉你的解答，也感谢腾讯能够开源这个项目。（感觉在使用的过程中学到了很多东西~
