### ISSUE TITLE
想咨询一下插件更新和新增逻辑

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1240]
假如初次下载插件后是这样的，有个plugin-debug.zip包，如果是正式发布的肯定是release啊，这个不重要了，只是咨询逻辑
![image](https://github.com/Tencent/Shadow/assets/22334853/57877228-42ba-486e-9e92-a95a916901a5)
1、那么下次如果我更新这个plugin-app-plugin-debug.apk这个插件是重新打包一个plugin-debug2.zip包吗？然后删除本地原来的plugin-debug.zip?
2、如果我想新增一个插件呢？plugin-debug3.zip,那么zip3中不用包含前两个插件了吧，还有就是zip3里的也要包含loader和runtime吗？
3、我如何判断一个插件包是否需要更新，是判断config.json中的UUID是否有变化吗？

**Comment by EmptyPages** [comment]
或者说我新增插件都是解压plugin-debug.zip,然后放入新的插件，然后更新config.json,再重新压缩？？？

**Comment by EmptyPages** [comment]
@shifujun 求告知一个更新插件和新增插件的逻辑

**Comment by liouyang** [comment]
我也想问这个问题，楼主有答案吗

**Comment by EmptyPages** [comment]
> 我也想问这个问题，楼主有答案吗

没有答案，如果我每记错的话，每个zip都要有manage这些去解析当前插件包，我很长时间没接触这个框架了有点不记得了，你可以拉取一下我这个项目看下：https://github.com/fzkf9225/shadow-plugin-master，当时怕忘了所以一些问题我基本都记录了，研究了下原理，后面就没深究了

**Comment by liouyang** [comment]
好的 感谢楼主
