### ISSUE TITLE
A页面启动插件页面无法启动能帮忙看看哪里出了问题嘛，看日志看不出来什么，能帮帮忙看看吗

### ISSUE THREAD

**Issue by liouyang** [Tencent/Shadow#1246]
![Screenshot_20230926_114647](https://github.com/Tencent/Shadow/assets/16998599/37b7c788-f899-484b-bb03-bbbaf71de4aa)
![image](https://github.com/Tencent/Shadow/assets/16998599/cdbe7fe7-6468-45be-bbc6-20fcbcccbf24)
![image](https://github.com/Tencent/Shadow/assets/16998599/04984d6f-6cf6-4895-9fca-6c6bc76f9832)
![image](https://github.com/Tencent/Shadow/assets/16998599/54ecfe1f-331a-4a3d-9dfa-6d24322c59d8)

```[tasklist]
### Tasks
```

**Comment by shifujun** [comment]
你应该先debug sample的启动过程，熟悉理解这东西是怎么工作的，再去debug你的业务。然后如果有bug，能解决的就提pr，不能解决的就以开源的方式交流复现bug的代码。

**Comment by liouyang** [comment]
> 你应该先debug sample的启动过程，熟悉理解这东西是怎么工作的，再去debug你的业务。然后如果有bug，能解决的就提pr，不能解决的就以开源的方式交流复现bug的代码。

谢谢，应该是一个很小的哪里配置的有问题，我新建一个项目就可以。
