### ISSUE TITLE
java.lang.NoSuchMethodError: androidx.lifecycle.ReportFragment.getActivity

### ISSUE THREAD

**Issue by XuchengJie** [Tencent/Shadow#1247]
![1695712558710](https://github.com/Tencent/Shadow/assets/7425714/dfacd6a7-9f0d-470d-8c34-5c267d384d23)
启动Activity时报错，反编译androidx.lifecycle.ReportFragment
![1695712804676](https://github.com/Tencent/Shadow/assets/7425714/cd4cd705-b2cc-46af-8e13-487255190c20)
此处的方法getActivity不存在。
此Activity是第三方SDK提供，无法修改，请问有没有思路可以解决此问题？

**Comment by shifujun** [comment]
ReportFragment是androidx加载必要的东西，androdix的那个test肯定用过了。所以我不能简单的猜出来那个getActivity怎么回事。你最好在sample改出来怎么复现。

**Comment by RiderFaiz** [comment]
我不知道我的情况是不是和你的一样，我的是在横屏时切换到插桩的Activity，由于插桩Activity是其他屏幕方向导致的这个错误，我把screenOrientation写成固定的横屏就没问题了，我估计屏幕旋转这块可能做了一些dex的替换还是什么操作
