### ISSUE TITLE
使用官方的例子 单个插件没问题, 当关闭一个插件 再打开第二个插件就会报错, 

### ISSUE THREAD

**Issue by winnershili** [Tencent/Shadow#1248]
使用官方的例子 单个插件没问题, 当关闭一个插件 再打开第二个插件就会报错, 
![image](https://github.com/Tencent/Shadow/assets/16534226/419e6c41-577e-4936-8c1f-7d771c0f8b57)
![image](https://github.com/Tencent/Shadow/assets/16534226/7cdf629c-c82d-4eab-97b2-27bdad3ca07a)

throw new NotFoundException("uuid==" + uuid + "partKey==" + partKey + "的Plugin找不到"); 
这个错误 
望给出解决方案 谢谢

**Comment by liouyang** [comment]
我觉得报这个错误出现在启动的partKey跟打包的partKey不一致导致的

**Comment by winnershili** [comment]
> 我觉得报这个错误出现在启动的partKey跟打包的partKey不一致导致的

特意从头到位检查了一遍 发现partKey 没问题

**Comment by winnershili** [comment]
> 我觉得报这个错误出现在启动的partKey跟打包的partKey不一致导致的
插件1
![image](https://github.com/Tencent/Shadow/assets/16534226/40fda201-350f-4d46-b46f-4072c58847cc)
![image](https://github.com/Tencent/Shadow/assets/16534226/ed598cec-44eb-4b82-a679-f48b1376fdcb)
插件2
![image](https://github.com/Tencent/Shadow/assets/16534226/369ba76f-3270-424f-b3a1-72e2f5d4744e)
![image](https://github.com/Tencent/Shadow/assets/16534226/ad6a466e-3859-4e38-97c5-7a123d2e3bf8)

通过调试发现问题出现在这个类中
![image](https://github.com/Tencent/Shadow/assets/16534226/9ba3e5fe-0bfd-4ecd-bd1c-51dba8ecac59)
启动第二个插件时 这地方mPpsController 居然不为空 
目前没有解决方法 期望指点

**Comment by shifujun** [comment]
你要先注意你复制的是`com.tencent.shadow.sample`包中的示例代码，你不能指望这些代码是通用的。它们是演示SDK接口如何调用的。

你可能没抄明白安装插件的调用逻辑。没安装就启动了。
