### ISSUE TITLE
插件进程被kill掉之后，可以自动拉起来，是在哪里重新拉起来的？

### ISSUE THREAD

**Issue by LeonWu6** [Tencent/Shadow#1249]
Hi  大佬前辈，
我在 adb shell 中用 "kill -9 {pid}" 指令将插件进程 kill 掉，但它马上会被重新拉起，请问这个重新拉起的动作是在哪里实现的？
如下是从 adb shell 中操作打印：

1|OP5CF9L1:/ # ps -A | grep shadow
u0_a330      15323  1470    6663516 160760 __arm64_sys_epoll_pwait 0 S com.tencent.shadow.sample.host
u0_a330      20911  1470   23884184 216512 __arm64_sys_epoll_pwait 0 S com.tencent.shadow.sample.host:plugin
OP5CF9L1:/ # kill -9 20911
OP5CF9L1:/ # ps -A | grep shadow
u0_a330      15323  1470    6681000 160752 __arm64_sys_epoll_pwait 0 S com.tencent.shadow.sample.host
u0_a330      23551  1470    6394248 116588 __arm64_sys_epoll_pwait 0 S com.tencent.shadow.sample.host:plugin

**Comment by shifujun** [comment]
Activity Manager吧。这是Android四大组件生命周期设计的基础问题。跟shadow没关系。

**Comment by LeonWu6** [comment]
> Activity Manager吧。这是Android四大组件生命周期设计的基础问题。跟shadow没关系。

好的，谢谢。
当服务进程被 kill 时，会进到这个函数 onPluginServiceDisconnected() 函数。
我在自己APK中，override 了这个函数，去调用 bindPluginProcessService()，则会触发 IllegalArgumentException("无法绑定PPS:" + serviceName); 
自以是特定代码来能重新拉起 plugin 进程，被自己误导了。
