### ISSUE TITLE
ShadowRemoteViewCreator 怎么使用？

### ISSUE THREAD

**Issue by woojunfeng** [Tencent/Shadow#125]
sample里面好像没有这方面的调用方法，看了sdk，也没太看懂，如何使用

这个是实现跨插件创建View的方法吗？
A插件在自己的Activity中添加 一个由 B插件提供的 ViewClass 实例？

**Comment by shifujun** [comment]
是的，这是一个我们业务曾经用到的一个类。我应该把它从sdk里删掉的。应该改成一个sample例子比较好。sdk里的这个类应该是不能单独使用的。

**Comment by woojunfeng** [comment]
这种需求应该也应该挺多，用于自定义组件的插件化包装。
我觉得四大组件的通讯作为Shadow的主要实现目的，同时，这种自定义组件的插件化包装，也应该是插件化的主要目标，放在sdk里面算作一个功能项，也挺不错的。
我现在使用的实现方法比较绕，在loadplugin的时候，将plugin的classloader放在了host里面，由host来创建view实例，不知道如何实现plugin的方法
希望能够提供一个sample，学习一下如何实现以上功能

**Comment by shifujun** [comment]
ad976251 已经删除相关代码。

插件和宿主相互交换View可以参考`com.tencent.shadow.sample.host.lib.HostUiLayerProvider`。
