### ISSUE TITLE
请问 packageDebugPlugin 任务 是在哪定义的？

### ISSUE THREAD

**Issue by luoxiong94** [Tencent/Shadow#1252]
编译插件，在`plugin-project`目录中运行：
./gradlew packageDebugPlugin

adb push build/plugin-debug.zip /data/local/tmp

请问 packageDebugPlugin 这个任务是在哪定义的，生吃 plugin-debug.zip 的逻辑代码是在哪个位置哦？

**Comment by shifujun** [comment]
你是如何查找的？

**Comment by luoxiong94** [comment]
我看了下在项目在很多模块中定义了
productFlavors {
        plugin {
            applicationId "com.tencent.shadow.sample.host"
        }
}

讲道理 应该是执行 ./gradlew packagePluginDebug， 现在是执行 ./gradlew packageDebugPlugin， 有点不解，望shifujun解答下，谢谢。

**Comment by shifujun** [comment]
讲道理？讲道理你应该搜索代码而不是猜吧。

CreatePackagePluginTask.kt这个文件中有很多创建task相关的API调用，应该很容易搜索出来的。

**Comment by luoxiong94** [comment]
感谢哈，明白了，通过 createPackagePluginTask 方法拼接的package   Debug    Plugin  。
