### ISSUE TITLE
请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'

### ISSUE THREAD

**Issue by midwinterwk** [Tencent/Shadow#1257]
编译环境：jdk11，gradle版本：classpath "com.android.tools.build:gradle:7.0.3" distributionUrl=https\://mirrors.tencent.com/gradle/gradle-7.0.2-bin.zip
问题背景：
盒子的项目准备使用插件化，先写个Demo出来，遇到了问题，求大佬帮忙看看。
我下载了https://github.com/Tencent/Shadow.git的代码，在Shadow\projects\sample\source\sample-plugin\sample-app下的build.gradle里添加了一行代码multiDexEnabled true，运行在Android 4.4的设备上，跳转插件Activity时，报错java.util.concurrent.ExecutionException: java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'
请问大佬怎么解决？求解答，谢谢！

**Comment by shifujun** [comment]
同#1256
