### ISSUE TITLE
【插件调用宿主】No virtual method apply(Lcom/tencent/shadow/core/runtime/ShadowActivity;)

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Tencent/Shadow#126]
情况有点复杂，关于插件调用宿主类方法的

host api host-lib-for-plugin
plugin compileOnly host-lib-for-plugin.jar
host-lib-for-plugin 里定义 `fun apply(Activity)`
plugin 里加白名单后调用宿主类的 `apply(Activity)`
抛出错误 `No virtual method apply(Lcom/tencent/shadow/core/runtime/ShadowActivity;)`

分析：由于 plugin 的 Activity 被 transform 成 ShadowActivity，而宿主的 Activity 还是 Activity，于是实际上 plugin 调用的是 apply(ShadowActivity) 而不是 host-lib-for-plugin.jar 里声明的 apply(Activity)

咋搞？

**Comment by guok2046** [comment]
目前插件中是不可见真实的Activity的，ShadowActivity本质上只是一个普通的类而非Activity，建议宿主中定义一个接口，插件中Activity实现这个接口。apply的时候将这个接口作为参数进行传递
