### ISSUE TITLE
请问：如果host有loader和runtime后，插件还支持动态loader和runtime吗？

### ISSUE THREAD

**Issue by luoxiong94** [Tencent/Shadow#1265]
我们有10个SDK需要做成插件化，大部分SDK插件不需要动态loader和runtime，部分SDK插件需要，

请问：
1、如果host有loader和runtime后，插件还支持动态loader和runtime吗？
2、每个SDK都需要维护自己的loader和runtime，维护成本有点高，有啥更好的方式吗？

**Comment by shifujun** [comment]
不管是loader还是什么部分，它能动态化完全是基于classloader查找类的原理实现的。不同classloader加载的同名类压根就不是一个类。宿主和插件或者loader等都是不同classloader加载的，它们各自打包了什么类根本不相关。让它们协作起来就是设计好跨classloader查找类的方案，典型的例子就是双亲委派机制。

多个loader之类的问题有很多种解决方案。如果多个插件的loader总是同一份代码，那它们似乎就是同一个uuid发布的一套插件，只是partkey不同。uuid主要是标识各部分是同一个版本，可以协同工作。如果是不同版本或业务总是复用同一个part，那可以在下载和打包层面复用文件，为相同文件分配新的uuid就可以了。插件管理这块和业务相关性比较大，自己完全重新实现也是可以的，不会和shadow的主要代码有什么冲突。我其实想把manager删掉，引入一个开源的管理库来代替这块功能。但没找到合适的。

**Comment by luoxiong94** [comment]
感谢指教，明白了您说的了，谢谢。

**Comment by SunShineLx** [comment]
你们是每个插件.apk、Loader.apk、Runtime.apk都放到zip包里吗？感觉维护起来很麻烦，每次都要打3个apk。

我想把把Loader 和 Runtime 直接集成到Host里面。 如果zip包里没有Loader.apk就默认使用Host的，如果有，则使用zip包里的，不知这种方案是否可行呢？

**Comment by luoxiong94** [comment]
方案1：
版本1，发布A插件的zip包有以下：
runtime.apk、loader.apk、pluginA.apk

版本2，发布A插件的zip包有以下：
runtime.apk、loader.apk、pluginA.apk

版本3，发布A插件的zip包有以下：
runtime.apk、loader.apk、pluginA.apk


方案2：
版本1，发布A插件的zip包有以下：
pluginA.apk

其中runtime和loader直接集成在宿主里，如果zip包有runtime就用zip包里的，没有就用宿主里的

版本2，发布A插件的zip包有以下：
runtime.apk、loader.apk、pluginA.apk

用zip包里的runtime和loader进行加载插件

2种方案都可以吧
