### ISSUE TITLE
最近在研究Shadow，建了个wx群，方便沟通

### ISSUE THREAD

**Issue by budaowengd** [Tencent/Shadow#1266]
最近在研究Shadow，建了个wx群，方便沟通。 项目写的很复杂，有时遇到问题还是需要道友指点下才能通
![image](https://github.com/Tencent/Shadow/assets/16216657/edcddc43-5c8a-4fb5-86da-936fcf0a6115)

**Comment by wudongze** [comment]
大佬微信多少，我想进下群或者加我一下，wudongze0

**Comment by budaowengd** [comment]
> 大佬微信多少，我想进下群或者加我一下，wudongze0

大佬，二维码已更新
