### ISSUE TITLE
./gradlew packageDebugPlugin

### ISSUE THREAD

**Issue by zhqf66** [Tencent/Shadow#1268]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugin-app:transformClassesWithShadowTransformForPluginDebug'.
> 'java.lang.String com.android.utils.FileUtils.relativePossiblyNonExistingPath(java.io.File, java.io.File)'

**Comment by wh963572516** [comment]
如果你用的shadow是2.3.0版本，那么Gradle Plugin版本不能超过7.2,  用7.1.3
