### ISSUE TITLE
setScm方法中的两个URL

### ISSUE THREAD

**Issue by lhkzx007** [Tencent/Shadow#127]
setScm方法中的两个URL , 是私服maven仓库的地址?  还是github的地址?

**Comment by shifujun** [comment]
应该是所谓“私服maven仓库“的地址。因为是你自己发布的，那个setScm方法只是帮你在pom文件里记录一些版本信息，方便回溯版本的。这些信息对实际运行毫无影响。建议按你的实际地址填写，记录到pom中。最好配置在CI中。

**Comment by shifujun** [comment]
有问题欢迎再打开。
