### ISSUE TITLE
插件manager中的view如果有ProgressBar，但是宿主不显示ProgressBar

### ISSUE THREAD

**Issue by budaowengd** [Tencent/Shadow#1271]
1、Shadow里Manager就会首先从manger.apk中动态加载一个View供宿主显示Loading状态。修改activity_load_plugin.xml
`
<LinearLayout  >

    <ProgressBar
        style="?android:attr/progressBarStyle"
        android:id="@+id/progressBar1"
        android:indeterminateTint="@android:color/holo_blue_dark"
        android:layout_gravity="center"
        android:layout_height="wrap_content"
        android:layout_marginTop="30dp"
        android:layout_width="wrap_content"
        android:max="100"
        android:progress="50"
        android:progressTint="@android:color/holo_blue_dark" />

    <TextView
        android:layout_gravity="center"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        android:layout_width="wrap_content"
        android:text="正在加载中..."
        android:textSize="30sp" />

</LinearLayout>
`

2、ProgressBar 不会显示，页面只显示"正在加载中..."
<img width="385" alt="image" src="https://github.com/Tencent/Shadow/assets/16216657/83e876d4-4171-448f-bb81-2d62fca5a0ce">
<img width="484" alt="image" src="https://github.com/Tencent/Shadow/assets/16216657/81fd216e-83a9-4554-8079-3fe2614345f2">

请问是咋回事

**Comment by shifujun** [comment]
这一般就是View的Context的问题。
https://github.com/Tencent/Shadow/blob/d9deb2f5da99091409be0e5e2fa718db57dff2bd/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L115C51-L115C66

这里的inflater的context可能是宿主的。所以有些资源可能找不到。调试调试看看它在请求context的哪些接口，搞一个wrapper接下来请求，从插件里取资源给它一般就可以了。

**Comment by budaowengd** [comment]
大佬，我从github拉下来Shadow代码后，就修改了 activity_load_plugin.xml，然后加了个ProgressBar，就显示不了了。你说的"搞一个wrapper接下来请求，从插件里取资源给它一般就可以了。"   我有点不懂该改哪里，可以再详细说说吗？

**Comment by shifujun** [comment]
这是个Bug。activity_load_plugin.xml原本就有个ProgressBar没显示出来。
没看代码前，我忘了前面说的那个context其实已经不是宿主的了。

**Comment by budaowengd** [comment]
已确认修复，感谢！
