### ISSUE TITLE
插件apk没有用到四大组件，有必要弄成多进程吗？

### ISSUE THREAD

**Issue by budaowengd** [Tencent/Shadow#1272]
我们有个业务插件A，只负责向宿主提供字符串数据，比如 APluginDataHandle 定义在插件A中，
`object APluginDataHandle {
    fun getUserName(): String {
        
        return "插件数据"
    }
}`
请问：
1、插件apk没有用到四大组件，有必要弄成多进程吗？
2、请问如何把业务插件A放在单独的进程运行，如果在单独进程运行，宿主如何获取APluginDataHandle类的引用呢，谢谢

**Comment by shifujun** [comment]
没有用到四大组件根本就不需要Shadow或者类似的插件技术。这些插件技术的目的都是动态更新四大组件的逻辑。

不涉及四大组件。你就简单的用DexClassLoader加载你的类就行了。

“跨进程获取类或对象的引用”，提出这种需求，说明你对进程和对象的关系没有基本认识。除非是系统允许的共享内存，否则我们的各进程是独立分开的内存空间。是不可能共享对象的。

**Comment by budaowengd** [comment]
感谢，Shadow项目没有利用AIDL生成的java类，而是手写Binder进行通信，看的有点懵。现在在同一个进程中，宿主是可以访问插件apk中的接口实现的。 跨进程传递数据，尝试了几天都没成功。
