### ISSUE TITLE
请问 normalImplementation 是只有Shadow才有的吗？

### ISSUE THREAD

**Issue by SunShineMy66** [Tencent/Shadow#1278]
在sample-plugin/sample-app/.build.gradle中有以下代码，不明白这是啥意思

`normalImplementation project(":sample-host-lib") `

**Comment by shifujun** [comment]
搜一下`addFlavorForTransform(baseExtension)`。shadow在这个方法里自动给插件模块添加了flavor。其余的就查查AGP关于flavor的设计，还有gradle关于依赖的语法。

**Comment by SunShineMy66** [comment]
感谢您的回答，明白了
