### ISSUE TITLE
none-dynamic场景使用so

### ISSUE THREAD

**Issue by Florizt** [Tencent/Shadow#1288]
none-dynamic场景下，插件需要load so，不知道要怎么弄，可以教教嘛

**Comment by shifujun** [comment]
插件代码就是宿主代码的一部分，对so来说不存在插件和宿主的差异和隔离。你直接load so的绝对路径就行了。

**Comment by Florizt** [comment]
是必须用绝对路径才行嘛？我目前是用  System.loadLibrary("sign");但是报错了，我看到另一个issue：https://github.com/Tencent/Shadow/issues/1244，里面老哥说要仿写BasePluginManager里的extractSo方法，我就不会了～～

**Comment by wudongze** [comment]
老兄，这个问题解决了吗，我也碰到这个问题了

**Comment by sun804336516** [comment]
![image](https://github.com/Tencent/Shadow/assets/18586862/af963bc1-bddb-45e9-9fd9-b424fc32f9de)
仿照这里面代码复制so即可
