### ISSUE TITLE
怎么加载本地存储中的插件，而不是加载assets中的插件

### ISSUE THREAD

**Issue by 2079541547** [Tencent/Shadow#1292]
怎么加载本地存储中的插件，而不是加载assets中的插件
如果我不想使用zip来加载可以分为多个apk吗

**Comment by yaoyue1019** [comment]
参考com.newland.plugin.manager.FastPluginManager#installPlugin
这里的zip路径是外部传进来的，如果用多个apk的话你得动一动manager里的代码了
