### ISSUE TITLE
可以更新一下最新代码的maven版本吗？

### ISSUE THREAD

**Issue by LuYeCong** [Tencent/Shadow#1296]
上次发布的maven版本比较旧了，希望可以更新一下。

**Comment by shifujun** [comment]
一般来说业务都不会直接用shadow开源的代码，总会有业务自己需要定制的部分。这也是为什么shadow要设计成可以动态更新自身。
所以也建议你自己发布一份到你的maven服务器上。github的maven服务器也不好用。shadow这边的发布主要是验证maven发布的流程是可以跑通的。
