### ISSUE TITLE
自荐 BlackShadow，Shadow的二次封装项目，开袋即食版。

### ISSUE THREAD

**Issue by nnjun** [Tencent/Shadow#1297]
接入Shadow需要大量的二次开发工作，其实一般小型项目其实并不想关心太多的逻辑和管理，只想开袋即食，奈何Shadow也并没有提供这方面的能力，所有开发者接入都需要二次开发才可以使用，所以花了点时间在Shadow的基础上包装了一层，几乎不需要任何二次开发，即可通过几个简单的接口使用与管理Shadow，屏蔽了Shadow所有的技术细节。

https://github.com/CodingGay/BlackShadow

**Comment by wjy000** [comment]
非常好
