### ISSUE TITLE
throw new RuntimeException("packageArchiveInfo is NullPointException")

### ISSUE THREAD

**Issue by ClarkRep** [Tencent/Shadow#1299]
三星Android7.0系统，加载PluginManager的时候报错，这里packageArchiveInfo为null了，请问怎么解决呢？    
PackageInfo packageArchiveInfo = packageManager
            .getPackageArchiveInfo(apkPath, GET_META_DATA);
    if (packageArchiveInfo == null) {
        throw new RuntimeException("packageArchiveInfo is NullPointException");
    }

**Comment by shifujun** [comment]
> packageArchiveInfo is NullPointException

我搜不到这个代码。

这个api很稳定。特别是在旧版本的Android上更不应该有问题。
所以就算真的有问题，也没什么好办法了。非要针对性兼容，就考虑hardcode所需的信息吧。

**Comment by zhuqichao** [comment]
这个一般是apk文件出问题了，损坏或者被删除了
