### ISSUE TITLE
插件里的 so 库路径名称太长加载不成功

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Tencent/Shadow#130]
```
java.lang.UnsatisfiedLinkError: dlopen failed: library name "/data/data/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/lib/0D88166A-8BA8-4396-927D-F1E486A505D1_lib/libhyphenate.so" too long
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:988)
        at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source)
        at com.hyphenate.chat.EMClient.getInstance(Unknown Source)
```

**Comment by guok2046** [comment]
具体的机型和Android版本是？

**Comment by LinXueyuanStdio** [comment]
oppo a59m, Android 5.1

**Comment by passXu** [comment]
后续如何处理捏

**Comment by shifujun** [comment]
这行是写入到数据库持久化的so路径：
https://github.com/Tencent/Shadow/blob/06d155a94681bfd369cb151fe6d6f90d36470f45/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L110

这两行是解压so时的路径：
https://github.com/Tencent/Shadow/blob/06d155a94681bfd369cb151fe6d6f90d36470f45/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L197
https://github.com/Tencent/Shadow/blob/06d155a94681bfd369cb151fe6d6f90d36470f45/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L220

同时修改这两个路径就可以修改新安装的插件的so路径了。已经安装的插件的so路径是在数据库里记录的，不受影响。

**Comment by passXu** [comment]
非常感谢，我去试一下。
