### ISSUE TITLE
com.tencent.shadow.core.runtime.remoteview 如何使用

### ISSUE THREAD

**Issue by adaJQD** [Tencent/Shadow#131]
`com.tencent.shadow.core.runtime.remoteview` 的示例有么

**Comment by shifujun** [comment]
RemoteView最初是为了解决我们业务中跨apk加载View引入的。在SDK中代码不完整，并且其功能可以通过相互约定自定义接口来实现。由于没有精力维护这样一个可选功能，所以删除这些代码。
