### ISSUE TITLE
NoSuchMethodException: com.android.tools.apk.analyzer.BinaryXmlParser.decodeXml 错误

### ISSUE THREAD

**Issue by aidaole** [Tencent/Shadow#1314]
基于最新的代码
![image](https://github.com/Tencent/Shadow/assets/77848640/cf056814-c00a-4284-a3e5-6492128c324e)
环境:
android studio 版本: Android Studio Iguana | 2023.2.1
jdk版本: 11 和17 均失败

尝试运行 `sample-host` 和 `./gradlew :sample-host:installDebug`  一直失败, 提示错误:
```
> Task :sample-loader:createDebugApkListingFileRedirect
> Task :sample-loader:assembleDebug

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sample-base:decodePluginDebugBinaryManifest'.
> java.lang.NoSuchMethodException: com.android.tools.apk.analyzer.BinaryXmlParser.decodeXml(java.lang.String, [B)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sample-app:decodePluginDebugBinaryManifest'.
> java.lang.NoSuchMethodException: com.android.tools.apk.analyzer.BinaryXmlParser.decodeXml(java.lang.String, [B)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

**Comment by shifujun** [comment]
如果是最近build tools更新了，导致找不到这个方法，我们就得重新适配了。你可以看下版本号，我看看能不能复现。

也可以按 https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md 中的说明去debug gradle插件。加log也是个选择。

相关逻辑可以搜索commit message找到。

**Comment by aidaole** [comment]
问题已经找到, 是因为我的电脑上配置了Flutter的环境, 将 `android sdk home\cmdline-tools\latest` 配置到了环境变量中, 导致 `com.android.tools.apk.analyzer.BinaryXmlParser` 加载错误了. 把环境变量删除之后可以正常编译了

**Comment by gi13371** [comment]
> 问题已经找到, 是因为我的电脑上配置了Flutter的环境, 将 `android sdk home\cmdline-tools\latest` 配置到了环境变量中, 导致 `com.android.tools.apk.analyzer.BinaryXmlParser` 加载错误了. 把环境变量删除之后可以正常编译了

你好 我也遇到了这个问题，一直没找到原因，请问有什么思路可以分享吗

**Comment by CaoMCan** [comment]
下一个新一点的cmdline-tools，替换原来旧的目录，再来编译就没问题了，我是这样解决的

**Comment by aprz512** [comment]
lastest 的方法签名变了，自己改下 ShadowPlugin 的 createGeneratePluginManifestTasks 就行，里面反射了 decodeXml 方法。

**Comment by qiangbin0201** [comment]
使用了最新代码时，在decodeXmal时报错，Gradle版本8.11.1, AGP版本8.9.3
Unknown chunk type: -27894
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:978)
	at com.google.devrel.gmscore.tools.apk.arsc.Chunk$Type.fromCode(Chunk.java:75)
	at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:254)
	at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:242)
	at com.google.devrel.gmscore.tools.apk.arsc.BinaryResourceFile.<init>(BinaryResourceFile.java:39)
	at com.android.tools.apk.analyzer.BinaryXmlParser.decodeXml(BinaryXmlParser.java:45)

请问大家有遇到吗，看下来时release生成的ap_文件AndroidManifest.xml格式和debug环境生成的不一致，解析会报错
目前思路时重新时AAPT的Resource重新解析，但发现Manifest里面使用的@string或@theme等没有映射成R文件的常量比如@ref/0xxxx, 这样PluginmainifestGenerator这个函数会报错，所以也需要重新，非常麻烦，
请问各位大佬有其他方案吗

 fun themeStringToResId(manifestValue: Any): String {
            val formatValue = manifestValue as String // for example: @ref/0x7e0b009e
            if (formatValue.startsWith("@ref/")) {
                return formatValue.removePrefix("@ref/")
            } else {
                // 其余格式：https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:apkparser/analyzer/src/main/java/com/android/tools/apk/analyzer/BinaryXmlParser.java;l=193
                throw TODO("不支持其他格式")
            }
        }
