### ISSUE TITLE
transformClassesWithShadowTransformForPluginDebug执行时卡住

### ISSUE THREAD

**Issue by AndroidMuggle** [Tencent/Shadow#1315]
1、我把shadow项目的transform相关代码添加了日志，发布到了本地仓库（相比master分支只添加了日志未做其他改动）
2、demo项目集成的时候依赖本地仓库版本，添加的日志如下（第一个字符串是类名，第二个字符串是方法名）：
![image](https://github.com/Tencent/Shadow/assets/100706160/a17fcd8b-bf28-4472-b3fe-8dd830f2cba2)
![image](https://github.com/Tencent/Shadow/assets/100706160/8f805910-ff75-442a-bfde-de6e337ca919)
3、以下是我的demo运行的效果，会一直卡在这一步（最高试过一个午休结束还在这个步骤）：
![image](https://github.com/Tencent/Shadow/assets/100706160/5e88dc6c-c51b-4108-8afe-ca233a18565b)
4、以下是pluginapp模块的资源，只有创建模块的时候AS自动添加的资源（其他模块也存在叫activity_main的xml布局文件）：
![image](https://github.com/Tencent/Shadow/assets/100706160/c92a023b-8b19-46f4-982b-07b65b270416)
5、项目环境：
kotlin_version = 1.7.10
build_gradle_version = 7.4.2
麻烦大佬帮忙瞅瞅可能是哪个环节出了问题，不胜感激！！！

**Comment by shifujun** [comment]
瞅是瞅不出来的。我也不能用眼睛编译运行代码啊。
