### ISSUE TITLE
Unsupported class loader

### ISSUE THREAD

**Issue by dhs964057117** [Tencent/Shadow#1316]
你好请教个问题，环境gradle8.4 AGP8.3.1 
能够正常启动插件，为了适配隐式启动activity修改如下：
PluginManifest中ActivityInfo类：
![image](https://github.com/Tencent/Shadow/assets/34617909/0e0ccd21-619c-4b0a-92c3-4508cc22d667)
ComponentManager类：
![image](https://github.com/Tencent/Shadow/assets/34617909/6f3afc4f-13e0-4e32-a817-b7935b6fae82)
![image](https://github.com/Tencent/Shadow/assets/34617909/35fa540f-38c5-4941-b562-be89abdc034b)
![image](https://github.com/Tencent/Shadow/assets/34617909/a6496196-2cd7-4d47-9ee7-6d7c5b2e65ef)
PluginManifestGenerator类
toNewActivityInfo方法：
![image](https://github.com/Tencent/Shadow/assets/34617909/8b8f0d7a-2ca8-4a21-989d-58b31d5224c0)
AndroidManifestReader类：
![image](https://github.com/Tencent/Shadow/assets/34617909/3e3e4781-d7b8-4626-9a8d-2e30d1f78477)
启动插件化报错：
![image](https://github.com/Tencent/Shadow/assets/34617909/20c0db6a-9a02-44da-b71e-0b6bb9ac28a5)

**Comment by shifujun** [comment]
把能复现问题的sample和修改的代码push到你fork的仓库中，并且使代码改动尽可能小，这样才是开源项目的代码交流。

**Comment by dhs964057117** [comment]
> 把能复现问题的sample和修改的代码push到你fork的仓库中，并且使代码改动尽可能小，这样才是开源项目的代码交流。

当前在公司环境，回家后再上传一份私人仓库代码
