### ISSUE TITLE
ERROR: Failed to resolve: multidex-instrumentation

### ISSUE THREAD

**Issue by yangpeiyong** [Tencent/Shadow#132]
构建失败，报错如下：

> ERROR: Failed to resolve: multidex-instrumentation
Affected Modules: test-plugin-multidex-v2_0_1

**Comment by shifujun** [comment]
如果还有问题，请参考
https://github.com/Tencent/Shadow/blob/dev/CONTRIBUTING.md#issue
再重新打开Issue。
