### ISSUE TITLE
崩溃必现   android.util.SuperNotCalledException: Activity {com.xx.act.DefaultContainerActivity} did not call through to super.onCreate()

### ISSUE THREAD

**Issue by budaowengd** [Tencent/Shadow#1326]
<img width="1993" alt="image" src="https://github.com/Tencent/Shadow/assets/16216657/0a929016-77ce-4b90-be1d-8cf8ed43139b">

背景：
OPPO A7x（版本8.0 ）和  魅族M1852（版本8.1）会必现上面崩溃。

复现路径：
宿主加载A插件后，打开A插件中的一个Activity，就会发生这个崩溃，测试了20多台手机，只有上面2台会出现 ，请问是啥原因？

**Comment by budaowengd** [comment]
已通过ActivityLifecycleCallbacks修复

**Comment by starlingever** [comment]
@budaowengd 请问具体是如何通过ActivityLifecycleCallbacks实现的呢？
