### ISSUE TITLE
ShadowActivity#getApplication()问题咨询

### ISSUE THREAD

**Issue by NMNET** [Tencent/Shadow#133]
插件中有个业务场景会调用插件Activity的getApplication方法获取application实例，此时返回的是ShadowApplication实例，但业务框架会判断如果不是App自己的Application则会抛出异常，请问这种情况应该怎么处理？不知道描述清楚了没有，希望大神们赐教，感谢。

**Comment by shifujun** [comment]
这里“业务框架”判断的逻辑具体是怎么写的？如果只是因为类型从“Application”变成了“ShadowApplication”，那么判断逻辑中的“Application”也会变成“ShadowApplication”，应该不受影响的。

**Comment by NMNET** [comment]
感谢回复，伪代码大概是这样的：
class MyApp extends Application implements IBusiness { ... }
class MyPluginActivity{
    ...
    if ( !(getApplication instanceof IBusiness) ){
         throw new Exception("application is not IBusiness")
    }
    ...
}
这种场景应该怎么处理，感谢指导

**Comment by shifujun** [comment]
这需要处理吗？你是不是根本没真跑过这种场景的代码？如果可以复现问题的话，应该很容易在Shadow的Sample里构造这个场景。能复现的话把代码库贴出来就好了。

**Comment by NMNET** [comment]
这个是在项目中尝试集成遇到的问题（补充一点，MyPluginActivity继承自Activity），
个人分析是这样的：MyPluginActivity的父类在构建时被shadow-plugin修改成ShadowActivity，所以getApplication()方法获取到的是ShadowApplication，ShadowApplication是没有实现IBusiness，所以会抛出异常。
如果有因为个人对shadow框架认识有限而导致的分析有误，希望帮忙纠正，感谢

**Comment by boyan01** [comment]
插件中的 Activity / Application 在编译的时候，会分别转成 ShadowActivity / ShadowApplication.

按 @NMNET  你所说的情况，个人猜测是你的**插件**中没有定义 Application，导致 ShadowActivity#getApplication 获取到的是默认的 ShadowApplication。所以你应该在插件里添加一个 Application 的子类，并实现 IBusiness 接口就好了。

**Comment by NMNET** [comment]
@shifujun @boyan01 非常感谢指导，插件中是没有定义Application，再次感谢
