### ISSUE TITLE
Android14上使用插件, 报错"java.lang.SecurityException: Writable dex file '/data/user/0/a.b.c/files/plugins/plugin-manager.apk' is not allowed."

### ISSUE THREAD

**Issue by YeJiashen** [Tencent/Shadow#1344]
我们的项目将targetSdk升级到Android14后, 发现使用插件时报了如上错误, 官网要求使用动态代码加载时必须要将动态加载的文件设置为只读, 这块Shadow插件是否针对这种场景进行了适配呢?

https://developer.android.com/about/versions/14/behavior-changes-14?hl=zh-cn#safer-dynamic-code-loading

![WX20240807-163923](https://github.com/user-attachments/assets/c2efc0f4-036b-4d24-8dd0-211dca0f5c8f)

**Comment by bellyjuice** [comment]
同问
