### ISSUE TITLE
desugar_jdk_libs导致D8编译错误

### ISSUE THREAD

**Issue by pangzhen** [Tencent/Shadow#1349]
MIN_SDK_VERSION为21，参照https://developer.android.com/studio/write/java8-support?hl=zh-cn， 增加desugar_jdk_libs会报D8编译错误，能否解决

**Comment by shifujun** [comment]
你可以在sample上尝试复现一下。我们再一起看看是什么情况。

**Comment by pangzhen** [comment]
是okhttp引入的okio导致，okhttp换成4.11.0就可以了
