### ISSUE TITLE
shadow插件页面在后台被系统回收后无法恢复

### ISSUE THREAD

**Issue by marsyu** [Tencent/Shadow#137]
问题描述:使用shadow插件实现的页面切换到后台，由于内存不足被系统回收后，无法恢复至插件页面，只能保证不crash,所以目前shadow不支持被系统回收恢复至回收前的页面是么？若支持，应该如何处理。

我看源码中有如下描述:
 /**
     * IllegalIntent指的是这些情况下的启动：
     * 1.插件版本变化之后，残留于系统中的PendingIntent或系统因回收内存杀死进程残留的任务栈而启动。
     * 由于插件版本变化，PluginLoader逻辑可能不一致，Intent中的参数可能不能满足新代码的启动条件。
     * 2.外部的非法启动，无法确定一个插件的Activity。
     *
     *
     * 3.不支持进程重启后莫名其妙的原因loader也加载了，但是可能要启动的plugin没有load，出现异常
     *
     * @param savedInstanceState onCreate时系统还回来的savedInstanceState
     * @return <code>true</code>表示这次启动不是我们预料的，需要尽早finish并退出进程。
     */
    private boolean isIllegalIntent(Bundle savedInstanceState) {
        Bundle extras = getIntent().getExtras();
        if (extras == null && savedInstanceState == null) {
            return true;
        }
        Bundle bundle;
        bundle = savedInstanceState == null ? extras : savedInstanceState;
        try {
            String loaderVersion = bundle.getString(LOADER_VERSION_KEY);
            long processVersion = bundle.getLong(PROCESS_ID_KEY);
            return !BuildConfig.VERSION_NAME.equals(loaderVersion) || processVersion != DelegateProviderHolder.sCustomPid;
        } catch (Throwable ignored) {
            //捕获可能的非法Intent中包含我们根本反序列化不了的数据
            return true;
        }
    }

**Comment by shifujun** [comment]
”不保留活动“是支持的，”不保留进程“是不支持的。这样描述你容易理解吗？

插件进程重启后，需要重新加载Runtime、Loader和Plugin，这个流程比较长，我们业务用不上，所以没有实现。理论上也是可以支持的。只需要把重新加载所需要的信息，一齐保存到savedInstanceState中就可以了。

**Comment by shifujun** [comment]
> 通过isIllegalIntent(savedInstanceState)判断方法将hostActivityDelegate设置为null 的逻辑,以至于之后通过空的ShadowActivity来代替，避免crash,我的理解是否正确？

这个理解是对的。

>若源码中增加了加载所需信息，就会走正常加载流程，另一个问题是如何加载Runtime、Loader和Plugin的时机，因为这是在PluginContainerActivity内，正常的处理逻辑是宿主加载完shadow插件之后进入，目前是在插件内部，能否指点下思路？

你想的没错，这种场景下PluginContainerActivity已经启动了，而Loader还没有加载，这跟正常的流程是不一样的。所以我也觉得实现这个恢复很麻烦。

我前面说的
>理论上也是可以支持的。只需要把重新加载所需要的信息，一齐保存到savedInstanceState中就可以了。

应该是说错了。这个之前也想过，有些忘了。这些恢复信息保存到Activity的savedInstanceState中是不行的。Activity已经启动，在onCreate中就必须同步调用Loader（delegate）的对应onCreate方法了。这里不能再异步去加载Loader（delegate）了。而且插件的Application的onCreate方法应该早于Activity执行。所以还是要想办法先加载Loader等插件框架的代码，再调用插件的Application，然后才能启动恢复的Activity。

因此，看起来必然的解决方向是要将恢复信息以另外的持久化手段存起来，比如SharedPreference。在宿主的Application对象中判断出插件进程，再从持久化的信息中判断出是否需要恢复插件加载，然后在Application这里以阻塞主线程、同步的方式去加载插件框架和插件，进而调用插件的Application对象。然后才能返回Application的onCreate方法，使系统能进一步恢复Activity。

这里确实想想就很麻烦。从完善框架的角度来看，实现这一特性是很好的。但是从满足业务需求的角度来看，场景太小，不值得投入。

**Comment by marsyu** [comment]
明白了，非常感谢耐心的解答
