### ISSUE TITLE
关于插件中个别Service不转换成ShadowService

### ISSUE THREAD

**Issue by NicoToast** [Tencent/Shadow#138]
请问一下大大，有没有方法添加Transform过滤，不让一些类进行Transform？比如在插件里面我有一个Service，并在宿主里面有manifest注册，我想这个类的继承保持android.app.Service，并使用原生的方式进行调用。

**Comment by shifujun** [comment]
在Transform逻辑中对某些类不进行操作，这本身很容易。但是对于插件中使用Service的类来说就很麻烦了，还需要它们单独对没有Transform成ShadowService的Service编写特殊的代码。所以这不是一个解决问题的好的思路。

Service变成ShadowService之后，主要的区别就是Service作为Android组件的生命周期不一样了。所有的插件Service的生命周期都跟PPS一致了，也包括他们的前台状态。由于我们认为PPS要代表整个插件的生命周期，所以PPS的生命周期一定比插件的Service长，所以我们认为这个实现能满足需求。

建议你还是再分析一下，为什么一定要直接继承系统的Service，而不能转换成ShadowService。最好是找一条转换成ShadowService，也能满足需求的方式。这样对整体的设计改动会更小一些。
