### ISSUE TITLE
单例stub activity的绑定

### ISSUE THREAD

**Issue by feixiaoluo** [Tencent/Shadow#139]
比如LaunchMode为SingleInstance的activity和container activity之间进行1对1的绑定，看代码框架通过让host实现bindContainerActivity维护绑定关系，那对于多个plugin app有在升级过程中增加SingleInstance activity中是不是也要同步在manifest中增加注册stub activity，这种依赖对于plugin app的独立升级不是很友好呀。不知我的理解是否有误，有好的解耦办法吗？在manifest中多打一些桩？为啥没有做成运行时动态分配stub activity呢？

**Comment by shifujun** [comment]
你理解的都没错。都是因为Manifest不能动态修改。所以在Manifest中多打一些桩是目前正确的做法。

从我们自身业务的需求来看，我们的业务对这种特殊LaunchMode的Activity需求并不多，所以预埋四五个就够了。因为只需要满足同一时间有足够数量的壳子（stub activity）就够了。即插件里可能有3个SingleInstance的Activity，它们没有场景会一起启动，那么宿主中只预埋一个壳子就够了。

这件事做成运行时动态分配也是可以的，只是收益不大。特别是在根据实际业务场景复用壳子的时候，配对关系也是要动态业务场景的。如果宿主中埋几十个壳子，那是可以做成自动分配的了。

除了前面说的做法。实际上我也考虑过LaunchMode是SingleInstance的壳子的复用是否可行。我想是可行的。需要让插件框架自行维护SingleInstance的壳子的状态切换。就是说一个Activity本身就实现了被销毁和重建的逻辑，我们在内部也实现一样的逻辑，但是不真的销毁Activity，而是直接给下一个使用壳子的插件Activity使用。把前一个的状态按照销毁重建的逻辑保存起来，等到它复用的时候再还原回去。当然这种设想有个局限是假设Activity都是全屏不透明的。

**Comment by shifujun** [comment]
有问题欢迎再重新打开。
