### ISSUE TITLE
关于Container的动态化中ClassLoader插入

### ISSUE THREAD

**Issue by wangb123** [Tencent/Shadow#144]
将原本的BootClassLoader <- PathClassLoader结构变为BootClassLoader <- DexClassLoader <- PathClassLoader的时候，Shadow好像只能设置一个Container，但如果不同的插件APP需要不同的Container，比如说设置成BootClassLoader <- DexClassLoader1 <- DexClassLoader2 <- PathClassLoader，那么就会导致插件在加载的时候，会使用多个Container，根据双亲委托，肯定是DexClassLoader1 生效，如果两个Container的内部现实是不同的，就可能导致插件App的运行不是预期的结果。如果改成DexClassLoader是PathClassLoader的child，又会出现白名单中的类加载有问题，请问一下您这边有什么思路解决这个问题吗？

**Comment by shifujun** [comment]
你没说清楚两个插件用的Container在宿主的Manifest中是否是注册的同一个名字。

如果Manifest中只注册一个Container，然后两个插件想加载不同的Container类实现，那么应该只能通过进程隔离两个插件。这需要额外在宿主中设置Container的进程为multiprocess的，以便在不同的插件进程都能启动。

还有一个问题是，Container的实现应该没有业务逻辑相关。两个插件应该肯定能复用同一个Container实现。如果你认为不能，你举个例子，我想想。

如果在宿主的Manifest中注册Container没什么限制。也可以通过修改两个Container实现的包名，让加载Container的两个DexClassLoader中实际上没有重名的类。

**Comment by wangb123** [comment]
不好意思，是我没有描述清楚，是这样的，我看shadow框架也有一段时间了，自己也尝试这重复造了一下轮子，我知道一个runtime应该可以满足绝大部分场景了，但我在看runtime的ClassLoader在插入的过程中，会直接替换掉上一个runtime，然后我就在想有没有什么方法可以保留多个runtime，不同的plugin使各自的runtime

**Comment by shifujun** [comment]
runtime现在实际上包含两部分内容。一部分是Container，另一部分是Shadow的一些中间件类。

其中只有Container是需要在PathClassLoader之上的。这些Container是系统的代码问PathClassLoader查询时，通过双亲委派得到的。其余的那些Shadow的中间件类，只有Loader和Plugin会使用，所以它们是可以在PathClassLoader之下的。只是把它们分开，会额外再增加模块，使构建更复杂。需要分开的原因，可能是中间件类越来越多，实现越来越完整，需要根据具体Plugin的使用情况而进行Proguard优化。

所以，同一个类名的Container能否根据不同插件加载不同实现？我想是不能的。因为系统通过ClassLoader loadclass时没有办法传递任何参数。要使不同Plugin使用不同的Container实现，只能让那些Container的类名不一样。

**Comment by wangb123** [comment]
好的，感谢您的回答，我再理解一下
