### ISSUE TITLE
关于proguard和resource id，是否需要自己apply mapping的复用和id的固定

### ISSUE THREAD

**Issue by Hackforid** [Tencent/Shadow#146]
Hi，请原谅我在看完源码前问这么一个粗浅问题，不过在demo使用时想到了这样的问题。
因为看到demo中插件和宿主是单独打包的，不像我们往常用的在编译时剥离插件，这样可能导致插件于宿主的公用代码升成为不同的混淆结果，资源id也是同理。

因为没有镇对release的demo，所以想问下是否需要我们自己实现这一套流程？

**Comment by shifujun** [comment]
不用抱歉哈，我理解插件技术有很多种使用场景。

在你之前用到的场景中，插件是宿主程序的一部分，这种场景下，插件中的类或者资源直接依赖宿主的类或者资源。宿主和插件的版本是一对一关系的。在一对一版本关系下，我们可以很容易的让插件直接依赖宿主的“符号”，所以混淆或者分配资源id时只要同步混淆或者分配就可以正常工作了。

Shadow也支持插件依赖宿主的类和资源，不过没有那么方便。因为我们假定的主要场景是宿主和插件的版本是多对多关系的。插件也像一个独立安装的应用一样，插件和宿主之间的依赖要通过app之间的依赖方式完成。比如协商固定不变的接口，比如通过Service通信，比如将另一个apk资源id分区后加入到插件的Resources对象路径中。

所以，在目前sample能演示的最简单的场景中，也就是单插件，与宿主几乎完全隔离，既不复用宿主的类，也不复用宿主的资源，在这种场景下，宿主和插件可以各自单独更新，他们的混淆，资源id分配都是独立的。所以不用特别做你担心的事情。

**Comment by Hackforid** [comment]
ok，我懂你的意思了。我理解，在业务场景上，shadow的插件是不是更像“小程序”，在设计中也是故意让plugin和host分开。
无反射时，每个classloader只用关注自己所加载到的symbol，所以无需care class or resource。
我可能需要根据自己的业务场景扩展一下，谢谢提供如此不错的插件思路。

**Comment by haizhiyun** [comment]
> ok，我懂你的意思了。我理解，在业务场景上，shadow的插件是不是更像“小程序”，在设计中也是故意让plugin和host分开。 无反射时，每个classloader只用关注自己所加载到的symbol，所以无需care class or resource。 我可能需要根据自己的业务场景扩展一下，谢谢提供如此不错的插件思路。

Hi  请问下你们在正式使用这个框架了吗，有几个问题想请教下：
1. 大部分场景下，依赖宿主这个东西还是挺常见的，比如通用的Util，Androidx 等这些库，如果每个插件放一份，显然不太行，你们是怎么处理的呢（如果依赖宿主，宿主Proguard后，如何保证插件也能正确调用）？
2. 其实像atlas 、 virtualApk 这些库，是允许依赖宿主，在打插件的过程中，将宿主代码剔除去，本框架不是这种做法，有没有最佳实践方式，你们依赖了宿主的场景是怎么处理的呢  
3. 你们是否涉及热修复，热修复是针对宿主打patch  还是针对各个插件打patch呢  
谢谢 ！
