### ISSUE TITLE
关于Fragment和Activity的实现方式疑惑，Fragment是否可以不用代理类实现？

### ISSUE THREAD

**Issue by ghhbgtf** [Tencent/Shadow#151]
如果说Activity使用了代理类是因为组件需要注册到安卓系统中，那么Fragment并不需要注册到系统中，为什么也需要一个ShadowFragment呢，直接基于基础组件的API不行吗？现在因为多了一层转调用，为了实现xml静态使用fragment还需要多加一个Fragment_ 类，不是很懂。

**Comment by shifujun** [comment]
把一个Fragment显示出来，其实不需要套一层ContainerFragment。直接正常添加就可以了。

但是Fragment上有一些接口会返回Activity，或者有通用的强制转换用法将context强制转换成具体的Activity类型。由于Activity被转换成ShadowActivity了，所以Fragment会拿到ContainerActivity。所以为了让Fragment能拿到原本的ShadowActivity，需要包一层ContainerFragment，在ContainerFragment里处理ContainerActivity到ShadowActivity的转换。

由于做了Fragment到ContainerFragment这样一个替换。所有添加Fragment的代码，都应该改为添加ContainerFragment。但是xml里添加的Fragment，我们又没有公开的接口可以修改。所以拿到的办法就是让原本的Fragment把名字让出来，所以原本的Fragment就改名加了一个下划线。

Fragment的处理是Shadow里比较复杂的了，想彻底理解，还是要自己去调试代码。你时间足够的话，就可以把ShadowFragment、ContainerFragment的相关代码都删了。就正常添加Fragment去跑。然后会发现一些问题，然后就能理解删掉的代码在干什么了。也许你还能写出更好的实现。

**Comment by ghhbgtf** [comment]
明白了，xml静态使用这部分看懂了，有空删了代码调试一下看看。
