### ISSUE TITLE
直接导入代码，不能跑？

### ISSUE THREAD

**Issue by zgxzgxzg** [Tencent/Shadow#153]
![image](https://user-images.githubusercontent.com/13228580/68267772-88480a00-008e-11ea-868c-cdf93075edcd.png)

**Comment by zgxzgxzg** [comment]
是需要怎么配置？想把demo跑起来～
知否有配置指导？

**Comment by zgxzgxzg** [comment]
按照如下说明弄了，也不行：
![image](https://user-images.githubusercontent.com/13228580/68268302-9ac34300-0090-11ea-8b2b-2ed0d1f872d0.png)

**Comment by zgxzgxzg** [comment]
AS换了几个版本也不行

**Comment by shifujun** [comment]
你反馈问题时，提供的有效信息很少。

比如你说“按照如下说明弄了，也不行”，也没有给出任何错误信息。

比如你说“AS换了几个版本也不行”，也没有给出任何版本信息。

我能从截图猜到你说的不能跑指的是Android Studio没有识别出可以运行的模块，这一般还是遇到错误了的后果。如果`./gradlew build`没有任何错误，一般IDE也不会有任何错误。如果有错误，IDE的Event中也会显示出来，你得检查一下，如果看不懂，也应该贴出来。

**Comment by zgxzgxzg** [comment]
辛苦，解决了

**Comment by BrightWade** [comment]
@zgxzgxzg 跟你一样的问题，方便说下怎么解决的吗
