### ISSUE TITLE
AndroidX支持情况

### ISSUE THREAD

**Issue by DaLeiGe** [Tencent/Shadow#154]

**Comment by shifujun** [comment]
我把
https://github.com/android/sunflower
这个应用在Shadow里跑起来了，没什么问题。

这个应用应该是专门用来演示AndroidX的吧？

从原理上来讲，AndroidX对于Shadow来说跟一般的业务代码没什么区别，所以应该是支持的。如果有哪里不支持，应该也只是个别方法没有实现，补充上就可以了。

**Comment by LanJD** [comment]
> 我把
> https://github.com/android/sunflower
> 这个应用在Shadow里跑起来了，没什么问题。
> 
> 这个应用应该是专门用来演示AndroidX的吧？
> 
> 从原理上来讲，AndroidX对于Shadow来说跟一般的业务代码没什么区别，所以应该是支持的。如果有哪里不支持，应该也只是个别方法没有实现，补充上就可以了。

实际上迁移到Androidx 还有很多的工作要做，比如说在Transform的库里要做Androidx 的兼容，其中Androidx的Fragment已经迁移到androidx.fragment.app包中，而android.app包里的Fragment已经被标记为Deprecated，Androidx还是要成为主流，插件虽然可以运行，Fragment的一些生命周期并不会调用，比如onResume()，FragmentTransform里的代码逻辑不适用，他们本也没继承关系，不像Activity，所以要驾驭这个框架，你只能去读懂源码，才能去改成适合你项目的框架

**Comment by shifujun** [comment]
@LanJD 你说的Fragment的onResume()方法不会被调用是对的。不过针对这个问题，也只需要补充Activity壳子上的onPostResume方法回调。我已经提交了b2a0072，也测试了现在Fragment可以收到onResume()方法调用了。

确实像你说的，还有很多工作要做。但并不需要完全读懂AndroidX的源码和设计。实际上我们只需要找到AndroidX对Activity、Service这些Shadow在Runtime中做了中间层实现的类，有哪些依赖就可以了。其余的代码我们不需要理解，那些代码就相当于业务代码而已。比如，我们看AndroidX中，AppCompatActivity是系统Activity的子类。我们就需要看一下它都依赖了哪些Activity的方法。比如它依赖了onPostResume方法，但是PluginContainerActivity并没有继承并转调这个方法，那就会导致AppCompatActivity工作不正常。这跟一个普通的业务自定义了一个Activity并依赖onPostResume方法也会在Shadow中工作不正常是一样的。

那么我们实际上是需要一个Transform逻辑，在Transform过程中去发现插件中使用了哪些中间件的方法，中间件实际上是没有实现的。我相信写出来这个逻辑之后，我们就能确定AndroidX的支持是否完整了。

**Comment by shifujun** [comment]
写了一下检查缺失方法的逻辑。测试了一下sunflower的例子。看起来缺少16个方法的实现。估计实现起来不会太麻烦。

```
Class com.tencent.shadow.core.runtime.ShadowFragment中缺少方法:
getParentFragment:()Lcom/tencent/shadow/core/runtime/ShadowFragment;被这些类调用了:
com.bumptech.glide.manager.RequestManagerFragment_

Class com.bumptech.glide.manager.RequestManagerFragment_中缺少方法:
getParentFragment:()Lcom/tencent/shadow/core/runtime/ShadowFragment;被这些类调用了:
com.bumptech.glide.manager.RequestManagerFragment_

Class com.tencent.shadow.core.runtime.PluginFragmentManager中缺少方法:
getFragment:(Landroid/os/Bundle;Ljava/lang/String;)Lcom/tencent/shadow/core/runtime/ShadowFragment;被这些类调用了:
com.bumptech.glide.manager.RequestManagerRetriever

Class com.tencent.shadow.core.runtime.ShadowActivity中缺少方法:
requireViewById:(I)Landroid/view/View;被这些类调用了:
androidx.core.app.ActivityCompat

In Class androidx.core.app.AppComponentFactory:
instantiateActivity:(Ljava/lang/ClassLoader;Ljava/lang/String;Landroid/content/Intent;)Lcom/tencent/shadow/core/runtime/ShadowActivity;
instantiateApplication:(Ljava/lang/ClassLoader;Ljava/lang/String;)Lcom/tencent/shadow/core/runtime/ShadowApplication;
instantiateService:(Ljava/lang/ClassLoader;Ljava/lang/String;Landroid/content/Intent;)Lcom/tencent/shadow/core/runtime/ShadowService;

In Class androidx.appcompat.app.AppCompatActivity:
onTitleChanged:(Ljava/lang/CharSequence;I)V
openOptionsMenu:()V
closeOptionsMenu:()V

In Class androidx.fragment.app.FragmentActivity:
onPictureInPictureModeChanged:(Z)V
onStateNotSaved:()V
dump:(Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V

In Class androidx.core.app.CoreComponentFactory:
instantiateActivity:(Ljava/lang/ClassLoader;Ljava/lang/String;Landroid/content/Intent;)Lcom/tencent/shadow/core/runtime/ShadowActivity;
instantiateApplication:(Ljava/lang/ClassLoader;Ljava/lang/String;)Lcom/tencent/shadow/core/runtime/ShadowApplication;
instantiateService:(Ljava/lang/ClassLoader;Ljava/lang/String;Landroid/content/Intent;)Lcom/tencent/shadow/core/runtime/ShadowService;

```

**Comment by LanJD** [comment]
> @LanJD 你说的Fragment的onResume()方法不会被调用是对的。不过针对这个问题，也只需要补充Activity壳子上的onPostResume方法回调。我已经提交了b2a0072，也测试了现在Fragment可以收到onResume()方法调用了。
> 
> 确实像你说的，还有很多工作要做。但并不需要完全读懂AndroidX的源码和设计。实际上我们只需要找到AndroidX对Activity、Service这些Shadow在Runtime中做了中间层实现的类，有哪些依赖就可以了。其余的代码我们不需要理解，那些代码就相当于业务代码而已。比如，我们看AndroidX中，AppCompatActivity是系统Activity的子类。我们就需要看一下它都依赖了哪些Activity的方法。比如它依赖了onPostResume方法，但是PluginContainerActivity并没有继承并转调这个方法，那就会导致AppCompatActivity工作不正常。这跟一个普通的业务自定义了一个Activity并依赖onPostResume方法也会在Shadow中工作不正常是一样的。
> 
> 那么我们实际上是需要一个Transform逻辑，在Transform过程中去发现插件中使用了哪些中间件的方法，中间件实际上是没有实现的。我相信写出来这个逻辑之后，我们就能确定AndroidX的支持是否完整了。

哈哈，能理解进去这个框架也是受益匪浅

**Comment by shifujun** [comment]
#166 合入后我认为AndroidX已经完整支持了。希望大家有机会可以测试一下，如果可以贡献一些单元测试就完美了。
