### ISSUE TITLE
插件Activity继承系统中的Activity直接子类，如ListActivity，是不是没有办法通过AOP替换父类？？

### ISSUE THREAD

**Issue by ghhbgtf** [Tencent/Shadow#155]
比如插件ActivityA继承ListActivity，而ListActivity继承Activity，但ListActivity和Activity都在系统中定义，并不会编入apk中吧？这种情况怎么替换ListActivity的父类呢？

**Comment by shifujun** [comment]
这种情况只能专门再为`ListActivity`添加一个`ShadowListActivity`。但是我没注意到系统内置实现中有Activity的子类，主要是因为我们业务不涉及吧。但是有另外一个例子，就是`DialogFragment`。所以runtime里有专门的`ShadowDialogFragment`。就是一般的`Fragment`子类父类替换成`ShadowFragment`，但是`DialogFragment`的子类要替换成`ShadowDialogFragment`。
