### ISSUE TITLE
路径遍历

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/Shadow#159]
https://github.com/Tencent/Shadow/blob/e3263005f5f3c2df65a17eccf62e7596b97a433b/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/CopySoBloc.java#L73-L76
程序在解压zip文件时，由于没有对文件名进行合法性的校验，而是直接将文件名拼接在待解压目录后面，导致可以将文件解压到正常解压缩路径之外并覆盖可执行文件，从而等待系统或用户调用他们实现代码执行（也可能是覆盖配置文件或其他可敏感文件）。

**Comment by shifujun** [comment]
感谢帮助Shadow关注安全问题！

这个Issue提出的问题，按我的理解已经在`SafeZipInputStream`中避免了。如果我没理解错，这个问题也是腾讯内部的安全监测会检查的。

如果不是我理解的问题，能否提供一个具体的例子呢？

**Comment by shifujun** [comment]
如果有补充欢迎再打开。
