### ISSUE TITLE
plugin不存在时，如何获取异常

### ISSUE THREAD

**Issue by ykk0612** [Tencent/Shadow#161]
如题，请教下如果动态加载一个不存在的插件或者插件加载失败（比如找不到文件，文件损坏等）时，怎么捕获异常重新加载或者提示用户稍后再试。

**Comment by shifujun** [comment]
我看了一下代码，这块实现的不是太完整，主要是在动态的、跨进程的封装这块。应该是我们的业务没有特别考虑插件加载失败的场景，大概是因为成功率很高的关系。

具体来说，插件加载有两部分过程。一部分是Manager这边去下载、安装插件，获取本地安装好的插件。第二部分是Loader这边去启动插件。

Manager这边看起来基本实现完了。主要是`com.tencent.shadow.dynamic.host.UuidManager`上的接口会返回`NotFoundException`和`FailedException`。这两种异常时专门实现了跨进程抛出异常的能力的。所以动态加载不存在的插件，应该可以在Manager入口这一侧捕获到这两种异常。

Loader这边看起来就没有实现一样的机制。如果实现的话，应该是在`com.tencent.shadow.dynamic.loader.PluginLoader`上的方法返回类似`UuidManager`上定义的那些自定义异常。用这些可序列化的自定义异常封装`com.tencent.shadow.core.loader.ShadowPluginLoader`上`loadPlugin`方法已经实现的`LoadPluginException`。

所以Loader这边目前只能在插件进程直接捕获`LoadPluginException`来做一些处理。

**Comment by ykk0612** [comment]
我试了下，在Manager中的onStartActivity方法里，executorService.execute方法传入的runnable获取到了空指针异常，然后想捕获异常后返回上一个界面，发现程序在返回界面前就退出了。

这块获取异常后要保证主程序仍正常运行有什么好的办法吗？

**Comment by shifujun** [comment]
你要不传一个例子上来，我看下怎么改。我这两天在写其他东西呢，我要写的话，就再晚些日子。是应该有几个加载失败的场景的测试用例。

**Comment by ykk0612** [comment]
demo这里传不上去啊。
在manager的pluginManager中代码如下：

**Comment by ykk0612** [comment]
private void onStartActivity(final Context context, Bundle bundle, final EnterCallback callback) {
        final String pluginZipPath = bundle.getString(Constant.KEY_PLUGIN_ZIP_PATH);
        final String partKey = bundle.getString(Constant.KEY_PLUGIN_PART_KEY);
        final String className = bundle.getString(Constant.KEY_ACTIVITY_CLASSNAME);
        if (className == null) {
            throw new NullPointerException("className == null");
        }
        final Bundle extras = bundle.getBundle(Constant.KEY_EXTRAS);

        if (callback != null) {
            final View view = LayoutInflater.from(mCurrentContext).inflate(R.layout.activity_load_plugin, null);
            callback.onShowLoadingView(view);
        }

        executorService.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    InstalledPlugin installedPlugin
                            = installPlugin(pluginZipPath, null, true);//这个调用是阻塞的
                    Intent pluginIntent = new Intent();
                    pluginIntent.setClassName(
                            context.getPackageName(),
                            className
                    );
                    if (extras != null) {
                        pluginIntent.replaceExtras(extras);
                    }

                    startPluginActivity(context, installedPlugin, partKey, pluginIntent);
                } catch (NullPointerException e) {
                    Log.d("plugin","starting NullPointerException "+ e.getMessage());
                    throw new RuntimeException(e);
                }catch(ActivityNotFoundException e){
                    Log.d("plugin","starting ActivityNotFoundException "+ e.getMessage());
                    if (callback != null) {
                        Handler uiHandler = new Handler(Looper.getMainLooper());
                        uiHandler.post(new Runnable() {
                            @Override
                            public void run() {
                                final LinearLayout linearLayout = new LinearLayout(context);
                                linearLayout.setOrientation(LinearLayout.VERTICAL);

                                TextView textView = new TextView(context);
                                textView.setText("插件未找到，请稍后重试");

                                linearLayout.addView(textView);

                                callback.onShowLoadingView(linearLayout);
                                Toast.makeText(context, "插件未找到，请稍后重试。", Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                    throw new RuntimeException(e);
                } catch(Exception e){
                    Log.d("plugin","starting Exception "+ e.getMessage());
                    throw new RuntimeException(e);
                }

                if (callback != null) {
                    Handler uiHandler = new Handler(Looper.getMainLooper());
                    uiHandler.post(new Runnable() {
                        @Override
                        public void run() {
                            callback.onCloseLoadingView();
                            callback.onEnterComplete();
                        }
                    });
                }
            }
        });
    }

**Comment by ykk0612** [comment]
NullPointerException 和 ActivityNotFoundException 都试了，但因为不在一个线程中，操作不来哦。

**Comment by shifujun** [comment]
你先fork这个仓库到你自己名下。然后clone下来，新建一个分支，做复现问题的修改，提交，push到你自己的仓库中。然后把你的分支告诉我，我就可以fetch你的分支了。然后我就能具体看到你改了sample的哪些行，试图做什么，跑起来也能复现问题。

**Comment by ykk0612** [comment]
https://github.com/ykk0612/Shadow.git  新建分支https://github.com/ykk0612/Shadow/tree/dynamic 有我写的测试代码。

主要修改了projects/sample/maven/下的host-project和manager-project

**Comment by shifujun** [comment]
我clone下来跑了一下，能正常启动插件。大概看了一下代码，你改了很多Manager的更新逻辑，似乎和你说的插件不存在或者启动失败的场景没关系。能不能再试试，做一个只跟问题相关的修改，比如manager的更新逻辑似乎是不必要的，关键是最后运行起来是复现问题的，是crash了或者插件没启动起来也没反应之类的场景。

**Comment by ykk0612** [comment]
这个测试主要就是在本地（data/local/tmp）下没有plugin-debug.zip的时候，startPluginActivity就会报错（NullPointerException，ActivityNotFoundException。。。）。这个案例就是想处理在加载plugin（plugin-debug.zip不存在）报错的时候，保证程序正常运行。

现在的现象是 data/local/tmp下没有plugin-debug.zip文件，加载报错，然后程序就直接退出了。我尝试使用uiHandler在ui做提示也运行不了。

**Comment by shifujun** [comment]
你这样说是说不清楚的，还是要看代码。你以为你说的场景是唯一的，实际上有很多理解。

如果说插件文件不存在，那你只需要在调用`com.tencent.shadow.core.manager.BasePluginManager#installPluginFromZip`之前判断文件是否存在就可以了。

**Comment by ykk0612** [comment]
好的，我再完善下吧，谢谢。
