### ISSUE TITLE
有个不太成熟的想法

### ISSUE THREAD

**Issue by fettdrac** [Tencent/Shadow#162]
如果允许对插件包本身做修改，是不是可以把插件字节码编辑的逻辑放到插件加载前，那么是不是可以就可以加载任意apk的了呢
不过这样的话，编辑对象变成了dex，目前我也不了解有这种解决方案

**Comment by shifujun** [comment]
很多人有这种想法。不过讨论的话，它从需求到实现都有很多问题。

需求上，应用本身并不想让你当成插件启动，非要把它当做插件启动起来，这种场景很少。我能想到的只有那种双开微信的沙箱运行需求。从应用本身考虑，希望提高的是入口的转化率，希望用户能不看到安装界面就运行起来，希望能先下载一部分就启动一部分。应用有这种诉求，是可以付出一些工作量的。我们只需要尽量减少这种工作量就可以了。像Shadow这样，让应用在编译时接入一个插件，基本上不修改源代码，让应用接入时的工作量很小，这样就可以了。

还有一方面问题是dex格式虽然是开源的，但它不属于公开的API。在后续的Android版本中，dex格式可能会修改的。所以做这种方案，虽然将应用接入的工作量减少到几乎没有了，但也带来了未来维护的成本，这属于技术债。

所以，不能简单的将Shadow理解成用字节码编辑手段做的插件框架。更重要的是Shadow是坚持不使用非公开API的实现方案。不使用非公开API意味着同一个插件代码未来运行在更高版本的Android系统上，只要Android系统的API不做不兼容变更，Shadow的代码是不需要维护的。

**Comment by fettdrac** [comment]
大佬回复真快!
运营的需求上来说确实没有必要(我可能对灵活性有点强迫症)
但是实现上来说，dex文件结构本身不太可能修改，因为绝大部分APP都使用dex，android和厂商需要考虑向下兼容问题，rom也只是对运行时结构做调整，文件通用，未来对dex的适配工作个人感觉和适配public api的修改差不多
后来仔细一想也有弊端，如果app加固的话，直接编辑dex显然是行不通的，尤其是指令抽取壳，适配的话又回到了黑科技的老路
