### ISSUE TITLE
插件中怎么获取宿主application

### ISSUE THREAD

**Issue by ykk0612** [Tencent/Shadow#169]
如题

**Comment by shifujun** [comment]
插件application的baseContext应该就是。

虽然这么说，但依赖这一点并不好。应该由宿主和插件直接约定接口来实现这一交互。

**Comment by ykk0612** [comment]
manger中是否可以获取到宿主的application呢？
之前把插件路径写在了application.getApplicationContext().getFilesDir().getAbsolutePath()下。

**Comment by ykk0612** [comment]
manager下貌似只能获取到context，要是不行，就只能全部改成context获取路径试试了
