### ISSUE TITLE
编译不通过过

### ISSUE THREAD

**Issue by mayi203** [Tencent/Shadow#173]
> Task :sample-plugin-app:transformClassesWithShadowTransformForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-plugin-app:transformClassesWithShadowTransformForRelease'.
> java.util.zip.ZipException: duplicate entry: android/support/v7/app/ActionBar$DisplayOptions.class

**Comment by shifujun** [comment]
我在最新的dev分支上复现不了

```
./gradlew clean
./gradlew :sample-plugin-app:transformClassesWithShadowTransformForRelease
```

**Comment by mayi203** [comment]
./gradlew build 会报上面的错误。单独 ./gradlew :sample-plugin-app:transformClassesWithShadowTransformForRelease 可成功 。。。

**Comment by shifujun** [comment]
应该是最近的修改造成的。我会在合入master前修复好的。
