### ISSUE TITLE
插件的 setSupportActionBar 调用了被代理到宿主的 invalidateOptionsMenu 方法

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#183]
```setSupportActionBar(toolbar: androidx.appcompat.widget.Toolbar) ```是 androidx 的方法，没有被代理。但是它里面调用了```invalidateOptionsMenu``` 方法，是被代理到宿主的，于是显示异常了。
这种情况应该怎么处理

**Comment by shifujun** [comment]
能不能在sunflower里加一段示例代码说明问题？

**Comment by donglua** [comment]
#185

**Comment by donglua** [comment]
![image](https://user-images.githubusercontent.com/3875265/69498407-cc5a5c00-0f22-11ea-80c6-12958b42e229.png)
![image](https://user-images.githubusercontent.com/3875265/69498415-db410e80-0f22-11ea-8240-04fb76416f7a.png)

**Comment by donglua** [comment]
![XiaoYing_Video_1574616330566](https://user-images.githubusercontent.com/3875265/69498480-66ba9f80-0f23-11ea-9bcc-6c369ea2dd65.gif)
![XiaoYing_Video_1574616413787](https://user-images.githubusercontent.com/3875265/69498484-6cb08080-0f23-11ea-9e6a-490bd6960a7d.gif)

**Comment by shifujun** [comment]
@donglua 你提供的演示代码和操作录像非常棒！如果大家反馈的问题都是这样提供的，我基本上都能很快帮大家解决。

那个PR不是必要的，只需要将你fork库的地址和分支贴出来就足够了。

动画录像非常棒，就是怕你录制比较麻烦，像这样简单的点击操作如果能描述出来，也是够用的。

最关键的还是复现问题的代码。解决问题后，我们可以发现问题跟你最初描述的`invalidateOptionsMenu`完全没有关系的。你贴出代码以后，我简单Debug了一下不使用Shadow情况下的调用栈，然后在Shadow环境下去一样的调用栈里步进一下就很快解决了。

**Comment by donglua** [comment]
我发现出现我一开始描述的情况是由于我试图把 AndroidX 从插件里剔除，共用宿主的代码，减少插件体积，在白名单里加了以下代码：
```
"androidx.core.text",
"androidx.core.text.**",
"androidx.appcompat.widget",
"androidx.appcompat.widget.**",
```
然后出现了 Toolbar 事件失效、按键错位的情况，在 sunflower 里只重现了点击事件失效的问题。
我把以上白名单的代码删除解决了问题，因为插件 Activity 都被替换了，估计很难解决插件和宿主共用一套UI库的问题。

**Comment by shifujun** [comment]
> 我发现出现我一开始描述的情况是由于我试图把 AndroidX 从插件里剔除，共用宿主的代码，减少插件体积，在白名单里加了以下代码：
> 
> ```
> "androidx.core.text",
> "androidx.core.text.**",
> "androidx.appcompat.widget",
> "androidx.appcompat.widget.**",
> ```
> 
> 然后出现了 Toolbar 事件失效、按键错位的情况，在 sunflower 里只重现了点击事件失效的问题。
> 我把以上白名单的代码删除解决了问题，因为插件 Activity 都被替换了，估计很难解决插件和宿主共用一套UI库的问题。

如果宿主里的androidx和插件想用的确实是一个版本，而且又都没混淆，应该是可以用的。我估计是版本不一致造成的吧。

**Comment by donglua** [comment]
这个共用代码的问题我再把 sunflower 改造一下，重新提 issue 上来。
