### ISSUE TITLE
runtime和container拆分后带来的问题

### ISSUE THREAD

**Issue by pzhangleo** [Tencent/Shadow#192]
打包plugin时候报错
Class com.tencent.shadow.core.runtime.ShadowActivity中缺少方法:
registerActivityLifecycleCallbacks:(Lcom/tencent/shadow/core/runtime/ShadowActivityLifecycleCallbacks;)V被这些类调用了:
androidx.lifecycle.ProcessLifecycleOwner$3
androidx.lifecycle.ReportFragment_

在增加这个方法的时候，发现ShadowActivityLifecycleCallbacks放在了runtime包中，activity的registerActivityLifecycleCallbacks是android sdk 29新增的api

**Comment by shifujun** [comment]
这不是拆分runtime和container带来的问题吧？

你是不是就是在插件中新加了`registerActivityLifecycleCallbacks`方法调用啊？那样的话，拆分前也会有问题的。应该就是没实现而已。

我晚点复现试试吧。但是你最好能贴上示例的代码。

**Comment by shifujun** [comment]
不知道你用的AndroidX的lifecycle是什么版本的。sunflower目前用的版本是`2.2.0-alpha01`，这个版本是用SDK28编译的，所以没有用这个新增的方法。

不过这个方法支持还是很简单的，所以我就直接加上了。你再试试吧。

**Comment by pzhangleo** [comment]
啊哈，反馈真快，我的lifecycle是2.2.0-rc02，sdk29编译出的问题，我这边也尝试改好了，倒是好改，就是反馈下，让更多人注意这个。

**Comment by shifujun** [comment]
我最近在写自动化生成这些代码的重构了，等写好了，应该就不会有这种问题了。
https://github.com/Tencent/Shadow/pull/194

**Comment by pzhangleo** [comment]
恩，自动化处理下就方便多了。👍
