### ISSUE TITLE
ShadowInstrumentation类缺少方法

### ISSUE THREAD

**Issue by rangerTao** [Tencent/Shadow#195]
greendao库中，引用到了Instrumentation类中的newApplication方法
    static public Application newApplication(Class<?> clazz, Context context)
            throws InstantiationException, IllegalAccessException, 
            ClassNotFoundException {
        Application app = (Application)clazz.newInstance();
        app.attach(context);
        return app;
    }
但是这个方法是static的，引用不到。
这个怎么能解决呢？

**Comment by rangerTao** [comment]
Class com.tencent.shadow.core.runtime.ShadowInstrumentation中缺少方法:
newApplication:(Ljava/lang/Class;Landroid/content/Context;)Lcom/tencent/shadow/core/runtime/ShadowApplication;被这些类调用了:
de.greenrobot.dao.test.DbTest

补充错误信息

**Comment by rangerTao** [comment]
@shifujun 大佬有时间看下吗？

**Comment by shifujun** [comment]
这个你不能按照提示自己实现缺失的方法吗？我确实最近没时间，我最近有的一点时间都在做自动生成这些缺失的方法上了。但是那个还要一些日子才能搞定。

**Comment by rangerTao** [comment]
啊，好惭愧。我试着自己实现了一下。但是这个方法在父类里是static的，无法覆盖。

**Comment by shifujun** [comment]
如果只是因为这个检查不通过阻塞你了，你可以先注释掉这个检查。

https://github.com/Tencent/Shadow/blob/dev/projects/sdk/core/transform-kit/src/main/kotlin/com/tencent/shadow/core/transform_kit/AbstractTransform.kt#L73

**Comment by shifujun** [comment]
如果实现的话，不是说要覆盖哪个方法，而是在ShadowInstrumentation中添加newApplication方法。

**Comment by rangerTao** [comment]
多谢解答。我先暂时在检查的位置，通过硬编码跳过了。
