### ISSUE TITLE
部分手机调用插件时崩溃异常信息为：android.os.DeadObjectException

### ISSUE THREAD

**Issue by guoyanfangabcd** [Tencent/Shadow#196]

**Comment by guoyanfangabcd** [comment]
机型为：HUAWEI nova  3e       android版本：9

**Comment by shifujun** [comment]
DeadObjectException只是操作跨进程binder时调用侧的异常。你得去对面的进程看实际的异常信息。

**Comment by shifujun** [comment]
和#198 应该是同一个问题。

这行注释掉试试
https://github.com/Tencent/Shadow/blob/dev/projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/HostApplication.java#L47

**Comment by guoyanfangabcd** [comment]
是的，注释掉就好了，谢谢大神~
