### ISSUE TITLE
引入gson后无法编译

### ISSUE THREAD

**Issue by LanJD** [Tencent/Shadow#200]
今天有空继续研究了下这个框架，发现插件引入gson（implementation 'com.google.code.gson:gson:2.8.5'）后无法通过编译了，发现有个checkOverrideMethods方法，不知道这个方法编译检查的逻辑是不是有问题，不太明白了

In Class com.google.gson.DefaultDateTypeAdapter 这些方法不再Override父类了:
read:(Lcom/google/gson/stream/JsonReader;)Ljava/lang/Object;(转换前定义在com.google.gson.TypeAdapter)
write:(Lcom/google/gson/stream/JsonWriter;Ljava/lang/Object;)V(转换前定义在com.google.gson.TypeAdapter)

In Class com.google.gson.Gson$1 这些方法不再Override父类了:
read:(Lcom/google/gson/stream/JsonReader;)Ljava/lang/Object;(转换前定义在com.google.gson.TypeAdapter)
write:(Lcom/google/gson/stream/JsonWriter;Ljava/lang/Object;)V(转换前定义在com.google.gson.TypeAdapter)

**Comment by shifujun** [comment]
那看起来确实是有bug。我在那段代码里hardcode了忽略kotlin包的类，应该也是因为逻辑有bug，不能处理kotlin的情况。

**Comment by LanJD** [comment]
> 有bug。我在那段代码里hardcode了忽略kotlin包的类，应该也是因为逻辑有bug，不能处理kotlin的情况

去掉检查失败抛的异常逻辑，插件能正常运行，gson也能正常工作，前后编译的字节码也一样，不知道是不是这个方法上的泛型引起的bridge synthetic

**Comment by shifujun** [comment]
修好了。是泛型方法的问题。
