### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by JohnLie** [Tencent/Shadow#204]
gradle 版本太低了

**Comment by shifujun** [comment]
哪个工程编译不通过？哪个工程的Gradle版本太低了？你是否有改任何代码？你的代码在哪里？编译不通过的错误日志在哪里？

**Comment by JohnLie** [comment]
* What went wrong:
A problem occurred configuring project ':sample-plugin-app'.
> Could not open proj remapped class cache for aotm4qs42ix4mtncjxpou4vpr (C:\Use
rs\Administrator\.gradle\caches\5.0\scripts-remapped\build_2mll753ljyqxb2yqp2xgm
xkbh\aotm4qs42ix4mtncjxpou4vpr\proj9b02549b227e12b42fe2f5001e3ab409).
   > Could not open proj generic class cache for build file 'C:\PandaWork\code\S
hadow-dev\projects\sample\source\sample-plugin\sample-plugin-app\build.gradle' (
C:\Users\Administrator\.gradle\caches\5.0\scripts\aotm4qs42ix4mtncjxpou4vpr\proj
\proj9b02549b227e12b42fe2f5001e3ab409).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript
_' Unsupported class file major version 57

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:comman
d_line_warnings

**Comment by shifujun** [comment]
> Java 13 uses major version 57

不知道你到底改了什么会去引用java 13编译出的类。如果你使用jdk 13编译的，麻烦换成jdk 8。jdk 13还没有测试过。
