### ISSUE TITLE
dev分支执行 ./gradlew clean build 失败

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#207]
仓库：https://github.com/JingZhuanDuoYing/Shadow/tree/release （代码无改动，加了travis-ci 和bintray依赖）
构建日志：https://travis-ci.org/JingZhuanDuoYing/Shadow

**Comment by shifujun** [comment]
clean和build一起传给gradle表示并发执行它们。不能这样做。

**Comment by donglua** [comment]
好的，我改改成```./gradlew clean &&  ./gradlew build ```可以了
