### ISSUE TITLE
projects\sample\maven\plugin-project>插件编译失败

### ISSUE THREAD

**Issue by JohnLie** [Tencent/Shadow#208]
> Task :plugin-shadow-apk:transformClassesWithShadowTransformForDebug
android.support.v4.content.FileProvider matchMethodCallInClass :loadXmlMetaData  =================
t2:2061

> Task :plugin-shadow-apk:transformClassesWithShadowTransformForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugin-shadow-apk:transformClassesWithShadowTransformForDebug'.
> javassist.NotFoundException: android.preference.PreferenceFragment_

**Comment by shifujun** [comment]
我在dev分支最新版本 bf3c640b 上没能复现。你改了什么吧？如果改任何东西，提issue的时候最好贴出来。

**Comment by shifujun** [comment]
同#243
