### ISSUE TITLE
大佬能加我QQ请教一下吗？

### ISSUE THREAD

**Issue by JohnLie** [Tencent/Shadow#209]
871878482

**Comment by shifujun** [comment]
开源项目的问题交流应该是公开的，内容沉淀的。

有任何关于Shadow的问题，首选的交流方法是：Fork Shadow的代码库，在Fork的库中添加复现问题的提交，提Issue，附上Fork的代码库和分支链接，描述清楚复现问题该如何操作，以及清晰的指出你认为的问题是什么。
