### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by wgypaul** [Tencent/Shadow#210]
用./gradlew build在windows下编译通过了，把代码import到AndroidStudio出现Cannot access first() element from an empty Iterable这样的错误，请问我该怎么改
![image](https://user-images.githubusercontent.com/58688477/70429843-6fc77700-1ab4-11ea-8ea1-e3f83a122896.png)

**Comment by shifujun** [comment]
应该是ide使用的问题。你注意让ide用项目的gradle wrapper，不要自行指定gradle版本。

**Comment by shifujun** [comment]
如果还有问题，请参考
https://github.com/Tencent/Shadow/blob/dev/CONTRIBUTING.md#issue
再重新打开Issue。
