### ISSUE TITLE
主题属性 android:fontFamily 设置字体资源无效

### ISSUE THREAD

**Issue by ChanNagihong** [Tencent/Shadow#211]
机型环境: AS内置虚拟机，Pixel, Android 8.1(Google APIs), x86
在 Shadow/projects/sample/source/sample-plugin/sample-app-lib/src/main/res/values/themes.xml
的 TestPluginTheme 主题中添加字体资源  
`
<item name="android:fontFamily">@font/xxoo</item>
`  
运行Demo后发现独立运行时正常的，但以插件方式打开却没有了效果。

**Comment by shifujun** [comment]
嗯？没问题了吗？

**Comment by ChanNagihong** [comment]
我发现问题在于
在 sample-app-lib 的 AndroidManifest.xml 中，为 application 随便写一个有字体的theme, 
`
<item name="android:fontFamily">@font/xxoo</item>
`
不论是插件运行还是独立运行，都是不生效的。

**Comment by shifujun** [comment]
嗯。那我先不看了。如果能复现的话，麻烦把修改的sample地址和分支发一下。到时候我可以直接调试。

**Comment by ChanNagihong** [comment]
[Shadow copy.zip](https://github.com/Tencent/Shadow/files/3943877/Shadow.copy.zip)
我直接压缩了工程，直接打开可以用的。Git保留了我改动的几个文件

**Comment by shifujun** [comment]
> [Shadow copy.zip](https://github.com/Tencent/Shadow/files/3943877/Shadow.copy.zip)
> 我直接压缩了工程，直接打开可以用的。Git保留了我改动的几个文件

这样我看不出你改了什么啊。用Github就应该fork版本库，新建分支，提交。

**Comment by ChanNagihong** [comment]
抱歉，第一次使用，不知道对不对。我提交了
https://github.com/Tencent/Shadow/pull/213

**Comment by shifujun** [comment]
没关系哈。习惯Github的交流方式就好了。

Shadow的问题，你就fork之后，提交一个修改。确定这个修改在独立安装没问题，插件环境下有问题。然后把链接贴到Issue里就行了。也不用提PR。

**Comment by donglua** [comment]
#214
