### ISSUE TITLE
声明系统权限是出现崩溃

### ISSUE THREAD

**Issue by wgypaul** [Tencent/Shadow#215]
您好，我把shadow声明成系统应用并进行系统签名后运行，点击启动插件后程序崩溃。查看日志提示：For security reasons, WebView is not allowed in privileged processes，此提示是在framwork中
![image](https://user-images.githubusercontent.com/58688477/70586140-45370480-1c01-11ea-8232-0a24fe541475.png)
请问，如果我要如何修改框架才能避免出现崩溃的情况呢？

**Comment by shifujun** [comment]
这个玩法有点高级啊。

如果是跟WebView相关的话，你先把 fb2da721715abddd618b8d585b6f222d24459104 Revert掉试试。

**Comment by wgypaul** [comment]
好的，非常感谢您耐心指导，我先去试试

**Comment by wgypaul** [comment]
Revert后可以正常运行，谢谢您
