### ISSUE TITLE
Maven依赖的疑问和建议

### ISSUE THREAD

**Issue by bm-x** [Tencent/Shadow#219]
我阅读了下simple中README.md的介绍，翻阅了下issues。
Shadow是希望我们真正使用的时候，自己编译一份Shadow SDK发布到自己的maven仓库中。
如 
host-project ： com.tencent.shadow.dynamic:host:x.x.x
manager-project : com.tencent.shadow.dynamic:manager:x.x.x 
这些库，都是要自己编译且发布到自己的maven仓库中是么？

我能理解可能一些大项目中涉及到一些比较复杂的业务需求和场景，但是我觉得可能绝大部分真正使用到的只是想以插件化的方式带来的热更的功能。估计很多人会连manager都不写直接一个plugin,然后在宿主做更新检测。

建议Shadow能否以稳定的分支发一个默认的二进制依赖呢？包括plugin中的loader和runtime (其实我暂时没搞清这两个模块的用处是啥，注释都写着固定类名固定包名，那岂不是没有特殊需求也可以发一个默认的二进制包？)

**Comment by shifujun** [comment]
> 这些库，都是要自己编译且发布到自己的maven仓库中是么？
是的。`maven.gradle`中已经写好了所有的发布配置，只需要你换成自己的groupId和仓库地址就行了。

Shadow不发布一个公共的二进制主要考虑到发布了也不会有太大用。有这么几个原因：

1. 我们认为插件框架技术很难包装成一个简单易用的SDK，使用插件框架技术的人对插件框架的实现机制应该是比较清楚的，才能够正常使用。因为业务的场景太复杂多变了，SDK很难一次性做好，不论哪个业务接入，总会有一些问题要解决。开源Shadow，而不是发布一个二进制的Shadow，可以让大家在有问题时方便相互交流，也可以自行修改。

1. Shadow的这种全动态的插件框架，实际上把插件框架做成了插件的一部分。这样在处理一些紧急异常情况时可以在插件框架中hardcode一些临时解决方案，而不影响其他业务。比如，某个新发布的手机系统造成的功能失效等。要利用这种能力，也需要业务的插件框架是自己编译发布的。

1. 通用的Shadow也不是理论上做不出来。最近WIP的那个PR就试图一次性解决所有没有实现完全的方法。但是那样可能会把插件框架的安装包体积撑大。插件这种动态加载的业务，对安装包体积要求非常严苛，所以一般使用的业务也会自行裁剪一些不需要的功能。比如我们的业务就没有使用ContentProvider。

1. 通用的二进制提供出来，还代表一种服务。而我们目前没有人力能够支撑这种服务。在腾讯内部，各个业务也是自行维护自己在使用的Shadow的。不过我们会通过这个Github的开源库来交流代码和问题的解决方案。各个业务只是针对自身需要做一些改动。
