### ISSUE TITLE
transform-kit 是否存在 ReplacePackageName?

### ISSUE THREAD

**Issue by vvVenom** [Tencent/Shadow#225]
transform-kit 中提供了 ReplaceClassName，但这似乎只能指定单个类而不能指定某个包下的所有类，有没有什么方法可以做到这个

例如：
com.a.b.* > my.a.b.*

**Comment by shifujun** [comment]
没有。如果做这种事，用proguard可能更合适。

**Comment by vvVenom** [comment]
> 没有。如果做这种事，用proguard可能更合适。

感谢，最后我通过 transform api 来记录包下的所有 className 后递归替换。
