### ISSUE TITLE
transform-kit-test 为什么需要被打包到 Maven，它有什么作用

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#226]
![image](https://user-images.githubusercontent.com/3875265/71344709-402d6a00-259e-11ea-9ff4-37c7389ce5d1.png)

**Comment by shifujun** [comment]
因为`transform`模块的`test`代码要依赖`transform-kit`模块的`test`代码，比如`SimpleRenameTransformTest`的父类是`AbstractTransformTest`。

在Shadow中没有通过Maven依赖，而是这样写的
```
testCompile project(path: ':transform-kit', configuration: 'tests')
```
如果是Maven依赖，就需要用到这个Maven构件了。

所以发布`transform-kit-test`可以作为使用`transform-kit`的功能的测试代码的依赖。
