### ISSUE TITLE
下载源码build完，用as打开项目出错了

### ISSUE THREAD

**Issue by fighter576133402** [Tencent/Shadow#228]
Could not find com.tencent.shadow.core:runtime-debug:.
Required by:
    project :sample-plugin-app
Search in build.gradle files

**Comment by shifujun** [comment]
我估计应该还是有部分构建失败了吧。命令行运行gradlew build已经成功的话，确认下AS的版本是不是高于3.4了。

还有，这是个复合构建，可能第一个错误不是你贴出来的这个。

**Comment by fighter576133402** [comment]
升级了一下as到3.5.3 可以了

**Comment by shifujun** [comment]
好的，那这个issue就关了。
