### ISSUE TITLE
Shadow不支持Service设置Foreground和IntentService吗

### ISSUE THREAD

**Issue by xprhs** [Tencent/Shadow#229]
如题

**Comment by shifujun** [comment]
没有实现，因为我们业务暂时没有这个需求。

如果要实现的话，Foreground都去操作PPS这个真正的Service就可以了。PPS需要融合多个插件Service的Foreground状态。IntentService比较好实现，就把系统的IntentService代码复制到Shadow里就行了，就相当于一个普通的抽象Service而已。

**Comment by xprhs** [comment]
IntentService我自己弄了一下，比较简单，Foreground没太明白你的思路，我再研究研究

**Comment by xprhs** [comment]
Foreground这个使用场景还是蛮多的

**Comment by shifujun** [comment]
就是Foreground这件事是Service在跟系统交互。而我们只有一个Service是真的Service，就是PPS。PPS为其他插件Service提供的Binder。

所以插件Service要表现出Foreground的特性，就需要通过PPS去跟系统交互。比如两个插件Service其中有一个要表现成Foreground，就需要让PPS去替它跟系统表现成Foreground。

如果涉及到多个Foreground的插件Service要有不同的通知栏表现。可能我们就需要考虑用多个PPS去代理插件Service了。

**Comment by xprhs** [comment]
晓得了
