### ISSUE TITLE
从后台下载插件

### ISSUE THREAD

**Issue by UserWang** [Tencent/Shadow#23]
请问，目前是需要我们自己实现从后台下载插件包的功能是么？后面官方有计划补充上这个功能么？

**Comment by shifujun** [comment]
对。现在开源的代码中Manager只实现了下载好插件包之后的事情，包括安装和升级之类的本地功能。

版本检查和下载是需要业务方继承SDK的Manager然后实现的。

这部分功能我们是有计划开源的，我们肯定是希望开源出来，让大家跟我们用同一套实现，这样才有可能公共维护。

**Comment by UserWang** [comment]
> 对。现在开源的代码中Manager只实现了下载好插件包之后的事情，包括安装和升级之类的本地功能。
> 
> 版本检查和下载是需要业务方继承SDK的Manager然后实现的。
> 
> 这部分功能我们是有计划开源的，我们肯定是希望开源出来，让大家跟我们用同一套实现，这样才有可能公共维护。

好的，了解了。谢谢回复！
