### ISSUE TITLE
code-generator 生成的代码包含高版本API引入的新类型，低版本手机会Crash

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#230]
![image](https://user-images.githubusercontent.com/3875265/71505313-a294ac00-28b7-11ea-9fce-bce9b6ed5143.png)

```
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 19 more
    		Suppressed: java.lang.ClassNotFoundException: java.util.function.Consumer
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
```

**Comment by shifujun** [comment]
这还真是个问题。就算是手工添加这个代码也有这个问题。

我们声明一个假的接口定义怎么样？正常来说，ClassLoader走双亲委派逻辑不会加载我们自带的假接口的。

**Comment by donglua** [comment]
![image](https://user-images.githubusercontent.com/3875265/71506659-d7573200-28bc-11ea-8dfd-d4c08695e880.png)


可以，像AndroidX里也是这么做的

**Comment by shifujun** [comment]
你测试一下#231的改动有没有解决你的问题。

这个修复还是不完全。我这里API19的模拟器还是会Crash，应该是还有需要补充的类定义。但是API19的Crash日志非常不友好，看不到是什么类型找不到。这个要花点时间逐个类去确认。需要把Activity import的类中API14之后引入的类型都这样定义出来才行。

**Comment by shifujun** [comment]
- [ ] 用Javassist对比一下API14和API29的Activity.class的RefClass

**Comment by shifujun** [comment]
通过这个链接逐个从21查看到15，手工找出了所有14以后新增的类型
https://developer.android.com/sdk/api_diff/21/changes

我认为类似的问题应该是都解决了。

如果还有类似问题随时再打开issue。

**Comment by donglua** [comment]
目前测试没有问题。

**Comment by donglua** [comment]
#234

**Comment by shifujun** [comment]
因为引入那些stub系统类造成Proguard又报错，我又细查了一下这个问题。

实际上不是简单的我们的类添加了一个方法，方法的签名上存在找不到的类就会出错。只要方法不被调用，就不会有问题。Activity上新版本增加的方法都属于这种，因为在低版本上根本不会被调用，所以是安全的。因此前面那样无脑的补充上所有新版本新增的类型是没必要的。

这里之所以会Crash，实际上是因为loader中的`ShadowActivityDelegate`实现需要在`PluginContainerActivity`中转换为`HostActivityDelegate`接口使用，而这个`HostActivityDelegate`接口和`ShadowActivityDelegate`实现处于两个不同的ClassLoader中。这样就会触发一种检查：
https://cs.android.com/android/platform/superproject/+/master:art/runtime/class_linker.cc;l=5744
在这个检查中，虚拟机会查验每一个接口的方法跟实现的方法签名是否一致，一致的前提之一自然是签名上的类型是一致的。而且我们知道在java里类型一致的前提是ClassLoader一致。因此它去加载类了。

所以实际上，就算是采用签名stub系统类的方法，也只需要补充出现在`HostActivityDelegate`接口中的新类型。

先把原因记录下来，reopen这个issue。下面考虑这里是不是把这些新增类型在签名中改成`Object`就可以了，因为都是转调，类型是什么也不太重要。
