### ISSUE TITLE
宿主加入 activity-container 依赖后，编译出错

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#234]
宿主里用到```ActivityManager```的 getRunningServices，编译时报
```
Unresolved reference: getRunningServices
```
和```activity-container```里的 ```ActivityManager```接口有冲突

**Comment by shifujun** [comment]
帮我试一下以’ runtimeOnly’方式依赖activity-container是否可以解决问题好吗？我现在身边没电脑。

**Comment by shifujun** [comment]
回来看了一下代码，`runtimeOnly `依赖`activity-container`还不行。看来必须要把那些假定义的类独立成一个jar包，再让宿主`runtimeOnly `依赖打包进去才行了。

**Comment by shifujun** [comment]
我在`test-none-dynamic-host`中复现不了这个问题，但我相信问题应该是存在的。可能编译期按什么规则随机选择了重名的类，我这里选到的是系统的正确实现，所以编译正常。

还是麻烦你验证一下是否修复了吧，理论上应该是修复了的。
