### ISSUE TITLE
java.lang.ClassCastException: com.facebook.drawee.generic.GenericDraweeHierarchy cannot be cast to com.facebook.drawee.interfaces.DraweeHierarchy

### ISSUE THREAD

**Issue by donnyisgood** [Tencent/Shadow#237]
在宿主中继承开源库的一个类，在插件app中调用宿主api实例化该类时，传入参数报错java.lang.ClassCastException: com.facebook.drawee.generic.GenericDraweeHierarchy cannot be 
cast to com.facebook.drawee.interfaces.DraweeHierarchy
如果将宿主中的子类移至插件中，不涉及宿主调用的话，则不存在该问题

问题代码提交地址为https://github.com/donnyisgood/Shadow/tree/issue/generics

**Comment by shifujun** [comment]
我最近在休假，手边没电脑。

这个类是什么系统类的子类吗？

你是否设置了插件访问宿主类的白名单呢？注意如果没有，堆栈上应该有找不到类的错误。

**Comment by donnyisgood** [comment]
涉及到的是开源库fresco里的类，具体是其中有一个类A，宿主中类B继承了A，它的构造方法的参数中有一个类型为DraweeHierarchy，在插件中传入GenericDraweeHierarchy类型的对象即报上述错误，在fresco中，GenericDraweeHierarchy是DraweeHierarchy的子类
访问宿主的白名单已在hostWhiteList中配置过

**Comment by donglua** [comment]
插件里的 DraweeHierarchy 和宿主里的 DraweeHierarchy 已经不是同一个类了。
参考： #187

**Comment by donnyisgood** [comment]
我理解的#187 的case中是系统类CoreComponentFactory在插件构建过程中被transform了，而DraweeHierarchy不属于系统类，应该没有被transform才对

**Comment by donglua** [comment]
我看到包含了 Drawable，Drawable 里引用的 Resources 是被 transform 的。

**Comment by donnyisgood** [comment]
读了下源码，之前对Shadow框架的ClassLoader的理解有偏差

问题原因是我在插件依赖中也`implementation`了这个开源库，并且没有将开源库的包名加到宿主白名单，这样插件中用到的开源库类和宿主中不是同一个ClassLoader加载的

将开源库的包名加到宿主白名单中，使插件运行时由宿主ClassLoader加载这个类，问题已解决
