### ISSUE TITLE
android7.0加载动态库失败

### ISSUE THREAD

**Issue by yinmingxuan** [Tencent/Shadow#239]
01-06 11:31:31.742  6012  6012 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.android.vpsclient/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/lib/F084B6E6-B2E5-4DA0-BF49-58B247DE1E80_lib/libvpsc.so" **has invalid shdr offset/size**

**Comment by shifujun** [comment]
你不能指望我从这几行log就复现问题呀。

附上可以复现问题的代码库。

**Comment by yinmingxuan** [comment]
so库就一个测试的函数，我在插件里用System.loadLibrary("vpsc")测试的。
不清楚shadow怎么处理so库的，我看到apk里已经打包了so，但是，ShadowPluginManager/UnpackedPlugin下面没有，于是我手动拷贝过去，然后修改so的权限进行测试的。
![image](https://user-images.githubusercontent.com/30332644/71860480-0e83d980-312e-11ea-9c9b-d29964355461.png)

在shadow代码里没找到插件里加载so的例子呀，能否说明一下？

测试用的so库：
[libvpsc.zip](https://github.com/Tencent/Shadow/files/4028474/libvpsc.zip)

**Comment by yinmingxuan** [comment]
修改SamplePluginManager的getAbi后已经解决了。
![image](https://user-images.githubusercontent.com/30332644/71862215-1181c880-3134-11ea-8ba4-5d7dc6c317d3.png)
