### ISSUE TITLE
关于Fragment实现的疑惑

### ISSUE THREAD

**Issue by onlylikews** [Tencent/Shadow#24]
目前Fragment的实现方式导致无法直接调试，我想请问一下能否类似Activity一样通过转调方式实现，保留原有的fragment class类呢？

**Comment by shifujun** [comment]
我们已经在这个问题上做过很多方向的尝试了。目前的结论是没有更好办法的。主要原因在于官方的构建流程中没有提供对XML资源的Transform API，导致我们没有办法通过公开API在构建过程中编辑XML。这样XML中写的Fragment的类名就无法修改。所以只能让原本的类名成为那个Fragment的壳子。

所以，如果自己写一段在编译期修改xml内容的Gradle任务，是可以将Fragment保持原始名字，然后让它的壳子用加上下划线的名字。

对于我们自身业务来说，Fragment的调试也不是特别大的困难。毕竟运行起来以后用IDE给Fragment的源码类改个名字还是很容易的。而且我们也可以不以插件方式运行来开发业务。

关于Fragment实现的细节，我晚点再补充一篇介绍文章吧。

**Comment by onlylikews** [comment]
修改xml资源是为了Fragment直接在layout.xml中定义的时候能正常解析吗？如果是为了这个原因，可以试试用LayoutInflateFactory解决

**Comment by shifujun** [comment]
是的。你说的办法很好想到嘛，你可以试试，也可能我们分析的不对。

**Comment by onlylikews** [comment]
恩，我试试看

**Comment by onlylikews** [comment]
自己磕磕碰碰后终于明白为什么这么做了，LayoutInflateFactory虽然拦截了fragment构建，但构建fragment的具体逻辑还是要跑回去FragmentManagerImpl，尝试从AttributeSet和XmlResourceParser入手都绕不开XmlBlock$Parser，这个封装地完全不暴露，尝试了很多方式都搞不过去，哈哈。

**Comment by shifujun** [comment]
虽然折腾了一下，但是应该对这块理解更深入了吧？很有意思的。

**Comment by onlylikews** [comment]
恩，是滴，整个过程让人很享受
