### ISSUE TITLE
请问 useHostContext 的规则是怎么写的

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#240]

**Comment by shifujun** [comment]
`packageName.Classname.MethodName(packageName.Classname,packageName.Classname)$1$2`

前面是完整类名用点接上方法名，括号里是方法参数类型，用逗号分开。括号外是指定第几个参数要保留成HostContext。从1开始数。

可能有点小错误，这里缺少单元测试。

**Comment by donglua** [comment]
好的，我测试了一下似乎不支持带泛型的参数

**Comment by wangzhenglei** [comment]
> _No description provided._

如果想过滤a.b.FilterClass这个类，是不是这么写  useHostContext = ['a.b.FilterClass'] ?

**Comment by wangzhenglei** [comment]
> `packageName.Classname.MethodName(packageName.Classname,packageName.Classname)$1$2`
> 
> 前面是完整类名用点接上方法名，括号里是方法参数类型，用逗号分开。括号外是指定第几个参数要保留成HostContext。从1开始数。
> 
> 可能有点小错误，这里缺少单元测试。

如果想过滤a.b.FilterClass这个类，是不是这么写  useHostContext = ['a.b.FilterClass'] ?

**Comment by shifujun** [comment]
> > `packageName.Classname.MethodName(packageName.Classname,packageName.Classname)$1$2`
> > 前面是完整类名用点接上方法名，括号里是方法参数类型，用逗号分开。括号外是指定第几个参数要保留成HostContext。从1开始数。
> > 可能有点小错误，这里缺少单元测试。
> 
> 如果想过滤a.b.FilterClass这个类，是不是这么写 useHostContext = ['a.b.FilterClass'] ?

这个确实复杂了点，我也不那么熟悉了。建议参考Wiki中的[《调试研究Shadow对字节码编辑的正确姿势》](https://juejin.cn/post/6844903881277702158) 一文直接debug调整这段逻辑，确定正确的写法。

而且在实践中我们也发现，很多情况下不需要用这个能力。可以直接在插件的代码中主动获取宿主的Context传给目标方法。
