### ISSUE TITLE
如何从host起插件中的服务

### ISSUE THREAD

**Issue by wgypaul** [Tencent/Shadow#241]
您好，目前我们使用的插件sample都是点击启动插件按钮进入插件的，然后在插件里面操作，但是有没有那种点击按钮或者通过某种调用直接启动插件里面服务的例子啊，麻烦您给我提供点思路，谢谢您！

**Comment by shifujun** [comment]
看看Manager的代码，里面是先调PPS的bindPluginService方法获取PluginLoader，再去loadPlugin的。这个PluginLoader就是一个插件Service。所以可以同理的去bind其他插件Service。

手边没电脑，晚一些可以加个示例。
