### ISSUE TITLE
这些方法不再Override父类了: onResume:()V(转换前定义在android.app.Fragment)

### ISSUE THREAD

**Issue by hzx0910** [Tencent/Shadow#242]
编译报  java.lang.IllegalStateException: 存在Override方法转换后不再Override的情况，详见shadow_override_check3494242925135198696.txt

这些方法不再Override父类了:**
onResume:()V(转换前定义在android.app.Fragment)

麻烦问下遇到这个需要怎么处理呢

**Comment by shifujun** [comment]
更新一下代码，目前应该去掉了OverrideCheck。它目前看起来有bug，已经禁用了。

**Comment by hzx0910** [comment]
再麻烦问下./gradlew publish默认情况mavenLocal下不是发布到/Users/XXX/.m2/repository文件夹了吗，我执行完为啥看不到

**Comment by hzx0910** [comment]
maven的问题解决了又遇到下面的问题
javassist.NotFoundException: android.preference.PreferenceFragment_
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.tencent.shadow.core.transform_kit.ReplaceClassName.checkAll(ReplaceClassName.kt:49)
