### ISSUE TITLE
javassist.NotFoundException: android.preference.PreferenceFragment_

### ISSUE THREAD

**Issue by hzx0910** [Tencent/Shadow#243]
javassist.NotFoundException: android.preference.PreferenceFragment_
at javassist.ClassPool.get(ClassPool.java:445)
at com.tencent.shadow.core.transform_kit.ReplaceClassName.checkAll(ReplaceClassName.kt:49)
插件不支持PreferenceFragment吗

**Comment by shifujun** [comment]
跟#242 一样，更新一下代码。

**Comment by hzx0910** [comment]
> 跟#242 一样，更新一下代码。

你好，已经是dev最新的了 打出来的包是2.0.12-fe668af9-SNAPSHOT

**Comment by hzx0910** [comment]
@shifujun 已经是dev最新的，一样报这个错

**Comment by shifujun** [comment]
那这样，你Fork一下Shadow，添加提交复现问题，然后把代码库地址贴一下。我能复现的话应该好解决。

**Comment by hzx0910** [comment]
@shifujun 你好请看https://github.com/hzx0910/Shadow dev分支

**Comment by shifujun** [comment]
这么一跑一下就明白问题了。这个PreferenceFragment确实不支持。因为它存在于Android SDK内部，需要特殊处理，就像DialogFragment一样。

所以两个办法：

1. 参考ShadowDialogFragment的实现，支持PreferenceFragment。
1. 使用AndroidX的PreferenceFragment，直接就支持了。而且我看PreferenceFragment的文档，它在API28中已经Deprecated了，官方推荐使用AndroidX的实现。

**Comment by hzx0910** [comment]
@shifujun 好的明白了谢谢
