### ISSUE TITLE
如何把插件apk里supportv4包移到宿主里

### ISSUE THREAD

**Issue by 88fanfan** [Tencent/Shadow#244]
在sample-app-lib项目下的build.gradle 做如下修改
//    implementation project(":pinnedheaderexpandablelistview")
 compileOnly project(":pinnedheaderexpandablelistview")
    compileOnly 'com.android.support:support-v4:27.1.1'
//    implementation 'com.android.support:support-v4:27.1.1'

发现pinnedheaderexpandablelistview 这个项目没有打入sample-plugin-app-debug.apk，而v4包仍然打入该apk，请问是什么原因

**Comment by shifujun** [comment]
`project(":pinnedheaderexpandablelistview")`是一个Android Library，是不能compileOnly方式依赖的。

但这个不重要。插件不能直接复用宿主中的support包。因为support包的代码相当于插件的代码，是需要被Shadow Transform处理才能运行的。比如support包里的Activity需要被修改为ShadowActivity。如果打包在宿主里，它们就不会被修改。

如果确实有这种需求，需要将support包里的一些类分离出来。按照support包的设计，大部分功能不是在系统组件的类中直接实现的。所以把一些Activity、Service的类分离出来就行了，但是应该也挺不会太省事。

再考虑到宿主和插件的版本一般不是一对一的。所以support包打包到宿主里，不一定是好事。插件复用宿主代码，建议都通过接口调用形式去复用，不要直接依赖宿主中的实现类。另外support包可以利用Proguard混淆、精简的，放在插件中体积也不是很大吧。

**Comment by 88fanfan** [comment]
aar 里面没有资源文件是可以compileOnly的。
基本上每个插件都会用到support 包，如果app里面插件多，这个节约的体积还是比较可观。 文档里说插件可以依赖插件，一个插件里有support包， 那么其他插件可以依赖这个插件里的support包吗。sample 里面好像没有这样的demo，我觉得这个demo 应该搞一下

**Comment by shifujun** [comment]
插件依赖插件是可以的。可以把support包做成一个公共的插件包，让其他插件依赖它。多个插件的版本是一对一的，这样依赖就没有问题。

多插件的sample确实一直欠缺着。你可以先自行尝试一下，设置`dependsOn`，值就是插件的`partKey`。

https://github.com/Tencent/Shadow/blob/dev/projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin1/build.gradle#L56

**Comment by 88fanfan** [comment]
好的，我先试试
