### ISSUE TITLE
插件使用宿主资源/宿主使用插件资源是否支持,前者可能会遇到

### ISSUE THREAD

**Issue by yizems** [Tencent/Shadow#246]

**Comment by shifujun** [comment]
这个不需要什么特别的技术支持。使用谁的资源，只需要拿到它的Resources对象就可以了。

这个对象的交换，可以通过定义插件访问宿主类的白名单，指定一个双方约定的接口来进行交换。

通过接口交换对象的主要原因是Shadow考虑的主要场景是，插件和宿主的版本是多对多关系的，因此需要假设插件和宿主不是一同编译的，双方的资源ID可能会改变等兼容性问题。

**Comment by yizems** [comment]
ok,3Q ,看来你是年前不太忙了呀,那么快的回复=.=

大概能明白你们对于shadow 某些方面的定位了

**Comment by shifujun** [comment]
哈哈，挺忙的，赶上编译工程什么的，问题又能直接回答的才能回复一下。
