### ISSUE TITLE
packagePlugin loaderApkProjectPath runtimeApkProjectPath配置问题

### ISSUE THREAD

**Issue by yizems** [Tencent/Shadow#247]
这里主要是想将 lader 和 runtime 发布到仓库中,但是在案例中,我看好像是都以源码的方式进行的配置

所以这里有点疑惑,这两个配置在插件中主要的作用是什么,我大致看了下, 好像里面主要是 将 loader和 runtime 打包, 然后读取一些配置类的东西,没看太明白,希望能解答下

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/dev/projects/sample/README.md#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven

先看一下这个。

**Comment by yizems** [comment]
![image](https://user-images.githubusercontent.com/16949474/72133027-726f0200-33bb-11ea-9297-76f65fdecc52.png)

我看了,问题就出在这里
![image](https://user-images.githubusercontent.com/16949474/72133044-7c910080-33bb-11ea-9bcd-7c583fe302bf.png)

你这个里面的脚本直接 引用了 loader 和 runtime 的 任务和apk,以及项目路径

我更加想要的是 这个plugin 里面,只有 plugin main,以及normal-apk 和 shadow-apk 就可以了

**Comment by shifujun** [comment]
没太看懂。你更加想要的，应该要自己去实现才对呀。

**Comment by yizems** [comment]
我换种方式问吧,如果我把脚本里面的下面的代码去掉会影响 plugin的打包么


![image](https://user-images.githubusercontent.com/16949474/72133735-245afe00-33bd-11ea-8542-7a81b4ef282c.png)

![image](https://user-images.githubusercontent.com/16949474/72133741-2755ee80-33bd-11ea-830e-e4526521f51b.png)

**Comment by shifujun** [comment]
至少应该有一个plugin里包含loader和runtime。后续加载的plugin可以不包含这两部分，通过uuid的一致和之前的插件复用相同的loader和runtime。

**Comment by yizems** [comment]
大概明白了,谢谢, 我再多看看的
