### ISSUE TITLE
阅读源码时有个地方不理解还望指点

### ISSUE THREAD

**Issue by fanmingyi** [Tencent/Shadow#249]
突然某天有了想读透`shadow`的源码，但是遇到了些问题，也许这个问题应该是个社区问题。 https://github.com/Tencent/Shadow/blob/fc307fb261af7fa0ddc286ca5451c618e2016d0d/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt#L32

`CreateResourceBloc`类中为何需要先用宿主上下文构造一个`Webview`。我看到注释：“先用宿主`Context`初始化一个`WebView`，以便`WebView`的逻辑去修改`SharedLibraryFiles`，将webview.apk添加进去”。我不是很理解，也许是我基础理论不扎实还希望能指点下？
这一步是为了拿到webview的so路径然后放入共享库路径列表，以让插件使用`Webview`的一些so吗

**Comment by shifujun** [comment]
这是在构造插件的Resource对象，所以跟so没关系。构造Resource对象时，可以使用多个apk文件。

为了让应用在使用webview时可以访问webview自带的资源，就是在webview中长按弹出的菜单的样式等等，系统的webview采用了一种非常dirty的实现。在应用的Resource对象已经构造完之后，在初始化Webview的时候去hack修改了应用的Resource对象。

我们的插件Resource对象由于不是系统创建的，所以Webview的hack逻辑没能找到插件的Resource对象，也做相同的hack操作。所以Shadow里new出这个webview就是为了让webview先去hack宿主应用的Resource对象。然后我们再从hack之后的Resource对象中取出webview.apk的路径，在构造插件Resource对象时直接添加进去。这样插件中的Webview就也能正常使用它的资源了。

建议你再Debug一下这个过程，能了解到更清楚一些。

**Comment by fanmingyi** [comment]
非常感谢
