### ISSUE TITLE
插件卸载和升级

### ISSUE THREAD

**Issue by yizems** [Tencent/Shadow#250]
最近看源码的时候突然发现好像没有这部分说明/ 代码, 那么请问你们是如何在插件已经运行过一次后 对插件进行更新的呢,更新比较关键, 先卸载再更新只是一种途径

**Comment by shifujun** [comment]
我只能猜你在问什么。

插件的更新机制可以由业务在Manager中控制。更新的时机和业务是强相关的。Manager和插件进行通信，在合适的时机启动新插件就可以了。

对于插件UUID更新的情况，由于配套的Loader和Activity-Container也需要更新，则需要重起PPS。

那么最容易实现的策略可以是如果没有插件包，则等待下载，否则先启动本地已有的最新插件包，同时去下载更新的插件包。
