### ISSUE TITLE
插件占用存储太大了

### ISSUE THREAD

**Issue by yinmingxuan** [Tencent/Shadow#251]
我查看了应用数据占用：
/data/data/com.android.egg/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager

竟然占用了810M！请问shadow升级应用，升级插件是需要自己删没用数据吗？

**Comment by shifujun** [comment]
是的，测试的manager没有删除插件。在实际业务中，也需要业务根据自身特点选择合适发时机删除就插件。主要原因在于删除插件是一个I/O操作，容易导致关键业务卡顿。
