### ISSUE TITLE
Class com.tencent.shadow.core.runtime.ShadowInstrumentation中缺少方法:

### ISSUE THREAD

**Issue by hzx0910** [Tencent/Shadow#252]
newActivity:(Ljava/lang/ClassLoader;Ljava/lang/String;Landroid/content/Intent;)Lcom/tencent/shadow/core/runtime/ShadowActivity;被这些类调用了:
........
这个方法没法加呀，跟Instrumentation里面名称参数相同返回值冲突了

**Comment by shifujun** [comment]
这个方法不能简单的转调给Instrumentation就行了。这个方法的功能是要构造Activity对象，所以插件中应该是构造ShadowActivity对象。这件事应该由ShadowAppComponentFactory来完成。所以方案上应该是这样的：

将ShadowAppComponentFactory存到PluginPartInfo中，然后按照PackageManagerInvokeRedirect的实现方法，将原本对newActivity的调用转到一个静态方法上去（redirectMethodCallToStaticMethodCall），在其中拿到ShadowAppComponentFactory对象，构造出所需ShadowActivity作为静态方法的返回。

你要尝试一下自己实现吗？

**Comment by hzx0910** [comment]
@shifujun 好的我看一下谢谢～
