### ISSUE TITLE
多个插件统一打包到宿主assets中，有gradle示例吗？

### ISSUE THREAD

**Issue by XBaron** [Tencent/Shadow#253]
多个插件打包到宿主assets时，插件中
shadow {
        packagePlugin {
        }
}
1.这部分配置怎么写？与打包单个插件相比有什么注意事项？（PS：插件gradle配置可否提供一下文档，例如packagePlugin中配置项compactVersion里面怎么填）
2.sample中打包后是一个plugin.zip，里面包含 sample-plugin.apk，loader.apk，runtime.apk，多个插件打包后是多个plugin.zip？ 还是一个plugin.zip，包含plugin1.apk，plugin2.apk，loader.apk，runtime.apk，即loader和runtime是否要都打包进每个插件中，还是说多个插件可以复用一个loader和runtime

小白刚接入Shadow，还有很多地方没明白，大神勿喷

**Comment by shifujun** [comment]
首先推荐读一下关于这部分的文档
https://juejin.im/post/5d2ec812e51d45778f076de3

关于`compactVersion`，全局搜一下就会发现没有逻辑读取了这个字段。这是一个我们业务中预留的字段，为了未来修改这个config文件格式时兼容旧版本用的。

zip包有几个不重要，这个zip包只是下载插件时使用的。插件的安装使用的是config文件和apk的相对路径。所以有几个zip包都可以。只要他们的的UUID是相同的，他们就是同一个插件包。一个config文件中可以有多个插件apk。

一个多apk的例子可以在`projects/test/plugin/general-cases/test-plugin-general-cases/build.gradle`中看到。

**Comment by XBaron** [comment]
感谢
