### ISSUE TITLE
请问有详细的文档吧， 或者说什么时候能发布文档？

### ISSUE THREAD

**Issue by lovemianhuatang** [Tencent/Shadow#256]
请问有详细的文档吧， 或者说什么时候能发布文档？  
希望有个集成文档

**Comment by shifujun** [comment]
请先参考这个回复：
https://github.com/Tencent/Shadow/issues/245#issuecomment-572853946

Shadow值得讲的内容已经都写在Wiki中了：
https://github.com/Tencent/Shadow/wiki

如果特别具体的技术问题，欢迎再提Issue。
