### ISSUE TITLE
如何在壳子Activity自主添加的方法

### ISSUE THREAD

**Issue by victorwrage** [Tencent/Shadow#261]
例子可以运行，但在用cocos导出的工程里面有个父类Cocos2dxActivity的onCreateView 等方法没有调用，并且还有些Cocos2dxGLSurfaceView之类的cocos的自定义View，我应该在sdk的怎么添加？谢谢

**Comment by shifujun** [comment]
Fork一下，然后把你有问题的例子提交上去，把地址贴过来。我就很容易看明白问题了。

**Comment by victorwrage** [comment]
https://github.com/victorwrage/shadowCocos    这是plugin地址

**Comment by shifujun** [comment]
我是说Fork一下Shadow，在sample上面做一点小改动复现问题。你贴的这个库完全是个跑不起来的工程，文件太多了，我没法看的。

比如你说有个Activity的onCreateView方法没有调用。那你在Shadow的sample也可以写一个Activity，如果它的onCreateView方法没有调用，我就能看到你是怎么加的Activity，怎么定义的onCreateView方法。不过具体到这个方法，我认为Shadow现在的dev分支上应该是没有问题的。Activity上的所有方法都是根据API29的Activity类自动生成的代码，应该不会有漏掉的。

其他的问题也这样交流，这样才能相互理解问题。

**Comment by shifujun** [comment]
如果还有问题，请参考
https://github.com/Tencent/Shadow/blob/dev/CONTRIBUTING.md#issue
再重新打开Issue。
