### ISSUE TITLE
Shadow支持Flutter吗？

### ISSUE THREAD

**Issue by Scarlet-Pan** [Tencent/Shadow#263]
Shadow支持Flutter吗？有没有什么需要特别适配的？

**Comment by shifujun** [comment]
支持，不过shadow没有特别做什么。因为flutter是通过so引入的，跟普通so没什么区别。

**Comment by longrenzhut** [comment]
flutter 混编打包成的包，本地assets 图片显示不了

**Comment by yumdao** [comment]
> flutter 混编打包成的包，本地assets 图片显示不了

请问你这个问题解决了吗？我也碰到了同样的问题

**Comment by yumdao** [comment]
> flutter 混编打包成的包，本地assets 图片显示不了

目前我倒是找到一个折中的方案，就是在宿主模块中同样引入插件的flutter，可以解决assets资源找不到的问题，但是会让安装包变大。

可以考虑在打包宿主的时候解压plugin.zip，把插件工程中assets的flutter_assets文件夹剪切到宿主工程的assets下，但还没测试过是否可行。
