### ISSUE TITLE
多工程分别打包的zip，该如何加载？

### ISSUE THREAD

**Issue by Scarlet-Pan** [Tencent/Shadow#265]
现有A、B、C三个工程，分别集成runtime和loader打包出了三个zip包；
目前是参考的是Sunflower的Sample来做，manager在enter时，根据不同参数，install各自的zip包；但在实际运行时：
1.如果加载了A，再去加载B，就会出错；
2.如果反复加载A，是正常的；
3.杀掉进程，加载B，可以正常；再加载A，仍旧会出错；
错误信息是启动的Activity（具体的业务Activity）没在manifest里注册，根据经验是没正确找到插件包所致。

请问一下这种多过程分别打的zip包，该怎么加载？或者说有什么参考Sample？

**Comment by shifujun** [comment]
我们的业务确实有这个场景，但是业务的代码不能直接开源出来。这个一直没时间写sample，所以暂时只能参考实现代码了。

插件在安装后是跟安装前有几个zip包有几个config.json没有关系的。

所以打的zip包只需要里面的config.json配置不冲突就好了。所以关键是只能有一个zip包里有runtime和loader，以及所有的zip包的uuid是一样的。这样它们分别安装后在数据库里看起来就和同一个zip安装的一样了。

然后关于指定uuid，之前写的同事是这样讲的：

> zip包里的uuid有三种生成方式，一种是读取根目录/build下一个文件，另一种是读取build.gradle的配置，以上都没有的话，随机生成一个。单次构建需要保证所有zip包里UUID相同的话，需要在根目录build文件夹下生成一个uuid.txt文件，打包插件会从里头读。

**Comment by Scarlet-Pan** [comment]
感谢指点思路，还有2个问题：
1.如果是在build.gradle里指定UUID，是具体用哪个字段？打包任务里只有uuidNickname，没有其它字段了诶。
2.A和B两个插件包有共同依赖库，同名类，比如公共的BaseActivity，这种情况怎么破呀？

**Comment by shifujun** [comment]
> 1.如果是在build.gradle里指定UUID，是具体用哪个字段？打包任务里只有uuidNickname，没有其它字段了诶。

https://github.com/Tencent/Shadow/blob/dev/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/extensions/PackagePluginExtension.kt#L133

> 2.A和B两个插件包有共同依赖库，同名类，比如公共的BaseActivity，这种情况怎么破呀？

搞一个公共插件，把共用的部分放进去，然后让另外两部分依赖它。
通过dependsOn字段指定。
https://github.com/Tencent/Shadow/blob/dev/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/extensions/PackagePluginExtension.kt#L98
这个字段最后会传到PluginClassLoader去
https://github.com/Tencent/Shadow/blob/dev/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/LoadApkBloc.kt#L60

**Comment by Scarlet-Pan** [comment]
估计还是不一定行，A和B的公共依赖库可能存在版本差异，甚至类并不兼容，估计A和B得在自己环境中独立运行才行，是否应考虑A和B两个插件独立进程运行，这种该怎么弄呢？
又或是Shadow目前是怎么解决多个插件，依赖库版本/兼容性冲突问题的呢？

**Comment by Scarlet-Pan** [comment]
估计还是不一定行，A和B的公共依赖库可能存在版本差异，甚至类并不兼容，估计A和B得在自己环境中独立运行才行，是否应考虑A和B两个插件独立进程运行，这种该怎么弄呢？
又或是Shadow目前是怎么解决多个插件，依赖库版本/兼容性冲突问题的呢？

**Comment by shifujun** [comment]
如果版本都不一样，那这是个逻辑问题了。只能分开到两个进程里了。想复用代码，就需要合理的设计稳定的接口，不能随意实现。这跟shadow就没什么关系了。

**Comment by Scarlet-Pan** [comment]
估计还是不一定行，A和B的公共依赖库可能存在版本差异，甚至类并不兼容，估计A和B得在自己环境中独立运行才行，是否应考虑A和B两个插件独立进程运行，这种该怎么弄呢？
又或是Shadow目前是怎么解决多个插件，依赖库版本/兼容性冲突问题的呢？

**Comment by Scarlet-Pan** [comment]
是的，的确有很多设计和管理不合理的地方，但毕竟A/B/C三个项目是不同人负责的，他们用的依赖库、公共模块的确可能存在较大差异，也是很现实的问题。
在多工程插件的时候，如果说插件框架，能让它们分别各自独立运行于自己的空间，应该是比较理想了

**Comment by Scarlet-Pan** [comment]
麻烦问一下，shadow多进程各自加载插件，有参考的sample么？或者说该怎么弄？

**Comment by shifujun** [comment]
把PPS配置到不同的进程就可以了。manager可以用多个也可以用一个。原理上一个进程多个进程没什么差别，都是用binder通信的。

**Comment by Dovar66** [comment]
> 把PPS配置到不同的进程就可以了。manager可以用多个也可以用一个。原理上一个进程多个进程没什么差别，都是用binder通信的。

host和插件在相同进程时也用的binder通信?

**Comment by shifujun** [comment]
> > 把PPS配置到不同的进程就可以了。manager可以用多个也可以用一个。原理上一个进程多个进程没什么差别，都是用binder通信的。
> 
> host和插件在相同进程时也用的binder通信?

是的。值得优化。欢迎贡献代码。

**Comment by linuxjava** [comment]
1.多插件问题，如下：
有A、B、C三个插件，那么这三个插件打包成zip时，里面都要包含runtime和loader吗？感觉如果每个插件中的runtime和loader是不一样的，那么各自zip包中包含runtime和loader是合理的，反之不合理，因为有冗余。

2.我这儿的需求是，runtime和loader其实是不需要动态的（也就类似非动态插件框架），解决思路如下：

3.分析了一下，定义A为主插件（也就是APP启动就要加载的），B、C为子插件，它们共用一个PluginProcessPPS；那么A里面包含runtime和loader即可，B、C里面不包含runtime和loader。

请问大佬是否有问题，或还有其它更好的思路？？

                                                                     Host
                                                                         |
                                 main-plugin.zip(main.apk、runtime.apk、loader.apk)
                                               |                                                   |
                                         B-plugin.zip(B.apk)                A-plugin.zip(B.apk)

**Comment by shifujun** [comment]
@linuxjava 现在的实现确实就是如你所想的。不用每个插件都带有runtime和loader。uuid就是用来标记一组apk是可以在一起共同工作的。相同uuid的插件就可以用一个loader和runtime。多个zip只是下载过程的一个打包，这些zip在安装后就没用了。东西都解压到一个路径里了，然后都会插入到数据库里。在数据库里的表现就是这些apk的uuid是一致的。从数据库里读取已经安装了哪些插件时是看不出来最初哪些apk是在同一个zip包里的。

**Comment by android-sz-coder** [comment]
跟楼主有相同的需求：在宿主中加载多个不同的插件 ，加载完A插件之后，再去加载B插件，直接提示找不到对应的组件，看错误信息应该是启动的宿主的组件，宿主没有注册，因此找不到，这个需要怎么配置和打包zip啊

**Comment by android-sz-coder** [comment]
你好 这个问题解决了吗  能告知下思路吗 我今天遇到了同样的问题
1：插件a,b分别设置了相同的uuid，不管是zip包里面是否有loader和runtime，先启动a插件，再次启动b插件的时候就会报错，找不到对应的组件，这个应该是没有找到正确的插件包导致的
2：多个插件包，放在不同的进程中，这个该怎么配置，需要多个pluginmanager吗，uuid是否需要设置成一样，我今天测试了下，uuid设置成一样，共用一个pluginmanager还是报找不到组件的问题

**Comment by android-sz-coder** [comment]
你好 这个问题解决了吗  能告知下思路吗 我今天遇到了同样的问题
1：插件a,b分别设置了相同的uuid，不管是zip包里面是否有loader和runtime，先启动a插件，再次启动b插件的时候就会报错，找不到对应的组件，这个应该是没有找到正确的插件包导致的
2：多个插件包，放在不同的进程中，这个该怎么配置，需要多个pluginmanager吗，uuid是否需要设置成一样，我今天测试了下，uuid设置成一样，共用一个pluginmanager还是报找不到组件的问题

**Comment by android-sz-coder** [comment]
@shifujun ，能帮忙提供下多插件包的实现思路吗

**Comment by android-sz-coder** [comment]
> 所以打的zip包只需要里面的config.json配置不冲突就好了。所以关键是只能有一个zip包里有runtime和loader，以及所有的zip包的uuid是一样的。这样它们分别安装后在数据库里看起来就和同一个zip安装的一样了。
> 
1：配置不冲突怎么理解 指那些得保持不同啊 
2：只能有一个zip有runtime和loader
有这么一个场景：插件a和插件b不一定都同时存在，插件a中有runtime和loader,b中只有apk和config.json，这个时候如果插件a并不存在手机上，直接去启动插件b应该存在问题吧 这样就没有runtime和loader了
麻烦解答下 谢谢

**Comment by listen2code** [comment]
> 1.多插件问题，如下：
> 有A、B、C三个插件，那么这三个插件打包成zip时，里面都要包含runtime和loader吗？感觉如果每个插件中的runtime和loader是不一样的，那么各自zip包中包含runtime和loader是合理的，反之不合理，因为有冗余。
> 
> 2.我这儿的需求是，runtime和loader其实是不需要动态的（也就类似非动态插件框架），解决思路如下：
> 
> 3.分析了一下，定义A为主插件（也就是APP启动就要加载的），B、C为子插件，它们共用一个PluginProcessPPS；那么A里面包含runtime和loader即可，B、C里面不包含runtime和loader。
> 
> 请问大佬是否有问题，或还有其它更好的思路？？
> 
> ```
>                                                                  Host
>                                                                      |
>                              main-plugin.zip(main.apk、runtime.apk、loader.apk)
>                                            |                                                   |
>                                      B-plugin.zip(B.apk)                A-plugin.zip(B.apk)
> ```

https://github.com/listen2code/Shadow，，我实现的demo，应该就是你说的这种场景，提供参考
