### ISSUE TITLE
编译不通过，求文档支援，或开个群一起交流一下，海涵

### ISSUE THREAD

**Issue by weiwenqiang** [Tencent/Shadow#268]
> Configure project :sample-loader
WARNING: The following project options are deprecated and have been removed:
android.enableAapt2
This property has no effect, AAPT2 is now always used.

android.useDeprecatedNdk
NdkCompile is no longer supported

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\zp\android\github\plugin\Shadow\projects\sample\source\sample-plugin\sample-loader\build.gradle' line: 49

* What went wrong:
A problem occurred configuring project ':sample-loader'.
> Cannot access first() element from an empty Iterable
-------------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':introduce-shadow-lib:lint'.
> Could not resolve all artifacts for configuration ':introduce-shadow-lib:releaseCompileClasspath'.
   > Could not find com.tencent.shadow.dynamic:host:2.0.12-ba5a2501-SNAPSHOT.
     Required by:
         project :introduce-shadow-lib

------------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':introduce-shadow-lib:lint'.
> Could not resolve all artifacts for configuration ':introduce-shadow-lib:releaseCompileClasspath'.
   > Could not find com.tencent.shadow.dynamic:host:2.0.12-ba5a2501-SNAPSHOT.
     Required by:
         project :introduce-shadow-lib

**Comment by yiwanganjing** [comment]
怎么解决的？
