### ISSUE TITLE
有办法获取插件apk内的fragment对象实例吗？

### ISSUE THREAD

**Issue by weiwenqiang** [Tencent/Shadow#269]
因为主页是viewpager，需要获取数个apk内的Fragment，进行加载，有方法可以实现吗?

**Comment by shifujun** [comment]
可以是肯定可以的，但是没有现成的api或者设计。shadow主要实现的是插件独立安装运行场景的对齐。对于宿主和插件通信的场景，都建议采用宿主和插件约定接口，加入插件访问宿主的白名单，配合控制反转的方式去实现。

**Comment by weiwenqiang** [comment]
十分感谢，有一小点明白，但我不知道从哪里下手，希望有个相关的小文档和小实现Demo,我研究一下

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/dev/projects/sample/source/sample-host-lib/src/main/java/com/tencent/shadow/sample/host/lib/HostUiLayerProvider.java

看一下这个类相关的代码吧。调试一下。

**Comment by o0starshine0o** [comment]
@shifujun HostUiLayerProvider.java类在宿主中，是插件使用宿主的类，根据[Container的动态化](https://juejin.im/post/5d1b466f6fb9a07ed524b995#heading-3)，使用的方法是插入一个DexClassLoader。
------
但是想要宿主（或者说manager）直接从插件中加载一个类（比如fragment），还不清楚怎么实现，再研究下。

**Comment by linhaosheng** [comment]
请问现有的代码支持这个功能了吗
