### ISSUE TITLE
请教个问题，插件接入第三方SDK，比如腾讯直播SDK，这里SDK一般都要在APPLICATION中初始化，要怎么处理呢？

### ISSUE THREAD

**Issue by lenomon** [Tencent/Shadow#273]
插件接入第三方SDK，比如腾讯直播SDK，这里SDK一般都要在APPLICATION中初始化。
似乎宿主没有调用插件的APPLICATION。
这种情况要怎么处理比较好。

**Comment by shifujun** [comment]
就正常在插件的Application类里调用就可以了。插件框架在启动插件时会按正常安装的App被启动时一样的顺序调用插件的组件的。

**Comment by lenomon** [comment]
感谢
