### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources com.tencent.shadow.core.runtime.ShadowApplication.getResources()' on a null object reference

### ISSUE THREAD

**Issue by buaasparkle** [Tencent/Shadow#274]
抱歉，先直接贴上我遇到异常，下面简述一下我的场景。

# 背景说明
我在集成 shadow 中遇到了上面的崩溃，于是尝试在 demo 中还原场景，应该也能把我的需求和问题说清楚。修改是在 shadow 的 sample/source 目录下，创建了一个新的 module，名为：sample-common
加入这个模块的初衷是想定义一些 host 和 plugin 项目中都会用到的类或资源，类似于现在的 sample-constant.

# 依赖配置
sample-host 和 sample-app-lib 中分别通过 implement 的方式依赖 sample-common

# sample-common 内部实现
只有两个类：
- ApplicationHelper
```  java
public class ApplicationHelper {

    private static Application me;

    public static void init(Application application) {
        me = application;
    }

    public static Application getInstance() {
        return me;
    }
}
```

- ResUtils
``` java
public class ResUtils {

    public static String getString(int id) {
        return ApplicationHelper.getInstance().getResources().getString(id);
    }

    public static int getColor(int id) {
        return ApplicationHelper.getInstance().getResources().getColor(id);
    }
}
```
同时还在 res 中定义了一个 colors.xml
``` xml
<resources>
    <color name="sample_green">#00AA00</color>
</resources>
```

# 代码修改
- 在 sample-host 项目中的 HostApplication 中初始化 ApplicationHelper
``` java
public class HostApplication extends Application {
    // 省略
    @Override
    public void onCreate() {
        super.onCreate();
        sApp = this;

        ApplicationHelper.init(sApp);
        // 省略
    }
}

```

-  在 sample-app-lib 项目中的  `UseCaseSummaryFragment` 里使用 ResUtils 设置了一下颜色

``` java
public class UseCaseSummaryFragment extends Fragment {

    private TextView mCaseName;
    private Button mStartCase;
    private TextView mCaseSummary;
    private TextView mEnvironment;

    public void setCase(final UseCase useCase) {
        mCaseName.setText(useCase.getName());
        mCaseSummary.setText(useCase.getSummary());
        mCaseSummary.setBackgroundColor(ResUtils.getColor(R.color.sample_green));

        // 下略
    }

```

#  崩溃发生场景
运行 demo 加载插件，通过 drawable 选择 useCase 后会触发 上面 setCase 方法的调用，当执行到 ResUtils.getColor(R.color.sample_green) 方法时就抛出了异常，下面贴一下崩溃栈：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources com.tencent.shadow.core.runtime.ShadowApplication.getResources()' on a null object reference
        at com.tencent.shadow.sample.common.ResUtils.getColor(ResUtils.java:27)
        
at com.tencent.shadow.sample.plugin.app.lib.gallery.cases.UseCaseSummaryFragment$1.onClick(UseCaseSummaryFragment.java:60)
        
at android.view.View.performClick(View.java:4793)

at android.view.View$PerformClick.run(View.java:19974)

at android.os.Handler.handleCallback(Handler.java:739)

at android.os.Handler.dispatchMessage(Handler.java:95)

# 求助

这里的崩溃栈应该是直接跳到 gradle 编译过程中 transform 生成的代码，我尝试查看一下生成的 
UseCaseSummaryFragment_.class 文件，也没有看到特别的处理，也是直接调用的 ResUtils 加载，所以目前没有什么解决思路。

## 一点说明：
还有一个在我的项目中遇到的问题是因为 applicationHelper 被不同 classloader 加载导致在插件中调用 ApplicationHelper.getInstance().getResource 处的崩溃 （NPE）并未在 demo 中出现，还有点不解。不过 demo 中在调用 ResUtils 时 applicationHelper 对象验证是非空的。

烦请帮忙查看，给我一些思路，谢谢！

**Comment by shifujun** [comment]
没提供代码的人里面你描述的算是最清楚的了，但是这还是不如你直接fork之后修改push上来给我看更清楚。

基于你的描述，我猜有这些问题：
1. >sample-host 和 sample-app-lib 中分别通过 implement 的方式依赖 sample-common

implementation方式依赖导致宿主和插件两个apk中各自打包了一份sample-common，自然也包括它的资源。因此，两个apk中的`R.color.sample_green`在aapt编译后的实际id是不一样的。所以就算没有其他问题，这样也是不能获得到你想要的的资源的。

2. `me`为`null`应该是因为宿主和插件各自打包了一份sample-common中的ApplicationHelper，所以你在宿主里初始化的跟你在插件里调用的不是一个类。插件里面的就没有初始化过。另外呢，ApplicationHelper这个类在插件里会被修改Application类型的引用，改成ShadowApplication。所以也不能传给它宿主的Application对象。

你的目的我是明白的，想插件复用宿主的一些代码和资源。所以有这几点需要注意：
1. 被复用的`sample-common`模块需要被宿主implementation方式依赖以便打包进宿主。而插件则只能compileOnly方式依赖它，以便不要打包它。但是通常你会将`sample-common`模块定义成aar模块，aar模块就不能被compileOnly方式依赖的，因为一个图片资源只编译不打包是没有道理的。所以，要么把aar中的jar导出来被插件compileOnly方式依赖，要么再额外定义一个Interface的jar模块。

2. 复用资源不能直接在插件中通过资源ID的方式去获取。因为宿主和插件的版本关系是多对多的，不同版本的资源ID可能会变化。所以两种方式，要么利用aapt2的public.txt机制固定一些资源ID，要么通过自定义接口的方式获取资源，比如定义一个getTitleColor方法。

3. 注意接口要定义在ClassLoader的白名单里才能被插件访问到。

**Comment by buaasparkle** [comment]
非常感谢及时的回复 🙏

按照您给出的 3 点建议，进行了如下修复：

1. 参照 sample-app-lib 中依赖 sample-host-lib jar 的方式，修改了插件中原先对 sample-common 的 依赖方式为 compileOnly

2. sample_green color 的加载暂时改为通过 resource getIdentifier 的方式解决

3. 原本已将 sample-common 目录加到白名单中，提问时疏忽了，抱歉。

至此，我的 demo 可以正常运行了，再次感谢帮助 🙏

P.S. 后面集成中如果再遇到问题我会尝试用提交代码的方式，尽可能提供完整的背景信息。
