### ISSUE TITLE
kill掉plugin进程，PluginServiceConnection中的onServiceDisconnected无调用？

### ISSUE THREAD

**Issue by crimeline** [Tencent/Shadow#275]
在SamplePluginManager的enter调用callPluginService方法，service插件启动是成功的。但是启动成功后模拟plugin异常，kill掉plugin进程，发现onServiceDisconnected没有被调用，这是为什么？

callPluginService代码如下：

    private void callPluginService(final Context context, final Bundle bundle, final EnterCallback callback) {
        final String partKey = bundle.getString(Constant.KEY_PLUGIN_PART_KEY);
        final String className = bundle.getString(Constant.KEY_CLASSNAME);
        final String pluginZipPath = bundle.getString(Constant.KEY_PLUGIN_ZIP_PATH);
        Intent pluginIntent = new Intent();
        pluginIntent.setClassName(context.getPackageName(), className);

        executorService.execute(new Runnable() {
            @SuppressLint("WrongConstant")
            @Override
            public void run() {
                try {
                    Log.d(TAG, "installedPlugin.....");
                    final InstalledPlugin installedPlugin
                            = installPlugin(pluginZipPath, null, true);//这个调用是阻塞的

                    loadPlugin(installedPlugin.UUID, partKey);

                    Intent pluginIntent = new Intent();
                    pluginIntent.setClassName(context.getPackageName(), className);

                    Log.d(TAG, "bindPluginService.....");
                    boolean callSuccess = mPluginLoader.bindPluginService(pluginIntent, new PluginServiceConnection() {
                        @Override
                        public void onServiceConnected(ComponentName componentName, IBinder iBinder) {
                            Log.d(TAG, "onServiceConnected");
                            if (null != callback) {
                                callback.onServiceBinded(iBinder,installedPlugin.version,installedPlugin.UUID);
                            }
                        }

                        @Override
                        public void onServiceDisconnected(ComponentName componentName) {
                            Log.d(TAG, "onServiceDisconnected");
                            //throw new RuntimeException("onServiceDisconnected");
                            if (null != callback) {
                                callback.onServiceUnbinded();
                            }
                        }
                    }, Service.BIND_AUTO_CREATE);

                    if (!callSuccess) {
                        Log.e(TAG, "bind service失败 className==" + className);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

望答疑，谢谢！

**Comment by shifujun** [comment]
这可能是没实现导致的bug。理论上讲这个场景支持是没问题的。插件的binder都是真的binder，应该可以支持。

如果方便的话，可以帮忙在sample里构造一个对比独立安装和插件运行的场景。

我这边不确定什么时候有时间能够修复，但我会尽快的。

**Comment by crimeline** [comment]
谢谢。

对比独立安装和插件运行的场景？

这个我不是很明白。是说构造一个单独运行的和插件运行的service例子么。

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/tree/dev/projects/sample/source/sample-plugin/sample-app-lib
这里面的代码是同时被编译成独立app和插件app的。运行`sample-normal-app`就是独立安装的方式运行，运行`sample-host`就是以插件方式运行`sample-plugin-app`插件。

所以可以在`sample-app-lib`里构造一个复现问题的场景。按理说它应该在`sample-normal-app`和`sample-host`两种方式运行时表现一致。这就是Shadow的基本目标。

**Comment by crimeline** [comment]
最新代码编译不过。我自己在本地使用commit id是: 54b1bb3876620a91ac31eca1bc77177053ced913尝试了一下，在单独场景中是有返回的，在使用bindPluginService接口时onServiceDisconnected无返回。
插件调用接口代码如下：
`boolean callSuccess = mPluginLoader.bindPluginService(pluginIntent, new PluginServiceConnection() {
                        @Override
                        public void onServiceConnected(ComponentName componentName, IBinder iBinder) {
                            Log.d(TAG, "onServiceConnected");
                            if (null != callback) {
                                callback.onServiceBinded(iBinder,101,installedPlugin.UUID);
                            }
                        }

                        @Override
                        public void onServiceDisconnected(ComponentName componentName) {
                            Log.d(TAG, "onServiceDisconnected");
                            //throw new RuntimeException("onServiceDisconnected");
                            if (null != callback) {
                                callback.onServiceUnbinded();
                            }
                        }
                    }, Service.BIND_AUTO_CREATE);`

打印如下：
![image](https://user-images.githubusercontent.com/30657747/78114174-6b441700-7433-11ea-940c-334616c34df7.png)

单独测试代码：
`Log.d(TAG, "onCreate: testApplication start !");
        bindService(intent, new ServiceConnection() {
            @Override
            public void onServiceConnected(ComponentName componentName, IBinder iBinder) {
                Log.d(TAG, "onServiceConnected: =================");
            }

            @Override
            public void onServiceDisconnected(ComponentName componentName) {
                Log.d(TAG, "onServiceDisconnected: =================");
            }
        }, Context.BIND_AUTO_CREATE);
        Log.d(TAG, "onCreate: testApplication start end!");`

打印如下：
![image](https://user-images.githubusercontent.com/30657747/78114376-c2e28280-7433-11ea-9950-815a0b9896f0.png)

是否是我版本不是使用最新的问题？

**Comment by shifujun** [comment]
你先fork一下shadow到你自己名下。

```
cd shadow //切换到你clone的shadow目录
git remote add crimeline https://github.com/crimeline/Shadow.git //把你fork的版本库添加成一个远端
git checkout -b issue275 54b1bb3876620a91ac31eca1bc77177053ced913 // 新建一个分支
//加上你复现问题的修改
git commit
git push -u crimeline  //推送issue275分支到你fork的版本库
```

然后在这里贴上你的分支地址就好了。这样我就可以直接拉下来代码debug了。

**Comment by crimeline** [comment]
感谢了，GitHub用得少。还不会这么骚的操作。
https://github.com/crimeline/Shadow/tree/issue275
打印就是上面说的，麻烦给我看下是不是写法有问题。

**Comment by shifujun** [comment]
你写的测试用例，不是太能反映问题。理想的是，先运行
![image](https://user-images.githubusercontent.com/3535204/78206326-1b1b9200-74d1-11ea-963b-eccb34e6e379.png) sample-normal-app测试没有插件框架的场景下工作正常。然后同样的代码同样的测试场景，在sample-host中运行，看插件环境下是否表现一致。

不过我还是看明白问题了。然后Review了一下Service支持的代码。确实没有实现`onServiceDisconnected`。

所以其实有两处Bug：
1. Service Destroy后没有调用`onServiceDisconnected`
2. `BinderPluginLoader`没有监听远端Binder的`linkToDeath`，所以也没有在插件进程死后调用`PluginServiceConnection`的`onServiceDisconnected`。

这两个问题确实应该优先解决。

**Comment by crimeline** [comment]
刚去了解了一下linkToDeath，发现在host调用BinderPluginLoader的地方监听一下也可以解决异常的问题。
不知道你那边什么时候能修改。我暂时修改成去监听Binder的linkToDeath。

**Comment by shifujun** [comment]
我这边暂时没有人力。只能挤时间改了。这个问题确实值得尽早修复。我希望先写出单元测试再修复。

**Comment by crimeline** [comment]
好的，这个我写的不是很好，估计帮不上什么忙。
又发现了一个问题。kill掉host主进程后，报错如下：
04-02 17:56:59.847 13625 13625 E AndroidRuntime: FATAL EXCEPTION: main
04-02 17:56:59.847 13625 13625 E AndroidRuntime: Process: com.android.vpsclient:plugin, PID: 13625
04-02 17:56:59.847 13625 13625 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.tencent.shadow.sample.host.PluginProcessPPS: java.lang.IllegalStateException: PPS出现多实例
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3172)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at android.app.ActivityThread.-wrap5(ActivityThread.java)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:915)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: Caused by: java.lang.IllegalStateException: PPS出现多实例
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at com.tencent.shadow.dynamic.host.PluginProcessService.onCreate(PluginProcessService.java:74)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3162)
04-02 17:56:59.847 13625 13625 E AndroidRuntime:        ... 8 more
04-02 17:56:59.887 13625 13813 D VOS_HttpStringRequest:  --KEYPATH-- Request{method=POST, url=http://iepg-b03.vosnewland.com:9444/daq/collect}

原因是service，接受到unbind会调用onUnbind-->onDestroy-->onCreate。
此时问题来了，下面代码抛了异常。
 @Override
    public void onCreate() {
        if (sSingleInstanceFlag == null) {
            sSingleInstanceFlag = new Object();
        } else {
            throw new IllegalStateException("PPS出现多实例");
        }
        super.onCreate();
        if (mLogger.isInfoEnabled()) {
            mLogger.info("onCreate:" + this);
        }
    }

我们在调用bindService绑定PluginProcessService之前，使用startService启动了一次它。这样就不存在这个问题了。不知道是否会导致重复加载Loader、Runtime、业务等插件，进而出现非常奇怪的异常。
修改位置：PluginManagerThatUseDynamicLoader.java的bindPluginProcessService方法。

**Comment by shifujun** [comment]
另外的问题开新的Issue记录。Issue不是针对人的问答功能，是跟踪记录问题的。同样的，复现问题还是不要自己描述代码，直接给出可复现问题可运行的代码最准确。
