### ISSUE TITLE
咨询Shadow 插件化 几个问题

### ISSUE THREAD

**Issue by yuzzjj** [Tencent/Shadow#278]
1.安全性这块是否影响，譬如签名，混淆，等代码加固方式

2.对于用户体验影响 ，跟原生apk区别，可用性，兼容性 

3.开发维护工作量，对比360replugin

4. 性能是否受影响. 插件中包含如下:蓝牙，网络, 摄像头， 麦克风等频繁硬件调用;

5.插件主要业务功能集中在，对插件中so使用，权限使用，手机摄像头，麦克风，蓝牙有什么限制吗

**Comment by shifujun** [comment]
这几点问题其实都可以通过了解Shadow的实现原理来理解。虽然我们文档不是特别多，但是重要的内容已经都写在Wiki里链接的那些文章中了。

我再简单回答一下这些点吧。

Shadow的插件本质上就是宿主代码的一部分。所以插件的签名跟系统完全不会产生关系，Shadow也没有实现对插件的插件进行签名校验。对插件的签名校验可以在Manager中实现，欢迎贡献代码。我们自身业务主要靠宿主对data目录安全性的保护，以及插件下载通过ssl链接进行保护的。

Proguard完全没有问题。其他加固方式要看实现的原理了。

Shadow的目标主要是希望插件的源码可以直接编译成可以正常安装的app。所以只要没有bug，跟正常安装apk在体验上应该是没有什么区别的。性能上可能会受首次加载时采用解释执行dex而有些影响，不过这和其他动态加载dex的技术也没什么区别。如果有更好的dex加载方案，也可以合入Shadow。

开发维护的工作量，可以说是非常小的了。完全不需要考虑兼容OEM系统，因为没有调用任何非公开API。虽然说有可能有些功能没有支持，但如果业务没有新功能，可以说单单因为Android系统本身更新，Shadow是不用维护的。所以，我们业务这边也没有什么人力专门维护Shadow。

I/O相关的性能应该完全没有影响，插件代码就是宿主的一部分。在系统看来是一样的。

so使用没有影响。

权限相关的东西，Shadow也没有黑魔法，完全看宿主申请了什么权限。插件代码是宿主的一部分，自然只能用宿主已有的权限。

**Comment by yuzzjj** [comment]
多谢， 这么快速回复，赞！！

另外问一下   插件与 宿主 app 同样类名， 资源，依赖  需要考虑 冲突解决问题吗

**Comment by shifujun** [comment]
不用。插件和宿主的ClassLoader、Resource都是隔离的。如果插件要访问宿主的类需要通过白名单机制设置允许访问的类。资源就完全要靠双方约定的Java接口进行交换了。

**Comment by yuzzjj** [comment]
谢谢！！，后续深入调研学习

**Comment by oppogazige** [comment]
> 不用。插件和宿主的ClassLoader、Resource都是隔离的。如果插件要访问宿主的类需要通过白名单机制设置允许访问的类。资源就完全要靠双方约定的Java接口进行交换了。

你好，关于资源需要靠双方约定的Java接口进行交换具体是指什么意思哈？

**Comment by shifujun** [comment]
> 你好，关于资源需要靠双方约定的Java接口进行交换具体是指什么意思哈？我现在遇到个问题，插件使用白名单中的类，因为白名单的类调用到了宿主的资源，而导致出现加载错误，对于这类问题该如何处理呢？

Android的资源管理要通过Context和Resources来管理，插件和宿主是不同的Context和Resources。所以插件不能直接用Android定义的资源ID去访问宿主的资源。但是插件可以和宿主约定一个Java层面的接口，接口上传递具体的资源类型，比如Bitmap。这样接口的实现就是宿主在宿主的代码里跟Android的Context和Resources类型沟通，插件也是一样。

如果还有问题，另外提Issue吧。最好带上你的代码。
