### ISSUE TITLE
无法加载插件apk,并且host crash；host与插件apk的applicationID是一样的，该如何解决？？谢

### ISSUE THREAD

**Issue by lp821020589** [Tencent/Shadow#281]
03-25 17:42:18.188  4504  4504 I cr_DRP  : No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
03-25 17:42:18.380  4504  4504 W cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
03-25 17:42:18.409  4504  4534 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
03-25 17:42:18.409  4504  4534 E JavaBinder: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.ClassCastException: com.w
ellcom.visitorattendancedevice.application.MyApplication cannot be cast to com.tencent.shadow.core.runtime.ShadowApplication
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.FutureTask.report(FutureTask.java:94)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.FutureTask.get(FutureTask.java:164)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:82)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:42)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at android.os.Binder.execTransact(Binder.java:565)
03-25 17:42:18.409  4504  4534 E JavaBinder: Caused by: java.util.concurrent.ExecutionException: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.ClassCastException: com.wellcom.visitorattendancedevice
.application.MyApplication cannot be cast to com.tencent.shadow.core.runtime.ShadowApplication
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.FutureTask.report(FutureTask.java:94)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.FutureTask.get(FutureTask.java:164)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildRunningPlugin$1.run(LoadPluginBloc.kt:146)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at java.lang.Thread.run(Thread.java:761)
03-25 17:42:18.409  4504  4534 E JavaBinder: Caused by: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.ClassCastException: com.wellcom.visitorattendancedevice.application.MyApplication cannot be cast
 to com.tencent.shadow.core.runtime.ShadowApplication
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.core.loader.blocs.CreateApplicationBloc.createShadowApplication(CreateApplicationBloc.kt:65)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(LoadPluginBloc.kt:127)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(LoadPluginBloc.kt:42)
03-25 17:42:18.409  4504  4534 E JavaBinder:    ... 4 more
03-25 17:42:18.409  4504  4534 E JavaBinder: Caused by: java.lang.ClassCastException: com.wellcom.visitorattendancedevice.application.MyApplication cannot be cast to com.tencent.shadow.core.runtime.ShadowApplication
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.core.runtime.ShadowAppComponentFactory.instantiateApplication(ShadowAppComponentFactory.java:12)
03-25 17:42:18.409  4504  4534 E JavaBinder:    at com.tencent.shadow.core.loader.blocs.CreateApplicationBloc.createShadowApplication(CreateApplicationBloc.kt:50)
03-25 17:42:18.409  4504  4534 E JavaBinder:    ... 6 more
03-25 17:42:18.417  2618  6193 I ActivityManager: START u0 {cmp=com.tencent.shadow.sample.host/com.wellcom.visitorattendancedevice.activity.MainActivity} from uid 10068 on display 0
03-25 17:42:18.420 21241  4327 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
03-25 17:42:18.420 21241  4327 E AndroidRuntime: Process: com.tencent.shadow.sample.host, PID: 21241
03-25 17:42:18.420 21241  4327 E AndroidRuntime: java.lang.RuntimeException: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.wellcom.visitorattendancedevice.activ
ity.MainActivity}; have you declared this activity in your AndroidManifest.xml?
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:120)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
03-25 17:42:18.420 21241  4327 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.wellcom.visitorattendancedevice.activity.MainActivity}
; have you declared this activity in your AndroidManifest.xml?
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4225)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4183)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4522)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4490)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:121)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:118)
03-25 17:42:18.420 21241  4327 E AndroidRuntime:        ... 3 more
03-25 17:42:18.424  2618  3544 W ActivityManager:   Force finishing activity com.tencent.shadow.sample.host/.PluginLoadActivity
03-25 17:42:18.431 21241  4327 I Process : Sending signal. PID: 21241 SIG: 9
03-25 17:42:18.432  2618  4015 I Legacy PowerHAL: ==NORMAL MODE==
03-25 17:42:18.432  2618  4015 E Legacy PowerHAL: Error opening /sys/devices/soc/cpu_budget_cool.7/roomage: No such file or directory
03-25 17:42:18.533  2618  3336 W InputDispatcher: channel '24c7901 com.tencent.shadow.sample.host/com.tencent.shadow.sample.host.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-25 17:42:18.534  2618  3336 E InputDispatcher: channel '24c7901 com.tencent.shadow.sample.host/com.tencent.shadow.sample.host.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-25 17:42:18.534  2618  3336 W InputDispatcher: channel '11c67c4 com.tencent.shadow.sample.host/com.tencent.shadow.sample.host.PluginLoadActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-25 17:42:18.534  2618  3336 E InputDispatcher: channel '11c67c4 com.tencent.shadow.sample.host/com.tencent.shadow.sample.host.PluginLoadActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-25 17:42:18.535  2618  6185 I ActivityManager: Process com.tencent.shadow.sample.host (pid 21241) has died
03-25 17:42:18.535  2618  6185 D ActivityManager: cleanUpApplicationRecord -- 21241

**Comment by shifujun** [comment]
>03-25 17:42:18.409 4504 4534 E JavaBinder: Caused by: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.ClassCastException: com.wellcom.visitorattendancedevice.application.MyApplication cannot be cast
to com.tencent.shadow.core.runtime.ShadowApplication

你的这个`MyApplication`没有被Transform成`ShadowApplication`，或者是配置错了`Application`。总之没有代码，只能猜。建议你在sample里复现问题，push上来，这样就好定位问题了。

**Comment by shifujun** [comment]
如果有进展，欢迎随时再打开Issue。
