### ISSUE TITLE
单插件多进程支持

### ISSUE THREAD

**Issue by vimerzhao** [Tencent/Shadow#282]
从代码来看，组件的process信息都是没有处理的，这样原来的在不同进程的组件应该会被放到同一进程，和独立运行的App还是有很多差异的。这个有考虑支持吗？

**Comment by shifujun** [comment]
插件不能运行在宿主Manifest注册的进程之外，这个应该清楚吧？所以原理上，插件都要运行在PPS所在的进程。那么哪个PPS里的Loader去启动插件的组件，那插件就运行在哪个进程里。

所以，如果说做一个插件注册的process和宿主中的PPS的对应关系，自动的决定由哪个PPS启动插件的组件。这个是没什么难度的。没有实现主要是我们的业务没有这种场景。

欢迎贡献代码😃

**Comment by vimerzhao** [comment]
> 所以，如果说做一个插件注册的process和宿主中的PPS的对应关系，自动的决定由哪个PPS启动插件的组件。这个是没什么难度的。没有实现主要是我们的业务没有这种场景。

这个确实不难，我已经实现了，但是如果我有一个Service，负责管理进程，现在打成插件之后，每个PPS都会代理这个Service的实例，简单来说按照现在的策略，Service就没有跨进程能力了。
我理解应该是这样吧。

**Comment by shifujun** [comment]
> > 所以，如果说做一个插件注册的process和宿主中的PPS的对应关系，自动的决定由哪个PPS启动插件的组件。这个是没什么难度的。没有实现主要是我们的业务没有这种场景。
> 
> 这个确实不难，我已经实现了，但是如果我有一个Service，负责管理进程，现在打成插件之后，每个PPS都会代理这个Service的实例，简单来说按照现在的策略，Service就没有跨进程能力了。
> 我理解应该是这样吧。

肯定不会这样的。不应该每个PPS都代理你那个特别的Service呀，应该只有一个PPS启动这个插件的Service。插件的Service的binder都是真的binder，是可以正常跨进程通信的。
