### ISSUE TITLE
存在转换后被调用方法未实现的问题

### ISSUE THREAD

**Issue by lp821020589** [Tencent/Shadow#283]
存在转换后被调用方法未实现的问题，详见E:\Shadow\projects\sample\source\sample-plugin\sample-weier-app\build\shadow_replace_class_have_right_methods764636990658451102.txt

文件中的内容：

Class com.tencent.shadow.core.runtime.ShadowInstrumentation中缺少方法:
newApplication:(Ljava/lang/Class;Landroid/content/Context;)Lcom/tencent/shadow/core/runtime/ShadowApplication;被这些类调用了:
de.greenrobot.dao.test.DbTest

**Comment by shifujun** [comment]
这个实现应该很简单的。我们没有贸然实现全部的方法是怕没有使用的场景而实现错误。

欢迎贡献代码🙂

**Comment by a6685234** [comment]
请问是怎么解决的
