### ISSUE TITLE
ClassCastException(cannot be cast to ShadowActivity) reproduced in Shadow source sample

### ISSUE THREAD

**Issue by buaasparkle** [Tencent/Shadow#285]
我在 PR #284 的 comment 中描述了重现场景和对应的代码修改，希望有空时可以帮助解答，谢谢～

**Comment by shifujun** [comment]
插件不能继承宿主中的Activity。你可以把BaseActivity中那些需要复用的逻辑抽到一个普通类里。

**Comment by buaasparkle** [comment]
好的，谢谢，fragment 也应该是一样吗？

**Comment by shifujun** [comment]
> fragment 也应该是一样吗？

是的。凡是插件里父类被修改了的，都一样。

**Comment by buaasparkle** [comment]
> > fragment 也应该是一样吗？
> 
> 是的。凡是插件里父类被修改了的，都一样。

好的 感谢～
