### ISSUE TITLE
需要支持startActivityFromChild

### ISSUE THREAD

**Issue by Dovar66** [Tencent/Shadow#287]
由于插件中的Activity在编译期都被tansform成ShadowActivity了，而ShadowActivity不是Activity的子类，所以当调用入参是Activity的函数时，如果使用this关键字，虽然开发时正常，但运行会出错。对于这种情况，有没有什么好的解决方案？另外插件Activity中该怎么获取当前Activity对象？

**Comment by shifujun** [comment]
你了解Activity都变成ShadowActivity了，那也应该知道入参是Activity的函数也会变成入参是ShadowActivity的函数呀。所以不应该会出现你说的问题。

所以在描述问题时，怎么说都不如用代码来说话。

非要猜的话，假如入参是Activity的函数是另外一个没有经过Shadow Transform的apk动态加载的，那么还是会出现你说的情况。但如果有这种前提，你描述问题时应该会主动说的吧？

**Comment by Dovar66** [comment]
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        TextView tv = new TextView(this);
        tv.setText("点我试试");
        tv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent();
                startActivityFromChild(MainActivity.this, intent, 100);
            }
        });
        setContentView(tv);
    }

当然这个demo比较特殊，不用关系它的实际意义，但的确可能存在这种场景。

另外，请问现在插件是不支持运行在主进程吗？

**Comment by shifujun** [comment]
你举例的代码会Crash是因为startActivityFromChild这个API需要特别支持，Shadow目前没有支持。

而单说this指针的问题，像我前面说的，像这样的例子就会工作正常的。
```
@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TextView tv = new TextView(this);
        tv.setText("点我试试");
        tv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                toastClassname(MainActivity.this);
            }
        });
        setContentView(tv);
    }

    void toastClassname(Activity activity) {
        ToastUtil.showToast(activity, activity.getComponentName().getClassName());
    }
```

**Comment by shifujun** [comment]
本来想支持一下这个方法的。结果我连用这个api的例子都不会写。搜了半天也没找到一个例子。

看了一下API文档：
https://developer.android.com/reference/android/app/Activity#startActivityFromChild(android.app.Activity,%20android.content.Intent,%20int,%20android.os.Bundle)

>This method was deprecated in API level R.
Use androidx.fragment.app.FragmentActivity#startActivityFromFragment( androidx.fragment.app.Fragment,Intent,int,Bundle)

这样的话，还是不支持这个API了。androidx目前Shadow已经都支持了，尽量用androidx吧。

**Comment by Dovar66** [comment]
的确，这种我目前也没有实际的使用场景，只是在demo里乱写东西的时候发现的。那么关于另一个问题，请问现在插件是不支持运行在主进程吗？

**Comment by shifujun** [comment]
支持，自己试试就知道了。

**Comment by Dovar66** [comment]
谢谢答疑
