### ISSUE TITLE
不要升级任何组件版本，升级后空安全提醒比比皆是

### ISSUE THREAD

**Issue by onewilk** [Tencent/Shadow#291]
尝试把版本号升级为我现在工程用的gradle和kotlin版本，满满的错误提醒。。。
看了下，目前项目里kotlin代码中的空安全提醒大多是用!!来强制去除的，还有很多应该做空安全检查的地方都没有做空检查。。。

提醒下大家，不要手贱。。。

**Comment by shifujun** [comment]
这个升级应该工作量不是特别大。Shadow里用到的!!都是从Java传入Kotlin的地方，所以都敢直接用!!。应该不存在逻辑上需要判空的地方没有判空。

这个等dev分支修好合入master之后，可以升级一下kotlin版本到下一个稳定版。

**Comment by shifujun** [comment]
这个可以打开，找时间改进一下。
