### ISSUE TITLE
kill掉host主进程后，报错PPS出现多实例

### ISSUE THREAD

**Issue by crimeline** [Tencent/Shadow#293]
代码见：https://github.com/crimeline/Shadow/tree/issue275

### kill掉host主进程后，报错如下：
04-02 17:56:59.847 13625 13625 E AndroidRuntime: FATAL EXCEPTION: main
04-02 17:56:59.847 13625 13625 E AndroidRuntime: Process: com.android.vpsclient:plugin, PID: 13625
04-02 17:56:59.847 13625 13625 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.tencent.shadow.sample.host.PluginProcessPPS: java.lang.IllegalStateException: PPS出现多实例
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at android.app.ActivityThread.handleCreateService(ActivityThread.java:3172)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at android.app.ActivityThread.-wrap5(ActivityThread.java)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at android.os.Looper.loop(Looper.java:154)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6077)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:915)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: Caused by: java.lang.IllegalStateException: PPS出现多实例
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at com.tencent.shadow.dynamic.host.PluginProcessService.onCreate(PluginProcessService.java:74)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: at android.app.ActivityThread.handleCreateService(ActivityThread.java:3162)
04-02 17:56:59.847 13625 13625 E AndroidRuntime: ... 8 more
04-02 17:56:59.887 13625 13813 D VOS_HttpStringRequest: --KEYPATH-- Request{method=POST, url=http://iepg-b03.vosnewland.com:9444/daq/collect}

### 原因：
是service，接受到unbind会调用onUnbind-->onDestroy-->onCreate。
此时问题来了，下面代码抛了异常。
@override
public void onCreate() {
if (sSingleInstanceFlag == null) {
sSingleInstanceFlag = new Object();
} else {
throw new IllegalStateException("PPS出现多实例");
}
super.onCreate();
if (mLogger.isInfoEnabled()) {
mLogger.info("onCreate:" + this);
}
}

### 暂定解决方案：
我们在调用bindService绑定PluginProcessService之前，使用startService启动了一次它。这样就不存在这个问题了。不知道是否会导致重复加载Loader、Runtime、业务等插件，进而出现非常奇怪的异常。
修改位置：PluginManagerThatUseDynamicLoader.java的bindPluginProcessService方法。

**Comment by twoCleaner** [comment]
这样的话, 在PluginProcessService::onDestroy里面去reset会不会更好一点

**Comment by charles-yinyu** [comment]
这个问题我在实践中也遇到了。具体情况是，系统资源紧张时，主进程被回收，但插件进程仍然存在；当再次进入插件页面时，即会报"PPS出现多实例"异常。具体原因楼主也指出了，静态变量与进程同生死，PPS退出了，静态变量仍然存在。

直观来看，有两个方法解决该问题：
1，在PluginProcessService::onDestroy里面去reset静态变量sSingleInstanceFlag（二楼提出的方法）
2，PluginProcessService与插件进程强绑定，PPS退出时强制退出插件进程

方案1复用了插件进程，但是否会导致同一个进程内重复加载Loader、Runtime、业务等插件，进而出现非常奇怪的异常？需要对框架源码掌握非常透彻才能确保成功复用了插件进程；

方案2简单直接，符合作者对PPS的定位，即“PPS应该代表插件进程的生命周期。插件进程应该由PPS启动而启动”，那么插件进程也应该因PPS退出而退出。

综上，我采用的第2个方案，将PPS与插件进程的生命绑定，同生死，具体操作则是在PPS的onDestroy里执行已有的exit方法。

另外，有一个疑问，PPS部署在host包中（即宿主中），无法动态化，为什么不部署在插件中或者manager中，这一点还请作者指点下， @shifujun

**Comment by shifujun** [comment]
@charles-yinyu 前面讲的我都同意。修改sSingleInstanceFlag没有意义，那个检测逻辑就是为了避免无意识的复用插件进程出现许许多多奇怪的问题难以定位的。

PPS不能动态化，PPS有两个作用：
1. 作为注册给系统的组件，启动它可以触发启动插件进程。这一点通过启动壳子Activity也可以做到，但是启动Activity需要非常快的执行完插件加载等操作，否则Activity界面显示不出来会卡住。

2. 插件Service的binder之所以能够正常跨进程通信，是因为按照Binder机制的原理，插件的binder都经过PPS这个已经存在的Binder通信过，所以才会注册进Binder系统内成为可以跨进程通信的binder。也就是说PPS是所有插件Service的“壳子”。

**Comment by hjqiaho** [comment]
> 

请教下所说的exit是PPS的exit方法吗，方法默认是私有的，是需要自己改成public调用吗 @charles-yinyu

**Comment by cyberau** [comment]
> 是service，接受到unbind会调用onUnbind-->onDestroy-->onCreate
@crimeline 你好，问下onDestroy后为什么会执行onCreate？

**Comment by cyberau** [comment]
@shifujun 你好，我也遇到“PPS出现多实例”的问题。我的pps和宿主在同一个进程。应该有两种情况。
1. 我的插件和宿主是在同一个进程，按理说如果主进程被回收，那pps应该也不存在了，那启动app应该就是正常流程，也不会出现这个问题。
2. 如果只是pps被回收了，主进程还在，那sSingleInstanceFlag还存在，也没有再次调用初始化，那也应该不会走到启动pps这里。
3. 初始化时也是确保不会初始化两次。
所以暂时没有头绪了。也请指点下这个问题。
