### ISSUE TITLE
宿主绿三角运行没有问题，打正式APK失败，build打出的APK无法安装

### ISSUE THREAD

**Issue by weiwenqiang** [Tencent/Shadow#294]
十分感谢作者的多次帮助，都很有作用

运行调试各方面都没什么问题，就打正式包时失败，我用的AndroidX，kotlin我改到了1.3.70，运行一直也没问题，打包失败后尝试很多环境，回退到1.3.10，依然不行，怀疑用了路由，但是直接编译运行没什么问题，打包就失败

第一个红：
Interface `android.app.SharedElementCallback(classpath class)` used as super class of `androidx.core.app.ActivityCompat$SharedElementCallback21Impl`.

错误栈
:armscore:dexBuilderRelease
Interface `android.app.SharedElementCallback(classpath class)` used as super class of `androidx.core.app.ActivityCompat$SharedElementCallback21Impl`.
org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.DexArchiveBuilderTaskDelegate$DexConversionWorkAction
org.gradle.tooling.BuildException: Failed to process G:\zp\android\BDJW\BdjwArmsCorePlugInMode\projects\project\bdjw\host\armscore\build\intermediates\transforms\com.alibaba.arouter\release\75.jar
com.android.builder.dexing.DexArchiveBuilderException: Failed to process G:\zp\android\BDJW\BdjwArmsCorePlugInMode\projects\project\bdjw\host\armscore\build\intermediates\transforms\com.alibaba.arouter\release\75.jar
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
com.android.tools.r8.utils.b: Error: Interface `android.app.SharedElementCallback(classpath class)` used as super class of `androidx.core.app.ActivityCompat$SharedElementCallback21Impl`.
Failed to process G:\zp\android\BDJW\BdjwArmsCorePlugInMode\projects\project\bdjw\host\armscore\build\intermediates\transforms\com.alibaba.arouter\release\75.jar
Error: Interface `android.app.SharedElementCallback(classpath class)` used as super class of `androidx.core.app.ActivityCompat$SharedElementCallback21Impl`

不知道是否与我宿主引用路由冲突？
![图片](https://user-images.githubusercontent.com/16027666/78417846-df1b3500-7668-11ea-89ce-e0059847141c.png)

**Comment by shifujun** [comment]
ARoute之前也有人问过，所以测过是能用的。 #38

你的这个问题是dev分支目前本身就没能编译过的问题。建议你先使用master分支。

具体来说问题是： #194 生成了全部Activity的方法，有些方法的签名上带有高版本API才有的类型，比如`SharedElementCallback`。这样在低版本机器上运行时就会找不到类（#230）。所以就提交了 2bd5f7d0 加了这些类的空定义。但是这些类又是系统类，Proguard在检查的时候又会说`android.app.Activity`这个系统类依赖了App里的类`SharedElementCallback`，这是不行的。所以现在问题就停在这了。

可能 2bd5f7d0 那种添加空定义的修复方案行不通。那么我们就得想办法在生成类中去掉这些可能只在高版本上才有的类型了。
