### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by ckrgithub** [Tencent/Shadow#3]
![image](https://user-images.githubusercontent.com/18225851/59770463-aaf1a600-92da-11e9-9195-c8b7a6986ec6.png)

**Comment by shifujun** [comment]
截图不完整，看不到使用的命令。请注意必须使用gradlew脚本。

**Comment by ckrgithub** [comment]
我是用gradlew脚本的。
![image](https://user-images.githubusercontent.com/18225851/59773442-34f03d80-92e0-11e9-9819-01b184c217b6.png)

**Comment by wuMaoTou** [comment]
windows平台要使用gradlew.bat编译
`gradlew.bat build`

**Comment by ckrgithub** [comment]
也编译不通过。可能是我改了些配置原因：
classpath "com.android.tools.build:gradle:3.0.1"
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

我升级一下studio后看看

**Comment by shifujun** [comment]
我不明白为什么你改了代码而编译不通过要来提issue问，然后还不在描述中先说明你改了代码。

你可能不明白Gradle Wrapper的设计就是用来保证使用的Gradle版本就是项目设计的版本。正是由于你把代码中设置的Gradle版本从5.0降低为了4.1才导致的编译不过。

另外，Gradle是不依赖于Android Studio的。实际上是Android Studio依赖Gradle。所以你尝试升级studio也是没有道理的。

**Comment by ckrgithub** [comment]
so sorry
