### ISSUE TITLE
Android 11 preview 版本，插件内部资源not found

### ISSUE THREAD

**Issue by enzowyf** [Tencent/Shadow#300]
![image](https://user-images.githubusercontent.com/34463867/78855070-84614f00-7a55-11ea-9768-890e45980ac1.png)

日前收集到一例找不到插件内部资源的情况，Android 11 preview 版本必现， 10和以下版本暂时未发现。

考虑到目前11还不是正式版本，不能笃定就一定是版本兼容问题。

由于资源有限，手头没有合适的设备，暂时无法做更多的验证。有更多信息，会及时更新。

这里做个风险提示，希望author和各使用者关注。

**Comment by shifujun** [comment]
这个版本的虚拟机已经可以下载了。我抽空试一下sample在上面是否正常。

```
Packages to install: 
- Google APIs Intel x86 Atom_64 System Image (system-images;android-R;google_apis;x86_64)

Preparing "Install Google APIs Intel x86 Atom_64 System Image (revision: 2)".
Downloading http://dl.google.com/android/repository/sys-img/google_apis/x86_64-R_r02.zip
```

**Comment by shifujun** [comment]
[connected.zip](https://github.com/Tencent/Shadow/files/4454087/connected.zip)

`./gradlew androidTestSdk`确实基本都挂了。需要细看一下原因。

**Comment by shifujun** [comment]
试了一下sample-host，可以正常工作。和资源相关的“Activity 主题测试”也能正常运行。

看起来没什么大问题。自动化测试挂了，可能是自动化测试框架有问题。

**Comment by shifujun** [comment]
升级了espresso版本到3.3.0-alpha05后基本都工作正常了，看起来没有能确定的bug了。

**Comment by enzowyf** [comment]
最新进展，昨天之前在模拟器上能稳定复现，今天模拟器有系统更新提示，更新后，这个bug消失
