### ISSUE TITLE
在Android studio3.4.2版本上sync gradle报错Could not find com.tencent.shadow.core:runtime-debug:.

### ISSUE THREAD

**Issue by crimeline** [Tencent/Shadow#302]
最新节点上。
Could not find com.tencent.shadow.core:runtime-debug:.
Required by:
    project :sample-plugin-app
Search in build.gradle files

![image](https://user-images.githubusercontent.com/30657747/78959914-f9e52200-7b1e-11ea-8cb4-892eaa3af3ed.png)

命令行./gradlew build编译正常。

**Comment by shifujun** [comment]
`./gradlew build`编译正常，说明Android Studio有缺陷。每个版本的Android Studio一般只能适配一段范围的Gradle版本。再加上Shadow用了复合构建，这个场景在大部分App里又不常见。所以出问题也正常吧。

我在用3.6.2版本Android Studio，你可以试试。

**Comment by crimeline** [comment]
好的。
测试在3.5上也是可以的，我准备更新了。
提个问题只是为了提醒下别个。

**Comment by shifujun** [comment]
改了README。
