### ISSUE TITLE
Fragment#setTargetFragment未实现

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Tencent/Shadow#307]
```
Class androidx.preference.PreferenceDialogFragment_中缺少方法:
getTargetFragment:()Lcom/tencent/shadow/core/runtime/ShadowFragment;被这些类调用了:
androidx.preference.PreferenceDialogFragment_

Class com.tencent.shadow.core.runtime.ShadowDialogFragment中缺少方法:
setTargetFragment:(Lcom/tencent/shadow/core/runtime/ShadowFragment;I)V被这些类调用了:
androidx.preference.PreferenceFragment_
```

```java
    /**
     * Return the target fragment set by {@link #setTargetFragment}.
     */
    final public Fragment getTargetFragment() {
        return mTarget;
    }
```

**Comment by shifujun** [comment]
愿意自己研究一下怎么实现，可以参考一下`https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/PackageManagerTransform.kt#L88`的实现，其中这个`redirectMethodCallToStaticMethodCall`方法可以把所有原本对`getTargetFragment()`方法的调用改调用到另一个类的静态方法上。这样就可以任意修改该调用的行为了。

这个方法只有一个限制是不能修改系统类或者动态加载的apk中的调用，本质上是修改了插件app自身代码。

**Comment by shifujun** [comment]
我看了一下这个问题，其实不涉及前面说的代理final方法。因为Fragment类型已经被改写成ShadowFragment了。所以其实涉及的3个方法直接实现就好了。
