### ISSUE TITLE
startForegroundService 相关未实现

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Tencent/Shadow#309]
android 8 以上不允许后台服务，要用 startForegroundService 来启动服务，并在 5 喵内推一个服务的通知

目前 startService 虽然可用，但是感觉不用 startForegroundService 的话会有隐患。。。

**Comment by shifujun** [comment]
现在插件的service都依赖pps传递的binder。所以其实算是一对多的代理。前台service如果要显示通知的话，应该只能有一个插件service传过去通知。

这块我还不太了解系统的规定。要是有相关文档的链接可以贴一下。先讨论下实现方向。

**Comment by Eyey110** [comment]
> 现在插件的service都依赖pps传递的binder。所以其实算是一对多的代理。前台service如果要显示通知的话，应该只能有一个插件service传过去通知。
> 
> 这块我还不太了解系统的规定。要是有相关文档的链接可以贴一下。先讨论下实现方向。

8.0以后调用startService需要通过setForeground来绑定一个前台通知栏。不然5秒后会直接抛异常

目前看shadowService没有实现setForeground，可以考虑直接创建出插件的Notification绑定到插件的PPS上

**Comment by shifujun** [comment]
> 8.0以后调用startService需要setForeground，之后必须在5秒内通过startForeground来绑定一个前台通知栏。不然会直接抛异常

这里说的行为是否区分targetAPI呢？最好贴一下官方的文档。

我是认为Service部分值得彻底重写一下。

**Comment by LinXueyuanStdio** [comment]
官方文档在这里：https://developer.android.com/guide/components/services#StartingAService

targetAPI >= 26

> 注意：如果您的应用面向 API 级别 26 或更高版本，除非应用本身在前台运行，否则系统不会对使用或创建后台服务施加限制。如果应用需要创建前台服务，则其应调用 startForegroundService()。此方法会创建后台服务，但它会向系统发出信号，表明服务会将自行提升至前台。创建服务后，该服务必须在五秒内调用自己的 startForeground() 方法。

我又谷歌里一下，发现前排就是自己博客，emmm....
http://xichen.pub/2018/10/25/2018-10-25-Android-TimeCat-context.startforegroundservice()didnotthencallservice.startforeground()/

我曾经被这个魔幻规定坑惨了，看到您的重视我很开心～

**Comment by LinXueyuanStdio** [comment]
后台执行限制的官方文档：https://developer.android.com/about/versions/oreo/background.html

> 在 Android 8.0 之前，创建前台 Service 的方式通常是先创建一个后台 Service，然后将该 Service 推到前台。 Android 8.0 有一项复杂功能：系统不允许后台应用创建后台 Service。 因此，Android 8.0 引入了一种全新的方法，即 startForegroundService()，以在前台启动新 Service。 在系统创建 Service 后，应用有五秒的时间来调用该 Service 的 startForeground() 方法以显示新 Service 的用户可见通知。 如果应用在此时间限制内未调用 startForeground()，则系统将停止此 Service 并声明此应用为 ANR。
