### ISSUE TITLE
有个问题请教一下：HostUiLayerProvider插件是如何跟宿主进行进程间通信的。

### ISSUE THREAD

**Issue by crimeline** [Tencent/Shadow#311]
sample-host-list中的HostUiLayerProvider，插件中能使用宿主的类。

我看的是的在宿主中调用了，在插件中获取下对象，然后就能使用其中的类。

我不是很明白插件如何能获取到那个对象，它是如何做到的，求告知。

**Comment by shifujun** [comment]
这个Debug一下应该能很清楚吧。关于如何做到，你还是需要说清楚你觉得哪里你会觉得做不到，为什么？否则讲清楚如何做到，可能要从ClassLoader的知识讲起了。

**Comment by crimeline** [comment]
宿主中调用init创建的HostUiLayerProvider对象属于host进程，plugin进程是如何获取到这个HostUiLayerProvider对象。
我觉得这是两个进程，应该要有进程间通信，但是我在debug（PluginUseHostClassActivity）中没有看到。

**Comment by shifujun** [comment]
噢，这个只是因为HostApplication在plugin进程也会运行嘛。

**Comment by crimeline** [comment]
感谢感谢。明白了，没有进程间通信。
老是忘了HostApplication所有进程都会启动一次，默认归属host进程了，导致的这个误区。

**Comment by HeLiHuang** [comment]
> 感谢感谢。明白了，没有进程间通信。 老是忘了HostApplication所有进程都会启动一次，默认归属host进程了，导致的这个误区。

没明白啊，为啥啊，为啥HostApplication所有进程都会启动一次，这不是宿主的Application吗？
