### ISSUE TITLE
有什么方法可以让我配置一些类，这些类里面不进行transfrom么？

### ISSUE THREAD

**Issue by hanswook** [Tencent/Shadow#314]
我的插件里面有用到so文件。so文件中有用反射直接寻找某个类的某个方法。
例如：
public class DemoA {
    public static void init(Activity activity){
}
}
因为这个类在插件里，打包的时候参数Activity 会被转为shadowActivity。
但是在运行的时候，so文件中找的还是参数为Activity的方法，这个时候就会报错。
java.lang.NoSuchMethodError: no static method "Lcom/demo/demoA.init(Landroid/app/Activity;)V".
麻烦帮忙看一下。

**Comment by dongbingbin77** [comment]
这个问题我也遇到了，同问

**Comment by shifujun** [comment]
反射和强制类型转换的弊端都会在Shadow这里暴露出来。

单说保持一个接口上的类型是Activity，还是比较容易的。可以在ActivityTransform中跳过这个类，也可以额外添加一个Transform再将这个类中的Activity类型改回去。

但是，我估计这样是行不通的。因为插件里的Activity确实已经都改成ShadowActivity了，将一个ShadowActivity传给Activity类型的接口上，还是会抛异常的。

合理的做法应该是在so中不要依赖Activity类型，可以自定义一个接口，让Activity实现它，在so里操作这个接口。或者，简单一点，将接口上的Activity类型直接改成Object类型，在so里反射调用它。

**Comment by hanswook** [comment]
多谢，我再想想办法

**Comment by OldWilliam** [comment]
有想到什么办法吗
