### ISSUE TITLE
能问下目前有哪些线上的app是基于shadow开发的么？

### ISSUE THREAD

**Issue by bm-x** [Tencent/Shadow#315]

**Comment by shifujun** [comment]
公司规矩很严，这个我实在不方便随意透露最新数据。

最初的[开源公告](https://mp.weixin.qq.com/s/lBiJEdD81yOBVqsqXpPRww)上有一句内容：

> Shadow支撑了QQ群视频、Now直播、腾讯即玩等业务比较复杂、访问量巨大的业务
