### ISSUE TITLE
插件中获取到的宿主的application最终都会被转化为ShadowApplication，导致无法满足业务需求

### ISSUE THREAD

**Issue by sup-IT-man** [Tencent/Shadow#321]
在插件中获取到了宿主的Application，但是在使用的时候就被框架转化为了ShadowApplication，所以在框架中是否有方式不对Application进行转化 的方法

**Comment by shifujun** [comment]
如果想跳过一些类中Transform Application类型的逻辑，可以自己在https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/ApplicationTransform.kt 中添加一些特殊逻辑。

不过我猜这不是你想要的。因为没有代码，我也只能猜。我猜你并不需要以Application类型操作宿主的Application对象。要么应该是Context类型，要么应该自定义接口。
