### ISSUE TITLE
用命令行编译没问题，用Studio无法编译

### ISSUE THREAD

**Issue by kiss718867** [Tencent/Shadow#322]
用命令行能正确读出环境变量，用Studio时System.getenv()获取到的是下面这些，导致无法编译，请问是哪里的配置有问题吗
local.properties也正确生成了

> null 
PATH - /usr/bin:/bin:/usr/sbin:/sbin 
SSH_AUTH_SOCK - /private/tmp/com.apple.launchd.WGJKKfpo6m/Listeners 
SHELL - /bin/zsh 
XPC_FLAGS - 0x0 
__CF_USER_TEXT_ENCODING - 0x7F384FD8:0x19:0x34 
Apple_PubSub_Socket_Render - /private/tmp/com.apple.launchd.oGyBHwwtqu/Render 
LOGNAME - ---
XPC_SERVICE_NAME - com.google.android.studio.58188 
USER - ---
HOME - /Users/---
TMPDIR - /var/folders/zw/w4zp0gf57w1d2z00wskdlk1dzlhlyr/T/

**Comment by shifujun** [comment]
如果你刚设置的环境变量，又不知道该怎么使它生效，可能重启一下计算机是最简单的办法了。

**Comment by kiss718867** [comment]
> 如果你刚设置的环境变量，又不知道该怎么使它生效，可能重启一下计算机是最简单的办法了。

感谢
执行了source .bash_profile，也重启了电脑，都不可以，诡异的是在我另一台电脑上顺利跑起来了
我去查查这两台电脑配置有什么区别，问题先关掉
