### ISSUE TITLE
Livedata 订阅activity类型的通知收不到？

### ISSUE THREAD

**Issue by victorwrage** [Tencent/Shadow#324]
model = activity?.run {
                ViewModelProvider(this)[SharedViewModel::class.java]
            } ?: throw Exception("Invalid Activity")

            model.nickname.observe(activity as AppCompatActivity, Observer {
            
                refreshNickname(it)
            })
请问要怎么改

**Comment by shifujun** [comment]
在不接入shadow时`refreshNickname`收到调用的调用栈什么样？发出来看看。

或者参考
https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue
将代码push上来。

**Comment by shifujun** [comment]
跟这个调用是一样的吗？
https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sample/sunflower/plugin-project/app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt#L71

**Comment by shifujun** [comment]
> 跟这个调用是一样的吗？
> https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sample/sunflower/plugin-project/app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt#L71

我测试了这处调用的断点，是能够收到调用的。

可能#312 合入后才正常工作的。你可以看一下你用的Shadow代码是不是最新的。

**Comment by victorwrage** [comment]
更新了后是可以的，但是我的dialog fragment动画缺失了

**Comment by shifujun** [comment]
> 更新了后是可以的，但是我的dialog fragment动画缺失了

那另外建个issue给个复现的例子吧。
