### ISSUE TITLE
关于Shadow中的RuntimeException

### ISSUE THREAD

**Issue by BiaoWu** [Tencent/Shadow#325]
那么多的运行时异常是否太暴力了啊。。。

这块目前是否有计划？

**Comment by shifujun** [comment]
Shadow用的RuntimeException可以说都是有计划的。首先我们应该有个讨论的前提是认同RuntimeException是有合理应用的场景的。而不是指凡是用了RuntimeException的代码都是粗暴处理异常的。

那么Shadow里面显得粗暴的返回RuntimeException的地方，都是表达没有容错逻辑的场景。如果说粗暴，也没错。如果一个异常可以以Checked Exception方式处理，应该可以改进。

但举个例子，比如说：
https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sdk/dynamic/dynamic-host/src/main/java/com/tencent/shadow/dynamic/host/ImplLoader.java#L49

这里如果白名单定义的类在apk里找不到，则会抛出RuntimeException。如果改为Checked Exception，就是声明throws WhiteListClassNotFoundException，要求调用loadWhiteList的代码处理这种情况。但是看起来这也没什么好容错的。apk里找不到类了，调用的代码能干什么呢？打行Log？

上面这个例子可能跟你想的不一样，你可以也这样举个例子。

如果从业务Crash率的角度关心这些RuntimeException的话，则有两种角度考虑这个问题：

1. 这些加载插件的代码，几乎没什么分支逻辑。按我们的业务要求，发布版本是要留守观察1小时的。所以如果出现Crash，我们很快就能发现修复问题。RuntimeException抛出会带有清晰的堆栈，便于准确解决问题。

2. 如果希望避免Crash，展示更友好的用户界面。可以在调用Shadow的线程中统一捕获RuntimeException。这有赖于调用的代码使用Excutor框架，比如我们的示例代码：
https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sample/maven/manager-project/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java#L35
使用了ExecutorService调用PluginLoader接口。Executor框架可以把全部RuntimeException封装到Future中返回，这样调用代码就可以处理这些异常了。

**Comment by BiaoWu** [comment]
感谢如此迅速、精美的回复！很棒！

主要因为公司对Crash特别敏感。
近期在项目中实践shadow，担心同一个进程内的多插件异常影响整个进程。
