### ISSUE TITLE
关于Shadow中Binder

### ISSUE THREAD

**Issue by BiaoWu** [Tencent/Shadow#326]
比如同一个进程使用pps，目前pps直接走的Binder逻辑。（类似的还有）
此块应该值得优化吧。

近期准备在项目中实践Shadow
因为业务中多进程支持可能还不到位，可能同宿主进程运行插件。

**Comment by shifujun** [comment]
同进程依然使用Binder通信确实不如aidl自动生成的代码中同进程直接使用接口调用性能好。

但是性能好坏这个事也要看应用场景的。PPS的接口都不是频繁调用的，所以这个性能应该影响不大。不一定值得优化。如果对这些调用造成的启动速度影响很敏感，建议也先从插件体积本身优化，那样效果更明显。

实现的时候，采用统一Binder通信也是为了保证在同进程和跨进程两种情况下代码逻辑一致，不易出Bug。

你的#327 构建失败了，好像是被取消了，是你自己取消的吗？不是的话可以重试一下。跑通过了我再细看。

不过粗看的话，改了host模块。这是我们比较谨慎的，因为host模块是打包在宿主中不能动态更新的。所以如果真的要提供一个在同进程下不使用Binder的实现，最好是以新增类新增代码的方式提供。极尽可能不修改host，使线上代码兼容。新增代码也应该和host现有实现兼容。例如`dynamic-host-multi-loader-ext`那样新增一个模块。

**Comment by shifujun** [comment]
忘说了，建议遵循“先实现，后优化”的原则，先保证结果正确性，再考虑优化性能。新业务可以先上线，只需要考虑未来优化是可行性即可。比如确定下一个版本的宿主换一个host实现，也可以跟旧版本插件相兼容。那么就可以先在第一个版本先上线没有修改的版本。

**Comment by BiaoWu** [comment]
嗯，确实相比较加载插件本身，这点优化微乎其微，调用频率也很低。

还是您考虑的周到，看了一下确实已经有的host 和 dynamic-manager部分会不兼容。
