### ISSUE TITLE
Build failed with connection timeout

### ISSUE THREAD

**Issue by AnswerZhao** [Tencent/Shadow#33]
Now could not resolve com.tencent.shadow.core:common:2.0.12-782812a5-SNAPSHOT from maven, and it warns that  'Remote host closed connection during handshake'.

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/dev/projects/sample/README.md#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sample

这段README我晚点再补充一下。是少解释了一段。

`maven`这个sample中实际上是期待从`mavenLocal()`找到SDK实现的。所以需要先自行发布一下到`mavenLocal()`。而SDK上配置好的maven任务的目标已经是`mavenLocal()`了。所以只需要按照
https://github.com/Tencent/Shadow/blob/dev/projects/sample/README.md#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sample
发布一下SDK就行了。但是需要将因引用的版本号改成实际发布的，主要是`782812a5 `这部分hash。

**Comment by AnswerZhao** [comment]
@shifujun 多谢啦
