### ISSUE TITLE
关于api28以上插件使用httpclient

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#330]
Shadow里有这样一段逻辑：
https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoader.kt#L72-L74

Google相关的文档有：
https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p

相关问答有：
https://stackoverflow.com/a/55122149/11616914

我写了几个测试用例，想验证这个逻辑：#329

但是有个问题暂时没时间确定清楚：

- [x] "Beginning with Android 9, that library is removed from the bootclasspath and is not available to apps by default."这个表述的意思是否是说在构建设置中配置什么可以使app不自行打包httpclient就能从bootclasspath中加载到？

**Comment by shifujun** [comment]
这个问题与插件相关的是：
当正常安装运行时依赖于在manifest中声明:
```
<uses-library android:name="org.apache.http.legacy" android:required="false"/>
```
时，
系统安装这个apk会解析manifest，发现这个声明，从而保持低版本api的逻辑，给app的BootClassLoader注入这个库。

Shadow就算解析出这个声明也无法从系统中获得这个库的ClassLoader。所以插件只有两个选择：
1. 让宿主做这个声明，从而使宿主ClassLoader可以加载到这个库。插件把`org.apache.http`和`org.apache.http.**`声明到白名单中就行了。
2. 插件自己打包这个库。可以用： 
```
// https://mvnrepository.com/artifact/org.jbundle.util.osgi.wrapped/org.jbundle.util.osgi.wrapped.org.apache.http.client
implementation 'org.jbundle.util.osgi.wrapped:org.jbundle.util.osgi.wrapped.org.apache.http.client:4.1.2'
```

另，声明`uses-library`时，AGP添加的compileOnly依赖只是一个stub实现的jar包。

**Comment by michaelxs** [comment]
亲测有效，感谢大佬
