### ISSUE TITLE
求助 如何设置插件的activity动画

### ISSUE THREAD

**Issue by 4iconfont** [Tencent/Shadow#331]
我在sample-host工程里修改PluginDefaultProxyActivity的动画，只修改
了sample-host工程里的themes.xml，如下

<style name="troop_Transparent" parent="@android:style/Theme">
      XXXXXX不变
        <item name="android:windowAnimationStyle">@style/Animation.Activity.Translucent.Style</item>  --->修改了这里
    </style>
 
    <style name="Animation.Activity.Translucent.Style" parent="@android:style/Animation.Translucent">
        <item name="android:windowEnterAnimation">@anim/support_act_slide_in</item>  ---->任意动画
        <item name="android:windowExitAnimation">@anim/support_act_slide_out</item>  ---->任意动画
    </style>

在general-cases-lib插件工程也用同样的方式修改

跑起来后没有期望般生效，请问大佬有解决方案吗？

**Comment by 4iconfont** [comment]
屏蔽ShadowActivity overridePendingTransition对资源的限制，使用固定资源的id，就可以了

**Comment by shifujun** [comment]
我再补充一下。Shadow这种实现原理，不能正常应对系统直接回调app取资源的动画。比如`overridePendingTransition`就是系统从这个方法获得资源id。然后直接向宿主apk索取这个动画资源播放，作用于Activity上。在这个实现的路径上，我们的代码没有任何办法可以hook这个调用。

所以，`overridePendingTransition`的动画只能用宿主中的资源。

所以在动画方面，推荐采用Fragment动画来实现。那些不依赖系统调用的动画应该是支持的。
