### ISSUE TITLE
使用dialogfragment时没有动画效果

### ISSUE THREAD

**Issue by victorwrage** [Tencent/Shadow#332]
`public void onResume() {
        Window window = getDialog().getWindow();
         
        window.setWindowAnimations(getAnimationStyle());
        super.onResume();
    }

   protected abstract int getAnimationStyle();`

这样没有动画效果，请问我该怎么改

**Comment by shifujun** [comment]
请参考
https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue
提供一个能运行的例子。这样做是为了节约时间，我这边不是全职在维护项目。

**Comment by shifujun** [comment]
研究了一下这个问题，看起来暂时没什么办法支持。详见commit message。
