### ISSUE TITLE
AlertDialog向上转型为Dialog时报错

### ISSUE THREAD

**Issue by o0starshine0o** [Tencent/Shadow#334]
先附上frok链接：
https://github.com/o0starshine0o/Shadow/tree/dialog

插件中的Dialog会被转换成ShadowDialog；
如果返回的是AlertDialog，但是用Dialog作为返回类型（注意，这边在插件运行时会被转换）
就会出现”AlertDialog“无法转换成”ShadowDialog“的错误。
--------
尝试了写AlertDialogTransform和ShadowAlertDialog，但是AlertDialog.Builder.show()返回的是AlertDialog，不能用”ShadowAlertDialog“（AlertDialog的子类）接受。
-------
目前只能修改项目，不出现这种情况，但是不知道怎么才能漂亮的解决这个问题。
希望 @shifujun 大神帮忙

**Comment by shifujun** [comment]
Dialog的支持方式应该可以被优化。应该不需要一个ShadowDialog作为父类。

实现方式应该和f1d0f5b5ae5b74e9cb9c156a4f75c1f8fbc9acd7是一样的。

将`setOwnerActivity`和`getOwnerActivity`的调用转调到静态方法上即可。

你可以自己尝试一下，我可能要周末有时间才能写这个。
