### ISSUE TITLE
BroadcastReceiver报NullPointerException

### ISSUE THREAD

**Issue by o0starshine0o** [Tencent/Shadow#336]
参考fork：
https://github.com/o0starshine0o/Shadow/tree/receiver
pull:
https://github.com/Tencent/Shadow/pull/335

因为在ShadowContext中执行registerReceiver方法时没有判定receiver是否为null就进行了注册。
而mBroadcastReceivers是HashMap，会把null放在首位，并不会做其他检测。
因此，在真正收到广播的时候就会报错：
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.BroadcastReceiver.onReceive(android.content.Context, android.content.Intent)' on a null object reference
        at com.tencent.shadow.core.runtime.BroadcastReceiverWapper.onReceive(BroadcastReceiverWapper.java:20)
```

解决办法是检测receiver是否为null，如果是null就不进行注册，直接返回空的intent。
增强一下Shadow的健壮性。

大神看下这样处理是否妥当。

**Comment by shifujun** [comment]
实现的原则是模仿系统行为。你说的这个场景在没有Shadow参与的正常App里是这样的行为吗？

我大概看确认一下这个就可以合入了。晚点处理。

**Comment by o0starshine0o** [comment]
刚看文档测试了一下，官方的做法是返回一个符合filter的Intent：
参考：源码注释
```
@return The first sticky intent found that matches <var>filter</var>,
     *         or null if there are none.
```

所以调整下代码，返回官方的intent
```
Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) }
```
参考frok：
https://github.com/o0starshine0o/Shadow/tree/receiver
pull：
https://github.com/Tencent/Shadow/pull/335
