### ISSUE TITLE
请教关于runtime的问题

### ISSUE THREAD

**Issue by BiaoWu** [Tencent/Shadow#340]
请教一下，runtime一个进程应该只能有一份hack吧。

![image](https://user-images.githubusercontent.com/8017691/82778884-42655e80-9e85-11ea-8d15-af28fd08821f.png)

我们知道PluginProcessService pps在loadRuntime的时候会hack一个RuntimeLoader到宿主PathClassLoader之上，为了上宿主启动PluginContainerActivity的时候能找到runtime中的Activity类

那么如果说 #333 中实现的时候，本想同进程多个uuid有自己的runtime
![image](https://user-images.githubusercontent.com/8017691/82779145-fbc43400-9e85-11ea-8908-39b3a35d93e3.png)

同进程内宿主启动activity的时候应该只会拿到宿主PathClassLoader的直接父类RuntimeClassLoader去loadClass（className）

**Comment by shifujun** [comment]
最好是共用一个runtime。因为里面的壳子要在宿主Manifest里注册才能用，至少宿主里有类继承它们 了。所以runtime和宿主是强绑定的。在 685f6139fcf95e775ccd23e0f58a29283af77cb4 和 fff8e87525436d5719a15231828d55e7049fe62c 提交之后。runtime其实变成了"activity-container"，只是名字没改，真正的"runtime"（包含ShadowActivity等类型）已经合入loader里了。所以RuntimeClassLoader里的类其实动态更新的诉求已经非常小了。其实完全合入host也是可以的，只是它的方法数增量非常大，我们才有保留这个hack的理由。

如果各自用各自的runtime，那最好就给它们的类改名，保证它们不重名。

**Comment by BiaoWu** [comment]
> 最好是共用一个runtime。因为里面的壳子要在宿主Manifest里注册才能用，至少宿主里有类继承它们 了。所以runtime和宿主是强绑定的。在 [685f613](https://github.com/Tencent/Shadow/commit/685f6139fcf95e775ccd23e0f58a29283af77cb4) 和 [fff8e87](https://github.com/Tencent/Shadow/commit/fff8e87525436d5719a15231828d55e7049fe62c) 提交之后。runtime其实变成了"activity-container"，只是名字没改，真正的"runtime"（包含ShadowActivity等类型）已经合入loader里了。所以RuntimeClassLoader里的类其实动态更新的诉求已经非常小了。其实完全合入host也是可以的，只是它的方法数增量非常大，我们才有保留这个hack的理由。
> 
> 如果各自用各自的runtime，那最好就给它们的类改名，保证它们不重名。

嗯嗯。我这里表达的runtime就是宿主清单文件里的那些Activity哦

各自用各自的也不好处理。。。
每个runtime的Activity写自己的类名就需要在宿主壳子注册这个Activity类。。。死路了。。。

所以同进程多loader这块实现（ #333 ）
1、要么是host直接接入activity-container，那各个地方就不需要runtime这个包了。缺点就是runtime不支持动态更新了
2、进程内共用一份runtime
