### ISSUE TITLE
编译时报错 java.lang.ClassCastException@3217cc04`

### ISSUE THREAD

**Issue by DerekYanJ** [Tencent/Shadow#342]
你好 插件loader编译失败 gradle从3.2.0升级到3.6.3后出现
`> Task :app:mergeDebugResources
> Task :app:processDebugResources
> Task :app:compileDebugKotlin
> Task :commlib:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
> Task :commlib:extractDebugAnnotations UP-TO-DATE
> Task :commlib:mergeDebugGeneratedProguardFiles UP-TO-DATE
> Task :commlib:mergeDebugConsumerProguardFiles UP-TO-DATE
> Task :commlib:mergeDebugJavaResource UP-TO-DATE
> Task :commlib:syncDebugLibJars UP-TO-DATE
> Task :commlib:bundleDebugAar UP-TO-DATE
> Task :commlib:compileDebugSources UP-TO-DATE
> Task :commlib:assembleDebug UP-TO-DATE
> Task :commlib:jarDebugPackage
> Task :loader:preBuild
> Task :loader:preDebugBuild
> Task :loader:compileDebugAidl NO-SOURCE
> Task :loader:compileDebugRenderscript NO-SOURCE
> Task :loader:generateDebugBuildConfig FAILED
> Task :app:javaPreCompileDebug
> Task :agora-plugin:mergeDexRelease

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':loader:generateDebugBuildConfig'.
> java.lang.ClassCastException@3217cc04`

**Comment by shifujun** [comment]
如果你什么都没改的话，应该是本地的一些编译缓存的问题，清理一下编译缓存吧。
`./gradlew clean`如果不行，就`git clean -fd`，还不行就`git clean -fdx`。

另外，可以看到升级3.6.3的提交在CI上是可以编译成功的。
https://github.com/Tencent/Shadow/actions/runs/113110976
