### ISSUE TITLE
请教关于只加载插件但不跳转activity的问题

### ISSUE THREAD

**Issue by DerekYanJ** [Tencent/Shadow#349]
您好，目前所知需要点击加载插件按钮并且跳转到指定activity方式加载插件，业务需求是在应用启动后，后台静默加载插件，不跳转activity，目的是初始化插件中Application下的第三方库相关的服务。
问下需要做些什么改动实现上述需求

**Comment by DerekYanJ** [comment]
不了解gradle语法，目前plugin-debug.zip直接打包到assets里了，怎么才能只输出到指定路径呢？

**Comment by shifujun** [comment]
不需要任何改动。只要注意一下`FastPluginManager`只是sample代码，不是SDK代码。SDK代码中只提供了插件启动的各个原子方法，没有提供类似于“启动插件Activity”这样的便捷方法。所以只需要参考`FastPluginManager`的调用流程自行修改启动过程就可以了。

**Comment by shifujun** [comment]
> 不了解gradle语法，目前plugin-debug.zip直接打包到assets里了，怎么才能只输出到指定路径呢？

不相关的问题下次请不要放在同一个issue里。

不了解Gradle语法，这个你只能自学了。我没有精力回答通用的技术问题。

> 直接打包到assets里了

这你应该完全没仔细看项目呢，建议先仔细看看。你说的只是sample工程。

**Comment by DerekYanJ** [comment]
好的 谢谢
