### ISSUE TITLE
插件怎么接入

### ISSUE THREAD

**Issue by chenyunecjtu** [Tencent/Shadow#35]
如题：
直接这样就可以吗？ 需要额外配置什么吗？
`apply plugin: 'com.tencent.shadow.plugin'`

**Comment by shifujun** [comment]
插件和宿主都要接入Shadow才能正常工作。

接入方式见
https://github.com/Tencent/Shadow/blob/dev/projects/sample/README.md#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sample
的说明。

其中跟你问题描述相关的文件是
https://github.com/Tencent/Shadow/blob/dev/projects/sample/maven/plugin-project/plugin-shadow-apk/build.gradle

**Comment by chenyunecjtu** [comment]
@shifujun 
`afterEvaluate {
    android {
        buildTypes.findAll().each { buildType ->
            def buildTypeName = buildType.getName()
            def task = project.getTasksByName("check${buildTypeName.capitalize()}Classpath", false).first() as Task
            task.dependsOn gradle.includedBuild('core').task(':common:jarDebugPackage')
            task.dependsOn gradle.includedBuild('dynamic').task(':dynamic-host:jarDebugPackage')
        }
    }
}`

我看loader runtime 后面都有这个配置 可以去掉吗

**Comment by shifujun** [comment]
在二进制依赖方式时可以去掉。你贴的这些构建配置，都是为了让那个源码依赖的sample能直接依赖SDK的最新源码状态，所以有很多非常繁琐的构建脚本。

在正式接入到项目中用的时候肯定是二进制依赖的，就是以maven引用的方式依赖。所以单独写了`projects/sample/maven`演示，就是为了演示正式接入时构建脚本中应该怎么配置。

**Comment by shifujun** [comment]
另外，我不太确定你接入的目的是什么。我原本预计大家应该拿到代码都是想先实验性的尝试，研究原理之类的。这种场景，我还是建议去修改源码依赖的sample，这样可以方便的断点，修改SDK源码，反复运行尝试。

可以把你们的业务代码直接复制到`projects/sample/sample-plugin/sample-app-lib`中测试。

**Comment by chenyunecjtu** [comment]
谢谢

**Comment by chenli3238** [comment]
> 如题：
> 直接这样就可以吗？ 需要额外配置什么吗？
> `apply plugin: 'com.tencent.shadow.plugin'`

你是怎么接入shadow的？必须发布到maven里再依赖吗

**Comment by shifujun** [comment]
> > 如题：
> > 直接这样就可以吗？ 需要额外配置什么吗？
> > `apply plugin: 'com.tencent.shadow.plugin'`
> 
> 你是怎么接入shadow的？必须发布到maven里再依赖吗

最好是发布到Maven仓库再通过Maven方式依赖。Shadow的组件非常多，本地jar包依赖会很麻烦的。Shadow已经给写好了Maven发布和如何依赖的代码。

**Comment by chenli3238** [comment]
> > > 如题：
> > > 直接这样就可以吗？ 需要额外配置什么吗？
> > > `apply plugin: 'com.tencent.shadow.plugin'`
> > 
> > 
> > 你是怎么接入shadow的？必须发布到maven里再依赖吗
> 
> 最好是发布到Maven仓库再通过Maven方式依赖。Shadow的组件非常多，本地jar包依赖会很麻烦的。Shadow已经给写好了Maven发布和如何依赖的代码。

发布完如何依赖？我已经改好，发布，但是依赖不成功

**Comment by shifujun** [comment]
依赖的示例已经写好了，看这段README
https://github.com/Tencent/Shadow/tree/dev/projects/sample#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven

**Comment by chenli3238** [comment]
> 依赖的示例已经写好了，看这段README
> https://github.com/Tencent/Shadow/tree/dev/projects/sample#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven

发步完其他项目依赖报错，找不到

**Comment by shifujun** [comment]
有问题的同学请fork版本库，将复现问题的代码上传。否则我们怎么看是什么问题呢？
