### ISSUE TITLE
startActivityForResult问题

### ISSUE THREAD

**Issue by linuxjava** [Tencent/Shadow#350]
### 1.场景
（1）有宿主、插件A、插件B，他们运行在同一个进程；
（2）插件A希望使用startActivityForResult启动插件B的activity

### 2.做法
（1）核心是通过convertActivityIntent获得转换后的intent 
final Intent intent = convertActivityIntent(installedPlugin, partKey, pluginIntent);
 intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
（2）然后在插件A的activity中调用startActivityForResult启动
MainActivity.this.startActivityForResult(intent, 10000);

### 3.现象
（1）插件B页面能正常启动，插件B Activity代码如下：
#### 4.1测试1
（1）插件B页面不调用setResult和finish方法
**（2）插件B启动的同时，插件A的onActivityResult被调用了（注：此时插件B Activity并未退出）**
#### 4.2测试2：
（1）在插件B添加如下代码
**（2）当插件插件B Activity退出时，插件A的onActivityResult也不会被调用**
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if(keyCode == KeyEvent.KEYCODE_BACK){
            Intent intent = new Intent();
            intent.putExtra("result", "plugin-a data test");
            setResult(1001, intent);
            finish();
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }

### 5.补充：
（1）同一插件内startActivityForResult跳转和返回是正常的
（2）插件间activity的startActivityForResult就会出现上面的问题

### 6.插件B Activity代码：
```
public class MainActivity extends AppCompatActivity implements View.OnClickListener {
    private TextView mInfo;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    public void onClick(View v) {
        int id = v.getId();

    }
}
```

**Comment by shifujun** [comment]
方不方便push上来一个fork后继续修改提交的分支？让我能clone下来直接跑起来复现问题的？

参考：
https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue

**Comment by linuxjava** [comment]
问题已找到，是intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);的问题；正常APP也有这个问题
