### ISSUE TITLE
Android 5.1 throw ZipExeception Entry not name

### ISSUE THREAD

**Issue by ycxGHub** [Tencent/Shadow#356]
运行SampleHost ，在Android5.1系统报错：
`06-05 18:59:20.281 9277-9323/com.tencent.shadow.sample.host E/com.tencent.shadow.core.manager.BasePluginManager: extractSo exception:
    com.tencent.shadow.core.manager.installplugin.InstallPluginException: 解压so 失败 apkFile:/data/data/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/db67b07d8f7e6bd29b930145c765440d/plugin-debug.zip/sample-plugin-app-debug.apk abi:lib//
        at com.tencent.shadow.core.manager.installplugin.CopySoBloc.copySo(CopySoBloc.java:100)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:198)
        at com.tencent.shadow.sample.manager.FastPluginManager$3.call(FastPluginManager.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.util.zip.ZipException: Entry is not named
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:251)
        at com.tencent.shadow.core.manager.installplugin.SafeZipInputStream.getNextEntry(SafeZipInputStream.java:32)
        at com.tencent.shadow.core.manager.installplugin.CopySoBloc.copySo(CopySoBloc.java:69)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:198) 
        at com.tencent.shadow.sample.manager.FastPluginManager$3.call(FastPluginManager.java:89) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
`

**Comment by ycxGHub** [comment]
以下为5.1中源码
`public ZipEntry getNextEntry() throws IOException {
        closeEntry();
        if (entriesEnd) {
            return null;
        }

        // Read the signature to see whether there's another local file header.
        Streams.readFully(in, hdrBuf, 0, 4);
        int hdr = Memory.peekInt(hdrBuf, 0, ByteOrder.LITTLE_ENDIAN);
        if (hdr == CENSIG) {
            entriesEnd = true;
            return null;
        }
        if (hdr != LOCSIG) {
            return null;
        }

        // Read the local file header.
        Streams.readFully(in, hdrBuf, 0, (LOCHDR - LOCVER));
        int version = peekShort(0) & 0xff;
        if (version > ZIPLocalHeaderVersionNeeded) {
            throw new ZipException("Cannot read local header version " + version);
        }
        int flags = peekShort(LOCFLG - LOCVER);
        if ((flags & ZipFile.GPBF_UNSUPPORTED_MASK) != 0) {
            throw new ZipException("Invalid General Purpose Bit Flag: " + flags);
        }

        hasDD = ((flags & ZipFile.GPBF_DATA_DESCRIPTOR_FLAG) != 0);
        int ceLastModifiedTime = peekShort(LOCTIM - LOCVER);
        int ceLastModifiedDate = peekShort(LOCTIM - LOCVER + 2);
        int ceCompressionMethod = peekShort(LOCHOW - LOCVER);
        long ceCrc = 0, ceCompressedSize = 0, ceSize = -1;
        if (!hasDD) {
            ceCrc = ((long) Memory.peekInt(hdrBuf, LOCCRC - LOCVER, ByteOrder.LITTLE_ENDIAN)) & 0xffffffffL;
            ceCompressedSize = ((long) Memory.peekInt(hdrBuf, LOCSIZ - LOCVER, ByteOrder.LITTLE_ENDIAN)) & 0xffffffffL;
            ceSize = ((long) Memory.peekInt(hdrBuf, LOCLEN - LOCVER, ByteOrder.LITTLE_ENDIAN)) & 0xffffffffL;
        }
        int nameLength = peekShort(LOCNAM - LOCVER);
        if (nameLength == 0) {
            throw new ZipException("Entry is not named");
        }
        int extraLength = peekShort(LOCEXT - LOCVER);

        String name = readString(nameLength);
        currentEntry = createZipEntry(name);
        currentEntry.time = ceLastModifiedTime;
        currentEntry.modDate = ceLastModifiedDate;
        currentEntry.setMethod(ceCompressionMethod);
        if (ceSize != -1) {
            currentEntry.setCrc(ceCrc);
            currentEntry.setSize(ceSize);
            currentEntry.setCompressedSize(ceCompressedSize);
        }
        if (extraLength > 0) {
            byte[] extraData = new byte[extraLength];
            Streams.readFully(in, extraData, 0, extraLength);
            currentEntry.setExtra(extraData);
        }
        return currentEntry;
    }`
修改为
` ZipFile zipFile= new ZipFile(file);
 Enumeration<? extends ZipEntry> zipFiles = zipFile.entries();
if (zipFiles.hasMoreElements()){
     ZipEntry entry = zipFiles.nextElement();
｝
`
遍历ZipEntry后问题解决

**Comment by shifujun** [comment]
为什么关了呢？到底有没有bug呢？

**Comment by shifujun** [comment]
我在API 19的模拟器上复现了这个问题。一时有点懵，怎么会一直没发现。

**Comment by shifujun** [comment]
>cd55646eef1c50ffc1d0f963b800141479399840 is the first bad commit
commit cd55646eef1c50ffc1d0f963b800141479399840
Author: shifujun <shifujun@foxmail.com>
Date:   Sat May 23 15:21:10 2020 +0800

    chore: 升级build_tool_gradle版本到3.6.3,Gradle版本到5.6.4
    
    对齐Android Studio 3.6.3版本创建的模板项目。
    
    #291

用git bisect找出来是这个提交改坏的。有点奇怪怎么会有这种影响。

**Comment by ycxGHub** [comment]
> > [cd55646](https://github.com/Tencent/Shadow/commit/cd55646eef1c50ffc1d0f963b800141479399840)是第一个错误提交
> > 提交[ cd55646](https://github.com/Tencent/Shadow/commit/cd55646eef1c50ffc1d0f963b800141479399840) 
> > 作者：shifujun[ shifujun@foxmail.com](mailto:shifujun@foxmail.com) 
> > 日期：周六5月23日15时21分10秒2020 +0800
> 
> ```
> chore: 升级build_tool_gradle版本到3.6.3,Gradle版本到5.6.4
> 
> 对齐Android Studio 3.6.3版本创建的模板项目。
> 
> #291
> ```
> 
> 用git bisect寻找来是这个提交改坏的。有点奇怪怎么会有这种影响。



> 为什么关了呢？到底有没有bug呢？

Bug有的，不清楚具体原因，但是根据5.1中的ZipInputStream源码
``` java
        int nameLength = peekShort(LOCNAM - LOCVER);
        if (nameLength == 0) {
            throw new ZipException("Entry is not named");
        }
```
的确会抛出异常。暂时解决方法是不使用ZipInputStream解压缩,而使用以下方法解压成功
``` java
     ZipFile zipFile= new ZipFile(file);
   Enumeration<? extends ZipEntry> zipFiles = zipFile.entries();
   if (zipFiles.hasMoreElements()){
     ZipEntry entry = zipFiles.nextElement();
  ｝ 
```

**Comment by ycxGHub** [comment]
**Debug** 生成的`sample-plugin-app-debug.apk`中`26`到`27`字节都为`0x00`，所以在Android `5.1`中`nameLength`的确为0会抛出异常，而使用**Release** 生成的`sample-plugin-app-release.apk`中`26`到`27`字节为`0x13`,`0x00`，`nameLength`不为0，结果能够正常解压缩。
简单的将`sample-plugin-app`中的`build.gradle`中的`debug` 和`release`配置调换一下，sampleHostApp 的debug也可以通过了，所以猜测问题应该是gradle 构建Apk时候有所不同导致的。
建议修改解压缩代码，使用`ZipFile`类解压缩而不是`ZipInputStream`。

**Comment by shifujun** [comment]
查阅了一下资料，也比较确定ZipFile比ZipInputStream更适合我们的场景。

https://stackoverflow.com/a/19799569/11616914

https://books.google.com.hk/books?id=g0X1TJJYLUAC&pg=PA687&lpg=PA687&dq=difference+between+ZipFile+and+ZipInputStream&source=bl&ots=NtKBwHbiZf&sig=ACfU3U2EVSIWzxI-ljnErBT4MWvptdKfDw&hl=en&sa=X&ved=2ahUKEwj00dXT-PPpAhVuF6YKHeB9D1YQ6AEwBHoECAkQAQ#v=onepage&q=difference%20between%20ZipFile%20and%20ZipInputStream&f=false
![image](https://user-images.githubusercontent.com/3535204/84107904-7af26400-aa51-11ea-8ebb-64695cb4bdba.png)

结论是ZipFile支持随机读取，性能更好。

另外用ZipFile也需要注意ZipperDown漏洞。
