### ISSUE TITLE
零hook方式怎么解决插件资源的加载问题

### ISSUE THREAD

**Issue by fredanf** [Tencent/Shadow#357]

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/4ad5668d3954aea0e076955aa97d0b96351d3592/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt#L40-L48

我猜你想问的是这个。这个其实就是公开的API，Android系统本来就是允许基于未安装的apk创建Resources对象的。

**Comment by fredanf** [comment]
很多插件化方案是通过hook AssertManager，然后根据hook出来的AssertManager来构造Resource来加载资源的。
望回答，先谢了。

**Comment by shifujun** [comment]
> 很多插件化方案是通过hook AssertManager，然后根据hook出来的AssertManager来构造Resource来加载资源的。

我的意思就是说，这种方法是没必要的。有现成可用的公开API可以构造Resources对象。

**Comment by fredanf** [comment]
> 很多插件化方案是通过hook AssertManager，然后根据hook出来的AssertManager来构造Resource来加载资源的。
> 望回答，先谢了。

> > 很多插件化方案是通过hook AssertManager，然后根据hook出来的AssertManager来构造Resource来加载资源的。
> 
> 我的意思就是说，这种方法是没必要的。有现成可用的公开API可以构造Resources对象。

了解，其实就是packageManager.getResourcesForApplication这个公开API是吧。

**Comment by shifujun** [comment]
是的。
