### ISSUE TITLE
如何预加载插件，以便快速启动Activity？

### ISSUE THREAD

**Issue by xuyunyu** [Tencent/Shadow#361]
如何预加载插件，以便快速启动Activity？

感谢。

**Comment by shifujun** [comment]
首先要注意到FastPluginManager只是一个sample代码。
其中`com.tencent.shadow.sample.manager.FastPluginManager#preparePlugin`方法执行完，插件就处于Application已经启动的状态，但还没有启动任何Activity。

**Comment by xuyunyu** [comment]
> 首先要注意到FastPluginManager只是一个sample代码。
> 其中`com.tencent.shadow.sample.manager.FastPluginManager#preparePlugin`方法执行完，插件就处于Application已经启动的状态，但还没有启动任何Activity。

你是指 installPlugin ？ ，没看到preparePlugin 方法

**Comment by shifujun** [comment]
噢，我刚才切到其他人改的分支上了。

master分支上是
https://github.com/Tencent/Shadow/blob/a0ea9d59443f538631e445a96dc9d51babbe9497/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java#L127

**Comment by xuyunyu** [comment]
> > 首先要注意到FastPluginManager只是一个sample代码。
> > 其中`com.tencent.shadow.sample.manager.FastPluginManager#preparePlugin`方法执行完，插件就处于Application已经启动的状态，但还没有启动任何Activity。
> 
> 你是指 installPlugin ？ ，没看到preparePlugin 方法

感觉更像是 loadPlugin

**Comment by xuyunyu** [comment]
> 噢，我刚才切到其他人改的分支上了。
> 
> master分支上是
> https://github.com/Tencent/Shadow/blob/a0ea9d59443f538631e445a96dc9d51babbe9497/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java#L127

感谢大佬

**Comment by xuyunyu** [comment]
Close

**Comment by xuyunyu** [comment]
> 噢，我刚才切到其他人改的分支上了。
> 
> master分支上是
> https://github.com/Tencent/Shadow/blob/a0ea9d59443f538631e445a96dc9d51babbe9497/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java#L127

大佬，请问怎么卸载一个插件（用完了插件服务，不需要这个服务），或者怎么重新加载一个插件？

**Comment by shifujun** [comment]
你是说运行时吗？运行时不能卸载插件，Android的JVM不支持的。so一旦加载也不能卸载的。

如果是说安装的存储，需要自己写一下了。之前有回复过：
https://github.com/Tencent/Shadow/issues/251#issuecomment-573658587

**Comment by xuyunyu** [comment]
感谢
