### ISSUE TITLE
sample和test中的provider authorities不应该hardcode

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#362]
https://github.com/Tencent/Shadow/blob/4e03ebafa2ad9d5021917ec8d51ba26d59fd6dde/projects/test/plugin/general-cases/general-cases-lib/src/main/AndroidManifest.xml#L83

应该改为用`${applicationId}`拼接，这样可以避免同时安装这些apk的冲突。

**Comment by BiaoWu** [comment]
应该是宿主里面的provider authorities冲突了吧
