### ISSUE TITLE
插件中依赖qmui报transformClassesWithShadowTransformForDebug

### ISSUE THREAD

**Issue by xiaonima666** [Tencent/Shadow#364]
报错信息：Execution failed for task ': plugin1: transformClassesWithShadowTransformForDebug'. 
javassist.CannotCompileExcetion: createFormFontFamilyFilesResourceEntry...... 

这是子插件的依赖，大佬帮忙看一下，
implementation 'com.qmuiteam:qmui:2.0.0-alpha10'
implementation 'com.qmuiteam:arch:2.0.0-alpha10'

**Comment by shifujun** [comment]
麻烦参考
https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue
提供一个最小改动的复现场景。

或者先简单的贴一下报错信息。

我刚才把这两个依赖加到sample里不能正常编译，暂时没时间修复编译问题。所以麻烦你先处理好了。

**Comment by xiaonima666** [comment]
就是只要依赖了就无法编译，报上边的错

**Comment by shifujun** [comment]
你所谓“上边的错”只是一行而已啊。你至少传一个完成的构建日志。最好还是加上`-S`选项的日志。

**Comment by shifujun** [comment]
你看我上传的代码。我把sample里的代码都删了，只依赖你说的这两行。没能复现问题。

**Comment by xiaonima666** [comment]
好，我晚上回去先把代码上传

**Comment by shifujun** [comment]
额，你最好别把一堆代码传上来。diff量太大也是没法看的。最好最好是在我的分支上加一点代码复现问题。我这里已经加上了你要的依赖，而没能复现问题。

https://github.com/shifujun/Shadow/tree/issue364

**Comment by xiaonima666** [comment]
https://github.com/xiaonima666/TestShadow
这是搞了个简单实现的例子，都是只有一个activiy 互跳，我在插件plugin1去掉qmui 的依赖完全可以运行🤣，加上编译就不行了，放到comonlibrary这module下也不行🤣
这是完整保存日志 https://github.com/xiaonima666/TestShadow/blob/master/errorMessage.md

**Comment by shifujun** [comment]
这日志里写的很清楚了嘛？

> Caused by: javassist.NotFoundException: android.graphics.fonts.Font

然后你查一下这个类：

https://developer.android.com/reference/android/graphics/fonts/Font

官方文档里写着： 

> Added in API level 29

所以你应该换一个29的compileSdk就能找到这个类了。

**Comment by xiaonima666** [comment]
我刚试了下集成实现了qmui 的ui，完全ok了，太强了，我看了一天愣是没看到这个日志后边的描述🤣，感谢！！

**Comment by xiaonima666** [comment]
https://github.com/xiaonima666/TestShadow
大佬 我想问下，点解plugin1等子插件单纯继承了AppCompatActivity或者其他的QMuiActivity时，由plugin插件点击跳转到plugin1，都会重新创建新一个process，connected中无响应卡死，无报错信息。

这是完整保存日志 https://github.com/xiaonima666/TestShadow/blob/master/errorMessage.md

**Comment by xiaonima666** [comment]
https://github.com/xiaonima666/TestShadow
大佬我想问下，点解plugin1等插件单纯继承了AppCompatActivity或者其他的QMuiActivity时，由plugin插件点击跳转到plugin1，都会重新创建新一个process，connected中无响应卡死，无报错信息

这是完整的保存日志https://github.com/xiaonima666/TestShadow/blob/master/errorMessage.md

**Comment by shifujun** [comment]
没法一眼看出来是什么原因。你如果坚持不按开源项目的协作方式解决问题，我也没法帮你更多了。开源项目是要在一个开源的共同的项目上协作的。你拿一个你的工程来问问题，其实是一种消费者找售后服务的心态了。我们暂时没有提供接入服务的能力，只有精力做一些技术交流。

**Comment by xiaonima666** [comment]
🤣问题是我用maven 目录下的plugin project 使用也是一个情况，有点尴尬

**Comment by shifujun** [comment]
那可以把改动push上来看看。不过maven那个sample主要是用于演示maven接入方法的。如果可以在source sample里复现问题就比较好debug里。因为它对sdk是源码依赖的，可以直接调试。
