### ISSUE TITLE
javassist.CannotCompileException: generateListView (Landroid/content/Context;I)Lorg/apache/weex/ui/view/refresh/wrapper/BounceRecyclerView; in org.apache.weex.ui.component.list.WXListComponent: failed to resolve types

### ISSUE THREAD

**Issue by lm87gb** [Tencent/Shadow#365]
插件里集成Weex  有什么办法让插件脚本不处理这个类吗

**Comment by shifujun** [comment]
自己修改Transform的input，跳过不想处理的类是可以的。但是跳过不处理，可能Shadow也不能正常工作。这还要看确实的类型用在什么地方了。

而且这里存在引用不到的类型，本身也是项目自己的问题。这样的工程应该也不能通过Proguard检查的。

**Comment by lm87gb** [comment]
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Component {
  boolean lazyload() default true;
}
-----------------
怀疑是arr包里自定义注解导致的  ，有解决类似问题的方法吗

**Comment by shifujun** [comment]
这个不用“怀疑”。编译的时候看一下具体报错找不到的类就行了。

**Comment by xuyunyu** [comment]
> 自己修改Transform的input，跳过不想处理的类是可以的。但是跳过不处理，可能Shadow也不能正常工作。这还要看确实的类型用在什么地方了。
> 
> 而且这里存在引用不到的类型，本身也是项目自己的问题。这样的工程应该也不能通过Proguard检查的。



> Task :sample-app:transformClassesWithShadowTransformForDebug FAILED
����com.pptv.xplayer.player.XPlayerImpʱ����:javassist.CannotCompileException: buildMediaSource (Landroid/net/Uri;Ljava/lang/String;Z)Lcom/google/android/exoplayer2/source/MediaSource; in com.pptv.xplayer.player.XPlayerImp: failed to resolve types

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-app:transformClassesWithShadowTransformForDebug'.
> javassist.CannotCompileException: buildMediaSource (Landroid/net/Uri;Ljava/lang/String;Z)Lcom/google/android/exoplayer2/source/MediaSource; in com.pptv.xplayer.player.XPlayerImp: failed to resolve types

大佬，请教一下，com/google/android/exoplayer2/source/MediaSource都能找到引用到，但是还是报这个错，不知道问题出在哪里

**Comment by shifujun** [comment]
@xuyunyu 你这跟这个Issue原本的问题确实是类似的。
就是你这里`com.pptv.xplayer.player.XPlayerImp`这个类引用的其他类型在编译时找不到，编译时加个`-S`选项可以看看具体的异常堆栈，可能能打印出找不到的类型。

这里现在能看到的只是说这个`buildMediaSource`方法带有这个签名信息，它编译不了，找不到引用的类型。不一定是这个签名上涉及的类型找不到，也可能是这个方法实现中用了什么类型找不到。

如果能确定是什么类型，找一下它的jar包加到compileOnly依赖中就行了。如果没有它原始的jar包，又能确定这个类实际在运行中用不到，也可以自己写一个这个类的空实现。

**Comment by xuyunyu** [comment]
> @xuyunyu 你这跟这个Issue原本的问题确实是类似的。
> 就是你这里`com.pptv.xplayer.player.XPlayerImp`这个类引用的其他类型在编译时找不到，编译时加个`-S`选项可以看看具体的异常堆栈，可能能打印出找不到的类型。
> 
> 这里现在能看到的只是说这个`buildMediaSource`方法带有这个签名信息，它编译不了，找不到引用的类型。不一定是这个签名上涉及的类型找不到，也可能是这个方法实现中用了什么类型找不到。
> 
> 如果能确定是什么类型，找一下它的jar包加到compileOnly依赖中就行了。如果没有它原始的jar包，又能确定这个类实际在运行中用不到，也可以自己写一个这个类的空实现。

找到问题了，的确是方法实现有些类找不到。 比心大佬。

**Comment by shifujun** [comment]
956b9a76 合入后应该不需要自己写空实现了。可以再试试。
