### ISSUE TITLE
source-sample-host直接Run(debug/release)签名不成功，不存在签名文件

### ISSUE THREAD

**Issue by tjt852** [Tencent/Shadow#367]
gradle build命令行打的包存在签名文件，但是直接run就是不行，签名不成功
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/5794936/84731325-17c17e00-afcb-11ea-88aa-21542c75cea7.png">

<img width="860" alt="image" src="https://user-images.githubusercontent.com/5794936/84731356-36c01000-afcb-11ea-9074-3b153acfab61.png">
不存在签名文件

**Comment by tjt852** [comment]
Android Studio版本3.6.3 ，build-gradle：3.6.3，sample里的代码

**Comment by shifujun** [comment]
以Issue反馈问题时应该附上完整的错误信息。因为你可能觉得写了“签名不成功，不存在签名文件”已经足够清晰了，但通常这不会是有用的信息。因为如果你能确定有用的信息，你大概率也能自己解决问题。

具体到这个问题，建议至少验证一下你的开发环境是否编译IDE example工程是成功的。

我们具体来看sample的签名配置：
```
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.create("release")
            signingConfig.initWith(buildTypes.debug.signingConfig)
        }
    }
```

这里debug的签名没有修改，应该采用默认自动生成的签名。Release的签名改成了debug的。所以这是一个比较通用的sample设置。如果签名失败，大概率是你的开发环境没有生成正确的debug签名，那么你的其他项目也会有同样的问题。
