### ISSUE TITLE
宿主如何访问插件中的具体类

### ISSUE THREAD

**Issue by xuyunyu** [Tencent/Shadow#368]
宿主和插件都依赖了一个公共接口库。
宿主将这个库打包进去，插件只是compileOnly。
插件的类A实现了接口库的部分接口，类A被打包进插件中。

在获得了类A的类名路径的情况下（网络下发），宿主如何加载这个实现了接口的类A，一般情况是loader.loadClass即可。不知Shadow这边怎么处理。

感谢指教。

**Comment by xuyunyu** [comment]
在其他issue找到了相关的，正在摸索找找插件的dexLoader在哪里

**Comment by shifujun** [comment]
建议采用依赖反转设计。让插件依赖宿主的类，将实现注入给宿主。可以参考：
projects/sample/source/sample-host-lib/src/main/java/com/tencent/shadow/sample/host/lib/HostUiLayerProvider.java

**Comment by shifujun** [comment]
而不是去直接拿插件的ClassLoader。那样太粗暴了。

**Comment by xuyunyu** [comment]
> 
> 
> 建议采用依赖反转设计。让插件依赖宿主的类，将实现注入给宿主。可以参考：
> projects/sample/source/sample-host-lib/src/main/java/com/tencent/shadow/sample/host/lib/HostUiLayerProvider.java

sample里，plugin调用HostUiLayerProvider是新建了一个实例？，不是用的宿主进程的HostUiLayerProvider实例，不是共用一个。宿主可以拿到插件的实现注入吗？

**Comment by shifujun** [comment]
不是“实例” 的关系。是同一个类对象。

这个类宿主打包，插件不打包。然后这里设置了插件访问宿主类的白名单：
https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sample/source/sample-plugin/sample-plugin-app/build.gradle#L49

插件只是compileOnly编译了这个类，所以运行时访问到的就是宿主中的类实现。

然后通过静态域的访问注入插件的实现。

**Comment by xuyunyu** [comment]
在HostUiLayerProvider 加了两行打印
`/**
 * 这是一个将要打包到宿主中的类。原本的目的是宿主依赖插件，宿主
 */
public class HostUiLayerProvider {
    private static HostUiLayerProvider sInstance = null;

    public static void init(Context mHostApplicationContext) {
        if (null==sInstance){
            Log.d("xuyunyu","HostUiLayerProvider/init");
            sInstance = new HostUiLayerProvider(mHostApplicationContext);
        }else {
            Log.d("xuyunyu","HostUiLayerProvider/already init");
        }
    }`

宿主进程启动
2020-06-16 17:39:17.402 32052-32052/? D/xuyunyu: HostApplication/onCreate
2020-06-16 17:39:17.405 32052-32052/? D/xuyunyu: HostUiLayerProvider/init


插件进程启动
2020-06-16 17:39:25.072 32156-32156/com.tencent.shadow.sample.host:plugin D/xuyunyu: HostApplication/onCreate
2020-06-16 17:39:25.079 32156-32156/com.tencent.shadow.sample.host:plugin D/xuyunyu: HostUiLayerProvider/init
2020-06-16 17:39:25.910 32156-32156/com.tencent.shadow.sample.host:plugin D/xuyunyu: TestApplication/onCreate

似乎new 了两次。

**Comment by shifujun** [comment]
注意32052和32156是两个进程。宿主和插件必须在同一个进程操作同一个类才能做这种事。

**Comment by xuyunyu** [comment]
> 
> 
> 注意32052和32156是两个进程。宿主和插件必须在同一个进程操作同一个类才能做这种事。

是的，只能在宿主进程加载插件，才能这么操作。 主进程加载插件会影响插件的 so res 和asse t的调用吗？

**Comment by shifujun** [comment]
在插件进程宿主也能执行代码啊。插件进程也要先跑宿主的Application的。

**Comment by xuyunyu** [comment]
> 
> 
> 在插件进程宿主也能执行代码啊。插件进程也要先跑宿主的Application的。

了解。可是我是要在宿主进程，获取插件进程的Class实例，显示在宿主的activity界面上。 刚好和sample反过来，应该是涉及到了跨进程通信了吧。

**Comment by shifujun** [comment]
你说的场景似乎就不需要插件存在Activity等四大组件，那就不需要Shadow这种技术。

可以简单参考
https://github.com/Tencent/Shadow/issues/366#issuecomment-644685098

**Comment by xuyunyu** [comment]
> 
> 
> 你说的场景似乎就不需要插件存在Activity等四大组件，那就不需要Shadow这种技术。
> 
> 可以简单参考
> [#366 (comment)](https://github.com/Tencent/Shadow/issues/366#issuecomment-644685098)



感谢大佬，构造插件的Context，是通过这个类吗  ChangeApkContextWrapper 还是 ShadowContext
