### ISSUE TITLE
请问基于Shadow开发的App能上架Google Play吗？

### ISSUE THREAD

**Issue by behring** [Tencent/Shadow#369]
Google Play不是禁止动态能力的App上架吗？希望官方回复。听说手Q是走了Google Play的白名单才上架的。求解答～～

**Comment by shifujun** [comment]
这个问题在iOS和Android上其实是一样的。两边市场的限制讲的都是不能动态修改产品的功能表现。这是一种产品角度的限制，不是技术角度的限制。

但是这种产品角度的限制，会通过技术手段，比如检测你的app里是否包含一些动态更新代码的能力来辅助判断。

所以理论上来说，你如果只是用Shadow动态修复bug，应该是可以上架的。

从经验上来讲，我们的业务对Google Play市场的依赖几乎没有，所以我们也不太关心。手Q上架Google Play的版本应该是没有我们业务的版本。至于手Q是如何操作的，我这里不太了解，也不方便透露和评论。

**Comment by leejay001** [comment]
Google 官方支持动态Feature，https://developer.android.com/guide/app-bundle/play-feature-delivery

**Comment by leonnnwu** [comment]
好奇海外版Wechat是否用了Shadow？

**Comment by behring** [comment]
感谢解答。
