### ISSUE TITLE
支持AppCompatActivity吗？

### ISSUE THREAD

**Issue by chenyunecjtu** [Tencent/Shadow#37]
我看转换里有
`"android.app.Activity"
                        to "com.tencent.shadow.core.runtime.ShadowActivity"`
我直接替换为
`"android.support.v7.app.AppCompatActivity"
                        to "com.tencent.shadow.core.runtime.ShadowActivity"`

**Comment by shifujun** [comment]
`android.support.v7.app.AppCompatActivity`的父类也是`android.app.Activity`，所以Shadow是支持的。

Shadow不关心这些support的实现。你可以认为support包的实现就是你自己写的代码，AppCompatActivity只是你写的业务的一个BaseActivity。

**Comment by chenyunecjtu** [comment]
好 谢谢
