### ISSUE TITLE
插件的包名与宿主一致的疑问？

### ISSUE THREAD

**Issue by tjt852** [Tencent/Shadow#372]
插件分为manager,loader,runtime,plugin,除了plugin跟宿主包名一致，其余的可以跟宿主包名不一致吗？

**Comment by shifujun** [comment]
可以的。sample里应该就是不一样的包名。这些组件的包名在代码中没有访问，只当做一般的Java类动态加载的。

**Comment by tjt852** [comment]
确实是可以的，谢谢
