### ISSUE TITLE
当类继承AndroidViewModel，Release包会Crash

### ISSUE THREAD

**Issue by ClaymanTwinkle** [Tencent/Shadow#374]
Crash堆栈如下：
![image](https://user-images.githubusercontent.com/15152514/86102123-b5e63580-baed-11ea-8465-133bc76f3e02.png)

分析：
![image](https://user-images.githubusercontent.com/15152514/86102213-cc8c8c80-baed-11ea-9857-e6df41623a59.png)
Crash原因是：MCRoomViewModel中没有一个带ShadowApplication参数的构造器，而因为继承了AndroidViewModel，只有一个带Application参数的构造器，所以Crash了。

**Comment by BiaoWu** [comment]
插件中的Application最后都会被rename成ShadowApplication

你这个MCRoomViewModel不会是不在插件app内吧，我感觉是你这个类没走插件的transform

**Comment by ClaymanTwinkle** [comment]
> 插件中的Application最后都会被rename成ShadowApplication
> 
> 你这个MCRoomViewModel不会是不在插件app内吧，我感觉是你这个类没走插件的transform

在的

**Comment by ClaymanTwinkle** [comment]
附目前临时的解决方案：不继承AndroidViewModel，直接继承ViewModel解决，因为ViewModel的构造器是无参的。

**Comment by shifujun** [comment]
还是先提供一个复现问题的代码看看吧。

我猜的话，应该是漏抄了这段设置吧：
https://github.com/Tencent/Shadow/blob/ed2b5af521599428f317cbe10d39d541046921b1/projects/sample/maven/plugin-project/plugin-shadow-apk/build.gradle#L11-L15
