### ISSUE TITLE
一个最致命的问题：混淆

### ISSUE THREAD

**Issue by xuwakao** [Tencent/Shadow#375]
如果插件或者宿主有混淆，那么，对于存在class相互依赖（例如，插件依赖宿主类）的情况，shadow根本没有办法解决。
除非不混淆，
或者插件本身是高内聚零耦合（极低耦合，宿主需要keep住白名单的类）的业务。
或者把所有插件依赖的类都要打包到插件中，对于大型项目，插件dex就会很大。
如果是这样，shadow的业务场景就比较有限了。

**Comment by shifujun** [comment]
混淆如果是用Proguard的话，Proguard是支持指定混淆的mapping规则的。可以让插件和宿主使用相同的mapping规则去混淆。
但这是针对彻底去掉白名单限制，允许插件任意依赖宿主类的情况。

按照我们的设想，宿主和插件版本是多对多关系的，所以宿主和插件不会是同时编译的。插件1，2版本会工作在宿主1，2版本上，形成4种运行环境。这种条件下，只能通过约定固定不变的接口来依赖宿主，所以只需要keep这些接口就行了，也可以混淆接口使用相同的mapping。这应该就是你说的“高内聚零耦合”的情况，看你的意思，好像这种很难做到。其实这个不难的。

BTW，在交流初期使用“致命“、”根本“这样的形容词，可能不是很好的交流实践。😃

**Comment by xuwakao** [comment]
> 混淆如果是用Proguard的话，Proguard是支持指定混淆的mapping规则的。可以让插件和宿主使用相同的mapping规则去混淆。
> 但这是针对彻底去掉白名单限制，允许插件任意依赖宿主类的情况。
> 
> 按照我们的设想，宿主和插件版本是多对多关系的，所以宿主和插件不会是同时编译的。插件1，2版本会工作在宿主1，2版本上，形成4种运行环境。这种条件下，只能通过约定固定不变的接口来依赖宿主，所以只需要keep这些接口就行了，也可以混淆接口使用相同的mapping。这应该就是你说的“高内聚零耦合”的情况，看你的意思，好像这种很难做到。其实这个不难的。
> 
> BTW，在交流初期使用“致命“、”根本“这样的形容词，可能不是很好的交流实践。😃

谢谢回复。
我说的规则，指的不是proguard规则文件，而是指，最终proguard后的mapping文件，对于同一个类或者方法要保持一样。
如果不同的话，如果插件依赖宿主的类问题就很大了，例如旧插件调用版本A的一个方法A，但是在版本B中，因为proguard，A方法已经变成Z方法了，method not found。类也是同理的。
核心需求是，希望插件尽量依赖宿主的类，避免打包的插件过大，但实际上，大部分的类在宿主中都是存在的。

另外，shadow不支持support包，这个可能对于很多项目来说，限制也很大。

BTW，会注意言词。（用骇人的词汇增加吸引度，因为能够得到及时回复的项目不多了，唉！！！）

**Comment by shifujun** [comment]
我猜你还是没明白我说的Proguard有复用mapping文件的功能。`-applymapping`选项，说明在这里：
https://www.guardsquare.com/en/products/proguard/manual/usage#applymapping

你只要宿主先混淆，拿到宿主的mapping，然后宿主的下一个版本也应用这个mapping，插件也应用这个mapping就可以了。

但我还是要说这不是好的实践，只是可行的。

再就是Shadow支持support包的，而且也支持AndroidX的。我不知道你说不支持的原因是什么，可能会有些场景有bug，但是总体是没问题的。因为support包也只是一般的第三方代码而已，跟我们插件自己的代码没什么区别。

**Comment by xuwakao** [comment]
> 我猜你还是没明白我说的Proguard有复用mapping文件的功能。`-applymapping`选项，说明在这里：
> https://www.guardsquare.com/en/products/proguard/manual/usage#applymapping
> 
> 你只要宿主先混淆，拿到宿主的mapping，然后宿主的下一个版本也应用这个mapping，插件也应用这个mapping就可以了。
> 
> 但我还是要说这不是好的实践，只是可行的。
> 
> 再就是Shadow支持support包的，而且也支持AndroidX的。我不知道你说不支持的原因是什么，可能会有些场景有bug，但是总体是没问题的。因为support包也只是一般的第三方代码而已，跟我们插件自己的代码没什么区别。

`-applymapping` 确实没有问题，只是这个实践可靠性太低了，这意味着往后mapping文件都改不了，未来很可能会遇到各种不可预见问题啊。
这个问题，你们是怎么处理的呢？难道你们的这种依赖的场景很少吗？

support包的问题之前试过好像是不行，可能是我自己的bug吧。想了一下，确实和shadow关系不大，至少从原理上应该是没有问题的。迟点再尝试一下，看看是什么问题。

**Comment by xuwakao** [comment]
还有，以下场景会出错：
`    
Dialog mDialog;
    public void show(View view){
        mDialog = new AlertDialog.Builder(this).create();
        mDialog.setContentView(R.layout.layout_dialog);
        mDialog.show();
    }
`

**Comment by shifujun** [comment]
> `-applymapping` 确实没有问题，只是这个实践可靠性太低了，这意味着往后mapping文件都改不了，未来很可能会遇到各种不可预见问题啊。
> 这个问题，你们是怎么处理的呢？难道你们的这种依赖的场景很少吗？

我们也有很多这种依赖，当然插件不想打包宿主已有的能力了。就是前面说的这种方式：
>按照我们的设想，宿主和插件版本是多对多关系的，所以宿主和插件不会是同时编译的。插件1，2版本会工作在宿主1，2版本上，形成4种运行环境。这种条件下，只能通过约定固定不变的接口来依赖宿主，所以只需要keep这些接口就行了

**Comment by shifujun** [comment]
> 还有，以下场景会出错：
> 
> ` Dialog mDialog;`
> ` public void show(View view){`
> ` mDialog = new AlertDialog.Builder(this).create();`
> ` mDialog.setContentView(R.layout.layout_dialog);`
> ` mDialog.show();`
> ` }`

如果你只说“会出错”，这就不是交流问题。
这样的问题请参考https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue 提交一个复现问题的代码。

**Comment by xuwakao** [comment]
> > `-applymapping` 确实没有问题，只是这个实践可靠性太低了，这意味着往后mapping文件都改不了，未来很可能会遇到各种不可预见问题啊。
> > 这个问题，你们是怎么处理的呢？难道你们的这种依赖的场景很少吗？
> 
> 我们也有很多这种依赖，当然插件不想打包宿主已有的能力了。就是前面说的这种方式：
> 
> > 按照我们的设想，宿主和插件版本是多对多关系的，所以宿主和插件不会是同时编译的。插件1，2版本会工作在宿主1，2版本上，形成4种运行环境。这种条件下，只能通过约定固定不变的接口来依赖宿主，所以只需要keep这些接口就行了

好的，明白了，谢谢。
