### ISSUE TITLE
插件APP在子线程启动service，同时创建Handler，导致崩溃。

### ISSUE THREAD

**Issue by xuyunyu** [Tencent/Shadow#376]
场景是：
插件APP启动某个service A 的代码是在子线程中执行的。
service A 启动后有创建一个Handler。
正常APP不编译成Shadow 插件APP，运行没有问题。
编程插件之后运行，就报这个错误。

07-01 20:24:46.316 30503 31096 E AndroidRuntime: FATAL EXCEPTION: Thread-122
07-01 20:24:46.316 30503 31096 E AndroidRuntime: Process: com.konka.livelauncher, PID: 30503
07-01 20:24:46.316 30503 31096 E AndroidRuntime: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at android.os.Handler.<init>(Handler.java:203)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at android.os.Handler.<init>(Handler.java:117)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.pptv.ottplayer.service.PPService$a.<init>(PPService.java:58)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.pptv.ottplayer.service.PPService$a.<init>(PPService.java:58)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.pptv.ottplayer.service.PPService.<init>(PPService.java:228)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.tencent.shadow.core.runtime.ShadowAppComponentFactory.instantiateService(ShadowAppComponentFactory.java:30)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.tencent.shadow.core.loader.managers.PluginServiceManager.newServiceInstance(Unknown Source:66)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.tencent.shadow.core.loader.managers.PluginServiceManager.createServiceAndCallOnCreate(Unknown Source:0)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.tencent.shadow.core.loader.managers.PluginServiceManager.bindPluginService(Unknown Source:32)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.tencent.shadow.core.loader.managers.ComponentManager.bindService(Unknown Source:28)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.tencent.shadow.core.runtime.ShadowContext.bindService(ShadowContext.java:202)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.pptv.ottplayer.utils.P2PEngineUtil.a(P2PEngineUtil.java:819)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.pptv.ottplayer.utils.P2PEngineAgent.startP2PEngine(P2PEngineAgent.java:33)
07-01 20:24:46.316 30503 31096 E AndroidRuntime:        at com.pptv.ottplayer.service.DataServiceMgr$b.run(DataServiceMgr.java:188)
07-01 20:24:47.459 30503 31096 E MtaSDK.CaughtExp: MTA has caught the following uncaught exception:
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp: 
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at android.os.Handler.<init>(Handler.java:203)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at android.os.Handler.<init>(Handler.java:117)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.pptv.ottplayer.service.PPService$a.<init>(PPService.java:58)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.pptv.ottplayer.service.PPService$a.<init>(PPService.java:58)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.pptv.ottplayer.service.PPService.<init>(PPService.java:228)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at java.lang.Class.newInstance(Native Method)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.tencent.shadow.core.runtime.ShadowAppComponentFactory.instantiateService(ShadowAppComponentFactory.java:30)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.tencent.shadow.core.loader.managers.PluginServiceManager.newServiceInstance(Unknown Source:66)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.tencent.shadow.core.loader.managers.PluginServiceManager.createServiceAndCallOnCreate(Unknown Source:0)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.tencent.shadow.core.loader.managers.PluginServiceManager.bindPluginService(Unknown Source:32)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.tencent.shadow.core.loader.managers.ComponentManager.bindService(Unknown Source:28)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.tencent.shadow.core.runtime.ShadowContext.bindService(ShadowContext.java:202)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.pptv.ottplayer.utils.P2PEngineUtil.a(P2PEngineUtil.java:819)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.pptv.ottplayer.utils.P2PEngineAgent.startP2PEngine(P2PEngineAgent.java:33)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp:      at com.pptv.ottplayer.service.DataServiceMgr$b.run(DataServiceMgr.java:188)
07-01 20:24:47.460 30503 31096 E MtaSDK.CaughtExp: App uncaught exception end.
07-01 20:24:47.633  2114  2198 E InputDispatcher: channel '385983 com.konka.livelauncher/com.konka.livelauncher.TrueLauncher (server)' ~ Channel is unrecoverably broken and will be disposed!
07-01 20:24:47.633  1852  1852 E HiMW@Hwtvmw: serviceDied cookie = 0x3946717632

**Comment by shifujun** [comment]
你的描述非常不清晰。从异常来看，就是基本的Handler创建错误。如果你是主动在子线程中创建Handler的，那不是本来就会有这个异常吗？你至少要强调，一样的代码没有shadow时是工作正常的吧。

请参考https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue 提交复现问题的代码。

**Comment by shifujun** [comment]
一般正常app没问题，shadow有问题，肯定是bug了。有一个复现场景，应该比较好修复。

**Comment by shifujun** [comment]
我写了一个测试用例，没能复现问题。
https://github.com/Tencent/Shadow/compare/master...shifujun:fix376_service_create_handler

你可以在我这个用例基础上改一下复现问题。

修改`com.tencent.shadow.test.plugin.particular_cases.plugin_service_for_host.CreateHandlerTestService#CreateHandlerTestService`这个Service。

执行`com.tencent.shadow.test.cases.plugin_service.PluginServiceCreateHandlerTest`这个测试用例。

**Comment by xuyunyu** [comment]
> 我写了一个测试用例，没能复现问题。
> [master...shifujun:fix376_service_create_handler](https://github.com/Tencent/Shadow/compare/master...shifujun:fix376_service_create_handler)
> 
> 你可以在我这个用例基础上改一下复现问题。
> 
> 修改`com.tencent.shadow.test.plugin.particular_cases.plugin_service_for_host.CreateHandlerTestService#CreateHandlerTestService`这个Service。
> 
> 执行`com.tencent.shadow.test.cases.plugin_service.PluginServiceCreateHandlerTest`这个测试用例。

好的，大佬，我晚些提交一个场景代码

**Comment by xuyunyu** [comment]
> CreateHandlerTestService

大佬，启动 CreateHandlerTestService 的代码要运行在子线程

`                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                // Intent 启动 CreateHandlerTestService 的代码
                            }
                        }).start();`

**Comment by shifujun** [comment]
好吧，但这应该是错误的写法吧。也许只是系统没报错而已。Context接口应该不是线程安全的。

不过我还是会试试的，Shadow的目标是尽可能跟系统行为保持一致。
