### ISSUE TITLE
关于加固的问题

### ISSUE THREAD

**Issue by winziyuan** [Tencent/Shadow#378]
@shifujun 请教一下，我们的宿主和插件APK支持加固吗

**Comment by shifujun** [comment]
什么叫“加固”？

**Comment by winziyuan** [comment]
就是给APK加保护啊，比如360加固，你们家腾讯的乐固等

**Comment by winziyuan** [comment]
看到有其他人反馈说不支持加固，所以找官方求证一下。

**Comment by shifujun** [comment]
我大概搜了一下你说的两个产品，都没看到实现原理，所以没法完全从原理上确定是否兼容。

从Shadow的原理上考虑，Shadow编辑过的App实际上是可以手工写出来的。Shadow只是一种通过字节码修改的自动编程手段而已。所以如果你说的“加固”对目标应用没有太多限制，应该就可以支持。

从目的上来讲，Proguard应该也属于你说的“加固”，Proguard是完全支持的。

如果有具体的问题，可以参考https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue 提交一个可以复现问题的最小改动，我来看看。

**Comment by yizems** [comment]
@winziyuan 虽然我现在还没有看完shadow 的源码,部分关键点还未看透, 但是就我自己的感觉来说, 加固是存在一些问题的;

宿主加固应该是没什么问题的, 但是插件访问宿主类可能存在问题;

插件的话 加固应该会存在一些问题,  加固会修改classloader,部分关键方法会native隐藏,  所以 宿主 加载 加固后的dex, 加固后的dex 去加载真正的dex 这个过程中可能存在问题, 还有就是 加固一般都会有so文件, 这一块可能有问题也可能没有问题, 试试吧, 我也有加固的需求, 公司对于插件化的需求不高,,唉, 调研计划搁置了半年了..

**Comment by trevorwang** [comment]
@yizems   加固后有发现问题么？

**Comment by yizems** [comment]
@trevorwang 调研计划搁浅一年了=.= 本人暂时也没什么业务时间来研究,
