### ISSUE TITLE
不同UUID的插件加载情况

### ISSUE THREAD

**Issue by xuyunyu** [Tencent/Shadow#379]
请问，宿主只能加载相同UUID的插件吗？即使两个插件zip的业务完全不同，运行在不同进程。

**Comment by shifujun** [comment]
UUID主要用来标记一组Loader、Runtime、Plugin是可以一起工作的。一般这些东西就是同一次构建的产物。

我们肯定不想Loader和Plugin版本不匹配吧？那就需要这样一个字段管理它们。

这跟业务是否相同没关系。不相同的两个业务，也可以标记成一个UUID，在同一个进程里用同一个Loader和Runtime加载。

不同进程就不需要UUID一致了。不过你可能需要多个Manager实例去管理多个进程，这样才能用多个UUID。

**Comment by xuyunyu** [comment]
> UUID主要用来标记一组Loader、Runtime、Plugin是可以一起工作的。一般这些东西就是同一次构建的产物。
> 
> 我们肯定不想Loader和Plugin版本不匹配吧？那就需要这样一个字段管理它们。
> 
> 这跟业务是否相同没关系。不相同的两个业务，也可以标记成一个UUID，在同一个进程里用同一个Loader和Runtime加载。
> 
> 不同进程就不需要UUID一致了。不过你可能需要多个Manager实例去管理多个进程，这样才能用多个UUID。

感谢大佬。想知道UUID是怎么生成的？由什么决定的？

**Comment by shifujun** [comment]
先参考这个看看：
https://github.com/Tencent/Shadow/issues/265#issuecomment-593763414
