### ISSUE TITLE
请教个插件获取宿主SharePreference数据被固化的问题

### ISSUE THREAD

**Issue by xiaonima666** [Tencent/Shadow#381]
用sample-hos的示例，宿主在加载插件前，通过SharePreference保存了数据，此时再去打开插件，插件能通过getBaseContext获取到宿主的数据。但是此时回退到宿主界面，再更新一下保存的数据，再次点击加载插件，获取的数据依旧是第一次保存的，数据似是固化了，插件获取不到更新后的数据是啥原因

**Comment by shifujun** [comment]
你知道SharePreference只是个文件包装了一些读写操作而已，Shadow里只是处理了插件Context的默认SP的文件路径。如果你确定拿到的是宿主的SP，那么剩下的事情跟shadow就没什么关系了。

我估计还是比较简单的其他问题，仔细debug一下sp的接口调用，文件路径，应该能发现问题。

还需要帮助的话，你得把代码push上来让人能复现问题才好。

**Comment by xiaonima666** [comment]
https://github.com/xiaonima666/Shadow-1/commit/277957dcabbfaff46b67dab91bdedd4f4c9eb792
这是刚push的，没配代理经常push不上来

**Comment by shifujun** [comment]
我试了一下：
https://github.com/shifujun/Shadow/tree/issue381

你也试试，正常的app里，在两个进程里这样使用SP也有一样的问题。所以我认为这就是SP本身的问题。

**Comment by xiaonima666** [comment]
是的，只能在宿主更新配置信息后插件exitProcess下，或重启pps 了才能生效了，感谢支持

**Comment by wlonglee** [comment]
> 用sample-hos的示例，宿主在加载插件前，通过SharePreference保存了数据，此时再去打开插件，插件能通过getBaseContext获取到宿主的数据。但是此时回退到宿主界面，再更新一下保存的数据，再次点击加载插件，获取的数据依旧是第一次保存的，数据似是固化了，插件获取不到更新后的数据是啥原因

SP默认不是多进程的，getSharedPreferences(
Constant.PLUGIN_SP_NAME,Context.MODE_MULTI_PROCESS or Context.MODE_PRIVATE ) 这样就可以了
