### ISSUE TITLE
插件里面有FileProvider，如何在host里提前占位？

### ISSUE THREAD

**Issue by tjt852** [Tencent/Shadow#382]
```xml
<provider
            android:name="com.xx.TTFileProvider"
            android:authorities="${applicationId}.TTFileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/plugin_xx_provider" />
</provider>

```

比如插件里面有这样的配置，如何在host里面提前占位？可否提供下思路

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/ed2b5af521599428f317cbe10d39d541046921b1/projects/sample/source/sample-host/src/main/AndroidManifest.xml#L86-L91
https://github.com/Tencent/Shadow/blob/ed2b5af521599428f317cbe10d39d541046921b1/projects/sample/source/sample-plugin/sample-app-lib/src/main/AndroidManifest.xml#L81-L83

sample里的例子有试过吗？

**Comment by tjt852** [comment]
谢谢，我试试
