### ISSUE TITLE
请问插件 APP 如何在宿主中 debug 调试？

### ISSUE THREAD

**Issue by 790396054** [Tencent/Shadow#383]

**Comment by shifujun** [comment]
没有任何特别的，跟正常App一样。

**Comment by 790396054** [comment]
1.宿主运行的插件 APP 是已经打包成 zip，放到/data/data/xxx 目录下了吧，那怎么在让宿主运行插件时，调试插件的代码？
2.我目前遇到一个问题，就是插件 APP 可以正常运行，但是打包成插件后，第一次打开都正常运行，在打开插件时，由于插件做了自动登录，这时插件就报错崩溃了，详细 bug 在下面。请问这个怎么解决？
![截屏2020-07-29 11 04 01](https://user-images.githubusercontent.com/10391006/88751909-38185700-d18b-11ea-8a9a-32d4871cac33.png)


看日志是由于插件代码的 dialog 空指针了，但是这个正常运行是不为空的。该怎么找问题？

**Comment by shifujun** [comment]
调试插件并没有什么特殊的操作，你是遇到了什么困难呢？注意下插件的进程？正常attach debugger就好了。

你那个Crash问题确实很依赖Debug能力，一般这样的问题我们就在直接安装运行App和以插件方式运行App两种模式下Debug，对比每层调用栈上变量的情况找出问题。

因为你说直接安装和插件运行时有不一样的效果，所以还是很有可能是Shadow的bug的。但是看你的堆栈，并不是在sample中测试的，所以我没法帮你具体调试。如果自己搞不定，建议尝试在sample的基础上提交一个最小复现问题的改动，我才能帮你调试。

另外，看起来不是dialog为null，因为调用栈上已经有Dialog.show的调用了。可能就是Miui在这个ForceDarkHelper上做了一些hack操作出了问题。

**Comment by 790396054** [comment]
多谢认真回复，调试插件明白了。
另外还有一个问题，在 Shadow的demo 中，就是 source/sample-host 中，在
com.tencent.shadow.sample.plugin.app.lib.usecases.dialog.TestDialogActivity 中，测试以下代码会崩溃，试了 2 个手机都是这样，MIUI12 和 EMUI10.
以下是代码，

public void show(View view){
//        TestDialog dialog = new TestDialog(this);
//        dialog.setContentView(R.layout.layout_dialog);
//
//        dialog.show();

        new AlertDialog.Builder(this, 0)
                .setMessage("message")
                .setPositiveButton("buttonText", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        ToastUtil.showToast(TestDialogActivity.this, "xx");
                    }
                })
                .setCancelable(false)
                .show();
    }

另外将 AndroidManifest.xml中的主题改为 
<activity android:name="com.tencent.shadow.sample.plugin.app.lib.usecases.dialog.TestDialogActivity"
            android:theme="@style/Theme.AppCompat.Light"
            />

报错如下，
![截屏2020-07-29 14 33 22](https://user-images.githubusercontent.com/10391006/88770541-93107500-d1b0-11ea-9232-f58104cb6a07.png)

**Comment by 790396054** [comment]
> 调试插件并没有什么特殊的操作，你是遇到了什么困难呢？注意下插件的进程？正常attach debugger就好了。
> 
> 你那个Crash问题确实很依赖Debug能力，一般这样的问题我们就在直接安装运行App和以插件方式运行App两种模式下Debug，对比每层调用栈上变量的情况找出问题。
> 
> 因为你说直接安装和插件运行时有不一样的效果，所以还是很有可能是Shadow的bug的。但是看你的堆栈，并不是在sample中测试的，所以我没法帮你具体调试。如果自己搞不定，建议尝试在sample的基础上提交一个最小复现问题的改动，我才能帮你调试。
> 
> 另外，看起来不是dialog为null，因为调用栈上已经有Dialog.show的调用了。可能就是Miui在这个ForceDarkHelper上做了一些hack操作出了问题。

这个问题确认了，只有在 MIUI12 上才能出现，MIUI10，EMUI10 不能复现。
