### ISSUE TITLE
AlertDialog 在 sample-host 报错

### ISSUE THREAD

**Issue by 790396054** [Tencent/Shadow#384]
在 Shadow的demo 中，就是 source/sample-host 中，在
com.tencent.shadow.sample.plugin.app.lib.usecases.dialog.TestDialogActivity 中，测试以下代码会崩溃，
（Android 模拟器，10 版本测试）
以下是代码，

public void show(View view){
// TestDialog dialog = new TestDialog(this);
// dialog.setContentView(R.layout.layout_dialog);
//
// dialog.show();

    new AlertDialog.Builder(this, 0)
            .setMessage("message")
            .setPositiveButton("buttonText", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    ToastUtil.showToast(TestDialogActivity.this, "xx");
                }
            })
            .setCancelable(false)
            .show();
}
另外将 AndroidManifest.xml中的主题改为 android:theme="@style/Theme.AppCompat.Light"

![截屏2020-07-31 10 50 55](https://user-images.githubusercontent.com/10391006/88994785-b86dc200-d31b-11ea-898f-c8cc2e8e2f98.png)

**Comment by 790396054** [comment]
请问这个问题是修复了吗？

**Comment by shifujun** [comment]
修复了，你试试。

**Comment by 790396054** [comment]
已修复，十分感谢
