### ISSUE TITLE
关于调用系统库方法时需要指定Activity对象的问题

### ISSUE THREAD

**Issue by charles-yinyu** [Tencent/Shadow#385]
使用共享元素时，需要调用下述方法：
ActivityOptionsCompat makeSceneTransitionAnimation(@NonNull Activity activity,
            @NonNull View sharedElement, @NonNull String sharedElementName)

方法需要传入一个activity对象，由于class文件中的Activity已经被改为ShadowActivity，会报没有相应makeSceneTransitionAnimation方法的异常，请指教

**Comment by shifujun** [comment]
大概参考`com.tencent.shadow.core.runtime.ShadowPendingIntent#getActivity(android.content.Context, int, android.content.Intent, int, android.os.Bundle)`的实现，将插件中对makeSceneTransitionAnimation的调用转移到Runtime里的一个自定义方法中。在自定义方法中取到ShadowActivity对象，然后转换成它的的壳子对象，再调用原本系统的makeSceneTransitionAnimation方法。

如果有什么其他的问题，你就考虑ShadowActivity其实只是真正的Activity的代码片段。如果你能将正常的代码重构成一个几乎没有自己代码的Activity，然后它只持有一个叫做ShadowActivity的普通类型，能实现一样的逻辑。那么在Shadow里就可以通过字节码编辑自动做这个重构。

**Comment by charles-yinyu** [comment]
ActivityOptionsCompat是support包里的类，插件框架介入到support包的适配，会面临support包与androidx的选择，通用性是个问题，发布support与androidx两个版本的插件框架，又不方便维护，这个问题如何解决呢？
另外，项目中类似的情况会持续发现，有没有更通用的解决方案呢，比如引入注解，当然这个会破坏shadow的原则，即无代码侵入性，请指教。

**Comment by charles-yinyu** [comment]
ShadowPendingIntent能够在框架层面实现，是因为PendingIntent是系统类；对于support包中类的适配，是否可以考虑放在插件本身中实现，比如ActivityOptionsCompat_shadow实现在插件工程中，并通过名单配置到框架中，虽然对业务工程有侵入性，但对业务代码本身却没有侵入，compileOnly也可以灵活控制兼容类（如ActivityOptionsCompat_shadow）的部署与集成问题，算是一个折中，请参考。

**Comment by shifujun** [comment]
这里我们在提一个前提上需要达成一致，我是将代码分为这3部分：系统代码、插件框架代码、业务代码，主要区分在于代码存在于哪个apk中，哪个ClassLoader中，是否可以由业务任意修改。在这个分类中，support包或者是androidx包，其实都是业务代码，和业务自己写的界面之类的代码没有本质的区别。所以Shadow呢就不能在设计上针对support包或者androidx有什么特别的代码，就像Shadow不会对QQ或者对我们的什么业务app有什么特殊的代码一样。

这里我理解的诉求主要是希望将support包打包到宿主里，这样对于插件的代码来说，support包就好像是系统代码了，因为它们没有被Transform修改过。所以，在Shadow上开发一些针对这种情况的扩展模块应该也是合理的。
