### ISSUE TITLE
dexOptions 配置不生效

### ISSUE THREAD

**Issue by skyson** [Tencent/Shadow#387]
配置了分dex ，如设置最大方法数是30000 ，但是插件包编译没有生效，怀疑是跟Transform-api 使用有关
dexOptions {
        javaMaxHeapSize "1g"
        preDexLibraries = false
        additionalParameters "--multi-dex", '--minimal-main-dex', "--set-max-idx-number", "30000"
 }

**Comment by shifujun** [comment]
可以专门学习一下transform api的原理，应该很容易判断是否有关系。

另外可以参考一下：https://github.com/Tencent/Shadow/tree/master/projects/test/plugin/particular-cases/multidex

**Comment by skyson** [comment]
使用 multiDexEnabled 在dex 方法数超出的情况下是ok的，但是如果加上 -set-max-idx-number 参数就不生效了；

**Comment by skyson** [comment]
大致了解了下transform api 的内部流程；从引入了 transform api 后，发现gradle 高版本会走到 DexArchiveBuilderTransform 内部逻辑；相对低一点的版本则是使用 DexTransform ； 两种情况都没有直接使用到 dexOptions additionalParameters 中的关于multi dex 的参数；
`boolean optimizedDex = !dexAdditionalParameters.contains("--no-optimize");
                DxContext dxContext = new DxContext(outStream, errStream);
                DexArchiveBuilderConfig config =
                        new DexArchiveBuilderConfig(
                                dxContext,
                                optimizedDex,
                                inBufferSize,
                                minSdkVersion,
                                DexerTool.DX,
                                outBufferSize,
                                DexArchiveBuilderCacheHandler.isJumboModeEnabledForDx());

                dexArchiveBuilder = DexArchiveBuilder.createDxDexBuilder(config);`

一个初步的思路：
在使用 DexArchiveBuilderTransform 之前 将DexArchiveBuilderConfig 添加上相应的 dexAdditionalParameters 数值；
不知道这个方案是否可行

**Comment by shifujun** [comment]
建议再试验一下不引入shadow时你要的dex选项是否工作正常。以及引入一个其他的transform能否工作正常。
