### ISSUE TITLE
WhiteList 配置 7.0 系统上的使用

### ISSUE THREAD

**Issue by skyson** [Tencent/Shadow#388]
使用Shadow 白名单的情况下，发现在 7.0 系统上（MI Max）会不生效，会直接调用到插件内的接口；
如果白名单接口使用compileOnly 的情况下，会抛classnotfound 异常；

**Comment by skyson** [comment]
如果插件内包含了两个dex 的话，发现白名单又是正常可以使用的；
分析了下插件包，发现插件包字节码正常，以及将odex 后的文件反编译，然后再重新转dex，查看反编译后的字节码也是正常；
单个dex 断点调试也是正常；只有在单个dex下才会有问题；

不确定是不是系统的问题，没有其他信息。

**Comment by shifujun** [comment]
这个问题没有足够的信息可以帮你分析。你可以看一下pluginclassloader的白名单逻辑，再结合java的classloader的基本原理debug一下。
