### ISSUE TITLE
框架打插件apk的时候，插件中继承AppCompatActivity的activity没有被转换成shadowActivity

### ISSUE THREAD

**Issue by VirgCode** [Tencent/Shadow#389]
框架打插件apk的时候，插件中继承AppCompatActivity的activity没有被转换成shadowActivity，大佬能否兼容一下，还是由于特殊的原因

**Comment by shifujun** [comment]
你遇到什么问题了？你现在说的似乎是直接提出应该如何修复你的问题，而没有说你遇到了什么问题。

**Comment by VirgCode** [comment]
> 你遇到什么问题了？你现在说的似乎是直接提出应该如何修复你的问题，而没有说你遇到了什么问题。

感谢您及时回复，我已找到问题原因，项目是用kotlin写的，之前在activity的
init {
        requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
    }
代码块中有一个设置屏幕方向的方法，这时候会报一个空指针异常com.tencent.shadow.core.runtime.container.GeneratedHostActivityDelegator.setRequestedOrientation(int)' on a null object reference，后来排查主要是由于调用设置竖屏方法的时期有问题，不应该在init代码块里调用，不过还是非常感谢您的回复，三克油
