### ISSUE TITLE
求助：帮忙写个多插件的 sample。

### ISSUE THREAD

**Issue by 790396054** [Tencent/Shadow#390]
帮忙写个多插件的 sample。搞了好几天，都不行，只能加载一个插件

**Comment by 790396054** [comment]
多个 manager 或一个 manager都行
多个 zip 或一个 zip 打包 2 个插件都行
多个 loader、runtime 或 1 个loader、runtime都行

只要能运行多个插件就行

**Comment by VirgCode** [comment]
> 多个 manager 或一个 manager都行
> 多个 zip 或一个 zip 打包 2 个插件都行
> 多个 loader、runtime 或 1 个loader、runtime都行
> 
> 只要能运行多个插件就行

项目默认就是加载的2个插件

**Comment by android-sz-coder** [comment]
@790396054  多插件多进程 多插件单进程 框架都是支持的啊 如果有问题 我可以提供个demo给你  你可以联系我  一起学习

**Comment by listen2code** [comment]
https://github.com/listen2code/Shadow， 提供参考

**Comment by 790396054** [comment]
> @790396054 多插件多进程 多插件单进程 框架都是支持的啊 如果有问题 我可以提供个demo给你 你可以联系我 一起学习

大佬，求 demo

**Comment by 790396054** [comment]
> @790396054 多插件多进程 多插件单进程 框架都是支持的啊 如果有问题 我可以提供个demo给你 你可以联系我 一起学习

大佬，求 demo

**Comment by 790396054** [comment]
> [https://github.com/listen2code/Shadow，](https://github.com/listen2code/Shadow%EF%BC%8C) 提供参考

地址 404 了？

**Comment by Heart-Beats** [comment]
我这有个 一个 zip 打包 2 个插件的 demo，多个也是类似的，有需要你可以参考下：https://github.com/Heart-Beats/ShadowPlugin

**Comment by longrenzhut** [comment]
> [https://github.com/listen2code/Shadow，](https://github.com/listen2code/Shadow%EF%BC%8C) 提供参考

有点懵逼，加个微信求指导 15088765390
