### ISSUE TITLE
一个第三方依赖库(https://github.com/bingoogolapple/BGAPhotoPicker-Android)的崩溃问题。独立运行没有问题，作为插件崩溃了

### ISSUE THREAD

**Issue by 790396054** [Tencent/Shadow#391]
在 source/smple-plugin/sample-app-lib 下，build.gradle 增加以下依赖
 implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'cn.bingoogolapple:bga-photopicker:1.2.9@aar'
    implementation 'cn.bingoogolapple:bga-baseadapter:1.2.9@aar'

在com.tencent.shadow.sample.plugin.app.lib.usecases.dialog.TestDialogActivity 的布局文件 layout_dialog_activity中添加以下代码
<cn.bingoogolapple.photopicker.widget.BGASortableNinePhotoLayout
        android:id="@+id/add_photos"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="10dp"
        app:bga_snpl_deleteDrawable="@mipmap/bga_pp_ic_delete"
        app:bga_snpl_deleteDrawableOverlapQuarter="false"
        app:bga_snpl_editable="true"
        app:bga_snpl_itemCornerRadius="0dp"
        app:bga_snpl_itemSpanCount="3"
        app:bga_snpl_itemWhiteSpacing="4dp"
        app:bga_snpl_itemWidth="0dp"
        app:bga_snpl_maxItemCount="9"
        app:bga_snpl_otherWhiteSpacing="10dp"
        app:bga_snpl_plusDrawable="@mipmap/bga_pp_ic_plus"
        app:bga_snpl_plusEnable="true"
        app:bga_snpl_sortable="true" />

作为插件运行就崩溃了。作为独立 APP 运行是正常的。

![截屏2020-08-07 下午6 42 40](https://user-images.githubusercontent.com/10391006/89638073-c86a4080-d8dd-11ea-955c-229e6cd2d166.png)

**Comment by shifujun** [comment]
我看了一下这个库的源码，它依赖了两种私有API获取当前应用的Application对象。
```
static {
        Application app = null;
        try {
            app = (Application) Class.forName("android.app.AppGlobals").getMethod("getInitialApplication").invoke(null);
            if (app == null)
                throw new IllegalStateException("Static initialization of Applications must be on main thread.");
        } catch (final Exception e) {
            Log.e(BGABaseAdapterUtil.class.getSimpleName(), "Failed to get current application from AppGlobals." + e.getMessage());
            try {
                app = (Application) Class.forName("android.app.ActivityThread").getMethod("currentApplication").invoke(null);
            } catch (final Exception ex) {
                Log.e(BGABaseAdapterUtil.class.getSimpleName(), "Failed to get current application from ActivityThread." + e.getMessage());
            }
        } finally {
            sApp = app;
        }
    }
```
这种代码毫无兼容性可言。如果要用这种代码，建议也同样反射设置它的`sApp`域吧。

**Comment by 790396054** [comment]
大佬 666
