### ISSUE TITLE
关于多插件的问题

### ISSUE THREAD

**Issue by 790396054** [Tencent/Shadow#393]
实现多插件，思路如下（参考 https://github.com/Tencent/Shadow/issues/265 这个 issue）：
现有A、B两个插件，
A 插件集成runtime和loader打包出zip包； 命名为 A.zip
B 插件没有runtime和loader，只有插件 apk 和 config.json。命名为 B.zip

A.zip 和 B.zip config.json中的 UUID 是一样的。

A 和 B 插件公用一个 manager 和一个 PluginProcessPPS 进程。

参考的是maven的Sample来做，manager在enter时，根据不同参数，install各自的zip包；实际运行时：
1.如果加载了A，再去加载B，就会出错；
2.如果反复加载A，是正常的；
3.杀掉进程，加载B，可以正常；再加载A，仍旧会出错；
错误信息是启动的Activity（具体的业务Activity）没在manifest里注册。

请问这种多插件分别打的zip包，该如何加载？

**Comment by listen2code** [comment]
同问，单项目，多mudole的插件形式如何实现？这里的插件如果单zip，像maven的sample一样，copy一个apk；或者像楼主的A.zip，B.zip两个插件文件，又如何加载？

**Comment by listen2code** [comment]
https://github.com/listen2code/Shadow  提供参考，runtime和loader在common里，pluginA.zip和pluginB.zip只有config.json和业务apk，满足你的需求

**Comment by hpuhsp** [comment]
有一个想法：关于把之前旧项目打包成插件作为新宿主App程序的一部分，是否只能旧项目单独配置runtime与loader模块实现，宿主程序配置多个PPS指定不同进程，这样才能实现多插件多进程？
