### ISSUE TITLE
宿主中打开插件的activity后，如何获取插件activity的返回值？

### ISSUE THREAD

**Issue by pianyun** [Tencent/Shadow#396]
最近使用Shadow遇到一个问题，在宿主中打开插件的activity后，无法获取插件activity的返回值。请问Shadow在宿主和插件之间怎么交互传值呢？

**Comment by shifujun** [comment]
其实就是`com.tencent.shadow.dynamic.loader.PluginLoader`目前没有提供`startPluginActivityForResult`这样的接口。

从原理上来说是可以实现的，插件Activity有一个真的Activity壳子，把Result透传回来就行了。

如果不能自己开发，只利用现有功能。可以通过自定义接口传值，也可以通过插件的Service传值。`bindPluginService`接口就是宿主绑定插件Service用的。

**Comment by pianyun** [comment]
> 其实就是`com.tencent.shadow.dynamic.loader.PluginLoader`目前没有提供`startPluginActivityForResult`这样的接口。
> 
> 从原理上来说是可以实现的，插件Activity有一个真的Activity壳子，把Result透传回来就行了。
> 
> 如果不能自己开发，只利用现有功能。可以通过自定义接口传值，也可以通过插件的Service传值。`bindPluginService`接口就是宿主绑定插件Service用的。

@shifujun ，你好，看了下源码，pluginLoader的startActivity最终是在DynamicPluginLoader.kt这个类里直接用mContext.startActivity(intent)启动插件的，但这个mContext是宿主的application。不是调用插件的宿主Activity，这样宿主Activity的onActivityResult()就无法回调。有没有办法在DynamicPluginLoader.kt里拿到宿主的activity?

**Comment by shifujun** [comment]
你用`convertActivityIntent`方法得到启动插件壳子Activity的Intent，然后用你宿主Activity的context自己调用startActivityForResult就好了。插件Activity的setResult已经透传给ContainerActivity了，所以应该可以正常返回值。

建议你先简单粗暴的在sample里改一下，验证一下可行性。

**Comment by pianyun** [comment]
> 你用`convertActivityIntent`方法得到启动插件壳子Activity的Intent，然后用你宿主Activity的context自己调用startActivityForResult就好了。插件Activity的setResult已经透传给ContainerActivity了，所以应该可以正常返回值。
> 
> 建议你先简单粗暴的在sample里改一下，验证一下可行性。

这个方法试过了，会报错。提示在宿主包里找不到ProxyActivity。这个ProxyActivity是在插件的Runtime apk里定义的，在宿主包里找不到。

**Comment by shifujun** [comment]
那是convert失败了，没找到它配对的宿主壳子activity。正常convert回来的就是宿主里定义的activity，你先debug一下sample的运行情况。

**Comment by pianyun** [comment]
是宿主的壳子activity，但这个activity只是在宿主AndroidManifest里注册了，真正的类文件在plugin的runtime里。

我在sample的FastPluginManager.java里做了如下修改：
    public void startPluginActivity(Context context, InstalledPlugin installedPlugin, String partKey, Intent pluginIntent) throws RemoteException, TimeoutException, FailedException {
        Intent intent = convertActivityIntent(installedPlugin, partKey, pluginIntent);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        //mPluginLoader.startActivityInPluginProcess(intent);
        context.startActivity(intent);
    }

但跑起来会carsh。

    --------- beginning of crash
2020-08-26 21:05:06.373 12726-12726/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.shadow.sample.host, PID: 12726
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity" on path: DexPathList[[zip file "/data/app/com.tencent.shadow.sample.host-sws0XldEuFV2F0-hJXr5ug==/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.shadow.sample.host-sws0XldEuFV2F0-hJXr5ug==/lib/arm64, /system/lib64, /system/product/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3700)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by shifujun** [comment]
那你按改之前的方式启动activity也一样会找不到啊。所以就是runtime没加载吧，漏了这步？

**Comment by pianyun** [comment]
之前的方式mPluginLoader.startActivityInPluginProcess(intent);启动没有问题。

**Comment by shifujun** [comment]
噢，那就是你没注意插件和宿主在不同的进程吧。应该只在插件进程加载Loader和Runtime了。你直接用宿主Activity startActivity会启动在宿主进程。你在宿主的Manifest里把插件的壳子都改到宿主进程应该就可以了。

**Comment by pianyun** [comment]
嗯，确实如此，这里process的配置去掉就好了。非常感谢！我关单了。

<service android:name="com.tencent.shadow.sample.host.PluginProcessPPS" />
