### ISSUE TITLE
调用Instrumentation.newApplication(appClass, context)时，transformClassesWithShadowTransformForDebug'无法编译

### ISSUE THREAD

**Issue by yghysdr** [Tencent/Shadow#397]
项目中使用了一个三方库调用了Instrumentation.newApplication(appClass, context)，插件模式下无法编译。
复现方法：在sameple-app-lib添加类
```
package com.tencent.shadow.sample.plugin.app.lib;

import android.app.Application;
import android.app.Instrumentation;
import android.content.Context;

public class TestDB {

    public static void createApplication(Class<?> appClass, Context context) {
        try {
            Application app = Instrumentation.newApplication(appClass, context);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
报错如下
```
Class com.tencent.shadow.core.runtime.ShadowInstrumentation中缺少方法:
newApplication:(Ljava/lang/Class;Landroid/content/Context;)Lcom/tencent/shadow/core/runtime/ShadowApplication;被这些类调用了:
com.tencent.shadow.sample.plugin.app.lib.TestDB
```
该怎么解决呢，忽略这个检查吗

**Comment by shifujun** [comment]
需要的话自己在https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowInstrumentation.java
里实现就好了。

**Comment by yghysdr** [comment]
> 需要的话自己在https://github.com/Tencent/Shadow/blob/e2936bd1ffa86bf45b6c445c440e7be86b74cfec/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowInstrumentation.java
> 里实现就好了。

我添加了
```
 public static Application newApplication(Class<?> clazz, Context context)
            throws InstantiationException, IllegalAccessException,
            ClassNotFoundException {
        return Instrumentation.newApplication(clazz, context);
    }
```
还是无法编译，抛出同样的错误；根据错误信息应该是缺少如下的方法
``
 static public ShadowInstrumentation newApplication(Class<?> clazz, Context context)
            throws InstantiationException, IllegalAccessException,
            ClassNotFoundException {
        return Instrumentation.newApplication(clazz, context);
    }
```
但是这个方法更是直接无法编译，应该怎么实现呢，有类似的例子吗。

**Comment by shifujun** [comment]
全文搜索一下callActivityOnDestroy，在transform里还有一处地方复杂编辑字节码转调过来，也要抄一下。

**Comment by shifujun** [comment]
我说错了。不需要改transform，应该是其他问题。我晚一点写一下试试。

**Comment by shifujun** [comment]
这个newApplication方法和之前已有的callActivityOnDestroy方法主要区别就是它是静态方法。静态方法不能Override嘛。所以还是需要在Transform里面rename一下调用的方法。

我已经合入了。
