### ISSUE TITLE
子插件中的反射代理是否兼容？

### ISSUE THREAD

**Issue by janus-xiao** [Tencent/Shadow#399]
如果在子插件中做了很多系统api（如android.content.pm.PackageParser BroadcastReceiver）的反射代理操作，在shadow中能正常运行吗？需要从哪些地方做适配呢

**Comment by shifujun** [comment]
反射本身没什么问题。但是如果要对一些系统api进行反射，可能这个目的本身就是去hack系统了。而shadow修改了很多app代码中对系统api的调用，可能app代码经过shadow处理之后，根本就不调用原本的系统api了。所以在逻辑上可能跟反射操作的逻辑有冲突。

建议在shadow的sample里测试一下。然后仔细看一下shadow的Transform都做了哪些改动。
