### ISSUE TITLE
getApplicationInfo有两处实现，且实现不一致。

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#40]
`com.tencent.shadow.core.runtime.ShadowContext#getApplicationInfo`
`com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`
两处实现的逻辑不一致，且不应该实现两遍。

其中`com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`返回的ApplicationInfo没有设置sourceDir，导致了问题#38

其中`ShadowPackageManager`是插件中代码通过PackageManager试图`getApplicationInfo`，并且传入的`packageName`等于插件（也等于宿主）的。我们认为这种调用实际上是试图拿到插件自己的ApplicationInfo。因此转调过来了。

**Comment by ehunmayh** [comment]
> 
> 
> `com.tencent.shadow.core.runtime.ShadowContext#getApplicationInfo`
> `com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`
> 两处实现的逻辑不一致，且不应该实现两遍。
> 
> 其中`com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`返回的ApplicationInfo没有设置sourceDir，导致了问题#38
> 
> 其中`ShadowPackageManager`是插件中代码通过PackageManager试图`getApplicationInfo`，并且传入的`packageName`等于插件（也等于宿主）的。我们认为这种调用实际上是试图拿到插件自己的ApplicationInfo。因此转调过来了。

请问一下最后是如何解决的呢？  按照教，初始化的时候一直输出这个错问日志： ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths

**Comment by shifujun** [comment]
> > `com.tencent.shadow.core.runtime.ShadowContext#getApplicationInfo`
> > `com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`
> > 两处实现的逻辑不一致，且不应该实现两遍。
> > 其中`com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`返回的ApplicationInfo没有设置sourceDir，导致了问题#38
> > 其中`ShadowPackageManager`是插件中代码通过PackageManager试图`getApplicationInfo`，并且传入的`packageName`等于插件（也等于宿主）的。我们认为这种调用实际上是试图拿到插件自己的ApplicationInfo。因此转调过来了。
> 
> 请问一下最后是如何解决的呢？ 按照教，初始化的时候一直输出这个错问日志： ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths

InstantRun和这个Issue应该不相关。你可以先关掉InstantRun试试。有问题的话附上修改的sample另外提issue吧。

**Comment by ehunmayh** [comment]
> 
> 
> > > `com.tencent.shadow.core.runtime.ShadowContext#getApplicationInfo`
> > > `com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`
> > > 两处实现的逻辑不一致，且不应该实现两遍。
> > > 其中`com.tencent.shadow.core.runtime.ShadowPackageManager#getApplicationInfo`返回的ApplicationInfo没有设置sourceDir，导致了问题#38
> > > 其中`ShadowPackageManager`是插件中代码通过PackageManager试图`getApplicationInfo`，并且传入的`packageName`等于插件（也等于宿主）的。我们认为这种调用实际上是试图拿到插件自己的ApplicationInfo。因此转调过来了。
> > 
> > 
> > 请问一下最后是如何解决的呢？ 按照教，初始化的时候一直输出这个错问日志： ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths
> 
> InstantRun和这个Issue应该不相关。你可以先关掉InstantRun试试。有问题的话附上修改的sample另外提issue吧。

打断点看初始化的错误是在这里输出的catch (Exception e)中输出了 ARouter::: InstantRun support error, com.android.tools.fd.runtime.Paths：
    /**
     * Get instant run dex path, used to catch the branch usingApkSplits=false.
     */
    private static List<String> tryLoadInstantRunDexFile(ApplicationInfo applicationInfo) {
        List<String> instantRunSourcePaths = new ArrayList<>();

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && null != applicationInfo.splitSourceDirs) {
            // add the split apk, normally for InstantRun, and newest version.
            instantRunSourcePaths.addAll(Arrays.asList(applicationInfo.splitSourceDirs));
            Log.d(Consts.TAG, "Found InstantRun support");
        } else {
            try {
                // This man is reflection from Google instant run sdk, he will tell me where the dex files go.
                Class pathsByInstantRun = Class.forName("com.android.tools.fd.runtime.Paths");
                Method getDexFileDirectory = pathsByInstantRun.getMethod("getDexFileDirectory", String.class);
                String instantRunDexPath = (String) getDexFileDirectory.invoke(null, applicationInfo.packageName);

                File instantRunFilePath = new File(instantRunDexPath);
                if (instantRunFilePath.exists() && instantRunFilePath.isDirectory()) {
                    File[] dexFile = instantRunFilePath.listFiles();
                    for (File file : dexFile) {
                        if (null != file && file.exists() && file.isFile() && file.getName().endsWith(".dex")) {
                            instantRunSourcePaths.add(file.getAbsolutePath());
                        }
                    }
                    Log.d(Consts.TAG, "Found InstantRun support");
                }

            } catch (Exception e) {
                Log.e(Consts.TAG, "InstantRun support error, " + e.getMessage());
            }
        }

        return instantRunSourcePaths;
    }
