### ISSUE TITLE
有没有方法可以在宿主中用反射的方法new一个插件的类（宿主和插件在同一进程）？

### ISSUE THREAD

**Issue by pianyun** [Tencent/Shadow#400]
尝试了一下打开插件的activity后，再在宿主中用反射的方法new一个插件的类，但报错说找不到类。

**Comment by shifujun** [comment]
要使用反射技术，需要先确定ClassLoader。所以问题是你没找到插件的ClassLoader。

Shadow没有针对反射需求的设计，所以没有便捷的接口可以直接让宿主取到插件的ClassLoader。

但是宿主依然可以利用依赖注入设计，类似sample中的`HostUiLayerProvider`，让插件向宿主传递自己的ClassLoader给宿主。

**Comment by pianyun** [comment]
我尝试用依赖注入的方式，在插件中添加了宿主的依赖。但是加载起来后会报找不到宿主里的依赖类。看log，插件启动时还是在插件包里找宿主的类。
java.lang.ClassNotFoundException: Didn't find class "com.example.shadow.host.ShadowHost" on path: DexPathList[[zip file "/data/user/0/com.example.shadowdemo2/files/ShadowPluginManager/UnpackedPlugin/default-plugin-manager/171895002077d17b819fa8dab14a2690/plugin-app1.9.zip/plugin-app1-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.example.shadowdemo2/files/ShadowPluginManager/UnpackedPlugin/default-plugin-manager/lib/plugin-app1_lib, /system/lib64, /system/product/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]

**Comment by pianyun** [comment]
`package com.tencent.shadow.dynamic.impl;

/**
 * 此类包名及类名固定
 * classLoader的白名单
 * PluginLoader可以加载宿主中位于白名单内的类
 */
public interface WhiteList {
    String[] sWhiteList = new String[]
            {
                    "com.huawei.shadow.host",
            };
}`

**Comment by pianyun** [comment]
已经在这里和插件包的json里添加白名单，但还是报找不到类。

``package com.tencent.shadow.dynamic.impl;

/**

此类包名及类名固定
classLoader的白名单
PluginLoader可以加载宿主中位于白名单内的类
*/
public interface WhiteList {
String[] sWhiteList = new String[]
{
"com.example.shadow.host",
};
}`

**Comment by shifujun** [comment]
在sample里全局搜索HostUiLayerProvider的包名，看看都用在了哪里。

**Comment by pianyun** [comment]
看了下sample，有两个地方使用HostUiLayerProvider，一是在宿主的Appliction里，二是在插件的activity里。
而我的使用场景是需要在插件的application里，注册供宿主调用的方法。宿主里的依赖类必须在activity里使用？
public class PluginApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        //ShadowHost.registerPluginMethod("plugin-app1", "pluginMethod", null);
        ShadowHost.registerPluginMethod("plugin-app1", "pluginMethod", new IShadowCallback() {
            @Override
            public Object onCall(Object o, IShadowCallback iShadowCallback) {
                Log.d("Plugin1App", "param from host = " + o);
                if (null != iShadowCallback) {
                    iShadowCallback.onResult("plugin callback value");
                }
                return "plugin value";
            }
            @Override
            public void onResult(Object o) {
            }
        });
    }
}

**Comment by shifujun** [comment]
shadow的白名单定义都是指定的包名，所以你应该搜索包名。
![image](https://user-images.githubusercontent.com/3535204/91931615-88e51780-ed16-11ea-8782-b9a1fae1f5dd.png)

**Comment by pianyun** [comment]
解决了，是插件包里的白名单有问题。

谢谢！

**Comment by AndroidMuggle** [comment]
> 解决了，是插件包里的白名单有问题。
> 
> 谢谢！

请问是怎么解决的呢，我这边有个类似的需求，需要从宿主通过反射的方式new一个插件中的类，没太明白作者提到的HostUiLayerProvider做法（下图是我的类，在插件的Application中初始化）
object PluginClassloaderProvider {

    private var pluginCtx: Context? = null

    fun init(ctx: Context) {
        pluginCtx = ctx
    }

    fun getClassLoader(): ClassLoader? {
        return pluginCtx?.classLoader
    }
}
但是我在宿主中使用的时候，会报错：
 Exception: java.lang.NoClassDefFoundError: Failed resolution of: 包名/PluginClassloaderProvider;
