### ISSUE TITLE
请问框架初始化，导致首次启动时延较长的问题该如何解决

### ISSUE THREAD

**Issue by leonard-hw** [Tencent/Shadow#401]
框架初始化，需要在App.onCreate中进行，首次启动因为要做框架自身apk的动态加载，odex优化比较耗时，导致首次启动白屏，另外，因为修改了Classloader的双亲委托链，导致启动时findClass过程变慢。这个目前有解决方案吗？

**Comment by shifujun** [comment]
动态性是一定有成本的。要不要这个动态性，取决于它能带来的价值。对于我们的业务来说，对宿主增量非常敏感，方法数增量也非常敏感，因此我们需要这个动态性。另一方面，长年使用这种技术，也深知各种系统的兼容性随时可能出问题，所以能尽快修复问题也是强需求。

shadow的实现是考虑了非动态的使用方式的，也就是core层。core层是能单独工作的，只是由于我们业务没有这个需求，api的包装有些简陋。不使用dynamic层，应该就能避免你说的问题了。

另一方面，我确实也不确定现有的dynamic层实现的是否是最优的。这一点主要是因为我们的业务在这方面诉求不强了，所以没有投入更多精力研究。这方面欢迎帮忙改进。

**Comment by leonard-hw** [comment]
感谢及时的答复！还有两个问题：
1、如果不使用dynamic层，是不是意味着框架的初始化就不必局限在App.onCreate这个时机了？是否就可以实现延时初始化了呢？
2、当前业界使用shadow的app都有哪些？我看到手Q是用了的

**Comment by shifujun** [comment]
1. 不管是否使用Dynamic层，插件框架也无非一段普通的代码而已，在使用之前初始化就可以了。不是必须要在App onCreate时初始化。 

2. 哪些App用了，这个不是技术问题，我就不回复了。一个SDK的质量也不能光看它都用在了哪，既然是开源项目，更应该从代码来判断。

3. 我们的业务确实插件跑在子进程的。这主要是怕搞插件更新太随意挂掉主进程。如果放在主进程跑，确实像你说的，也要做runtime的加载。不过你也可以选择将runtime直接打包在宿主内，这样只是不能动态更新了。目前runtime中的代码已经非常固定了，很多Shadow的类已经移到loader里了，所以打包在宿主中是一个可行的选择。

**Comment by leonard-hw** [comment]
感谢解惑~

**Comment by shifujun** [comment]
那这个就先关了。如果有另外的问题单独再提Issue就好。
