### ISSUE TITLE
请问下shadow 可以以Lib 作为宿主，编译成一个aar 提供给第三方在上层做开发

### ISSUE THREAD

**Issue by ly2251** [Tencent/Shadow#406]
我初步想法是以lib 作为宿主，然后lib初始化的时候获取到当前集成应用的Application 来进行plugin 的加载和实现，请问下这样的用法会不会出现问题？

**Comment by shifujun** [comment]
原理上是可行的。遇到问题也是正常的，因为Shadow现有的代码在设计过程中不是以这个目标进行的。

从原理上来说Shadow其实只是一个通过字节码编辑自动重构代码的工具，自动改写app的代码，使它们不再直接依赖Android系统的类（Activity等系统有安装限制的类）。
