### ISSUE TITLE
shadow支持java环境吗

### ISSUE THREAD

**Issue by YiScond** [Tencent/Shadow#408]
业务场景需要:宿主或者插件不一定会有kotlin环境,这种情况下支持吗,需要怎么做

**Comment by shifujun** [comment]
支持的。这个跟Shadow没关系，是Kotlin的设计。Kotlin实现的模块编译之后对于JVM来说跟Java代码没有区别。Kotlin的Runtime会被打包到编译的模块中，所以会占一些空间。但是Kotlin考虑到了这个问题，它的Runtime对Proguard是非常友好的，所以开启Proguard之后，kotlin的runtime占用空间非常小。

所以宿主或者插件都不需要关心Shadow使用了Kotlin。

**Comment by YiScond** [comment]
还有个问题不是很明白
假设插件里面集成了一个sdk,这个sdk会启动内部的一个Activity，这种场景支持吗；也就是支不支持 插件内的Activity启动

**Comment by YiScond** [comment]
看了代码 是支持的 不过是有条件的
启动的Activity或者Context是需要经过transfrom后的
