### ISSUE TITLE
请教问题：org.apache.commons.logging是非常特殊的的包,由系统放到App的PathClassLoader中.

### ISSUE THREAD

**Issue by o0starshine0o** [Tencent/Shadow#409]
在类：PluginClassLoader中，默认白名单出现了：
```kotlin
val defaultWhiteList = arrayOf(
                               "org.apache.commons.logging"//org.apache.commons.logging是非常特殊的的包,由系统放到App的PathClassLoader中.
        )
```
这样一段代码

------

在实际使用时，我们插件用到了鹅厂的X5WebView，发现PluginClassLoader无法加载位于插件xxx.zip/xxx-plugin.apk文件中的X5WebView类，真正加载X5WebView类的是PluginClassLoader的parent：PathClassLoader（用的是/data/app/包名-1/base.apk）

------

所以只能通过设置白名单，让X5WebView的加载走到`super.loadClass`中才能正常运行。
而且在接下来的实践中还发现了`androidx.localbroadcastmanager.content`的`LocalBroadcastManager`也是同样的问题；
不清楚是否还有其他的类也会遇到这样的问题。

------

无意中看到了defaultWhiteList的注释，发现注释和我遇到的情况很相似，想对这一块进一步了解，请问能否提供更进一步解释下这里为什么`logging`是非常特殊的包，另外有什么参考资料可以学习下？

@shifujun

**Comment by shifujun** [comment]
我觉得应该分成两个问题来看，我先说这个logging这个包。

从提交记录来看是 5cc30047 这个特别早的提交就写上了的。可惜当时没有写更多的注释，但我基本还能记清楚。

一开始设计的时候，最简单的想法肯定是想我的需求是插件和宿主相互隔离，像两个独立的应用一样，那么我的PluginClassLoader应该跟PathClassLoader是兄弟关系，他们的parent应该都是BootClassLoader。但是这么跑起来就Crash，就是`org.apache.commons.logging`这个包的类找不到。因为我测试的插件也能当作独立应用安装，独立安装的时候它不会Crash。所以就很容易判断找不到的类根本不在应用自己的apk里。进一步Debug一下Class的ClassLoader是谁，就能发现找不到的类存在于PathClassLoader中。因为正常安装的应用，我又没篡改什么ClassLoader，那我只能推断这是系统注入进来的。

所以这个问题基本上就是促使我决定将PathClassLoader作为PluginClassLoader的parent的根本原因。然后因为我又想让两个ClassLoader隔离，所以就有了白名单设计。

至于为什么系统有这种行为，当时这不是重点问题，所以好像没深究系统是如何注入的。但基本能推断出来，这跟6.0系统开始deprecate Apache httpclient有关。我当时猜是因为系统代码演化时想把Apache这些东西从BootClassLoader中去掉，但是为了保持应用的兼容性，就把它们又注入到PathClassLoader里了。

所以我承认，这部分确实没研究透彻。

然后说你另外的问题，基于前面的理由，我肯定认为其他的类，比如X5内核的类的问题，跟Apache的问题是不一样的原因。因为这些类都是业务自己的，android系统没有参与过。

问题的主要原因应该是因为这个特性：

一个Class加载它用到的其他Class时，总是从加载自己从ClassLoader尝试加载。而ClassLoader一般有缓存，曾经加载过的Class，不会再去反复执行双亲委派的逻辑了。

所以搞不清这个特性时，经常出现类似的问题。而且容易出现expect A but found A这样的类型异常。因为传来的A对象是其他类加载的A类型，自己接收时对象时却试图用自己加载的A类型接收。自己和其他的类如果不是同一个ClassLoader加载的，那么它们加载到的A就也有可能是不同的。你说的X5WebView就很有可能遇到了这样的问题。

一般解决这种问题，只能避免类冲突。既然宿主打包了X5WebView，插件就不要再打包了，改为compileOnly依赖就好了。如果插件和宿主使用的版本确实不兼容，就只能另外想办法为X5单独构造一个ClassLoader，parent跳过PathClassLoader了。不过如果扩展考虑到Native So库，就完全没办法避免符号冲突了。所以最好还是跟宿主保持兼容，不能真的完全不考虑宿主的环境。

**Comment by o0starshine0o** [comment]
对于`org.apache.commons.logging`可以理解，但是对于`X5WebView`又仔细看了一遍深入理解java虚拟机，还是不能理解。对于`androidx.localbroadcastmanager.content`感觉应该也是做了和`logging`相似的处理。

我的理解：
一个xxxActivity（ShadowActivity）加载它用到的其他Class（X5WebView）时，
总是从加载自己的ClassLoader（PluginClassLoader）尝试加载。
而ClassLoader一般有缓存（通过findLoadedClass实现），
曾经加载过的Class，不会再去反复执行双亲委派的逻辑了。

但是，我们的PluginClassLoader并没有完全严格按照双亲委派来实现，只有白名单和一些特殊的类才按照双亲委派的模式来加载，其他普通的类只会在插件apk中查找。

```kotlin
var clazz: Class<*>? = findLoadedClass(className)
// 执行完成后clazz=null，表示这个ClassLoader并没有曾经加载过X5WebView
clazz = findClass(className)
// 执行完成后clazz=null，这里是最困惑的地方，按理说应该是在dex中去寻找class，但是dex中其他包名下的类都能通过这行找到，唯独X5WebView找不到
clazz = specialClassLoader.loadClass(className)
// 这里是系统的类，specialClassLoader传的是hostClassLoader.parent，宿主的parent
```
代码到`clazz = findClass(className)`时就蒙了，不是应该到dex中去找的吗，dex中明明就有X5WebView的class，dex中其他包下的类都可以找到；这里应该也不涉及到双亲委派模型。

对于dex中明明存在class，而ClassLoader却找不到，这一点很不理解，是不是有其他我不知道的原因呢？

谢谢

**Comment by shifujun** [comment]
我先不细想这个问题。这里存在一种可能性需要先排除一下。你遇到的X5WebView找不到的异常，有没有特别注意它的root cause Exception。或者有可能复现的机型没有很好的抛出根异常。有可能是X5WebView依赖的其他类找不到，进而导致X5WebView也加载失败。这种情况还是很常见的。

另外你能否构造一个复现场景push上来？

**Comment by o0starshine0o** [comment]
我在demo中直接添加了X5WebView：https://github.com/o0starshine0o/Shadow/tree/x5webview
这边看到加载类是正常的，通过PluginClassLoader能加载到X5WebView；
log上也显示是在findClass函数中找到X5WebView的，这符合预期；

公司的项目就不能提到这上面来了，issues先放着吧，我再找找问题，有突破了这边再写原因。
