### ISSUE TITLE
Flutter混合项目接入Shadow疑问

### ISSUE THREAD

**Issue by liujunhongz** [Tencent/Shadow#41]
请问Flutter项目接入Shadow怎么做呢？

**Comment by shifujun** [comment]
Flutter的Android端就是一个Activity壳子啊，这还用Shadow这种框架吗？它的主要代码不都在So里面么？So的动态加载没有门槛呀。

**Comment by liujunhongz** [comment]
我现在用的是Flutter混合开发的   依赖的库有大量安卓的代码

**Comment by liujunhongz** [comment]
而且flutter本身开发就会依赖安卓的代码

**Comment by shifujun** [comment]
我理解的Flutter在Android部分的代码也没有特别特殊的。我想Shadow应该是直接就支持的。Flutter的代码基本上都最后编译进so了。那么只需要在Android工程上应用Shadow就可以了。

我建议你fork一下Shadow，然后把Shadow的sample中的plugin app改造成Flutter项目。如果运行不正常，我可以一起看看。

**Comment by liujunhongz** [comment]
好 谢谢  我先试试

**Comment by liujunhongz** [comment]
请问我运行normal app生成的apk里面为什么没有包含flutter生成在assets中的文件呢？我正常创建创建flutter混合项目是有的

**Comment by shifujun** [comment]
你可以仔细review一下sample-normal-app的构建配置中有没有跟Shadow相关的东西。我原本的设计是它跟Shadow完全没有关系。就是一个普通的App。这个模块的作用就是证明这一点。

**Comment by liujunhongz** [comment]
嗯  发现是flutter的脚本需要设置`mainModuleName`的名字，默认是module名称为`app`，见[flutter.gradle](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L535)

所以在Shadow里面想要运行带flutter的工程，例如运行sample-normal-app，按照[官方文档](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#make-the-host-app-depend-on-the-flutter-module)插入`settings.gradle`如下代码：

```groovy
setBinding(new Binding([gradle: this, mainModuleName: 'sample-normal-app']))
evaluate(new File(settingsDir, 'sample_flutter/.android/include_flutter.groovy'))
```

指定`mainModuleName`为`sample-normal-app`就可以正常运行了

也可以把module的名字`sample-normal-app`改为`app`
