### ISSUE TITLE
FileProvider

### ISSUE THREAD

**Issue by crazymongo** [Tencent/Shadow#416]
在插件内部调用FileProvider.getUriForFile方法获取Uri时，最后的结果包含com.tencent.shadow.contentprovider.authority.dynamic字符串，但是我在FileProvider内部调试时却没有看到这个字符串，不知道这个字符串是何时加入的，请大佬帮忙解惑一下，非常感谢

**Comment by shifujun** [comment]
建议参考
https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue
提交可以复现问题的代码。
