### ISSUE TITLE
发布到nexus仓库

### ISSUE THREAD

**Issue by wwq006** [Tencent/Shadow#417]
麻烦问下，在maven.gradle 文件里如何配置 nexus 账户密码，才能发布到本机的nexus仓库

**Comment by shifujun** [comment]
像这样：
https://github.com/Tencent/Shadow/blame/676a611561e773d67c18516abdb05ae171182be6/buildScripts/gradle/maven.gradle#L301-L313

官方文档：https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials

**Comment by wwq006** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishActivityContainerPublicationToMavenRepository'.
> Failed to publish publication 'activityContainer' to repository 'maven'
   > Could not PUT 'http://10.110.143.37:8081/nexus/content/repositories/thirdparty/com/wwq/shadow/core/activity-container/2.0.12-5e3b7d73-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 27s




哈喽，我尝试过，报错了，一直都是不行的,是因为什么呢
配置如下：
 repositories {
        maven {
            credentials {
                username "admin"
                password "admin123"
            }
            url "http://10.110.143.37:8081/nexus/content/repositories/thirdparty/"
        }
    }

**Comment by shifujun** [comment]
这跟Shadow恐怕就一点关系也没有了。应该是你的Nexus部署有什么问题吧，也许只是单纯的账号密码错了。建议你测试一下其他构件的发布是否正常。

一般也要看一下Nexus服务端的日志吧。

**Comment by wwq006** [comment]
但是我用这种方式上传是好的呢

// 上传到本地仓库
task uploadToPublic(type: Upload) {
    group = "test"
    configuration = configurations.archives
    uploadDescriptor = true
    repositories{
        mavenDeployer {
            repository(url: MAVEN_RELEASE_REPO){
                authentication(userName: MAVEN_USER_NAME, password: MAVEN_PASSWORD)
            }
            pom.groupId = "com.test"
            pom.artifactId = "test"
            pom.version = "1.0.8"
        }
    }
}

**Comment by shifujun** [comment]
那你再参考一下maven-publish插件的文档中的例子，看看它是否跟你的Nexus部署兼容吧。
https://docs.gradle.org/current/userguide/publishing_maven.html

相信你用`mavenLocal()`也是好使的，maven-publish插件应该没什么问题。前面贴给你的例子也是我们之前自己部署的Nexus上传配置，是可以正常运行的代码。

**Comment by wwq006** [comment]
嗯嗯，谢谢啦，我昨晚试了好久都是不行，mavenLocal是好的，换成nexus就不行，谢谢，我再看看

**Comment by wwq006** [comment]
Storing of item thirdparty:/com/tencent/shadow/core/activity-container/2.0.12-5e3b7d73-SNAPSHOT/maven-metadata.xml is forbidden by Maven Repository policy. Because thirdparty is a RELEASE repository

不好意思，找到问题了，谢谢。一个捂脸的表情

**Comment by lejun** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':publishActivityContainerPublicationToMavenRepository'.
> 
> > Failed to publish publication 'activityContainer' to repository 'maven'
> > Could not PUT 'http://10.110.143.37:8081/nexus/content/repositories/thirdparty/com/wwq/shadow/core/activity-container/2.0.12-5e3b7d73-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Bad Request
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3m 27s
> 
> 哈喽，我尝试过，报错了，一直都是不行的,是因为什么呢
> 配置如下：
> repositories {
> maven {
> credentials {
> username "admin"
> password "admin123"
> }
> url "http://10.110.143.37:8081/nexus/content/repositories/thirdparty/"
> }
> }

这里得替换成快照路径：
```url
http://localhost:8081/nexus/content/repositories/snapshots/
```
