### ISSUE TITLE
Cannot access first() element from an empty Iterable

### ISSUE THREAD

**Issue by wuchengithub** [Tencent/Shadow#42]
Cannot access first() element from an empty Iterable

build 的时候发生问题 模块：sample-plugin

afterEvaluate {
    android {
        buildTypes.findAll().each { buildType ->
            def buildTypeName = buildType.getName()
            **def task = project.getTasksByName("check${buildTypeName.capitalize()}Classpath", false).first() as Task**
            task.dependsOn gradle.includedBuild('core').task(':common:jarDebugPackage')
            task.dependsOn gradle.includedBuild('dynamic').task(':dynamic-host:jarDebugPackage')
        }
    }
}

**Comment by shifujun** [comment]
建议fork之后，把复现问题的代码push上来，让我可以直接拉取你的代码复现问题。

如果让我猜的话，你改了Shadow的代码才会发生这种问题。因为Gradle构建非常健壮，不会有这种问题的。

**Comment by wuchengithub** [comment]
我修改过gradle和kotlin的版本号
ext.kotlin_version = '1.3.21'
ext.build_gradle_version = '3.3.1'
应该和gradle的版本有关系，不兼容3.3.1

**Comment by shifujun** [comment]
所以就是你改了代码才有问题呀。

我确实不理解为什么会认为改了代码出错是项目本身的问题。而且为什么提issue的时候不说自己改了代码呢？

如果你认为你的改动和项目无关的话，我们就没必要把这两个版本号用Git版本控制起来了。另外，如果再猜的话，你可能想验证你想在项目中用的这两个版本Shadow是否支持，那你搞错了验证方式。这里定义的版本号是Shadow项目本身使用的，跟你的业务使用的没关系。想验证的话，可以在二进制maven依赖的sample中试验。见https://github.com/Tencent/Shadow/tree/dev/projects/sample#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven

**Comment by ckrgithub** [comment]
使用[0]替换first(),然后进行判空处理，就可以编译成功
def buildTypeName = buildType.getName()
def taskArray=project.getTasksByName("check${buildTypeName.capitalize()}Classpath", false)
def task = taskArray[0] as Task
task?.dependsOn gradle.includedBuild('core').task(':common:jarDebugPackage')
task?.dependsOn gradle.includedBuild('dynamic').task(':dynamic-host:jarDebugPackage')
