### ISSUE TITLE
如何管理多插件zip包里的uuid

### ISSUE THREAD

**Issue by wwq006** [Tencent/Shadow#420]
你好，按照您之前多插件如何加载的回复这一条，我按照这条确实实现了多插件的同宿主运行，我有个问题：就是我是通过手动改写json文件的uuid并且删除其他zip包的loader和runtime 包，然后运行的，那有没有办法可以指定哪些插件不生成loader和runtime并且同时给json指定uuid值，谢谢

下面是您之前的回复：

**我们的业务确实有这个场景，但是业务的代码不能直接开源出来。这个一直没时间写sample，所以暂时只能参考实现代码了。

插件在安装后是跟安装前有几个zip包有几个config.json没有关系的。

所以打的zip包只需要里面的config.json配置不冲突就好了。所以关键是只能有一个zip包里有runtime和loader，以及所有的zip包的uuid是一样的。这样它们分别安装后在数据库里看起来就和同一个zip安装的一样了。**

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/gradle-plugin/src/test/kotlin/com/tencent/shadow/core/gradle/PackageOnlyPluginTest.kt

这个测试用例里执行的测试构建是`:plugin1:packageOnlyApkPlugin`，对应的配置就在

https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin1/build.gradle#L63-L75

**Comment by wwq006** [comment]
嗯嗯，我先看看，谢谢

**Comment by wwq006** [comment]
谢谢，完美 ， 赞

**Comment by wwq006** [comment]
唯一的问题就是感觉启动插件activity有点延时

**Comment by shifujun** [comment]
> 唯一的问题就是感觉启动插件activity有点延时

需要业务自己设计一些合适的预加载时机吧。

**Comment by wwq006** [comment]
嗯，那多问个问题哈，那这样的话，是不是意味着宿主进程启动后首次就得加载带有ruuntime和loader的zip插件，这个可以提供些思路吗

**Comment by wwq006** [comment]
宿主里包含10个插件，9个是不包含runtime和loader的zip文件，只有一个是包含的，那假如首次用户触发的是不带runtime和loader的插件，肯定是没法加载的，这种情况可以提供下思路吗？谢谢

**Comment by shifujun** [comment]
> 嗯，那多问个问题哈，那这样的话，是不是意味着宿主进程启动后首次就得加载带有ruuntime和loader的zip插件，这个可以提供些思路吗

宿主的Application启动之后到需要启动插件之前，这段时间之内都可以加载runtime和loader。具体在什么时间点合适肯定是跟业务相关的。如果你的宿主启动的时候对速度很敏感，你的插件又不是宿主启动完第一时间要使用的，那在宿主启动后就立即加载runtime和loader肯定是不合适的。

可以单独搞一个只有runtime和loader的zip包先下载。让用户触发下载插件时同时下载两个zip包。

**Comment by wwq006** [comment]
嗯，那我先尝试预加载runtime和loader，不操作插件apk试试，谢谢

**Comment by wwq006** [comment]
太给力了，我预加载runTime和laoder用的是这个方法installPlugin(pluginZipPath, null, true);，有其他方法吗？

**Comment by wwq006** [comment]
private void setUuid(String uuid) throws FailedException {
        if (mUuid.isEmpty()) {
            mUuid = uuid;
        } else if (!mUuid.equals(uuid)) {
            throw new FailedException(ERROR_CODE_RESET_UUID_EXCEPTION, "已设置过uuid==" + mUuid + "试图设置uuid==" + uuid);
        }
    }


你好，这个操作，为什么在下一次设置uuid的时候就直接抛错误了，是基于什么原因

**Comment by shifujun** [comment]
https://juejin.im/post/6844903893130821640

wiki里的链接建议都读一下。

**Comment by wwq006** [comment]
大神，谢谢，昨天可下哈，还有个问题，希望可以指导下：
加入插件是用户点击之后触发的，那么从下在到插件加载完成耗时好长，我统计了下，仅仅shadow内部首次加载插件都耗时长达6秒多了，麻烦问下如何优化呢

**Comment by shifujun** [comment]
插件的加载分成几个过程，每个过程跟插件的特点都有关系。比如dex大小，Manifest大小等等。这部分Shadow没有特别优化，其实是值得做的。不过我们的业务优先考虑的是从预加载、缩小插件包体积、拆分多插件这些简单的手段去优化的。

**Comment by wwq006** [comment]
嗯嗯，谢谢，腾讯系的可能是可以保活可以做预加载，像我们的没法保活的进程，没法做预加载，对于用户冷启动后，手动触发插件加载，这个时候除了loading等待好像别无他法，但是产品又不希望看见loading，哈哈

**Comment by wwq006** [comment]
谢谢哈，这个问题我关了哈，非常感谢，给shadow一个赞

**Comment by longrenzhut** [comment]
@sophild006 求指导15088765390
