### ISSUE TITLE
系统app使用Shadow报错 java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes

### ISSUE THREAD

**Issue by yiwanganjing** [Tencent/Shadow#421]
java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:187)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.getFactory(WebView.java:2530)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2525)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2590)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.view.View.<init>(View.java:4574)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.view.View.<init>(View.java:4706)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.view.ViewGroup.<init>(ViewGroup.java:597)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:643)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:588)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:571)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:558)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:548)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at com.tencent.shadow.core.loader.blocs.CreateResourceBloc$create$1.run(Unknown Source:4)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:793)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-20 18:34:20.180 18825 18825 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by yiwanganjing** [comment]
同 #215

**Comment by shifujun** [comment]
你也可以跟#215 一样revert fb2da72 。

反正WebView本来也不让在你这个进程使用，那个提交也是针对WebView的问题的，revert掉应该没关系吧。
