### ISSUE TITLE
宿主改成 系统app 插件中使用System.loadLibrary()加载so库会报错,提示没有权限

### ISSUE THREAD

**Issue by yiwanganjing** [Tencent/Shadow#422]
java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/data/com.*.*/files/ShadowPluginManager/UnpackedPlugin/uhome-manager/lib/EE4C13CE-42EF-44CF-B6F3-5CAED21FAA66_lib/libnative-lib.so" segment 1: Permission denied
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.*.*.service.AppService.<init>(UaiAppService.kt:47)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.tencent.shadow.core.runtime.ShadowAppComponentFactory.instantiateService(ShadowAppComponentFactory.java:30)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.tencent.shadow.core.loader.managers.PluginServiceManager.newServiceInstance(Unknown Source:66)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.tencent.shadow.core.loader.managers.PluginServiceManager.createServiceAndCallOnCreate(Unknown Source:0)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.tencent.shadow.core.loader.managers.PluginServiceManager.bindPluginService(Unknown Source:32)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader$bindPluginService$1.invoke(DynamicPluginLoader.kt:158)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader$bindPluginService$2.run(DynamicPluginLoader.kt:167)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:793)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-01 13:40:27.736 10581 10581 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by shifujun** [comment]
系统app我接触的比较少，Shadow的在设计上也没有考虑系统app。如果要考虑的话，我会觉得系统app应该不需要shadow这种插件技术。因为有root权限了就完全不用管app需要安装才能运行这种限制了。
