### ISSUE TITLE
我的子插件apk项目是不是需要依赖你们项目里的一些核心库比如sdk？我发现我这边直接打包一个和你们项目没有关联的apk是运行不了的

### ISSUE THREAD

**Issue by 123yangu** [Tencent/Shadow#427]

**Comment by VirgCode** [comment]
> _No description provided._

用做插件的项目需要通过shadow框架处理，转换成可以通过框架启动的apk，转换后的apk是不能正常安装到手机上的

**Comment by shifujun** [comment]
可以从这篇文章中了解一下Shadow的基本原理：https://juejin.im/post/6844903876655579150

Wiki中的其他文档也可以看一下。

**Comment by 123yangu** [comment]
我这边是建立了两个项目都是都是clone下来你们的Shadow，把其中一个作为宿主项目，另一个作为插件项目，插件Shadow项目编译出来的apk，在宿主项目启动的demo上把原有的pluginmanager.apk替换换成我自己插件项目打包出来的apk,这种思路可以吗？还是项目必须只能在单个Shadow项目中进行？

**Comment by shifujun** [comment]
参考https://github.com/Tencent/Shadow/tree/master/projects/sample#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven
