### ISSUE TITLE
宿主和插件之间通讯

### ISSUE THREAD

**Issue by barryly** [Tencent/Shadow#43]
刚刚提交了一个例子
d25da55fc68557da0f0b966f33e182594136dd87

后面再补充其他场景。

_Originally posted by @shifujun in https://github.com/Tencent/Shadow/issues/31#issuecomment-509094491_

按照您的方式，我试着增加一个module，然后有个host宿主implementation这个module，插件plugin ComplieOnly这个module，然后插件使用这个module里面的某个类，而且我已经加了whitelist，但是为啥现在还是会报错插件找不到这个宿主的module呢？

**Comment by shifujun** [comment]
你把出错的代码push上来，我就可以直接调试看出问题了。

fork Shadow到自己名下。然后把改动提交，push上来。不用提MR，我直接去你的版本库里看就行了。

**Comment by barryly** [comment]
问题找到了，是由于我当前插件依赖了dependOn别的插件，然后当前的父classloader应该是被依赖的插件。而不是宿主，解决办法是在被依赖的插件上面加个宿主的白名单才对。
