### ISSUE TITLE
获取插件的类

### ISSUE THREAD

**Issue by wwq006** [Tencent/Shadow#434]
你好，请问下我manager的 enter方法里通过context获取类，发现context是Manager.apk的上下文，并非插件的，我现在想在宿主里获取插件的context，为的是获取插件的某一个类，请问可以做到吗？有什么方式，谢谢

**Comment by shifujun** [comment]
由于插件ClassLoader的parent是宿主的ClassLoader，所以插件的ClassLoader中的类型不能在宿主中直接使用。最好的方式还是通过依赖反转设计，让插件向宿主注入接口的实现。接口由宿主定义，并写到白名单中。

需要注意的是，获取插件的ClassLoader也最好通过依赖反转的方法，令插件自己向宿主设置自己的ClassLoader。

关于插件如何依赖宿主中的类型，可以参考：
https://github.com/Tencent/Shadow/tree/master/projects/sample/source/sample-host-lib

**Comment by wwq006** [comment]
好的，我看看，谢谢哈，还有个问题哈，就是插件依赖了第三方的sdk，他们里面有对context强转application，但是插件的application变成了shadowApplication，这个问题如何规避呢

**Comment by shifujun** [comment]
强制转换本身是错的。你可以在没有Shadow的情况下，重写Application的getContext方法，返回一个ContextWrapper类型，这样它也一样会Crash的。所以这是第三方sdk的bug。

绕过的办法，可以考虑将宿主的Application对象传给它看看能否满足它的需求。

**Comment by wwq006** [comment]
嗯嗯，谢谢大神指导
刚刚那个classLoader的问题，是在宿主里LoadPluginCallback.setCallback设置callBack吗？我设置后在调用的地方报空指针，麻烦在指导下哈，谢谢

![image](https://user-images.githubusercontent.com/11993379/97870639-33e17400-1d4e-11eb-9f02-609a2e4539d2.png)

**Comment by wwq006** [comment]
拿到了，谢谢大神

**Comment by wwq006** [comment]
![image](https://user-images.githubusercontent.com/11993379/97954345-3be8f480-1dde-11eb-80c6-5f246ae9eed3.png)
你好，classloader是获取到了，但是有个问题，回调是在plugin进程里的，宿主拿不到

**Comment by shifujun** [comment]
> classloader是获取到了，但是有个问题，回调是在plugin进程里的，宿主拿不到

这你就得复习下什么是进程了。进程的内存是独立的。ClassLoader只是个对象而已。由于它不可序列化，我们也没有共享内存的能力，所以没法跨进程使用ClassLoader。

**Comment by wwq006** [comment]
> > classloader是获取到了，但是有个问题，回调是在plugin进程里的，宿主拿不到
> 
> 这你就得复习下什么是进程了。进程的内存是独立的。ClassLoader只是个对象而已。由于它不可序列化，我们也没有共享内存的能力，所以没法跨进程使用ClassLoader。

大神，你好，我把插件的pps没有加载在plugin进程里，而是加载到了宿主进程，
 <service
            android:name="com.test.service.MainPluginProcessService"
   />
启动activity后获取到了classloader，但是没法加载成功插件的类
 classLoader  ： com.tencent.shadow.dynamic.host.ApkClassLoader[DexPathList[[zip file 
     "/data/data/com.test.shadow_demo/files/Plugin-M.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
 exception ： java.lang.ClassNotFoundException: com.test.MyVideoView
请问下这个是什么原因？

**Comment by wwq006** [comment]
大神，框架太厉害了，膜拜
