### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by guozhiqiang123** [Tencent/Shadow#435]
我已经配置好ANDROID_HOME的环境变量了，并且验证也是通过的。android-30的jar包对应目录也是有的，但还是报错。报错如下，希望有大佬指点一下：
Caused by: java.lang.RuntimeException: Missing SDK Platform Android，API 30。请确保以下文件存在: C:\Users\xxx\AppData\Local\Android\Sdk;/platforms/android-30/android.jar

**Comment by shifujun** [comment]
`Sdk;`那个分号是正确的吗？

**Comment by Gtaiqin** [comment]
allprojects {
    ext.COMPILE_SDK_VERSION = 30
    ext.MIN_SDK_VERSION = 14
    ext.TARGET_SDK_VERSION = 28
    ext.VERSION_CODE = 1
    ext.VERSION_NAME = "2.0.12"
    if ("${System.env.PUBLISH_RELEASE}".equalsIgnoreCase("true")) {
        ext.VERSION_SUFFIX = ""
    } else if ("${System.env.ORANGE}".equalsIgnoreCase("true")) {
        ext.VERSION_SUFFIX = "-${System.env.ORANGE_COMMIT_SHORT}-SNAPSHOT"
    } else {
        ext.VERSION_SUFFIX = "-${gitShortRev()}-SNAPSHOT"
    }
    ext.ARTIFACT_VERSION = ext.VERSION_NAME + ext.VERSION_SUFFIX
    ext.TEST_HOST_APP_APPLICATION_ID = 'com.tencent.shadow.test.hostapp'
    ext.SAMPLE_HOST_APP_APPLICATION_ID = 'com.tencent.shadow.sample.host'
    repositories {
        google()
        jcenter()
    }
    //环境检查
    envCheck()
}


def envCheck(){
    //优化错误提示，不然会出现代码中找不到android依赖的问题
    def jarFile = file("${System.getenv().get('ANDROID_HOME')}/platforms/android-${project.COMPILE_SDK_VERSION}/android.jar")

    if(!jarFile.exists()){
        throw new RuntimeException("Missing SDK Platform Android，API ${project.COMPILE_SDK_VERSION}。请确保以下文件存在: ${jarFile.absolutePath}")
    }
}



packageDebugPlugin    执行报错

Execution failed for task ':app:transformClassesWithShadowTransformForDebug'.
> javassist.NotFoundException: D:\Android\SDK\platforms\null\android.jar

ANDROID_HOME环境变量有配置   并且android-30目录存在  
classpath 'com.android.tools.build:gradle:4.0.2'
gradle编辑版本6.6.1

**Comment by Heart-Beats** [comment]
这个问题解决很简单，你必须要和 sample 中插件对Shadow Gradle 使用的位置一样，如：[Shadow 插件应用的位置](https://github.com/Tencent/Shadow/blob/master/projects/sample/maven/plugin-project/plugin-shadow-apk/build.gradle#L44-L46)，
因为 Gradle 脚本是按顺序执行的，Shadow Gradle 插件会读取项目构建脚本中的 Android { } 闭包 compileSdkVersion 的值，得到的 androidJarPath 即如 D:\Android\SDK\platforms\${compileSdkVersion }\android.jar，你可以查看一下自己应用插件的位置是否正确
