### ISSUE TITLE
插件依赖的类是否都要打进插件？

### ISSUE THREAD

**Issue by crazymongo** [Tencent/Shadow#440]
有些插件框架对于一些公共的类，是不打进插件的，不知道Shadow是怎么处理这块的。

**Comment by shifujun** [comment]
公共的类如果不涉及Shadow Transform操作，可以复用宿主中的实现。

可以参考#429 中的回复。

**Comment by crazymongo** [comment]
Shadow框架在剔除类的时候，是基于lib级别还是类级别呀？我发现Shadow框架在处理FileProvider的时候，把整个lib都打进了插件，感觉这样不是很合理，如果用一个新类替换这个FileProvider，可以避免把相关的lib打入插件，以减少插件体积。

**Comment by shifujun** [comment]
你说的"剔除类"是指什么过程？Shadow本身没设计哪些类要打包哪些类不要打包，这完全还是apk本身的构建过程决定的。

**Comment by crazymongo** [comment]
换个说法吧，假如插件和宿主都依赖了lib A，当A的版本一样的时候，插件可以不把A打进去，与宿主共享A；如果插件所依赖A的版本跟宿主不一样，此时插件需要把A打入插件吗？

**Comment by shifujun** [comment]
都可以啊。这跟Shadow的唯一关系就是Shadow设计的ClassLoader白名单机制，可以参考#429 中的回复。其余问题都是Java本身的问题，以及apk的构建设计，这些都是通用的知识，跟Shadow没有具体关系。

**Comment by crazymongo** [comment]
非常感谢您的解惑
