### ISSUE TITLE
关于宿主apk 和 插件apk资源id冲突的问题

### ISSUE THREAD

**Issue by hyandroid** [Tencent/Shadow#443]
你好，请教一个问题，宿主apk 和 插件apk是单独打包的，这样会导致资源id冲突。
现在插件apk中有两种引用color资源的方式：
1.xml引用： android:background="@color/color_plugin"
2.代码设置：findViewById<View>(R.id.myView).setBackgroundColor(resources!!.getColor(R.color.color_plugin))

第二种方式没问题，取得是插件中的色值，而第一种方式会取到宿主中对应的R文件索引的色值，这个问题该怎么处理呢？

**Comment by shifujun** [comment]
如果是测试apk，麻烦上传上来我看看。如果是在sample中添加代码复现的，麻烦push上来代码。

从实现原理来说，即使插件和宿主中存在两个一样的ID，也会优先使用插件的。出现你说的取到宿主中色值的情况，正常情况下不会发生。要么是插件apk中就没有这个ID，这不太可能嘛，都是自动生成的ID。要么就是你这个Activity或者Fragment的Context是宿主的。

还要强调的是，本身Shadow在设计目的上是没有这种宿主和插件资源混用，有优先级关系的。参考之前讲的：https://github.com/Tencent/Shadow/issues/323#issuecomment-626482522

我还在抽时间复现那个Bug，然后争取去掉MixResources。

**Comment by hyandroid** [comment]
抱歉，我不是在用Shadow，而是在研究hook方式加载插件apk时发现的问题。你提到的”这个Activity或者Fragment的Context是宿主的" 应该不是这个原因吧，因为以代码方式设置颜色是正确显示的，在xml中引用才会冲突
。是因为xml中引用方式加载机制不一样吗？

如图插件的plugin_color的id索引0x7f04002a取到了宿主中的
0x7f04002a | dim_foreground_disabled_material_light | argb8(0x80323232)  色值
![Lark20201120101154](https://user-images.githubusercontent.com/11974245/99749535-b3768d80-2b19-11eb-94d0-81f255835b41.png)
![Lark20201120101326](https://user-images.githubusercontent.com/11974245/99749538-b4a7ba80-2b19-11eb-83fb-a8956293bc13.png)
能给一些建议，从哪里寻找问题吗？多谢

**Comment by shifujun** [comment]
哈哈😄，我就说Shadow不应该有这个问题嘛。

大概就是这么个路径把ID换成value的：ID → Context → Resources  → Assets  → arsc  → value 。

然后就看你是怎么把插件apk加载进去的了。Shadow的方式就在 https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt ，你可以直接拿出去用。这种方式会得到一个插件apk的Context，所以直接用这个Context加载ID，就不会跟任何东西冲突了。

**Comment by hyandroid** [comment]
多谢帮助，我试试
