### ISSUE TITLE
每新增一个插件都需要一个Pps类么？

### ISSUE THREAD

**Issue by lwns** [Tencent/Shadow#445]
每新增一个插件都需要一个Pps类么？

**Comment by shifujun** [comment]
不是必要的。在一个插件进程有一个PPS就够了，由它持有Loader。一个Loader可以同时加载多个插件。

**Comment by lwns** [comment]
我看demo是有两个插件，有两个pps，那么原则上一个pps也可以是不？

**Comment by shifujun** [comment]
PPS是个正常的、注册在宿主Manifest里的Service。它的数量和运行插件的进程数量是一对一的关系。只有一个PPS，插件也就只能在PPS那个进程运行。

**Comment by lwns** [comment]
那么每次新增一个插件都需要发版新增一个Pps?

**Comment by shifujun** [comment]
为什么呢？你说你的判断的同时应该也说理由才行啊。要不我感觉我前面的解释都白说了。😕

**Comment by lwns** [comment]
还有个问题是，为啥要设计成Pps方式，不能放到主进程么？

**Comment by Heart-Beats** [comment]
@lwns 你需要看看设计原理，以及相关的工作流程。
这是大佬对插件需要跨进程的解释： [Shadow的跨进程设计与插件Service原理](https://juejin.cn/post/6844903877871927304)

还有你本来的问题只要你看过相关的代码就能了解，宿主是通过 Pps 来调用插件的，可以使用一个来调用不同的插件，至于多插件，如果你的多插件为通过 partKey 启动只需要一个 PluginManager 即可， 如果是要启动多个不同的插件压缩包，则需要多个 PluginManager ，否则在不改源码的基础上，你的插件数据库会混乱。

**Comment by HeLiHuang** [comment]
> 为什么呢？你说你的判断的同时应该也说理由才行啊。要不我感觉我前面的解释都白说了。😕

这个问题还是没有说清楚，在多个插件的情况中，应该是只有一个PPS就够了呢，还是每一个插件都需要一个属于这个插件的PPS？
