### ISSUE TITLE
由于Shadow是多进程的，仅支持单进程的Arouter如何兼容

### ISSUE THREAD

**Issue by listen2code** [Tencent/Shadow#446]
由于Arouter仅支持单进程，宿主想通过Arouter启动插件的中注册了Route的Activity，目前看来是实现不了。这个问题对于接入Shadow的业务方有一定的改造成本，是否有什么好的替代技术方案或建议？Shadow是否可以支持单进程，插件和宿主同一个进程？

**Comment by shifujun** [comment]
支持在主进程使用的。你把sample里的plugin进程声明都删了试试就行了。注意PPS一个进程只能有一个。

不过我估计ARouter只支持单进程的这个判断可能不太准确，虽然我也没用过。但这种Router设计应该不会强依赖内存指针，自己做一个跨进程通信应该能解决。

我们使用插件技术，不太愿意在主进程使用，主要是怕把主进程搞挂了。而且从原理上来讲，Shadow也只能在ClassLoader层面隔离插件和宿主，无法避免so这种Native库产生冲突。如果插件在主进程，就免不了要跟主进程的开发人员沟通可能存在的冲突问题。

**Comment by Daimhim** [comment]
1. 首先保证宿主与插件的ARouter使用同一个
解决方案：配置白名单就行
2. 插件注册路径不会自动添加到宿主的arout里面，所以需要手动加入
在插件内的Application中动态添加插件的arout路径即：
`
public class StartPlugin extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Log.i("StartPlugin222",String.format("%s",ARouter.getInstance().hashCode()));
        //ARouter$$Group$$testrout 是arout动态生成的
        ARouter
                .getInstance()
                .addRouteGroup(new ARouter$$Group$$testrout());
    }
}
`
记得在宿主加载插件的时候调用callApplicationOnCreate(partKey);
