### ISSUE TITLE
transformClassesWithShadowTransformFor异常

### ISSUE THREAD

**Issue by sophild006** [Tencent/Shadow#447]
Execution failed for task ':app:transformClassesWithShadowTransformForSnm'.
> javassist.CannotCompileException: findField (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/reflect/Field; inconsistent stack height 3

你好，在打包插件的时候报错，麻烦可以分析下吗？

**Comment by shifujun** [comment]
要是你什么都没改，那就应该是bug吧。就这么点信息也就只能分析到这了😕

**Comment by wwq006** [comment]
哈哈，那应该是个bug，有个新问题咨询下哈，就是插件里面有provider配置，但是并没有用到，如何做到不加载，因为插件我没法改

**Comment by shifujun** [comment]
请不要将Issue当作IM使用。对于无效的反馈，我实在无能为力。请参考：[CONTRIBUTING.md#issue](CONTRIBUTING.md#issue)。
