### ISSUE TITLE
加载系统so文件报错

### ISSUE THREAD

**Issue by sophild006** [Tencent/Shadow#448]
你好，加载系统so文件的时候抛出异常
Failed to register native method com.deviceinfo.TDeviceInfo.native_devinfo_getInfo
art/runtime/jni_internal.cc:769] JNI FatalError called: RegisterNatives failed for 'com/deviceinfo/TDeviceInfo'; aborting...

在TDeviceInfo Java类里确实没有native_devinfo_getInfo这个native方法，但是正常运行apk是好的，把apk以插件的形式加载就抛出异常，是shadow改了什么吗？

**Comment by shifujun** [comment]
Shadow没有对JNI相关的东西有任何修改。唯一沾边的事情就是配置了插件ClassLoader的so搜索路径，让插件的代码通过默认的System.loadLibrary能正常找到它的so。

你说的这种差异，估计是来自于业务的自身逻辑分支。可能是Shadow的其他影响导致它的分支逻辑判断出了问题。建议你在这个Native方法调用的最后一个可以打Java断点的地方看看的调用栈。对比两种运行方式下调用栈的差异，再去细看差异处的分支逻辑是怎样的。

**Comment by sophild006** [comment]
嗯，好的，我看看，谢谢哈

**Comment by sophild006** [comment]
你好，碰到javassist 处理泛型是抛出异常的问题
![image](https://user-images.githubusercontent.com/11993379/100608968-37b1e780-3348-11eb-923a-3da6d1ab9db8.png)
![image](https://user-images.githubusercontent.com/11993379/100608986-3ed8f580-3348-11eb-99de-fdd4f1e39d8b.png)
这个可以处理吗？

**Comment by shifujun** [comment]
你用的Shadow的代码是最新的吗？是的话，参考https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue 复现一下问题，push上来代码看看。
