### ISSUE TITLE
宿主可以直接调用插件的代码

### ISSUE THREAD

**Issue by kzhu-bstar** [Tencent/Shadow#45]

**Comment by shifujun** [comment]
让我猜猜，你想问的是宿主可不可以直接调用插件的代码？如果可以，想看示例代码？

最好能不让我猜，描述清楚。

**Comment by kzhu-bstar** [comment]
嗯嗯，是的

**Comment by shifujun** [comment]
那这个问题也值得再细化。建议问问题时尽量细化你的问题，因为有些你觉得是显然只有一种场景的情况，实际上别人会想到其他场景去。

比如”直接调用“是什么定义？宿主里直接写插件中的一个类名，new出来实例，调用方法吗？我觉得这样才是直接调用。但又感觉这不应该是个问题，因为我们做插件系统，不就是希望插件的代码是动态更新的吗？那宿主怎么可能能提前写出来插件中存在的类呢？

希望你能举出具体的例子。

**Comment by kzhu-bstar** [comment]
我们想一部分逻辑加入到插件中，但是这部分逻辑涉及到一些View的传递，无法通过Binder传递，所以想宿主直接new出一个插件的类，来调用插件里面的方法。

**Comment by shifujun** [comment]
这么说我应该想不到别的场景了。

先说实现方法，参考 d25da55 实现插件直接调用宿主中的代码。在宿主中定义一个Callback让插件实现，插件先调用宿主方法把Callback实现传给宿主，宿主再调用Callback对象的方法。在这个Callback的方法上传递View即可。

为什么要这么实现？我们运用ClassLoader，可以任意实现插件调用宿主或者宿主调用插件。但是在任何设计中都不应该出现循环依赖，所以我们在这里也不能即让插件依赖宿主，又让宿主依赖插件。所以我们必须二选一，我们的选择就是让插件依赖宿主。因为宿主代码比较稳定，假设宿主是不会热更新的。所以被依赖的一方比较稳定更有用一些。这说的只是实际结构上是单向依赖的。并不是说逻辑上不能出现双向依赖，因此宿主依赖插件要用”依赖反转“来实现，即前面讲的方法。

**Comment by kzhu-bstar** [comment]
谢谢

**Comment by kzhu-bstar** [comment]
我在插件的Application子类的onCreate调用
```
 HostUiLayerProvider.getInstance().setCallback(new Callback() {
            @Override
            public String call(String s) {
                return "Recv: " + s + ", return byebye!";
            }
        });
```

然后在宿主加载插件结束回调内 
```
Callback callback = HostUiLayerProvider.getInstance().getCallback();
String result = callback.call("hello");
```

这样实现下来 Callback获取的会为null

是哪里出错了么？

**Comment by shifujun** [comment]
为什么不把代码push上来呢？其实这个跟插件框架都没什么关系了，简单debug一下就行了吧？

**Comment by kzhu-bstar** [comment]
简单的查看了下 日志发现HostUiLayerProvider插件和宿主是不同的对象，他们分别有主进程和插件进程，load出来的吧

**Comment by shifujun** [comment]
你看你这不是很容易发现原因了嘛？

**Comment by kzhu-bstar** [comment]
之前想到利用插件调用宿主，直接把插件的ClassLoader传过去，有宿主直接通过ClassLoader来loadclass，就发现传递不过去，想了很久没有想到，不知道用什么方式 能够让宿主拿到插件传递过来的对象

**Comment by kzhu-bstar** [comment]
有没有办法 让宿主拿到插件传递过来的对象呀 想不到了...

**Comment by shifujun** [comment]
怎么还在问呀？前面不是都回答了，还给你例子了。而且你又不提供自己搞不定的具体代码，想别人怎么帮你呢？
