### ISSUE TITLE
shadow demo  sample-plugin-app  调用系统相机拍照，不能返回照片

### ISSUE THREAD

**Issue by 790396054** [Tencent/Shadow#450]
运行 sample-host 项目，启动 sample-plugin-app 插件，点击 ContentProvider 测试用例+  ==》 FileProvider 相关测试。
启动 拍照界面，调用系统相机后，得不到照片。查看是 onActivityResult 方法resultCode 返回 0。正常情况应该返回 -1。
附上代码 com.tencent.shadow.sample.plugin.app.lib.usecases.provider.TestFileProviderActivity
![截屏2020-12-08 下午5 54 36](https://user-images.githubusercontent.com/10391006/101468493-72d29d00-397e-11eb-87bd-aca031df32f4.png)

这是打开相机的代码。
![截屏2020-12-08 下午5 55 13](https://user-images.githubusercontent.com/10391006/101468545-867e0380-397e-11eb-89f4-382dc55dcd78.png)

**Comment by 790396054** [comment]
忘了说了，是在 MIUI12，Android 10 测试的代码。

**Comment by shifujun** [comment]
这个表述是说MIUI12有Bug吗？

**Comment by 790396054** [comment]
我用vivo Funtouch OS Android 6 测试也出现这个问题。你们不能复现么？

**Comment by shifujun** [comment]
你应该先测试官方的系统。因为我们没用非公开API实现任何功能，如果官方系统上没问题，那就是OEM系统的bug了。

**Comment by 790396054** [comment]
![截屏2020-12-09 下午2 37 44](https://user-images.githubusercontent.com/10391006/101594126-1a59d900-3a2c-11eb-8c80-6cba8362e79a.png)

java.lang.IllegalArgumentException: hostContentProviderDelegate is null ,请检查ContentProviderDelegateProviderHolder.setDelegateProviderHolderPrepareListener是否调用，或PluginContainerContentProvider 是否和插件在同一进程

报错了，请问怎么修改？
另外是官方的系统是模拟器吗？没有谷歌系列的手机啊

**Comment by 790396054** [comment]
刚才又测试了下，作为插件，在模拟器上运行也是一样的错误。
sample-normal-app 独立运行是正常的。请问在插件环境下怎么解决？

**Comment by shifujun** [comment]
![image](https://user-images.githubusercontent.com/3535204/101612875-163ab500-3a46-11eb-8563-4c28993acdc4.png)

如图我没能复现问题。你还是检查下自己是不是改了什么代码吧。

**Comment by 790396054** [comment]
确实是我改的代码导致的，感谢回复。
