### ISSUE TITLE
能否提供一个宿主加载插件Fragment的示例？

### ISSUE THREAD

**Issue by chenfuxu920** [Tencent/Shadow#453]
我看过之前#319 的讨论，也尝试过里面各位提到的思路，但是折腾几天也没成功，这个需求应该也挺常见的吧，能提供一个官方示例吗？

**Comment by shifujun** [comment]
就像#319 里讨论的那样。宿主加载插件Fragment有很多可以想到的要求。不同要求下实现复杂度也不同。每个具体的需求都不常见，只能说和Fragment相关的需求比较常见。

你可以在sample里用代码表达一下你的需求。如果需求简单到在宿主加载Fragment这句话，那显然Shadow现在的实现就已经满足需求了。

**Comment by chenfuxu920** [comment]
> 就像#319 里讨论的那样。宿主加载插件Fragment有很多可以想到的要求。不同要求下实现复杂度也不同。每个具体的需求都不常见，只能说和Fragment相关的需求比较常见。
> 
> 你可以在sample里用代码表达一下你的需求。如果需求简单到在宿主加载Fragment这句话，那显然Shadow现在的实现就已经满足需求了。

就像@qlfabc 这位朋友提到的[仓库](https://github.com/qlfabc/Shadow/tree/feat_fragment)一样，就是在宿主中加载插件Fragment，能正常显示即可。他的代码实现我试了，可以获取到插件的Fragment对象，但是布局加载是错误的，没有使用插件中的布局资源，他后面提到的修复思路，我尝试了一下，没能成功。
至于说现在的实现能满足要求，这个不太理解，现有的示例里面只有宿主开启插件activity和service吧，没有获取插件中对象的示例

**Comment by shifujun** [comment]
如果那个`DemoFragmentActivity`代表了全部需求，那根本没必要用Shadow。系统本来也不管Fragment的动态加载。这也是我说现有代码已经满足需求的原因。Shadow里的Fragment也是正常的Fragment，它直接被添加到了ContainerActivity上。ContainerActivity就是一个宿主的Activity。Shadow做的额外的事情是让Fragment内部的代码在获取Activity时拿到插件的ShadowActivity，以便它试图操作插件中的Activity时正常工作。

Fragment动态加载相关的问题中最麻烦的是Fragment的资源和Activity是直接绑定的，如果Activity需要使用宿主的资源，而它上面的Fragment又要使用插件的资源。这就需要去Activity的Resource上做复杂的逻辑了。

如果Activity不用宿主的资源，完全使用插件的资源，那么插件的Fragment直接添加到Activity就行了。这简单写个DexClassLoader加载Fragment的代码就行了，不用Shadow。

更复杂的需求会说一个宿主Activity想同时加载来自多个apk中的Fragment。这就非常麻烦了，那个取资源的实现是系统代码，继承之后匹配这种逻辑很别扭。想想就很麻烦。所以这种场景我会推荐将Fragment改成View，然后关心的生命周期问题自行设计一个接口实现。View就没有这种麻烦。

**Comment by chenfuxu920** [comment]
我的需求是在宿主的Activity中同时展现宿主自带的Fragment和一个插件中的Fragment，正如您所说，目前遇到的问题就是插件的Fragment不会使用插件的资源，而是使用了宿主的资源。

不知道您对RePlugin这个插件化框架有没有了解，RePlugin是支持宿主加载插件Fragment的，不清楚它的实现是不是您说的修改Activity的Resource，但是RePlugin现在不支持AndroidX，不太适合长期使用。

您说的Fragment改View，这种实现不会出现和Fragment一样无法加载插件自己的资源的问题么？

**Comment by shifujun** [comment]
RePlugin对Fragment的支持我没有具体了解。但可以猜到如果允许调用私有api，最好的办法是对插件的资源ID分区，然后把插件的apk直接注入到宿主的Resource里。这样很容易就能达到目的。Shadow的方案中不会考虑使用私有api，所以这条路是行不通的。

Fragment与View有一个显著的区别是Fragment没有自己的Context或者Resource，它是直接使用Activity的，而View构造的时候就会绑定一个自己的Context。然后业务用Fragment而不用View，主要的原因也是业务关心了Activity的生命周期，需要通过Fragment的设计了解这些生命周期。但这一点也可以不用Fragment，业务完全可以自己设计一个简化版的Fragment接口，让View实现后由特定的承载这些View的Activity去通知它们生命周期。

**Comment by chenfuxu920** [comment]
明白了，那宿主该怎么获取插件的Context提供给插件的View呢

**Comment by shifujun** [comment]
抄一下这个API的用法，构造出插件的Resource，然后放到一个ContextWrapper的getResource方法中返回就行了。

https://github.com/Tencent/Shadow/blob/116cb827686c7bda8e0a8d455b7c320710e314f5/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt#L45

**Comment by chenfuxu920** [comment]
好的，感谢解答
