### ISSUE TITLE
android 10 crash

### ISSUE THREAD

**Issue by obaniu2006** [Tencent/Shadow#455]
com.tencent.shadow.sample.host E/dow.sample.hos: Dex checksum does not match for dex: /data/user/0/com.tencent.shadow.sample.host/files/pluginmanager.apk.Expected: 2819350984

**Comment by shifujun** [comment]
只有这么个标题和一行Log，实在是不知道这是什么情况下发生的什么问题，也不知道你有什么想问的。

提Issue请参考
https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue
