### ISSUE TITLE
编译配置问题

### ISSUE THREAD

**Issue by Gtaiqin** [Tencent/Shadow#456]
插件packageDebugPlugin 执行报错

Execution failed for task ':app:transformClassesWithShadowTransformForDebug'.

javassist.NotFoundException: D:\Android\SDK\platforms\null\android.jar

ANDROID_HOME环境变量有配置 并且android-30目录存在
classpath 'com.android.tools.build:gradle:4.0.2'
gradle编辑版本6.6.1

**Comment by shifujun** [comment]
你应该改了代码吧？自己看看改了什么，就是什么错了。

**Comment by Gtaiqin** [comment]
没有修改，修改的我已经重新clone编译了

**Comment by shifujun** [comment]
你的报错信息里的`null`应该只有这行
https://github.com/Tencent/Shadow/blob/a312f4447ea4c1066d977588858808ea542358b2/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt#L42
能打出来。你再看看你的compileSdkVersion有没有修改过设置吧。可以Debug一下这段代码的运行。

**Comment by Gtaiqin** [comment]
打这个断点需要运行哪个项目呢  我运行sample-host没走断点

**Comment by shifujun** [comment]
运行sample-host就行，它会源码依赖Shadow的Gradle Plugin的。

你可能是不知道怎么debug编译期的代码，可以参考：
https://medium.com/grandcentrix/how-to-debug-gradle-plugins-with-intellij-eef2ef681a7b

**Comment by Gtaiqin** [comment]
这里可以打印出来  
<img width="757" alt="捕获" src="https://user-images.githubusercontent.com/23159316/102842479-035eb200-4442-11eb-858e-11fa5e4e0035.PNG">

**Comment by Gtaiqin** [comment]
重新编译只需要删除.m2文件夹就可以是吧

**Comment by shifujun** [comment]
应该不用，都是做了源码依赖关系配置的，直接运行应该就会增量编译生效。

能debug了就查查那个null怎么产生的吧。之前执行的gradle命令可以加上-S选项打印出堆栈。

**Comment by shifujun** [comment]
我本来怀疑是Windows上构建我平常没有环境验证导致实际上不能正常构建。但是刚才加上了Windows环境的CI，看起来也是一切正常的。

https://github.com/Tencent/Shadow/pull/458/checks?check_run_id=1593456081

**Comment by Gtaiqin** [comment]
找到问题了 my_loader 和my_runtime gradle配置中
//apply plugin: 'com.android.library'
apply plugin: 'com.android.application'
这里改了一下 创建的时候搞错了

**Comment by Gtaiqin** [comment]
但是有个新的问题 我的demo插件运行安装正常   正式用到项目中时报错找不到application文件

**Comment by shifujun** [comment]
> 找到问题了 my_loader 和my_runtime gradle配置中
> //apply plugin: 'com.android.library'
> apply plugin: 'com.android.application'
> 这里改了一下 创建的时候搞错了

所以我最初就说你检查一下改了什么，你还说没改。


> 但是有个新的问题

与这个Issue不相关的问题另外提Issue吧，还是注意附上你的改动代码，push上来。可以参考：https://github.com/Tencent/Shadow/blob/a089ae87a848ae921489d1254d7b420861dddbc6/CONTRIBUTING.md
