### ISSUE TITLE
多插件的一些疑问

### ISSUE THREAD

**Issue by yghysdr** [Tencent/Shadow#457]
前提：一个PPS下多插件。

情景：多个插件的UUID相同下，每个插件有一个dynamic-manager和plugin.zip。多plugin情况下，只会加载第一个插件的loader，所以现在将plugin.zip中的runtime/loader单独打包，提供给所有的业务plugin.zip(不包含runtime/loader)。这个思路是符合现在shadow的设计吗？

疑问：
1 多个dynamic-manager配合UUID相同符合shadow的设计吗？
2 包含runtime/loader的plugin.zip是所有插件的集合，是不是每个插件单独处理runtime/loader/业务apk更合适，现在shadow应该是不支持单PPS下多个loader（看到有人提PR去提供支持多loader） 
3 单PPS下多插件UUID是否必须相同

**Comment by shifujun** [comment]
> 1 多个dynamic-manager配合UUID相同符合shadow的设计吗？

不符合。那个manager本身就是用来管理多个插件的，我想不到你需要多个manager的需求是什么。我们用UUID相同表示一组apk可以共用工作。这组apk里可以有一个runtime一个loader和多个插件apk。

> 2 包含runtime/loader的plugin.zip是所有插件的集合，是不是每个插件单独处理runtime/loader/业务apk更合适，现在shadow应该是不支持单PPS下多个loader（看到有人提PR去提供支持多loader）

在一个进程里，最好只有一组runtime和loader，毕竟一个进程里总有无法隔离的冲突。多插件时可以把runtime和loader放到一个单独的zip包里分发。其余业务插件apk可以放到单独的zip包里，根据需要决定先下载哪个。

一个PPS一个进程，里面放多个loader是`*-multi-loader-ext`两个模块支持的，这些loader需要共享一个runtime.apk。

> 3 单PPS下多插件UUID是否必须相同

肯定要相同的。UUID就是为了表示它们能否一起正常工作的。

**Comment by yghysdr** [comment]
> 想不到你需要多个manager的需求是什么
我们思考每个manager里面处理每个插件自己的业务跳转，这样每个业务有自己的manager不必关心其他业务的，多个loader也是这样考虑的。现在多个manager是运行的，多个loader不行。不过再想下dynamic-manager/loader/runtime的目的是为了动态化，只包含业务少量的业务跳转，一个也没什么问题。

那这样说单个PPS下多插件：一个zip包（只包含loader+runtime）+ 多个业务插件zip+ 一个manager.apk 是现在的shadow设计的多插件的思路吧

**Comment by yghysdr** [comment]
> 想不到你需要多个manager的需求是什么

我们思考每个manager里面处理每个插件自己的业务跳转，这样每个业务有自己的manager不必关心其他业务的，多个loader也是这样考虑的。现在多个manager是运行的，多个loader不行。不过再想下dynamic-manager/loader/runtime的目的是为了动态化，只包含业务少量的业务跳转，一个也没什么问题。

那这样说单个PPS下多插件：一个zip包（只包含loader+runtime）+ 多个业务插件zip + 一个manager.apk是的shadow设计的多插件的思路吧。

**Comment by shifujun** [comment]
> 那这样说单个PPS下多插件：一个zip包（只包含loader+runtime）+ 多个业务插件zip + 一个manager.apk是的shadow设计的多插件的思路吧。

这个是满足我们自身业务需求的设计的。

在同一个进程中存在多个相互独立开发的业务，这很难维护的。最好一个业务一个单独的进程。那样的话每个业务有自己的全套实现肯定也是相互没有影响的。

**Comment by yghysdr** [comment]
好的谢谢

**Comment by listen2code** [comment]
> > 那这样说单个PPS下多插件：一个zip包（只包含loader+runtime）+ 多个业务插件zip + 一个manager.apk是的shadow设计的多插件的思路吧。
> 
> 这个是满足我们自身业务需求的设计的。
> 
> 在同一个进程中存在多个相互独立开发的业务，这很难维护的。最好一个业务一个单独的进程。那样的话每个业务有自己的全套实现肯定也是相互没有影响的。

这样说的话，业务比较多的时候，就会有N个进程，进程太多会不会有性能问题？比如像手淘这样平台型的APP，各种子业务就会比较多，是不是就不太适合用shadow了？

**Comment by shifujun** [comment]
> > > 那这样说单个PPS下多插件：一个zip包（只包含loader+runtime）+ 多个业务插件zip + 一个manager.apk是的shadow设计的多插件的思路吧。
> > 
> > 
> > 这个是满足我们自身业务需求的设计的。
> > 在同一个进程中存在多个相互独立开发的业务，这很难维护的。最好一个业务一个单独的进程。那样的话每个业务有自己的全套实现肯定也是相互没有影响的。
> 
> 这样说的话，业务比较多的时候，就会有N个进程，进程太多会不会有性能问题？比如像手淘这样平台型的APP，各种子业务就会比较多，是不是就不太适合用shadow了？

多个进程一般也不会同时启动吧，如果有合适的时机切换插件进程对于内存中不可卸载的部分是唯一的清理手段。多个业务共用一个进程也不是不能用，花额外的精力处理冲突就行了。共用一个进程在切换业务时速度能快一些。

**Comment by hpuhsp** [comment]
想问一下，实现多个插件多进程 有什么比较好的思路吗？

**Comment by longrenzhut** [comment]
> 前提：一个PPS下多插件。
> 
> 情景：多个插件的UUID相同下，每个插件有一个dynamic-manager和plugin.zip。多plugin情况下，只会加载第一个插件的loader，所以现在将plugin.zip中的runtime/loader单独打包，提供给所有的业务plugin.zip(不包含runtime/loader)。这个思路是符合现在shadow的设计吗？
> 
> 疑问：
> 1 多个dynamic-manager配合UUID相同符合shadow的设计吗？
> 2 包含runtime/loader的plugin.zip是所有插件的集合，是不是每个插件单独处理runtime/loader/业务apk更合适，现在shadow应该是不支持单PPS下多个loader（看到有人提PR去提供支持多loader）
> 3 单PPS下多插件UUID是否必须相同

大佬 多插件搞好了没，加个微信 1162371142@qq.com, 求指导

**Comment by hehe2015** [comment]
> > 1 多个dynamic-manager配合UUID相同符合shadow的设计吗？
> 
> 不符合。那个manager本身就是用来管理多个插件的，我想不到你需要多个manager的需求是什么。我们用UUID相同表示一组apk可以共用工作。这组apk里可以有一个runtime一个loader和多个插件apk。
> 
> > 2 包含runtime/loader的plugin.zip是所有插件的集合，是不是每个插件单独处理runtime/loader/业务apk更合适，现在shadow应该是不支持单PPS下多个loader（看到有人提PR去提供支持多loader）
> 
> 在一个进程里，最好只有一组runtime和loader，毕竟一个进程里总有无法隔离的冲突。多插件时可以把runtime和loader放到一个单独的zip包里分发。其余业务插件apk可以放到单独的zip包里，根据需要决定先下载哪个。
> 
> 一个PPS一个进程，里面放多个loader是`*-multi-loader-ext`两个模块支持的，这些loader需要共享一个runtime.apk。
> 
> > 3 单PPS下多插件UUID是否必须相同
> 
> 肯定要相同的。UUID就是为了表示它们能否一起正常工作的。

多个plugin-debug都包含了loader和runtime，cofing.json里面的UUID在哪儿配置？
如果把loader和runtime单独打个zip包，怎么加载呢？
