### ISSUE TITLE
插件如果运行在宿主进程有没有什么影响？

### ISSUE THREAD

**Issue by vinaiso** [Tencent/Shadow#459]

**Comment by shifujun** [comment]
实现机制上没有任何影响。只是主进程基本上默认了这个进程里还有其他代码在执行。就算一个插件进程，里面跑多个不相关的插件在实现机制上也是可行的。

**Comment by vinaiso** [comment]
> 实现机制上没有任何影响。只是主进程基本上默认了这个进程里还有其他代码在执行。就算一个插件进程，里面跑多个不相关的插件在实现机制上也是可行的。
非常感谢，大佬的解惑
