### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/content/LocusId;

### ISSUE THREAD

**Issue by aminey555** [Tencent/Shadow#460]
你好，我对模块插件化的过程中，突然出现这种报错：

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/content/LocusId;
error	17:20:46.81		at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
error	17:20:46.81		at java.lang.reflect.Method.getParameterTypes(Method.java:186)
error	17:20:46.81		at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
error	17:20:46.81		at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
error	17:20:46.81		at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
error	17:20:46.81		at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
error	17:20:46.81		at com.newtzt.app.tztActivityBase.onCreate(tztActivityBase.java:140)
error	17:20:46.81		at com.newtzt.activity.ggqq.activity.tztBiaoSelectActivity.onCreate(tztBiaoSelectActivity.java:80)
error	17:20:46.81		at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:395)
error	17:20:46.81		at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
error	17:20:46.81		at android.app.Activity.performCreate(Activity.java:7458)
error	17:20:46.81		at android.app.Activity.performCreate(Activity.java:7448)
error	17:20:46.81		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
error	17:20:46.81		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
error	17:20:46.81		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
error	17:20:46.81		at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
error	17:20:46.81		at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
error	17:20:46.81		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
error	17:20:46.81		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
error	17:20:46.81		at android.os.Handler.dispatchMessage(Handler.java:112)
error	17:20:46.81		at android.os.Looper.loop(Looper.java:216)
error	17:20:46.81		at android.app.ActivityThread.main(ActivityThread.java:7625)
error	17:20:46.81		at java.lang.reflect.Method.invoke(Native Method)
error	17:20:46.81		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
error	17:20:46.81		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
error	17:20:46.81	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.content.LocusId" on path: DexPathList[[zip file "/data/user/0/com.xx.xx/files/ShadowPluginManager/UnpackedPlugin/sample-manager/94e7c6ba3f8e52825d89b1d41c4e2972/plugin-debug.zip/sample-runtime-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.xx.xx/files/ShadowPluginManager/UnpackedPlugin/sample-manager/lib/CC5EF10D-D60F-40F8-ABDD-879603FE2EF0_lib, /system/lib, /product/lib]]
error	17:20:46.81		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
error	17:20:46.81		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
error	17:20:46.81		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
error	17:20:46.81		at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:86)
error	17:20:46.81		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
error	17:20:46.81		... 25 more
error	17:20:46.81		Suppressed: java.lang.ClassNotFoundException: Didn't find class "android.content.LocusId" on path: DexPathList[[zip file "/data/user/0/com.xx.xx/files/ShadowPluginManager/UnpackedPlugin/sample-manager/94e7c6ba3f8e52825d89b1d41c4e2972/plugin-debug.zip/sample-loader-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.xx.xx/files/ShadowPluginManager/UnpackedPlugin/sample-manager/lib/CC5EF10D-D60F-40F8-ABDD-879603FE2EF0_lib, /system/lib, /product/lib]]
error	17:20:46.81			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
error	17:20:46.81			at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:79)

----------------------------------
查了下 LocusId 是Android Q 新增的属性，as 的环境是 4.1.1， compileSdkversion 29  targetSdkversion 29 。请问应该怎么解决呢？ 
谢谢

**Comment by shifujun** [comment]
从堆栈上写的那点英文猜测，就是代码有反射这个类的逻辑，那在低版本系统上找不到这个类不是很正常么。

你可以尝试在shadow的sample上接入这个SDK，如果能复现问题，就把代码push上来我看看。

**Comment by LanJD** [comment]
我也遇到了，插件无法注册eventbus，android api 改成28就行了，原因未知，NoClassDefFoundError发生在编译时对应的类可用，而运行时在Java的classpath路径中，对应的类不可用

**Comment by YanYoJun** [comment]
你好，解决了吗？我这里遇到一样的问题，就是插件中集成EventBus框架就会有问题
implementation 'org.greenrobot:eventbus:3.2.0'
代码中EventBus.getDefault().register(this);
必现

**Comment by YanYoJun** [comment]
小米6手机。

**Comment by shifujun** [comment]
这个问题我是能复现的，在API 28的虚拟机上。

问题应该是由于EventBus在反射上的错误实现导致的。即使不用Shadow，只要那个register的Activity声明了类似于
```
public void setLocusContext(LocusId arg0, Bundle arg1) {}
```
的方法都会有问题。这个方法是Shadow在模仿新版本的Android Activity加上的。虽然这个`LocusId`在低版本手机上找不到，但是低版本手机也不会调用这个方法，因此不会有问题。

**Comment by shifujun** [comment]
可以通过在插件里自己定义这个`android.content.LocusId`类型来workaround。在高版本手机上，这个类型会由于双亲委派逻辑而不会被插件加载到。

**Comment by YanYoJun** [comment]
嗯嗯，明白了，多谢。

**Comment by weithink** [comment]
> 嗯嗯，明白了，多谢。

怎么自己定义这个类型？需要路径和android.content.LocusId保持一致么？

**Comment by weithink** [comment]
> 可以通过在插件里自己定义这个`android.content.LocusId`类型来workaround。在高版本手机上，这个类型会由于双亲委派逻辑而不会被插件加载到。
怎么自己定义这个类型？需要路径和android.content.LocusId保持一致么？

**Comment by xixi6999** [comment]
eventbus 升级3.2.0可以规避这个问题

**Comment by aminey555** [comment]
感谢！



在 2021-08-16 11:25:26，"xixi6999" ***@***.***> 写道：

eventbus 升级3.2.0可以规避这个问题

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhuqichao** [comment]
> 可以通过在插件里自己定义这个`android.content.LocusId`类型来workaround。在高版本手机上，这个类型会由于双亲委派逻辑而不会被插件加载到。

实测插件里定义无效，需要在runtime的实现里定义
