### ISSUE TITLE
多工程打包成多插件，多插件如何加载

### ISSUE THREAD

**Issue by android-sz-coder** [Tencent/Shadow#461]
不同uuid的插件a,插件b均有自己的loader和runtime，注册的代理组件名称不相同，在宿主中加载插件a，可以正常运行，此时在宿主中再去启动插件b的组件，报找不到对象的组件，提示没有在androidmaniest中注册，插件a,插件b分别在不同的子进程中，想请教下两个问题
AndroidRuntime(10356): java.lang.RuntimeException: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.kysy/com.example.plugin_shadow_apk.MainActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime(10356):        at com.example.myplugindemomanager.RealPluginManager$1.run(RealPluginManager.java:119)
E/AndroidRuntime(10356):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(10356):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(10356):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(10356): Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.kysy/com.example.plugin_shadow_apk.MainActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime(10356):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
E/AndroidRuntime(10356):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
E/AndroidRuntime(10356):        at android.app.Activity.startActivityForResult(Activity.java:3788)
E/AndroidRuntime(10356):        at android.app.Activity.startActivityForResult(Activity.java:3749)
E/AndroidRuntime(10356):        at android.app.Activity.startActivity(Activity.java:4059)
E/AndroidRuntime(10356):        at android.app.Activity.startActivity(Activity.java:4027)
E/AndroidRuntime(10356):        at com.example.myplugindemomanager.HostPluginManager.startPluginActivity(HostPluginManager.java:106)
E/AndroidRuntime(10356):        at com.example.myplugindemomanager.RealPluginManager$1.run(RealPluginManager.java:117)
E/AndroidRuntime(10356):        ... 3 more

想问下这个是什么原因造成的，是加载插件b的runtime/loader失败了吗，应该怎么解决呢

**Comment by shifujun** [comment]
设计本来如此，Wiki中有一篇：[Shadow对插件包管理的设计](https://juejin.cn/post/6844903893130821640) 可以看一下。

**Comment by android-sz-coder** [comment]
@shifujun  谢谢你  这两天撸了下源码，解决了我的问题，多插件多进程得保证有多个pluginmanager,共用一个pluginmanager是不可以的，改成多个pluginmanager就好了

**Comment by vinaiso** [comment]
> @shifujun 谢谢你 这两天撸了下源码，解决了我的问题，多插件多进程得保证有多个pluginmanager,共用一个pluginmanager是不可以的，改成多个pluginmanager就好了

用一个manager也可以加载不同进程并且不同uuid的插件，不过需要改一下shadow源码，就可以实现

**Comment by hpuhsp** [comment]
@android-sz-coder  想问下你这个问题是怎么处理的？我这边在宿主App中配置多个pluginManager依然报错。

**Comment by hpuhsp** [comment]
@android-sz-coder  通过修改pluginManager来实现一个管理所有插件加载可以吗？不知道你有没有尝试过呢？

**Comment by longrenzhut** [comment]
@android-sz-coder 大佬我也这样实现，第一次进来正常依次打开2个，但是退出app，第二次进来，第一个插件A 可以打开，第二个插件B提示上面同样的错误

**Comment by chenjinguang** [comment]
@longrenzhut 这两天正在看shadow，也有相同的问题，楼上最近解决了吗

**Comment by pangliang071** [comment]
@shifujun 能否在maven下面再增加一个插件，实现一个宿主加载多个插件的功能呢？不胜感激。
