### ISSUE TITLE
什么时候发布release版本

### ISSUE THREAD

**Issue by tanlimin201** [Tencent/Shadow#462]

**Comment by shifujun** [comment]
Shadow开源主要是技术交流，并没有提供接入服务的准备，所以提供一个稳定的release二进制版本并没有太大意义。

如果主要关注的是代码的稳定性，可以认为最初开源的代码就是release版的。完全不是beta或者alpha那种质量不稳定的概念。Shadow对外开源时就已经稳定运行了很久了。我们内部用的代码和外部开源的代码是一致的。

从开源至今后续的commit修改都考虑了动态修复的设计，都可以正常更新发布于现网版本之上，不存在不兼容的升级。

**Comment by tanlimin201** [comment]
既然是稳定的，个人认为就可以发布个较稳定的release 版本，这样也可以给大家参考

**Comment by shifujun** [comment]
已经将最新代码发布为`2.1.0`版本，二进制传到Github Packages了。使用时可以参考maven sample例子中的用法。

https://github.com/Tencent/Shadow/blob/f6d75266a04fec6cdbb0b3a11179f91ff08a63b4/projects/sample/maven/host-project/build.gradle#L20-L29
