### ISSUE TITLE
PluginContainerContentProvider

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#463]
想咨询下版主，在插件中使用ContentProvider, PluginContainerContentProvider是如何启动的。这个原理是啥。

**Comment by weikaiyun** [comment]
![image](https://user-images.githubusercontent.com/20124328/104114226-e3355b00-533c-11eb-951a-a101ac2e4173.png)
有个笔误，可以修正下。

**Comment by shifujun** [comment]
`PluginContainerContentProvider`是一个正常注册在宿主Manifest里的`ContentProvider`，所以它的启动跟正常的`ContentProvider`没有区别。Shadow要做的就是将插件的`ContentProvider`的`authority`和`uri`与宿主里的这个代理的`PluginContainerContentProvider`的`authority`和`uri`做一个映射关系，做一些转换。把这些转换的代码以字节码编辑的形式插入到插件原有的代码处。

你可以Debug一下sample的`ContentProvider`例子就清楚了。

`ContentProvider`与其他组件有一点不一样的是它会比`Application`启动的更早。

**Comment by weikaiyun** [comment]
好的 谢谢版主
