### ISSUE TITLE
关于AndroidManifest动态合并的问题

### ISSUE THREAD

**Issue by mickyliu945** [Tencent/Shadow#464]
我们项目在插件中使用了第三方库，第三方库初始化的时候会检测AndroidManifest中是否有他们的Activity，Provider是否已注册。  我在插件中已经注册了SDK所需的Activity和Provider，但是还是会提示没注册。
   请问这种情况有没有办法解决呢？

**Comment by shifujun** [comment]
插件的Manifest中注册的信息，正常来说只有插件框架会去读取，其他代码是不会主动拿到的。

如果这个第三方库读取Manifest的方案是标准的API，我们可以看看能否通过字节码修改使它读到插件的Manifest信息。

你可以fork之后在sample里写一个这种例子，我看看能否支持上。

**Comment by mickyliu945** [comment]
@shifujun 
第三方SDK通过 packageManager.queryContentProviders(a.getApplicationInfo().processName, a.getApplicationInfo().uid, 131072) 获取Provider
通过context.getPackageManager().resolveActivity(intent, 65536) 获取是否已注册Activity

**Comment by shifujun** [comment]
已经简单支持了这两个API，如果还不能满足需求，可以参考我的代码自行补充。欢迎提PR贡献代码。
