### ISSUE TITLE
宿主so abi

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#466]
![image](https://user-images.githubusercontent.com/20124328/104543931-95349600-5661-11eb-8b98-dcc4cf649d8e.png)
版主，就是有个问题咨询下， 我怎么确定宿主so的abi呢

**Comment by shifujun** [comment]
宿主不是你自己的应用吗？apk里可能包含多种ABI以兼容模式运行。在代码中查询可以参考：https://stackoverflow.com/a/46751394/11616914

wiki中有一段之前写的说明也可以参考一下：https://juejin.cn/post/6844903893130821640#heading-2

**Comment by weikaiyun** [comment]
![image](https://user-images.githubusercontent.com/20124328/104563918-3da82180-5685-11eb-8cf0-16979df10119.png)
看到了可以这样获取 abi。 谢谢版主。

**Comment by shifujun** [comment]
你得注意一下，这个截图里的方法返回的ABI是这台手机的ABI，或者是最合适的ABI。很可能是arm64的，但是宿主apk可能没有arm64的so，它只有armeabi的so，所以宿主安装时会使用armeabi。这时插件也得使用armeabi才行，而不能根据系统返回的arm64使用so。
