### ISSUE TITLE
aidl文件

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#467]
wiki文档说shadow中的binder接口是半手工的，版主能否附上原始的aidl文件，想自己对照着看看，这样更容易理解源码。

**Comment by shifujun** [comment]
比如`PpsBinder`,`PpsController`都不是先写了aidl文件然后修改的生成文件。而是就写了`IMyAidlInterface.aidl`那种测试aidl，然后模仿了对应生成代码的写法，直接写的`PpsBinder`,`PpsController`。

aidl生成的代码会把同进程、不同进程的实现写在一起，有if-else分支。我手写的就省略了同进程的分支，简化代码，所以同进程也会走序列化过程，这样也有目的地使测试简化，不会因为是否在同一个进程走不同逻辑。

aidl生成的代码还会把Binder子类和控制类写在一个文件里，我也拆开了，都是为了使代码稍微清晰一点，可能也只是更符合我的编码习惯而已。

其余的主要是模仿生成代码中对于Parcel类型的操作，以及如何序列化Exception，如何传递Exception这些。不用aidl生成的主要原因就是aidl不支持自定义Exception。
