### ISSUE TITLE
FileProvider.getUriForFile

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#468]
版主，我调试这个函数的时候， 发现sample依赖的FileProvider被ContentProviderTransform编辑了，我有个疑问，v4包会打包到插件中吗？

**Comment by shifujun** [comment]
v4包作为一个普通的第三方库，是否打包，Shadow是不会干预的。sample中`sample-app-lib/build.gradle`声明的`implementation 'com.android.support:support-v4:27.1.1'`正常就会使v4被传递依赖，进而打包进`sample-normal-app`。所以相同配置的`sample-plugin-app`也会打包v4的。

这些打包逻辑，shadow不会干预的。
