### ISSUE TITLE
AutoMakeMissingClassPool

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#469]
版主有个困惑，在字节码编辑时，为啥要自动创建缺失类，我们编辑的类不应该都存在吗？

**Comment by weikaiyun** [comment]
我平时做字节码插桩都是用的ASM，javaassist可能有自己的逻辑？

**Comment by shifujun** [comment]
看代码的时候不光要期待注释会给出一些解释，也应该参考相关的提交记录。看这个类的提交记录就能很容易找到：fix #411，fix #451。看这两个Issue就知道当时为什么引入这个类了。

ASM和Javassist的选择不太重要，我当时也就是随便找的，能满足需求就好。Javassist来自Jboss，也是我比较信任的原因。

**Comment by weikaiyun** [comment]
嗯嗯 我后面注意下。不过我这三周基本看完了源码 对着版主的wiki看源码 外加调试 真的是能够完全看懂源码的。要是很多开源库都能像版主一样讲解这么细致就好了。点赞。
