### ISSUE TITLE
Fragment处理

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#471]
版主，我查看源码，ShadowFragmentSupport和FragmentSupportTransform是对android.app.Fragment进行处理，这样使用AndroidX和support包中的fragment进行fragmentStartActivity调用时不会有问题吗？比较疑惑。

**Comment by shifujun** [comment]
support包的Fragment不是`android.app.Fragment`的子类，而是完全重新实现的Fragment类，你可以认为就是业务自己写的普通类，所以不用特殊处理。support包新写的Fragment类是靠一个继承了`android.app.Fragment`的ReportFragment监听了生命周期通知来实现的。这个ReportFragment会被Shadow处理，所以能正常工作。

你可以仔细Debug调试一下这些Fragment的工作过程。

**Comment by weikaiyun** [comment]
明白了 谢谢。

**Comment by weikaiyun** [comment]
另外我看demo中 fragment是直接使用的android.app.Fragment，平时的项目中会有直接使用android.app.Fragment吗，我见过的项目要不使用support包，要不就使用androidx包

**Comment by shifujun** [comment]
是否直接使用系统的Fragment实现是业务的自身考虑。Shadow只是帮助业务代码以动态加载方式运行时，处理与系统API交互不正常的地方。

**Comment by weikaiyun** [comment]
嗯嗯 谢谢。
