### ISSUE TITLE
怎么去掉从宿主跳转到插件Activity的过度动画？

### ISSUE THREAD

**Issue by mickyliu945** [Tencent/Shadow#473]
我想去掉宿主跳转到插件到的过度动画，目前做法：
1. ShadowActivity里的 hostActivityDelegator.overridePendingTransition(0, 0); 强制去掉过度动画
2. 在宿主中EnterCallback的onEnterComplete回掉中finish掉当前Activity。并在重写finish方法中调用了overridePendingTransition(0,0)

按照上面这样做了修改之后从宿主跳转到插件Activity还是有过度动画。

**Comment by shifujun** [comment]
插件Activity有一个壳子Activity，插件Activity不是一个真的Activity，它只是宿主中壳子Activity代码的一部分。比如sample中的`PluginDefaultProxyActivity`。所以你的需求也不过是一个正常的app中两个Activity之间的跳转而已。

如果有Bug，可以根据这个思路debug一下。

https://github.com/Tencent/Shadow/blob/2b494707308b28522a73a2355b258c9b70448441/projects/sample/source/sample-host/src/main/AndroidManifest.xml#L109
