### ISSUE TITLE
插件是AndroidX，宿主是AppCompat支持吗？

### ISSUE THREAD

**Issue by WangcWj** [Tencent/Shadow#474]
目前遇到这样的报错：Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory。

**Comment by shifujun** [comment]
AndroidX和AppCompat本身都是普通的第三方库，一般来说会因为默认的ClassLoader隔离使宿主和插件没有冲突。就算是同一个SDK的不同版本同时用在插件和宿主里，也会因为ClassLoader隔离而正常使用。

你遇到的报错，我估计只能出现在插件通过白名单访问了宿主的类的情况下。这种情况下，插件不能复用那些与Shadow干预的系统API交互的类。也就是你遇到的ComponentFactory。

更好理解就是Activity了。Shadow之所以存在，就是因为简单的用ClassLoader加载Activity是不能正常运行的。所以Shadow通过字节码编辑改写了插件中Activity相关API的代码。如果Activity API就是系统的API的全部，Shadow的作用就是将插件与系统API之间隔离开，Shadow作为中间件与两边交互，使代码正常工作。对于这些API，如果插件直接去复用宿主中本该被Shadow干预，又没有被干预的类，肯定是无法正常工作的。ComponentFactory就属于这类。

对于业务自己的代码，比如插件想复用宿主Activity的类，建议重构这个Activity，变继承为组合，使需要复用的逻辑成为普通类。

对于第三方库可能就没什么好办法了。不过具体到AndroidX的设计，大部分也都有组合的使用接口，如果能避免不能复用的类也是可行的。

**Comment by WangcWj** [comment]
不明觉厉！感谢大佬~

**Comment by WangcWj** [comment]
刚又看了下代码，这边还有个疑问：
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            pluginInfo.appComponentFactory = packageArchiveInfo.applicationInfo.appComponentFactory
        }
这边打日志看了一下，返回的就是androidx.core.app.CoreComponentFactory。

**Comment by shifujun** [comment]
> 刚又看了下代码，这边还有个疑问：
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
> pluginInfo.appComponentFactory = packageArchiveInfo.applicationInfo.appComponentFactory
> }
> 这边打日志看了一下，返回的就是androidx.core.app.CoreComponentFactory。

这可能是没考虑到的bug。如果可以在sample中复现，可以把代码push上来看看。

**Comment by shifujun** [comment]
应该和这个问题一样：
https://github.com/Tencent/Shadow/issues/529#issuecomment-862977957

就是runtime.apk里打包了`androidx.core.app.CoreComponentFactory`。

**Comment by loslink** [comment]
> > 刚又看了下代码，这边还有个疑问：
> > if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
> > pluginInfo.appComponentFactory = packageArchiveInfo.applicationInfo.appComponentFactory
> > }
> > 这边打日志看了一下，返回的就是androidx.core.app.CoreComponentFactory。
> 
> 这可能是没考虑到的bug。如果可以在sample中复现，可以把代码push上来看看。

大佬，是不是没把androidx.core.app.CoreComponentFactory转换成shadow类，什么时候可以打个补丁，我也遇到这个问题项目跑不起来

**Comment by shifujun** [comment]
> 是不是没把androidx.core.app.CoreComponentFactory转换成shadow类

这是已经支持的功能。如果你遇到bug，可以尝试在sample上做最小改动复现。然后push上来看看。
