### ISSUE TITLE
关于动态加载xml布局文件的问题

### ISSUE THREAD

**Issue by hyandroid** [Tencent/Shadow#475]
请教一下，有什么办法可以在运行时动态加载外部xml文件呢？比如网络下载过来的，用来动态替换当前布局。大佬有什么思路吗？

**Comment by shifujun** [comment]
简单实现的话，可以参考shadow的manager的loading view那种实现。就是一个apk里面有一个view，view所需的资源，包括xml，都在apk里。Android系统是可以动态加载这个apk，用它构造一个context，new出来里面的view的正常使用的。这个不需要shadow，因为Android系统不限制view的动态加载。

但如果这个view的资源和其他apk又有关系，就变得麻烦了许多。Android有这方面的设计，但都是面向系统的，没有太友好的api可以使用。比如用apk构造context时还允许添加更多的apk作为共享资源，配合资源id分区使用。

建议不要把Layout动态化搞太复杂，直接用web，或者native写好一些布局支持切换。这样的维护成本都会低一些。

**Comment by hyandroid** [comment]
多谢指导，正在做这方面的研究。

**Comment by hyandroid** [comment]
再次打扰，研究时发现插件assets文件夹下的资源无法通过resources.getAssets().open("file.png")加载，会报错FileNotFound，请教下这个怎么解决呢？

**Comment by shifujun** [comment]
> 再次打扰，研究时发现插件assets文件夹下的资源无法通过resources.getAssets().open("file.png")加载，会报错FileNotFound，请教下这个怎么解决呢？

新问题就单独提issue吧，加上在sample上复现问题的例子。

**Comment by shifujun** [comment]
![image](https://user-images.githubusercontent.com/3535204/110094016-4d66fb00-7dd6-11eb-955e-2b270372eae1.png)
我试了一下在插件里`getResources().getAssets().list("web")`是可以看到插件的assets：test.html的。

**Comment by hyandroid** [comment]
抱歉，确实可以，后来发现是名字写错了。
