### ISSUE TITLE
一直卡在某个打包task中

### ISSUE THREAD

**Issue by o19871109** [Tencent/Shadow#476]
onfigure project :modules-base:tp-view
WARNING: DSL element 'annotationProcessorOptions.includeCompileClasspath' is obsolete.
It will be removed in version 5.0 of the Android Gradle plugin.
It does not do anything and AGP no longer includes annotation processors added on your project's compile classpath
<============-> 94% EXECUTING [19m 3s]
什么原因呢

**Comment by shifujun** [comment]
如果你不把可复现问题的项目push上来，应该很难帮到你。

你确定不加Shadow是可以快速正常构建的吗？是的话，应该是Shadow在Transform时比较慢。可能命中了一些耗时的逻辑。Transform时要查找很多目标方法的调用，这个很耗时。可以Debug一下Transform的过程，看看卡在哪了。搜一下怎么debug Gradle插件就行了。
