### ISSUE TITLE
Didn't find class "com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity" on path:

### ISSUE THREAD

**Issue by ClarkRep** [Tencent/Shadow#477]
华为的Android 10、11系统偶现  java.lang.ClassNotFoundException，请问是不是有适配问题？

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/2b494707308b28522a73a2355b258c9b70448441/projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/HostApplication.java#L52-L57

看看是不是漏了这个调用。没有这个调用的话，杀了插件进程，再通过最近程序页面直接打开之前的插件页面就会出现这种Crash。

DynamicRuntime方案是hack实现，但是从来没遇到过兼容性问题。另外，完全可以放弃DynamicRuntime，直接把runtime.apk的内容打包到宿主里。那里面的代码没什么逻辑，而且之前动态更新它的主要原因是那些Activity的代理方法实现不全。但现在Activity的代理方法已经是自动生成的，很完整了。所以更新它的需求更小了。

**Comment by zdy793410600** [comment]
这个方法调用了，只在华为10、11系统上有上报，其他手机系统没有上报过。
