### ISSUE TITLE
加载sample-plugin时它的依赖sample-common还没有加载

### ISSUE THREAD

**Issue by listen2code** [Tencent/Shadow#478]
"com.tencent.shadow.core.loader.exceptions.LoadApkException: 加载sample-plugin时它的依赖sample-common还没有加载"
sample-plugin里面只有plugin-apk，sample-common里面有runtime和loader，在sample-plugin的gradle里，设置了"dependsOn=sample-common"，如果手动先加载sample-common，再加载sample-plugin是没有问题的；如果不加载sample-common，直接加载"sample-plugin"就会报上面的错误，是否可以在加载sample-plugin的时候，发现没有加载common，先自动加载"sample-common"，还是这个逻辑需要业务方，在每个加载sample-plugin的地方自己处理？

**Comment by shifujun** [comment]
是需要业务方自己在manger里写这个逻辑的。现有的代码提供好了插件是否已经加载的查询能力以及加载能力，什么时候加载对于业务来说是特别需要定制的逻辑。通常来说不太可能是发现依赖的插件没加载再去自动加载，这样太慢了，加载插件是一个高IO的操作。一般来说都要根据具体的业务在合适的时机提前加载，甚至提前做一些登陆逻辑。

**Comment by listen2code** [comment]
> 是需要业务方自己在manger里写这个逻辑的。现有的代码提供好了插件是否已经加载的查询能力以及加载能力，什么时候加载对于业务来说是特别需要定制的逻辑。通常来说不太可能是发现依赖的插件没加载再去自动加载，这样太慢了，加载插件是一个高IO的操作。一般来说都要根据具体的业务在合适的时机提前加载，甚至提前做一些登陆逻辑。

其实每次加载sample-plugin的之前，都需要固定的加载sample-common就可以了，没加载过就加载了，有加载过就直接加载plugin了。我以为build.gralde里面配置了dependsOn就会自动加载一次，目前是直接报错了，因为想要common预先加载一次，可以放到APP启动的时机，不过没办法保证加载plugin之前comon已经加载完了，所以，需要在每个加载plugin的地方，手动check一次，就会比较麻烦。

**Comment by listen2code** [comment]
又比如，A dependsOn B，B dependsOn C，这种链条比较长的依赖，业务方写起来就比较麻烦， 框架层如果有写掉的话是最好的，类似于Startup。
