### ISSUE TITLE
插件包放在/data/local/tmp/目录下是有什么讲究吗？

### ISSUE THREAD

**Issue by liujunhongz** [Tencent/Shadow#48]
是否正式上线包也建议放于该目录

**Comment by shifujun** [comment]
确实有讲究。这个tmp目录是一个Android系统的特殊目录。这个目录的特点是adb可以直接push写入。app都能读取，但不能写入。同时这个目录还是手机的内置存储，可以直接用DexClassLoader加载这个目录中的apk，而sdcard不行。所以，如果我们用adb push到sdcard上，想动态加载还要将apk再复制到应用的data目录才行。

正是环境肯定没法用这个目录，因为应用没有这个目录的写入权限。建议应用把插件包下载到宿主的data私有目录中，以保证数据安全，其他应用不能篡改。

**Comment by liujunhongz** [comment]
嗯  好的  谢谢

**Comment by qualcommcd** [comment]
good,thanks
