### ISSUE TITLE
FragmentSupportTransform

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#481]
![image](https://user-images.githubusercontent.com/20124328/108586702-18e15100-738b-11eb-93e7-4cf348c7de45.png)
想问下为啥只有这个transform里面需要红框里面的importPackage。

**Comment by shifujun** [comment]
因为只有这个Transform用了`CtMethod.make`这样的编译Java源码的API。这是编译源码时需要的import。

https://github.com/Tencent/Shadow/blob/a312f4447ea4c1066d977588858808ea542358b2/projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/FragmentSupportTransform.kt#L152-L157
