### ISSUE TITLE
Plugin2ProcessPPS

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#486]
demo中 先启动插件app，然后切换启动插件app2, Plugin2ProcessPPS并不会启动

**Comment by shifujun** [comment]
FastPluginManager不是SDK的代码，上次也是PR接受的Plugin2的加入，所以没太注意这种场景。

你可以把`mPpsController`改成一个map，用`getPluginProcessServiceName(partKey)`作key。如果能调试通的话，欢迎提PR完善sample。

**Comment by weikaiyun** [comment]
好的 我试试。
