### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by qweawdqq** [Tencent/Shadow#488]
建议录一个视频教程，相比于复杂的文档，这样不用消耗太多时间精力，大家也更容易理解与学习。可以讲一下原理及如何使用，根据实际工作遇到的问题给大家讲讲，例如进行在线修复BUG等等的

**Comment by shifujun** [comment]
视频教程是会更快速传递信息，但这种信息的传递是单向的。Shadow开源主要的目的是技术交流。开源世界的交流需要可追溯的文字记录，并且以代码为中心。

一般开源项目都难以有专门的人力维护运营，Shadow也是。所以从一开始就有这种准备，所以把可用的时间都花在了项目的可调试性改进上。作为一个同时应用了编译期插件、动态加载、十几个编译模块的SDK，Shadow的source sample运行起来可以Debug断点Shadow的任何一处代码。希望和大家交流时，大家可以方便的修改sample，调试任何代码。

感谢建议，精力有限，请理解。
