### ISSUE TITLE
关于宿主代码复用问题

### ISSUE THREAD

**Issue by panwankun** [Tencent/Shadow#489]
大佬你好，最近在尝试接入shadow到业务工程中，在使用中以下问题希望大佬解惑：

因为宿主是比较大的原生端容器，包含了很多基础的SDK，这部分包体积大小不容忽视，所以在做插件的时候是希望尽量能复用
的，以提高插件的到达率，但是shadow通过代理的方式修改了一些对于Activity、Fragment等API的调用，而且这部分修改是通过gradle插件作用于插件打包的，导致有一些基础类和宿主中的类同名但是实际代码则不同。一方面很难找出哪些类做了修改，把它们找出来打出最小的包作为基础插件给到业务方进行复用，另一方面，插件和宿主部分类通过修改classloader的双亲委派进行了隔离，部分类又进行了复用，从而导致经常遇到ClassCastException和NoSuchMethodException异常。

所以想问一下把插件和宿主**完全隔离**，尽量少的复用宿主类但是会导致插件**冗余的代码下发**，还是尽量多的**复用宿主**基础SDK同时尽量保证耦合的类也同时复用，减少Exception风险，在这两种策略之间你们目前主要是采取哪一种，能兼顾到复用率高而且风险小吗，是否可以把插件的影响范围只限定在业务代码中，避免对于基础三方SDK的修改？

**Comment by shifujun** [comment]
你说的问题是非常普适性的，在我们的业务中肯定也是存在的。我们不说Shadow的技术方案，单说支持动态加载代码的Java以及面向对象的抽象接口这两个方面。不管是什么机制实现的动态加载，要么反射的形式去动态调用代码，要么提前约定好调用的接口，以接口去调用。接口的方式由于有编译期检查，以及调用指令是编译期决定的关系，可维护性和性能都是更好的。所以我们的结论就是通过接口调用是更好的消费动态加载的代码的最好方式。

然后说Shadow的技术方案其实就是通过字节码编辑，把插件的代码变成了一种宿主和插件之间的自定义接口的调用。最终目标是插件与系统API不直接交互。这是解决Android的部分系统API不兼容动态加载代码的方案。所以，如果系统API到处都不与动态加载代码兼容，那么Shadow的这种技术方案就要做更多更多的字节码编辑了。

宿主和插件，插件和插件之间的代码复用，其实也都是动态加载代码的调用问题。只需要在它们之间约定好调用的接口就可以了。在设计接口时自然是要减少类型的引入，这是一般的设计原则。所以不在这些接口上使用Activity等Android系统有动态加载代码限制的类型也很正常的选择。

也就是说，不能简单的把第三方SDK分分组就编译成各种插件供其他插件调用。你需要定义一套自己的接口类型，让各个第三方SDK实现这些接口，在自己的插件内部与Android系统API进行交互。插件之间见到的类型应该都是你自己定义的类型。这样才能避免这个方案被第三方SDK的接口中引入的一层又一层的类型引用破坏类型隔离。

**Comment by panwankun** [comment]
大佬你好，非常感动你能给出如此详细的回答。根据你说的我的理解是如果相对一个SDK做复用，最好是需要加一层接入层，避免字节码插件对于SDK的修改，这确实是比较完美的方式，但是对于我们来说成本比较大，目前我们维护的很多插件都没有这样一个使用三方SDK的良好习惯，改造成本和推广阻力都比较大。在实践中，我们尽量把插件和宿主两套环境隔离开，把基础SDK封装到一个基础插件里面，因为同样是经过字节码插件修改过的，所以给到别的插件使用是兼容的。我们必须谨慎的配置白名单，减少和宿主之间的耦合。再次感谢你的耐心解答。

**Comment by shifujun** [comment]
如果引入接入层，字节码编辑也会修改第三方SDK的。只是接入层就不会被修改了，有利于跨Classloader复用。

对于你说的情况，其实也可以考虑利用字节码编辑技术修改遍布app各处的第三方SDK调用，将那些接口和数据类型替换成接入层。Shadow就是这样的思路。当然这还是不如在源码层面重构。

**Comment by panwankun** [comment]
感谢，确实是很好的思路，我顺着你的指导尝试一下。

**Comment by Caij** [comment]
代码复用的难点宿主和插件混淆规则不一样，导致插件中找宿主的类找不到，设计接口然后keep住的确是可以，但是在一个庞大的老的项目中实践起来基本不可能，VirtualAPK 是直接 Kepp 主共同的代码. Atlas 使用的是 DexPatch 技术.  看起来直接宿主和插件隔离是比较容易的做法。

**Comment by haizhiyun** [comment]
@shifujun @SpenceAcc  请教个问题，使用这个框架，公共依赖的库都是打入每个插件了吗，比如一些公共依赖的Util类，第三方sdk 诸如Androidx 系列。。
（我看到virtualApk或者atlas 之类的库，是直接依赖公共库，打插件时，将host 代码从插件中剔除去，如果本框架要实现直接依赖host，有什么难点吗。（因为现有的项目公共依赖比较大））
感谢！
