### ISSUE TITLE
请问一个Activity中加载多个Apk中的View，这个功能是怎么实现的？我看demo里好像没有这个使用方式。

### ISSUE THREAD

**Issue by ClarkRep** [Tencent/Shadow#490]

**Comment by shifujun** [comment]
`EnterCallback`返回的那个View就是manager.apk中的View。它是`SamplePluginManager`中构造的。

这个实现的时候不用什么字节码编辑，就是构造一个apk对应的Context就可以了。

`ManagerImplLoader`在加载manager.apk时构造了一个`ChangeApkContextWrapper`。

**Comment by zdy793410600** [comment]
这个是加载PluginManager.apk的View，可以加载插件里面的View么？

**Comment by shifujun** [comment]
可以啊，你觉得有什么区别吗？

**Comment by zdy793410600** [comment]
加载PluginManager里面的view，因为本身就有接口映射，所以可以很简单处理。
但是加载插件里的view，需要拿到插件的classloader，将插件里的view映射成宿主的，这样成本就高不少里，而且如果插件是独立进程的话，主进程还是没把发拿到子进程插件的view。
