### ISSUE TITLE
是否支持免安装运行

### ISSUE THREAD

**Issue by rishli** [Tencent/Shadow#491]
是否支持免安装直接运行apk，像VirtualAPP框架一样的功能？

**Comment by wangzhanxian** [comment]
5分钟看了一下代码，感觉不能像VA一样，这个插件apk是需要你按照插件的规则去开发的，如果是任意的apk是无法安装运行的

**Comment by shifujun** [comment]
Android插件这个领域，有两类技术：
1. 免安装运行别人的应用，用于沙箱场景，多开场景。这种技术需要支持apk不修改就能免安装运行。
2. 免安装运行自己家的应用，用于快速启动和更新应用，利用流量入口。这种技术只需要app的源码不用大量修改就可以了。

Shadow是后一种技术。前一种技术往往需要使用非公开接口，而我们的需求又是后一种的，所以我们开发了Shadow替代了原有方案。

**Comment by rishli** [comment]
谢谢

**Comment by whiteopaper** [comment]
> Android插件这个领域，有两类技术：
> 
> 1. 免安装运行别人的应用，用于沙箱场景，多开场景。这种技术需要支持apk不修改就能免安装运行。
> 2. 免安装运行自己家的应用，用于快速启动和更新应用，利用流量入口。这种技术只需要app的源码不用大量修改就可以了。
> 
> Shadow是后一种技术。前一种技术往往需要使用非公开接口，而我们的需求又是后一种的，所以我们开发了Shadow替代了原有方案。

大大，如果是开发一个类似应用市场的应用，我能理解为Shadow不支持打开非自家（未注册在清单文件中）的第三方插件应用吗

**Comment by shifujun** [comment]
> > Android插件这个领域，有两类技术：
> > 
> > 1. 免安装运行别人的应用，用于沙箱场景，多开场景。这种技术需要支持apk不修改就能免安装运行。
> > 2. 免安装运行自己家的应用，用于快速启动和更新应用，利用流量入口。这种技术只需要app的源码不用大量修改就可以了。
> > 
> > Shadow是后一种技术。前一种技术往往需要使用非公开接口，而我们的需求又是后一种的，所以我们开发了Shadow替代了原有方案。
> 
> 大大，如果是开发一个类似应用市场的应用，我能理解为Shadow不支持打开非自家（未注册在清单文件中）的第三方插件应用吗

只要第三方插件应用也经过Shadow transform修改过就行。

**Comment by whiteopaper** [comment]
> 

Sample的Demo是经过transform修改吗？

因为我看到有接入文章中提到需要在AndroidManifest.xml中提前写好插件的ID，似乎不满足应用市场宿主App不更新自身情况下就可以打开任意插件应用的需求

目前对Shadow的了解还很浅，希望大大解惑！

**Comment by shifujun** [comment]
> > 
> 
> 
> 
> Sample的Demo是经过transform修改吗？
> 
> 
> 
> 因为我看到有接入文章中提到需要在AndroidManifest.xml中提前写好插件的ID，似乎不满足应用市场宿主App不更新自身情况下就可以打开任意插件应用的需求
> 
> 
> 
> 目前对Shadow的了解还很浅，希望大大解惑！

建议主要阅读和调试源码，wiki也可以看看。
