### ISSUE TITLE
请教一个sample/source/sample-host的buidl.gradle中的一个小问题

### ISSUE THREAD

**Issue by alex11235813** [Tencent/Shadow#494]
作者大大你好，我刚开始学习gradle。看shadow源码过程中一直没搞清楚“implementation 'com.tencent.shadow.core:common'”，这种写法是怎么依赖到源码的呢？

**Comment by shifujun** [comment]
这是复合构建：https://docs.gradle.org/current/userguide/composite_builds.html

Gradle支持的一个Gradle工程依赖另一个Gradle工程的构建产物的能力。要理解为什么需要它，你需要了解Gradle构建分为3个阶段。

**Comment by alex11235813** [comment]
赞，回复效率好高。我先简单理解是符合构建时依赖sub projects中module的一种方式，之后再慢慢研究。感谢。
