### ISSUE TITLE
广点通sdk问题

### ISSUE THREAD

**Issue by wangzhenglei** [Tencent/Shadow#495]
广点通sdk需要在插件的AndroidManifest.xml中注册DownloadService，但是注册后，sdk表示未找到该服务
![企业微信截图_1616388848425](https://user-images.githubusercontent.com/1657703/111942501-61b53280-8b0e-11eb-886a-2eadf3418c7d.png)
![企业微信截图_16163888914255](https://user-images.githubusercontent.com/1657703/111942516-67ab1380-8b0e-11eb-9ff6-7f3449b57ecf.png)
但是自己定义的AdService能正常调用，
请问关于三方aar包中需要在插件AndroidManifest.xml注册的四大组件要怎么处理

**Comment by shifujun** [comment]
对于系统来说，插件只是宿主代码的一部分。所以权限还是要复用宿主的权限，如果宿主没有这种权限，需要在宿主的Manifest中申请。

另外，这个SDK的实现好像用反射查找了自己的构造器，兼容不了。之前有人讨论过： #441
