### ISSUE TITLE
插件工程的Service的无法使用

### ISSUE THREAD

**Issue by superKeJi** [Tencent/Shadow#497]
插件工程中的service不是class形式，是在一个加固格式的文件（.dat文件），在插件工程运行时解压、用classloader动态加载的，现在使用Shadow时出现cannot be cast to com.tencent.shadow.core.runtime.ShadowService，请问有什么解决方法。

**Comment by shifujun** [comment]
请参考https://github.com/Tencent/Shadow/blob/2b494707308b28522a73a2355b258c9b70448441/CONTRIBUTING.md#issue
提供可以复现问题的工程供大家探讨交流。
