### ISSUE TITLE
A problem occurred configuring project ':core:common'. > Cannot access first() element from an empty Iterable

### ISSUE THREAD

**Issue by Guoshitong1** [Tencent/Shadow#498]
![1 (O4PW1_Y{AX9$K$0ES}NF](https://user-images.githubusercontent.com/62371965/112922455-18349b00-913f-11eb-8ccf-ba376bd00cd5.png)
我想知道编译时build.gradle里报的什么错，如何解决，求指教

**Comment by shifujun** [comment]
从你截图的界面上有看到 License .... not accepted. 你可能要先接受一下SDK的协议。

可以参考：
https://stackoverflow.com/a/45782695/11616914

**Comment by Guoshitong1** [comment]
> 从你截图的界面上有看到许可....不接受。你可能要先接受一下软件开发工具包(Software Development Kit)的协议。
> 
> 可以参考：
> https://stackoverflow.com/a/45782695/11616914

看完了对我的帮助不是很大，这个跟sdk权限有关吗，其实我没看懂可以详细说明一下吗，万分感谢

**Comment by shifujun** [comment]
这个跟Shadow项目应该没关系的。就是你的Android开发环境没初始化好。Android SDK安装完还要接受一个使用协议才能使用。

另外你截图中文件名都是红的，看起来没有正确配置好git，所以我也不确定你是不是改了代码。

**Comment by Guoshitong1** [comment]
> 这个跟Shadow项目应该没关系的。就是你的Android开发环境没初始化好。Android SDK安装完还要接受一个使用协议才能使用。
> 
> 另外你截图中文件名都是红的，看起来没有正确配置好git，所以我也不确定你是不是改了代码。
您好，确实没有修改代码的迹象，这个是拉取项目时候创建的.git,所以才是红色，不要介意，主要是我不知道怎么获取许可，之前敲项目时也没有这种问题。所以希望您可以指导一下

**Comment by shifujun** [comment]
那就先回归到命令行构建上看一下具体的报错吧。

Shadow是有Windows CI环境验证的，也可以参考一下：https://github.com/Tencent/Shadow/blob/464738bfb5a4cee8045e5799260d100987b49759/.github/workflows/pr-check.yml#L31-L43

**Comment by Guoshitong1** [comment]
> 那就先回归到命令行构建上看一下具体的报错吧。
> 
> Shadow是有Windows CI环境验证的，也可以参考一下：
> 
> https://github.com/Tencent/Shadow/blob/464738bfb5a4cee8045e5799260d100987b49759/.github/workflows/pr-check.yml#L31-L43

![%V`5I7}(@BL1LF%A 7K(%I1](https://user-images.githubusercontent.com/62371965/112930664-4f11ad80-914d-11eb-9f80-88b85f9c3759.png)
许可证是这样获取的没错吧，如果不是许可证的问题，我再来找您

**Comment by Guoshitong1** [comment]
> > 那就先回归到命令行构建上看一下具体的报错吧。
> > Shadow是有Windows CI环境验证的，也可以参考一下：
> > https://github.com/Tencent/Shadow/blob/464738bfb5a4cee8045e5799260d100987b49759/.github/workflows/pr-check.yml#L31-L43
> 
> ![%V`5I7}(@BL1LF%A 7K(%I1](https://user-images.githubusercontent.com/62371965/112930664-4f11ad80-914d-11eb-9f80-88b85f9c3759.png)
> 许可证是这样获取的没错吧，如果不是许可证的问题，我再来找您

![image](https://user-images.githubusercontent.com/62371965/112930830-97c96680-914d-11eb-8190-290a5ce0d37c.png)
许可证已获取

**Comment by Guoshitong1** [comment]
> 那就先回归到命令行构建上看一下具体的报错吧。
> 
> Shadow是有Windows CI环境验证的，也可以参考一下：
> 
> https://github.com/Tencent/Shadow/blob/464738bfb5a4cee8045e5799260d100987b49759/.github/workflows/pr-check.yml#L31-L43

谢谢哥，问题已解决，就是没有许可证，您可以在开源项目引导里说明这一项，给其他小伙伴一些引导。
