### ISSUE TITLE
感觉工程有点凌乱。

### ISSUE THREAD

**Issue by xuyabin521** [Tencent/Shadow#499]
感觉工程有点凌乱，能否把工程整理一下，去掉不需要的。

**Comment by shifujun** [comment]
可以举个例子，哪些是你认为所有人都不需要的代码或模块。我相信应该还是有的，只是不多。

**Comment by liupeng110** [comment]
看的很心塞

**Comment by leonnnwu** [comment]
同感，感觉作者想通过一个工程展示所有的use case。用了大量的gradle tasks，没接触过这种动态化的架构，读起来有点吃力啊。
建议拆分成小的apps，或者用settings.gradle来控制不同use case的引用。

**Comment by shifujun** [comment]
> 同感，感觉作者想通过一个sample-app 展示所有的use case。用了大量的gradle tasks，没接触过这种动态化的架构，读起来有点吃力啊。
> 建议拆分成小的apps，或者用settings.gradle来控制不同use case的引用。

大量Gradle task引入的阅读成本我理解。只是这里有些必要性。

`projects/sample/source`并不是为了展示Shadow的接入用法的，它是为了让人能方便的改写sample或者sdk的任何一处代码，都能重新编译生效而做的。那些gradle task就是为了这个目的。这里的难点在于整个编译流程涉及复合构建以及插件apk打包的相关步骤。

所以为了演示怎么接入Shadow，还专门提供了一个`projects/sample/maven`示例，这个示例没有在根settings.gradle中引入。

Shadow目前已经不怎么改`projects/sample/source`了，后续的开发，一直把全部case都写成了自动化测试，在`projects/test`里。

Shadow的核心代码都在`projects/sdk`里。`core`是“插件化”相关的代码，`dynamic`是把“插件化”相关代码再动态化起来的代码。

精力有限，文档还是少了点，优先保证还是代码调试的通路。此外，任何Shadow相关的具体技术问题都欢迎提Issue来问。如果有代码改动最好push上来参考。
