### ISSUE TITLE
lifecycle版本升级后，livedata订阅失效

### ISSUE THREAD

**Issue by Bin43** [Tencent/Shadow#503]
如题，我将项目`projects/sample/sunflower/plugin-project`中的`lifecycleVersion`版本升级至`2.3.0`，发现页面的LiveData订阅均无效。若将版本降至为`2.2.0-alpha04`，则LiveData可正常使用。请问，我想使用最新稳定版本的lifecycle，该怎么处理LiveData订阅失效问题。

**Comment by shifujun** [comment]
有这种对比效果，是Shadow的bug的可能性就比较大了。你可以把这个库接到`projects/sample/source`中调试一下，Debug一下订阅通知的调用栈，看看失效在什么方法上了。找到后可以把代码push上来，我应该可以知道是什么原因。

**Comment by Bin43** [comment]
`projects/sample/source`非Androidx项目，要想使用2.2.0-alpha01及以上的lifecycle，我得将整个项目迁移至Androidx，这步操作感觉会涉及到好多……
然后，我仔细看了下，`2.2.0-alpha05`的问题修复，主要是[修复了协程 LiveData 构建器中的竞态条件问题](https://android.googlesource.com/platform/frameworks/support/+/af12e75e6b4110f48e44ca121466943909de8f06%5E%21/#F6)。
最后，我还是找时间把项目迁移到Androidx去看下调用栈吧。

**Comment by Bin43** [comment]
刚才重新调试了一下，发现在Fragment中，不管什么版本都能订阅成功，而在Activity则只能在`2.2.0-alpha04`及其以下的版本才能订阅成功。从而推断出可能是插件在打包过程中，所替换的activity中有部分方法缺省或者不支持高版本的调用。恕我才疏学浅，实在看不出这里面有啥不一样的。

**Comment by shifujun** [comment]
像这样的bug我是肯定会看的。只是最近有点忙。你可以再继续debug看看这个订阅机制的原理，特别是与activity和fragment相关的部分。应该是比较长知识的实践，值得自己看看。实在不行，也最好把你调试的代码传上来。我完全独立去看这个问题时间上可能没保证。

**Comment by Bin43** [comment]
抱歉哈，最近工作上一堆事，回复晚了…… 我这边还有一个问题，项目`kotlin`版本为`1.4.31`,`kotlinx_coroutines`版本为`1.4.2`，单独运行插件工程协程功能正常，而打包成插件则提示`cannot be cast to kotlin.coroutines.Continuation`，这让我有点抓狂……等手头事情告一段落，我重写一个测试例子(`p.s. 之前写的例子包含太多公司项目的内容，不大方便上传，请见谅`)，然后大佬一起探讨探讨？？

**Comment by shifujun** [comment]
有代码可以方便pull回来，run起来就能复现问题的，就很容易交流。我也有其他的工作，所以没代码都只能猜测。这个bug我自己也是找时间先搭个androidx的测试环境，再细看。

**Comment by shifujun** [comment]
我已经查清楚这个问题了。

androidx.lifecycle.ReportFragment.injectIfNeededIn在SDK_INT >= 29时
采用了activity.registerActivityLifecycleCallbacks的方式监听Activity生命周期。

通过监听`onActivityPostStarted`方法，通知LiveData生命周期。

`onActivityPostStarted`等一些方法是ActivityLifecycleCallbacks在API 29新增的default方法，
因此Shadow的Compile SDK升级到29后，没有覆盖这些default方法也没有报错。

TODO：补全所有ActivityLifecycleCallbacks在API 29新增的default方法。
