### ISSUE TITLE
请问一下,宿主R.java和插件R.java冲突怎么解决?

### ISSUE THREAD

**Issue by hqweb** [Tencent/Shadow#509]
我目前在写一个轮子, 但是出现了问题, 你们项目我试了没问题. 我知道原因, 但我不知道怎么解决.

插件里的代码,宿主调用getLayout方法获取插件的View并展示出来
` public static View getLayout(Context ctx){
        return LayoutInflater.from(ctx).inflate(R.layout.main_activity, new LinearLayout(ctx),false);
    }`
但是界面展示出来和预想的不一样,因为这段代码会通过R.java调用资源,代码如下
`TypedArray a = getContext().obtainStyledAttributes(attrs, styleable.ConstraintLayout_Layout);`
attrs是插件的资源,styleable.ConstraintLayout_Layout是R.java的内部类,但是这个R.java是宿主的,正常来说这个R.java也应该是插件的才行.

我通过打印这个R.java的classloder印证了我的观点
`import androidx.constraintlayout.widget.R.styleable;
 ClassLoader classLoader =  styleable.class.getClassLoader();
  Log.v("consttest", "stylayout_class:"+classLoader.toString());`
我发现宿主不包含constraintlayout的依赖,那么ClassLoader就是插件的,如果包含了,那么ClassLoader就是宿主的,这就很奇怪了,但你们框架不会出现这个问题,代码如下,
`dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
}`

**Comment by shifujun** [comment]
你最好提供一个对sample的最小改动，并能复现问题的代码。

**Comment by hqweb** [comment]
这个是我写的一个demo,我把代码上传到我的github给你看吗?

**Comment by shifujun** [comment]
fork之后修改sample复现问题，push上来就行。不要自己写demo，代码太多了。

**Comment by hqweb** [comment]
不是你们的代码,我正在写一个插件化的轮子....遇到bug了,但我搞了两三天,一直无法解决.  所以在这里找下前辈帮帮忙.

**Comment by hqweb** [comment]
我这个轮子代码很少,一下就能看懂了

**Comment by shifujun** [comment]
如果不是本项目的问题，就不要反馈到这里了。Shadow的插件Resource对象是独立构造的，所以不会有冲突。
