### ISSUE TITLE
mac找不到环境变量

### ISSUE THREAD

**Issue by cikichen** [Tencent/Shadow#510]
![image](https://user-images.githubusercontent.com/1478821/115555137-c4524780-a2e1-11eb-9d78-af8caed671f2.png)

环境变量配置无问题，无论命令行还是AS都提示找不到ANDROID_HOME

**Comment by shifujun** [comment]
> 环境变量配置无问题

怎么得出这个结论的？

**Comment by shifujun** [comment]
我猜，是先执行了`./gradlew`，看到报错后才添加的环境变量。没有重启电脑。`./gradlew`还是找不到是因为Gradle有deamon没重启。

**Comment by luoxiong94** [comment]
我也遇到这个问题了，输入env ， 是可以显示 ANDROID_HOME的 ，但是 System.getenv()  确获取不到
