### ISSUE TITLE
Shadow和Tinker有冲突，存在转换后被调用方法未实现的问题

### ISSUE THREAD

**Issue by a6685234** [Tencent/Shadow#511]
Execution failed for task ':app:transformClassesWithShadowTransformForIwristRelease'.
存在转换后被调用方法未实现的问题，详见D:\git\pda-allocate-plugin\app\build\shadow_replace_class_have_right_methods2881414713821973757.txt

下面是文件内容
Class com.tencent.shadow.core.runtime.ShadowInstrumentation中缺少方法:
newActivity:(Ljava/lang/Class;Landroid/content/Context;Landroid/os/IBinder;Lcom/tencent/shadow/core/runtime/ShadowApplication;Landroid/content/Intent;Landroid/content/pm/ActivityInfo;Ljava/lang/CharSequence;Lcom/tencent/shadow/core/runtime/ShadowActivity;Ljava/lang/String;Ljava/lang/Object;)Lcom/tencent/shadow/core/runtime/ShadowActivity;被这些类调用了:
com.tencent.tinker.loader.hotplug.interceptor.TinkerHackInstrumentation
callActivityOnNewIntent:(Lcom/tencent/shadow/core/runtime/ShadowActivity;Landroid/content/Intent;)V被这些类调用了:
com.tencent.tinker.loader.hotplug.interceptor.TinkerHackInstrumentation

**Comment by shifujun** [comment]
这跟Tinker没关系的。只是`ShadowInstrumentation`没实现`android.app.Instrumentation#newActivity(java.lang.Class<?>, android.content.Context, android.os.IBinder, android.app.Application, android.content.Intent, android.content.pm.ActivityInfo, java.lang.CharSequence, android.app.Activity, java.lang.String, java.lang.Object)`方法而已。

你可以参考`ShadowInstrumentation`相关的提交记录实现一下这个方法。欢迎PR贡献代码。
