### ISSUE TITLE
Shadow不支持隐式Intent跳转到插件么

### ISSUE THREAD

**Issue by SmileLeev** [Tencent/Shadow#512]
例如插件新增Activity申明scheme，shadow是否支持使用scheme打开插件Activity？

**Comment by shifujun** [comment]
Shadow的原理是插件代码只是宿主代码的一部分，Shadow帮业务代码自动编辑成了适合动态加载的代码。所以没有什么黑科技突破系统的限制。插件只能复用宿主注册在manifest中的权限以及Scheme。
