### ISSUE TITLE
支持插件的app里面集成了其他插件化的库吗

### ISSUE THREAD

**Issue by sun804336516** [Tencent/Shadow#513]
现在想做插件化动态更新，但是插件化的app必须得集成一个其他的热更插件（跟Shadow实现原理类似。也是动态下发apk），这个时候会出现Application类型不一致的问题

**Comment by shifujun** [comment]
请参考https://github.com/Tencent/Shadow/blob/2b494707308b28522a73a2355b258c9b70448441/CONTRIBUTING.md 交流。
