### ISSUE TITLE
请问下自定义属性冲突你们是怎么解决的？

### ISSUE THREAD

**Issue by hqweb** [Tencent/Shadow#514]
比如插件中的ConstraintLayout 会通过 android.support.constraint.R.class 获取解析自定义属性，而 android.support.constraint.R.class 在内存中只有一份，并且会优先加载 Host，因此在实际的运行内存中，R.class 来自于 Host。
我看其它插件化框架都是通过修改插件的 xml 文件 Package ID解决的。但你们不是这样的，请问下你们是怎么解决的？

**Comment by shifujun** [comment]
`R.class`就是个普通的Java类而已，通过ClassLoader的控制就能决定插件加载哪个实现。这没什么特别的。可以Debug一下sample，看看所有的ClassLoader关系。

**Comment by hqweb** [comment]
好的，谢谢
