### ISSUE TITLE
请问有没有新手配置教程？

### ISSUE THREAD

**Issue by wangshujun123** [Tencent/Shadow#515]
请问有没有新手配置教程？比如在我们已有的项目中，改支持插件化框架

**Comment by wangshujun123** [comment]
插件下载及数据统计打点需要自己来实现吗

**Comment by wangshujun123** [comment]
@shifujun

**Comment by wangshujun123** [comment]
@shifujun  RePlugin现在还升级维护吗？能否支持android 10，11

**Comment by shifujun** [comment]
> 请问有没有新手配置教程？比如在我们已有的项目中，改支持插件化框架

参考https://github.com/Tencent/Shadow/issues/245#issuecomment-572853946

> 插件下载及数据统计打点需要自己来实现吗

需要。因为这些不是Shadow的关键技术。

> RePlugin现在还升级维护吗？能否支持android 10，11
问错人和地方了。RePlugin不是我们的项目。

后续请针对具体的技术问题提Issue交流，避免在同一个Issue中讨论多个主题。
