### ISSUE TITLE
插件sunflower有没有适配android11

### ISSUE THREAD

**Issue by sindicly** [Tencent/Shadow#519]
我用demo的sunflower模块，发现宿主App可以安装成功，但是启动sunflower插件的时候，android11手机就闪退了，也不报错。

**Comment by shifujun** [comment]
前一阵为了支持#503 引入了一个bug。自动化测试用的是API 28的模拟器，没测出来。我这两天正在改呢。

还差自动化测试，你可以先试试：https://github.com/shifujun/Shadow/tree/onActivityPreCreated

**Comment by shifujun** [comment]
把这个方法暂时删了也行：
https://github.com/Tencent/Shadow/commit/0e5d9d8d935d296bc40555b07d8396ba539de214#diff-857170774724397c52d54548813c0e4968ed779df91bda6eb390a3ba9b2c1b13R164-R173

**Comment by sindicly** [comment]
谢大佬，很好使
