### ISSUE TITLE
我如何去调用jar包里面的第三方库呢

### ISSUE THREAD

**Issue by sindicly** [Tencent/Shadow#523]
我把宿主打成jar包，然后插件想调用jar里面的第三方库（比如retrofit2），怎么去掉呢？

**Comment by shifujun** [comment]
你描述的太简单了，第三方库由谁实现，都需要在哪里使用？还是用代码表达吧。fork一下，编辑sample，演示一下你想怎么调用。

其实这跟Shadow没什么太大关系。没有插件框架，你怎么做，现在还怎么做。由Shadow导致异常的情况，才是这里该交流的。

Shadow其实也就是帮业务把包含Activity等不能简单动态加载的代码重写了一下，变成了跟Activity等无关的代码，然后用普通的ClassLoader动态加载代码的方式加载起来运行的。

**Comment by sindicly** [comment]
我描述有误，就是把第三方依赖打成jar包，给多个插件使用，那么插件要怎么去调用？
代码：https://github.com/sindicly/Shadow.git（分支problem）

**Comment by sindicly** [comment]
![image](https://user-images.githubusercontent.com/46366983/120787873-63659280-c562-11eb-932b-1e8aeb06c1ae.png)

**Comment by shifujun** [comment]
像retrofit这样的与Android系统没关系的第三方库，不需要Shadow介入。你就正常的把它编成独立的apk，然后用DexClassLoader加载就行。可以自行搜索一下这方面的知识。Shadow的dynamic.manager或者dynamic.loader都是这样动态加载的。

如果第三方库使用了Activity等需要Shadow Transform修改的接口，可以编成一个单独的插件。然后在通过Shadow设计的·、`dependsOn`声明，使插件之间形成依赖关系。这个依赖关系会变成运行时各插件的ClassLoader的parent关系。因此可以复用代码。

可以参考这个测试用例的写法：
https://github.com/Tencent/Shadow/blob/0e5d9d8d935d296bc40555b07d8396ba539de214/projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin1/build.gradle#L64

还有这篇Wiki的介绍：https://juejin.cn/post/6844903893130821640
