### ISSUE TITLE
白名单里是"包名.**"时，PluginClassLoader类里的inPackage方法判断，“包名.类”会返回false

### ISSUE THREAD

**Issue by ychxx** [Tencent/Shadow#524]
![image](https://user-images.githubusercontent.com/18575712/120630416-69dc0780-c499-11eb-9c98-314cba1aa7cf.png)

**Comment by shifujun** [comment]
这是正常的，有测试用例的。你需要的应该是再定义一个单独的“包名”。“.**”中的那个点是匹配时，包名部分必须包含的。
