### ISSUE TITLE
目前插件退出时不会自动杀掉插件进程；当插件中包含so加载时，第二次进入插件时会crash

### ISSUE THREAD

**Issue by tanghuai** [Tencent/Shadow#527]
插件加载时，会创建PluginClassLoader加载插件dex，当插件退出时，sdk默认会保留插件进程，第二次进入时，会重新loadPlugin，如果插件中有so的加载，那会直接报错。因为so不能同时被多个classLoader加载。

**Comment by shifujun** [comment]
> sdk默认会保留插件进程

sdk没有这个设计。Android系统何时结束进程也不受应用代码控制。在设计中PPS service是为了管理插件进程的，同时也是由于它与manger保持的Binder链接，使Android系统认为它是一个活跃的Service，从而不会随意终止插件进程。

如果插件进程没有重启，正常来说，也不应该重复调用loadPlugin。应该查询已经加载的插件，直接启动它们，像正常安装的App一样。

另外，插件也可以和宿主工作在同一个进程。

如果还有不理解的地方，可以fork之后给sample加一个so，如果能复现问题，push代码上来我看看。
