### ISSUE TITLE
core:manager 打包成 aar 本地依赖的 :utils 不存在

### ISSUE THREAD

**Issue by Heart-Beats** [Tencent/Shadow#528]
大佬： 
       使用最新的代码编译测试运行报错：
![image](https://user-images.githubusercontent.com/33248551/121983246-9827e400-cdc3-11eb-8bb4-f476cf593b0f.png)

原因是本地依赖不会被打包到 aar 包中，考虑优化一下打包脚本（增加个 util 库）还是各个模块集成自己的 util ?

然后还有个问题可否考虑优化一下：
             在我的插件工程的 loader 模块中，继承自 `ComponentManager` 的类由 kotlin 编写，但 ComponentManager 继承的接口 `ShadowContext.PluginComponentLauncher` 无法访问，能否考虑将 PluginComponentLauncher 该接口从类中抽出？

**Comment by shifujun** [comment]
确实是忘了发maven构件然后测一下了。

PluginComponentLauncher的问题另外讨论吧。

**Comment by Heart-Beats** [comment]
好的，还有个问题我另开一个提一下
