### ISSUE TITLE
Execution failed for task ':core:generate-delegate-code:generateDelegateCode'.

### ISSUE THREAD

**Issue by TongWeiLe** [Tencent/Shadow#531]
FAILURE: Build failed with an exception.

* Where:
Build file '/Shadow/projects/sdk/core/generate-delegate-code/build.gradle' line: 27

* What went wrong:
Execution failed for task ':core:generate-delegate-code:generateDelegateCode'.
> java.lang.ExceptionInInitializerError (no error message)

host sample构建失败了，什么问题

**Comment by AlwaysOL** [comment]
看issue ，java版本设置 改成jdk 1.8即可解决，我昨天也碰到了，按照解决办法成功解决
