### ISSUE TITLE
多插件应用场景

### ISSUE THREAD

**Issue by yghysdr** [Tencent/Shadow#535]
我们现在有多个插件（每个是相对独立的业务，因此每个就单独分配了一个进程），都是用了一个播放器（假设sdk大小是10mb），这样就造成sdk重复下载，有什么好的建议吗

**Comment by shifujun** [comment]
下载过程是业务自己控制的，所以下载就先自己下载一次就好。然后多个进程的插件，如果UUID不一致，恐怕就要考虑自己动态生成那个`config.json`了。这个没有现成的实现。然后现有代码也支持从zip安装插件，也需要再额外实现一种支持传入`config.json`和apk路径的安装实现。
