### ISSUE TITLE
Intent 传值方面的问题

### ISSUE THREAD

**Issue by Heart-Beats** [Tencent/Shadow#540]
大佬，我这边尝试一个应用场景：

宿主启动一个插件中的 Service，通过 Intent 给其传输一个 Parcelable 对象，Service 再从 Intent 中取出处理。

此时就会有产生一个异常：`AndroidRuntime: android.os.BadParcelableException: ClassNotFoundException when unmarshalling:`
查阅相关知识后了解，因为跨进程，所以导致了传输的 Bundle 对象的 ClassLoader 为空，因此无法反序列化获取转化 Parcelable 对象。

了解了这个原因后，我就使用以下方式进行尝试：
![image](https://user-images.githubusercontent.com/33248551/122514104-f65ffb80-d03d-11eb-835f-796101c4f3da.png)
即取值时给传输的 Bundle 设置 ClassLoader，理想状态应该设为宿主的 PathClassLoader , 但由于在插件进程无法获取，所以采用了打包插件时添加宿主白名单的方式，问题得以解决。

但在实际应用上，该方式并不理想，首先传输的 Parcelable 对象是可能为匿名内部类对象，此种方式用在传值上还是比较多的，这就导致打包时的白名单：1. 不好确定具体的包名  2. 不好确定匿名内部类对象的个数。
其次，即使加入了白名单，传输的 Bundle  对象的 ClassLoader 仍为空，还需重新设置。

不知道大佬是否有比较好的解决方式？

**Comment by shifujun** [comment]
如果你不能确定这些Parcelable类的范围，确实怎么搞都麻烦。Parcelable其实是比较接近于传统C的struct的，有类型的结构体。由于它有类型，所以不方便跨ClassLoader传递。所以在技术方案选型的层面，最好就别这样做。可选的替代方案有很多，最好能用Map加基本类型解决最好，实在不行，再上json或者pb。其实也可以只传一个文件路径，用shared preferences共享数据。

**Comment by Heart-Beats** [comment]
这个对象主要是获取插件相关处理的回调，如果仅仅为了共享数据是没这么麻烦的，所以该对象必须要序列化，目前使用序列化主要有Parcelable 和 Serializable 两种方式， 但尝试好像都有 ClassLoader 相应的问题，所以这个问题好像最终又变成了宿主与插件如何方便的进行双向通信？

**Comment by shifujun** [comment]
插件和宿主双向通信可以直接用AIDL做一个Service给两边用就行了。

**Comment by Heart-Beats** [comment]
好的，我有时间参照 Sample 中的示例看看是否需要改为此种方式实现某些功能，谢谢大佬
![image](https://user-images.githubusercontent.com/33248551/122536667-5ca54800-d057-11eb-9348-a29e1a2ecdc8.png)
