### ISSUE TITLE
Could not determine the dependencies of task ':app:copyDebugPluginManagerTask'. > Task with path ':PluginManager:assembleDebug' not found in project ':app'.

### ISSUE THREAD

**Issue by TongWeiLe** [Tencent/Shadow#541]
本地项目配置报错，宿主项目中找不到这个task

还有 sample-host`在构建中会自动打包manager和"插件"到assets，readme看到这么一句，想问下作者这块的代码具体在哪里？

看到宿主sample-host的gradle配置了dependsOn("${projectName}:${taskName}")的依赖任务，在manager执行完assembleDebug后，执行copy任务，想问下是在哪里控制的manager的构建？

**Comment by shifujun** [comment]
如果代码什么都没改的话，应该不是这个错误，应该是有其他报错信息没看到。比如ANDROID_HOME是否配好了。可以在命令行下执行一下`./gradlew clean`,`./gradlew buildSdk`, `./gradlew :sample-host:assembleDebug`，逐个尝试下。

sample-host的一系列自动打包插件等配置，只是为了服务于Shadow这个项目的，希望修改sample或sdk的任意一处代码，重新执行都能生效。代码就在他们的build.gradle脚本里。
https://github.com/Tencent/Shadow/blob/0b3739912c0d61fa4ebdd9d4ae15d6141245be3e/projects/sample/source/sample-host/build.gradle#L98-L104

**Comment by TongWeiLe** [comment]
demo项目我这边跑起来了没问题，上面的报错是我自己引入到项目里面报的，:PluginManager:assembleDebug 这个task在当前app项目中没找到，setting中已经配置过了

**Comment by shifujun** [comment]
引入到你的项目中就不要参考`projects/sample/source`了，直接参考`projects/sample/maven`吧。

https://github.com/Tencent/Shadow/tree/master/projects/sample#%E4%BA%8C%E8%BF%9B%E5%88%B6maven%E4%BE%9D%E8%B5%96sdk%E7%9A%84sampleprojectssamplemaven

**Comment by TongWeiLe** [comment]
已解决
