### ISSUE TITLE
PluginManager 可否添加一个 enter 的重载方法？

### ISSUE THREAD

**Issue by Heart-Beats** [Tencent/Shadow#542]
因为 enter 方法中绑定 Service 时需要一个 PluginServiceConnection 对象， 但是目前的框架时使用 AIDL 时是需要在 Manager 侧创建 PluginServiceConnection  对象，无法在宿主中直接传入导致灵活性变差， 若如下在 manager 侧添加 公共方法如下：
``` java 
public void enter(final Context context, long fromId, Bundle bundle, final EnterCallback callback,
                      OnPluginServiceConnection onPluginServiceConnection){
}
```

则在宿主中使用时需要将 PluginManager  强制类型转换，同时又缺少 `BaseDynamicPluginManager `相关依赖还需添加依赖，因此可否考虑 PluginManager 中添加个 enter 重载方法，该方法添加一个参数支持传入 `PluginServiceConnection`，已有接口改为默认方法，`PluginServiceConnection `传入 null ?

**Comment by shifujun** [comment]
没太看明白为什么要在enter加一个PluginServiceConnection参数，还是加一个OnPluginServiceConnection回调，以及为什么。

PluginManager是宿主的一一部分动态代码。这里的enter方法是为了让宿主可以传入调用enter的代码相关的信息。enter的实现代码依旧是宿主当前进程的代码，也是宿主的代码。这里实现enter方法时，可以先加载PluginLoader，再加载插件，再根据enter的参数决定后面干什么。比如再调用PluginLoader的bindPluginService方法绑定一个Plugin中的Service。

如果要将这个Service再交给宿主中非动态的代码使用，可以由Manager和宿主之间约定一个接口，也可以直接把插件Service的`IBinder`继续传给任何代码直接使用。

**Comment by Heart-Beats** [comment]
OnPluginServiceConnection 是为了避免引入 runtime 相关的依赖添加的继承自 PluginServiceConnection 的接口，主要的原因就是 
插件 Service 的 IBinder 在 PluginServiceConnection 中收到回调，宿主是无法通过 PluginManager 直接获取的，对于 enter 方法是传入启动插件相关的信息，但其并无返回值，所以除非在 PluginManager  添加接口，按现有的 enter 方法是无法直接在宿主侧实现插件 Service 绑定成功后进行其他操作

**Comment by shifujun** [comment]
噢，大概就是需要控制反转。这里我们认为宿主是不可变的代码。Manager是动态代码，并且和宿主的版本关系是多对多的。

所以宿主里可以准备好一个接口接受IBinder类型，Manager拿到插件的IBinder之后主动调用宿主的接口，传给它。

**Comment by Heart-Beats** [comment]
但是这样的话就会使 Manager 和 宿主侧灵活性降低了，首先 Manager 侧需要添加宿主白名单，其次白名单中的类需要单例实现，否则宿主中无法取到这个 IBinder 对象，同样的，针对插件 Service  断开连接后若想进行一些操作，仍需进行这些设置，所以传递这个 IBinder 对象并不是很合适，若想进行这些操作更合适的应该是传递 PluginServiceConnection 实现，当然如何传递遇到的问题是一样的

**Comment by shifujun** [comment]
现有的代码并不想让宿主直接操作插件，是希望操作插件的代码都写在Manager里的。这样与动态代码相关的逻辑才会都动态化。

所以宿主中非动态的代码如果要操作插件Service，一定要控制反转，提前和Manager约定好接口。如果宿主要关心插件Service的PluginServiceConnection，那可能需要额外再声明一个ServiceConnection接口，由Manager去实现它，转调PluginServiceConnection。这样做才能保证Manager和Loader未来可以修改PluginServiceConnection接口，新增方法，同时和旧版本的宿主协同工作。

另外Manager调宿主接口依赖的单例可以选择使用宿主的Application对象，让宿主Application实现那个Manager认知宿主的接口。

**Comment by Heart-Beats** [comment]
嗯嗯，好的，谢谢大佬的解答，我会考虑按照设计的动态化实现
