### ISSUE TITLE
关于transform-kit使用问题

### ISSUE THREAD

**Issue by chrissen0814** [Tencent/Shadow#545]
你好，最近我在学习你们的框架，看了你们写的文章，深受启发，也非常感谢你们能够开源如此优秀的库。

我们在项目中有使用到Shadow的transform-kit这个库，期间我们遇到了一个问题想跟你们请教一下：

`@JvmStatic
    fun register(project: Project) {

        val baseExtension = getBaseExtension(project)
        val sdkDirectory = baseExtension.sdkDirectory
        val androidJarPath = "platforms/$compileSdkVersion/android.jar"
        val androidJar = File(sdkDirectory, androidJarPath)

        //在这里取到的contextClassLoader包含运行时库(classpath方式引入的)shadow-runtime
        val contextClassLoader = Thread.currentThread().contextClassLoader

        val classPoolBuilder = AndroidClassPoolBuilder(project, contextClassLoader, androidJar)

        baseExtension.registerTransform(
            MiraTransform(
                project,
                classPoolBuilder
            )
        )

        project.afterEvaluate {
            compileSdkVersion = baseExtension.compileSdkVersion
        }
    }`

上面是我们插件的一个注册方法，是借鉴了Shadow中的做法，但是我们的插件有引用到一个自己写的库，需要在tranform的过程中使用到，但是直接使用上面这段代码会报找不到具体的类。目前我们的做法是：

`override fun beforeTransform(invocation: TransformInvocation) {
        super.beforeTransform(invocation)
        classPool.insertClassPath("/Users/me/.gradle/caches/modules-2/files-2.1/com.bytedance.article.common/mira-sdk-loader/0.0.0.1-alpha08/7cd2760c7e6e240183dbabaa024d5c98177e72a8/mira-sdk-loader-0.0.0.1-alpha08.jar")
        _mTransformManager = MiraTransformManager(mCtClassInputMap, classPool)
    }`

这种做法肯定不是更好的实现方式，所以想请教你们有没有更好的方式能够解决找不到被引用的三方库的问题。

**Comment by shifujun** [comment]
这里buildscript引入的`gradle-plugin`间接引入的`transform-kit`：
https://github.com/Tencent/Shadow/blob/master/projects/sample/maven/plugin-project/plugin-shadow-apk/build.gradle#L40

所以在这里加入的`classpath`都会出现在`val contextClassLoader = Thread.currentThread().contextClassLoader`中，按照前面已有的逻辑，`contextClassLoader`会被添加到`AndroidClassPoolBuilder`中。

所以应该只需要在那里加一行`classpath com.bytedance.article.common:mira-sdk-loader:0.0.0.1-alpha08`应该就行了。
