### ISSUE TITLE
屏幕旋转兼容问题

### ISSUE THREAD

**Issue by yghysdr** [Tencent/Shadow#548]
oppo A37m/colorOS V3.0/Android5.1版本
vivoX9i/Funtouch OS_3.1 /Android7.1.2

目前已知两款手机屏幕旋转有问题（旋转会触发activity的oncreate方法），示例里面的屏幕旋转就可以验证。

**Comment by shifujun** [comment]
是用`TestActivityOrientation`验证的吧？Android官方的模拟器没有问题的话，应该就是这些OEM系统的bug了。
没有他们的系统源码是很难debug哪里造成的差异的。

不过按照Shadow的原理，插件Activity代码只是宿主代码的一部分。应该可以不用Shadow直接写一个Activity也能复现这个问题的。你可以试试将`TestActivityOrientation`中的代码直接复制到一个正常的应用中，注意Activity的manifest设置要和`PluginDefaultProxyActivity`保持一致。

如果不能复现问题，再尝试将TestActivityOrientation的代码写成一个Activity持有的普通类。这就是Shadow帮插件自动修改代码所做的事。
