### ISSUE TITLE
多插件时的UUID问题

### ISSUE THREAD

**Issue by enzowyf** [Tencent/Shadow#55]
当存在多个插件的时候，目前的打包脚本会为每个插件都生成新的uuid，加载插件的时候，就会发生错误，需要固定uuid

**Comment by shifujun** [comment]
目前打包插件支持一种固定uuid的方式，请参考这篇文章的说明。如果有更好的实现方法，欢迎向Shadow贡献代码。

> 执行packageDebugPlugin任务时会自动生成UUID。如果要复用之前UUID，可以在插件包生成的build目录放一个uuid.txt文件，将UUID指定在里面。这部分代码见com.tencent.shadow.core.gradle.extensions.PackagePluginExtension#toJson。需要注意的是，如果在源码依赖的sample中这样固定了UUID，会导致更新代码的sample-plugin不能正常更新安装，因为它的UUID总是不变的。

作者：shifujun
链接：https://juejin.im/post/5d2ec812e51d45778f076de3
来源：掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
