### ISSUE TITLE
PluginManagerUpdater接口设计冗余

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Tencent/Shadow#550]
PluginManagerUpdater接口定义如下：
```java
public interface PluginManagerUpdater {
    boolean wasUpdating();
    Future<File> update();
    File getLatest();
    Future<Boolean> isAvailable(File file);
}
```
但是用到的只有  `update()`和 `File getLatest()`，而且`update()`的 返回值 `Future<File>`被忽略。
建议简化后的接口设计如下：
```java
public interface PluginManagerUpdater {
    void update();
    File getLatest();
}
```

**Comment by shifujun** [comment]
wasUpdating应该是用来判断更新中断的。getLatest应该是用来获取本地可用的。其余两个Future接口应该是发起异步调用后可用用来等待完成的。

考虑的主要场景应该是首次启动本地没有可用文件的情况，还有更新时中断的情况，还有更新未完成时启动已有旧版本的情况。

manager的这些逻辑跟业务关系太强了，定制化太多。也不是shadow的重点。所以sample里实现的太简单了。

**Comment by LinXueyuanStdio** [comment]
嗷我懂了，host包里只提供了简单默认实现，`public final class DynamicPluginManager implements PluginManager` 这个东西完全可以自己实现一个。

不过既然shadow不关心`PluginManagerUpdater`和`DynamicPluginManager`，只关心`PluginManager`的实例，那么接口`PluginManagerUpdater`的具体定义应该留给用户，而不是在shadow里写一个不通用的东西

**Comment by LinXueyuanStdio** [comment]
shadow里PluginManagerUpdater接口对宿主来说完全可以丢掉

**Comment by shifujun** [comment]
是的，manager相关的代码都不算是重点。但是没有这东西又不好演示插件框架的功能。所以当时主要重点是把必要的代码和业务的manager代码分离开，方便尽快开源出来。

我具体看了一下，`PluginManagerUpdater`这个接口确实没有提供sdk的实现，代码里的`FixedPathPmUpdater`只是个sample代码。

**Comment by LinXueyuanStdio** [comment]
我尝试自己定义`DynamicPluginManager `，但是一些类是package-private的，调用不了。
我的看法是，有两种方式。
- 一是先把`DynamicPluginManager `改成抽象类，只定义一些原子方法，比如加载`managerImpl`等比较核心的方法，然后把updater相关的东西都去掉，让宿主自己新建一个类，继承这个抽象类，实现自己的更新方法。
- 二是把相关方法都public。这个比较危险一点。
你设计一下，我可以帮忙提相关的pr。

**Comment by shifujun** [comment]
我还是没理解需要修改DynamicPluginManager行为的理由是什么。我再完整写一下这些类的关系：

`core.loader`可以加载启动插件，是我们的核心功能。它需要一个启动参数，描述插件apk在哪以及其他信息。

`core.common`里的`InstalledApk`就是`core.loader`所需的启动参数。

`core.manager`实现的就是一个本地插件包的管理器，不管它怎么管理的，它需要最后提供出`core.common`里的`InstalledApk`，供`core.loader`使用。

所以前面就是`core.loader`和`core.manager`两个模块都依赖`core.common`，一个生产`InstalledApk`一个消费`InstalledApk`，连起来完成插件的安装和启动。

然后我们想把`core`层这些功能也动态化起来，所以就有了`dynamic`层。我们希望先下载一个`PluginManager`，这个`PluginManager`不需要Activity等功能，所以直接用DexClassLoader加载起来就能运行了。然后由它再去下载加载Loader。

所以这里就有2个下载器，一个是`PluginManagerUpdater`，它负责升级`PluginManager`。由于它的实现要放在宿主里，不能动态更新，所以它的逻辑要非常简单可靠。我们的sample里只提供了一个`FixedPathPmUpdater`，从固定路径加载演示的本地`PluginManager`。另一个下载器就是`PluginManager`实现本身，它负责下载业务插件包，这个下载逻辑就比较复杂了，可以做渠道、灰度等逻辑，另外由于下载的业务插件体积可能大一点，也可以用一些专门的下载SDK技术。

`DynamicPluginManager`也是`dynamic-host`中的类，也是打包在宿主里不动的代码。它的职责就是把`PluginManager`的实现加载起来。它确实只依赖`PluginManagerUpdater`的`getLatest`和`update`接口。但是`PluginManagerUpdater`是宿主中注入的，宿主里的其他代码还是可以持有它，在特别设计的时机调用`isAvailable`和`wasUpdating`，用来满足预加载等场景。

将这些类设计成final和package访问的，是为了简化设计的，这样可以不用考虑被继承时的复杂情况。

要不再继续讨论下你的场景中，需要定义成怎样的更新逻辑吧？我看看能否保持兼容性来支持。

**Comment by LinXueyuanStdio** [comment]
我描述一下我打算怎么使用shadow的吧。
## 1. 需求
### 1.1 插件化系统
首先需求是插件化系统，包括以下几个维度的动态化：
1. 复杂view，和宿主页面中其他view交互
2. 复杂list item，和宿主其他list item交互
3. fragment，嵌入宿主主页
4. activity
5. service

其中1、2、3可以让宿主和插件约定接口达到，4、5 shadow自己支持。

目前我们的精力主要在1、2、3的接口设计上。

### 1.2 更新能力

其次是对插件的更新管理。

有两个，一个是 `manager.apk`，另一个是 `plugin.zip`。

## 2. 实现

实际上1、2、3可以合并为一个需求，即 view 的动态化，这个 view 需要和宿主进行复杂的交互。
目前直接能做的是只需要在 manager enter 时回调返回这个 view 即可（我们自己写相关的view动态化逻辑和manager的动态化是差不多的，都是约定接口，加载类，回调返回view，所以直接用已有的接口了。这里或许可以进一步优化`EnterCallback`）。
此时 view 打包在 manager 中，而不是插件包中。因而 manager 成为插件的一部分。

因为这个 view 要跟宿主频繁交互，所以宿主需要管理 manager 的生命周期和 view 的生命周期。

manager 的生命周期主要是 manager 的更新。
宿主调用插件，先查询是否已有`manager.apk`，没有就当场下载，下载完就进入 view 的生命周期。
如果已有`manager.apk`，则查询是否是最新版本，根据最新版本和用户设置自动更新，决定是后台自动更新`manager`还是等待用户手动更新。

view 的生命周期和业务相关，主要是调用宿主注入的接口进行交互，以及调用 manager 中的方法拉起插件包中的 activity 或者 service。

因为`manager.apk`和`plugin.zip`是同一插件业务，所以更新这两个文件是同时更新的。

## 3. 与 Shadow 的不同点

`shadow` 的 `DynamicPluginManager` 现在实现得比较简单：
1. 在构造函数中检测必须存在`getLatest() != null`，而我们需要即使在没有最新`manager.apk`的情况下当场下载，然后加载。
2. 在加载好 `PluginManager` 的实现后都会调用一次 `PluginManagerUpdater::update()` ，然后也不关心返回值。我们需要在合适的时机进行更新，即根据用户设置，决定后台更新还是等用户在其他地方手动更新。所以我们实现`update()`函数时会更加复杂。

这两点都可以曲线救国达到目的，但很不优雅，容易出错。

究其原因，是`DynamicPluginManager`没有做好自己的生命周期管理。它应该暴露出相应的回调接口，比如 `onLoadingManagerImpl`、`onLoadManagerImplFail`、`onLoadManagerImplSuccess`、`onReleaseManagerImpl`、`onEntering`等等。它目前是尝试自己加载好就调用 updater 接口自动更新，但实际上更新这个场景对宿主来说是更复杂的。

**Comment by LinXueyuanStdio** [comment]
可能我的理解不是很到位，shadow重点关注的是 activity 和 service 的动态化，而不是 view。感觉这样实现有点滥用框架了。

Shadow 应该是有 **让宿主从插件包 `plugin.zip` 中加载 view** 的能力的，而不仅仅是加载 `manager.apk` 中的 view。

但我在 sample 中没有看到相关的演示。

**Comment by LinXueyuanStdio** [comment]
动态加载 view 的需求和 #319 #453 #490 类似。

**Comment by shifujun** [comment]
看起来你对manager.apk的用法确实和我们的设计不太匹配。

> 因为manager.apk和plugin.zip是同一插件业务，所以更新这两个文件是同时更新的。

我们的设计中，manager是负责下载plugin.zip的，决定如何调用loader启动哪个插件页面。更新manager的逻辑由于在宿主中写死了，需要特别简单可靠，也就不能有什么复杂的逻辑。manager中含有一个动态加载的view，只是用于下载的loading界面实现。

如果考虑动态View的实现，确实不应该在manager上扩展。可以考虑参考DynamicPluginManager的实现，另外实现。

动态View确实不是Shadow的重点，但将DynamicPluginManager涉及的动态View的代码抽成一个更易复用的模块确实无伤大雅。
