### ISSUE TITLE
启动插件时 partKey 为 null

### ISSUE THREAD

**Issue by Heart-Beats** [Tencent/Shadow#555]
大佬， 我遇到一个比较奇怪的问题：
打包的插件压缩包 config 如下：
``` json
{
  "compact_version": [
    1,
    2,
    3
  ],
  "pluginLoader": {
    "apkName": "my-loader-debug.apk",
    "hash": "D0E03A1288C246B4FA7B91531E2A524E"
  },
  "plugins": [
    {
      "partKey": "update",
      "apkName": "update-TSP26A1V2_GZ-debug.apk",
      "businessName": "update-debug",
      "hostWhiteList": [
        "android.tsinglink.hostlib"
      ],
      "hash": "CFE125DA6F1407B727E02742FE8F88A5"
    }
  ],
  "runtime": {
    "apkName": "my-runtime-debug.apk",
    "hash": "35F10E0060DD846822D7848766D43EAC"
  },
  "UUID": "1A3272B6-E9C6-428C-9536-9610BFC88427",
  "version": 1,
  "UUID_NickName": "0.0.1"
}
```

然后我启动插件时传的 partKey 也为  update， 但是启动插件创建 Service 时崩溃， 在 PluginServiceManager 的源码上添加的 log 如图：
![image](https://user-images.githubusercontent.com/33248551/123774819-6143e900-d900-11eb-9fc9-01b51d61bc77.png)
崩溃时的日志如下：
![image](https://user-images.githubusercontent.com/33248551/123775193-bed83580-d900-11eb-81a4-2a3d44b03c46.png)

不太清楚问题出在哪，请大佬有时间帮忙解答一下！

**Comment by shifujun** [comment]
就是还没有loadPlugin吧，debug一下这里的运行情况吧：
https://github.com/Tencent/Shadow/blob/e62dfd7c8b57978e40e1fcb549e51b880a60ba7c/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt#L167

**Comment by shifujun** [comment]
你最好先debug一下sample的运行情况，再对比一下你的插件。

**Comment by Heart-Beats** [comment]
嗯，原因我已经确定到了，的确是我个人的原因，我在复制 Service 时忘记向清单注册了，导致 ComponentManager 中没有该组件，疏忽大意了
![image](https://user-images.githubusercontent.com/33248551/124052957-f276a500-da51-11eb-8092-bdfea8a98f3b.png)
