### ISSUE TITLE
多插件切换异常

### ISSUE THREAD

**Issue by Bin43** [Tencent/Shadow#557]
如题，若A、B插件依赖同一个第三方库（该库中存在一个C页面），则会出现先调用插件A正常，调用插件B则会报`重复添加Component`的错，再次重新调用插件B才正常。
排查代码发现`com.tencent.shadow.core.loader.managers.ComponentManager`中`common`方法，切换插件`pluginInfoMap`并未清空，导致相同的componentName会被判定为重复添加并抛异常。

请问是否可以在切换插件时将上一个插件所存储的配对关系清空呢
相关代码如下：
```
    fun addPluginApkInfo(pluginInfo: PluginInfo) {
        // TODO 可否在此处清空上一个插件的配对关系
        packageNameMap.clear()
        componentMap.clear()
        pluginInfoMap.clear()
        pluginComponentInfoMap.clear()

         fun common(pluginComponentInfo: PluginComponentInfo,componentName:ComponentName) {
                    packageNameMap[pluginComponentInfo.className!!] = pluginInfo.packageName
                    // 切换插件，pluginInfoMap还携带着上个插件的数据
                    val previousValue = pluginInfoMap.put(componentName, pluginInfo)
                    if (previousValue != null) {
                        throw IllegalStateException("重复添加Component：$componentName")
                    }
                    pluginComponentInfoMap[componentName] = pluginComponentInfo
                }
               
        ...
}
```

**Comment by shifujun** [comment]
> 切换插件pluginInfoMap并未清空

这个不清空考虑的使用场景是多个插件协同工作的。

我觉得你可以考虑将C页面所在的第三方库单独作为一个插件C，让A和B依赖它。

**Comment by Bin43** [comment]
多插件协同，我得去想想使用场景…… 但仍存在一个问题，插件不能存在相同的包名以及Activity，这种同样也会被判定重复添加

**Comment by shifujun** [comment]
不允许重复添加同名的组件是为了启动它们时能区分开。你可以设计一个能方便区分开插件组件的方案。

**Comment by Bin43** [comment]
大佬，这个多插件协同实在想不出使用场景，可否指点一二。

**Comment by shifujun** [comment]
“使用场景”？就是你说的”A、B插件依赖同一个第三方库“的场景啊。插件A dependsOn 插件B，就会把插件B的ClassLoader设置为插件A的ClassLoader的parent。这样插件A就能使用插件B中的类型了。

**Comment by Bin43** [comment]
soga……自己钻牛角尖了，多谢
