### ISSUE TITLE
shadow运用到sdk中

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#558]
版主，现在如果是将shadow运用到sdk中，开发sdk供开发者使用，这个时候难以保证sdk插件包名和开发者一致，有什么好的办法可以解决嘛

**Comment by shifujun** [comment]
如果你了解为什么插件和宿主包名需要保持一致，也可以自行去掉这个检查限制。WIKI：[Shadow为什么要求插件和宿主包名一致](https://juejin.im/post/5d13579cf265da1b957067af)

对于SDK来说，会比较容易控制影响，自己主动不用一些API，也避免包名交给系统。SDK的功能测试应该也比较容易覆盖全，所以有一定的可行性。

这个包名一致的问题，如果细致解决，可以考虑用Transform修改有问题的调用。只是不如包名一致来的简单直接。

另外，如果插件的CI/CD流程做的复杂一点，也可以针对每个宿主编译一个对应包名的插件。这是一定可行的，只是需要开发一些自动化流程来支撑。
