### ISSUE TITLE
java.lang.RuntimeException: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ychxx** [Tencent/Shadow#560]
插件里跳转页面时，报了ConcurrentModificationException错误。

在ShadowActivityLifecycleCallbacks类的下方两个方法设置断点发现
  public static void notifyPluginActivityPreCreated(ShadowActivity pluginActivity, Bundle savedInstanceState) {
            synchronized (sAllHolders) {
                for (Holder holder : sAllHolders) {
                    holder.onPluginActivityPreCreated(pluginActivity, savedInstanceState);
                }
            }
  }
public void registerActivityLifecycleCallbacks(Object caller,  ShadowActivityLifecycleCallbacks callback) {
            synchronized (sAllHolders) {
                final ShadowActivityLifecycleCallbacks.Wrapper wrapper
                        = new ShadowActivityLifecycleCallbacks.Wrapper(callback, caller);
                mActivityLifecycleCallbacksMap.put(callback, wrapper);
                register(wrapper);
                sAllHolders.add(this);
            }
 }
在notifyPluginActivityPreCreated方法的for循环执行到第二次未完成时，registerActivityLifecycleCallbacks方法又被执行，导致ConcurrentModificationException错误
由于已经将shadow加入我们自己的项目里，没法在shadow的测试例子里复现，请问有什么办法能解决这个问题。

**Comment by ychxx** [comment]
我将set<Holder> sAllHolders改为CopyOnWriteArrayList<Holder>就没有报错了

**Comment by shifujun** [comment]
感谢反馈，已修复。通知前copy一份数组就行了，不用`CopyOnWriteArrayList`。
