### ISSUE TITLE
使用第三方百度ocr，找不到so文件问题

### ISSUE THREAD

**Issue by ychxx** [Tencent/Shadow#562]
com.tencent.shadow.core.loader.classloaders.PluginClassLoader[DexPathList[[zip file "/data/user/0/com.tencent.shadow.test.hostapp/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/1894ba644df5c24893c090fb68180d02/plugin-debug.zip/test-plugin-general-cases-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.tencent.shadow.test.hostapp/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/lib/9EF65F23-D568-42DF-A097-540E23A9160B_lib, /system/lib64, /product/lib64]]] couldn't find "libocr-sdk.so"

在shadow里测试的例子[b7fb361](https://github.com/ychxx/Shadow/commit/b7fb36148eeaf49d6999862a6615d7a397f0aea5)

**Comment by shifujun** [comment]
看起来是没有在Manager里主动设置好abi。这里是Shadow实现的比较简陋，没有写像系统一样的自动判断abi的逻辑。
https://github.com/Tencent/Shadow/blob/master/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L58

**Comment by ychxx** [comment]
我在自己的项目里做了如下修改
1.修改为public String getAbi() {return "armeabi-v7a";}
2.在build.gradle里添加了ndk { abiFilters 'armeabi-v7a'  }
3.删除了除了armeabi-v7a的其他abi的文件夹
但是又报/libocr-sdk.so" is 32-bit instead of 64-bit错误

**Comment by ychxx** [comment]
shadow的demo里也会[afec15a](https://github.com/ychxx/Shadow/commit/afec15abe9a924c28dc91308b5780f27532bde1d)

**Comment by shifujun** [comment]
你的宿主app可能是64位的，或者没有so，系统会默认它是64位的。你可以在宿主里随便加一个32位的so就好了。

**Comment by ychxx** [comment]
可以了，非常感谢帮忙
