### ISSUE TITLE
support 包一直拉不下来，能否迁移到androidx下面。

### ISSUE THREAD

**Issue by yanweimin7** [Tencent/Shadow#563]
![image](https://user-images.githubusercontent.com/1791581/125915191-e0ce7eef-94b4-485d-8d47-7d36478c07c2.png)

用as的migrate，只找到30个可迁移的，实际有大量没扫出来。。。

**Comment by shifujun** [comment]
AS的migrate也不是100%可靠的。对于这个sample来说也没必要这么做啊。你为什么想做这个呢？

我近期有考虑把source sample中的代码都删除掉，变成一个更适合随时引入任何代码和库的测试工程。

**Comment by yanweimin7** [comment]
@shifujun 主要是我现在不知道为啥support包一直拉不到，依赖里面看到的全是对androidx的依赖，
![image](https://user-images.githubusercontent.com/1791581/125922746-cfd25719-53c1-433c-a52d-6347b6c31cc1.png)
导致sample根本没法跑。

**Comment by shifujun** [comment]
项目默认使用了腾讯的软件源镜像，如果故障了可以换成其他的镜像，或者禁用掉。
https://github.com/Tencent/Shadow/blob/master/buildScripts/gradle/common.gradle#L34

**Comment by weithink** [comment]
> 的代码都删除掉，变成一个更适合随时引入任何代码和库的测试工程。

这大可不必吧，觉着这样已经很适合导入了。现在的这种更适合团队协作开发的演示。

**Comment by SunmerCho** [comment]
我也是，刚clone 下来， 运行 ./gradlew build 就提示support 包找不到

**Comment by shifujun** [comment]
> 我也是，刚clone 下来， 运行 ./gradlew build 就提示support 包找不到，请问解决了吗？

是外网访问腾讯的软件源镜像有问题吗？可以禁用掉，或者自己换成其他可用的软件源。https://github.com/Tencent/Shadow/blob/master/buildScripts/gradle/common.gradle#L34

**Comment by SunmerCho** [comment]
禁用了还是不行，我截取了头尾的部分的log:
> Task :general-cases-lib:compileDebugJavaWithJavac FAILED
/Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/gallery/TestApplication.java:25: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/gallery/TestApplication.java:26: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/context/ActivityContextSubDirTestActivity.java:22: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow//Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/activity/TestListActivity.java:23: error: cannot find symbol
    protected void onCreate(@Nullable Bundle savedInstanceState) {
                             ^
  symbol:   class Nullable
  location: class TestListActivity
/Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/activity/PrintActivityResultActivity.java:40: error: cannot find symbol
    protected void onCreate(@Nullable Bundle savedInstanceState) {
                             ^
  symbol:   class Nullable
  location: class PrintActivityResultActivity
/Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/activity/ApplicationContextActivity.java:21: error: cannot find symbol
    protected void onCreate(@Nullable Bundle savedInstanceState) {
                             ^
  symbol:   class Nullable
  location: class ApplicationContextActivity
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/chosunmer/Android/Shadow/projects/test/plugin/general-cases/general-cases-lib/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/receiver/TestReceiverActivity.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':general-cases-lib:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
test/plugin/general_cases/lib/usecases/context/SubDirContextThemeWrapperTestActivity.java:26: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;

**Comment by shifujun** [comment]
基本肯定是环境问题导致拉取不到依赖包。这里先报`support`包可能只是因为代码顺序的关系，并不是只有它找不到。

准确的报错信息在哪我们没法确定。我估计`./gradlew --refresh-dependencies --info`应该能报出哪个repo访问不到。

Shadow对外依赖都来自`google()`和`jcenter()`，也就是Android模板项目的默认依赖。你可以对比你其他能够正常编译的Android项目，在所有`.gradle`文件中搜索`repositories`字段，改成一样的。

**Comment by SunmerCho** [comment]
可能是我本地的配置问题，我把support 包全部迁移到AndroidX 就可以编译成功了。
