### ISSUE TITLE
是否支持pendingIntent

### ISSUE THREAD

**Issue by catEgg** [Tencent/Shadow#567]
如题shadow的插件支持pendingIntent吗？

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/0e5d9d8d935d296bc40555b07d8396ba539de214/projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/PendingIntentTransform.kt

有简单的支持。如果哪种用法不支持，可以在sample中写一个例子复现一下方便讨论。

**Comment by catEgg** [comment]
好的，谢谢大佬，近期准备接入
