### ISSUE TITLE
PluginContainerActivity: DelegateProviderHolder没有初始化是哪没配置？

### ISSUE THREAD

**Issue by Rdigoo** [Tencent/Shadow#572]
PluginContainerActivity: PluginContainerActivity: DelegateProviderHolder没有初始化
PluginContainerActivity: onCreate: hostActivityDelegate==null finish activity

**Comment by MmingY** [comment]
你看看是不是SamplePluginLoader类中的getDelegateProviderKey()方法，将这个方法注释掉试一下呢。

**Comment by hahajing9** [comment]
一般是因为 默认的launchmode是stander的，比如使用NFC的时候，flag有的手机是修改不了加载模式 需要manifest中设置，所以使用的壳子就不一样，发现插件中没有，就会在宿主中找，然后就会报错；
