### ISSUE TITLE
关于插件新增权限处理

### ISSUE THREAD

**Issue by catEgg** [Tencent/Shadow#577]
如题，如果插件里有一个需要检测的新增权限（宿主无此权限），比如Manifest.permission.ACCESS_FINE_LOCATION 获取用户的位置信息，这种我自己在demo中测试，即使弹窗授权，也依然无法获取到，这种问题有处理方案吗？

**Comment by weithink** [comment]
所有权限都得预先在宿主中注册，这个插件的设计是宿主的一部分
