### ISSUE TITLE
匿名token

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#579]
版主 你的那个提供匿名下载的token咋申请的呀，这个token是一直生效的吗，我现在在githubPackages上发布包 但是token和你的不一样，而且很快就失效了。

**Comment by weikaiyun** [comment]
我已经选择了PAT no expiration

**Comment by weikaiyun** [comment]
版主用的什么工具 把pat 变为 xml encoded

**Comment by weikaiyun** [comment]
版主用的什么工具 对 pat 进行编码的 这样可以上传到github

**Comment by shifujun** [comment]
你可能已经找到了，还是贴一下。参考这个添加的：https://github.community/t/download-from-github-package-registry-without-authentication/14407
