### ISSUE TITLE
单个插件单独升级问题？

### ISSUE THREAD

**Issue by piaomiao8179** [Tencent/Shadow#583]
场景与需求：我们项目中有三个插件ABC，其中想单独升级插件C。

Shadow实现：在宿主host中将manage先复制到build/generated/assets/...文件夹下，将build目录下plugin-debug.zip根据packagePlugin复制到assets文件夹下，然后通过PluginHelper类从assets文件夹下复制到pluginManagerFile和pluginZipFile这两个文件中，然后后续的插件加载都是通过这两个文件糅合到宿主host中进行加载的。

问题： 目前插件中的实现，都是加载pluginZipFile这个文件加载插件的，没法做到单独升级插件C。

我不确定我目前理解的是不是对的，请大佬解惑。
@shifujun

**Comment by shifujun** [comment]
你理解的基本没问题。manager作为shadow的插件管理逻辑，它的主要设计是服务于我们做shadow时自己的业务的需要的。作为开源项目，我们尽可能把它设计的通用可扩展了，但是对于我们自己业务用不上的逻辑没法实现那么完整。

在现有代码设计中，宿主、manager、插件，是3个不同的版本部分，可以更新其中1个的版本。对于插件这个部分来说，其中还包含loader、runtime、业务插件这些部分。这些东西是用一个UUID统一成一个版本的。在设计中，UUID相同的apk，才能协同工作。这个设计主要是因为我们需要这些UUID相同的插件经常通过类的白名单直接跨apk引用类型，所以需要简单管理它们，需要它们一同更新。

ABC三个插件，如果只需要更新C插件，那么AB也要一起更新，对于用户来说要重复下载AB插件显然是不合适的。在预想的设计中，考虑未来这个场景应该通过增量下载来优化。即manager在下载新UUID的ABC插件时，可以根据md5等文件hash复用之前旧的UUID的AB插件，达到只下载新版本的C插件和少量新配置文件的目的。所以对于loader来说，新UUID的ABC 3个插件都是新的。

启动新版本UUID的ABC 3个插件时，肯定要重启进程了。如果要保持AB插件的内存而更新插件C，还需要特别的设计。在改动不大的情况下，应该只能给C单独分配一个manager实现，让它和AB采用不同的UUID，相互通过AIDL通信。即同一个宿主接入多个不相关的Shadow实现。

**Comment by piaomiao8179** [comment]
首先感谢大佬的回复。

是不是我将插件AB使用一套manager，插件C使用另一套单独的manager进行管理，我们项目中插件ABC相互不通讯，是不是可以单独升级插件C？

**Comment by shifujun** [comment]
是的。一个宿主中可以接多个Shadow的实现。最好将这些插件分开到不同进程中，避免潜在的冲突。

**Comment by piaomiao8179** [comment]
好的，谢谢大佬，赞。

**Comment by 863010067** [comment]
ACB三个插件在同一个子进程里（同一个UUID,同一个Zip包里），ABC三个插件只需要升级C插件，一定需要重启这个子进程吗？

**Comment by hibouwu** [comment]
PluginManager实例只能加载相同UUID的不同Plugin，不同PLuginManager实例分别绑定到不同PPS，运行不同的UUID的PluginLoader，就能运行不同的UUID的插件了，这样他们的更新也是不会影响到别的Plugin这样吧
