### ISSUE TITLE
插件中无法加载广点通以及穿山甲中配置组件。

### ISSUE THREAD

**Issue by Rdigoo** [Tencent/Shadow#584]
如何加载出aar中配置组件（DownloadService、TTRewardVideoActivity等等）

![image](https://user-images.githubusercontent.com/17718649/129555463-becad766-1acf-421d-91e4-e08d10b09166.png)

**Comment by shifujun** [comment]
这些组件加载不了，不是因为它们在aar中，而是另有原因。比如广点通之前讨论过：#441

处于aar中的Java class是可以被Shadow一同Transform编辑的。一般产生不兼容问题是由于代码本身有反射或强制类型转换等不安全的代码。

**Comment by Rdigoo** [comment]
感谢~
