### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/tencent/shadow/core/runtime/ShadowActivity

### ISSUE THREAD

**Issue by xixi6999** [Tencent/Shadow#587]
2021-08-19 21:09:25.550 12682-12718/com.rokid.fusionplatformapp E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.rokid.fusionplatformapp, PID: 12682
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/shadow/core/runtime/ShadowActivity;
        at com.rokid.pluginmanager.RokidPluginManager.startPluginActivity(RokidPluginManager.java:215)
        at com.rokid.pluginmanager.RokidPluginManager.lambda$enter$1$RokidPluginManager(RokidPluginManager.java:114)
        at com.rokid.pluginmanager.-$$Lambda$RokidPluginManager$eguLNbcwSn4YOkIbeQSNWmebi_Y.run(Unknown Source:16)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: com.tencent.shadow.core.runtime.ShadowActivity
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.rokid.pluginmanager.RokidPluginManager.startPluginActivity(RokidPluginManager.java:215) 
        at com.rokid.pluginmanager.RokidPluginManager.lambda$enter$1$RokidPluginManager(RokidPluginManager.java:114) 
        at com.rokid.pluginmanager.-$$Lambda$RokidPluginManager$eguLNbcwSn4YOkIbeQSNWmebi_Y.run(Unknown Source:16) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.core.runtime.ShadowActivity" on path: DexPathList[[zip file "/data/local/tmp/plugin-manager-debug.apk"],nativeLibraryDirectories=[/system/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:79)
        		... 7 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

从宿主启动插件后就一直报这个错误。
我固定了插件的uuid。
将loader与runtime抽离出来，单独打了一个zip包（也固定了相同的uuid）。
当应用启动时，我会先去loadPlugin（loader-runtime），然后再去loadPlugin（我的插件）。
然后就会出现此错误。问题是。即使我不这么做，将loader、runtime、插件打在同一个zip包中，依旧会报此错误。
求教

**Comment by xixi6999** [comment]
这是PluginManager的代码：


package com.rokid.pluginmanager;

import android.app.Activity;
import android.app.Service;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.IBinder;
import android.os.Looper;
import android.os.RemoteException;
import android.text.TextUtils;

import com.tencent.shadow.core.manager.installplugin.InstalledPlugin;
import com.tencent.shadow.core.manager.installplugin.InstalledType;
import com.tencent.shadow.core.manager.installplugin.PluginConfig;
import com.tencent.shadow.dynamic.host.EnterCallback;
import com.tencent.shadow.dynamic.host.FailedException;
import com.tencent.shadow.dynamic.loader.PluginServiceConnection;
import com.tencent.shadow.dynamic.manager.PluginManagerThatUseDynamicLoader;

import org.json.JSONException;

import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/**
 * @author ChenxiHu
 * @date 2021/8/13
 * A smile is the best business card.
 */
public class RokidPluginManager extends PluginManagerThatUseDynamicLoader {

    private final ExecutorService executorService = Executors.newSingleThreadExecutor();
    private final ExecutorService mFixedPool = Executors.newFixedThreadPool(4);

    /**
     * PluginProcessService
     */
    private final static String PPS_NAME = "com.rokid.fusionplatformapp.plugin.MainPluginProcessService";

    public RokidPluginManager(Context context) {
        super(context);
    }

    /**
     * @return PluginManager实现的别名，用于区分不同PluginManager实现的数据存储路径
     */
    @Override
    protected String getName() {
        return "rokid-manager";
    }

    /**
     * @return demo插件so的abi
     */
    @Override
    public String getAbi() {
        return "armeabi-v7a";
    }

    /**
     * @return 宿主中注册的PluginProcessService实现的类名
     */
    protected String getPluginProcessServiceName() {
        return PPS_NAME;
    }

    /**
     * @param context  context
     * @param fromId   标识本次请求的来源位置，用于区分入口
     * @param bundle   参数列表
     * @param callback 用于从PluginManager实现中返回View
     */
    @Override
    public void enter(final Context context, long fromId, Bundle bundle, final EnterCallback callback) {
        // 插件 zip 包地址，可以直接写在这里，也用Bundle可以传进来
        final String pluginZipPath = bundle.getString("plugin_path");
        final String partKey = bundle.getString("part_key");
        final String className = bundle.getString("activity_class_name");
        //是否重新加载zip
        boolean isLoad = bundle.getBoolean("is_load", false);
        if (className == null) {
            throw new NullPointerException("className == null");
        }
        if (fromId == 1011) {
            // 打开 Activity 示例
            final Bundle extras = bundle.getBundle("extra_to_plugin_bundle");
            if (callback != null) {
                // 开始加载插件了，实现加载布局
                callback.onShowLoadingView(null);
            }
            executorService.execute(() -> {
                try {
                    InstalledPlugin installedPlugin = installPlugin(pluginZipPath, null, true);//这个调用是阻塞的
                    Intent pluginIntent = new Intent();
                    pluginIntent.setClassName(context.getPackageName(), className);
                    if (extras != null) {
                        pluginIntent.replaceExtras(extras);
                    }

                    if (!TextUtils.isEmpty(className)) {
                        startPluginActivity(context, installedPlugin, partKey, pluginIntent, isLoad);
                    }

                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                if (callback != null) {
                    Handler uiHandler = new Handler(Looper.getMainLooper());
                    uiHandler.post(() -> {
                        // 到这里插件就启动完成了
                        callback.onCloseLoadingView();
                        callback.onEnterComplete();
                    });
                }
            });

        } else if (fromId == 1012) {
            // 打开Server示例
            Intent pluginIntent = new Intent();
            pluginIntent.setClassName(context.getPackageName(), className);

            executorService.execute(() -> {
                try {
                    InstalledPlugin installedPlugin = installPlugin(pluginZipPath, null, true);//这个调用是阻塞的

                    loadPlugin(installedPlugin.UUID, partKey, isLoad);

                    Intent pluginIntent1 = new Intent();
                    pluginIntent1.setClassName(context.getPackageName(), className);

                    boolean callSuccess = mPluginLoader.bindPluginService(pluginIntent1, new PluginServiceConnection() {
                        @Override
                        public void onServiceConnected(ComponentName componentName, IBinder iBinder) {
                            // 在这里实现AIDL进行通信操作
                        }

                        @Override
                        public void onServiceDisconnected(ComponentName componentName) {
                            throw new RuntimeException("onServiceDisconnected");
                        }
                    }, Service.BIND_AUTO_CREATE);

                    if (!callSuccess) {
                        throw new RuntimeException("bind service失败 className==" + className);
                    }
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            });
        } else {
            throw new IllegalArgumentException("不认识的fromId==" + fromId);
        }
    }


    public InstalledPlugin installPlugin(String zip, String hash, boolean odex) throws IOException, JSONException, InterruptedException, ExecutionException {
        final PluginConfig pluginConfig = installPluginFromZip(new File(zip), hash);
        final String uuid = pluginConfig.UUID;
        List<Future<Object>> futures = new LinkedList<>();
        if (pluginConfig.runTime != null && pluginConfig.pluginLoader != null) {
            Future<Object> odexRuntime = mFixedPool.submit(() -> {
                oDexPluginLoaderOrRunTime(uuid, InstalledType.TYPE_PLUGIN_RUNTIME,
                        pluginConfig.runTime.file);
                return null;
            });
            futures.add(odexRuntime);
            Future<Object> odexLoader = mFixedPool.submit(() -> {
                oDexPluginLoaderOrRunTime(uuid, InstalledType.TYPE_PLUGIN_LOADER,
                        pluginConfig.pluginLoader.file);
                return null;
            });
            futures.add(odexLoader);
        }
        for (Map.Entry<String, PluginConfig.PluginFileInfo> plugin : pluginConfig.plugins.entrySet()) {
            final String partKey = plugin.getKey();
            final File apkFile = plugin.getValue().file;
            Future<Object> extractSo = mFixedPool.submit(() -> {
                extractSo(uuid, partKey, apkFile);
                return null;
            });
            futures.add(extractSo);
            if (odex) {
                Future<Object> odexPlugin = mFixedPool.submit(() -> {
                    oDexPlugin(uuid, partKey, apkFile);
                    return null;
                });
                futures.add(odexPlugin);
            }
        }

        for (Future<Object> future : futures) {
            future.get();
        }
        onInstallCompleted(pluginConfig);

        return getInstalledPlugins(1).get(0);
    }


    public void startPluginActivity(Context context, InstalledPlugin installedPlugin, String partKey, Intent pluginIntent, boolean isLoad) throws RemoteException, TimeoutException, FailedException {
        Intent intent = convertActivityIntent(installedPlugin, partKey, pluginIntent, isLoad);
        if (!(context instanceof Activity)) {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        }
        context.startActivity(intent);
    }

    public Intent convertActivityIntent(InstalledPlugin installedPlugin, String partKey, Intent pluginIntent, boolean isLoad) throws RemoteException, TimeoutException, FailedException {
        loadPlugin(installedPlugin.UUID, partKey, isLoad);
        return mPluginLoader.convertActivityIntent(pluginIntent);
    }

    private void loadPluginLoaderAndRuntime(String uuid) throws RemoteException, TimeoutException, FailedException {
        if (mPpsController == null) {
            bindPluginProcessService(getPluginProcessServiceName());
            waitServiceConnected(10, TimeUnit.SECONDS);
        }
        loadRunTime(uuid);
        loadPluginLoader(uuid);
    }

    protected void loadPlugin(String uuid, String partKey, boolean isLoad) throws RemoteException, TimeoutException, FailedException {
        loadPluginLoaderAndRuntime(uuid);
        Map map = mPluginLoader.getLoadedPlugin();

        if (!map.containsKey(partKey)) {
            mPluginLoader.loadPlugin(partKey);
        }else{
            if (isLoad) {
                mPluginLoader.getLoadedPlugin().remove(partKey);
                mPluginLoader.loadPlugin(partKey);
            }
        }
        Boolean isCall = (Boolean) map.get(partKey);
        if (isCall == null || !isCall) {
            mPluginLoader.callApplicationOnCreate(partKey);
        }
    }
}

**Comment by shifujun** [comment]
看起来你的manager代码运行时找不到ShadowActivity报错的。这个manager是不应该会引用到ShadowActivity类型的。是不是你把Shadow的transform plugin给应用到manager.apk的工程上了？

**Comment by xixi6999** [comment]
十分感谢。
是的。我将loader、runtime的module直接写在manager.apk工程中了。
移除loader、runtime module后重新打包manager.apk，错误解决了。

我的理解是，loader、runtime的module其实和plugin工程没有具体的联系。所以我将其抽取出来，随便放入一个工程（manager.apk工程）。


我理想中的项目结构是这样的。
loader-runtime  -> 输出loader-runtime.zip（包含loader.apk、runtime.apk、config.json）
plugin1  ->输出plugin1.zip（包含plugin1.apk、config.json）
plugin2- >输出plugin2.zip（包含plugin2.apk、config.json）
pluginManager -> 输出manager.apk

loader-runtime、plugin1、plugin2这三者中的config.json的uuid是相同的。


那么我就可以项目启动时，择机提前加载loader-runtime.zip，然后加载插件plugin1、plugin2。
事实上也确实这么实现了。但是我比较疑惑的点是，loader、runtime的module，如果我放入pluginManager工程，此时给pluginManager -> app打包后，就会出现这种错误。
那么问题来了，app module与loader、runtime module并没有依赖关系，为何会影响到app module中的代码呢？

**Comment by shifujun** [comment]
> 我的理解是，loader、runtime的module其实和plugin工程没有具体的联系。所以我将其抽取出来，随便放入一个工程（manager.apk工程）。

没法理解你为什么会做一个“随便”的事情。如果这些工程之间的关系是无差别的，我们为什么要分成loader、runtime、plugin这些模块呢？都放一起多省事。

插件中的Activity等类型被替换成ShadowActivity类型了。这个类型需要由loader去调用，模仿系统行为。因此plugin和loader共同依赖runtime模块。

https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoader.kt#L70-L71

即使你不做任何修改，也是可以预加载loader的。插件安装后是以uuid关联在一起的，与安装前是不是在同一个zip包里没有关系。所以你先下载一个只包含loader.apk和runtime.apk的插件包就可以了。

**Comment by xixi6999** [comment]
好的，十分感谢解答疑惑。
