### ISSUE TITLE
jitpack编译错误

### ISSUE THREAD

**Issue by chenli3238** [Tencent/Shadow#59]
从github fork项目，创建版本，然后jitpack构建编译失败，不能引用，jitpack错误如下：
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sample-runtime:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: /home/jitpack/build/projects/sdk/coding/lint/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':core:common:generateReleaseRFile'.
> java.nio.file.NoSuchFileException: /home/jitpack/build/projects/sdk/coding/lint/build/intermediates/res/symbol-table-with-package/release/package-aware-r.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 22s
553 actionable tasks: 534 executed, 19 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2019-07-22T07:53:36.658571083Z
Exit code: 0

ERROR: No build artifacts found

**Comment by shifujun** [comment]
我从你的版本库里并没有看到提交。

https://github.com/chenli3238/Shadow/commits/dev

如果能直接复现，你没必要描述自己是怎么做的，我看代码就可以了。

**Comment by shifujun** [comment]
另外，我搜了一下jitpack，你指的是https://www.jitpack.io/这个东西吗？

看起来是个CI/CD平台。那么构建出现错误的原因应该只能是你修改了代码但没有说。Shadow的构建是非常标准的Gradle构建，不会有问题的。

如果那个jitpack能用docker环境构建，可以试试这个
https://github.com/shifujun/Shadow/blob/ci-docker-only-sdk-tools/Dockerfile

这是Shadow的CI环境，是非常标准的构建环境，没有什么定制的地方。

**Comment by shifujun** [comment]
有问题欢迎再打开。
