### ISSUE TITLE
插件升级的疑问

### ISSUE THREAD

**Issue by xixi6999** [Tencent/Shadow#590]
我这边想要做一个插件升级的功能。
我的项目中，有多个插件。固定了uuid，保持他们一致。
loader、runtime、manager这些我会预装在宿主assets中，
当宿主启动时，会将这些push到app的私有目录中。

插件工程最后打包的zip中，包含了config.json，及插件apk。

按照sample中的逻辑，当一个插件包被加载过后，不会重新加载zip。这块我修改了源码，可以自主选择是否重新加载zip包。

那么问题来了，插件的版本号控制，我能想到的是，宿主去维护一个版本号。
安装了某个插件后，记录下当前版本号，发现版本号有更新，再去重新加载新下载的zip。

请问shadow框架在此场景中，有没有记录插件版本号的字段及管理？
config.json中，有一个version字段，但该字段并没有被解析到InstalledPlugin中，而且该字段表明的意思似乎并不是插件的版本号。

我在查看源码的时候，发现UUID_NICKNAME字段有注释为插件版本号，可以依据此字段去做插件升级判断逻辑吗？

**Comment by ychxx** [comment]
> 我没有去掉uuid的限制，但是用另一种方式做了规避。
> 虽然可能不符合shadow的设计理念，但符合我这边的业务场景。
> 在此分享一下大概思路。
> 
> 在shadow的脚本中添加partVersion，用于记录每一个part的版本号信息。
> 在manager中判断已加载的partVersion与zip中的partVersion差异，
> 来决定是否重新加载zip包。

我这边也遇到相似的情况，能否帮忙给个demo

**Comment by HeLiHuang** [comment]
> 我没有去掉uuid的限制，但是用另一种方式做了规避。 虽然可能不符合shadow的设计理念，但符合我这边的业务场景。 在此分享一下大概思路。
> 
> 在shadow的脚本中添加partVersion，用于记录每一个part的版本号信息。 在manager中判断已加载的partVersion与zip中的partVersion差异， 来决定是否重新加载zip包。

求代码
