### ISSUE TITLE
插件可以访问宿主中的类吗

### ISSUE THREAD

**Issue by hf529270451** [Tencent/Shadow#592]
插件可以和宿主使用同一个base层吗（插件和宿主在同一进程），比如我的宿主base层里有地图的能力，插件可以直接compileOnly base 去使用地图吗，想通过这种方式有效的减少插件的包体积，改造完发现出发了classnotfoundException

**Comment by yexingyun** [comment]
大佬，想问下怎么解决的，有没有示例呀，看demo看不懂，宿主怎么获取插件里面的类，比如单例类，通过单例启动activity呢？

**Comment by shifujun** [comment]
> 大佬，想问下怎么解决的，有没有示例呀，看demo看不懂，宿主怎么获取插件里面的类，比如单例类，通过单例启动activity呢？

这个issue讨论的是插件访问宿主，跟你说的宿主访问插件是两个方向。这个issue先关了。

你问的可以参考 #368
