### ISSUE TITLE
插件如何访问宿主中的资源

### ISSUE THREAD

**Issue by hf529270451** [Tencent/Shadow#593]
例如我的宿主sdk有个地图的sdk，这个sdk里面会有很多资源（assets和so），插件中compileOnly地图的sdk，现在地图的java代码通过配置白名单可能访问到，但是资源好像没有访问到，请问有什么解决方案吗

**Comment by shifujun** [comment]
我建议你还是考虑改写这个地图SDK的代码，它获取assets和so的调用代码应该都不复杂。可以运用Transform编辑这些调用代码，允许外部提供给它需要的assets或者so，就像shadow的Transform那样。只是你要针对这个SDK进行编辑。

直接构造AssetManager和Resources对象都涉及访问私有API或者Deprecate的API，不够安全。构造Resource对象的公开API是`packageManager.getResourcesForApplication`，可以参考这里：https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt#L45
