### ISSUE TITLE
手机型号兼容问题

### ISSUE THREAD

**Issue by a6685234** [Tencent/Shadow#594]
部分手机报如下错误，目前大部分都是小米，安卓10
java.lang.RuntimeException:Unable to resume activity {com.seuic.kysy/com.example.my_runtime.TakeDeliveryPluginDefaultProxyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
系统源码奔溃在：
java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
android.os.MiuiBinderProxy.callTransact(MiuiBinderProxy.java:40)
android.os.MiuiBinderProxy.callOneWayTransact(MiuiBinderProxy.java:21)
日志很长就不全部复制了我们shadow报在：
com.tencent.shadow.core.loader.delegates.GeneratedShadowActivityDelegate.onPostResume(Unknown Source:2)
com.tencent.shadow.core.runtime.container.GeneratedPluginContainerActivity.onPostResume(GeneratedPluginContainerActivity.java:913)

**Comment by shifujun** [comment]
嗯，单从现有的堆栈看不出来问题可能在哪。先把完整的堆栈传个附件上来吧。

我主要关注的是MiuiBinderProxy和ContainerActivity是在哪一层调用栈上产生关系的。希望能找出来"on a null object reference"的reference是什么哪里的代码，本来是个什么类型的引用。

**Comment by a6685234** [comment]
那个奔溃找不到了，现在是另外一个奔溃,帮忙看一下，全部都是在Android10和11上面奔溃的
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.seuic.kysy/com.example.my_runtime.PluginDefaultProxyActivity}: java.lang.NullPointerException: mPluginActivity must not be null
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
......
Caused by:
java.lang.NullPointerException:mPluginActivity must not be null
com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.getPluginActivity(Unknown Source:6)
com.tencent.shadow.core.runtime.container.PluginContainerActivity.getPluginActivity(PluginContainerActivity.java:65)
com.tencent.shadow.core.runtime.PluginActivity.get(PluginActivity.java:34)
com.tencent.shadow.core.runtime.ShadowActivityLifecycleCallbacks$Wrapper.getPluginActivity(ShadowActivityLifecycleCallbacks.java:101)
com.tencent.shadow.core.runtime.ShadowActivityLifecycleCallbacks$Wrapper.onActivityPreCreated(ShadowActivityLifecycleCallbacks.java:165)
android.app.Application.dispatchActivityPreCreated(Application.java:386)
android.app.Activity.dispatchActivityPreCreated(Activity.java:1222)
android.app.Activity.performCreate(Activity.java:7886)
android.app.Activity.performCreate(Activity.java:7881)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:224)
android.app.ActivityThread.main(ActivityThread.java:7560)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by shifujun** [comment]
onActivityPreCreated出现的NPE另外提issue吧。一个issue应该只讨论一个主题。另外，最好能附上可以复现问题的最小代码。

**Comment by shifujun** [comment]
> onActivityPreCreated

这个Crash应该是 fa1229af 已修复的，更新下代码吧。

**Comment by a6685234** [comment]
好的，我们Shadow有对应的maven仓库了么？放本地maven在jenkins上面不好打包

**Comment by shifujun** [comment]
有的，直接用了Github packages：
https://github.com/Tencent/Shadow/blob/master/projects/sample/maven/host-project/build.gradle#L28-L37
