### ISSUE TITLE
IllegalStateException: 存在转换后被调用方法未实现的问题

### ISSUE THREAD

**Issue by hf529270451** [Tencent/Shadow#596]
我为了解决在插件activity中拿不到真实activity的问题，在shadowActivity中加了一端代码

```
/**
     * 返回Activity对象本身
     *
     * @return 返回Activity对象本身
     */
    public Activity getImplementActivity() {
        return hostActivityDelegator.getHostActivity().getImplementActivity();
    }
```
调用打包命令后报错 IllegalStateException: 存在转换后被调用方法未实现的问题，详见xxxxx，请问该如何解决呢，checkReplacedClassHaveRightMethods这个方法的主要作用是检查啥呢

**Comment by shifujun** [comment]
> 详见xxxxx

所以你为什么不看呢？

**Comment by hf529270451** [comment]
大佬 我看了，我看了  没看懂啥意思
```
Class com.tencent.shadow.core.runtime.ShadowActivity中缺少方法:
getImplementActivity:()Lcom/tencent/shadow/core/runtime/ShadowActivity;被这些类调用了:
com.czb.chezhubang.plugin.map.ShadowHelper

```

我的shadowActiivty有这个方法呢

**Comment by shifujun** [comment]
你添加的getImplementActivity方法返回的类型是`Activity`。Shadow主要的工作就是把`Activity`都替换成`ShadowActivity`，所以`checkReplacedClassHaveRightMethods`方法就是在检查替换后，`ShadowActivity`是否有声明对应的方法。

如果你想在插件里拿到宿主Activity对象，你可以直接让插件跟宿主约定接口获取对象。但是即便拿到Activity对象，插件也是不能用Activity类型操作它的。

**Comment by hf529270451** [comment]
明白了，意思就是插件里所有的activity都会转化成ShadowActivity   那比如说我的插件里 有个系统api需要传入activity，那岂不是会造成ClassCastException或者MethodNotFound ，这种有什么解决方案吗，比如我的插件引入了一个第三方sdk，第三方sdk里面掉用了系统的方法需要传入actiivty，不就不行了吗。

**Comment by shifujun** [comment]
你可以在sample里写一个具体的例子然后push上来说明问题。具体是什么系统方法需要传入Activity？你还是在把”Shadow会把所有Activity都替换成ShadowActivity“这个做法作为一个要对抗的特性来考虑问题，但其实它是帮你在改写代码，使你的代码不要跟系统API发生交互，从而避免系统的限制。

**Comment by hf529270451** [comment]
明白了大佬可能是我想把shadow改成适配我们的项目而没考虑shadow的特性，想问一下比如我插件为了减少包体积，直接compileOnly宿主，比如掉用了宿主的ActivityCompat.requestPermissions(activity, permissions, requestCode); 类似这种的方法，shadow插件会把reqeusetPermissions这个方法改成入餐是shadowactivity，请问这种情况有啥好的思路可以借鉴吗，是不我这种想法不适合插件化只适合动态组件化。

**Comment by shifujun** [comment]
按照Shadow这种屏蔽插件直接访问系统API（比如Activity）的原理，插件是不能直接通过白名单依赖宿主中操作这些本来要被屏蔽的接口的。也就是你能不能让插件直接调宿主中使用Activity类型的接口。

那么像`ActivityCompat.requestPermissions(activity, permissions, requestCode)`这个方法，就需要宿主对其再次封装。比如提供一个`ActivityCompatForPlugin.requestPermissions(object, permissions, requestCode)`，插件可以把Activity对象通过Object类型传给宿主。宿主拿到Object类型再强制类型转换成Activity，再调用原本希望调用的方法。插件可以通过getBaseContext获取到ContainerActivity。也可以通过更复杂的形式，让插件编译runtime模块，从而调用`com.tencent.shadow.core.runtime.container.HostActivityDelegator#getHostActivity`接口获取ContainerActivity。

**Comment by hf529270451** [comment]
大佬您好，我按照您给的思路在宿主中包装了一下 ActivityCompat.requestPermissions(activity, permissions, requestCode) 这个方法，宿主是compileOnly了runtime和activity-container模块， 但是在调用我封装的这个方法时候报错 ClassCastException，说我的插件中的activity不能强转成ShadowActivity，我打印了object的superClass确实是ShadowActivity，但是一强转就会报错，请问可能是什么问题吗
```
public class HostPluginWrapper {

    public static void activityCompatRequestPermissions(Object object, String[] permissions, int requestCode) {
        Activity activity = getRealActivity(object);
        ActivityCompat.requestPermissions(activity, permissions, requestCode)
    }

    public static void butterKnifeBind(Object object) {
        Activity activity = getRealActivity(object);
        ButterKnife.bind(activity);
    }

    private static Activity getRealActivity(Object object) {
        ShadowActivity activity = (ShadowActivity) object;
        return activity.getHostActivity().getImplementActivity();
    }

}

```

**Comment by shifujun** [comment]
插件中改成这样试试：
```
HostPluginWrapper.activityCompatRequestPermissions(this.getBaseContext());
```

插件Activity是以宿主壳子Activity作为baseContext的。https://github.com/Tencent/Shadow/blob/b3c9a9e907e469282e9fdeba97d8ab49289e4c30/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/delegates/ShadowActivityDelegate.kt#L176

**Comment by ClarkRep** [comment]
你好，我也遇到同样的问题了，存在转换后被调用方法未实现的问题：
原因是第三方SDK内部直接调用了 Application.getProcessName()静态方法，请问有什么解决方案么？
