### ISSUE TITLE
启动不了插件问题ShadowAppComponentFactory转换错误

### ISSUE THREAD

**Issue by TorresATaoge** [Tencent/Shadow#597]
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory

**Comment by shifujun** [comment]
你能在Shadow的sample上复现问题吗？可以的话把代码push上来看看。

关于`AppComponentFactory`，Shadow是像处理`Activity`一样，把插件中的全部`AppComponentFactory`类型都替换成`ShadowAppComponentFactory`了。所以预期中`androidx.core.app.CoreComponentFactory`的父类也会被修改为`ShadowAppComponentFactory`。那么它就不会出现"Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory"这样的异常了。

这个设计有一个自动化测试: `com.tencent.shadow.test.cases.plugin_androidx.ComponentFactoryTest`。你可以调试这个自动化测试，要是能复现问题就非常好定位了。

**Comment by BBNO** [comment]
我也遇到这样的问题，请问怎么解决的？

**Comment by BBNO** [comment]
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
 请问这个问题怎么解决？ @shifujun

**Comment by shifujun** [comment]
这是开源交流，你们不分享代码，我也没法帮你们啊。
