### ISSUE TITLE
Manager能力拓展

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Tencent/Shadow#598]
这3个类需要public，这样宿主可以自己模仿 DynamicPluginManager 定义类似 PluginManager 的接口，让 manager 和宿主进行更复杂的交互
```java
import com.tencent.shadow.dynamic.host.ApkClassLoader;
import com.tencent.shadow.dynamic.host.ChangeApkContextWrapper;
import com.tencent.shadow.dynamic.host.ImplLoader;
```

**Comment by shifujun** [comment]
这个`dynamic-host`模块是一个完整的设计，在这个设计中它不希望使用方修改它的行为，所以特别适用了package访问权限和final class关键词。

这里主要约定的是宿主看到的Manager只是一个`PluginManager`接口，只有一个`enter`方法。这是最大限度的视图用一个“main”方法进入Manager逻辑，避免未来增减接口。因为这里的Manager需要动态升级，所以接口必须足够稳定。

`ApkClassLoader`、`ChangeApkContextWrapper`、`ImplLoader`三者都是动态加载Manager等apk的工具类。这些类型不应该暴露给Manager的使用方。因为宿主不应该需要知道apk是如何动态加载的。

如果是模仿`dynamic-host`的设计定义一套类似的接口和动态加载机制，理论上来说应该抽出这些工具类作为一个单独的模块。但如果没有足够通用的场景，只为一个业务复用，也许直接复制代码更合适一些。

**Comment by LinXueyuanStdio** [comment]
那可以把这些工具类抽出来单独一个模块嘛？
dynamic-host模块的设计我可以理解，平时也没必要去改动（虽然Updater的设计有些画蛇添足）

**Comment by LinXueyuanStdio** [comment]
我可以帮忙提相关的pr，也可以写个笔记，针对宿主自定义接口，给出一个apk里动态化的实现
把这些工具类抽成一个模块后，以往的”宿主使用插件资源“的需求也可以容易实现一点点

**Comment by shifujun** [comment]
OK。我觉得也可以。dynamic-host这里对于插件包的管理是有设计的，这块我们也可能进行迭代改进。所以把这里更通用的部分拆出来也是有帮助的。

那我们抽出一个模块来专门做从一个apk里动态加载接口以及Context处理的功能吧。

你提个PR，我们可以一起看看细节。保持兼容性比较重要。

**Comment by LinXueyuanStdio** [comment]
写好啦 #600
