### ISSUE TITLE
多插件多进程问题

### ISSUE THREAD

**Issue by ysbrowser** [Tencent/Shadow#599]
主进程 持有一个 PluginManagerThatSupportMultiLoader 对象 当这个对象连接各个插件的PPS时  会回调onPluginServiceConnected,这里刚好把自身的MultiLoaderPpsController mPpsController; 这个属性重置掉了，这样设计是不是有问题， mPpsController 是不是应该是个Map  如HashMap<PartKey, MultiLoaderPpsController> mPpsControllers;

**Comment by shifujun** [comment]
这个feature #202 应该是预计在同一个进程里使用多个Loader实现，所以它预期也是只有一个PPS实例的。如果manager要管理多个PPS，可能需要再继承`BaseDynamicPluginManager`实现一个。
