### ISSUE TITLE
使用文档什么时候有

### ISSUE THREAD

**Issue by godlikewangjun** [Tencent/Shadow#60]
看的一脸懵逼，想集成到现有项目测试，有些多余的东西需要去除，无从下手

**Comment by shifujun** [comment]
可以在wiki中看到一些文章，这些文章会作为未来文档的草稿。所以我们目前在建设文档中。

跟未完成的文档就开放出来一样，Shadow目前也没有服务化。我们只是以开源的标准撰写了Shadow的代码，并将它尽早的开源出来。我们相信一部分熟悉插件框架的人，看到Shadow开源的代码对他们来说是有帮助的。这其中的一部分也有可能能直接采用Shadow的代码，和我们一起继续开发Shadow，将其服务化。

如果你感到无从下手，很可能因为对Gradle构建不是很熟悉，对插件框架领域也不太了解。建议先读一下我们已有的文章，再实际调试一下Shadow的代码。我们提供了可以源码依赖SDK的sample，可以让你很方便的改动任何部分都直接运行生效。这是我们开源时对项目可用性的最低保证，希望有能力看懂代码的人调试起来是方便的。

对于完整文档何时能有，我们暂时无法给出确切时间。因为开源Shadow没有商业目的，而我们也有正常的业务工作。但我们还是会尽量在这个领域和大家交流的。

**Comment by liupeng110** [comment]
能不能加个统一维护的平台.像360replugin那样,他们一开始也是没有后端 但是现在他们连后台带插件更新是一整套的。

**Comment by shifujun** [comment]
> 能不能加个统一维护的平台.像360replugin那样,他们一开始也是没有后端 但是现在他们连后台带插件更新是一整套的。

加一个统一维护平台的工作量不是一两个星期那么简单的。Shadow开源出来不是为了给大家提供插件服务。RePlugin那样是在给大家提供服务的。Shadow目前只是开源交流技术。你不会希望我们没法提供服务就完全不开源了吧？

未来视大家对Shadow的需求和我们自身业务在管理平台建设上的进度，我们是有可能提供服务化的Shadow的。目前我们在内部插件管理平台的建设上已经在向通用化方向发展了。大家也可以向Shadow贡献这方面的代码，我们可以一起共建出来。

希望大家能理解开源和提供服务的区别，二者既不是绑定的也不是冲突的。
