### ISSUE TITLE
启动a插件在启动b插件找不到类

### ISSUE THREAD

**Issue by ychxx** [Tencent/Shadow#601]
1.宿主启动插件a正常
2.宿主启动插件b正常
3.宿主启动插件a，关闭插件a，在启动插件b报错
 java.lang.RuntimeException: android.content.ActivityNotFoundException: Unable to find explicit activity class ***; have you declared this activity in your AndroidManifest.xml?
请问这种情况该怎么解决，还有宿主和插件的AndroidManifest.xml在哪里合并的

**Comment by shifujun** [comment]
SDK没有提供"启动插件"这样的接口，所以你是怎么“启动插件”的需要看看代码。你可以把复现问题的代码push上来看看。

报ActivityNotFound一般是因为试图启动的插件Intent中组件并没有被loader加载，所以loader不知道这是一个插件的Intent。那么就认为这是一个系统中的Intent，所以会直接交给系统启动，进而就发生ActivityNotFound了。

宿主和插件的Manifest没有合并。对于系统来说，安装的就是宿主的Manifest。插件的Manifest是loader自己解析的，然后跟宿主中的对应壳子进行配对操作，以便将插件的Intent转换为宿主的Intent再交给系统。理解这一过程最好是debug一下插件Activity的启动流程。

**Comment by xixi6999** [comment]
a、b的uuid不一样吧

**Comment by limingboGitHub** [comment]
我也是试图这样操作，想在宿主APP中启动插件A，back回来，再启动插件B，就报这个错误。这种业务场景要怎么实现呢。提问者说的启动插件应该就是指调用PluginManager的enter方法。我在宿主APP中通过该方式成功启动了插件A，back回来，再调用PluginManager的enter方法传递插件B的Zip路径和className，就报这个一样的错。

感觉自己对Activity启动，多进程这些底层的知识了解的太少了，理解Shadow框架有点费力。给作者和Shadow点个赞，特别好。

**Comment by shifujun** [comment]
如果说是A、B插件的uuid不一致的情况。情况是这样的，Shadow主要开源分享的是`core.loader`和`core.transform`配合将Activity动态启动这部分的能力。但是光有这两部分肯定是演示不起来的。所以我们就是把业务中用到的插件管理的逻辑尽可能通用化的抽出来了。

在这个`core.manager`的管理逻辑中，一个manager只管理一个”插件“，这个”插件“可以包含多个apk，也就是可以包含A、B、C多个插件。这所谓的”一个“，是指逻辑上的一个整体，这个整体的各个部分要能协同工作在一起。然后，肯定是存在不能协同工作的apk，比如同一个apk的不同版本，所以我们需要一个UUID这样的版本控制区分它们。

**Comment by ychxx** [comment]
很抱歉现在回复。
我尝试触发这个报错的场景写了一个[demo](https://github.com/ychxx/ShadowDemo)
在项目plugin1（插件a）和plugin2（插件b）里都加入一个自己写的基础库（implementation 'com.github.ychxx:ShadowJetpack:0.99998'）后就会触发这个报错，没加入时插件a，b可以互相切换。
请问该怎么解决这个问题呢？

**Comment by shifujun** [comment]
@ychxx 我看你的demo只有一个提交记录，完全看不出来改动是什么。按理说加入一个库不会引起任何插件加载过程的问题。这是不相关的两个过程。你多implementation一个库，只是影响插件apk内部的代码。

还是建议你在Shadow的sample中调试，commit后我们可以清楚的看到你修改了什么。另外，你说的报错到底是找不到哪一个activity class，这个class原本应该在哪？你是否检查了你的插件a,b的uuid是否一致？以及是否都对它们执行了`com.tencent.shadow.dynamic.loader.PluginLoader#loadPlugin`。

debug这个过程可以关注这行代码的执行：
https://github.com/Tencent/Shadow/blob/a75c81cd644114b22832ab6f411658a9ef5ffd22/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt#L177

推荐你在Shadow的sample中调试也是因为它可以方便的debug SDK里任何一处代码。

**Comment by ychxx** [comment]
这样应该可以看出修改记录了
[正常](https://github.com/ychxx/ShadowDemo/commit/6581550a420d5a81b238663773080402b9aea66f)
[修改后报错](https://github.com/ychxx/ShadowDemo/commit/adbb90b4d917b9082475509cd1821411a8ff348d)

**Comment by shifujun** [comment]
又看了一下，报错是:`重复添加Component：ComponentInfo{com.yc.shadowdemo/com.huawei.hms.hmsscankit.ScanKitActivity}`

如果Shadow允许不同apk添加同名的Activity，我们显然不知道该启动哪个apk里的Activity合适了。

看了下： `plugin1/build/intermediates/manifest_merge_blame_file/debug/manifest-merger-blame-debug-report.txt` 应该是`com.huawei.hms:scanplus:1.3.1.300`引入的。大概是`com.github.ychxx:ShadowJetpack`依赖的包吧。

你大概应该应用https://developer.android.com/studio/build/manifest-merge#node_markers 提到的`tools:node="remove"`去掉其中一个引入的Activity。

**Comment by ychxx** [comment]
我尝试了添加tools:node="remove"可以解决这个报错。不过由于引用的第三方库比较多，导致ShadowJetpack清单里需要写上第三方库的Activity，service，provider非常多。
所以我想在ComponentManager的common方法修改成，移除之前添加的，在往里面添加新，这可以么
```
fun common(pluginComponentInfo: PluginComponentInfo, componentName: ComponentName) {
    if (pluginInfoMap.containsKey(componentName)) {
        pluginInfoMap.remove(componentName)//移除之前添加的
    }
    packageNameMap[pluginComponentInfo.className!!] = pluginInfo.packageName
    val previousValue = pluginInfoMap.put(componentName, pluginInfo)
    pluginComponentInfoMap[componentName] = pluginComponentInfo
 }

**Comment by shifujun** [comment]
针对你具体的业务，你可以判断这样移除已经添加的同名组件是否安全，但显然这作为SDK的逻辑并不合适。

你是不是可以考虑把重复的第三方库依赖作为一个单独的公共插件呢？

**Comment by ychxx** [comment]
明白了，非常感谢您的耐心回答
