### ISSUE TITLE
中间层出现数据库异常

### ISSUE THREAD

**Issue by a6685234** [Tencent/Shadow#604]
java.lang.IllegalArgumentException:java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.seuic.kysy/databases/shadow_installed_plugin_dbTakeDeliveryPluginManager
2
com.kysy.shadow_plugin_manager.HostPluginManager$6.run(HostPluginManager.java:204)
3
......
4
Caused by:
5
java.lang.IllegalStateException:attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.seuic.kysy/databases/shadow_installed_plugin_dbTakeDeliveryPluginManager
6
android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
7
android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:564)
8
com.tencent.shadow.core.manager.installplugin.InstalledDao.insert(InstalledDao.java:64)
9
com.tencent.shadow.core.manager.BasePluginManager.onInstallCompleted(BasePluginManager.java:113)
10
com.kysy.shadow_plugin_manager.HostPluginManager.installPlugin(HostPluginManager.java:97)
11
com.kysy.shadow_plugin_manager.HostPluginManager$6.run(HostPluginManager.java:192)
12
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
13
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
14
java.lang.Thread.run(Thread.java:764)

**Comment by shifujun** [comment]
看起来这里不应该close db
https://github.com/Tencent/Shadow/blob/b3c9a9e907e469282e9fdeba97d8ab49289e4c30/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/InstalledDao.java#L174

但是好像没设计在哪里close。我再看看怎么修复好。
