### ISSUE TITLE
Application.getProcessName()未实现

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#606]
你好，我也遇到同样的问题了，存在转换后被调用方法未实现的问题：
原因是第三方SDK内部直接调用了 Application.getProcessName()静态方法，请问有什么解决方案么？

_Originally posted by @ClarkRep in https://github.com/Tencent/Shadow/issues/596#issuecomment-916695977_

**Comment by ClarkRep** [comment]
这个有什么好的解决方案么？目前卡在这里了，谢谢啊

**Comment by shifujun** [comment]
这个很简单的，补充一下就行了。我写一下吧。
