### ISSUE TITLE
> > 对于shadow工程的loader模块如果用远程依赖基本没法断点，真的不太好调试

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#609]
> > 对于shadow工程的loader模块如果用远程依赖基本没法断点，真的不太好调试
> 
> 这个问题的根本原因与用kotlin没太大关系。即便是Java，经过Proguard也是基本没法断点的。能否断点主要看debug信息，尤其是行号是否得以保留。
> 
> 如果问题不是Proguard等release过程引起的，那么完全可以把loader模块替换成debug版。这个调试成本似乎不高的，因为我也调试过这种场景。

我说的就是debug版本没有混淆的工程，主要是loader模块是kt写，如果直接依赖loader.jar的话，定位会到源码kt文件里面去，断点无法断下来，只能依赖源码才能调试

_Originally posted by @qq8803128 in https://github.com/Tencent/Shadow/issues/603#issuecomment-917917760_

**Comment by shifujun** [comment]
我也又调试了一下`projects/sample/maven`，确实是不能直接调试loader源码的。这也是预期内的，因为loader这里发布时就进行了Proguard：
https://github.com/Tencent/Shadow/blob/a75c81cd644114b22832ab6f411658a9ef5ffd22/projects/sdk/core/loader/build.gradle#L29-L32

在`buildScripts/gradle/maven.gradle`里将这个loader换成debug版，也就是没有Proguard过的版本，就可以调试了。
```
Index: buildScripts/gradle/maven.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/buildScripts/gradle/maven.gradle b/buildScripts/gradle/maven.gradle
--- a/buildScripts/gradle/maven.gradle	(revision a75c81cd644114b22832ab6f411658a9ef5ffd22)
+++ b/buildScripts/gradle/maven.gradle	(date 1631520225260)
@@ -1,7 +1,7 @@
 task buildSdk() {
     dependsOn gradle.includedBuild('core').task(':gradle-plugin:assemble')
     dependsOn gradle.includedBuild('core').task(':common:jarReleasePackage')
-    dependsOn gradle.includedBuild('core').task(':loader:assembleRelease')
+    dependsOn gradle.includedBuild('core').task(':loader:assembleDebug')
     dependsOn gradle.includedBuild('core').task(':manager:assembleRelease')
     dependsOn gradle.includedBuild('core').task(':runtime:jarReleasePackage')
     dependsOn gradle.includedBuild('core').task(':activity-container:jarReleasePackage')
@@ -168,7 +168,7 @@
             groupId coreGroupId
             artifactId 'loader'
             version publicationVersion
-            artifact("$corePath/loader/build/outputs/aar/loader-release.aar")
+            artifact("$corePath/loader/build/outputs/aar/loader-debug.aar")
             artifact sourceJar("loader", "$corePath/loader")
 
             pom.withXml {
```

能否调试的关键还是看最终得到的apk中，这些类的是否还有source字段：
![image](https://user-images.githubusercontent.com/3535204/133048010-2d2bba8d-4167-4a8f-8047-9077352a77b5.png)

如果你说的问题是这种场景，可以试试。否则再详细描述下你的操作吧。

**Comment by qq8803128** [comment]
我这边是下载shadow源码编译并发布了package，然后自己新建工程远程依赖shadow相关的库，我刚刚观察了下，远程依赖shadow的相关库
在loader模块中.source全部是"",如图
![image](https://user-images.githubusercontent.com/15795651/133051924-0f483934-37db-4f15-acef-99c7a00e292e.png)
在com.tencent.shadow.core.loader下面的包全部都是空，loader插件不在这个包名下面的其他类基本都存在.source路径
![image](https://user-images.githubusercontent.com/15795651/133051815-73808a4e-c2dc-4c6c-8f25-4989a4975b8b.png)
![image](https://user-images.githubusercontent.com/15795651/133051875-05f7f727-2ac0-46d3-99a3-fe1cc1a008d9.png)


    implementation "com.tencent.shadow.dynamic:loader-impl:$shadow_version"

    compileOnly "com.tencent.shadow.core:activity-container:$shadow_version"
    compileOnly "com.tencent.shadow.core:common:$shadow_version"
    compileOnly "com.tencent.shadow.dynamic:host:$shadow_version"
这个是我自己发布的github package这样依赖的

**Comment by shifujun** [comment]
所以你可以在本地发布一个debug版的loader，然后就可以调试了。

**Comment by qq8803128** [comment]
> 所以你可以在本地发布一个debug版的loader，然后就可以调试了。

github的package是包含源码的啊，远程依赖会将源码下下来的
![image](https://user-images.githubusercontent.com/15795651/133052980-01282208-0026-4a4f-a9ce-27c0a20358b6.png)
![image](https://user-images.githubusercontent.com/15795651/133053037-8a8c11ba-b286-48ff-852e-5a4d22f92a50.png)
所以很奇怪  就loader下面的无法调试

**Comment by qq8803128** [comment]
然后我这样测试了下，直接新建一个工程，直接在app模块下面

implementation "com.tencent.shadow.dynamic:loader-impl:$shadow_version"

直接在app里面调用AdapterPackage.INSTANCE.checkPackageName("as",getPackageName());
然后在checkPackageName下断点也没法断下来
![image](https://user-images.githubusercontent.com/15795651/133054444-62179b71-7507-461a-83ea-347a7dc74020.png)

**Comment by shifujun** [comment]
这里下载下来的源码只是供IDE跳转展示用的，是通过maven管理起来的。这一过程和Debug没有任何关系。Debuger需要从运行的JVM获取到正在执行的代码所在的类的源文件名和行号。因此需要你反编译看到的`.source`，IDE拿到这个源文件名才会跳转到已知的源文件中。如果不存在源文件，IDE一般可以反编译class作为源文件。所以为了不让IDE反编译源文件，我们在maven发布时带上了源文件的zip包。

**Comment by shifujun** [comment]
你确定有按照我前面写的重新发布debug版本的loader了吗？缺失`.source`的包不是`com.tencent.shadow.dynamic:loader-impl`，而是`com.tencent.shadow.core:loader`，它是前者的依赖。

> 在buildScripts/gradle/maven.gradle里将这个loader换成debug版，也就是没有Proguard过的版本，就可以调试了。

```
Index: buildScripts/gradle/maven.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/buildScripts/gradle/maven.gradle b/buildScripts/gradle/maven.gradle
--- a/buildScripts/gradle/maven.gradle	(revision a75c81cd644114b22832ab6f411658a9ef5ffd22)
+++ b/buildScripts/gradle/maven.gradle	(date 1631520225260)
@@ -1,7 +1,7 @@
 task buildSdk() {
     dependsOn gradle.includedBuild('core').task(':gradle-plugin:assemble')
     dependsOn gradle.includedBuild('core').task(':common:jarReleasePackage')
-    dependsOn gradle.includedBuild('core').task(':loader:assembleRelease')
+    dependsOn gradle.includedBuild('core').task(':loader:assembleDebug')
     dependsOn gradle.includedBuild('core').task(':manager:assembleRelease')
     dependsOn gradle.includedBuild('core').task(':runtime:jarReleasePackage')
     dependsOn gradle.includedBuild('core').task(':activity-container:jarReleasePackage')
@@ -168,7 +168,7 @@
             groupId coreGroupId
             artifactId 'loader'
             version publicationVersion
-            artifact("$corePath/loader/build/outputs/aar/loader-release.aar")
+            artifact("$corePath/loader/build/outputs/aar/loader-debug.aar")
             artifact sourceJar("loader", "$corePath/loader")
 
             pom.withXml {

```

**Comment by qq8803128** [comment]
好的，我重新去更新下包试试

**Comment by qq8803128** [comment]
的确是这样的，loader好像要发布debug版本才行- -
