### ISSUE TITLE
插件Service不是运行在Manifest里声明的进程

### ISSUE THREAD

**Issue by ClarkRep** [Tencent/Shadow#610]
翻了一下源码，发现Service的实现和Activity不一样，并不是使用代理方式，而是模拟了Service的运行流程，所以有个问题，就是插件的Service额外指定了一个进程的话是不生效的，这块有没有什么好的解决办法啊？

**Comment by shifujun** [comment]
从原理上来讲，Service的binder只要随便经过一个binder跨进程通信，就会被注册到内核里成为可以跨进程通信的binder。所以插件Service的binder都委托给PPS帮忙传递了。选择用PPS传递插件Service的binder只是因为省事。

如果插件有一个Service需要在另外的进程，那么其实和Activity需要在另外的进程一样。每个插件进程都要有一个PPS，进而有Loader实例。这么来看，在另外进程的Service或Activity其实可以作为一个单独的插件启动的，因为每个进程都是比较独立的，相互之间没有什么相关性。
