### ISSUE TITLE
androidx的布局适配

### ISSUE THREAD

**Issue by liluyue** [Tencent/Shadow#614]
因为androidx是通过setFactory2来变换布局信息的，而插件的getLayoutInflater()丢失了androidx全局设入的factory2，
导致布局丢失了androidx的风格。我本地是通过这种方式做的暂时修复。希望您能修复一下

```
 @NonNull
    @Override
    public LayoutInflater getLayoutInflater() {
        if (inflater == null) {
            inflater = super.getLayoutInflater();
            inflater.setFactory2(LayoutInflater.from(this).getFactory2());
        }
        return inflater;
    }
```

**Comment by shifujun** [comment]
你使用的代码已经包含 c710a18c 了吗？提交注释说明了当时的情况，也是缺失了AndroidX自动安装的Factory。如果包含了，能方便修改一下`LiveDataWithActivityTestActivity`，演示一下怎么复现问题吗？可以在`androidx-cases-app`模块运行调试非插件环境下的表现。在`LiveDataWithActivityTest`运行自动化测试调试插件环境下的表现。

**Comment by liluyue** [comment]
好的，我试一下

**Comment by liluyue** [comment]
[3f25c5c](https://github.com/liluyue/Shadow/commit/3f25c5c84ab602190f4390012018fba5fd02c691)中包含了复现场景，由于对自动化测试不熟，我用了log的方式打印异常数据
