### ISSUE TITLE
为什么一执行gradlew publish命令,各个module就会自动生成了build/xxx.jar，看不懂

### ISSUE THREAD

**Issue by YiScond** [Tencent/Shadow#616]

**Comment by shifujun** [comment]
是指原本aar的module生成了jar包吗？那些模块都有这段配置：
https://github.com/Tencent/Shadow/blob/d9fd8cdbdeaa449f296826457d3cf55c5e7b2bdd/projects/sdk/core/common/build.gradle#L23-L44

`buildSdk`任务依赖了它们：
https://github.com/Tencent/Shadow/blob/d9fd8cdbdeaa449f296826457d3cf55c5e7b2bdd/buildScripts/gradle/maven.gradle#L3

publish任务依赖的生成pom任务又依赖了`buildSdk`
https://github.com/Tencent/Shadow/blob/d9fd8cdbdeaa449f296826457d3cf55c5e7b2bdd/buildScripts/gradle/maven.gradle#L93

**Comment by YiScond** [comment]
`def setGeneratePomFileAndDepends(publicationName) {
    model {
        tasks."generatePomFileFor${publicationName.capitalize()}Publication" {
            destination = file("$buildDir/pom/$publicationName-pom.xml")
            dependsOn(buildSdk)
            dependsOn(lintSdk)
        }
    }
}`

**Comment by shifujun** [comment]
这个依赖关系是`maven-publish`插件内部的实现。从它的文档里可以找到这个任务。

https://docs.gradle.org/current/userguide/publishing_maven.html

**Comment by YiScond** [comment]
行 我再看看 谢谢大佬
