### ISSUE TITLE
请问有删除老的管理插件的接口吗

### ISSUE THREAD

**Issue by liluyue** [Tencent/Shadow#621]
老的插件管理的文件累积太大了，想要删除。
需要一个获取老的插件管理资源路径的接口

**Comment by shifujun** [comment]
是有这样一个接口：https://github.com/Tencent/Shadow/blob/a499e0d592e637e4939369ac44a694eecc1731da/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L248

插件删除操作有可能和正在运行的插件产生IO操作竞争，使插件卡顿。所以我们实际在业务中何时删除旧插件是具体业务具体设计的。

**Comment by liluyue** [comment]
确认一下：这个方法 应该没有做重复安装的处理吧。是需要通过uuid来检查是否需要再次安装吗。com.tencent.shadow.sample.manager.FastPluginManager#installPlugin

**Comment by liluyue** [comment]
删除插件的代码应该有问题，非空目录直接删应该删除不了
` ``
   private boolean deletePart(InstalledPlugin.Part part) {
        boolean suc = true;
        if (!part.pluginFile.delete()) {
            suc = false;
        }
        if (part.oDexDir != null) {
            if (!part.oDexDir.delete()) {
                suc = false;
            }
        }
        if (part.libraryDir != null) {
            if (!part.libraryDir.delete()) {
                suc = false;
            }
        }
        return suc;
    }
```

**Comment by shifujun** [comment]
这块代码确实用的少。我找时间写点自动化测试再优化下吧。也欢迎贡献代码。😅

**Comment by liluyue** [comment]
这个是我对问题的修改。
还有一个很影响开发的问题，插件导致的crash，信息经常在日志里找不到，导致定位问题很麻烦！！
```
    private boolean deletePart(InstalledPlugin.Part part) {
        boolean suc = true;
        if (!part.pluginFile.delete()) {
            suc = false;
        }
        if (part.oDexDir != null && part.oDexDir.isDirectory()) {
            try {
                MinFileUtils.cleanDirectory(part.oDexDir);
            } catch (IOException e) {
                suc = false;
            }
            if (!part.oDexDir.delete()) {
                suc = false;
            }
        }
        if (part.libraryDir != null && part.libraryDir.isDirectory()) {
            try {
                MinFileUtils.cleanDirectory(part.libraryDir);
            } catch (IOException e) {
                suc = false;
            }

            if (!part.libraryDir.delete()) {
                suc = false;
            }
        }
        return suc;
    }

```

**Comment by liluyue** [comment]
这是我暂时做清理逻辑修复，不正规。但是有助于描述问题。
[插件清理问题修复：因为InstalledPlugin中少了根路径信息，所以无法彻底清理。这里用了目录层级的推理去清理整个目录。](https://github.com/liluyue/Shadow/commit/b802b954296a2469ee292c193f74b5965fab7f76)
