### ISSUE TITLE
插件导致的crash，信息经常在日志里找不到

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#622]
还有一个很影响开发的问题，插件导致的crash，信息经常在日志里找不到，导致定位问题很麻烦！！

_Originally posted by @liluyue in https://github.com/Tencent/Shadow/issues/621#issuecomment-925488780_

**Comment by shifujun** [comment]
这个问题值得专门说一下。Android系统在Activity Crash了之后，会试图打开前一个Activity。由于前一个Activity可能也在插件里，如果插件Crash了，系统就会重启插件进程。插件在ContainerActivity里有逻辑兼容这种情况，会主动finish。否则就会出现找不到插件类的新Crash。

建议调试时关注插件进程的pid，根据pid过滤日志。

Shadow有不会主动吞Crash的设计原则。如果确实发现Shadow吞掉了RuntimeException，应该是bug。所以插件由于Shadow造成的Crash一定可以在日志里看到，或者被上层代码捕获到。

**Comment by liluyue** [comment]
查了一下，是线程池用了FutureTask，将异常忽略掉了。

**Comment by shifujun** [comment]
哪行代码呢？`Future`应该在`get()`时会抛出封装的异常的。

**Comment by liluyue** [comment]
类似这种，是匿名形式的，不会调用get()
```
  singlePool.submit(new Runnable() {
            @Override
            public void run() {
                preparePlugin();
            }
        });
```

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/0e5d9d8d935d296bc40555b07d8396ba539de214/projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/PluginHelper.java#L69

这里是sample的代码，确实不严谨，它没有等这个preparePlugin执行完，所以没用Future.get().
