### ISSUE TITLE
hostWhiteList的规则

### ISSUE THREAD

**Issue by liluyue** [Tencent/Shadow#624]
hostWhiteList 有通配符规则吗？
比如为了简便，通常将一个包名用作与插件交互，但是为了功能的区分，会在该报名下新建很多子包名，如果有通配符规则，那列表的维护将容易的多（不需要一个个添加子包名）

**Comment by shifujun** [comment]
我理解是这种场景？
https://github.com/Tencent/Shadow/blob/0e5d9d8d935d296bc40555b07d8396ba539de214/projects/sdk/core/loader/src/test/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoaderTest.kt#L224-L225

**Comment by liluyue** [comment]
对

**Comment by LinXueyuanStdio** [comment]
好像通配符规则有瑕疵
如果要某个包下的所有类都公开，必须同时使用所有通配符

比如希望公开`com.shadow.sample.host`下的所有类
需要写三行：
`com.shadow.sample.host`    公开形如 `com.shadow.sample.host.MainActivity` 的类，一级
`com.shadow.sample.host.*`  公开形如 `com.shadow.sample.host.activity.MainActivity` 的类，二级
`com.shadow.sample.host.**` 公开形如 `com.shadow.sample.host.activity.main.MainActivity` 的类，大于三级

有点丑

**Comment by liluyue** [comment]
也还好，起码比没有强

**Comment by LinXueyuanStdio** [comment]
我感觉中更好的通配符应该是这样的：
1. `com.shadow.sample.host.MainActivity` 公开一个类，即一个类文件 `MainActivity.java`
2. `com.shadow.sample.host.*` 公开类列表，即包`com.shadow.sample.host`下的所有一级类，如公开 `com.shadow.sample.host.MainActivity` 而不公开 `com.shadow.sample.host.activity.MainActivity`
3. `com.shadow.sample.host.**` 公开包下所有类，即包`com.shadow.sample.host`下的所有类，同时公开`com.shadow.sample.host.MainActivity`和`com.shadow.sample.host.activity.MainActivity`

这样既可以细粒度（精确到类），也可以粗粒度（精确到包）

**Comment by liluyue** [comment]
和混淆的规则类似：
通配符*，匹配任意长度字符，但不含包名分隔符(.)
通配符**，匹配任意长度字符，并且包含包名分隔符(.)

**Comment by shifujun** [comment]
现有实现的代码确实很值得优化。最初也只是供业务依赖少量的类设计实现的。语法够当时的业务用，实现又比较简单。

重新考虑的话，一是匹配的性能要优化好。二是语法我觉得最好是直接复用大家都熟悉的，而不是重新发明。那么这个领域可能直接复用Proguard的语法比较好。

**Comment by LinXueyuanStdio** [comment]
我的意思是现在的`fun String.inPackage`函数没有完全实现Proguard的*和**这两个语法。。。
会导致`com.shadow.sample.host.**`不能公开`com.shadow.sample.host.MainActivity`

**Comment by shifujun** [comment]
对。现有实现有隐含约束，白名单需要以包为单位设置。这在当初是为了影响业务代码的设计，不希望插件随便依赖宿主里的任何类。希望宿主里主动声明一个新的包，在里面放一些设计上就为了插件来直接访问的类，这些类的接口要足够稳定，特别管理。

**Comment by LinXueyuanStdio** [comment]
随便找一篇博客，https://blog.csdn.net/qq_30379689/article/details/81589428
```java
# 一颗星表示keep当前本包下的类名，子包下的类名是会被混淆的
-keep class com.example.hensen.*
# 两颗星表示keep当前本包下的类名和子包下的类名
-keep class com.example.hensen.**
# 表示keep当前类名
-keep class com.example.hensen.net.NetWorkCache
# 表示keep当前类的内部类的类名
-keep class com.example.hensen.net.NetWorkCache$NetWorkBean
```
hostWhiteList这部分确实应该好好优化了

另外，很常见的操作是宿主和插件共用一个SDK，出于减少插件包体积，会把宿主的SDK都暴露给插件。
SDK里有复杂的包结构，现在的实现导致每个SDK要写3行公开规则，所以每个类的判定时都会多判定3个规则，不知道对性能有没有影响。

有人在这个操作上踩坑了，我不说是谁~

**Comment by shifujun** [comment]
插件希望复用宿主中的SDK以减少插件包体积，这个目的好理解。

但是直接将宿主中的SDK类暴露给插件使用，与宿主和插件的版本多对多关系是相违背的。这样宿主不能再方便的更新SDK版本了。因为毕竟是SDK，代码不受宿主控制，接口可能发生变化。而插件是用旧版本的SDK编译的，这会发生不可控的风险。

安全的做法只能是宿主专门为插件稳定的接口，然后依赖可更新的SDK实现这些接口。这样做才能保证多对多版本关系下稳定的类依赖关系，同时SDK还是可以更新版本的。

如果仅仅考虑复用，又有自信保证多对多版本下不会有问题，那么完全可以直接把白名单机制去掉，让插件按通常的双亲委派逻辑优先从宿主加载类就可以了。

**Comment by qq8803128** [comment]
> 随便找一篇博客，https://blog.csdn.net/qq_30379689/article/details/81589428
> 
> ```java
> # 一颗星表示keep当前本包下的类名，子包下的类名是会被混淆的
> -keep class com.example.hensen.*
> # 两颗星表示keep当前本包下的类名和子包下的类名
> -keep class com.example.hensen.**
> # 表示keep当前类名
> -keep class com.example.hensen.net.NetWorkCache
> # 表示keep当前类的内部类的类名
> -keep class com.example.hensen.net.NetWorkCache$NetWorkBean
> ```
> 
> hostWhiteList这部分确实应该好好优化了
> 
> 另外，很常见的操作是宿主和插件共用一个SDK，出于减少插件包体积，会把宿主的SDK都暴露给插件。
> SDK里有复杂的包结构，现在的实现导致每个SDK要写3行公开规则，所以每个类的判定时都会多判定3个规则，不知道对性能有没有影响。
> 
> 有人在这个操作上踩坑了，我不说是谁~

根据插件类型自己修改源码，对于loader和manager这样的白名单机制
```java
public interface WhiteList {
    String[] sWhiteList = new String[]{"com.tencent.host.shadow","com.tencent.shadow.core.common"};
}
```
自己在module里面新建WhiteListHelper工具类
```java
public final class WhiteListHelper {
    public static final String[] arrayOf(String... args){
        if (args == null){
            return new String[]{};
        }else{
            List<String> list = new ArrayList();
            for (String arg : args){
                if (arg.endsWith(".**")){
                    String pak0 = arg.replace(".**","");
                    String pak2 = arg;
                    list.add(pak0);
                    list.add(pak2);
                }else if (arg.endsWith(".*")){
                    String pak1 = arg.replace(".*","");
                    list.add(pak1);
                }else{
                    list.add(arg);
                }
            }

            String[] array = new String[list.size()];
            list.toArray(array);
            return array;
        }
    }
}

//修改WhiteList 
public interface WhiteList {
    String[] sWhiteList = WhiteListHelper.arrayOf(
        "com.tencent.host.shadow","com.tencent.shadow.core.common",
        "retrofit2.**"
    );//new String[]{"com.tencent.host.shadow","com.tencent.shadow.core.common"};
}
```
对于自己的业务插件，由于shadow是读取json配置生成的，因此可以修改gradle-plugin源码的
PackagePluginExtension中的写白名单的json配置
```java
if (i.hostWhiteList.isNotEmpty()) {
                val hostWhiteListJson = JSONArray()
                for (k in i.hostWhiteList) {
                    hostWhiteListJson.add(k)//修改这句代码，类似我上面提到的WhiteListHelper 自己检测.**和.*生成
                }
                pluginObj["hostWhiteList"] = hostWhiteListJson
            }
```
@shifujun 我当初开始接触shadow的时候也和 @LinXueyuanStdio 一样觉得有问题,可能是混淆语法写习惯了吧，但是用的时间长了，我觉得就应该是shadow设计的那样，不推荐使用.**和.*

**Comment by qq8803128** [comment]
你说的没错，我对inPackage的代码有点疑问
![image](https://user-images.githubusercontent.com/15795651/135014303-be2c84ad-aa6f-430a-9488-e7f1460c3fb3.png)
比如现在写com.a1.b1.**，根据代码最后的结果是这样的
    whiteList = 'com.a1.b1.**'
    packageName = 'com.a1.b1'
    sub = 'com.a1'
感觉是代码问题吧， @shifujun 大佬来说一下呗

**Comment by qq8803128** [comment]
com.xxx.xxx.*的包的sub是用的it重置了

**Comment by shifujun** [comment]
`.**`是指最后有至少1层包名是任意的，所以123行那个`sub`是想拿到当前类的包名再去掉最后一级包名的部分，这个部分应该是以那个规则去掉后面的`**`起始的。

你可以做你想做的修改，然后跑一下PluginClassLoaderTest，然后拿那个失败的用例来讨论一下。

**Comment by qq8803128** [comment]
@shifujun 也就是说a.b.c.** 等价于a.b.c.sub吧，这样说我就理解了

**Comment by shifujun** [comment]
我没法说“等价”于什么。`a.b.c.**`表示的首先是类的包名，不含类名的部分。包名至少包含`a.b.c.`，最后这个`.`表示它至少还有一级包名。具体的更多例子看自动化测试的用例就行了。
