### ISSUE TITLE
整合Unity包出现java.lang.NoSuchMethodError JNI调用异常

### ISSUE THREAD

**Issue by hejinyin273** [Tencent/Shadow#628]
对应的代码在这里https://github.com/hejinyin273/Shadow/tree/zwn_dev
CubeController是Unity打包后的内容，现在作为Shadow\projects\sample\maven\plugin-project里的一个组件，打包到plugin-shadow-apk里，在host里启动插件后进行启动。出现如下错误
09-26 10:37:05.663 31271 31271 E ple.host:plugi: ----- class 'Lcom/unity3d/player/GoogleARCoreApi;' cl=0x167c14f8 -----
09-26 10:37:05.663 31271 31271 E ple.host:plugi:   objectSize=248 (224 from super)
09-26 10:37:05.663 31271 31271 E ple.host:plugi:   access=0x0000.0001
09-26 10:37:05.663 31271 31271 E ple.host:plugi:   super='java.lang.Class<java.lang.Object>' (cl=0x0)
09-26 10:37:05.663 31271 31271 E ple.host:plugi:   vtable (3 entries, 11 in super):
09-26 10:37:05.663 31271 31271 E ple.host:plugi:      0: void com.unity3d.player.GoogleARCoreApi.initializeARCore(com.tencent.shadow.core.runtime.ShadowActivity)
09-26 10:37:05.663 31271 31271 E ple.host:plugi:      1: void com.unity3d.player.GoogleARCoreApi.pauseARCore()
09-26 10:37:05.663 31271 31271 E ple.host:plugi:      2: void com.unity3d.player.GoogleARCoreApi.resumeARCore()
09-26 10:37:05.663 31271 31271 E ple.host:plugi:   direct methods (1 entries):
09-26 10:37:05.663 31271 31271 E ple.host:plugi:      0: void com.unity3d.player.GoogleARCoreApi.<init>()
09-26 10:37:05.663 31271 31271 E ple.host:plugi:
09-26 10:37:05.663 31271 31271 E ple.host:plugi: Failed to register native method com.unity3d.player.GoogleARCoreApi.initializeARCore(Landroid/app/Activity;)V in /data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/99f1a48f6a9ef3340311e18fed28a953/plugin-debug.zip/plugin-shadow-apk-debug.apk
09-26 10:37:05.663 31271 31271 F ple.host:plugi: jni_internal.cc:699] JNI FatalError called: com/unity3d/player/GoogleARCoreApi
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166] No pending exception expected: java.lang.NoSuchMethodError: no static or non-static method "Lcom/unity3d/player/GoogleARCoreApi;.initializeARCore(Landroid/app/Activity;)V"
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at boolean com.unity3d.player.NativeLoader.load(java.lang.String) ((null):-2)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void com.unity3d.player.UnityPlayer.a(android.content.pm.ApplicationInfo) ((null):-1)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void com.unity3d.player.UnityPlayer.<init>(android.content.Context) ((null):-1)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void slq.tory.CubeController.UnityPlayerActivity.onCreate(android.os.Bundle) (UnityPlayerActivity.java:25)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(android.os.Bundle) (:-1)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(android.os.Bundle) (PluginContainerActivity.java:84)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7458)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7448)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1286)
09-26 10:37:05.728 31271 31271 F ple.host:plugi: thread.cc:2166]   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:3409)

大佬帮忙看下要怎么解决？

**Comment by shifujun** [comment]
这个直接原因好理解吧？就是插件里的Activity类型都换成ShadowActivity了，JNI代码去反射原来的方法签名是找不到方法的。所以可能本质问题是Shadow没有对native代码Transform的能力。

能否成本较低的解决这个问题，主要看JNI代码依赖这个Activity类型在做什么。

假设JNI部分代码和这个jar中的代码我们都可以修改。解决方案肯定是重构这个接口，使其用一个自定义接口代替Activity类型。然后在接口实现中可以委托给Activity的各种方法。

**Comment by hejinyin273** [comment]
com.unity3d.player以及JNI库没有开源，com.unity3d.player对应的jar是经过混淆了的。没法修改JNI部分代码和这个jar中的代码。大佬，还有没有其它方式？

**Comment by shifujun** [comment]
从Shadow通过Transform修改的原理来看，Activity是一定要被重写的，以便能动态更新其中和Activity API不相关的代码。那native代码这边又不能修改，所以肯定没法支持的。而且从Shadow的视角来看，第三方库和业务自己的代码是没有区别的。

虽然Shadow没法通用的支持这种场景。但是从动态化代码的思路上，我觉得还是有方案的。首先Activity肯定是打包在宿主里的了。然后Activity要依赖这个第三方库。我们可以把这个库的接口都抽出来，然后把库放到单独的apk里动态加载实现这个接口。Activity的其他逻辑也可以按照Shadow的原理委托出来。

**Comment by hejinyin273** [comment]
没有理解怎么做，能否再具体一点？

**Comment by shifujun** [comment]
Shadow等插件化框架的主要目的动态化Activity子类的代码，这是为了方便插件的开发，开发时可以正常写Activity，所以插件框架实现起来很麻烦，要绕过各种限制。但实际上我们的核心目的是动态化我们写的逻辑而已，并没有说一定要把代码写在Activity里，再动态化。而非Activity的普通类动态化非常简单，Android系统根本就不限制。所以如果一定要在你的这种场景下动态化，你可以重构你的代码，让需要动态更新的代码不要和Activity类型产生交互。可以通过自定义接口把行为都委托到普通类上。这样就可以动态加载了。

实际上Shadow就是通过字节码修改在自动帮业务的代码做这种重构。

我前面说的Activity也指代Service等系统要求必须在Manifest里注册的，不能动态加载的API。

**Comment by newchenxf** [comment]
请问有解决办法吗？我也遇到同样的问题了！@shifujun

**Comment by shifujun** [comment]
> 请问有解决办法吗？我也遇到同样的问题了！@shifujun

前面解释了原因。如果你写个demo成本不高的话，可以fork了之后在source sample上复现一下问题，push上来我看看。
虽然通用的解决方案成本比较高，但有可能针对具体的问题可以低成本解决。

**Comment by hejinyin273** [comment]
对应的代码在这里https://github.com/hejinyin273/Shadow/tree/zwn_dev
Shadow/projects/sample/maven/plugin-project/CubeController
CubeController就是Unity导出来的Android lib

**Comment by hejinyin273** [comment]
@shifujun 大佬有空看看demo吗？

**Comment by shifujun** [comment]
我看了，只是还没有什么好办法。

之前有接过Unreal引擎的场景，Unreal也会生成一个GameActivity，它带的so就不依赖Android的API，所以就很好支持了。

**Comment by hejinyin273** [comment]
我用360的replugin将Unity导出的CubeController做成插件可以在replugin 的Host上运行，有什么可以参考的吗？ @shifujun

**Comment by shifujun** [comment]
> 我用360的replugin将Unity导出的CubeController做成插件可以在replugin 的Host上运行，有什么可以参考的吗？ @shifujun 

这是两种不同的技术手段，所以效果不同。

**Comment by 545519501** [comment]
@hejinyin273 请问这个问题有后续吗？最终有在插件环境下运行unity的解决方案吗

**Comment by TongHongliang** [comment]
@hejinyin273 我也碰到了这个问题，希望能帮忙看看
2023-04-16 06:22:50.362 13784-13784 ple.host:plugi          com.tencent.shadow.sample.host       E  ----- class 'Lcom/unity3d/player/GoogleARCoreApi;' cl=0x138619b8 -----
                                                                                                      objectSize=248 (224 from super)
                                                                                                      access=0x0000.0001
                                                                                                      super='java.lang.Class<java.lang.Object>' (cl=0x0)
                                                                                                      vtable (3 entries, 11 in super):
                                                                                                         0: void com.unity3d.player.GoogleARCoreApi.initializeARCore(com.tencent.shadow.core.runtime.ShadowActivity)
                                                                                                         1: void com.unity3d.player.GoogleARCoreApi.pauseARCore()
                                                                                                         2: void com.unity3d.player.GoogleARCoreApi.resumeARCore()
                                                                                                      direct methods (1 entries):
                                                                                                         0: void com.unity3d.player.GoogleARCoreApi.<init>()
2023-04-16 06:22:50.363 13784-13784 ple.host:plugi          com.tencent.shadow.sample.host       E  Failed to register native method com.unity3d.player.GoogleARCoreApi.initializeARCore(Landroid/app/Activity;)V in /data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/72b90b1fbf45d5d5762a50cbbe265764/plugin-debug.zip/sample-app-plugin-debug.apk
2023-04-16 06:22:50.363 13784-13784 ple.host:plugi          com.tencent.shadow.sample.host       A  jni_internal.cc:748] JNI FatalError called: com/unity3d/player/GoogleARCoreApi

**Comment by YANGHR0209** [comment]
我也遇到这个问题，有解决方案吗？大佬

**Comment by YANGHR0209** [comment]
@TongHongliang 最后解决了吗？

**Comment by zhufeixiang** [comment]
> @hejinyin273 请问这个问题有后续吗？最终有在插件环境下运行unity的解决方案吗

+1

**Comment by YMoonRiver** [comment]
> > @hejinyin273 请问这个问题有后续吗？最终有在插件环境下运行unity的解决方案吗
> 
> +1

+1

**Comment by YMoonRiver** [comment]
> 

大佬，可以贴出对应代码段吗，感激不尽

**Comment by YMoonRiver** [comment]
> 我这边解决了，简单讲下步骤： 1、修改com.tencent.shadow.core.transform_kit.ReplaceClassName.replaceClassName函数，函数内过滤掉"com.unity3d.player"这个路径的类，避免unity内部的jar包class被替换为ShadowActivity 2、修改unity-class.jar包，把com/unity3d/player/UnityPlayer.java中构造函数传入的shadowcontext通过反射修改为ContainerActivity中的真实context

大佬，可以贴出相应代码段吗，方便后人查阅，感激不尽

**Comment by jeffdeen** [comment]
1:
`    fun replaceClassName(ctClass: CtClass, oldName: String, newName: String) {
//        println("replaceClassName:${ctClass.name}")
        if (ctClass.name.contains("com.unity3d.player")) {
            return
        }
        ctClass.replaceClassName(oldName, newName)
        mNewNames.add(newName)
    }`
2:
`        if (var1 instanceof Activity) {
            currentActivity = (Activity)var1;
        }
        // 调整getContext，反射
        try {
            Class<?> shadowActivity = Class.forName("com.tencent.shadow.core.runtime.PluginActivity");
//            Log.i(TAG, "initView: getContext is shadowActivity");
            if(shadowActivity.isInstance(var1)) {
                Field field = shadowActivity.getDeclaredField("hostActivityDelegator");
                field.setAccessible(true);
                Class<?> hostActivityDelegator = Class.forName("com.tencent.shadow.core.runtime.container.HostActivityDelegator");
                Method getHostActivity = hostActivityDelegator.getDeclaredMethod("getHostActivity"); // 获取方法
                Class<?> hostActivity = Class.forName("com.tencent.shadow.core.runtime.container.HostActivity");
                Method getActivity = hostActivity.getDeclaredMethod("getImplementActivity"); // 获取方法

                Object hostActivityDelegatorObj = field.get(getContext());
                Object hostActivityObj = getHostActivity.invoke(hostActivityDelegatorObj);
                currentActivity = (Activity) getActivity.invoke(hostActivityObj);
                Log.i("Unity", "activity: " + currentActivity + " " + currentActivity.getClass());
//                currentContext = (Context) activity;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }`

**Comment by jeffdeen** [comment]
> 

https://numerous-innocent-348.notion.site/Shadow-Unity-8a9c0fb11db44962ae6cff1e70cc06fc

**Comment by jeffdeen** [comment]
> > 我这边解决了，简单讲下步骤： 1、修改com.tencent.shadow.core.transform_kit.ReplaceClassName.replaceClassName函数，函数内过滤掉"com.unity3d.player"这个路径的类，避免unity内部的jar包class被替换为ShadowActivity 2、修改unity-class.jar包，把com/unity3d/player/UnityPlayer.java中构造函数传入的shadowcontext通过反射修改为ContainerActivity中的真实context
> 
> 大佬，可以贴出相应代码段吗，方便后人查阅，感激不尽

https://numerous-innocent-348.notion.site/Shadow-Unity-8a9c0fb11db44962ae6cff1e70cc06fc

**Comment by dscxnwiair** [comment]
> > > 我这边解决了，简单讲下步骤： 1、修改com.tencent.shadow.core.transform_kit.ReplaceClassName.replaceClassName函数，函数内过滤掉"com.unity3d.player"这个路径的类，避免unity内部的jar包class被替换为ShadowActivity 2、修改unity-class.jar包，把com/unity3d/player/UnityPlayer.java中构造函数传入的shadowcontext通过反射修改为ContainerActivity中的真实context
> > 
> > 
> > 大佬，可以贴出相应代码段吗，方便后人查阅，感激不尽
> 
> https://numerous-innocent-348.notion.site/Shadow-Unity-8a9c0fb11db44962ae6cff1e70cc06fc

大哥有改好的 unity-class.jar 包么 或者修改方法么，我这编译不过呀，感激不尽

**Comment by TA-J** [comment]
> 我这边解决了，简单讲下步骤： 1、修改com.tencent.shadow.core.transform_kit.ReplaceClassName.replaceClassName函数，函数内过滤掉"com.unity3d.player"这个路径的类，避免unity内部的jar包class被替换为ShadowActivity 2、修改unity-class.jar包，把com/unity3d/player/UnityPlayer.java中构造函数传入的shadowcontext通过反射修改为ContainerActivity中的真实context

我这边有Unity插件，还是 android 的插件，如果按照这种方式改shadow代码会不会影响android 插件的运行环境

**Comment by TA-J** [comment]
> > > > 我这边解决了，简单讲下步骤： 1、修改com.tencent.shadow.core.transform_kit.ReplaceClassName.replaceClassName函数，函数内过滤掉"com.unity3d.player"这个路径的类，避免unity内部的jar包class被替换为ShadowActivity 2、修改unity-class.jar包，把com/unity3d/player/UnityPlayer.java中构造函数传入的shadowcontext通过反射修改为ContainerActivity中的真实context
> > > 
> > > 
> > > 大佬，可以贴出相应代码段吗，方便后人查阅，感激不尽
> > 
> > 
> > https://numerous-innocent-348.notion.site/Shadow-Unity-8a9c0fb11db44962ae6cff1e70cc06fc
> 
> 大哥有改好的 unity-class.jar 包么 或者修改方法么，我这编译不过呀，感激不尽

大佬  你解决了吗

**Comment by idersan** [comment]
> > > 我这边解决了，简单讲下步骤： 1、修改com.tencent.shadow.core.transform_kit.ReplaceClassName.replaceClassName函数，函数内过滤掉"com.unity3d.player"这个路径的类，避免unity内部的jar包class被替换为ShadowActivity 2、修改unity-class.jar包，把com/unity3d/player/UnityPlayer.java中构造函数传入的shadowcontext通过反射修改为ContainerActivity中的真实context
> > 
> > 
> > 大佬，可以贴出相应代码段吗，方便后人查阅，感激不尽
> 
> https://numerous-innocent-348.notion.site/Shadow-Unity-8a9c0fb11db44962ae6cff1e70cc06fc

下载地址找不到了，可以重新传一个看看吗？十分感谢哈
