### ISSUE TITLE
JobService 应该如何代理

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Tencent/Shadow#629]
组件转插件，用了这个库，没转成功

https://github.com/evernote/android-job

Shadow会处理Service的子类，但没有处理形如JobService、IntentService等的子类
这种情况怎么解决？

**Comment by shifujun** [comment]
这个不久之前#566 中讨论过了。

IntentService跟JobService不一样，IntentService主要是给插件自己的代码用的，JobService是给系统用的。所以IntentService是有IntentServiceTransform支持了的。

**Comment by LinXueyuanStdio** [comment]
看了，好麻烦。。。
