### ISSUE TITLE
插件需要额外的Proguard规则

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#632]
> 建议有个统一的混淆注意事项文件，我刚才也遇到这个问题了

_Originally posted by @liluyue in https://github.com/Tencent/Shadow/issues/608#issuecomment-928895264_

随着aar打包一份自己的proguard规则用法越来越多。Shadow在Transform时修改的类名确实会使引用了这些类的proguard规则失效。修复这个问题，应该对应的也修改proguard规则。但不幸的是没有这样直接的接口允许我们替换proguard规则。

先记录一种比较可靠的手工修复方案。可以考虑基于这种方案做一些自动化的改善。

1. 在插件apk的proguard规则中加入一行`-printconfiguration "build/outputs/mapping/configuration.txt"`。
  这样在进行一次proguard之后，会得到一份最终合并生效的proguard规则。

2. Transform中改类名的操作被集中到了`com.tencent.shadow.core.transform_kit.ReplaceClassName#replaceClassName`方法上。可以从这个方法获取一份修改名字的集合。

3. 在前面生成的`configuration.txt`中查找被替换的类名，也将对应的规则替换成transform之后的名字。把新规则添加到插件的proguard配置中，重新构建。

**Comment by liluyue** [comment]
明白

**Comment by liluyue** [comment]
不过第一步应该可以省略，gradlew本身已经生成了一份：build/outputs/mapping/release/configuration.txt

**Comment by shifujun** [comment]
> 不过第一步应该可以省略，gradlew本身已经生成了一份：build/outputs/mapping/release/configuration.txt

你可以在它的内容里搜一下`-printconfiguration`，看看是哪个文件引入的，注释里应该写了。应该不是所有版本的AGP都添加了这个设置。
