### ISSUE TITLE
shadow可以建一个wx讨论群吗？

### ISSUE THREAD

**Issue by ranhuanbin** [Tencent/Shadow#637]
shadow可以建一个wx讨论群吗？大家在使用shadow的时候遇到问题可以随时在群里反馈，比在这里提issue要方便一些

**Comment by shifujun** [comment]
如果我们的目的不是闲聊，那么讨论的内容都是有价值的。有价值的内容应该被记录起来以便回溯查询，因此issue更合适。

关于回复及时性的问题，作为免费的开源项目，我们只能尽量回复。对于线索清晰的问题，回复肯定会更快更准确。对于模糊的问题，可能即时通讯也只是浪费时间在厘清问题上。用类似信件的issue交流问题，有助于我们提高文字的准确性。

提issue前可以先搜索一下，很多问题都有人问过，比如你这个。
https://github.com/Tencent/Shadow/issues?q=is%3Aissue+%E7%BE%A4
