### ISSUE TITLE
URLEncodedUtils.  NotFound

### ISSUE THREAD

**Issue by hzbhzb** [Tencent/Shadow#638]
项目中有声明了 useLibrary 'org.apache.http.legacy'，但是插件运行的时候会报找不到URLEncodedUtils 这个类
这个问题看了issue里面有个类似的问题是这个：https://github.com/Tencent/Shadow/issues/409#issue-704014015
但是没看到解决方案，请问下对于这种情况应该怎么处理

**Comment by shifujun** [comment]
这个问题得先明确下测试的Android系统版本。因为这个包是在不同版本的系统上有不同处理的。

比如我这样写：https://github.com/shifujun/Shadow/commit/1bd61a98a1389e52684609b694043ba88616d0e9

我在API 28的虚拟机上，无论是插件环境（sample-host）还是正常app环境(sample-normal-app)，都是一样找不到这个类的。

**Comment by hzbhzb** [comment]
嗯，是API 29，这个在没有shadow的影响下是可以正常加载的，还有一个问题是 在dialog 展示的传入的context 参数是activity的，但是会报 token is null
