### ISSUE TITLE
只能启动Activity插件，不能直接启动dialog吗？

### ISSUE THREAD

**Issue by wuQAQ** [Tencent/Shadow#64]

**Comment by shifujun** [comment]
没有提供这种接口。因为Shadow的目标是将正常安装能跑的App免安装运行起来。正常安装的App就不可能直接脱离Activity启动一个Dialog，所以Shadow也没有提供这样的接口。

但是从技术上来讲，这没什么难度。因为Shadow在原理上就是将插件代码自动重构为宿主代码的一部分。
