### ISSUE TITLE
源码依赖的示例工程崩溃，100%复现,非常容易

### ISSUE THREAD

**Issue by xprhs** [Tencent/Shadow#643]
复现步骤:
1、用Android Studio运行示例工程sample-host，在模拟器或手机上点击启动插件
2、在源码依赖的插件工程projects/sample/source/sample-plugin/sample-app-lib中的闪屏页SplashActivity的onCreate中随意打印一条日志；例如Log.v(TAG,"====SplashActivity=====");
3、再次运行编译后的sample-host，在模拟器或手机上点击启动插件 ====> 示例直接崩溃
      备注:再次运行时，卸载原有应用和不卸载覆盖安装均可

崩溃日志如下:
10-14 13:14:29.331  4823  4823 E AndroidRuntime: FATAL EXCEPTION: main
10-14 13:14:29.331  4823  4823 E AndroidRuntime: Process: com.tencent.shadow.sample.host:plugin, PID: 4823
10-14 13:14:29.331  4823  4823 E AndroidRuntime: java.lang.RuntimeException: partKey==sample-plugin-app className==android.support.v4.content.FileProvider providerInfo==ContentProviderInfo{name=com.tencent.shadow.test.plugin.general_cases.fileprovider className=android.support.v4.content.FileProvider}
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.createContentProviderAndCallOnCreate(PluginContentProviderManager.kt:93)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$1.invoke(ShadowPluginLoader.kt:125)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$2.run(ShadowPluginLoader.kt:135)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/86a5878b0b384d038720663a09379b17/plugin-debug.zip/sample-plugin-app-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/lib/5C9AA66B-BB33-4E46-81AD-9D2A19A6574D_lib, /system/lib, /system_ext/lib]]
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadClass(PluginClassLoader.kt:100)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.tencent.shadow.core.runtime.ShadowAppComponentFactory.instantiateProvider(ShadowAppComponentFactory.java:36)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.createContentProviderAndCallOnCreate(PluginContentProviderManager.kt:89)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	... 9 more
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/86a5878b0b384d038720663a09379b17/plugin-debug.zip/sample-runtime-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/lib/5C9AA66B-BB33-4E46-81AD-9D2A19A6574D_lib, /system/lib, /system_ext/lib]]
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 		at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadClass(PluginClassLoader.kt:94)
10-14 13:14:29.331  4823  4823 E AndroidRuntime: 		... 12 more
10-14 13:14:29.369  4770  4816 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
10-14 13:14:29.369  4770  4816 E AndroidRuntime: Process: com.tencent.shadow.sample.host, PID: 4770
10-14 13:14:29.369  4770  4816 E AndroidRuntime: java.lang.RuntimeException: android.os.DeadObjectException
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:120)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: Caused by: android.os.DeadObjectException
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at com.tencent.shadow.dynamic.manager.BinderPluginLoader.callApplicationOnCreate(BinderPluginLoader.java:79)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at com.tencent.shadow.sample.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:127)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:116)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:118)
10-14 13:14:29.369  4770  4816 E AndroidRuntime: 	... 3 more

**Comment by xprhs** [comment]
package com.tencent.shadow.sample.plugin.app.lib.gallery.splash;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.util.Log;

import com.tencent.shadow.sample.plugin.app.lib.R;
import com.tencent.shadow.sample.plugin.app.lib.gallery.MainActivity;

public class SplashActivity extends Activity {

    private SplashAnimation mSplashAnimation;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout_splash);
        Log.v("zxp","====SplashActivity=====");

        mSplashAnimation = new SplashAnimation(this);
        mSplashAnimation.start();

        mSplashAnimation.setAnimationListener(new ISplashAnimation.AnimationListener() {
            @Override
            public void onAnimationEnd() {
                finish();

                startActivity(new Intent(SplashActivity.this, MainActivity.class));
            }
        });
    }
}

**Comment by shifujun** [comment]
你可以检查一下`android.support.v4.content.FileProvider`到底在不在插件apk里。有可能是buildCache出bug了。可以把cache关了试试：
https://github.com/Tencent/Shadow/blob/cc8f6d09ec5ca5f243feb0311c9856fe9f84c69d/gradle.properties#L15
