### ISSUE TITLE
跳转插件activity较慢

### ISSUE THREAD

**Issue by baixxx** [Tencent/Shadow#646]
从宿主activity跳转到插件activity耗时较长，较慢。这个怎么可以优化一下

**Comment by shifujun** [comment]
这是个很长的，包含许多步骤的过程。Shadow的core.manager实际上没有对这个过程封装成固定的API。只是在sample里演示了整个过程。业务应该根据自身业务特点，选择适当的时机提前执行其中的某些步骤。比如在宿主启动后就立即下载和启动插件的Application。这样在用户要启动插件的Activity时，剩下的步骤就少多了。

简而言之，做好预加载。
