### ISSUE TITLE
请问可以建一个 shadow 交流群吗？

### ISSUE THREAD

**Issue by ranhuanbin** [Tencent/Shadow#652]
如果有一个 shadow 交流群就好了，大家有问题可以及时的在群里反馈，大家一起探讨，同时可以将比较关键的问题进行备份整理到 Issue 中
如果作者大大能够同意建一个 shadow 交流群就好了
平时遇到 shadow 的问题，在 issue 中查找以及给 作者提问，效率实在是太低了
![WechatIMG2](https://user-images.githubusercontent.com/14325460/138417552-7e93f56f-6bd2-481a-90ff-1f45e937f806.jpeg)
。

**Comment by cucuberboy** [comment]
大佬们请问一下，目前接入shadow插件化框架的APP能否上架到小米、华为的应用市场，是否会因为公司之间的竞争关系被限制发布？有没有已经发布小米或者华为应用市场的APP能参考下

**Comment by cucuberboy** [comment]
二维码过期了，能否更新下二维码，我也入群请教请教大佬们，多谢 @ranhuanbin

**Comment by daosanqing** [comment]
群主能发一下微信吗？

**Comment by HeLiHuang** [comment]
![Shadow插件化框架交流群聊二维码](https://user-images.githubusercontent.com/7981470/200156962-f4cd7d3a-6d51-402c-ba6b-c55bcc3e4a9e.png)
