### ISSUE TITLE
偶发性错误 java.lang.VerifyError

### ISSUE THREAD

**Issue by Linats** [Tencent/Shadow#653]
大数据统计中，在android 12的设备上，有以下的偶发性错误。
错误仅发生在android 12。
请教一下，能否帮忙提供一下解决思路？
非常感谢~

一个个人猜测是：
从`'Unresolved Reference: com.tencent.shadow.core.runtime.MixResources'`猜测可能是因为runtime的classloader出问题了？

> 10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: FATAL EXCEPTION: main
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: Process: 包名:plugin, PID: 1763
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: java.lang.NoClassDefFoundError: com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at com.tencent.shadow.core.loader.ShadowPluginLoader.getHostActivityDelegate(Unknown Source:5)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at com.tencent.shadow.core.runtime.container.PluginContainerActivity.<init>(Unknown Source:20)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at com.samsung.android.sdk.rewardssdk.runtime.PluginDefaultProxyActivity.<init>(Unknown Source:0)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3892)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4192)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2429)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8572)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
10-22 13:22:51.915 10299  1763  1763 E AndroidRuntime: Caused by: java.lang.VerifyError: Verifier rejected class com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate: android.content.res.Resources com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.getResources() failed to verify: android.content.res.Resources com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.getResources(): [0x8]  can't resolve returned type 'Reference: android.content.res.Resources' or 'Unresolved Reference: com.tencent.shadow.core.runtime.MixResources' (declaration of 'com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate' appears in /data/user/0/包名/files/ShadowPluginManager/UnpackedPlugin/xxx-sdk/7adba112ba9c7509995c995900b0f060/plugin.zip/sample-loader-release.apk)

**Comment by X32580** [comment]
我也遇到了这个问题，vivo 手机Android 12 启动插件，在插件界面显示的时候立即关闭应用就有概率触发。需要宿主直接启动插件后立即关闭。

**Comment by X32580** [comment]
Caused by: java.lang.VerifyError: Rejecting class com.demo.manager.SamplePluginManager that attempts to sub-type erroneous class com.demo.manager.FastPluginManager (declaration of 'com.demo.manager.SamplePluginManager' appears in /data/user/0/com.demo.user/files/manager-release.apk)

**Comment by X32580** [comment]
从其他地方看到这个bug的原因,它和shadow没有关系。 https://www.51cto.com/article/700901.html
