### ISSUE TITLE
上传两张流程图，新接入 shadow 的可能会

### ISSUE THREAD

**Issue by ranhuanbin** [Tencent/Shadow#662]
![shadow 架构图 (1)](https://user-images.githubusercontent.com/14325460/139222526-f609bda7-8f30-4c31-8255-8ab9d1abd735.png)
![shadow 源码流程分析](https://user-images.githubusercontent.com/14325460/139222585-05d87978-29df-42cd-ba24-bd027e9602c9.png)

**Comment by cucuberboy** [comment]
大佬们请问一下，目前接入shadow插件化框架的APP能否上架到小米、华为的应用市场，是否会因为公司之间的竞争关系被限制发布？有没有已经发布小米或者华为应用市场的APP能参考下

**Comment by cucuberboy** [comment]
> 好尴尬，建了一个 shadow 的微信群，目前只有六个人，如果大家能来建设 shadow 就好了，经常被 shadow 的问题折腾的焦头烂额

能否更新个群二维码给我，我也入群讨论讨论，多谢

**Comment by Zhang-liangliang** [comment]
能否更新下群二维码，最近在研究这个框架，遇到了很多问题

**Comment by luoxiong94** [comment]
能否更新下群二维码，最近在研究这个框架，遇到了很多问题
