### ISSUE TITLE
关于通过API的形式调用，插件的代码， 生成dialog， 布局里面的EditText

### ISSUE THREAD

**Issue by fran-cheng** [Tencent/Shadow#670]
EditText 的focusableInTouchMode默认改为false， 当主动设置为ture时，  当输入框内没有文字时， 正常， 当有文字时， 点击
 android.content.res.Resources$NotFoundException: Resource ID #0x0   是不支持这么使用吗？   
dialog用宿主的Activity生成，   插件的layout通过setContentView  加载到布局上

**Comment by shifujun** [comment]
你的描述不太好理解。你可以fork之后，在sample中做一个简单的修改复现你的问题场景，然后把代码push上来。这样用代码交流就很好沟通了。

https://github.com/Tencent/Shadow/blob/352561d6cc061d2870335c4c5bd9be35fc8004ff/CONTRIBUTING.md#issue

**Comment by qq821978827** [comment]
https://github.com/qq821978827/Shadow/tree/dev
麻烦了

**Comment by shifujun** [comment]
我猜你的意思是运行`sample-hello-host`之后，点击"宿主自定义接口的动态化“按钮，然后观察弹出的Dialog吧？

我在API28的虚拟机上测试正常。
![image](https://user-images.githubusercontent.com/3535204/140717283-88a2fd7b-5db8-4240-b1b9-f64be82037bd.png)


你说的”闪退“是指Crash还是页面被关闭了？如果是Crash，完整的堆栈是什么内容？

请尽量不要让人猜如何操作以及应该关注什么状态不符合预期。

**Comment by qq821978827** [comment]
到弹出dialog为止都是没有问题的，  问题在于弹出的dialog的EditText：
1、默认是无法获取焦点的（这于非插件使用存在明显不同）
2、在设置setFocusableInTouchMode为true后，存在2种情况
情况1：当EditText 内容为“”时，与期望一致

**Comment by qq821978827** [comment]
补充一下，当我把layout从插件APK处复制到HOST处时，  把Context更改为Host的Context  
即资源是从host拿的，代码是在插件APK上的，这时的效果跟直接在Host使用一致。 
我的使用是否存在问题？

**Comment by shifujun** [comment]
这个问题的关键点应该在于Dialog的复杂性，它需要构造一个这样的Context：
```
ContextThemeWrapper mixContext = new ContextThemeWrapper(apkContext, android.R.style.Theme_DeviceDefault) {
            @Override
            public Object getSystemService(String name) {
                if (WINDOW_SERVICE.equals(name)) {
                    return activityContext.getSystemService(name);
                } else {
                    return super.getSystemService(name);
                }
            }
        };
```

Dialog需要访问`WINDOW_SERVICE`，所以一般需要传给它Activity Context。其次EditText需要从Theme访问其内置的资源，而我们构造的apkContext没有Theme，所以需要用ContextThemeWrapper指定一个Theme。

这是我调试时的代码改动：
https://github.com/shifujun/Shadow/tree/issue670

**Comment by qq821978827** [comment]
感谢，我会有这个疑惑看来是因为我对Dialog等理解不深入所导致的。
多问一个问题：
在我的使用场景下可能会通过，api调用的形式来调用插件代码。    当参数传入一个Activity时， 我想在插件代码里面使用插件的资源，其余跟activity相关的都使用宿主的activity。  但是我没有想到很好能实现这个的办法
