### ISSUE TITLE
支持通过manager关闭PPS

### ISSUE THREAD

**Issue by weixiaokang** [Tencent/Shadow#673]
我们这边的需求：
宿主APP注册n个PPS，需要加载的插件有n+x个。当加载第n+x个插件时，释放第(n+x)%n个PPS。
维护队列这个是我们的业务逻辑，但是PluginManager为什么不提供退出的接口？
com.tencent.shadow.dynamic.host.PluginManager
```
public interface PluginManager {
    void enter(Context context, long formId, Bundle bundle, EnterCallback callback);

    void exit();
}
```
Manager的具体实现
```
    @Override
    public void exit() {
        if (mPpsController != null) {
            try {
                mPpsController.exit();
            } catch (RemoteException exception) {
                if (LOG.isDebugEnabled()) {
                    LOG.debug("PpsController exit error, reason: " + exception.toString());
                }
            }
        }
    }
```
我们业务上这样实现经过测试时没问题的，当前还是改了你们代码再编译打包，这个退出接口是否考虑加到shadow中？

**Comment by shifujun** [comment]
这里的`enter`方法其实是一种一般程序的main函数的意思。`fromId`更像是表达宿主代码调用`enter`方法的代码行号。这个设计希望`enter`方法接口固化到宿主中之后足够稳定，能承担任何场景。

因此关闭PPS这个场景，也分配一个`fromId`，然后将相关参数传入。
