### ISSUE TITLE
启动插件服务后，不会调用onHandleIntent(@Nullable Intent intent)

### ISSUE THREAD

**Issue by HQlin** [Tencent/Shadow#674]
LogCat打印：
2021-11-15 20:42:26.093 7060-7060/com.tencent.shadow.sample.host D/ConnectService: ConnectService 开始com.lin.basever.INIT_APP
2021-11-15 20:42:26.094 520-799/system_process W/ActivityManager: Unable to start service Intent { act=com.lin.basever.INIT_APP cmp=com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.app.lib.gallery.ConnectService } U=0: not found
2021-11-15 20:42:26.112 520-2630/system_process W/NotificationService: Toast already killed. pkg=com.tencent.shadow.sample.host token=android.os.BinderProxy@bc70100
2021-11-15 20:42:26.117 520-2630/system_process W/ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (296783267)
2021-11-15 20:42:26.117 520-2630/system_process W/InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
2021-11-15 20:42:26.117 520-2630/system_process W/InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.

服务用例代码：ConnectService.java
package com.tencent.shadow.sample.plugin.app.lib.gallery;

import android.app.IntentService;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.Intent;
import android.os.Build;
import android.util.Log;

import androidx.annotation.Nullable;
import androidx.annotation.RequiresApi;

public class ConnectService extends IntentService {
    /**
     * 初始化APP
     */
    public static final String ACTION_INIT_APP = "com.lin.basever.INIT_APP";
    /**
     * 清空机器缓存，退出登录等方式重新启动APP
     */
    public static final String ACTION_REENTER_APP = "com.lin.basever.REENTER_APP";
    /**
     * 退出APP
     */
    public static final String ACTION_APP_EXIT = "com.lin.basever.ACTION_APP_EXIT";

    public ConnectService() {
        super("ConnectService");
    }

    @Override
    public void onCreate() {
        super.onCreate();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            String CHANNEL_ID = "com.lin.basever.run";
            NotificationManager notificationManager = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
            NotificationChannel channel = new NotificationChannel(CHANNEL_ID, "运行", NotificationManager.IMPORTANCE_LOW);
            channel.setDescription("软件运行通知");
            notificationManager.createNotificationChannel(channel);
        }
    }

    private static void startAction(String action) {
        Intent intent = new Intent(TestApplication.getInstance(), ConnectService.class);
        intent.setAction(action);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            TestApplication.getInstance().startForegroundService(intent);
        } else {
            TestApplication.getInstance().startService(intent);
        }
    }

    public static void initApp() {
        Log.d("ConnectService", "ConnectService 开始" + ACTION_INIT_APP);
        startAction(ACTION_INIT_APP);
    }

    public static void relaunchApp() {
        Log.d("ConnectService","ConnectService 开始" + ACTION_REENTER_APP);
        startAction(ACTION_REENTER_APP);
    }

    public static void exitAPP() {
        Log.d("ConnectService","ConnectService 开始" + ACTION_APP_EXIT);
        startAction(ACTION_APP_EXIT);
    }

    public void cancelNotification() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationManager notificationManager = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
            notificationManager.cancel(1);
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.N)
    @Override
    protected void onHandleIntent(@Nullable Intent intent) {
        if (intent == null) {
            Log.d("ConnectService","ConnectService 执行异常， intent为空");
            return;
        }
        Log.d("ConnectService","ConnectService 执行" + intent.getAction());
    }
}

启动插件服务后，不会调用onHandleIntent(@Nullable Intent intent)，大佬该如何处理？

**Comment by shifujun** [comment]
IntentService是特别支持了的，还有个自动化测试`PluginIntentServiceConnectionTest`。

我看这个Log有Intent not found，看起来是不是就是Service忘在Manifest里注册了？

**Comment by HQlin** [comment]
多谢提醒，原因是插件中用startForegroundService无法正常启动服务，修改startAction函数已解决了：
    private static void startAction(String action) {
        Intent intent = new Intent(BaseApp.getInstance(), com.bzl.basever.service.ConnectService.class);
        intent.setAction(action);
        BaseApp.getInstance().startService(intent);
    }
