### ISSUE TITLE
关于宿主和插件进程间通信

### ISSUE THREAD

**Issue by qq821978827** [Tencent/Shadow#677]
想通过加载插件的afterLoadPlugin回调持有，让宿主持有插件的实现，因为他们不是同一个进程所以遇到遇到了问题
已经尝试过多种方法了
代码链接
https://github.com/qq821978827/Shadowtree/dev2

**Comment by shifujun** [comment]
既然明确了需要跨进程通信，那么也就不可能拿到对面进程的对象了。所以可以直接考虑用AIDL通信。插件和宿主的Service可以正常相互通信的。

**Comment by qq821978827** [comment]
明白了， 感谢
