### ISSUE TITLE
不知道支持compose嘛？ 

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#682]
如题支持compose嘛

**Comment by shifujun** [comment]
支持不支持什么特性永远是试试才准确。“支持，但不完全支持”可能是常态。

compose基本上是完全自绘的，所以应该没什么需要特别支持的地方，我猜是支持的。

**Comment by limingboGitHub** [comment]
目前最新版的compose1.0.5有点问题：
Class com.tencent.shadow.core.runtime.ShadowActivity中缺少方法:
isLaunchedFromBubble:()Z被这些类调用了:
androidx.core.app.ActivityCompat$Api31Impl

compose1.0.5里好像有androidx.core:core:1.7.0@aar的依赖，这个版本里面androidx.core.app.ActivityCompat类新增了一个方法isLaunchedFromBubble

**Comment by wzgl5533** [comment]
> 简单测了下是支持的

方便说下 支持的版本配置么？
