### ISSUE TITLE
重复的第三方库依赖作为一个单独的公共插件的疑问

### ISSUE THREAD

**Issue by HQlin** [Tencent/Shadow#683]
场景1：
A插件为公共插件，B插件依赖于A插件，B插件单独运行时是直接依赖于第三方库正常，B构建插件化时该如何处理不依赖第三方库而是依赖A插件，使B能插件化成功呢？看一下dependsOn = ['Core', 'Base']的构建，但没看明白Core与Base插件在哪，有更详细的例子参考？我现在存在的问题是先启动A，再启动B插件时，还是会报【重复添加Component】错误。
场景2：
A插件为公共插件，B插件依赖于A插件，如果没先启动A，就直接启动B插件时，会报【加载sample-plugin-app2时它的依赖sample-plugin-app还没有加载】错误，框架可否支持自动启动依赖插件呢？

**Comment by shifujun** [comment]
B插件编译时需要以`compileOnly`方式依赖A插件。这可能需要先让A插件拆分出一个library，才能被`compileOnly`方式依赖。
然后B插件的`dependsOn`中要添加A插件的`partKey`。这个dependsOn的设置会导致B插件的ClassLoader以A插件的ClassLoader作为parent，因此B插件可以加载A插件中的类。

如果A插件中包含有Component，B插件也打包了它们，就会出现“【重复添加Component】”的Crash。这是避免潜在错误的assert。

自动启动依赖插件，或者自动调用Application.onCreate，或者自动odex，等等，这些按需调用的自动场景都不会是对业务来说最佳的方案。因此Shadow只提供了原子化的方法。对于业务来说最佳的方案一定是尽可能早的预加载。什么时候是最早的预加载时机，肯定是按业务场景决定的。

**Comment by shifujun** [comment]
例子，我尽量抽时间添加一个。

**Comment by HQlin** [comment]
多谢解答，还有个场景3：A插件为公共插件，B插件依赖于A插件，C插件也依赖于A插件，先启动B插件时启动了A插件的一个service，然后启动C插件时也启动了A插件的同名service。问运行时是同个service实例吗？如果是同个service实例，我想实现多个service实例在现有框架可有什么思路实现呢？

**Comment by shifujun** [comment]
Service肯定是单例的。这里你的3个插件可以看成3个独立安装的App来理解的。插件A并不是编译期的一个库，而是一个公用的App。

如果希望是多实例的，需要B和C插件分别继承A插件中的Service，起不同的名字。

**Comment by HQlin** [comment]
多谢哈
