### ISSUE TITLE
gradlew build 报错

### ISSUE THREAD

**Issue by 1321365765** [Tencent/Shadow#687]
G:\android\plugin\Shadow-master>gradlew build

Starting a Gradle Daemon, 2 incompatible and 6 stopped Daemons could not be reused, use --status for details

> Configure project :coding
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

FAILURE: Build failed with an exception.

* Where:
Build file 'G:\android\plugin\Shadow-master\projects\sdk\coding\get-android-jar\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':coding:get-android-jar'.
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

![image](https://user-images.githubusercontent.com/13029455/142817829-2319d416-ef97-4bd0-a0a5-bc34d7982f94.png)

**Comment by shifujun** [comment]
`gradlew`脚本和Android Studio是不相关的。所以你在Android Studio里设置是影响不了你的`cmd`环境的。你应该在`cmd`环境里检查`JAVA_HOME`环境变量。

**Comment by 1321365765** [comment]
现在不理解要去哪里修改这个配置了。把本地的java_home 升级到11吗
![image](https://user-images.githubusercontent.com/13029455/142820752-4e9516a8-c501-4177-ba8e-52348ade7317.png)

**Comment by shifujun** [comment]
这个报错已经变为找不到Android SDK路径了。你可以用Android Studio直接打开项目，它会帮你生成local.properties文件，里面会自动设置好SDK路径的。或者需要设置ANDROID_SDK_ROOT环境变量，像提示中说的那样。

**Comment by 1321365765** [comment]
重新解压过一次项目后，经历漫长的编译，现在成功了
感谢！
