### ISSUE TITLE
你好，我希望把所有插件使用的res资源打包成一个apk供业务插件APP去使用，这个怎么实现呀

### ISSUE THREAD

**Issue by yexingyun** [Tencent/Shadow#689]
如题，有什么思路呢

**Comment by shifujun** [comment]
如果坚持不使用任何非公开API，我目前只能给出一个方案：让那个包含共享资源的apk通过Java接口提供资源给其他插件使用。其他插件不能在xml里面引用这些资源。

还有一种需要用非公开API的手段，就是去复用系统资源的方案。修改资源id分区到系统资源，然后固定id，让其他插件编译时使用这些id。就像使用`@android:`前缀的那些系统资源一样。这种方案可以自行搜索一下，关键词是`aapt2`,`资源id`,`固定`,`public`。

**Comment by yexingyun** [comment]
感谢解答
