### ISSUE TITLE
请问如何把我们工程当成一个插件打包？

### ISSUE THREAD

**Issue by curry-wei** [Tencent/Shadow#690]
如何把我们项目打包成一个类似于plugin-debug.zip的插件包，我试着把plugin-app替换成我们工程但是通过gradlew build命令并没有打到zip包中  请问如何配置？

**Comment by shifujun** [comment]
业务的项目有何特殊性，SDK是无从得知的。因此一般SDK主动提供一个sample来使业务理解SDK的接入原理。

建议看一下README中提到的https://github.com/Tencent/Shadow/blob/master/projects/sample/README.md

**Comment by curry-wei** [comment]
> 业务的项目有何特殊性，SDK是无从得知的。因此一般SDK主动提供一个sample来使业务理解SDK的接入原理。
> 
> 建议看一下README中提到的https://github.com/Tencent/Shadow/blob/master/projects/sample/README.md

这个sample跑通了， 但是我想把我们项目也打成一个插件 不知道都改那些地方

**Comment by shifujun** [comment]
这个sample应用本身的代码非常少，其中比Android Studio模板项目多出来的配置就是插件相关的。

哪些代码读不懂可以单独提issue，我们可以有针对性的在sample上补充注释。

**Comment by curry-wei** [comment]
> 这个sample应用本身的代码非常少，其中比Android Studio模板项目多出来的配置就是插件相关的。
> 
> 哪些代码读不懂可以单独提issue，我们可以有针对性的在sample上补充注释。
![20211125-165042](https://user-images.githubusercontent.com/48320441/143411469-1f527ad6-9f51-4520-8417-7933a7cfea0f.png)
就是把这个工程和plugin-project一样打成zip 需要改哪些地方？

**Comment by shifujun** [comment]
我没法回答你的问题。我举个例子：我炒的菜想跟你炒的菜一个味道，我需要改哪些地方？你能回答吗？你应该也只能给我你的菜谱，让我自己看我哪做的不一样吧？
