### ISSUE TITLE
宿主和插件在同一个进程运行可以吗

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#695]

**Comment by shifujun** [comment]
可以的。但是分开在单独的进程有很多好处。比如插件Crash不会影响宿主，或者插件引入so时不必考虑和宿主的so冲突。

**Comment by weikaiyun** [comment]
我们这边有需求就是，主界面有多个tab，只有一个tab下的View是由插件提供的或者宿主有一个listView中只有几个item是由插件提供的，这个时候如果插件和宿主在两个进程，感觉就没什么好的办法了，因为View不能跨进程传递。所以插件和宿主在同一个进程，其实很普遍的诉求。
