### ISSUE TITLE
建个QQ群讨论研究

### ISSUE THREAD

**Issue by 247321453** [Tencent/Shadow#7]
RT，找不到组织

**Comment by Hujunjob** [comment]
刚刚建了个QQ群，111617129

**Comment by shifujun** [comment]
支持你们通过QQ群对Shadow进行交流。

但是作为官方，我们希望以异步的方式同大家交流。欢迎大家将讨论清楚的问题以Issue的方式提过来。

对于这个非技术问题，先关闭了。
