### ISSUE TITLE
插件Apk View

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#702]
我看到read.me里面 支持的特性 有提到一个Activity中加载多个Apk中的View，请问能提供一下示例嘛，在sample demo里面，提供sample-app插件里面的 View 加载到 sample-host的activity里面

**Comment by weikaiyun** [comment]
我这边有个思路，就是ShadowPluginLoader拿到业务插件的信息，构建一个ShadowContext，然后类似加载com.tencent.shadow.dynamic.loader.impl.CoreLoaderFactoryImpl的方式去获取插件中View，添加到host activity，不知道这样可行吗？

**Comment by shifujun** [comment]
如果View是插件代码构造的，那不需要同宿主分享插件的ClassLoader或者Context，直接将View对象传给宿主就可以了。
#703 演示了一种实现。

如果宿主想自己构造插件中的View对象，可以用`dynamic-apk`模块的类直接加载插件apk文件，构造相应的context，然后用LayoutInflater自行inflate就可以了。SamplePluginManager中的`onShowLoadingView`回调传给宿主的View就是从manager.apk动态加载的。

**Comment by weikaiyun** [comment]
好像pr block住了， 代码没有合进去，版主可以看下。

**Comment by shifujun** [comment]
> 好像pr block住了， 代码没有合进去，版主可以看下。

你先拉下来看看呗，没准哪里有错还要改。

**Comment by weikaiyun** [comment]
嗯嗯 我拉下来看过啦

**Comment by likaida** [comment]
在此分支的基础上进行改动，通过回调添加
@OverRide
public void setFragment(Fragment fragment) {
getFragmentManager()
.beginTransaction()
.add(R.id.content,fragment)
.commit();
}
获取到插件的Fragment后，在宿主进行使用时，插件的Fragment在执行Oncreate时inflate布局时，报错无法找到layout的xml资源，现有方法可以实现host的Activity拿到plugin的Fragment并进行展示么

**Comment by weikaiyun** [comment]
我个人觉得获取插件fragment然后在宿主中使用，完全可以改成获取插件中的View，然后View加到宿主的fragment不就好啦。Shadow这个框架 好像暂时不支持宿主直接使用插件中的fragment。
