### ISSUE TITLE
宿主中如何调试插件代码

### ISSUE THREAD

**Issue by MmingY** [Tencent/Shadow#707]
想请教您一个问题哈，如何在宿主中调试插件的代码？因为插件都是以zip的方式放在手机本地的，当我们调试宿主的时候可以调整到对应的插件的代码上面吗？

**Comment by shifujun** [comment]
可以的。运行的class包含有debug信息，信息中有源码文件名和行号。只要没被Proguard去掉这个信息，正常编译的类都有。反编译可以看到它们。所以只要IDE知道源码在哪就行了，也就是一般你打开插件的源码工程就可以。因此Shadow的source sample中可以调试宿主、插件、SDK的任何一处代码。

这个问题其实和Shadow没有关系，可以自行搜索更多的资料。

**Comment by cong99** [comment]
刚好有这个问题，回来给个链接：https://developer.android.com/studio/debug?hl=zh-cn#attach-debugger
