### ISSUE TITLE
Could not initialize class com.tencent.shadow.coding.code_generator 

### ISSUE THREAD

**Issue by MrR0990** [Tencent/Shadow#708]
![image](https://user-images.githubusercontent.com/10650866/144989248-d3e5db50-f436-4e74-8506-1e676d21536c.png)

**Comment by shifujun** [comment]
这一般是Android SDK找不到造成的。只有一个截图，我也没法复现问题，也无从改进的。

**Comment by MrR0990** [comment]
![image](https://user-images.githubusercontent.com/10650866/145004533-3209860c-7106-465b-8ac7-abe1ac712e39.png)
说是这个类找不到

**Comment by MrR0990** [comment]
跟打包成plugin安装包有关,不过写了一个已经过时的类,是不是在gradle配置这里可以删掉了??

**Comment by MrR0990** [comment]
![image](https://user-images.githubusercontent.com/10650866/145005440-d63748d0-7ea6-41aa-b8e6-1e706825f63e.png)

**Comment by shifujun** [comment]
你按这个顺序自查一下吧：
1. 你的代码不应该有任何修改，至少包含 0cf839653b5dd422f5a9504427c70949c8d936bd 提交。
2. 根目录的`local.properties`中记录的`sdk.dir`确实有效。它的值后面接上`/platforms/android-30/android.jar`，这个文件确实存在。
3. 检查`projects/sdk/coding/local.properties`文件是否存在。它应该在Studio打开工程后被自动创建的。
4. 测试`./gradlew -p projects/sdk/coding :get-android-jar:clean`，如果报错看看是什么。

**Comment by MrR0990** [comment]
非常感谢,最终排查到sdk里面的android.jar使用了我自行生成的jar,替换成原版的就可以了.

**Comment by shifujun** [comment]
哈，我前面那个提交写完就想，后面再有人遇到错误能是什么场景。你这个操作真的是我怎么也想不到的。绝了😂
