### ISSUE TITLE
FixedContextLayoutInflater

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#709]
版主能解释下FixedContextLayoutInflater中sClassPrefixList 为啥这三个prefix 
"android.widget.",
"android.webkit.",
"android.app."
需要特殊处理呢，我看提交记录是说解决Button找不到的问题，为啥Button会找不到呢

**Comment by shifujun** [comment]
希望 1c0bb52 可以解决你的疑问。
