### ISSUE TITLE
Shadow现在是不支持在插件的AndroidManifest里面设置横竖屏方向吗？

### ISSUE THREAD

**Issue by wuQAQ** [Tencent/Shadow#71]
在代码里面倒是可以设置横竖屏方向，在androidmanifest里面就不起作用了

**Comment by shifujun** [comment]
没做这个支持，因为我们业务用不上。方案我们倒是考虑过。插件的manifest不可能直接生效的，都要靠自己解析出来用Java代码实现。因为屏幕方向是可以用代码设置修改的，所以这个功能是可以实现的。

欢迎帮Shadow实现这个功能。

**Comment by shifujun** [comment]
#1258
