### ISSUE TITLE
如何执行插件的Application

### ISSUE THREAD

**Issue by fsdhr1** [Tencent/Shadow#712]
如何执行插件的Application

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/87d721947f1f05d31ed983037ca8c8e9ea7f8555/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L127-L128

类似的问题，都应该可以通过直接debug插件的代码找到答案。

**Comment by fsdhr1** [comment]
好的谢谢
