### ISSUE TITLE
dynamic-loader-impl和loader能否改成java实现，可以减小大小

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#714]
如题，kotlin语法自身就会携带很多实现，对于网络下载的插件包来讲 能小一点就小一点

**Comment by shifujun** [comment]
kotlin runtime对Proguard是很友好的，它所占的体积和loader本身的代码比大约只有10%。考虑到kotlin对于loader带来的贡献，这是值当的。

我估计你可能没注意到Proguard之后的结果，否则你应该会先提出来。
```
./gradlew :sample-loader:assembleRelease
```
然后查看`projects/sample/source/sample-plugin/sample-loader/build/outputs/apk/release/sample-loader-release.apk`
![image](https://user-images.githubusercontent.com/3535204/145542382-1fee0dbb-ee15-47af-9b9b-22640770c7f6.png)

这里应该是keep了所有shadow的类，所以体积还可以进一步优化。
