### ISSUE TITLE
shadow插件使用apt的问题

### ISSUE THREAD

**Issue by fsdhr1** [Tencent/Shadow#717]
shadow无法和dagger等使用apt的框架兼容吗？

**Comment by shifujun** [comment]
把代码push上来，说明你认为不符合预期的地方。https://github.com/Tencent/Shadow/blob/3d8a6d903c0c00ed934a98540af123b7d47e253f/CONTRIBUTING.md

**Comment by fsdhr1** [comment]
这个问题已经解决，是由于使用java11编译导致部分使用apt的库无法正常使用导致的，感谢您的回复。
