### ISSUE TITLE
Shadow源码解析

### ISSUE THREAD

**Issue by weikaiyun** [Tencent/Shadow#718]
https://weikaiyun.notion.site/Shadow-9dc4501de5f44c508263a753761daae3

**Comment by gb18030** [comment]
请问assemblePluginDebug这个任务是android gradle自带的还是这个框架创建的 如果是框架创建的再哪里创建的  如果是自带的为啥有些工程没有

**Comment by shifujun** [comment]
> 

https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt#L86-L100

https://developer.android.com/studio/build/build-variants#product-flavors

插件工程apply Shadow的Gradle插件，ShadowPlugin就自动添加了plugin和normal两个flavor，这样Android gradle插件就会为每个flavor创建对应的assemble任务。
