### ISSUE TITLE
Task with path ':demo-app:assemblePluginDebug' not found in project ':demo-plugin:demo-app'.

### ISSUE THREAD

**Issue by MmingY** [Tencent/Shadow#722]
我本来想按照您source中的结构写一个demo的，然后我去执行./gradlew packageDebugPlugin的时候就会报上面的那个错误了。Task with path ':demo-app:assemblePluginDebug' not found in project ':demo-plugin:demo-app'.

**Comment by shifujun** [comment]
这个flavor是 e38755ec8fb77adfb5e7e96d8631dd04a1626422 加入的。你得确认一下你的代码包含这个提交了。如果你在用这里发布的版本，至少要是2.2.0才行。
