### ISSUE TITLE
插件中集成高德地图sdk，地图显示黑屏，直接运行sample-app运行正常

### ISSUE THREAD

**Issue by Hxh188** [Tencent/Shadow#724]

**Comment by shifujun** [comment]
就一句话别人能帮你什么呢？

https://github.com/Tencent/Shadow/blob/3d8a6d903c0c00ed934a98540af123b7d47e253f/CONTRIBUTING.md#issue

**Comment by Hxh188** [comment]
https://github.com/Hxh188/Shadow.git  这个工程，你download下来运行下

**Comment by Hxh188** [comment]
在TestActivityOnCreate 这个类里显示地图

**Comment by shifujun** [comment]
这回提供的复现代码就很棒。不过我没能复现：
![image](https://user-images.githubusercontent.com/3535204/147030745-3b0e4302-80aa-4166-831d-77e3de91d2cf.png)

我用的是API 28 x86_64的官方虚拟机。

**Comment by Hxh188** [comment]
直接运行sample-app是正常没错，你运行sample-host,就会黑屏。

**Comment by Hxh188** [comment]
![image](https://user-images.githubusercontent.com/17246178/147032239-905215d4-78f8-4647-ad74-da443974e474.png)

**Comment by shifujun** [comment]
> 直接运行sample-app是正常没错，你运行sample-host,就会黑屏。

我当然不会搞错它们的区别。我前面截图的是sample-host的效果，也就插件模式下的效果。

**Comment by Hxh188** [comment]
我设备是系统android 10的，也就是API level 29, 难道是机型差异？
![Uploading image.png…]()

**Comment by shifujun** [comment]
我又仔细看了一下。这个问题原因是因为这个SDK缺少arm64的so，而sample-host宿主没有so，所以在arm64的手机上默认的ABI是arm64。所以插件中解压不出来arm64的so，缺少so造成的。

所以问题难定位原因主要是因为这个SDK加载so失败而没有抛出异常。

解决办法可以是给sample-host添加一个arm64-v8a的so文件，让它被系统安装时使用兼容ABI就可以了。

![image](https://user-images.githubusercontent.com/3535204/147051681-f3086162-4278-445a-99a9-be44768e0d85.png)

**Comment by Hxh188** [comment]
https://github.com/Hxh188/Shadow.git 代码已经在sample-host添加了so库，目前在模拟器Pixel 4 API 29 上测试没问题，但在真机上测试还是一样是黑屏的==。
还有一个问题，是否后面插件包新增so库都要在宿主包中新增？

**Comment by shifujun** [comment]
你加的`abiFilters`只是一种编译期打包的参数，加了之后`sample-host.apk`中还是没有任何so文件。这样系统在安装和启动它时就会指定ABI为设备的默认值，比如是`arm64`。这样插件也只能用`arm64`了，所以Shadow跑去插件apk中解压`arm64`的so时没有解压出来所需的so。

正确的做法是让插件使用和宿主一样的ABI，所以如果宿主本身已经确定了是`arm64`的，那插件也只能去提供`arm64`的so。

对于`sample-host`这个测试场景，因为它没有任何so，所以可以给它加个`arm64-v8a`的任何so文件，然后启动时load一下。系统会根据第一个加载的so决定应用的ABI。

所以根据前面说的原理，插件后续新增so时不需要特别操作。

**Comment by Hxh188** [comment]
测试的时候没有abiFilters，不好意思我代码没及时更新上去,你更新下代码，还是一样的

**Comment by shifujun** [comment]
https://github.com/Hxh188/Shadow/compare/87b9c95a2da2be15ee61f9cc7b0618c22ebb95f8...master

没看到加载的代码。

**Comment by Hxh188** [comment]
我sample-app 和 sample-host都加了 abiFilters  'armeabi-v7a'， 打包是有so库的,我项目的需求是强制用armeabi-v7a中的so包，所以需要加abiFilters  'armeabi-v7a'，目前在真机测试是黑屏的，git代码已更新
![image](https://user-images.githubusercontent.com/17246178/147065492-1c5df1c0-f9dd-4d2f-a143-345b9492ad3c.png)

**Comment by shifujun** [comment]
你把load的代码指出来？compare一下就那么几行啊，我还能看漏了？

**Comment by Hxh188** [comment]
不好意思，今天git提交不太稳定，代码没push成功，现在push成功了。load 在截图中已标识出来
![image](https://user-images.githubusercontent.com/17246178/147067614-7b699b76-729a-45cc-ad36-6f47f7ecd13c.png)

**Comment by shifujun** [comment]
确定有Bug了。
![image](https://user-images.githubusercontent.com/3535204/147069554-4b675cb6-817b-4c75-b4b6-bc38d8b3815d.png)

你可以先把 97b1d84778d665302da40a654ba35aefc2849963 回滚了，然后手工指定。

**Comment by Hxh188** [comment]
你是说回滚到 97b1d84，然后BasePluginManager的getAbi()返回固定的“armeabi-v7a” 吗？ 目前这样改了是可以，可是debug的时候rtmp so 库的位置还是在/lib/arm/下？？目前是能用了！谢谢了
![image](https://user-images.githubusercontent.com/17246178/147078454-633c975f-1c53-4fe6-ba98-e7a4f1f68dc4.png)

![image](https://user-images.githubusercontent.com/17246178/147078783-510c34e9-cc55-4f72-837e-ea21606465e5.png)

**Comment by shifujun** [comment]
回滚用`git revert 97b1d84`命令。

看起来没有任何公开的API可以获取宿主在安装时被系统选择了什么abi。
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/jni/com_android_internal_content_NativeLibraryHelper.cpp;drc=master;l=442?q=nativeFindSupportedAbi

所以看起来只有一个方法可以自动获取abi了：
Shadow主动提供一个host依赖的native库，只提供一个固定的方法getAbi，然后在每个abi实现中返回对应的字符串。这样让Loader可以通过这个库得知宿主究竟被安装了什么abi。

感觉这样很麻烦，也许手工指定abi是最好的选择。

**Comment by Hxh188** [comment]
OK，牛
