### ISSUE TITLE
导入腾讯地图，无法读取到腾讯地图sdk配置在sample-app下AndroidManifest中的key

### ISSUE THREAD

**Issue by Hxh188** [Tencent/Shadow#728]
导入腾讯地图，无法读取到腾讯地图sdk配置在sample-app下AndroidManifest中的key，需要在宿主sample-host下才能正常。是否可以只要在插件代码中配置就行，而无需改动到宿主代码？
代码地址：https://github.com/Hxh188/Shadow.git

![image](https://user-images.githubusercontent.com/17246178/147193322-e35b6695-f783-4448-af46-fa0265e238f7.png)

**Comment by shifujun** [comment]
meta-data是支持的。看起来你的代码没有写上GET_META_DATA的flag。

https://github.com/Hxh188/Shadow/commit/490d3ae33a3f65e24394f0c62e380274bfbf3cbc?diff=unified#diff-4396e8dd86ec309d89b4f6b77264485552addc7764e22e713e0c37e2248d5835R72

自动化测试：
https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/test/plugin/general-cases/test-plugin-general-cases/src/main/java/com/tencent/shadow/test/plugin/general_cases/lib/usecases/packagemanager/TestPackageManagerActivity.java#L64

**Comment by Hxh188** [comment]
不是，腾讯地图sdk 只需在AndroidManifest中配置key就行，但是key 读取不到。

**Comment by Hxh188** [comment]
不需要在代码中读取，地图sdk内部会自行读取，但似乎读取不到key

**Comment by shifujun** [comment]
![image](https://user-images.githubusercontent.com/3535204/147233165-e692875b-9d25-4fc0-93e9-1c57f145cc9b.png)

这不是能读到吗？

**Comment by Hxh188** [comment]
![image](https://user-images.githubusercontent.com/17246178/147244353-f97e935d-a3b7-4e84-9000-411738a75e2e.png)
是能读到，不过初始化失败了，提示KEY_IS_REQUIRED, 即keyque'shi缺失

**Comment by shifujun** [comment]
我简化了一下改动：https://github.com/Tencent/Shadow/compare/master...shifujun:issue728

这个在sample-app独立安装运行时也是一样的报错的。你这个key是不是不可用呀？

**Comment by Hxh188** [comment]
你代码更新下，我这边是正常的

![image](https://user-images.githubusercontent.com/17246178/147311885-1836f83d-ed47-4030-a443-cb57b0145b7d.png)

**Comment by shifujun** [comment]
https://github.com/Hxh188/Shadow/pull/1

这样改应该可以了。这里关键问题是SDK自行动态加载了没有被Shadow Transform处理过的代码。所以这种场景也不是都能简单兼容的。只是恰好它只需要ApplicationInfo，可以这样兼容它。

**Comment by Hxh188** [comment]
嗯，可以了
