### ISSUE TITLE
我们的组件化是用的阿里的ARouter，然后Shadow和ARouter两者兼容嘛？

### ISSUE THREAD

**Issue by nianzixin** [Tencent/Shadow#73]

**Comment by shifujun** [comment]
支持的。之前有点小bug已经修复了。
https://github.com/Tencent/Shadow/issues/38

另外类似的支不支持什么sdk的问题，可以在sample中自己接入一下试试。我们并不是了解所以sdk的支持情况。Shadow从原理上来说，只可能会和字节码编辑技术的sdk有冲突。像ARoute这种注解技术的sdk应该是完全没影响的。
