### ISSUE TITLE
java.lang.ClassCastException: androidx.lifecycle.ReportFragment

### ISSUE THREAD

**Issue by itwangyu** [Tencent/Shadow#732]
插件里面的activity继承AppCompatActivity,线上出现了很多ClassCastException。

java.lang.RuntimeException: java.lang.ClassCastException: androidx.lifecycle.ReportFragment cannot be cast to androidx.lifecycle.ReportFragment
com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:361)

com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(Unknown Source:58)

android.app.Activity.performCreate(Activity.java:7458)

android.app.Activity.performCreate(Activity.java:7448)

android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)

android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)

android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)

android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)

android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)

android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)

android.os.Handler.dispatchMessage(Handler.java:112)

android.os.Looper.loop(Looper.java:216)

android.app.ActivityThread.main(ActivityThread.java:7625)

java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)

com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

请问一下这个应该怎么改，我现在还没办法复现这个问题

**Comment by shifujun** [comment]
这个应该是因为宿主和插件都有ReportFragment这套lifecycle机制。然后它们是根据TAG来查找Fragment的，所以宿主也会拿到插件的Fragment。
可以先参考这个提交兼容这个问题：https://github.com/hgx1001/Shadow/commit/3de1273d4ff08f29ad9a50076d378df5a8496706

**Comment by itwangyu** [comment]
好，谢谢大神，我改一下试试
