### ISSUE TITLE
在宿主app 不重启的情况下，能否直接热更新插件的功能

### ISSUE THREAD

**Issue by Hxh188** [Tencent/Shadow#733]
在宿主app不重启的情况下，能否直接热更新插件的功能

**Comment by shifujun** [comment]
看技术层面你考虑的是什么场景。“宿主app 不重启“是一个模糊的概念。假如插件和宿主app工作在同一个进程，那是必须重启的，因为没有任何公开的API可以更新已经加载的class，也没有公开的API可以卸载so。假如插件工作在独立的进程中，我们可以认为这个进程没有宿主app的组件了，那么重启这个进程也可以认为是没有重启宿主app的。
