### ISSUE TITLE
腾讯maven仓不支持TLSv1.2

### ISSUE THREAD

**Issue by cainiaoxiaomin** [Tencent/Shadow#738]
下载了源码，无法编译通过，报错说无法获取POM文件，server可能不支持TLSv1.2，浏览器可以打开，这个大家是怎么解决的。
![123](https://user-images.githubusercontent.com/26954011/147737244-7f82391b-5cb8-4028-9762-fd9d3128e20c.PNG)
![321](https://user-images.githubusercontent.com/26954011/147737297-c9dc1644-4edd-4b84-a3ea-1f5fd5ea4c31.PNG)

**Comment by shifujun** [comment]
可以先参考下#667 的debug过程。提供下有问题的服务器ip和测试证据。

**Comment by shifujun** [comment]
不想理这个问题的话，可以搜一下代码中的`DISABLE_TENCENT_MAVEN_MIRROR`，去掉腾讯的软件源镜像。项目不依赖腾讯软件源中任何专有的包。

**Comment by cainiaoxiaomin** [comment]
> 
DISABLE_TENCENT_MAVEN_MIRROR这个值默认不就是true么

**Comment by shifujun** [comment]
`DISABLE_TENCENT_MAVEN_MIRROR`是个环境变量名，咱们本地默认肯定没有这个环境变量的。代码中是CI配置了`true`的值，为了避免在国际网的Github Action服务器访问腾讯软件源。这个没有必要。

**Comment by cainiaoxiaomin** [comment]
> 

这个问题解决了，多谢大佬。androidstudio更新ing...
