### ISSUE TITLE
打开插件报错

### ISSUE THREAD

**Issue by chenli3238** [Tencent/Shadow#74]
调用application.getPluginLoader().getMComponentManager().convertPluginActivityIntent(pluginIntent);

用的是demo的apk，
public void startPlugin(View view) {
        AwsApplication application = (AwsApplication) getApplication();
        application.loadPlugin(AwsApplication.PART_MAIN);

        Intent pluginIntent = new Intent();
        pluginIntent.setClassName(getPackageName(), "com.tencent.shadow.test.plugin.general_cases.lib.usecases.activity.TestActivityOnCreate");
        //application.getPluginLoader().getMComponentManager().convertPluginActivityIntent()

        Intent intent = application.getPluginLoader().getMComponentManager().convertPluginActivityIntent(pluginIntent);
        startActivity(intent);
    }

kotlin.KotlinNullPointerException
        at com.tencent.shadow.core.loader.managers.ComponentManager.toActivityContainerIntent(Unknown Source:17)
        at com.tencent.shadow.core.loader.managers.ComponentManager.convertPluginActivityIntent(Unknown Source:11)

**Comment by shifujun** [comment]
你贴出来的代码和堆栈不是很好看明白。能不能简单的把你的工程push上来？我拉下来你的代码看看你改了什么。

**Comment by chenli3238** [comment]
> 你贴出来的代码和堆栈不是很好看明白。能不能简单的把你的工程push上来？我拉下来你的代码看看你改了什么。

我测试出来了，必须host和plugin包名保持一致才没问题，我把源码中一处包名相同判断取消了，怎么打开插件还有判断啊，这个在哪修改

**Comment by shifujun** [comment]
你都说你测出来了，必须host和plugin包名保持一致才没问题。那怎么还改Shadow的源码，改出问题了，还问我们怎么办？我们能说的不就是你改回去么？

**Comment by chenli3238** [comment]
> 你都说你测出来了，必须host和plugin包名保持一致才没问题。那怎么还改Shadow的源码，改出问题了，还问我们怎么办？我们能说的不就是你改回去么？

我的意思是我们第三方的项目很多，不可能要求大家都改包名，能不能包名不一致？

**Comment by shifujun** [comment]
关于这个问题之前已经写过一段文字解释过了：
https://juejin.im/post/5d13579cf265da1b957067af

你不应该要求大家改包名，而是帮大家改包名。用一些简单的Gradle技巧配合CI就行了。
