### ISSUE TITLE
PluginManifest NoClassDefFoundError

### ISSUE THREAD

**Issue by MmingY** [Tencent/Shadow#745]
我看见在最新的sdk中启用了PluginClassLoader类中的loadPluginManifest方法，然后报了这个类找不到“com.tencent.shadow.core.manifest_parser.PluginManifest”，我根据包名在sdk中的确找不到这个类哎~

**Comment by Daimhim** [comment]
同上，我也遇到了相同的问题。在插件apk的加载过程中找不到生成的com.tencent.shadow.core.manifest_parser.PluginManifest类，在demo官方中验证是有生成的。
请问一下 这个类的生成需要哪些必要的配置

顺便提一下这个新增的生成模块没有配置远程库，导致依赖到项目时编译报错。可以使用下面的配置打包到远程仓库

![lALPJwY7RDfj4mzNA0fNBJ4_1182_839](https://user-images.githubusercontent.com/20254978/148042498-4fe68223-7808-46ab-b845-43378b5d0f84.png)

**Comment by shifujun** [comment]
确实是漏了发布pom的配置。maven的sample还没有使用这个代码。

生成PluginManifest.java是`apply plugin: 'com.tencent.shadow.plugin'`插件自动添加的任务。
https://github.com/Tencent/Shadow/blob/307800cd93ca6a4f7613195892c43253ccd8f0e6/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt#L106-L119

所以它是`compilePluginDebugJavaWithJavac`的依赖任务。如果一切正常还是没有生成，有可能是因为Gradle Cache判断compilePluginDebugJavaWithJavac任务不需要重新执行，没有执行`generatePluginDebugPluginManifest`。可以先把`org.gradle.caching`关掉试试：
https://github.com/Tencent/Shadow/blob/307800cd93ca6a4f7613195892c43253ccd8f0e6/gradle.properties#L15

**Comment by shifujun** [comment]
> 我根据包名在sdk中的确找不到这个类

这个类不在SDK中，是通过给插件工程生成代码，添加到插件中的。
https://github.com/Tencent/Shadow/blob/307800cd93ca6a4f7613195892c43253ccd8f0e6/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt#L121-L124

**Comment by Daimhim** [comment]
生成了但是 打不进插件包 ，插件运行还是找不到。插件的dex里面也没有这个文件
![image](https://user-images.githubusercontent.com/20254978/148062246-68201b24-9730-45dd-9757-4e62649e8854.png)

**Comment by shifujun** [comment]
> 生成了但是 打不进插件包 ，插件运行还是找不到。插件的dex里面也没有这个文件 ![image](https://user-images.githubusercontent.com/20254978/148062246-68201b24-9730-45dd-9757-4e62649e8854.png)

缓存关闭了吗？AGP是什么版本呢？

**Comment by Daimhim** [comment]
gradle-7.0.2-bin.zip 
classpath "com.android.tools.build:gradle:7.0.3"
build_Tools_Version = "29.0.2"
kotlin_version = '1.5.31'
android Studio 2020.3.1 patch 4

org.gradle.caching=false|true 参数都试过一样的结果

目前的状态是PluginManifest已经生成了，build\generated\source\pluginManifest\pluginDebug\com\tencent\shadow\core\manifest_parser\PluginManifest.java

但是打出来的插件包里面不包含这个类，是不是我这边gradle配置有什么问题
![image](https://user-images.githubusercontent.com/20254978/148180363-dcbef53f-1bf0-4bb4-b79f-5bf369d3d418.png)

这个是目前插件的gradle配置
`
apply from: "../configurationDev/build_config.gradle"
apply plugin: 'com.tencent.shadow.plugin'

android {

    defaultConfig {
        applicationId application_id
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.create("release")
            signingConfig.initWith(buildTypes.debug.signingConfig)
        }
    }
//    compileOptions {
//        sourceCompatibility JavaVersion.VERSION_1_8
//        targetCompatibility JavaVersion.VERSION_1_8
//    }
    // 将插件applicationId设置为和宿主相同
    productFlavors {
        plugin {
            applicationId application_id
        }
    }
}

dependencies {

    testImplementation androidTest.junit
    androidTestImplementation androidTest.androidx_junit
    androidTestImplementation androidTest.espresso_core
//    implementation project(path: componentDependencies.qgb_zcore) // 基础base
    implementation project(path: componentDependencies.plugin_core)//插件共用
    pluginCompileOnly "com.tencent.shadow.core:runtime:$shadow_version"
}
def createDuplicateApkTask(buildType) {
    def apkDir = file("${getBuildDir()}/outputs/apk/$buildType")

    return tasks.create("duplicatePlugin${buildType.capitalize()}ApkTask", Copy) {
        group = 'build'
        description = "复制一个testrout-${buildType}.apk用于测试目的"
        from(apkDir) {
            include("testrout-plugin-${buildType}.apk")
            rename { "testrout-plugin-${buildType}2.apk" }
        }
        into(apkDir)

    }.dependsOn(":testrout:assemblePlugin${buildType.capitalize()}")
}

tasks.whenTaskAdded { task ->
    if (task.name == "assemblePluginDebug") {
        def createTask = createDuplicateApkTask('debug')
        task.finalizedBy(createTask)
    }
    if (task.name == "assemblePluginRelease") {
        def createTask = createDuplicateApkTask('release')
        task.finalizedBy(createTask)
    }
}

shadow {
    packagePlugin {
        pluginTypes {
            debug {
                loaderApkConfig = new Tuple2('plugin-loader-debug.apk', ':plugin-loader:assembleDebug')
                runtimeApkConfig = new Tuple2('plugin-runtime-debug.apk', ':plugin-runtime:assembleDebug')
                pluginApks {
                    pluginApk1 {
//                        uuid = "D71E09E5-123B-4232-9279-410E49077CC1"
                        businessName = ''//businessName相同的插件，context获取的Dir是相同的。businessName留空，表示和宿主相同业务，直接使用宿主的Dir。
                        partKey = 'rout'
                        buildTask = 'assembleDebug'
                        apkName = 'testrout-plugin-debug.apk'
                        apkPath = 'testrout/build/outputs/apk/plugin/debug/testrout-plugin-debug.apk'
                        hostWhiteList = ["com.alibaba.android.arouter",
                                         "com.alibaba.android.arouter.facade.model",
                                         "com.alibaba.android.arouter.launcher",
                                         "com.alibaba.android.arouter.facade.enums",
                                         "com.alibaba.android.arouter.facade.template",]// 配置允许插件访问宿主的类
                    }
                }
            }

            release {
                loaderApkConfig = new Tuple2('plugin-loader-release-unsigned.apk', ':plugin-loader:assembleRelease')
                runtimeApkConfig = new Tuple2('plugin-runtime-release-unsigned.apk', ':plugin-runtime:assembleRelease')
                pluginApks {
                    pluginApk1 {
                        businessName = ''
                        partKey = 'rout'
                        buildTask = 'assembleRelease'
                        apkName = 'testrout-plugin-release-unsigned.apk'
                        apkPath = 'testrout/build/outputs/apk/plugin/release/testrout-plugin-release-unsigned.apk'
                        hostWhiteList = ["com.alibaba.android.arouter",
                                         "com.alibaba.android.arouter.launcher",
                                         "com.alibaba.android.arouter.facade.model",
                                         "com.alibaba.android.arouter.facade.enums",
                                         "com.alibaba.android.arouter.facade.template",]// 配置允许插件访问宿主的类
                    }
                }
            }
        }

        loaderApkProjectPath = 'plugin-loader'
        runtimeApkProjectPath = 'plugin-runtime'

        archiveSuffix = System.getenv("PluginSuffix") ?: ""
        archivePrefix = 'plugin'
        destinationDir = "${getRootProject().getBuildDir()}"

        version = 1
        compactVersion = [0]
        uuidNickName = "1.0.0"
    }
}
`

**Comment by shifujun** [comment]
org.gradle.caching=false 然后gradle clean或者把build目录删掉，也可能是up-to-date逻辑跳过apk构建了。

**Comment by Daimhim** [comment]
找到问题了，不能使用kotlin的生成器。。。

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

去掉之后打包就有了，大佬这可以改善兼容吗？

**Comment by shifujun** [comment]
把`apply plugin: 'com.tencent.shadow.plugin'`写在它们之后确实能复现问题。写在它们前面就没问题了：
```
apply plugin: 'com.android.application'
apply plugin: 'com.tencent.shadow.plugin'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
```

我觉得这个可能是`kotlin-kapt`的bug。因为如果有问题时，把IDE的Build Variants改成pluginDebug，也可能看到IDE已经正常把`build/generated/source/pluginManifest`列为源码目录了。

**Comment by shifujun** [comment]
是`apply plugin: 'kotlin-android'`和`apply plugin: 'com.tencent.shadow.plugin'`的顺序的问题。跟`kotlin-kapt`没关系。
