### ISSUE TITLE
宿主和插件互调的问题

### ISSUE THREAD

**Issue by jychenX** [Tencent/Shadow#746]
框架目前只提供了预加载，以及四大组件调用的接口；如果宿主要直接调用插件，还需要改造框架，抛出插件的classloader；或者采用当前这种：依赖注入方式通过白名单的注册，去调用宿主再让宿主回调给插件，这样来来回回稍微有点麻烦，在涉及到需要使用很多处交互调用的时候可能非常不方便，你们有考虑过将多个classloader合并pathList和dexelements的方案吗？或者其它更方便的方案

**Comment by shifujun** [comment]
方便与可维护性是不容易双赢的。目前代码设计的白名单是为了帮助实现宿主和插件版本的多对多兼容性，让它们只交换有限的接口。

关于麻烦的问题，倒是可以通过引入一个DI框架解决。可能现有框架做一些跨ClassLoader的适配就可以了。也可以配合注解等技术自动生成白名单。
