### ISSUE TITLE
启动插件报错 Unable to find explicit activity class ; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by godlikewangjun** [Tencent/Shadow#75]
我修改了，插件的包名和manager的包名，启动插件报错，请问还需要改哪里。` @Override
    public void enter(final Context context, long fromId, Bundle bundle, final EnterCallback callback) {
        if (fromId == Constant.FROM_ID_START_ACTIVITY) {
            bundle.putString(Constant.KEY_PLUGIN_ZIP_PATH, "/data/local/tmp/plugin-debug.zip");
            bundle.putString(Constant.KEY_PLUGIN_PART_KEY, "sample-plugin");
            bundle.putString(Constant.KEY_ACTIVITY_CLASSNAME, "com.wj.makebai.plugin.MainActivity");
            onStartActivity(context, bundle, callback);
        } else if (fromId == Constant.FROM_ID_CALL_SERVICE) {
            callPluginService(context);
        } else {
            throw new IllegalArgumentException("不认识的fromId==" + fromId);
        }
    }`
这个地方也改了

**Comment by guok2046** [comment]
1.检查activity名称是否正确
2.检查插件所在工程的AndroidManifest中是否注册了activity，建议直接反编译插件查看

**Comment by godlikewangjun** [comment]
单独都可以运行，打的包里面反编译是这个名字com.wj.makebai.plugin.MainActivitycom.wj.makebai.plugin.MainActivity
![image](https://user-images.githubusercontent.com/7495222/62032200-adb9b200-b21b-11e9-90f6-6e99c1e40df9.png)

**Comment by guok2046** [comment]
看代码是注册了，你上面提到修改包名。shadow要求插件和宿主包名保持一致，这里是否一致

**Comment by godlikewangjun** [comment]
`
android {
    defaultConfig {
        //再把applicationId改成宿主的
        applicationId "com.wj.makebai"
    }
}`
这个忘了改，现在可以了

**Comment by godlikewangjun** [comment]
但是启动插件

> java.lang.RuntimeException: java.lang.ClassCastException: com.wj.makebai.plugin.MainActivity cannot be cast to com.tencent.shadow.core.runtime.PluginActivity
