### ISSUE TITLE
Shadow支持android support版本

### ISSUE THREAD

**Issue by wanshijie3** [Tencent/Shadow#750]
shadow目前是否有支持android support的版本或者有没有从当前版本降级的思路?

**Comment by shifujun** [comment]
先把问题描述清楚。如果描述不清楚，就用代码表达：https://github.com/Tencent/Shadow/blob/669f8b5cb11142df9b50ee3dc221f87adaebc30d/CONTRIBUTING.md#issue

**Comment by wanshijie3** [comment]
我的项目目前还没有升级到androidx,如果想要集成shadow,直接把shadow直接从当前版本手动降级是否可行?

**Comment by shifujun** [comment]
建议还是按前面文档提示，把代码push上来。看不懂“当前版本”和“手动降级”指的是什么。什么都不做不可行在哪？

**Comment by Daimhim** [comment]
Android 源码、androidx、support

androidx与support的修改都不牵扯Android 源码，他们只是对源码进行了封装、扩展

Shadow的作用域在替换、代理插件中的 Android 源码，理论上不牵扯androidx与support

**Comment by wanshijie3** [comment]
好的,谢谢解答
