### ISSUE TITLE
插件和宿主可以共用资源文件吗？

### ISSUE THREAD

**Issue by MmingY** [Tencent/Shadow#760]
您好，我想请教一下插件和宿主可以共用图片和布局资源吗？因为有些资源插件和宿主是一样的，如果每个插件和宿主都有一套感觉会太大了。

**Comment by shifujun** [comment]
资源本身肯定是可以复用的，但是资源ID是一种编译产物，所以不能直接通过资源ID去复用。

通过资源ID复用，需要应用aapt固定ID的设计。这个目前没有示例代码。

还可以通过普通的Java接口复用资源，每个插件或者宿主通过Java接口返回资源，在实现时从自己的Resource对象中取出来。

不能直接复用的根本原因是宿主和插件的版本关系是多对多的。
