### ISSUE TITLE
测试Demo中多个Plugin多次(在不同的zip包中)加载后可能导致只能打开其中一个

### ISSUE THREAD

**Issue by gb18030** [Tencent/Shadow#761]
[这个地方](https://github.com/Tencent/Shadow/blob/68d54d9a06a92a657ea63ba2bf3389db772ada04/projects/sample/maven/manager-project/sample-manager/src/main/java/com/tencent/shadow/sample/manager/FastPluginManager.java#L94)是不是考虑做如下修改 通过uuid获取plugin的信息
![image](https://user-images.githubusercontent.com/19511418/148521795-f2562cfe-e033-484f-bab9-a30f4c0d931f.png)
出错时的数据库信息
![image](https://user-images.githubusercontent.com/19511418/148522214-fef253f8-4ac9-4628-bd44-bc96773a3edf.png)

我想加载uuid为A6530172-CBF6-4CA1-95E8-6145F40AC9DE的插件 但原来的逻辑是加载的uuid为22469FDE-79C8-46F9-8E11-2B99FE213D8F的插件

**Comment by Daimhim** [comment]
我已经这么干了，但目前有新的问题 开发阶段 ，每次运行，都会出现新的zip，原因时解压后会不停的产生解压文件 不知道有什么有效的解决手段没

**Comment by shifujun** [comment]
`sample-host`中只有一个`plugin-debug.zip`，`FastPluginManager`也只是sample的代码，所以对它来说每次只打开最新安装的插件是没问题的。

如何下载安装启动插件是Manager该负责的逻辑，这里`SamplePluginManager`和`FastPluginManager`的任务就是每次都新安装启动打包在assets中的插件。

不同业务的这部分流程差异太大，所以目前只有`BasePluginManager`提供各种原子方法供业务组合。
