### ISSUE TITLE
插件中快速点击两次底部tab切换activity，宿主会退到桌面？

### ISSUE THREAD

**Issue by piaomiao8179** [Tencent/Shadow#768]
@shifujun 大佬 请教一个问题：
 我的插件app里底部有5个tab切换标签，每个标签对应一个activity，当我点击一次的时候能正常跳转，但是快速点击两次tab标签，宿主会回退到桌面，不是crash，请问遇到过这个问题吗？

急切盼望回复，谢谢。

**Comment by shifujun** [comment]
又来让我猜呀🤦‍♂️，可以把代码push上来一起看看。

首先确定没有Crash要观察点击按钮前的进程号和退回桌面后的进程号是否一致。

然后如果没有Crash，这里应该涉及的问题是同一个Activity短时间内重复启动的问题。
先观察一下不使用插件环境下Activity的启动行为，确定和插件环境表现不一样，再查问题。

Shadow启动插件Activity也非常简单，跟正常启动Activity一样，也是给系统发一个Intent，
要求启动一个宿主中的壳子Activity。所以对系统来说，是否在插件环境下运行，
区别只在于启动的Classname和Manifest中注册的相关属性。

可以先把壳子Activity在Manifest中的属性全部设置为和插件Activity一致的，来观察一下插件和非插件环境下是否表现一致。

关于Activity栈状态查看可以参考：
https://stackoverflow.com/questions/2442713/view-the-tasks-activity-stack

另外，短时间内向系统发出相同内容的Intent，本身就是不合理的。建议给按钮加上限频控制。问题可能就不存在了。

**Comment by piaomiao8179** [comment]
1. 插件环境下没有问题。

**Comment by piaomiao8179** [comment]
- 插件环境下没有问题。
- 宿主中的Manifest和插件中的已经修改一致。
- 进程号一致。
所以比较疑惑，按道理来说不应该这样，开始以为是坑位不够，在宿主和插件中增加了坑位数量，还是这种情况。

**Comment by shifujun** [comment]
我猜你快速点击的是同一个按钮，所以和非插件环境下的区别只在于Activity的Manifest属性。如果你点不是同一个按钮，那插件环境下，你有可能给插件Activity匹配了同一个壳子Activity，对系统来说就是在启动同一个Activity了。

从原理上来说就是这样。没有代码别的就猜不到了。

**Comment by piaomiao8179** [comment]
是第一种情况，点击的同一个按钮，点击时间做了处理了，防止频繁点击，间隔1s，第二次没有执行下面的跳转逻辑。
`binding.getRoot().setOnClickListener(v -> {
            if (FastClickUtils.isFastClick()) {
                Log.e("您点击的太快了", "请稍侯");
                return;
            }
            if (position != lastClickPosition) {
                lastClickPosition = position;
                if (onItemClickListener != null) {
                    onItemClickListener.itemClick(moreSetting.getTitle());
                }
                notifyDataSetChanged();
            }
        });`

`@Override
    public ComponentName onBindContainerActivity(ComponentName pluginActivity) {
        switch (pluginActivity.getClassName()) {
            case "com.echase.mycasher.ui.LoginActivity":
                return new ComponentName(context, SINGLE_TASK_ACTIVITY);
            case "com.echase.mycasher.ui.DeskActivity":
                return new ComponentName(context, SINGLE_TASK_1_ACTIVITY);
            case "com.echase.mycasher.ui.DishActivity":
                return new ComponentName(context, SINGLE_TASK_2_ACTIVITY);
            case "com.echase.mycasher.ui.OrderActivity":
                return new ComponentName(context, SINGLE_TASK_3_ACTIVITY);
            case "com.echase.mycasher.ui.SettingActivity":
                return new ComponentName(context, SINGLE_TASK_4_ACTIVITY);
            case "com.echase.mycasher.ui.PaymentActivity":
                return new ComponentName(context, DEFAULT_1_ACTIVITY);
            case "com.echase.mycasher.ui.DeskManagerActivity":
                return new ComponentName(context, DEFAULT_2_ACTIVITY);
            case "com.echase.mycasher.ui.SyncDataActivity":
                return new ComponentName(context, DEFAULT_3_ACTIVITY);
            case "com.echase.mycasher.ui.ProductManagerActivity":
                return new ComponentName(context, DEFAULT_4_ACTIVITY);
            case "com.echase.mycasher.ui.MemberManagerActivity":
                return new ComponentName(context, DEFAULT_5_ACTIVITY);
        }
        return new ComponentName(context, DEFAULT_ACTIVITY);
    }`

**Comment by piaomiao8179** [comment]
我尝试了将startActivity注释掉，就不会出现这种退出的情况了，应该是跳转逻辑出了问题。连续快速点击同一个按钮，可能是宿主执行的比较慢，执行了两次startActivity，启动了两次同一个界面 出现的问题。
