### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by Hxh188** [Tencent/Shadow#769]
现在有个问题就是宿主apk 和插件 apk 混淆后，如果两个apk中不同的类混淆成了同一个类型，会导致类加载错误，比如宿主apk中com.host.util.HostUtil混淆成了b.a.c， 而插件apk中的com.plugin.util.MyUtil混淆成了b.a.c，这样可能导致类加载错误，请问如何解决这个潜在问题

**Comment by shifujun** [comment]
这是个普通的Proguard问题，可以参考Proguard手册：
https://www.guardsquare.com/manual/configuration/usage

两个选择，要么keep住这些接口，不让Proguard混淆它们。要么应用`-applymapping`选择，让它们保持相同的混淆规则。

**Comment by YiScond** [comment]
插件的proguard使用以下配置
如下示例，将被混淆的类统一放到包名为pluginA的下面
```
-flattenpackagehierarchy 'pluginA'
```
或者
```
-repackageclasses 'pluginA'
```
