### ISSUE TITLE
集成打开插件报错  cannot be cast to com.tencent.shadow.core.runtime.PluginActivity

### ISSUE THREAD

**Issue by godlikewangjun** [Tencent/Shadow#77]
> Unable to start activity ComponentInfo{com.wj.makebai/com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: java.lang.ClassCastException: com.wj.makebai.plugin.MainActivity cannot be cast to com.tencent.shadow.core.runtime.PluginActivity

>  Caused by: java.lang.RuntimeException: java.lang.ClassCastException: com.wj.makebai.plugin.MainActivity cannot be cast to com.tencent.shadow.core.runtime.PluginActivity
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:153)

**Comment by shifujun** [comment]
看看其他activity有没有被transform成shadowactivity。如果单单只有这一个activity没有转换成功，可能遇到什么bug了。但是你不把代码push上来，我们也分析不了。

**Comment by godlikewangjun** [comment]
需要哪部分的代码

**Comment by godlikewangjun** [comment]
和gradle版本有关系吗

**Comment by shifujun** [comment]
当然是所有代码啦。跟什么有关系都有可能，没有代码乱猜是没有意义的。

**Comment by godlikewangjun** [comment]
[MakeBai.zip](https://github.com/Tencent/Shadow/files/3445328/MakeBai.zip)
接口本地的哦，直接跳MainAcActivuty

**Comment by shifujun** [comment]
能不能不传附件呢？如果不是在Shadow工程上进行的修改，我可能就帮不了你了。如果是在Shadow工程上的修改，你直接push到你名下的仓库就好了。

**Comment by godlikewangjun** [comment]
Shadow工程上改了 我看是对的，我重新导入就好了，不知道啥问题
