### ISSUE TITLE
插件中启动A-Activity，在插件最小化之后，宿主启动的插件Activity始终是A-Activity

### ISSUE THREAD

**Issue by is0308** [Tencent/Shadow#774]
A-Activity的启动模式是SingleTask，请问一下，是因为这个Activity没有finish吗，该怎么修改？

**Comment by is0308** [comment]
明白了，但是我启动的所有Activity都是singletask，按照插件设计就只有一个实际的代理Activity，那就会导致跳转失败
我A-Activity(singletask) 跳转到 B-Activity(singletask)这种跳转不了，且上面问题因为跳转的因为都是singletask，就问题解决不了，我设置taskAffinity应为就一个代理Activity，所以taskAffinity无效对吗，那这种插件的Activity都是singletask，有什么解决方案吗

**Comment by is0308** [comment]
即使我使用standard启动A-Activity，最小化插件之后，在宿主启动其他Activity的仍然还是A-Activity

**Comment by shifujun** [comment]
所有插件Activity都是singletask的话，如果最多同时有n个activity没有finish，那宿主中就需要至少n个对应的singletask的PluginContainerActivity。

你可以通过观察非插件环境和插件环境下的activity栈情况来理解。
关于Activity栈状态查看可以参考：
https://stackoverflow.com/questions/2442713/view-the-tasks-activity-stack

前两天也有类似的issue #768

**Comment by is0308** [comment]
明白了，谢谢

**Comment by 1455033987** [comment]
所以壳子activity最好不要设成singleTask模式，处理起来会很麻烦
