### ISSUE TITLE
宿主如何获取插件Activity的实例？

### ISSUE THREAD

**Issue by is0308** [Tencent/Shadow#776]
在ActivityLifecycleCallbacks中能够回调onActivityCreated方法，但是将插件Activity实例存储到集合中，获取插件activity一直为空，但是添加到集合中了，请问是我写法不对吗，或者有什么别的方法获取到插件Activity的Activity实例

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/d0d0b927eaf07064ed3cd10920d6f3e4d706639b/projects/sdk/core/activity-container/src/main/java/com/tencent/shadow/core/runtime/container/PluginContainerActivity.java#L63

这个`PluginContainerActivity`是宿主中的壳子Activity基类。由它持有插件Activity，并转调它的各种对应方法。

https://github.com/Tencent/Shadow/blob/d0d0b927eaf07064ed3cd10920d6f3e4d706639b/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/PluginActivity.java#L34-L36

runtime就是这样获取的插件Activity。
