### ISSUE TITLE
关于目前插件化框架在不改动插件APK的情况下，宿主可直接唤醒的技术可行性

### ISSUE THREAD

**Issue by whiteopaper** [Tencent/Shadow#777]
大大，冒昧咨询Shadow是否支持如题的需求？

在下近日了解目前大部分插件化框架如Replugin，似乎都需要插件应用添加依赖等改动，于是产生了对不改动现有应用的情况是否可直接打开的技术可行性研究，是否存在android机制上的障碍？

**Comment by shifujun** [comment]
没太理解”改动“指的是哪些改动，可以举例说一下。

如果是说可以正常安装运行的apk，不做任何修改，希望能直接免安装运行。这在Android系统上通常来讲是不行的。如果可行，要么是找到了系统漏洞，要么是这个apk本身与系统API高度解耦，像Shadow编辑过的apk一样，可以被其他应用作为普通Java库加载运行。

**Comment by whiteopaper** [comment]
以Replugin为例，改动有两处，第一是项目根目录的 build.gradle添加插件依赖，第二是在 app/build.gradle 中应用插件，并添加依赖包，否则无法使用。

您刚指出的Shadow编辑过的apk，这个编辑动作是否指在插件应用工程里也添加类似Replugin的某些改动？

以您的理解，目前技术上是不支持android系统不允许直接免安装运行是吗？

**Comment by shifujun** [comment]
插件框架都是在尽量绕过Android系统必须安装apk才能启动其中Activity等组件的限制。

Shadow的主要目的是尽量让业务代码不需要修改来达到免安装的效果。实际上插件apk是和正常安装的apk的代码不一样的。只是源代码一样。

在越来越新的Android上，免安装运行已经越来越受限了。好在Android系统总是还开放动态库的加载。所以按照Shadow的原理，尽量将插件代码与系统API分离，总是可以动态化那些业务自身逻辑的。

直接免安装运行，理论上来说是不可能的。就算找到方法，也不具备长远的可维护性。

**Comment by whiteopaper** [comment]
感谢，您的解答让我受益匪浅
