### ISSUE TITLE
scheme启动插件Activity

### ISSUE THREAD

**Issue by choofake** [Tencent/Shadow#778]
插件已经启动了，怎么使用scheme方式启动插件中的Activity

**Comment by shifujun** [comment]
https://developer.android.com/training/app-links
讨论的应该是这种方式对吧？

这种Deep links是系统和Activity的交互接口，所以也需要通过宿主Activity中转。

Shadow目前的代码并没有特殊处理这个接口。
如果是插件内部跳转或者宿主跳转插件，显然都不应该用这种麻烦系统的方式，应该可以内部用Router模式解决的。

如果是外部应用希望通过Deep links打开插件Activity，建议在宿主Activity中注册相应scheme，然后再通过manager打开插件Activity。

确实通过manager再次打开插件Activity实际上对于系统来说是跳转了2次Activity。这里可以通过修改PluginContainerActivity的逻辑，支持从此种隐式意图的Intent直接转换为插件Intent加载。

**Comment by choofake** [comment]
感谢大佬，按照您说的，通过manager打开，功能测试可以了。
只是这种方式怪怪的，有直接一点的吗

**Comment by shifujun** [comment]
> 只是这种方式怪怪的，有直接一点的吗

“怪怪的”和“直接”都是比较主观的词汇。你可以用代码表达的清楚一些。

让我猜的话，是想直接在宿主里调用startPluginSomething的方法吧。没有这样的接口的原因是，在dynamic设计下，宿主和插件之间约定的接口只有一个enter方法，以便manager、loader逻辑可以足够动态。

**Comment by choofake** [comment]
不好意思，没描述清楚。
是这样的，我想不需要在宿主注册scheme，启动插件后，可以通过scheme打开插件的Activity

在插件使用其他SDK的时候，比如第三方登录，授权后返回用scheme的方式。
授权后不能返回，不熟悉的SDK，不知道怎么注册scheme

所以想请教大佬，能不能做到像正常打开Activity一样使用scheme方式打开插件Activity，这样比较有通用性。

**Comment by shifujun** [comment]
> 比如第三方登录，授权后返回用scheme的方式

按照这个场景我明白你想要的了。这个和最初说的问题也是一致的。这种SDK希望通过接入方尽可能方便，就通过aar带入一个Manifest设置，让接入app响应固定的scheme。这样回调时可以通过固定的scheme返回原应用。

这个场景确实是在通过系统API从一个已安装的应用打开另一个已安装的应用。我们无法突破系统的这一限制。

如果这种SDK采用的是像PendingIntent一样的机制，我们倒是可以将插件Intent转换为宿主中的Intent交给系统使用。所以PendingIntent交给系统，是可以被系统回调打开插件Activity的。

**Comment by choofake** [comment]
这样的话，就先用manager打开的方式，后面有时间再看看。
谢谢大佬。
