### ISSUE TITLE
java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'

### ISSUE THREAD

**Issue by fanshidong1993** [Tencent/Shadow#782]
确实在 插件的build.gradle里应用了apply plugin: 'com.tencent.shadow.plugin'
但是AS Build出来的 插件APK 无法在host.apk 成功加载
能讲解一下 插件的配置吗， 除了 apply plugin: 'com.tencent.shadow.plugin' 还需要其他的吗？
我参考的是test-none-dynamic-host 和 test-plugin-androidx-cases
求大佬指教

**Comment by fanshidong1993** [comment]
plugins {
    id 'com.android.application'
    id 'com.tencent.shadow.plugin'

    id 'kotlin-android'
    id 'androidx.navigation.safeargs.kotlin'

}

**Comment by shifujun** [comment]
代码push上来吧。

**Comment by fanshidong1993** [comment]
我使用github特别费劲，上传不了代码。
就是APK里没有manifest_parser
Gradle JDK 11
 AS 2020.3.1 Patch3 

buildscript {
    repositories {
        if (!System.getenv().containsKey("DISABLE_TENCENT_MAVEN_MIRROR")) {
            maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        } else {
            google()
            jcenter()
        }
    }

    dependencies {
        classpath 'com.tencent.shadow.core:runtime'
        classpath 'com.tencent.shadow.core:activity-container'
        classpath 'com.tencent.shadow.core:gradle-plugin'
        classpath 'org.javassist:javassist:3.28.0-GA'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.tencent.shadow.plugin'
apply plugin: 'kotlin-android'

android {
    compileSdk project.COMPILE_SDK_VERSION

    defaultConfig {
        applicationId "com.hzl.a_test"
        minSdkVersion project.MIN_SDK_VERSION
        targetSdkVersion project.TARGET_SDK_VERSION
        versionCode project.VERSION_CODE
        versionName project.VERSION_NAME

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    // 将插件applicationId设置为和宿主相同
    productFlavors {
        plugin {
            applicationId project.TEST_HOST_APP_APPLICATION_ID
        }
    }
}

dependencies {
    pluginCompileOnly 'com.tencent.shadow.core:runtime'
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

**Comment by fanshidong1993** [comment]
我打开项目根目录，跑出来的 sample-app 等其他 应用 apply plugin: 'com.tencent.shadow.plugin' 的plugin， apk 里也没有 manifest_parser ， 应该是什么地方的配置出问题了。

**Comment by fanshidong1993** [comment]
pluginApk2 {
                        businessName = 'a-test'
                        partKey = 'a-test'
                        buildTask = ':a-test:assemblePluginDebug'
                        apkPath = 'a-test/build/outputs/apk/plugin/debug/a-test-plugin-debug.apk'
                        hostWhiteList = ["androidx.test.espresso",//这个包添加是为了general-cases插件中可以访问测试框架的类
                                         "com.tencent.shadow.test.lib.plugin_use_host_code_lib.interfaces"]//测试插件访问宿主白名单类
                    }

**Comment by fanshidong1993** [comment]
shadow{
    //这一块 配置能不能简单介绍一下
}
大概知道是一个 normal 一个 plugin 2个文件夹 ，只有plugin 的文件夹 dex 会包含 manifest_parser。
但是自己建的模块，没生成 plugin 文件夹

**Comment by shifujun** [comment]
> 我使用github特别费劲，上传不了代码。

如果不能正常使用GitHub，先解决使用GitHub的问题。可以参考这里：https://docs.github.com/ 

我不是不相信有bug，但确实没有代码很难找出问题。建议在demo的基础上做简单改动复现问题，然后把代码分享出来。

**Comment by fanshidong1993** [comment]
读源码已经解决了， 是我自己搞错了
com.tencent.shadow.plugin 提供了2种 Active Build Variant， normal 和 plugin 
我一直在用normal 当 plugin。 
现在正常了。 已经愉快的在使用shadow 改造项目了。 感谢开源，真香。


------ github 是公司网络 就是很难连上，这条评论提交 了 3次才还没成功。再试一次。
