### ISSUE TITLE
pluginmanager.apk 动态更新问题

### ISSUE THREAD

**Issue by Hxh188** [Tencent/Shadow#784]
pluginmanager.apk 改变后，可以在不重启宿主进程的情况下生效吗？目前测试是不行，会报以下错误，需要重启宿主进程才能解决。

android.content.res.Resources$NotFoundException: Resource ID #0x7f010000
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:239)
        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2309)
        at android.content.res.Resources.getLayout(Resources.java:1189)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.tencent.shadow.sample.manager.SamplePluginManager.onStartActivity(SamplePluginManager.java:132)
        at com.tencent.shadow.sample.manager.SamplePluginManager.enter(SamplePluginManager.java:83)
        at com.tencent.shadow.dynamic.host.DynamicPluginManager.enter(DynamicPluginManager.java:53)
        .....

**Comment by Hxh188** [comment]
@shifujun

**Comment by shifujun** [comment]
这个功能是支持的。但是一直没演示也没测试用例。我刚补充了一个基本的测试用例。
https://github.com/shifujun/Shadow/commit/005085d5a53fc0fe4cb8ac69275df324b212c11a

麻烦在此基础上修改看看能不能复现问题。

**Comment by Hxh188** [comment]
有测过，java类是有更新成功成新的，但是就是报Resources$NotFoundException，找不到资源文件。在demo的SamplePluginManager 的 onStartActivity 中 if (callback != null) {
            final View view = LayoutInflater.from(mCurrentContext).inflate(R.layout.activity_load_plugin, null);
            callback.onShowLoadingView(view);
        }报的，

**Comment by shifujun** [comment]
那你看看是不是这个意思：https://github.com/shifujun/Shadow/commit/d8651c3d6ba0b06d15ecc767011926bcc6d36c4f

不是的话，你改一个。

**Comment by Hxh188** [comment]
是的，的确这边测试时没问题，但我这边是新的pluginmanager.apk跟旧的pluginmanager.apk是放在同一个路径覆盖的，这样就会出现资源找不到的问题。你把UpdateManagerImplTestActivity中的DumbUpdater换成以下内容，就会出现资源找不到的问题。目前我git一直提交补上去，麻烦大神从这边复制进去就可以重现

class DumbUpdater implements PluginManagerUpdater {

    final private File dumbManagerApk;
    final private File workedManagerApk;
    private boolean updated = false;

    DumbUpdater(File dumbManagerApk, File workedManagerApk) {
        this.dumbManagerApk = dumbManagerApk;
        this.workedManagerApk = workedManagerApk;
    }


    @Override
    public boolean wasUpdating() {
        return false;
    }

    @Override
    public Future<File> update() {
        try {
            FileUtils.copyInputStreamToFile(new FileInputStream(workedManagerApk), dumbManagerApk);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;

//        updated = true;
//        return new Future<File>() {
//            @Override
//            public boolean cancel(boolean mayInterruptIfRunning) {
//                return false;
//            }
//
//            @Override
//            public boolean isCancelled() {
//                return false;
//            }
//
//            @Override
//            public boolean isDone() {
//                return true;
//            }
//
//            @Override
//            public File get() throws ExecutionException, InterruptedException {
//                return workedManagerApk;
//            }
//
//            @Override
//            public File get(long timeout, TimeUnit unit) throws ExecutionException, InterruptedException, TimeoutException {
//                return workedManagerApk;
//            }
//        };
    }

    @Override
    public File getLatest() {
        return dumbManagerApk;

//        if (!updated) {
//            return dumbManagerApk;
//        } else {
//            return workedManagerApk;
//        }
    }

    @Override
    public Future<Boolean> isAvailable(final File file) {
        return null;
    }

**Comment by Hxh188** [comment]
我这个写法有问题没？

**Comment by Hxh188** [comment]
我这个写法在android 9.0(包含android 9.0)以上会报资源找不到的问题，低于9.0的不会报。你可以在android studio自带的模拟器上测试看看

**Comment by shifujun** [comment]
没有代码不方便测试，晚点再看吧。

**Comment by Hxh188** [comment]
我就直接pull request 到你的784分支了 bff43c0f37d5c6aab9bc75940fe99d1ebf7f6684

**Comment by Hxh188** [comment]
https://github.com/Hxh188/Shadow.git

**Comment by Hxh188** [comment]
还是在784分支， 用Android 10 的模拟器测就可重现

**Comment by shifujun** [comment]
https://github.com/Hxh188/Shadow/blob/bff43c0f37d5c6aab9bc75940fe99d1ebf7f6684/projects/test/dynamic/host/test-dynamic-host/src/main/java/com/tencent/shadow/test/dynamic/host/UpdateManagerImplTestActivity.java#L69-L82

我不太理解为什么会有复用File对象的需求。这里如果File对象不变，文件路径不变，最终ClassLoader和Resource加载文件时是有可能使用缓存的。

因为完全没必要复用相同路径，所以我也不太想花精力搞清它的缓存逻辑。

建议深究这个问题的话，可以脱离Shadow来研究，单纯研究File、DexClassLoader、Resource这3个类型的创建效果就可以了。

对于Shadow，可能确实可以在`ImplLoader`中加入这一情况的检查，及早提示错误。

**Comment by Hxh188** [comment]
目前我app是从后台下载的pluginmanager.apk，存到手机本地的固定的文件路径，然后PluginManager 每次 从这个固定的文件路径取，更新pluginmanager.apk下载路径也是这个固定的文件路径。如果是缓存的问题，那是否说我要每次下载保存的文件路径都要不一样吗？

**Comment by shifujun** [comment]
> 那是否说我要每次下载保存的文件路径都要不一样吗？

是的。
