### ISSUE TITLE
请问怎么设置插件的状态栏的颜色

### ISSUE THREAD

**Issue by SkywardSky** [Tencent/Shadow#785]
无论怎么修改host，sample-base-lib，sample-app的theme，都无法在宿主调插件的页面展示的时候，状态栏的颜色仍然不生效，一直都是黑色的，请问无法修改的么，还是我的修改方法错误了？

**Comment by SkywardSky** [comment]
看sample是通过java代码设置的，是只能在代码设置是么，不可以在清单文件配置么

**Comment by shifujun** [comment]
这个不通过Manifest设置，是因为Manifest还需要解析，最终还是拿到值通过java代码设置，所以显然性能差。

不过最近增加了编译期解析Manifest的manifest-parser模块（ 8a99c4fb92ce8963c600e55ac92901cf9b15eea0 ），所以其实现在是有能力做编译期解析manifest生成所需的java代码的。
