### ISSUE TITLE
构建插件      build/generated/source/目录下面          pluginManifest          没生成是出什么问题了

### ISSUE THREAD

**Issue by yatoooon** [Tencent/Shadow#787]

**Comment by shifujun** [comment]
可以观察一下Gradle是否有执行对应任务：`generate${variantName.capitalize()}PluginManifest`。

另外，有可能是受先前构建缓存的影响，可以禁用Gradle build cache看看。

**Comment by yatoooon** [comment]
确实没有执行 generate${variantName.capitalize()}PluginManifest   
但是我已经配置了  apply plugin: 'com.tencent.shadow.plugin'
并且已经构建成功插件了  

这是哪里出了问题

**Comment by shifujun** [comment]
那再确认应用的插件代码版本吧。目前应该只有master分支代码有这个特性。如果你是自己编译的，检查下是否包含那个提交。

**Comment by yatoooon** [comment]
是最新的master分支编译的shadow版本

**Comment by shifujun** [comment]
那你可以手工执行那个generate任务试试。如果手工执行效果正常。我还是认为是缓存的问题。建议clean构建目录，禁用Gradle缓存。

**Comment by yatoooon** [comment]
手工执行generateDebugCOnfig     也可以build successful  但是看着还是没有这个类

**Comment by yatoooon** [comment]
clean 项目   禁用缓存   这些都试过了

**Comment by yatoooon** [comment]
https://github.com/yatoooon/MVVMArms.git         能否帮我看看       在feature_plugin分支

**Comment by yatoooon** [comment]
执行  ./gradlew packageDebugPlugin       打出的基础插件包是有的    但是其他插件包就没有        我怀疑是不是和buildSrc有关系   因为其他插件都是从buildSrc打出来的

**Comment by shifujun** [comment]
好的，我晚点看下。有代码就好交流了。

**Comment by yatoooon** [comment]
好的  麻烦了

**Comment by yatoooon** [comment]
我看了一下   我这边就没有生成 generatePluginDebugPluginManifest 这个task         不知道为什么

**Comment by shifujun** [comment]
应该是
https://github.com/yatoooon/MVVMArms/blob/32bfb590b02d91b3107edc41447f4933e76ecf02/buildSrc/src/main/java/com/arms/plugin/CommonAndroid.kt#L38
这里调用的`flavorDimensions`产生的影响。这个方法内部隐含清空了原本的flavorDimensions。这样ShadowPlugin在后面试图判断哪个variant是插件的时就找不到自己先添加的了：

https://github.com/Tencent/Shadow/blob/3beb9e6547bcddc214fad512f6af0a70a5fe7df3/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt#L104-L107

**Comment by yatoooon** [comment]
感谢大佬     现在可以生成了PluginManifet了  但是 打的插件包classes.dex里面还是没有PluginManifest这个类

**Comment by shifujun** [comment]
没看到你修改后的代码。
如果有PluginManifest.java了，就检查下srcDir是不是包含那个目录了。

https://github.com/Tencent/Shadow/blob/3beb9e6547bcddc214fad512f6af0a70a5fe7df3/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt#L134-L135

**Comment by yatoooon** [comment]
我提交了一些修改    能帮我看看为什么没有PluginManifest这个类嘛   我已经晕了   gradle plugin用的不是很熟练

**Comment by shifujun** [comment]
问题在于
https://github.com/Tencent/Shadow/blob/3beb9e6547bcddc214fad512f6af0a70a5fe7df3/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/ShadowPlugin.kt#L135
这行代码添加完srcDir之后的其他代码把这个目录给丢掉了。

简单实验了一下，去掉这几行配置就可以恢复正常。
https://github.com/yatoooon/MVVMArms/blob/32bfb590b02d91b3107edc41447f4933e76ecf02/buildSrc/src/main/java/com/arms/plugin/CommonPlugins.kt#L25-L30

说明这几行配置的代码，比如说`android-aspectjx`插件可能存在bug。

建议可以手工再配置`build/generated/source/pluginManifest/pluginDebug`目录到srcDir中。

**Comment by yatoooon** [comment]
十分感谢
