### ISSUE TITLE
第三方activity重复依赖

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#789]

**Comment by Daimhim** [comment]
如题，集成第三方的一些SDK，里面包含了一些activity 在多个插件都有使用时 会提示重复添加。请问一下这个如何避免

**Comment by shifujun** [comment]
不能重复添加的原因是因为这些插件Activity被要求使用宿主的packageName，所以当类名重复时，相当于它们的ComponentName完全相同，这样就无法区分它们了。就像正常的安装的Apk中也不能存在和自身或系统中已有的Activity重名的一样。

建议把这种带有Activity的第三方SDK单独做成一个插件，供其他插件dependsOn依赖。

如果重复打包，也可以参考官方的manifest合并控制语法修改不同插件中的同名Activity：https://developer.android.com/studio/build/manage-manifests

**Comment by fanshidong1993** [comment]
java.lang.IllegalStateException: 重复添加Component：ComponentInfo{com.hzl.newzerohelper/androidx.room.MultiInstanceInvalidationService}

a插件使用了jetpack中的room
b插件也使用了jetpack中的room
先后加载会抛这个异常。
这个service 我没有注册过
数据库也要单独做一个插件吗？所有插件都依赖数据库插件？

**Comment by shifujun** [comment]
> java.lang.IllegalStateException: 重复添加Component：ComponentInfo{com.hzl.newzerohelper/androidx.room.MultiInstanceInvalidationService}
> 
> a插件使用了jetpack中的room b插件也使用了jetpack中的room 先后加载会抛这个异常。 这个service 我没有注册过 数据库也要单独做一个插件吗？所有插件都依赖数据库插件？

是的。这个SDK被打包进了两个插件。而每个插件都是宿主代码的一部分。所以它们重复了。

**Comment by fanshidong1993** [comment]
我目前是把抛异常的代码改成了打印异常
我看了addPluginApkInfo 这个方法里是 Map.put,  如果能保证名称一样的类，内容也是一样的，看起来就不会出问题，因为哪个都一样。
我这么理解对吗 @shifujun

**Comment by shifujun** [comment]
不对。你可能不太理解不同ClassLoader里的类在运行时是不同的类。

**Comment by Daimhim** [comment]
@shifujun 我把ComponentManager改造了一下，把四大组件的添加过程分解成单个方法，让其子类可以实现。这样就可以做到按需求过滤，插件不加载这些第三方activity，统一使用宿主的
![image](https://user-images.githubusercontent.com/20254978/152966489-5c99a245-df9d-473b-85c1-cddd91d10f76.png)
![image](https://user-images.githubusercontent.com/20254978/152966682-54e12ddd-e971-4542-b057-1f44c33c3f0a.png)
如图，我把指定的四大组件全包名提前注册到白名单，然后在插件加载过程中直接跳过。当然你可以可以定制自己的过滤规则。

大部分项目估计都用了不少第三方，不仅使用了其中的activity，肯定还有少量的资源文件，所以必须把依赖打包到插件内。我们无法把activity和资源剥离开来，只能绕过activity检测。上述方法提供了一种思路，希望对遇到相同问题的人有帮助

**Comment by Florizt** [comment]
> @shifujun 我把ComponentManager改造了一下，把四大组件的添加过程分解成单个方法，让其子类可以实现。这样就可以做到按需求过滤，插件不加载这些第三方activity，统一使用宿主的 ![image](https://user-images.githubusercontent.com/20254978/152966489-5c99a245-df9d-473b-85c1-cddd91d10f76.png) ![image](https://user-images.githubusercontent.com/20254978/152966682-54e12ddd-e971-4542-b057-1f44c33c3f0a.png) 如图，我把指定的四大组件全包名提前注册到白名单，然后在插件加载过程中直接跳过。当然你可以可以定制自己的过滤规则。
> 
> 大部分项目估计都用了不少第三方，不仅使用了其中的activity，肯定还有少量的资源文件，所以必须把依赖打包到插件内。我们无法把activity和资源剥离开来，只能绕过activity检测。上述方法提供了一种思路，希望对遇到相同问题的人有帮助

@Daimhim 能分享下代码吗
