### ISSUE TITLE
白名单规则的BUG

### ISSUE THREAD

**Issue by fanshidong1993** [Tencent/Shadow#790]
com.tencent.shadow.core.loader.classloaders.PluginClassLoader
PackageNameTrie
isMatch(packageName) （第172行）

这里的 packageName 是去掉了最后的类名的
如果规则 设置， a.b.c.*
想要加载类名 a.b.c.d 是没办法加载到宿主的类的
循环只有3次， lastindex == index 的时候 node 其实还是 b， 他的subnode 是c 而不是*

 ```
for ((index, name) in split.withIndex()) {
            // 只要下级包名规则中有**，就完成了匹配
            val twoStars = node.subNodes["**"]
            if (twoStars != null) {
                return true
            }

            // 剩最后一级包名时，如果规则是*则完成比配
            if (index == lastIndex) {
                val oneStar = node.subNodes["*"]
                if (oneStar != null) {
                    return true
                }
            }

            // 找不到下级包名时即匹配失败
            val subNode = node.subNodes[name]
            if (subNode == null) {
                return false
            } else {
                node = subNode
            }
        }
```

**Comment by shifujun** [comment]
如果类名是`a.b.c.d`，建议举例写成`a.b.c.D`。因为白名单的逻辑只关心包名，这里的包名是`a.b.c`，所以`a.b.c`、`a.b.*`、`a.**`都可以匹配`a.b.c`。

测试用例见：
https://github.com/Tencent/Shadow/blob/41c91c174f87f402f14c0a0ebe0d0ea46e75fee6/projects/sdk/core/loader/src/test/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoaderTest.kt#L33-L38

如此设计的原因等类似的讨论可以参考#624
