### ISSUE TITLE
第三方service 的使用问题

### ISSUE THREAD

**Issue by fanshidong1993** [Tencent/Shadow#791]
java.lang.ClassCastException: org.eclipse.paho.android.service.MqttService cannot be cast to com.tencent.shadow.core.runtime.ShadowService

我想在插件中使用第三方提供的service ， 应该怎么操作。在例子中似乎没有找到相应的内容。

还是说由宿主提供第三方服务，插件通过接口或者其他方式间接使用。

**Comment by shifujun** [comment]
出现`MqttService`cannot be cast to `ShadowService`这种错误，大概率是因为`MqttService`这个类是这个SDK自行动态加载了apk，所以它没有经过Shadow Transform处理：
https://github.com/Tencent/Shadow/blob/9bb0188a5ab1067ac57ef8268fbaa493563462da/projects/sdk/core/transform/src/main/kotlin/com/tencent/shadow/core/transform/specific/ServiceTransform.kt#L21-L26

对于这种自行动态加载apk的SDK，Shadow从原理上无法兼容。因为Shadow要在编译期帮助插件中所有class进行字节码修改。

考虑到这种动态加载的SDK本身跟Shadow的特性差不多，也不占用宿主体积也能动态更新，所以建议直接将这种SDK放到宿主中。Shadow插件可以正常和宿主之间通过Service的binder通信。
