### ISSUE TITLE
优化编译流程&简化工程结构&简化接口

### ISSUE THREAD

**Issue by goodyuanwei** [Tencent/Shadow#798]
也是刚刚完整的阅读理解了Shadow工程，这着实是一件非常苦逼的事情，原因有三：编译流程繁琐，工程结构繁琐，过度的接口设计。理解这个开源项目花费的精力胜过了ffmpeg。

**Comment by shifujun** [comment]
欢迎提出具体可行的改进意见。比如编译流程繁琐，可以指出哪些步骤其实是没有必要的，为什么，或者直接修改代码简化这个流程。其余2点也是如此。我对这些设计并没有100%的信心它们是完美的。但如果没有可操作的建议，我也确实无从改进。

**Comment by goodyuanwei** [comment]
1. 把插件 插件加载器 插件管理器全部动态起来，为了支持全动态，该工程引入过多的接口设计导致可读性不强，从运维层面考虑全动态多余了费力不讨好。 2. 可能是我深度不够，不清楚PPS服务的必要性在哪里，PPS的数据交互过于繁琐了，是否可以优化？ 3. sdk/coding的若干子工程能否简化成一个插件工程？

**Comment by shifujun** [comment]
> 被部门要求彻底搞清楚这个技术栈，源代码看了4天，我真的很无语，这么糟糕的工程架构你们还真敢开源，勇气可嘉！

我理解你的压力。但是请注意这是一个开源分享技术的项目，并不是收费服务。如果4天可以完全理解Shadow的方方面面，欢迎向腾讯投简历，我可以为你推荐T11级进行面试。
