### ISSUE TITLE
更新最新版本2.2.1后，启动插件打不开界面

### ISSUE THREAD

**Issue by BruceLiuTao** [Tencent/Shadow#803]
如题，更新了最新版本后，启动插件，回调成功了，但界面不展示

**Comment by shifujun** [comment]
没有代码，复现不了，谁也帮不上你什么吧？

**Comment by BruceLiuTao** [comment]
主要是我没改任何其他东西，就升级了一个版本就启动不了了，没升级就能启动，不知道问题出在哪个地方，也不知道截取哪个代码

**Comment by BruceLiuTao** [comment]
从2.1.0升级到了2.2.1

**Comment by shifujun** [comment]
如果你的代码是闭源的，我只能建议你对比Shadow前后版本的代码差异，然后debug那些改动的代码。找出问题后在shadow的sample上复现出来。
