### ISSUE TITLE
Cannot resolve symbol Tuple2 

### ISSUE THREAD

**Issue by fanshidong1993** [Tencent/Shadow#805]
JDK 11
apply plugin: 'com.tencent.shadow.plugin' 添加了的， Cannot resolve symbol Tuple2 

在全动态 打包 plugin 的时候， 例子里有只有 .zip 的方式
其中
```
oDexPluginLoaderOrRunTime(uuid, InstalledType.TYPE_PLUGIN_RUNTIME,
                            pluginConfig.runTime.file);

```
pluginConfig.runTime.file 是不是就是 runtime.apk 的路径
如果我不打包zip， 直接用`oDexPluginLoaderOrRunTime`去加载 runtime 和loader 的apk
后面plugin的加载 自行初始化 `PluginFileInfo`
然后执行 `for (Map.Entry<String, PluginConfig.PluginFileInfo> plugin : pluginConfig.plugins.entrySet())`下的逻辑
是否也能正常使用

runtime 和 loader 可以根据不同的进程编译多个不同版本吗？。

BTW：
```
name = "GitHubPackages"
            url "https://maven.pkg.github.com/tencent/shadow"
```
这个库里 Shadow的最新版本号是多。2.2.1 的话 少个方法
`public final void onInstallCompleted(PluginConfig pluginConfig, Map<String, String> soDirMap)`

只有
`public final void onInstallCompleted(PluginConfig pluginConfig)`

**Comment by fanshidong1993** [comment]
不是shadow 的问题

**Comment by fanshidong1993** [comment]
大牛知不知道如何升级项目的groovy  同一个项目往同事的电脑上跑就能正常识别。 我搜索软件查了半天也没查出来。

**Comment by shifujun** [comment]
这个问题还是没太看明白。Groovy版本是Gradle自己控制的，所以也是项目代码定义的，不用自己改。Shadow构建对外部环境依赖只依赖JDK环境。
