### ISSUE TITLE
白名单可以指定类，而不是整个包吗？ 

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#807]
如题

**Comment by shifujun** [comment]
现有设计背景可以参考：
https://github.com/Tencent/Shadow/issues/624#issuecomment-926502347

自定义逻辑代码在这里：
https://github.com/Tencent/Shadow/blob/89205f6d7c59982612736cb5bf0dc5485e0d856d/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoader.kt#L88-L90

**Comment by Daimhim** [comment]
不能说没有帮助  他们需求比我这要深多了。

**Comment by Daimhim** [comment]
现有的api可以支持 白名单匹配到类吗？
在使用DataBinding的过程中，宿主与插件间都共有DataBinding的一些核心变量，过滤时只能按照包名过滤。导致宿主调用插件的fragment时，插件fragment加载布局时，DataBinding找布局找到宿主里面去了

**Comment by shifujun** [comment]
> 现有的api可以支持 白名单匹配到类吗？

不支持。

对于在插件和宿主间复用SDK的场景，由于各种SDK对系统API依赖各不相同，所以还没有统一的方案的方案可以解决。

>  导致宿主调用插件的fragment时

这种场景也不是现有代码支持的功能。现有代码主要支持插件和宿主相互独立工作，以各自为独立App的方式跨进程交互，以普通Java类ClassLoader依赖的形式交互Java类。普通Java类排除的就是Shadow Transform涉及的受系统限制API的类，如Activity。

**Comment by Daimhim** [comment]
现在就是吧fragment改造成一个普通类，但是里面的DataBinding还是冲突

**Comment by Daimhim** [comment]
修改前
![image](https://user-images.githubusercontent.com/20254978/154426599-158b4623-8645-46be-b0bd-9ea771f50cc3.png)
修改后
![image](https://user-images.githubusercontent.com/20254978/154426943-f51d912c-f1fd-47a4-9148-0712220e749b.png)

shadow中可以改造成这样吗？ 就可以及支持类名又支持过滤包名

**Comment by shifujun** [comment]
如果是说通用的优化，还是参考https://github.com/Tencent/Shadow/issues/624#issuecomment-926502347
 不适合添加。

如果是自己用，开源的随便改。

**Comment by Daimhim** [comment]
他这个改动量太大 规则复杂 学习成本高，虽然这个改动量小 但功能都能实现
