### ISSUE TITLE
部分手机手机会出现：com.tencent.shadow.dynamic.host.FailedException

### ISSUE THREAD

**Issue by SkywardSky** [Tencent/Shadow#820]
请问一般出现这种问题是什么情况导致的，bugly记录的堆栈信息如下：
java.lang.RuntimeException:com.tencent.shadow.dynamic.host.FailedException
com.kblife.plugin.manager.SamplePluginManager$1.run(SamplePluginManager.java:147)
......
Caused by:
com.tencent.shadow.dynamic.host.FailedException:
com.tencent.shadow.dynamic.host.PpsController.loadPluginLoader(PpsController.java:63)
com.tencent.shadow.dynamic.manager.PluginManagerThatUseDynamicLoader.loadPluginLoader(PluginManagerThatUseDynamicLoader.java:107)
com.kblife.plugin.manager.FastPluginManager.loadPluginLoaderAndRuntime(FastPluginManager.java:131)
com.kblife.plugin.manager.FastPluginManager.loadPlugin(FastPluginManager.java:135)
com.kblife.plugin.manager.SamplePluginManager$1.run(SamplePluginManager.java:132)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
java.lang.Thread.run(Thread.java:764)

看源码：com.tencent.shadow.dynamic.host.PpsController.loadPluginLoader(PpsController.java:63) 感觉像是pps进程没启动，或者ibinder绑定失败的

**Comment by shifujun** [comment]
这个FailedException是Binder通信后传回来的跨进程异常，所以不能完整反映对面的调用栈。所以还是应该看看插件进程的错误。

对于loadPluginLoader来说，遇到异常时插件进程抛出的肯定也是runtime exception。

这种跨进程调用有一定的异步性，如果上报量少的话，也可能只是因为用户很快就杀掉插件进程了，导致主进程调用失败。

**Comment by SkywardSky** [comment]
主要是很奇怪，我搞了台和用户同型号同系统的手机，是可以正常运行的，但是用户的却不行，这就很头疼了

**Comment by admin313cn** [comment]
我也遇到这个问题了，这个问题解决了吗
