### ISSUE TITLE
请问下，一个Activity中加载多个Apk中的View。这个Activity是不是也需要运行在插件线程，并且多个apk也都运行在同样的插件线程

### ISSUE THREAD

**Issue by donway** [Tencent/Shadow#821]

**Comment by Daimhim** [comment]
先说说 这个View是怎么创建的把

**Comment by shifujun** [comment]
“插件线程”，”apk运行在线程“，这都是很难理解的说法。建议还是通过代码交流。https://github.com/Tencent/Shadow/blob/50678f5228660b0a7a4b91576605721a89c9ba7c/CONTRIBUTING.md#issue

**Comment by donway** [comment]
> “插件线程”，”apk运行在线程“，这都是很难理解的说法。建议还是通过代码交流。https://github.com/Tencent/Shadow/blob/50678f5228660b0a7a4b91576605721a89c9ba7c/CONTRIBUTING.md#issue

宿主进程一般是主进程，当前进程里有个Activity，能去加载运行在其他进程中的apk（也就是插件）中的view吗？

**Comment by zhuqichao** [comment]
> > “插件线程”，”apk运行在线程“，这都是很难理解的说法。建议还是通过代码交流。https://github.com/Tencent/Shadow/blob/50678f5228660b0a7a4b91576605721a89c9ba7c/CONTRIBUTING.md#issue
> 
> 宿主进程一般是主进程，当前进程里有个Activity，能去加载运行在其他进程中的apk（也就是插件）中的view吗？

官方demo中是有类似示例代码的，但是实现方式比较奇怪，是通过全局变量持有宿主的布局容器，然后插件去使用这个布局容器将view添加到宿主中的。
如果宿主和插件运行在同一进程，有比较简单的方式实现，我已验证可行

**Comment by donway** [comment]
> ，

如果是在不同的进程，我已验证是不可行的。可能是要用RemoteView吧
