### ISSUE TITLE
插件获取不到插件manifest声明的权限列表

### ISSUE THREAD

**Issue by Tomgogo** [Tencent/Shadow#824]
插件跟宿主运行在主进程，在插件manifest文件声明了一些权限（有permission和uses-permission），但在插件调用如下getPermissions获取的权限列表为空,宿主和插件包名一样，包名传的没问题。请问插件是不支持获取权限列表吗？
PluginApp extends Application() {
         override void onCreate() {
                super.onCreate();
                PluginContext.setAppContext(this);
           }
}
public PermissionInfo[] getPermissions(String packageName){
                return PluginContext.getAppContext().getPackageManager().getPackageInfo(
                         packageName, 4096).permissions;//requestedPermissions获取也为null
}

**Comment by BBNO** [comment]
请问这个问题怎么解决？ @shifujun

**Comment by shifujun** [comment]
你们可能是刚接触Android插件框架这个领域。目前还没有技术能使插件Manifest中注册的权限生效。

Android系统不允许动态更新Manifest中的内容。所以所有的插件框架都是在解耦代码逻辑和Manifest的关系，使插件在固定的Manifest下尽可能动态更新其他的部分。

**Comment by BBNO** [comment]
但是我在宿主中Manifest注册了所需要的权限，还是会报权限null的问题。 @shifujun

**Comment by BBNO** [comment]
报错日志：
 java.lang.IllegalStateException: Runtime.hostContext.pack…ONS).requestedPermissions must not be null

**Comment by shifujun** [comment]
getPackageInfo获取宿主的权限，可以先试一下这样修改：https://github.com/shifujun/Shadow/commit/ca32b3efd5c3d84a805a663db7e19ccf048c0582

我还没有测试。

**Comment by Tomgogo** [comment]
> 



> 



> 报错日志： java.lang.IllegalStateException: Runtime.hostContext.pack…ONS).requestedPermissions must not be null



> getPackageInfo获取宿主的权限，可以先试一下这样修改：[shifujun@ca32b3e](https://github.com/shifujun/Shadow/commit/ca32b3efd5c3d84a805a663db7e19ccf048c0582)
> 
> 我还没有测试。

其实就是要这样的实现，上面没有表述太清楚，插件中的权限宿主中也会声明。
