### ISSUE TITLE
请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'

### ISSUE THREAD

**Issue by BBNO** [Tencent/Shadow#830]
请问为什么会出现这样的报错：
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'

**Comment by BBNO** [comment]
@shifujun 大佬，帮忙看一下这个问题

**Comment by zeronewhepler** [comment]
https://github.com/Tencent/Shadow/issues/782

**Comment by BBNO** [comment]
你好，我插件是通过这个命令打包的：gradlew packageDebugPlugin，还是会报这个错，跟你发的这个不一样。 @zeronewhepler

**Comment by zeronewhepler** [comment]
看一下编译出来的apk 名字里带没带 plugin， 带plugin 的apk 才能当 插件用。 否则就是正常的apk。
要是带了 plugin 还是报错， fork 一下 push 你的代码

**Comment by BBNO** [comment]
@zeronewhepler 代码已push上去，能帮忙看一下吗？
[https://github.com/BBNO/Shadow/tree/master/projects/mydemo](url)

**Comment by BBNO** [comment]
https://github.com/BBNO/Shadow/tree/master/projects/mydemo
