### ISSUE TITLE
启动插件中的activity，报 java.lang.ClassCastException

### ISSUE THREAD

**Issue by zzx752904457** [Tencent/Shadow#833]
Unable to start activity ComponentInfo{com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: java.lang.ClassCastException: androidx.appcompat.widget.ActionBarOverlayLayout cannot be cast to androidx.appcompat.widget.DecorContentParent
宿主和插件的包名是一致的，而且如果把插件中的activity继承于activity也不会报错，如果继承于AppCompatActivity，启动就会报这个错误

**Comment by shifujun** [comment]
单纯继承AppCompatActivity是不会有问题的。应该还是你有什么特别的写法没有说，所以我们常说交流问题时应该把你的代码push上来看看。

这是继承AppCompatActivity的测试用例，你可以在这基础上修改复现问题。

https://github.com/Tencent/Shadow/blob/10ce0228d9a0edde3d21f11fa3207eacae139450/projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_androidx/AppCompatActivityTest.java#L33

https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/test/plugin/androidx-cases/test-plugin-androidx-cases/src/main/java/com/tencent/shadow/test/plugin/androidx_cases/lib/AppCompatTestActivity.java#L10

**Comment by zzx752904457** [comment]
class TestActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.test_activity)
    }
}

**Comment by zzx752904457** [comment]
class TestActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.test_activity)
    }
}
就只是这么一个很简单的测试activity

> 单纯继承AppCompatActivity是不会有问题的。应该还是你有什么特别的写法没有说，所以我们常说交流问题时应该把你的代码push上来看看。
> 
> 这是继承AppCompatActivity的测试用例，你可以在这基础上修改复现问题。
> 
> https://github.com/Tencent/Shadow/blob/10ce0228d9a0edde3d21f11fa3207eacae139450/projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_androidx/AppCompatActivityTest.java#L33
> 
> https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/test/plugin/androidx-cases/test-plugin-androidx-cases/src/main/java/com/tencent/shadow/test/plugin/androidx_cases/lib/AppCompatTestActivity.java#L10

**Comment by zzx752904457** [comment]
> class TestActivity : AppCompatActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState) setContentView(R.layout.test_activity) } }

就是一个简单的测试activity

**Comment by zzx752904457** [comment]
> 单纯继承AppCompatActivity是不会有问题的。应该还是你有什么特别的写法没有说，所以我们常说交流问题时应该把你的代码push上来看看。
> 
> 这是继承AppCompatActivity的测试用例，你可以在这基础上修改复现问题。
> 
> https://github.com/Tencent/Shadow/blob/10ce0228d9a0edde3d21f11fa3207eacae139450/projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_androidx/AppCompatActivityTest.java#L33
> 
> https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/test/plugin/androidx-cases/test-plugin-androidx-cases/src/main/java/com/tencent/shadow/test/plugin/androidx_cases/lib/AppCompatTestActivity.java#L10

找到原因了，是一个三方库在内部注册了一个ActivityLifecycleCallbacks，在activity的生命周期onCreate回调中更改了Factory2
找到原因了，是

**Comment by zhuqichao** [comment]
我也遇到这个问题了，也是单纯继承AppCompatActivity，不过是在Android4.4设备上报错的

**Comment by zhuqichao** [comment]
> > 单纯继承AppCompatActivity是不会有问题的。应该还是你有什么特别的写法没有说，所以我们常说交流问题时应该把你的代码push上来看看。
> > 这是继承AppCompatActivity的测试用例，你可以在这基础上修改复现问题。
> > https://github.com/Tencent/Shadow/blob/10ce0228d9a0edde3d21f11fa3207eacae139450/projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_androidx/AppCompatActivityTest.java#L33
> > 
> > https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/test/plugin/androidx-cases/test-plugin-androidx-cases/src/main/java/com/tencent/shadow/test/plugin/androidx_cases/lib/AppCompatTestActivity.java#L10
> 
> 找到原因了，是一个三方库在内部注册了一个ActivityLifecycleCallbacks，在activity的生命周期onCreate回调中更改了ShadowLayoutInflater的Factory2

大佬，这个问题怎么解决的呢
