### ISSUE TITLE
宿主获取插件service问题

### ISSUE THREAD

**Issue by onenoobinit** [Tencent/Shadow#834]
您好，我在宿主里面开启了插件的两个service，都是通过bindservice的方式开启的，然后在宿主遍历所有运行的service，打印后发现插件的service只有一个是插件的ppsservice，老师请问有什么办法可以获取具体开启的service？
<img width="418" alt="截屏2022-02-28 下午2 51 14的副本" src="https://user-images.githubusercontent.com/26533048/155937832-152c0681-8dcf-4774-815b-1375b593f59a.png">
<img width="1277" alt="截屏2022-02-28 下午2 51 57" src="https://user-images.githubusercontent.com/26533048/155937840-6b50441a-4c60-4c83-9f02-2de114e4e85c.png">
<img width="719" alt="截屏2022-02-28 下午2 52 50" src="https://user-images.githubusercontent.com/26533048/155937849-286b5515-27bc-4771-9f3a-4815a6b53143.png">

**Comment by shifujun** [comment]
对于系统来说确实只有PPS这个Service。插件Service都只有一个binder是和正常Service一样的。

所以有需要的话，你可能得自己写一个管理器持有这些插件Service的binder，从而知道哪些插件Service启动了。
