### ISSUE TITLE
RuntimeException: Unable to instantiate activity ComponentInfo{com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity}

### ISSUE THREAD

**Issue by BBNO** [Tencent/Shadow#836]
启动插件的时候出现报错：
  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.my.demo/com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity" on path: DexPathList[[zip file "/data/app/com.my.demo-74BGiwKQsy_noV5Tc-GkdA==/base.apk"],nativeLibraryDirectories=[/data/app/com.my.demo-74BGiwKQsy_noV5Tc-GkdA==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64]]

**Comment by qczgwxg** [comment]
大佬解决了吗？

**Comment by qczgwxg** [comment]
我也遇到这个问题了

**Comment by wh963572516** [comment]
我也遇到了，大佬解決了嘛？
