### ISSUE TITLE
Shadow怎么实现插件内多个activity的跳转？

### ISSUE THREAD

**Issue by jasmineeeeeeee** [Tencent/Shadow#837]
我理解插件内startActivity使用的context等信息应该属于插件，是一个虚假的信息，那么怎么启动插件内其他的页面呢

**Comment by shifujun** [comment]
你是调试过sample有写了什么startActivity的代码不好使吗？否则为什么这么问呢？

是指这样的代码吗？
https://github.com/Tencent/Shadow/blob/7d99d7686ae78dbc584d2f8b95e5a8f2db1a0010/projects/sample/source/sample-plugin/sample-base-lib/src/main/java/com/tencent/shadow/sample/plugin/app/lib/gallery/splash/SplashActivity.java#L46

如果是这种场景，没什么特别的，正常start就是了。

如果还有问题，建议把你的代码push上来看看。
