### ISSUE TITLE
Unity下导出的android项目，使用脚本生成plugin.zip时，出现BuildIl2CppTask异常，请问如何解决吗？

### ISSUE THREAD

**Issue by Stu520** [Tencent/Shadow#839]
目前在构建本地的测试时，需要调用脚本generateDebugAssets把插件的runtime,loader,config配置文件及其插件本身打包生成zip到assets目录下，普通自建的插件是能正常打包到且输出到assets目录下，但是从Unity导出的android项目作为插件引入到我们主项目（宿主），在执行generateDebugAssets脚本时，提示**BuildIl2CppTask**异常。

![exception](https://user-images.githubusercontent.com/14923798/156864150-fdf5a1b7-9448-4037-8dde-01ef7dd1bef2.png)

补充：从Unity导出的android项目在自身构建到运行到android手机上，是正常。但是接入shadow后，需提前准备这个zip包时，执行**BuildIl2CppTask任务**出错。

**Comment by shifujun** [comment]
Shadow无法支持Unity这种so库中引用Activity类型的第三方库。见#628
