### ISSUE TITLE
Unity2021  “failed to load libmain.so”

### ISSUE THREAD

**Issue by alton-ye** [Tencent/Shadow#841]
![image](https://user-images.githubusercontent.com/10337289/157364437-096fdbb3-ceab-4a5a-8731-cbfb73e94a04.png)

编译成独立apk安装手机上正常运行，用shadow插件化出来的apk包，用plug-manager加载运行就报上面图片的错误信息，如果不是unity的项目，则插件包可正常启动

已在所需要地方增加:

 ndk {
        abiFilters 'armeabi-v7a', 'arm64-v8a'
    }

< string name="game_view_content_description" >Game view</ string>

**Comment by shifujun** [comment]
我估计是因为你的宿主里没有so，或者so和插件里的so ABI不一样造成的。

你可以debug一下这段代码：
https://github.com/Tencent/Shadow/blob/f777caea7ac238cdb2e644f14bf64e04dcb548b8/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L383

**Comment by alton-ye** [comment]
请问目前框架是不是还不支持unity导出项目做为插件化，我看到之前的问题，链接：
https://github.com/Tencent/Shadow/issues/628

**Comment by shifujun** [comment]
> 请问目前框架是不是还不支持unity导出项目做为插件化，我看到之前的问题，链接： #628

按照Shadow的原理，需要修改业务代码中受限制的API类型，如把Activity类型替换成ShadowActivity，目前由于没有so的编辑手段，像Unity这种在so中使用Activity等受限制类型的代码是无法支持的。
