### ISSUE TITLE
宿主的SharedPreferences怎么和插件中的SharedPreferences数据互通

### ISSUE THREAD

**Issue by zzx752904457** [Tencent/Shadow#843]
因为context对象不一样，所以宿主中保存的sp数据，插件中不能直接读取；插件中保存的sp数据，宿主中页不能直接读取

**Comment by shifujun** [comment]
把插件的`businessName`设置为空字符串应该就可以了。
https://github.com/Tencent/Shadow/blob/d0d0b927eaf07064ed3cd10920d6f3e4d706639b/projects/test/plugin/general-cases/test-plugin-general-cases/build.gradle#L88

它会影响这些代码：
https://github.com/Tencent/Shadow/blob/50678f5228660b0a7a4b91576605721a89c9ba7c/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java#L84-L89

https://github.com/Tencent/Shadow/blob/50678f5228660b0a7a4b91576605721a89c9ba7c/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java#L240-L246

https://github.com/Tencent/Shadow/blob/9bb0188a5ab1067ac57ef8268fbaa493563462da/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/SubDirContextThemeWrapper.java#L249-L255

**Comment by zzx752904457** [comment]
好的，万分感谢

> 把插件的`businessName`设置为空字符串应该就可以了。
> 
> https://github.com/Tencent/Shadow/blob/d0d0b927eaf07064ed3cd10920d6f3e4d706639b/projects/test/plugin/general-cases/test-plugin-general-cases/build.gradle#L88
> 
> 它会影响这些代码：
> 
> https://github.com/Tencent/Shadow/blob/50678f5228660b0a7a4b91576605721a89c9ba7c/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java#L84-L89
> 
> https://github.com/Tencent/Shadow/blob/50678f5228660b0a7a4b91576605721a89c9ba7c/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java#L240-L246
> 
> https://github.com/Tencent/Shadow/blob/9bb0188a5ab1067ac57ef8268fbaa493563462da/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/SubDirContextThemeWrapper.java#L249-L255

OK，万分感谢
