### ISSUE TITLE
关于 Java8 和 Java11 兼容性的一点疑问

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#844]
parser/src/main/kotlin/com/tencent/shadow/core/manifest_parser/AndroidManifestReader.kt: (31, 65): Unresolved reference: newDefaultInstance
报错之后搜索Issue, 发现 #770  和 #771  已经解决了该问题， 但是有点疑问想向大佬问下：
1. shadow目前是只支持 Java11 ,不支持 Java8 了么？
我尝试修改代码为 val documentBuilderFactory = DocumentBuilderFactory.newDefaultInstance(）发现还是编译不过去。是因为 AGP 和 Gradle 版本是7.+ 的原因么 ？ 
3. Shadow编译用java11编译， 项目工程里用java8是否可行？ 因为目前项目中用的是java8， 担心升级到java11是否会有什么兼容性的坑在线上暴露出来

**Comment by shifujun** [comment]
这个问题确实有点复杂，这里首先要先清楚Shadow的代码运行在多个不同的环境。

`coding`中的代码都是运行在Shadow自己这个工程中`core`和`dynamic`两个子构建的构建期，
这里的代码运行环境是Shadow这个项目自己的Gradle环境。

`core.gradle-plugin`以及它依赖的`core.manifest-parser`、`core.transform`、`core.transform-kit`
几个模块是运行在接入项目的构建期，运行环境是接入项目的Gradle环境。

其余模块基本运行在Android系统上了。

所以这里应该是有3个环境。3个环境的JVM版本可能都不一样。

像你遇到的这个manifest_parser的问题应该只是Shadow自己的编译期需要JDK11。编译结果应该是受这里控制的：
https://github.com/Tencent/Shadow/blob/b0406307333c7f8646df9a25fd7d63865b7920a2/projects/sdk/core/manifest-parser/build.gradle#L12-L17

其余在Android系统上运行的代码的模块应该都统一应用了：`apply plugin: 'com.tencent.shadow.internal.common-jar-settings'`

这个插件内部定义了统一的：
https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/coding/common-jar-settings/src/main/kotlin/com/tencent/shadow/coding/common_jar_settings/CommonJarSettingsPlugin.kt#L16-L17

接入项目工程采用Java8应该是没有问题的。我们可以这样来看，编译期依赖如果有问题，编译肯定会失败，能在上线前暴露问题的。Android运行时代码有一个普通class转换成dex格式的过程，这个过程本身就能保证Java字节码版本的兼容性。

关于接入项目的Gradle兼容性目前有一个自动化测试：
https://github.com/Tencent/Shadow/blob/5a3227b621717c17902f9bd0849ce3fc7c9d55f7/projects/test/gradle-plugin-agp-compat-test/README.md#L12-L11

**Comment by lks6123** [comment]
非常感谢大佬的回复
