### ISSUE TITLE
关于插件与宿主同一进程内，插件进程重启后再加载的问题

### ISSUE THREAD

**Issue by wlonglee** [Tencent/Shadow#852]
由于业务场景需求,宿主和插件在同一进程下运行利大于弊。分属不同进程的话，要实时处理手势相关的数据信息，跨进程通讯再回传数据给宿主的话肯定不如实时返回来的好，目前同进程的实现了需求，在更新插件这块遇到了问题，恳请大佬指点.
调用PpsController.exit()可以退出插件服务,如果插件服务属于单独的进程,这部分是没有问题的，
如果插件服务和宿主属于同一进程,PluginProcessService.exit的最后会调用System.exit(0) 这会导致整个主工程退出。 如果注释掉System.exit(0)这行代码，插件服务的进程很多其实都没解绑。再加载插件就会出问题。

**Comment by shifujun** [comment]
插件动态加载的代码可以说涉及3个部分：插件的Java代码加载到单独的ClassLoader中，插件的Native代码so加载到进程内存中，还有Android系统对插件代码的缓存，比如View的构造器缓存。

其中我们只有插件的ClassLoader算是能够自主卸载的，其余两部分都控制不了，所以唯一的手段只有重启进程。

所以这个问题只有在一个很小的场景下可以解决。就是动态加载的代码是完全自定义的Java代码，它们不会被系统以任何形式缓存。所以我们可以通过更换ClassLoader，从而加载固定接口的新实现来热更新。

如果考虑通过私有API修改PathClassLoader和Dex文件结构，即Tinker等热补丁技术，可以达到类似的效果。

**Comment by wlonglee** [comment]
> 插件动态加载的代码可以说涉及3个部分：插件的Java代码加载到单独的ClassLoader中，插件的Native代码so加载到进程内存中，还有Android系统对插件代码的缓存，比如View的构造器缓存。
> 
> 其中我们只有插件的ClassLoader算是能够自主卸载的，其余两部分都控制不了，所以唯一的手段只有重启进程。
> 
> 所以这个问题只有在一个很小的场景下可以解决。就是动态加载的代码是完全自定义的Java代码，它们不会被系统以任何形式缓存。所以我们可以通过更换ClassLoader，从而加载固定接口的新实现来热更新。
> 
> 如果考虑通过私有API修改PathClassLoader和Dex文件结构，即Tinker等热补丁技术，可以达到类似的效果。

多谢解答，我明白了，我先试下跨进程通讯的处理效果
