### ISSUE TITLE
请问下下面的结论对吗？

### ISSUE THREAD

**Issue by igottime** [Tencent/Shadow#854]
比如说我现在有两个插件。pluginmanager1，plugin1-zip和pluginmanager2，plugin1-zip。
一个PPS只能加载一个插件包里面的插件，如果我要同时加载两个插件包就需要两个PPS，并且两个PPS不能在同一进程。
如果想让一个PPS能够加载多个插件，就必须把这多个插件放在同一个插件包。
插件1跳插件2，必须要用宿主作为跳板吗？还是说可以直接从插件1跳插件2。这两个插件可能在同一个包，也可能不在。

**Comment by shifujun** [comment]
这些结论是不对的。

Wiki里的一些文章可以帮助你更好的理解代码，关于插件管理有  [Shadow对插件包管理的设计](https://juejin.im/post/5d2ec812e51d45778f076de3)

注意插件安装和加载插件是两个独立的过程，同一个UUID的多个apk才可以协同工作，但是它们也是可以分开安装的。

同一个进程只能有一个PPS，但是不影响它的Loader可以加载多个插件apk，甚至多个Loader（MultiLoaderPluginProcessService）。

插件间跳转依赖于同一个Loader加载了这些插件，同时具有所有插件的组件信息，才能帮助转换Intent直接跳转。仅此同进程中同一个Loader加载的插件是可以相互直接跳转的。

**Comment by igottime** [comment]
现在改用MultiLoaderPluginProcessService了。 但是发现一个疑问。如果采用同一个进程加载两个插件包，那这两个插件包就不能共用一套壳子，需要一个插件声明一套。或者如果要共用，就只能一个插件占用一个进程。是这样吗？

**Comment by igottime** [comment]
我现在想实现的效果是。可以动态新增插件。是不是只有两种方案：第一种是多进程方案。宿主里面预置若干个PPS，每个PPS都在不同的进程，一个PPS负责加载一个插件。第二种方案是单进程方案，需要在宿主里面预置若干组壳子Activity，一个插件占用一组。

**Comment by shifujun** [comment]
一个PPS对应一个插件进程。一个PluginContainerActivity对应一个HostActivityDelegate，也就对应一个Loader。

新增插件还可以通过下发更多相同UUID的安装包。相同UUID的插件和Loader等组件可以协同工作。这些相同UUID的部分只需要使用时已经安装好就可以了，并不需要提前都安装好。因此在一个进程中只有一个Loader的情况下，也是可以在部分插件已启动的状态下继续新增插件的。

**Comment by igottime** [comment]
那这样的话。因为升级某个插件要改变uuid。就导致所有的插件都要用新的uuid重新下发一次吗？

**Comment by shifujun** [comment]
uuid只是表达这些apk中的类是相互兼容的。所以升级插件时，变更所有部分的uuid对于兼容性来说是最可靠的做法。但确实存在部分代码变更并不破坏兼容性的情况。这时就有两种做法，要么是保持uuid不变，下发新的partKey。要么就是下发新的uuid，但是在下载插件时复用前一个uuid的文件。

**Comment by igottime** [comment]
我现在想实现动态地新增插件。我探索了两种方式。
第一种是，所有插件都在一个进程中。这时还有两种情况1. 宿主预置一组壳子Acitivty，所有插件共用一个uuid和一个runtime。2.有几个插件就宿主预置几组壳子Activity。不同插件使用不同uuid，每个插件都有自己独立的壳子Activity。后者肯定不理想，如果要新增插件，宿主就需要迭代。但是第一种的话，好像现有的代码不支持不同的uuid的插件直接复用同一个runtime。
第二种是，每个插件都有一个独立的进程。这种情况下需要宿主预置足够多的PPS。由于不同进程是隔离的。所以每个插件uuid可以不同。并且都必须有自己的runtime和loader。这样就可以任意升级插件，而不会有相互影响。

请问下你们在项目中是哪种方案。如果我想实现所有插件都在同一个进程，并且每个插件都有自己的uuid，还有我只想配置一组壳子Activity。每个不同uuid的插件都复用这一组壳子（代码和ClassLoader都只有一份）。这样的话，现有的代码是不是满足不了，只能自己重写插件的安装和加载流程。 我在现有代码里试了，不同uuid的插件包，里面放同一份runtime。由于同样的类只会加载一次。并且收到DelegatKey的影响，插件壳子类就不能被多个Loader所加载。同一个进程，相当于同一份runtime和loader其实是绑定在一起的。

**Comment by igottime** [comment]
就是我想实现的是。插件之间是相对独立的，以单独升级某个插件为主。

**Comment by hahajing9** [comment]
请问最后用了哪一种方案
