### ISSUE TITLE
貌似Provider对于支持grantUriPermissions有问题。。。

### ISSUE THREAD

**Issue by SpaceQ-Z** [Tencent/Shadow#855]
对接华为支付时需要在插件里声明个
        <provider
            android:name="com.huawei.hms.update.provider.UpdateProvider"
            android:authorities="${applicationId}.hms.update.provider"
            android:exported="false"
            android:grantUriPermissions="true"></provider>
        <provider
            android:name="com.huawei.hms.device.provider.CheckHmsProvider"
            android:authorities="${applicationId}.hms.device.validate.spoofprovider"
            android:exported="false"
            android:grantUriPermissions="false" />

打包的时候看到插件的Manifest里有 android:grantUriPermissions="false"，但在运行插件时会报错。因为CheckHmsProvider里有个判断grantUriPermissions为true时有抛个异常，导致插件闪退。
![image](https://user-images.githubusercontent.com/13994354/158989926-5263025d-860a-48dc-85ee-2c98df97b668.png)
明明传的false，但是代码里收到的是true....

**Comment by SpaceQ-Z** [comment]
找到问题了。。。走了默认值true值
我先自己改一下。。。
![image](https://user-images.githubusercontent.com/13994354/158991157-89a91192-ba4c-41e1-aed4-c24e9ad51d99.png)

**Comment by shifujun** [comment]
感谢反馈，确实有问题。

**Comment by SpaceQ-Z** [comment]
老板，我修复了下，辛苦看一下
