### ISSUE TITLE
关于 getDelegateProviderKey() 的疑问？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#856]
大佬。我看 shadow 这块儿示例的时候，在runtime中的 ContainerActivity 中，有的覆写了这个方法，返回了sample，有的使用的默认值DEFAULT_KEY。  然后在 Loader 中，继承自 ShadowPluginLoader 的类也覆写了这个值，返回了sample。看源码给我看的有点懵了。我想问下：
1. 这个值有什么用啊？
2. runtime 和 loader 中要返回相同的值么？
3. 如果值 runtime 和 loader 中返回的值不一样会怎样？
```
@SuppressLint("Registered")//无需注册在这个模块的Manifest中，要注册在宿主的Manifest中。
public class PluginDefaultProxyActivity extends PluginContainerActivity {

    @Override
    protected String getDelegateProviderKey() {
        return "SAMPLE";
    }
}
```
```
public class SamplePluginLoader extends ShadowPluginLoader {
    @Override
    public String getDelegateProviderKey() {
        return "SAMPLE";
    }
}
```

**Comment by shifujun** [comment]
DelegateProvider是宿主中不能动态更新的ContainerActivity的逻辑委托给能动态更新的Delegate接口的工厂类，
然后用DelegateProviderHolder这个静态类来完成依赖注入。

https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/activity-container/src/main/java/com/tencent/shadow/core/runtime/container/DelegateProviderHolder.java#L34-L36

因为是静态类，所以当进程中同时有多个DelegateProvider实现时，就需要根据一个key来完成这个**一对多**的绑定关系。

可以看一下这个key添加前的代码： 13a9d392f9300a748ecc09017ba3a30e27c51d21

示例代码中确实没有这个场景，这应该是我们业务中所需要的场景。

**Comment by lks6123** [comment]
> DelegateProvider是宿主中不能动态更新的ContainerActivity的逻辑委托给能动态更新的Delegate接口的工厂类， 然后用DelegateProviderHolder这个静态类来完成依赖注入。
> 
> https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/activity-container/src/main/java/com/tencent/shadow/core/runtime/container/DelegateProviderHolder.java#L34-L36
> 
> 因为是静态类，所以当进程中同时有多个DelegateProvider实现时，就需要根据一个key来完成这个**一对多**的绑定关系。
> 
> 可以看一下这个key添加前的代码： [13a9d39](https://github.com/Tencent/Shadow/commit/13a9d392f9300a748ecc09017ba3a30e27c51d21)
> 
> 示例代码中确实没有这个场景，这应该是我们业务中所需要的场景。

我看了下，DelegateProvider 的实现是ShadowPluginLoader，也就是说如果进程不存在多个loader的话，那么这个方法就不需要管它。 只有多 loader 的情况下才需要进行处理。 对吧？

**Comment by shifujun** [comment]
是的。
