### ISSUE TITLE
运行的时候,  apk下assets文件夹没有plugin_manager.apk

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#861]
但是asssts有plugin-debug.zip

**Comment by shifujun** [comment]
向assets中复制文件并不是SDK功能的一部分。sample中有这些代码可以参考：
https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/sample/source/sample-host/build.gradle#L53-L105

**Comment by TA-J** [comment]
这一段代码在宿主是有的，路径什么都是对的，唯独plugin_manager.apk没有复制进去

**Comment by TA-J** [comment]
@shifujun zip可以复制进去，manager需要有什么操作吗

**Comment by hdhhdhd** [comment]
> @shifujun zip可以复制进去，manager需要有什么操作吗
> 
> def createCopyTask(projectName, buildType, name, apkName, inputFile, taskName) { def outputFile = file("${getBuildDir()}/generated/assets/${name}/${buildType}/${apkName}") outputFile.getParentFile().mkdirs() return tasks.create("copy${buildType.capitalize()}${name.capitalize()}Task", Copy) { group = 'build' description = "复制${name}到assets中." from(inputFile.getParent()) { include(inputFile.name) rename { outputFile.name } } into(outputFile.getParent())
> 
> ```
> }.dependsOn("${projectName}:${taskName}")
> ```
> 
> }
> 
> def generateAssets(generateAssetsTask, buildType) {
> 
> ```
> def moduleName = 'sample-manager'
> def pluginManagerApkFile = file(
>         "${project(":sample-manager").getBuildDir()}" +
>                 "/outputs/apk/${buildType}/" +
>                 "${moduleName}-${buildType}.apk"
> )
> generateAssetsTask.dependsOn createCopyTask(
>         ':sample-manager',
>         buildType,
>         moduleName,
>         'sample-manager.apk',
>         pluginManagerApkFile,
>         "assemble${buildType.capitalize()}"
> )
> 
> def pluginZip = file("${getRootProject().getBuildDir()}/plugin-${buildType}.zip")
> generateAssetsTask.dependsOn createCopyTask(
>         ':plugin-one',
>         buildType,
>         'plugin-zip',
>         "plugin-${buildType}.zip",
>         pluginZip,
>         "package${buildType.capitalize()}Plugin"
> )
> ```
> 
> }
> 
> tasks.whenTaskAdded { task -> logger.debug("TAG", task.name) if (task.name == "generateDebugAssets") { generateAssets(task, 'debug') } if (task.name == "generateReleaseAssets") { generateAssets(task, 'release') } }
有什么解决方法吗。  我是apk能复制进去 zip不行
