### ISSUE TITLE
加载不到so

### ISSUE THREAD

**Issue by GitHubShy** [Tencent/Shadow#863]
已经重写了abi去和插件的一致：
`  @Override
    protected String getPluginPreferredAbi(String[] pluginSupportedAbis, File apkFile) throws InstallPluginException {
        return "armeabi-v7a";
    }`
宿主是一个系统app，咋还是报了如下错呢：
2022-03-23 14:31:26.233 7505-7570/com.senter.monitordaemon E/AndroidRuntime: FATAL EXCEPTION: Client[1]Tcp:WritingThread run
    Process: com.senter.monitordaemon:plugin, PID: 7505
    java.lang.UnsatisfiedLinkError: com.tencent.shadow.core.loader.classloaders.PluginClassLoader[DexPathList[[zip file "/data/user/0/com.senter.monitordaemon/files/ShadowPluginManager/UnpackedPlugin/senter-manager/962301a2a9ddef5ad1aa6cb36ed101eb/plugin-debug.zip/MonitorDaemon-plugin-Ic2-s2600v5-plain-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.senter.monitordaemon/files/ShadowPluginManager/UnpackedPlugin/senter-manager/lib/C072EC94-6BA4-42B4-BC2D-34E92F5A5EBC_lib, /system/lib64]]] couldn't find "libStNativeUtil.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.senter.support.util.StNativeUtil.<clinit>(StNativeUtil.java:12)
        at com.senter.support.util.StNativeUtil.ioctlSioCoutQ(StNativeUtil.java:39)
        at com.senter.monitordaemon.net.ClientImplTcp$3.run(ClientImplTcp.java:244)

**Comment by shifujun** [comment]
> couldn't find "libStNativeUtil.so"

既然报了找不到文件，建议debug一下这两个方法的执行情况吧。

https://github.com/Tencent/Shadow/blob/f777caea7ac238cdb2e644f14bf64e04dcb548b8/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L237

https://github.com/Tencent/Shadow/blob/f777caea7ac238cdb2e644f14bf64e04dcb548b8/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/CopySoBloc.java#L41

**Comment by GitHubShy** [comment]
我之前debug了一下，发现路径和插件apk，so的路径一致啊（插件的extractNativeLibs为false，所以没走extractSo），再往下就不知道咋找原因了...
![image](https://user-images.githubusercontent.com/12857252/159641357-b71db1a1-1d34-450c-9a3a-fcfd8f997ceb.png)

**Comment by shifujun** [comment]
即便设置了android:extractNativeLibs="false"，也需要调用extractSo的。因为要将nativeLibraryDirectories设置为apk路径。

https://github.com/Tencent/Shadow/blob/f777caea7ac238cdb2e644f14bf64e04dcb548b8/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L264

**Comment by GitHubShy** [comment]
> 即便设置了android:extractNativeLibs="false"，也需要调用extractSo的。因为要将nativeLibraryDirectories设置为apk路径。
> 
> https://github.com/Tencent/Shadow/blob/f777caea7ac238cdb2e644f14bf64e04dcb548b8/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/BasePluginManager.java#L264
不好意思打错了，是设置false之后就不走 CopySoBloc.copySo，直接取apk的lib目录了（和你发的一致）。 这一个问题应该是数据库里面的脏数据引起的。现在有个问题是：
    Process: com.senter.monitordaemon:plugin, PID: 11585
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.senter.monitordaemon/files/ShadowPluginManager/UnpackedPlugin/senter-manager/33475b0130dbb60517464814049fb082/plugin-debug.zip/MonitorDaemon-plugin-Ic2-s2600v5-plain-debug.apk!/lib/armeabi-v7a/libStNativeUtil.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.senter.support.util.StNativeUtil.<clinit>(StNativeUtil.java:12)
        at com.senter.support.util.StNativeUtil.ioctlSioCoutQ(StNativeUtil.java:39)
        at com.senter.monitordaemon.net.ClientImplTcp$3.run(ClientImplTcp.java:244)
插件单独运行是可以的，因为64位设备应该是兼容armeabi-v7a，但是现在插件化之后为报了这错，有点懵不知道改从哪改

**Comment by shifujun** [comment]
> is 32-bit instead of 64-bit

本来getPluginSupportedAbis的实现为你处理了这个问题的。如果在64位机器上，宿主没有任何so，系统安装它的时候就会默认它是64位的ABI了。这之后就不能再加载32位so了。所以你需要给宿主要先加入一个32位的so。

**Comment by GitHubShy** [comment]
> > is 32-bit instead of 64-bit
> 
> 本来getPluginSupportedAbis的实现为你处理了这个问题的。如果在64位机器上，宿主没有任何so，系统安装它的时候就会默认它是64位的ABI了。这之后就不能再加载32位so了。所以你需要给宿主要先加入一个32位的so。

哇塞，我刚还纳闷为啥getPluginSupportedAbis只返回Build.SUPPORTED_64_BIT_ABIS的列表呢，原来这样啊，学习到了非常感谢！
