### ISSUE TITLE
是否可以只打包Loader和Runtime？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#864]
我看其他人的issue以及源码。 loader和runtime加载时是通过uuid进行加载的。
那么是否可以这样做？
1. 打包时，一个 manager.apk + loader.zip (包里只有一个 loader.apk 和 runtime.apk 以及 config.json . ) + 若干个 plgin.zip（包含一个plugin.apk 以及 config.json ）?
2. 通过gradle打包插件时，是通过 packageAllPlugin 来打包的。 那有办法打包一个只包含 loader.apk 和 runtime.apk 以及 config.json 的zip包么？ ( 我发现在插件的module中的 shadow{} 中不写 plufinApks 的话， 打包过程会卡在  transformClassesWithShadowTransformForPluginDebug 这个Task这里 )

**Comment by shifujun** [comment]
是可以把一个uuid的多个部分拆成多个zip包分多次安装的。

不同的包可以通过配置配置多个pluginType实现，像这样：
https://github.com/Tencent/Shadow/blob/d0d0b927eaf07064ed3cd10920d6f3e4d706639b/projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin1/build.gradle#L53-L88

打包这块的逻辑比较简单，不同业务需求差异也比较大。可以二次开发一下。
