### ISSUE TITLE
关于插件启动另一个插件Activity的问题

### ISSUE THREAD

**Issue by leo-wxy** [Tencent/Shadow#87]
你好，我当前是基于 `https://github.com/shifujun/Shadow.git`中的`issue_56`测试多插件的启动，现在需要测试在插件中启动另一插件Activity的功能。请问可以提供一下相关代码或者思路吗？还是需要交由宿主进行跳转？

**Comment by shifujun** [comment]
同一个插件进程用的是同一个PPS，同一个PPS只有同一个Loader。同一个Loader可以加载多个插件。同一个Loader加载的多个插件的所有信息都由同一个Loader管理，所以这些插件之间可以直接相互跳转的。因为他们的Intent转换是由同一个ComponentManager完成的。

**Comment by leo-wxy** [comment]
但是在`另一个插件Plugin2`未被加载的情况下，需要先回调到宿主进行`插件Plugin2`加载，再进行跳转吗？还是可以在跳转过程中直接去进行加载插件的过程？

**Comment by shifujun** [comment]
是的，需要先通知Manager加载Plugin2，才能跳转到Plugin2中的组件。

自动去加载Plugin2这样的逻辑不适合在Core层写死。Core层目前的设计都是提供原子化的能力。需要在更贴近业务的上层组合这些能力。

**Comment by leo-wxy** [comment]
好的，感谢回复
