### ISSUE TITLE
插件的大小与启动速度设计有没有相应参照？

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#873]
如题
在贵公司实际项目中，插件的大小与速度有没有相应参考标准？我在开发中发现插件常常超过10mb左右，虽然还没有进行细致的缩减优化  想请教一下有咩有相应标准可以参考的。

**Comment by shifujun** [comment]
我们在实践中其实只关心从业务入口到关键能留住用户的功能正常工作的整体耗时。在统计这一过程中耗时分布时，如果遇到插件下载耗时较长的情况，会考虑这些手段：

1. 预加载。比如在业务入口本身可见时就触发插件的提前下载。
2. 占体积较大的基础能力复用宿主中的实现。
3. 网络化内置图片。
4. 拆分多插件，将次级业务延后下载。

并不会直接建立插件大小的硬标准。不同业务面对的用户群的网络情况也是不一样的。
