### ISSUE TITLE
插件的Application与跟随插件进程启动的Application是否是一个ClassLoader？

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#876]
插件、插件的Application
宿主、宿主的Application

插件进程启动时，会把宿主的Application执行一次，里面进行了一些初始化，插件启动后是不是就不需要初始化了？

**Comment by Daimhim** [comment]
多个插件公用一个进程 他们的ClassLoader是不是就用的同一个？

**Comment by shifujun** [comment]
“初始化”是一个抽象的概念。对于一段逻辑是否需要针对两部分代码分别初始化，是和这段逻辑自身特性相关的。

Shadow采用DexClassLoader加载插件apk，并且不会通过私有API修改DexClassLoader已加载的类。因此多个apk一定是由多个ClassLoader加载的。

建议通过debug sample来确定这些问题的答案。

**Comment by shifujun** [comment]
“基础sdk”和“初始化”都是抽象的概念，并没有确切的实现标准，因此无法抽象的断言是否可以“被同进程的多个插件共同使用”。

如果无法理解可以简单的debug一下，只管自己所需要的场景。
