### ISSUE TITLE
插件项目报错

### ISSUE THREAD

**Issue by lzphub** [Tencent/Shadow#878]
> Task :app:transformClassesWithShadowTransformForPluginDebug FAILED

Execution failed for task ':app:transformClassesWithShadowTransformForPluginDebug'.
> javassist.NotFoundException: D:\sdk\platforms\null\android.jar

**Comment by lzphub** [comment]
> 可以看一下你的代码是否包含了 [c4e17e1](https://github.com/Tencent/Shadow/commit/c4e17e1d0317922dde82ef09f2bf00d355a192a7)
不包含，并且我已经安装了20到31的SDK。

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/commit/0cf839653b5dd422f5a9504427c70949c8d936bd 这个提交可能也没有吧？

没有这个提交，也没有配置好ANDROID_HOME等SDK路径的环境变量的话，之前是会发生取到sdk版本为null的错误的。

**Comment by lzphub** [comment]
> [0cf8396](https://github.com/Tencent/Shadow/commit/0cf839653b5dd422f5a9504427c70949c8d936bd) 这个提交可能也没有吧？
> 
> 没有这个提交，也没有配置好ANDROID_HOME等SDK路径的环境变量的话，之前是会发生取到sdk版本为null的错误的。

环境变量应该是没问题的，Host包和Manager包都可以正常编译，只有Plugin包会出现这个错误。
