### ISSUE TITLE
宿主隐式声明插件中的类，如何做拦截？

### ISSUE THREAD

**Issue by TongWeiLe** [Tencent/Shadow#879]
一般都是选用叶子节点作为插件的，如果想用基础模块做插件，那业务开发无法控制入口类，所以想用clasloader的loadeclass方法作为拦截，但是测试发现，隐式声明的一个类，直接会从顶层的bootclassloader做加载，loadedapk里面的classloader根本拦截不到，这块有什么方法可以解决这种问题？

**Comment by TongWeiLe** [comment]
当然四大组件是可以正常拦截的因为它们都是通过classloader直接显示加载的，但是非组件的普通类都不会这么写。

**Comment by shifujun** [comment]
“隐式声明”、“拦截”是什么含义需要猜测。最好能附上可以debug的代码。

如果是说宿主中依赖的类位于插件apk中，是不行的。插件可以依赖宿主，因此宿主对插件的依赖要用控制反转实现。
这个依赖方向也和AAB中的dynamic-feature是一致的。

插件依赖宿主的示例代码可以参考：https://github.com/Tencent/Shadow/blob/e38755ec8fb77adfb5e7e96d8631dd04a1626422/projects/sample/source/sample-plugin/sample-app/src/main/java/com/tencent/shadow/sample/plugin/app/lib/usecases/host_communication/PluginUseHostClassActivity.java#L30 
同时注意全文搜索`com.tencent.shadow.sample.host.lib`这个包名在各处的配置。

**Comment by TongWeiLe** [comment]
宿主依赖插件，其实就是需要在宿主调用插件的时候去做拦截安装加载。如果插件是叶子节点正常业务开发都是路由跳转拦截的，
但是反过来的话，就需要在宿主调用插件类的时候进行拦截。


` @Override
    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {

        if (name.contains("xx")) {

            Log.e("", name);
        }
        return super.loadClass(name, resolve);
    }`

比如上面是我自定义的classloader，我可以在loadclass的时候去判断现在加载的类，如果包名符合插件的包名就去进行判断是否已经安装过插件。如果没有安装过就去同步的去安装（这里的插件是内置的，不需要去下载）。


进过测试发现这种方法存在的问题就是拦不住，当我加载一个插件类时

Plugin plugin = new Plugin();

直接会在bootclassloader里面进行load走不到我自定义的loader的loadClass方法里面。这里想了解下这种情况下是不是只能去hook顶层的bootclassloader了，但好像没法做。

**Comment by TongWeiLe** [comment]
网上搜了一圈好像之前没有这么做的，都是需要业务方保证在调用之前保证插件已经加载过了。但这种如果可以实现的话，业务方接入将会很简单，有利于推广

**Comment by shifujun** [comment]
你讨论好像不是Shadow已有的代码。似乎是讨论`Plugin plugin = new Plugin();`这样的代码中，为什么`Plugin`类无法在自定义的ClassLoader中加载。

如果是这样的话，这其实只涉及JVM加载类的一个基本知识，`Plugin`类必须由这行代码所属类的ClassLoader加载。所以一般不涉及自定义ClassLoader的app中如果写了这行代码。`Plugin`类会由PathClassLoader加载。因为PathClassLoader有双亲委派设计，所以它会先委托BootClassLoader加载。

因此如果想达到你说的效果，确实只能“hook顶层的bootclassloader了”。Shadow中的DynamicRuntime就是这样hook的。你可以在这个ClassLoader中再自行委托给任意ClassLoader实现你需要的逻辑。

**Comment by TongWeiLe** [comment]
试了下，确实可以，jvm遵循父加载器，当我插入定义的loader后，当代码执行到Plugin plugin = new Plugin()后，先执行到自定义的CustomDexClassloader的loadClass方法

`
protected Class<?> loadClass(String name, boolean resolve){

// 同步去安装插件

return super.loadClass(name, resolve);
}
`

这里安装成功后，调用super方法执行到bootclassloader的loadclass，boot先询问了自己是否进行了load，然后走到

`
 @Override
    protected Class<?> findClass(String name) throws ClassNotFoundException {
        return Class.classForName(name, false, null);
    }
`
最后在这里，这里没跟下去，我理解按照正常逻辑还是走到我们的pathclassloader，毕竟dex是添加到了pathclassloader的dexpathlist里面的。

----------------------------------------------------------------------------------------------------------------------

PS,刚开始是在customdexclassloader的super.loadclass之前调用pathclassloader的loadclass方法发现会一直死循环继续走进来。
