### ISSUE TITLE
请问Shadow版本使用最新代码还是release2.2.1版本比较好

### ISSUE THREAD

**Issue by Melody916** [Tencent/Shadow#880]
公司准备用Shadow构建应用，请问下，我们是基于github上的最新代码集成，还是基于 release2.2.1版本进行集成比较好。
另外想问下，release的下一个正式版本，最近是否有发布计划。

**Comment by shifujun** [comment]
请先注意Shadow一直是一个目的为代码交流的开源项目，并不提供商业服务。

将Shadow用于生产环境还是比较依赖于你对项目的掌握程度的。但尽管如此，将master分支的最新代码用于生产环境还是比较建议的。可以先注意这三点关键问题：
1. 宿主和插件的版本关系是多对多的。因此宿主Manifest中提前注册的壳子要提前预埋足够用的，否则修改宿主Manifest就意味着插件要区分宿主版本进行适配了。
2. 注意Shadow代码中不可动态更新的部分。仔细看提交记录可以发现Shadow的这部分代码非常稳定。这也是使用最新Shadow代码的信心来源。Shadow中的Bug和新增feature基本都可以动态升级的。
3. Shadow合入master分支的代码都是以正式发布的标准合入的。可以考察一下Shadow的提交记录，并不会随意向master分支提交不完整的改动，但确实存在合入后短期内发现bug的情况。

下一个正式版本近期可能就可以打一个tag了。但是这可能没那么重要，只是按照semver规则表达一些Shadow特性的进步。

**Comment by Melody916** [comment]
还有个问题
1.宿主和插件的版本关系是多对多的。----为什么这里是多对多的关系？

**Comment by shifujun** [comment]
> 还有个问题
> 
> 1.宿主和插件的版本关系是多对多的。----为什么这里是多对多的关系？
> 
> 

因为我们需要插件和宿主各自比较自由的自行发布新版本。希望不同版本的宿主和插件都能协同工作。
