### ISSUE TITLE
自己打包源码时，需要打包哪些module

### ISSUE THREAD

**Issue by Melody916** [Tencent/Shadow#884]
自己使用源码进行打包时，在project/sdk/core目录下的mudole，有一个manager-db-test，这个打包的时候需要带上吗？
还有就是使用README.md里的gradlew publish方式打包时，最终的产物里会有一个transform-kit-test目录，这个目录里的文件也是必须的吗？

**Comment by shifujun** [comment]
`manager-db-test`这个module肯定不是任何消费SDK的代码所需要的，它是Shadow项目自身的一个用于自动化测试DB升级兼容性的模块。将其与`manager`拆分，没有放到`manager`的`test`目录中，主要是因为不需要`manager`是一个android library（aar)模块，但是自动化测试确是需要在Android设备上执行。

`gradlew publish`是Shadow发布的任务。它发布的`transform-kit-test`也是SDK的产物之一，但不总是有用的。Shadow的`transform-kit`模块可以被单独复用于任何字节码编辑场景，因此有一个简单的`transform-kit-test`配套用于自动化测试。

如果你说的“打包”是指自行构建发布Shadow使用的话，可以注意下这段文档：https://github.com/Tencent/Shadow/tree/master/projects/sample#%E8%87%AA%E8%A1%8C%E5%8F%91%E5%B8%83sdk%E5%88%B0maven%E4%BB%93%E5%BA%93%E6%96%B9%E6%B3%95
