### ISSUE TITLE
插件Activity的管理如何做？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#887]
同一个进程中如何全局管理Activity?   
例如我在 宿主关闭一个 已打开的 Activity? 在 A 插件关闭 B 插件的一个Activity？
目前的思路是通过 广播 或者 Service ，  是否有更好的思路？

**Comment by shifujun** [comment]
这个问题和“插件”技术有什么特别的相关性吗？在无“插件”技术的app中你如何“管理”呢？

可以fork之后在sample中添加示例代码，表达你的意图。

**Comment by lks6123** [comment]
无插件的情况下，创建一个list, 通过 Application.ActivityLifecycleCallbacks 回调中， 在 onCreate 时将 activity 加入 list , 在 onDestroy 时移出 list 。 这样我就可以通过这个 list 获取任何一个 activity .
和插件化相关的点在于：
插件的管理方面，当我插件被卸载时， 可能我已经进入插件中的某个页面了。 此时我触发插件更新的查询， 发现插件已下架或者或者需要更新。 我可能需要关闭对应插件的所有页面。  而对于插件的管理是一个 单独的 运行在宿主中的库。 此时就涉及到关闭插件的页面了。

**Comment by lks6123** [comment]
> 这个问题和“插件”技术有什么特别的相关性吗？在无“插件”技术的app中你如何“管理”呢？
> 
> 可以fork之后在sample中添加示例代码，表达你的意图。

和插件相关的点在于插件的 管理。 我们项目中插件的下载更新管理是一个单独写的库，在宿主中运行。 
当启动一个插件时，如果本地包存在，会先打开插件页面，同步去获取插件更新。 此时发现插件可能由于业务原因已下架，不再使用。那么就需要 app 退出已进入的插件页面。 需要在宿主发起这个操作。 此时就涉及到关闭插件页面。
我们这边插件和宿主是运行在同一个进程的。

在无插件情况下， 是通过注册 Application.ActivityLifecycleCallbacks 的接口回调。 创建一个全局管理类，当 onCreate 时，将 Activity 加入 list 中， 当 onDestroy 时移出 list .  那么我可以在任何地方获得 list 中的 Activity 的对象，来进行操作。

**Comment by shifujun** [comment]
那你现在依然可以在插件内部使用ActivityLifecycleCallbacks，由插件的Application持有这些Activity对象。只是运行时它们会变成ShadowActivity类，不能传给宿主使用。但是宿主可以和插件约定接口让这些插件Activity实现，让宿主以自定义接口持有这些插件Activity。
