### ISSUE TITLE
callApplicationOnCreate可以返回包名嘛？

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#888]
启动插件的Application之后 返回插件的包名  这个算是比较通用吧

**Comment by Daimhim** [comment]
或者宿主、插件不同进程的情况下，启动插件时或启动插件后，宿主有咩有办法获取插件的包名

**Comment by shifujun** [comment]
如果“包名”指的是插件apk工程的`applicationId`，这个包名应该都是和宿主一样的。

因为插件的包名最终都是一样的，所以我们新增了一个属性：`partKey`，用来区别不同的插件apk。

在你调用callApplicationOnCreate时就是通过这个`partKey`来指明插件的：
https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/ShadowPluginLoader.kt#L115

所以这个问题显然不清楚，你最好用代码来表达。

**Comment by Daimhim** [comment]
额 我把插件改造了一下 现在插件与宿主使用的是不同的包名，
现在想通过partKey去反查找对应插件的包名 方便在插件activity跳转的时候 获取包名

![image](https://user-images.githubusercontent.com/20254978/162356733-c1bcaf09-4266-4653-8f11-78719a8d620c.png)
