### ISSUE TITLE
支持直接调用插件中的某个方法吗？不启动插件中的页面

### ISSUE THREAD

**Issue by guofudong** [Tencent/Shadow#895]

**Comment by shifujun** [comment]
这种场景就不是Shadow或者其他“插件框架”主要解决的问题了。实际上这不需要什么复杂的代码，new DexClassLoader加载一个apk，其余的东西就和普通的Java代码一样了。

**Comment by lizhanqi** [comment]
DexClassLoader 实现四大组件,或者资源会很难的.所以怎么能做到用shadow 里面方法调用某个方法然后返回结果呢

**Comment by shifujun** [comment]
> DexClassLoader 实现四大组件,或者资源会很难的.所以怎么能做到用shadow 里面方法调用某个方法然后返回结果呢

用代码表达一下问题push上来看看吧。

**Comment by sun804336516** [comment]
其实 加载了插件里面的application，applicaton定义个一个返回的api类，然后拿到这个application，获取这个访问的api类就行了
