### ISSUE TITLE
bindService 和 unbindService 的一个疑问？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#898]
通过 PluginLoader 可以 bindService 和 unbindService。  使用时传入了一个 PluginServiceConnection 对象。 那么 unbindService 时，必须传入和 bind 时相同的那个 PluginServiceConnection  实例 么 ？

**Comment by shifujun** [comment]
我没细看代码。但是如果你关心这个问题，你可以写个测试用例测一下不使用shadow时的系统API行为。如果shadow和系统不一致，就算是bug。
