### ISSUE TITLE
请问插件中的xml能够直接访问宿主的资源吗，目前会报错：AAPT: error: resource xxx not found.

### ISSUE THREAD

**Issue by code-czh** [Tencent/Shadow#899]

**Comment by shifujun** [comment]
> 请问在插件的xml中访问宿主的资源，有好的思路吗？ 目前直接访问构建会报错：AAPT: error: resource xxx not found.

Shadow的设计中宿主和插件的版本是多对多关系，所以你在编译期引用的宿主id是不固定的。即便你解决了AAPT的编译问题也是不可靠的。你这里aapt需要额外的参数将宿主资源路径也传进去才行。

由于宿主中的资源ID是不固定的，所以一样是通用的两种方法：反射或者约定接口。

反射的话可以参考：
https://github.com/singwhatiwanna/PinnedHeaderExpandableListView/blob/e8363011a4e156d2047c09cb0dcdfa12df89eef2/PinnedHeaderExpandableListView/src/com/ryg/expandable/ui/StickyLayout.java#L101-L105

约定接口可以sample中的`com.tencent.shadow.sample.host.lib`包，全文搜索，定义好插件访问宿主类的白名单。

**Comment by code-czh** [comment]
通过反射，只能在插件的代码中访问宿主的资源，插件的xml还是不能访问宿主的资源，是这样吗？

**Comment by liuhongda** [comment]
插件和宿主之间保持多对多的关系是非常不安全的：
1. 资源ID在每一次宿主APK重新打包的时候都是不一样的，插件也一样，每一次插件生成的时候资源ID都会变化（可以通过AAPT配置已经生成的ID保持不变）
2. 每一次宿主或者插件重新打包的时候混淆规则都可能发生改变（可以通过applymapping配置已经生成的混血规则保持不变）
3. 宿主或者插件重新打包的时候可能类也会改变，例如新打包的插件某些类已经被打包到新的宿主里面去了

根据Google官方的AAB方案，我们应该保持宿主对插件可以1对多，但是插件对宿主只能一对一，插件升级了宿主不一定要升级，但是宿主升级了，所有的插件一定要全部升级
