### ISSUE TITLE
Cannot run program "git": CreateProcess error=2, 系统找不到指定的文件。

### ISSUE THREAD

**Issue by SheepYang1993** [Tencent/Shadow#9]
* Where:
Script 'D:\Android\Project\Shadow\buildScripts\gradle\common.gradle' line: 3

* What went wrong:
A problem occurred evaluating script.
> Cannot run program "git": CreateProcess error=2, 系统找不到指定的文件。

**Comment by kaiyangjia** [comment]
> * Where:
>   Script 'D:\Android\Project\Shadow\buildScripts\gradle\common.gradle' line: 3
> * What went wrong:
>   A problem occurred evaluating script.
> 
> > Cannot run program "git": CreateProcess error=2, 系统找不到指定的文件。

你没有安装 git 吧？应该安装下 git 就行了

**Comment by SheepYang1993** [comment]
> > * Where:
> >   Script 'D:\Android\Project\Shadow\buildScripts\gradle\common.gradle' line: 3
> > * What went wrong:
> >   A problem occurred evaluating script.
> > 
> > > Cannot run program "git": CreateProcess error=2, 系统找不到指定的文件。
> 
> 你没有安装 git 吧？应该安装下 git 就行了

装git了，我其他项目也有git rev-parse --short HEAD命令，且能执行成功。
但只有Shadow项目不能找到git...

**Comment by kaiyangjia** [comment]
> > > * Where:
> > >   Script 'D:\Android\Project\Shadow\buildScripts\gradle\common.gradle' line: 3
> > > * What went wrong:
> > >   A problem occurred evaluating script.
> > > 
> > > > Cannot run program "git": CreateProcess error=2, 系统找不到指定的文件。
> > 
> > 
> > 你没有安装 git 吧？应该安装下 git 就行了
> 
> 装git了，我其他项目也有git rev-parse --short HEAD命令，且能执行成功。
> 但只有Shadow项目不能找到git...

按照这个文章里面的方法配置下Android Studio 呢？看起来是AndroidStudio内部指定的git 位置没找到

[https://blog.csdn.net/JavaLixy/article/details/76167439](https://blog.csdn.net/JavaLixy/article/details/76167439)

**Comment by SheepYang1993** [comment]
重启下AndroidStudio重新打开项目就可以了，可能是AndroidStudio的问题。。。
