### ISSUE TITLE
打release和debug签名包出现这个问题，正常运行是没问题的

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#901]
E:\VirtualAPKProject\TX_Shadow\sample-loader\build\outputs\apk\release\sample-loader-release.apk , loader file not exist...

**Comment by TA-J** [comment]
![image](https://user-images.githubusercontent.com/39261338/163583153-e74ef1ab-1083-41a8-b23d-3389f3561fa4.png)
打包是这种方式还是通过gradlew这种

**Comment by TA-J** [comment]
@shifujun

**Comment by shifujun** [comment]
把代码push上来，然后贴一下git clone之后复现问题的命令。

**Comment by TA-J** [comment]
https://gitee.com/GaoHJ1112/tx_shadow.git
Build-->Generate Signed Bundle or APK

**Comment by shifujun** [comment]
```
sh ./gradlew packageDebugPlugin

7z l build/plugin-debug.zip                

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2022-04-18 18:38:14 .....      4023391      3333472  plugin-one-plugin-debug.apk
2022-04-18 18:38:20 .....      4018703      3329935  plugin-two-plugin-debug.apk
2022-04-18 18:37:44 .....     45238246     17529496  plugin-game-plugin-debug.apk
2022-04-18 18:38:20 .....        54718        48241  sample-runtime-debug.apk
2022-04-18 18:38:18 .....       819885       809900  sample-loader-debug.apk
2022-04-18 18:38:38 .....          879          389  config.json
------------------- ----- ------------ ------------  ------------------------
2022-04-18 18:38:38           54155822     25051433  6 files
```

执行`packageDebugPlugin`看起来一切正常。不知道你从哪看到用`Build-->Generate Signed Bundle or APK`的指引。正常的话应该参考这里：https://github.com/Tencent/Shadow/blob/08da57dd53ae76a002a1fa341b170fd469151e68/projects/sample/README.md#%E8%BF%90%E8%A1%8C%E6%96%B9%E6%B3%95

**Comment by TA-J** [comment]
我是通过这个打release包的
<img width="471" alt="image" src="https://user-images.githubusercontent.com/39261338/163804634-9fa5daa6-1991-45fe-92c7-cb14d0c73fc1.png">

**Comment by luoxiong94** [comment]
同样的错误，请问楼主是如何解决的？

**Comment by TA-J** [comment]
作者解决了啊，有什么东西被混淆了，过滤一下就行了

**Comment by luoxiong94** [comment]
> 我是通过这个打release包的 <img alt="image" width="471" src="https://user-images.githubusercontent.com/39261338/163804634-9fa5daa6-1991-45fe-92c7-cb14d0c73fc1.png">

我和你一样，也是通过这个方式打的sample-host项目，我配置了signingConfigs，但是还是报 loader file not exist...
