### ISSUE TITLE
插件、模块依赖问题疑惑

### ISSUE THREAD

**Issue by neil-zhao** [Tencent/Shadow#902]
shadow项目中有好多诸如以下的各种依赖，其中有的是插件依赖，有的是项目模块间依赖
classpath 'com.tencent.shadow.coding:android-jar'
classpath 'com.tencent.shadow.coding:aar-to-jar-plugin'
classpath 'com.tencent.shadow.core:runtime'
classpath 'com.tencent.shadow.core:activity-container'
classpath 'com.tencent.shadow.core:gradle-plugin'

implementation 'com.tencent.shadow.core:common'
implementation 'com.tencent.shadow.dynamic:dynamic-host'

这种依赖方式针对插件开发和多项目模块依赖提供了诸多便利，我想在自己的项目中尝试使用这种方式依赖本地项目模块或插件。但始终失败，不知道哪里有问题。
目前尝试的方式是在项目的setting文件中增加诸如includeBuild 'projects/coding'来依赖子项目。然后再通过以下这种方式引入，发现模块无法找到
 classpath 'com.rifle.coding:plugin-debug'
 classpath 'com.rifle.coding:symbols-debug'

我翻了针对本项目的好多issue，发现没有人针对这个问题提问，
不知道问题出在哪里。大佬能否解释下shadow项目中以上的依赖方式如何实现的，非常感谢

**Comment by shifujun** [comment]
同这个回复：https://github.com/Tencent/Shadow/issues/869#issuecomment-1080151174

如果你有代码我可以帮你看看。
