### ISSUE TITLE
关于Runtime的ProxyActivity注册问题

### ISSUE THREAD

**Issue by chy116449859** [Tencent/Shadow#904]
Runtime的ProxyActivity需要在host里注册，这个是必需的吗？插件的内容注册到宿主里，感觉这个不太好，如果有多个插件如何处理呢，有没有其他的处理方式？

**Comment by shifujun** [comment]
是必须的。而且这是所有类似的插件技术绕不开的障碍。因为它是Android系统的基本设计之一，连系统App都要遵守。官方的AAB分发技术中的dynamic-feature也有此限制。

尽管如此，所有插件技术都尽可能在固定的manifest限制下，将app行为尽可能动态化。“感觉这个不太好”并不是一个清晰的表达，你应该说你有什么场景实现不了。

多插件在这件事上并没有什么影响。Shadow这种代理方案下，ProxyActivity和PluginActivity是一对多的关系。即便是Single Instance的Activity，也只需要保证同一时间ProxyActivity只被一个PluginActivity占用即可。

**Comment by chy116449859** [comment]
所谓的“不太好”的场景，我举个例子，比如宿主和插件是2个团队开发的，宿主和插件是彼此没有对方源码，理论上插件方只需要接入宿主的一些的信息即可完成插件化流程，而不用让宿主为了兼容该插件去动宿主的源码。我做了一个宿主，我想让公司的其他团队的一些功能作为插件集成到我的宿主上，只需要告诉他你配置一些数据就可以完成了。如果不同的插件都需要在宿主里改动，那是不是意味着每多一个插件，我的宿主也需要跟着进行升级一次？

**Comment by shifujun** [comment]
> 如果不同的插件都需要在宿主里改动，那是不是意味着每多一个插件，我的宿主也需要跟着进行升级一次？

没错。但是你的前提错了。使用插件技术的目的就是不修改宿主代码，能动态更新插件。因此你的判断是有问题的。你可以多做些实验来理解这项技术。

**Comment by chy116449859** [comment]
是的，使用插件就是不希望修改宿主代码。你的意思是第一次安装插件需要修改宿主代码(意味着要升级宿主)而后续的更新不用更新宿主了，还是说无论新安装的插件还是更新插件都不需要宿主升级？可能我还没理解到你这套的核心吧，我还在尝试，试试多插件的情况。

**Comment by shifujun** [comment]
至少在Shadow的设计中，合入宿主的不可修改的部分提供的都是”容器“”权限“等能力范围的限制，所以这要在这些范围内开发插件，就永远都不用更新宿主中插件相关的代码了。
