### ISSUE TITLE
拉取最新代码以后，IDE不能索引android.jar中的api了。全部爆红。

### ISSUE THREAD

**Issue by igottime** [Tencent/Shadow#905]
重启ide，清除ide缓存，重启电脑都不行。更新之前是没问题的。更新之后就不行了。
[![Lrm9Jg.png](https://s1.ax1x.com/2022/04/20/Lrm9Jg.png)](https://imgtu.com/i/Lrm9Jg)

**Comment by igottime** [comment]
只是爆红，不影响编译运行

**Comment by igottime** [comment]
as版本是稳定版最新的。2021.1.1 patch3。这份代码是官方的sample，没有改动过gradle的配置。

**Comment by shifujun** [comment]
应该是因为最近升级了compilesdk到31的关系。IDE索引是基于.idea目录里的xml和iml文件的。这些文件应该没有被正确更新。我刚才也构造了一下场景确实能复现。

你可以先`mv .idea .idea.bak`一下，然后重新用IDE打开工程，让它重新生成这个目录里的ide相关文件，应该就正常了。

我们可以再研究一下怎么更优雅的让IDE重新生成正确的配置。

**Comment by shifujun** [comment]
> 让它重新生成这个目录里的ide相关文件，应该就正常了。

我这里还是不太正常，我再调试一下。

你可以在原来的.idea目录里全文搜索一下android-30，把它们改成andorid-31。
