### ISSUE TITLE
如何生成多个插件

### ISSUE THREAD

**Issue by lzphub** [Tencent/Shadow#907]
如何在一个项目中的多个module生成不同的插件，现在可以生成插件zip，但是每个插件名称都是plugin-debug.zip，多个module同时生成后一个Module的插件会将前一个覆盖，如何修改每个插件的名称，使其不覆盖前一个module已生成的插件？

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/CreatePackagePluginTask.kt#L77-L85

有前后缀设置的DSL。

**Comment by lzphub** [comment]
> 

好的，谢谢
