### ISSUE TITLE
ProxyActivity注册时指定configChanges全注册 和theme为透明的原因？

### ISSUE THREAD

**Issue by ARabbitCoder** [Tencent/Shadow#909]
现在接入过程中ProxyActivity theme注册成透明，在Actvity启动模式为singleTop时，同一ProxyActivity跳转，部分手机能看到上一个Activity.关闭<item name="android:windowIsTranslucent">false</item>时就不会出现。想知道这些设置是否是必须的？

**Comment by shifujun** [comment]
设置为透明的原因是我们开发时观察到如果不设置成透明的，插件将无法再设置透明背景。所以考虑都设置成透明的，插件如果不需要透明，就主动设置一个不透明的颜色作为背景就行了。毕竟manifest里的设置是不能动态更新的。
