### ISSUE TITLE
test-none-dynamic-host实现插件卸载

### ISSUE THREAD

**Issue by ChessLuo** [Tencent/Shadow#91]
大佬好；参考test-none-dynamic-host实例，这时只需复制插件apk文件就可以打开插件了，如果在此基础上添加插件卸载功能，可以依赖SDK库使用BasePluginManager中的“删除指定uuid的插件”功能吗

**Comment by ChessLuo** [comment]
目前none-dynamic好像实现不了插件删除，但是继承manager就需要定义UUID，可能就要使用类似sample-host-demo打包zip插件压缩包方式吧；Shadow确实强大，我尝试改变插件apk版本尝试升级功能，再重新启动 插件数据没有丢失，继续看sample源码先了

**Comment by shifujun** [comment]
这里确实有点遗憾，我们没精力写好none-dynamic的例子了。因为我们业务并不以none-dynamic方式使用插件框架了。但是Shadow的架构设计是想保持none-dynamic可用的。这里没能实现好的是core.manager没有真的做到不关心dynamic，它还是假设了loader和runtime都是动态的。所以none-dynamic的sample没能演示直接使用core.manager，而是裸写了启动apk的逻辑。

**Comment by ChessLuo** [comment]
@shifujun 好的，谢谢，已经很强大了，感谢开源。
