### ISSUE TITLE
关于32位与64位so

### ISSUE THREAD

**Issue by choofake** [Tencent/Shadow#910]
现在的问题是：正常打包，在32位和64位设备上都能正常运行，但是打包成插件后，在64位设备上提示so不存在
在manager 中把 ABI 改成“armeabi-v7a”，提示不是64位的so

尴尬的是没有64位so.......

大佬，这个问题怎么处理

**Comment by shifujun** [comment]
插件要和宿主采用相同的ABI。如果宿主没有so，在64位机器上，系统就会默认它是64位的ABI。

所以插件如果是32位的，就至少要给宿主内置一个32位的so才行。

**Comment by choofake** [comment]
> 插件要和宿主采用相同的ABI。如果宿主没有so，在64位机器上，系统就会默认它是64位的ABI。
> 
> 所以插件如果是32位的，就至少要给宿主内置一个32位的so才行。

ok,已经好了，谢谢
