### ISSUE TITLE
关于so问题

### ISSUE THREAD

**Issue by choofake** [Tencent/Shadow#911]
现在的问题是：正常打包，在32位和64位设备上都能正常运行，但是打包成插件后，在64位设备上提示so不存在
在manager 中把 ABI 改成“armeabi-v7a”，提示不是64位的so

尴尬的是没有64位so.......

大佬，这个问题怎么处理

**Comment by szhua** [comment]
同问，如何解决的

**Comment by szhua** [comment]
> 现在的问题是：正常打包，在32位和64位设备上都能正常运行，但是打包成插件后，在64位设备上提示so不存在 在manager 中把 ABI 改成“armeabi-v7a”，提示不是64位的so
> 
> 尴尬的是没有64位so.......
> 
> 大佬，这个问题怎么处理

同问，咋解决的大佬
