### ISSUE TITLE
请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'

### ISSUE THREAD

**Issue by wangqingpeng131** [Tencent/Shadow#916]
自己写的简单的demo一直报错。请大佬帮忙看一下问题出在哪里了。
宿主：https://github.com/wangqingpeng131/shadow-host.git 
插件：https://github.com/wangqingpeng131/shadow-plugin.git
mananger：https://github.com/wangqingpeng131/shadow-manager.git
shadow sdk版本：commit e41153daa0f2d48d2724bf4c5fb8748ea19cce20 (HEAD, tag: 2.3.0)
我是用2.3.0的shadow发布的本地包。
看了之前的issues在插件的build.gradle中加入了    flavorDimensions(*flavorDimensionList) 和
` productFlavors {
        plugin {
            applicationId "com.test.shadowmaster"
        }
    }`
仍然报错。

**Comment by wangqingpeng131** [comment]
manager编译出来的apk和插件编译出来的apk我都放在了宿主的assets目录下面。在我用宿主启动插件的时候报错。

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/classloaders/PluginClassLoader.kt#L115-L125

可以看到这个异常只是在判断能不能在插件apk中找到`com.tencent.shadow.core.manifest_parser.PluginManifest`这个类。

我用本地编译的`local-e41153da-SNAPSHOT`，放到你的[shadow-plugin.git](https://github.com/wangqingpeng131/shadow-plugin.git)工程中，编译的`app-plugin-debug.apk`中是有这个类的。
<img width="643" alt="image" src="https://user-images.githubusercontent.com/3535204/164628000-a307289a-8f20-4113-b319-ff4515b75127.png">


你这个app工程也挺简单的，没什么自定义flavor。所以我估计你可能只是搞错了shadow的版本，混用了没有manifest-parser设计的旧版本。

**Comment by wangqingpeng131** [comment]
![image](https://user-images.githubusercontent.com/24642224/164964672-fd9d9315-8edb-42bf-a957-688b03cad12e.png)
![image](https://user-images.githubusercontent.com/24642224/164964716-71e580f0-38b9-4620-a5fb-2e78ca5e1136.png)
![image](https://user-images.githubusercontent.com/24642224/164964723-097b8d15-c442-4ecd-8691-b66295b97c6b.png)
感谢回复，我又做了几次尝试，发现签名的release版本没有PluginManifest。而没有签名的debug版本是有的。这个是因为什么？./gradlew packageDebugPlugin打包出来的插件确实不会crash。但release会报上面的错误。
