### ISSUE TITLE
插件中的Application

### ISSUE THREAD

**Issue by fy9er** [Tencent/Shadow#917]
请问在怎么让指定的类中的Application保持原有类型，保持插件（或者指定类）的Application会不会有影响

**Comment by shifujun** [comment]
Shadow把Application、Activity都替换成由宿主的Application、Activity持有的普通类ShadowApplication、ShadowActivity，这是因为Android系统对这些类型有不能动态更新的限制。通过改继承为持有，Android系统就不会直接和插件中动态加载的类型有任何交互，因此达到不违反Android系统对这些特定类型不能动态更新的限制。

所以插件的Application在Shadow运行时下只是一段普通的逻辑。如果遇到任何接口需要Application类型，而插件代码又想把插件的Application传入的场景，都说明这里违反了设计原则。即便插件Application的类型没有被Shadow修改，通常也是不能工作的，因为插件的Application并没有在已安装的app的manifest中注册。

通常我们应该把宿主的Application传给这些需要Application的接口。

**Comment by wh963572516** [comment]
那怎么写呢？
