### ISSUE TITLE
最新的代码编译shadow，在小于等于8.0的系统出现资源找不到，或者主题不匹配

### ISSUE THREAD

**Issue by SkywardSky** [Tencent/Shadow#918]
请问为什么使用最新的代码编译shadow后，在小于等于8.0的系统上会出现资源id找不到，或者主题不匹配的问题
资源id找不到所报的错：
04-22 22:45:22.381 11524 11524 E AndroidRuntime: android.view.InflateException: Binary XML file line #18: Binary XML file line #21: Error inflating class com.afollestad.materialdialogs.internal.button.DialogActionButton
--
4604-22 22:45:22.381 11524 11524 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class com.afollestad.materialdialogs.internal.button.DialogActionButton
4704-22 22:45:22.381 11524 11524 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
4804-22 22:45:22.381 11524 11524 E AndroidRuntime: at java.lang.reflect.Constructor.newInstance0(Native Method)
4904-22 22:45:22.381 11524 11524 E AndroidRuntime: at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
5004-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.createView(LayoutInflater.java:656)
5104-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835)
5204-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775)
5304-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.rInflate(LayoutInflater.java:908)
5404-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869)
5504-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1040)
5604-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.rInflate(LayoutInflater.java:904)
5704-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869)
5804-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
5904-22 22:45:22.381 11524 11524 E AndroidRuntime: at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
6004-22 22:45:22.381 11524 11524 E AndroidRuntime: at com.afollestad.materialdialogs.ModalDialog.createView(DialogBehavior.kt:98)
6104-22 22:45:22.381 11524 11524 E AndroidRuntime: at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.kt:106)
6204-22 22:45:22.381 11524 11524 E AndroidRuntime: at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.kt:58)

主题不匹配所报的错：
You need to use a Theme.AppCompat theme (or descendant) with this activity.

shadow代码在切回到：

https://github.com/Tencent/Shadow/commit/e41153daa0f2d48d2724bf4c5fb8748ea19cce20 的提交，然后重新编译shadow，这时候就没有上述的两个问题。感觉像是那个mixresource去掉后的问题，看了后面的提交已经是使用反射去添加资源了，但是感觉像不起作用一样。

**Comment by shifujun** [comment]
有能复现问题的代码吗？要是26以下资源id分区实在不行，还是回到mix resource的方案比较安全。目前master的测试用例已经都在api 16的机器上跑过了。21，25，26，28也都测了资源相关在用例。
