### ISSUE TITLE
LoadPluginCallback  找不到

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#919]
![8NI_)62UQO3H%LLKZKN99~3](https://user-images.githubusercontent.com/39261338/164955101-5e2be93e-5392-4e72-8f28-f59fc7830022.png)
一、在sample-loader->SamplePluginLoader类找不到LoadPluginCallback
二、如果注释掉LoadPluginCallback.getCallback().beforeLoadPlugin(partKey) ，然后会出现    请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'  我检查了项目的每个插件都有用到apply plugin: 'com.tencent.shadow.plugin'
这个问题很奇怪

**Comment by shifujun** [comment]
如果没有代码和可以复现问题的步骤，很难产生有效的交流。

**Comment by TA-J** [comment]
debug运行没问题的，release才会出现，感谢
https://gitee.com/GaoHJ1112/tx_shadow.git
