### ISSUE TITLE
请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#922]
![image](https://user-images.githubusercontent.com/39261338/164965983-e4629de1-9a43-4062-8f53-d5e4265287bf.png)
这个问题也是的 debug跑是没问题的，release打包就会出现

**Comment by shifujun** [comment]
duplicate with #922

**Comment by TA-J** [comment]
感谢，问题都已解决
