### ISSUE TITLE
请问下在插件activity中能否获取到宿主代理activity的实例

### ISSUE THREAD

**Issue by zhuqichao** [Tencent/Shadow#923]
调用一个第三方SDK，需传入activity作为参数，传入一个插件activity后会报如下错误：
No implementation found for void com.alipay.face.api.ZIMFacade.initApdid(android.content.Context) (tried Java_com_alipay_face_api_ZIMFacade_initApdid and Java_com_alipay_face_api_ZIMFacade_initApdid__Landroid_content_Context_2)

**Comment by shifujun** [comment]
可以参考：https://github.com/Tencent/Shadow/issues/596#issuecomment-914116701

不过第三方SDK中的java代码如果原本签名上需要的是Activity，也会被Shadow修改成ShadowActivity的，所以传入插件Activity应该是可以的。

出现第三方SDK依然需要Activity类型的情况，一般是第三方SDK处于宿主中，或者这个接口是so中的native方法。这种情况下，最好还是在宿主中调用第三方SDK。再由宿主提供接口给插件服务。

**Comment by zhuqichao** [comment]
> 可以参考：[#596 (comment)](https://github.com/Tencent/Shadow/issues/596#issuecomment-914116701)
> 
> 不过第三方SDK中的java代码如果原本签名上需要的是Activity，也会被Shadow修改成ShadowActivity的，所以传入插件Activity应该是可以的。
> 
> 出现第三方SDK依然需要Activity类型的情况，一般是第三方SDK处于宿主中，或者这个接口是so中的native方法。这种情况下，最好还是在宿主中调用第三方SDK。再由宿主提供接口给插件服务。

今天遇到个新的问题，插件中调用SDK里面的一个方法，参数是activity，但是会报如下错误：
Caused by: java.lang.NoSuchMethodError: No static method getRootView(Lcom/tencent/shadow/core/runtime/ShadowActivity;)Landroid/view/View;
检查插件apk dex文件，发现方法是有的：
.method public static getRootView(Lcom/tencent/shadow/core/runtime/ShadowActivity;)Landroid/view/View;
    .registers 3
    .param p0, "activity"    # Lcom/tencent/shadow/core/runtime/ShadowActivity;

    .line 96
    const v0, 0x1020002

    invoke-virtual {p0, v0}, Lcom/tencent/shadow/core/runtime/ShadowActivity;->findViewById(I)Landroid/view/View;

    move-result-object v0

    check-cast v0, Landroid/view/ViewGroup;

    const/4 v1, 0x0

    invoke-virtual {v0, v1}, Landroid/view/ViewGroup;->getChildAt(I)Landroid/view/View;

    move-result-object v0

    return-object v0
.end method

**Comment by shifujun** [comment]
与原issue不相关的问题最好另外提issue。但是看你的新问题也是没有代码，只能猜测。如果能复现，有代码再新提issue附上吧。

如果出现报找不到匹配的签名，但实际上字节码中是存在的。一种可能的原因是运行时同名的类型存在于多个ClassLoader中，调用方和实现方加载的类型不是同一份。比如你可能把ShadowActivity加载到了两个ClassLoader中，所以虽然报错信息看起来是同一个ShadowActivity，但是它预期的ShadowActivity和它发现的ShadowActivity不是同一个类。

**Comment by zhuqichao** [comment]
> 与原issue不相关的问题最好另外提issue。但是看你的新问题也是没有代码，只能猜测。如果能复现，有代码再新提issue附上吧。
> 
> 如果出现报找不到匹配的签名，但实际上字节码中是存在的。一种可能的原因是运行时同名的类型存在于多个ClassLoader中，调用方和实现方加载的类型不是同一份。比如你可能把ShadowActivity加载到了两个ClassLoader中，所以虽然报错信息看起来是同一个ShadowActivity，但是它预期的ShadowActivity和它发现的ShadowActivity不是同一个类。

感谢解答，已经找到原因了
