### ISSUE TITLE
Plugin找不到

### ISSUE THREAD

**Issue by lzphub** [Tencent/Shadow#929]
启动A插件后再去启动B插件会报错，java.lang.RuntimeException: java.lang.IllegalStateException: uuid==B299D280-5577-49FB-800F-795401091402partKey==sample-plugin-app的Plugin找不到
debug发现在SamplePluginManager中loadPlugin(installedPlugin.UUID,partKey);时，partKey是B插件的，但是uuid为先启动的A插件的，无法匹配，请问要怎么处理？

**Comment by shifujun** [comment]
插件进程每次只能启动相同uuid的组件。这个uuid就是它们共同的版本号，表明它们是可以协同工作的。

因此你的A插件和B插件如果确实是同一个版本，需要将它们的uuid设置成一样的。

https://github.com/Tencent/Shadow/blob/1d950691f2e52305fbc96dddd2dd68023d1d147b/projects/sdk/core/gradle-plugin/src/test/testProjects/case1/plugin1/build.gradle#L93

https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/extensions/PackagePluginExtension.kt#L121-L137

**Comment by lzphub** [comment]
> 

谢谢，可以了，还有个问题是否是在同一个宿主中运行的插件都需要将uuid设为一致的。

**Comment by shifujun** [comment]
同一个PPS实例加载的所有组件的uuid要保持一致。同一个宿主可能有多个插件进程，它们是不相关的。

**Comment by hahajing9** [comment]
那如果就是需要不同的uuid 报这个错误怎么办

**Comment by hahajing9** [comment]
@shifujun
