### ISSUE TITLE
android9.0报错

### ISSUE THREAD

**Issue by ChessLuo** [Tencent/Shadow#93]
报错信息：
Unsupported class loader
Skipping duplicate class check due to unsupported classloader

目前我使用了Android9.0的手机上测试，在打开插件的时候报错，在Android9.0之前的手机打开插件正常；大佬有遇到过这问题吗，打扰了，先谢谢了哈

**Comment by shifujun** [comment]
你贴的报错信息应该不是真正原因。

建议你把代码push上来，让我或者其他人可以直接跑。

如果是在sample工程里添加了什么东西跑不起来了，可能是因为严格检查模式的关系吧。比如之前的issue #54

**Comment by ChessLuo** [comment]
@shifujun 应该不是严格检查模式问题，我注释掉了，但是奇怪的是在Android4.4、Android6.0以及7.0的手机上都打开插件了，这里比较头疼，只好先请教一下大佬；刚刚push了sample工程：https://github.com/ChessLuo/ShadowSample

**Comment by shifujun** [comment]
上周五本来是要帮你看一下这个问题的，结果有事情耽搁了又没时间了。

主要问题是你的代码库不是Shadow的fork，我要花很多时间才能看明白你的代码改了什么，再干什么。这样效率很低。

如果你的问题还没有解决，建议还是fork一个版本添加修改，这样我既能运行也能快速知道你改了什么。像#92 #94 那样交流问题，效率就很高。

**Comment by ChessLuo** [comment]
@shifujun 在9.0上报错的原因 java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.DefaultHttpClient" ，插件APP使用了该库
