### ISSUE TITLE
关于 DynamicRuntime.recoveryRuntime(this) 的一点疑问？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#940]
当插件和宿主在不同进程时，当启动插件进程会调用这段代码：
```
        if (isProcess(this, ":plugin")) {
            //在全动态架构中，Activity组件没有打包在宿主而是位于被动态加载的runtime，
            //为了防止插件crash后，系统自动恢复crash前的Activity组件，此时由于没有加载runtime而发生classNotFound异常，导致二次crash
            //因此这里恢复加载上一次的runtime
            DynamicRuntime.recoveryRuntime(this);
        }
```
那么有两个疑问：
1. 如果有多个插件进程，是每个插件进程调用一遍么？（我的判断是需要的，不清楚对不对）
2. 如果插件和宿主在同一进程，这里要怎么处理？ 不调用了？

**Comment by shifujun** [comment]
> 如果有多个插件进程，是每个插件进程调用一遍么？

是的。

> 如果插件和宿主在同一进程，这里要怎么处理？ 不调用了？

也要调用。

你需要理解这个`recoveryRuntime`的作用。你可以这样复现问题：
1. 准备两个插件Activity：A、B。
2. 在A中点按钮打开B。
3. 在B中点按钮触发Crash。
4. 观察插件进程pid，观察插件进程Crash日志。
5. 去掉`recoveryRuntime`调用，再观察。

预期应该是这样的，在Crash之后，B应该就被系统关掉了。然后系统就会把Activity栈中的前一个Activity A启动起来。这里A也是一个插件Activity，所以它对于系统来说就是runtime.apk中的PluginContainerActivity的子类，它的类代码不在宿主apk中。这时，如果没有调用`recoveryRuntime`，此Activity所在的进程也没有执行过任何插件相关逻辑加载runtime.apk，所以就会发生第2次Crash，即报找不到A类。如果调用了`recoveryRuntime`，这里就能正常启动壳子PluginContainerActivity，之后应该由PluginContainerActivity的逻辑判断出此时的场景，静默finish自己。
https://github.com/Tencent/Shadow/blob/abf3916a52ec4a83270979e4a30505db90c306be/projects/sdk/core/activity-container/src/main/java/com/tencent/shadow/core/runtime/container/PluginContainerActivity.java#L85-L91

**Comment by lks6123** [comment]
好的

**Comment by lks6123** [comment]
> > 如果有多个插件进程，是每个插件进程调用一遍么？
> 
> 是的。
> 
> > 如果插件和宿主在同一进程，这里要怎么处理？ 不调用了？
> 
> 也要调用。
> 
> 你需要理解这个`recoveryRuntime`的作用。你可以这样复现问题：
> 
> 1. 准备两个插件Activity：A、B。
> 2. 在A中点按钮打开B。
> 3. 在B中点按钮触发Crash。
> 4. 观察插件进程pid，观察插件进程Crash日志。
> 5. 去掉`recoveryRuntime`调用，再观察。
> 
> 预期应该是这样的，在Crash之后，B应该就被系统关掉了。然后系统就会把Activity栈中的前一个Activity A启动起来。这里A也是一个插件Activity，所以它对于系统来说就是runtime.apk中的PluginContainerActivity的子类，它的类代码不在宿主apk中。这时，如果没有调用`recoveryRuntime`，此Activity所在的进程也没有执行过任何插件相关逻辑加载runtime.apk，所以就会发生第2次Crash，即报找不到A类。如果调用了`recoveryRuntime`，这里就能正常启动壳子PluginContainerActivity，之后应该由PluginContainerActivity的逻辑判断出此时的场景，静默finish自己。
> 
> https://github.com/Tencent/Shadow/blob/abf3916a52ec4a83270979e4a30505db90c306be/projects/sdk/core/activity-container/src/main/java/com/tencent/shadow/core/runtime/container/PluginContainerActivity.java#L85-L91

如果我将 loaderRuntime 做一个单独的插件包，在 Application 的 onCreate 中提前进行 loaderRuntime 的安装加载。 那么我应该就不需要调用了。 因为在走onCreate时会重新加载一遍 loaderRuntime 。 这样理解是否正确？

**Comment by shifujun** [comment]
> 如果我将 loaderRuntime 做一个单独的插件包，在 Application 的 onCreate 中提前进行 loaderRuntime 的安装加载。 那么我应该就不需要调用了。 因为在走onCreate时会重新加载一遍 loaderRuntime 。 这样理解是否正确？

是的，可以这样。
