### ISSUE TITLE
插件支持打包成aar吗

### ISSUE THREAD

**Issue by androiddong** [Tencent/Shadow#943]
大神，请教下两个问题：
1、插件打包成aar让宿主加载不支持吗？
apply plugin: 'com.android.library'
apply plugin: 'com.tencent.shadow.plugin'
配成aar插件就会报错
 Failed to apply plugin 'com.tencent.shadow.plugin'.
   > Plugin with type class com.android.build.gradle.AppPlugin has not been used
2、项目需要把一部分功能拆分出来做成插件，减少包体积。插件会用到宿主中一部分代码。不需要动态去管理插件，如何省略manager动态管理过程，让宿主直接加载插件

**Comment by shifujun** [comment]
aar是最终apk构建过程的一个中间状态，并不能直接在Android设备上运行，相当于native编程中的“静态库”。apk才是Android平台上的“可执行程序”和“动态库”。Shadow和其他插件框架的主要功能其实就是在Android平台上提供“动态库”的加载能力。

如果你想把工程解耦成多个插件模块，插件模块共同依赖宿主模块，插件和宿主都编译成apk，这是可行的。只是Shadow目前的代码解决的问题比这个问题要更复杂。你的场景中宿主和插件版本是一对一的关系，Shadow中的是多对多的关系。

可以调试一下Shadow，理解core层各个环节的原理，然后二次开发一下。Shadow的测试工程中有一个省略了manager和dynamic层的例子：
https://github.com/Tencent/Shadow/tree/4ad5668d3954aea0e076955aa97d0b96351d3592/projects/test/none-dynamic/host/test-none-dynamic-host
