### ISSUE TITLE
LoadPluginCallback找不到

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#944]
![image](https://user-images.githubusercontent.com/39261338/167124527-0134cb18-b38e-4d04-9f91-eb4e7af520fc.png)

SamplePluginLoader类里面LoadPluginCallback路径的指向不是outputs文件夹下面的sample-host-lib-debug.jar
而是generated文件夹下的，导致运行时找不到LoadPluginCallback

**Comment by TA-J** [comment]
这些包名我都改掉了，相对应用到这些类的地方也都改了，会有影响吗
![image](https://user-images.githubusercontent.com/39261338/167129715-b677841b-178d-4395-9fab-4c204358cdda.png)

**Comment by shifujun** [comment]
修改任何代码都一定是有影响的。调试白名单相关逻辑，建议全文搜索包名。

如果希望交流代码，应该fork、修改、提交、push上来。这样其他人才能通过git diff看到你改了什么。运行也能复现问题。

**Comment by TA-J** [comment]
https://gitee.com/GaoHJ1112/tx_shadow.git  代码已更上去，在dev分分支，大佬帮忙看看

**Comment by shifujun** [comment]
> https://gitee.com/GaoHJ1112/tx_shadow.git 代码已更上去，在dev分分支，大佬帮忙看看

你这个仓库根本就不是Shadow的分支呀。

**Comment by TA-J** [comment]
主分支是没改包名的，dev分支是改过包名的

**Comment by shifujun** [comment]
请参考
https://github.com/Tencent/Shadow/blob/abf3916a52ec4a83270979e4a30505db90c306be/CONTRIBUTING.md#issue
交流。

**Comment by TA-J** [comment]
github公司网络访问不了，提交代码太麻烦了，我就单独提交到码云了

**Comment by shifujun** [comment]
不push到github影响不大，但是至少需要是同一份代码才能diff。
