### ISSUE TITLE
关于“插件需要利用aapt2的修改资源ID前缀的选项使其与宿主不同”的疑问？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#948]
编译插件时提示：
···
插件需要利用aapt2的修改资源ID前缀的选项使其与宿主不同。
没有找到--package-id参数。示例：
aaptOptions {
    additionalParameters "--package-id", "0x7E", "--allow-reserved-package-id"
}
···

1. 请问这段提示在什么情况下会出现？ 前面测试了很多次demo，没有出现这个提示，今天会一直出现。

2. 这一段代码是每个插件都要添加嘛？
···
aaptOptions {
    additionalParameters "--package-id", "0x7E", "--allow-reserved-package-id"
}
···
3. 如果每个插件都要添加，  "0x7E" 这个是不是不同插件要配置成不一样的？

**Comment by shifujun** [comment]
> 请问这段提示在什么情况下会出现？ 前面测试了很多次demo，没有出现这个提示，今天会一直出现。
这一段代码是每个插件都要添加嘛？

这样的问题在开源项目中最好通过搜索代码来确定。可以blame一下相关代码添加的时间。

> 如果每个插件都要添加， "0x7E" 这个是不是不同插件要配置成不一样的？

不需要。也可以通过观察测试工程的多插件配置来确定。

**Comment by lks6123** [comment]
> > 请问这段提示在什么情况下会出现？ 前面测试了很多次demo，没有出现这个提示，今天会一直出现。
> > 这一段代码是每个插件都要添加嘛？
> 
> 这样的问题在开源项目中最好通过搜索代码来确定。可以blame一下相关代码添加的时间。
> 
> > 如果每个插件都要添加， "0x7E" 这个是不是不同插件要配置成不一样的？
> 
> 不需要。也可以通过观察测试工程的多插件配置来确定。

想问下： 
1. 修改这个前缀的原因是什么？ 宿主和插件的资源不是隔离的么, 为什么还要修改id？
2. 多个插件之后的id都是 0x7e 开头的话，他们不会冲突么？ 插件和插件之间的  与 插件和宿主 之间的 有什么区别呢？

**Comment by shifujun** [comment]
可以先看下 f208e8be245e165f9753094fd2f6ef02f5208135 的提交记录。

确实是想让宿主和插件资源隔离。原因是宿主和插件版本多对多，资源ID在不同版本间会变化，所以不隔离也不能正常工作。
但是存在极少量无法避免的路径，系统就是会问插件要宿主中的资源，所以还不能完全隔离。

所以这里实现的插件可以访问宿主资源的能力并不是为了让业务代码实现这一目的。但是未来确实可以依赖这个资源分区，再加上固定一些资源ID，来实现跨Apk共享资源的目的。

插件之间的资源都是隔离的，所以他们的分区一样是没关系的。

**Comment by lks6123** [comment]
明白了， 意思就是： 
理论上来说是应该让插件资源和宿主资源完全隔离，完全独立的。

但是，在部分情况下，系统会向插件的Resource请求宿主的资源。 这种情况下，需要插件返回宿主的资源。

以前采用了 mixResource的方案，当在插件的Resource中找不到时，会去宿主中查找。但是这种设计方式是违反 “插件宿主资源互相独立” 的这个设计逻辑的。
