### ISSUE TITLE
编译不过，帮我看看这是什么问题

### ISSUE THREAD

**Issue by 123ufo** [Tencent/Shadow#95]
I:\Github4\Shadow>gradlew build

> Configure project :coding:lint
Checking the license for package Android SDK Build-Tools 28.0.2 in D:\AndroidStu
dio3.4\SDK\licenses
Warning: License for package Android SDK Build-Tools 28.0.2 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':coding:lint'.
> Failed to install the following Android SDK packages as some licences have not
 been accepted.
     build-tools;28.0.2 Android SDK Build-Tools 28.0.2
  To build this project, accept the SDK license agreements and install the missi
ng components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to anot
her, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: D:\AndroidStudio3.4\SDK

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:comman
d_line_warnings

**Comment by Hackergeek** [comment]
Failed to install the following Android SDK packages as some licences have not
been accepted.
build-tools;28.0.2 Android SDK Build-Tools 28.0.2
To build this project, accept the SDK license agreements and install the missi
ng components using the Android Studio SDK Manager.
在SDK Manager安装一下28.0.2版本的build-tools就可以了。遇到错误认真看一下报错信息
