### ISSUE TITLE
插件是否可以实现免安装直接启动app呢

### ISSUE THREAD

**Issue by LiJinJinJIn** [Tencent/Shadow#950]
插件是否可以实现免安装直接启动app

**Comment by lks6123** [comment]
我建议你先去学习下 github 提issue 流程规范。 提问的规范啥的，再来提issue！
  提个问题莫名其妙的， 别人也晕乎乎的。

**Comment by shifujun** [comment]
我是比较认同“[talk is cheap show me the code](https://www.goodreads.com/quotes/437173-talk-is-cheap-show-me-the-code#:~:text=Quote%20by%20Linus%20Torvalds%3A%20%E2%80%9CTalk,Show%20me%20the%20code.%E2%80%9D)“的，所以在有限的精力下，我们把更多的精力放在了代码上，让Shadow的sample运行和调试起来更容易一些。

所以简单来说，sample-app可以正常安装运行，也可以在sample-host中动态加载运行（类似动态库）。注意两种运行方式的apk不一样，但是源码是一样的。这样的效果，有的人就会说这是免安装运行插件，有的人就会说不是。不过是不是不重要，它满足了一类需求就可以了。

**Comment by LiJinJinJIn** [comment]
总感觉做的很繁琐，相比DroidPlugin来说，不知道从哪里下手

**Comment by shifujun** [comment]
> 不知道从哪里下手

如果你说的还是这个issue的问题，我已经说了“如何下手“，运行sample-app和sample-host，调试它们。

如果不是这个issue的问题，可以另外提issue，附上复现问题的代码。如果问题清晰并且可以解决，我们就可以改进代码或者改进文档。

**Comment by LiJinJinJIn** [comment]
不好意思没有及时反馈，我今天大概浏览了一下相关的wiki以及文章，我如果有一个现成的线上apk，我现在要使用Shadow直接在一个新的宿主里面打开这个apk。

**Comment by spysoos** [comment]
> 

NO way By this way
