### ISSUE TITLE
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to android.app.servertransaction.ClientTransaction

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#951]
咨询一个问题，宿主启动插件，插件通知宿主拉起支付，不管支付成功失败，在返回插件时出现这个错误
![image](https://user-images.githubusercontent.com/39261338/167985236-55e64c33-2588-4eb7-bb50-f7197f2cd0e8.png)

**Comment by shifujun** [comment]
我搜了一下`android.app.ActivityInjector`这个类应该不是AOSP的类，可能是MIUI的私有设计。估计是MIUI的bug吧。

https://cs.android.com/search?q=android.app.ActivityInjector&sq=
https://stackoverflow.com/questions/61483708/binderproxy-cannot-be-cast-to-clienttransaction-exception-when-changing-defaultn
https://stackoverflow.com/questions/70060730/android-activity-error-with-activityinjector-get-life-cycle-exception

**Comment by TA-J** [comment]
华为P50 也是这样的，只是没有日志

**Comment by shifujun** [comment]
这应该就是MIUI的bug，那个“华为P50”可能只是刷了MIUI而已。从网上搜索的信息来看，`android.app.ActivityInjector`应该只存在于MIUI。

**Comment by ShireYin** [comment]
![img_v3_02h1_7e91c458-0680-431b-8ed2-af2b85e207bl](https://github.com/user-attachments/assets/30e70285-c1f8-4d0a-be15-cfef622c84dd)
xi tong ji bie     系统级别的catch，不会导致你的项目出问题，可忽略
