### ISSUE TITLE
Api < 29 以下 lifecycle 里 ReportFragment 强转失败的问题

### ISSUE THREAD

**Issue by huazidev** [Tencent/Shadow#953]
线上发现了 ReportFragment 强转失败的问题，发现是因为 ReportFragment 是根据 TAG 相同来判断是否是同一个 fragment，也搜到其他 issue https://github.com/Tencent/Shadow/issues/942

想问下，除了处理宿主的 ActivityLifecycleCallbacks 不回调 PluginContainerActivity，还有没有其他的解决方案？

**Comment by huazidev** [comment]
抱歉回复晚了，没有改 support 包的代码，一开始想着使用反射把 Tag 给改了，这也更简单，但是 debug 发现，虽然通过反射修改成功了，但是最终还是会报错，最后还是使用 ActivityLifecycleCallbacks 的方式处理的。

有个疑问想问一下，插件中收到 ActivityLifecycleCallbacks 的回调的时候，会调到下面的代码：

```
ReportFragment.get(activity).setProcessListener(mInitializationListener);
```

ReportFragment get 方法如下：

```
    static ReportFragment get(Activity activity) {
        return (ReportFragment) activity.getFragmentManager().findFragmentByTag(
                REPORT_FRAGMENT_TAG);
    }

```

就是用反射修改了 tag 后，取到的还是原来 tag 对应的 fragment, 注入 fragment 也是原来 tag 的 fragment, 是没有修改成功吗，但是我通过反射再去取得值是修改后的值，还是说因为 `activity.getFragmentManager()` 的 classLoader 是宿主的 classLoader, 导致 `activity.getFragmentManager().findFragmentByTag(
                REPORT_FRAGMENT_TAG)` 中 `REPORT_FRAGMENT_TAG` 一直是宿主中的 ReportFragment 的 tag。
                
  issue 关闭了，希望您能有时间回复一下。

**Comment by shifujun** [comment]
`findFragmentByTag(REPORT_FRAGMENT_TAG);`中的`REPORT_FRAGMENT_TAG`是个常量，反射修改不了吧？所以拿到的还是宿主中的ReportFragment。

`(ReportFragment)`这个强制类型转换中引用的`ReportFragment`是当前代码所在的类的ClassLoader加载的，所以应该是插件中的`ReportFragment`。

**Comment by huazidev** [comment]
找到问题原因了，反射是可以修改静态常量的，我改后重新反射读取值是改动后的值，但是这个改动有一定的局限性，具体的原因应该是：
```
activity.getFragmentManager().findFragmentByTag(
                REPORT_FRAGMENT_TAG)
```

这个方法在编译期就将 `REPORT_FRAGMENT_TAG` 替换成了常量值，所以获取到的也一直是宿主中 ReportFragment。

**Comment by iPel** [comment]
替换add和findFragmentByTag等调用，给插件fragment的tag都加个前缀，是否可行？@shifujun

**Comment by shifujun** [comment]
> 替换add和findFragmentByTag等调用，给插件fragment的tag都加个前缀，是否可行？@shifujun

针对ReportFragment应该是可行的。但如果对所有tag都修改，恐怕会有其他业务逻辑存在hardcode tag的其他用法受影响。但如果把getTag调用也替换掉，可能是行的。再就确认下xml里会不会有什么tag的相关引用了。

**Comment by budaowengd** [comment]
@iPel  请问最后是如何解决的？
