### ISSUE TITLE
PluginProcessPPS 进程通信问题

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#955]
请问一下，使用 LoadPluginCallback 让插件通知宿主，插件进程不能修改宿主进程的变量吗？
![image](https://user-images.githubusercontent.com/39261338/168247190-5080ba93-2c71-4a6f-86ed-ef30453659e8.png)

**Comment by shifujun** [comment]
这个问题涉及的是《操作系统原理》中关于进程的基本知识，就不在这里讨论了吧。
