### ISSUE TITLE
 重复添加Component：ComponentInfo

### ISSUE THREAD

**Issue by 1185864434** [Tencent/Shadow#957]
两个插件都用到com.soundcloud.android.crop.CropImageActivity图片裁剪的东西，宿主调取插件报异常

java.lang.IllegalStateException: 重复添加Component：ComponentInfo{com.ln_hy.dihome/com.soundcloud.android.crop.CropImageActivity}
这种情况需要怎么解决呀

**Comment by shifujun** [comment]
像sample-base一样，抽出一个公共插件，让其他两个插件依赖它，把CropImageActivity放到这个公共插件中。

**Comment by 1185864434** [comment]
具体要怎么实现呀，有相关代码可以分享吗

**Comment by shifujun** [comment]
sample已经是两个具有依赖关系的插件了，再具体就要帮你写好你的需求了。

https://github.com/Tencent/Shadow/blob/ab35d8abd0c721bc106afe8b1b1a648c8d2c0ba2/projects/sample/source/sample-plugin/sample-app/build.gradle#L65-L66

https://github.com/Tencent/Shadow/blob/ab35d8abd0c721bc106afe8b1b1a648c8d2c0ba2/projects/sample/source/sample-plugin/sample-app/build.gradle#L120

**Comment by 1185864434** [comment]
大佬，我重新建一个插件，把其他插件需要的依赖都放进去，然后让其他插件依赖这个插件，是这样吗

**Comment by zhuqichao** [comment]
MultiLoaderPluginProcessService，这里好像是同进程多个loader的实现，能否解决此问题呢

**Comment by shifujun** [comment]
是出于原始需求的场景这样设计的，在设计时也考虑了一定的通用性。

原始的需求是服务于一个业务的，同时希望把一个业务中的多个子业务拆分成多个apk。用户有可能在不同场景下会先打开其中一个apk。拆分成多个apk可以有助于用户尽快下载完他的场景所需的apk。在这种场景下，多插件的apk其实共同组成的是一个app。这和Android系统本身的split apk设计也是类似的。

从技术原理上看，确实允许一个loader加载的多个apk插件包含相同ComponentName的组件是可行的。但是这样也会限制插件只能访问或者要优先访问自带的组件，也会给另外的应用场景带来麻烦。

如果两个插件中的组件确实是同一份代码，那么抽到一个公共基础插件中可以减少插件包大小。如果两个组件确实不是同一份代码，建议将组件改名，可以考虑删除。manifest是可以修改来自aar中的组件名的：https://developer.android.com/studio/build/manage-manifests

MultiLoaderPluginProcessService应该也可以应用到此场景。多个loader实例是互不影响的。除了so中全局符号冲突，不同loader中的插件是隔离的，效果跟多个进程中的loader应该区别不大。MultiLoaderPluginProcessService的原始需求场景就是在同一个宿主的同一个公共插件进程中有多个相互独立的业务都在使用Shadow。

**Comment by zhuqichao** [comment]
> 是出于原始需求的场景这样设计的，在设计时也考虑了一定的通用性。
> 
> 原始的需求是服务于一个业务的，同时希望把一个业务中的多个子业务拆分成多个apk。用户有可能在不同场景下会先打开其中一个apk。拆分成多个apk可以有助于用户尽快下载完他的场景所需的apk。在这种场景下，多插件的apk其实共同组成的是一个app。这和Android系统本身的split apk设计也是类似的。
> 
> 从技术原理上看，确实允许一个loader加载的多个apk插件包含相同ComponentName的组件是可行的。但是这样也会限制插件只能访问或者要优先访问自带的组件，也会给另外的应用场景带来麻烦。
> 
> 如果两个插件中的组件确实是同一份代码，那么抽到一个公共基础插件中可以减少插件包大小。如果两个组件确实不是同一份代码，建议将组件改名，可以考虑删除。manifest是可以修改来自aar中的组件名的：https://developer.android.com/studio/build/manage-manifests
> 
> MultiLoaderPluginProcessService应该也可以应用到此场景。多个loader实例是互不影响的。除了so中全局符号冲突，不同loader中的插件是隔离的，效果跟多个进程中的loader应该区别不大。MultiLoaderPluginProcessService的原始需求场景就是在同一个宿主的同一个公共插件进程中有多个相互独立的业务都在使用Shadow。

感谢回复，再请教一下，无论是否在同一进程，还是使用同一loader，多个插件都是共用so，这样是没有问题的吧。
