### ISSUE TITLE
如何修改插件打包后的zip包

### ISSUE THREAD

**Issue by Melody916** [Tencent/Shadow#960]
你好，请问一下，我在开发过程中，打包插件zip包的方式，是使用plakageReleasePlugin的gradle插件命令进行打包，最终在build目录下形成zip包。现在有个需求，我想在最终形成的zip包里，再添加一个我自己写的config文件，要实现这个效果，有什么建议的方式吗？

**Comment by shifujun** [comment]
这个你二次开发一下很容易的。在这里：
https://github.com/Tencent/Shadow/blob/ab35d8abd0c721bc106afe8b1b1a648c8d2c0ba2/projects/sdk/core/gradle-plugin/src/main/kotlin/com/tencent/shadow/core/gradle/CreatePackagePluginTask.kt#L72

加到from里的文件都会到zip里去了，文档在这里：
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip:from(java.lang.Object[])

**Comment by Melody916** [comment]
感谢，已经实现了想要的需求。
修改了两个module的代码，gradle-plugin，manifest-parser
