### ISSUE TITLE
PluginManagerThatSupportMultiLoader使用问题

### ISSUE THREAD

**Issue by zhuqichao** [Tencent/Shadow#961]
没有找到PluginManagerThatSupportMultiLoader的使用示例代码
请教一下这个类应该怎么使用：
插件的partKey应该怎么传入？

**Comment by shifujun** [comment]
> 每个插件有一个PluginKey

不是每个插件，是每个`PluginManagerThatSupportMultiLoader`的子类，对应每个loader。

> manager对象在什么时机创建呢？

和之前一样，由宿主中的代码自行决定。

> 由于一个进程只有一个PPS实例，那么PluginManagerThatSupportMultiLoader的onPluginServiceConnected也只会回调一次吧

你应该还没有测试吧？每个manager实例应该都是独立bind的PPS，所以它们都会各自收到一次bind的回调，进而回调到`onPluginServiceConnected`方法。

PS：刚才发现这里的`onPluginServiceConnected`方法名不对，应该叫`onPluginProcessServiceConnected`。

**Comment by zhuqichao** [comment]
> > 每个插件有一个PluginKey
> 
> 不是每个插件，是每个`PluginManagerThatSupportMultiLoader`的子类，对应每个loader。
> 我需要实现的需求是，每个进程管理多个插件，每个插件有独立的loader，从而解决重复添加组件的问题，是否是这个场景，如果是的话，是每个插件对应一个PluginManagerThatSupportMultiLoader的子类吗？
> > manager对象在什么时机创建呢？
> 
> 和之前一样，由宿主中的代码自行决定。
> 之前不是宿主自行决定，是通过实现ManagerFactory，返回manager实例的
> > 由于一个进程只有一个PPS实例，那么PluginManagerThatSupportMultiLoader的onPluginServiceConnected也只会回调一次吧
> 
> 你应该还没有测试吧？每个manager实例应该都是独立bind的PPS，所以它们都会各自收到一次bind的回调，进而回调到`onPluginServiceConnected`方法。
> 
> PS：刚才发现这里的`onPluginServiceConnected`方法名不对，应该叫`onPluginProcessServiceConnected`。
