### ISSUE TITLE
请问如果宿主设置了productFlavors，需要做哪些额外的处理？

### ISSUE THREAD

**Issue by GodOfRealm** [Tencent/Shadow#962]
如题

**Comment by shifujun** [comment]
应该不用什么处理吧？

能问这个问题，应该是遇到什么问题了吧？为什么不直接把代码放上来呢？

productFlavors影响的是构建时采用的源码路径。对于Shadow接入宿主的代码来说，这没什么影响，对于需要对接插件的productFlavors，都应该引入Shadow的host模块。

**Comment by GodOfRealm** [comment]
如果宿主中做了如下配置：
    flavorDimensions "default"
    productFlavors {
        //内网
        beta {
            dimension "default"
        }
        //外网
        pre {
            dimension "default"
        }
    }

demo中这一段代码：
tasks.whenTaskAdded { task ->
    if (task.name == "generateDebugAssets") {
        //region hello.apk 演示
        generateHelloAssets(task, 'debug')
        //endregion
    }
    if (task.name == "generateReleaseAssets") {
        //region hello.apk 演示
        generateHelloAssets(task, 'release')
        //endregion
    }
}
对于的task,name的判断是不是需要相应的改成generateBetaDebugAssets 或者generateBetaReleaseAssets
