### ISSUE TITLE
java.net.SocketException: socket failed: EPERM (Operation not permitted)

### ISSUE THREAD

**Issue by withyi9223** [Tencent/Shadow#964]
网络请求使用的是retrofit，连接了不能访问外网的WiFi，单独安装插件app，请求局域网地址没问题，但是如果当作插件使用，一直提示：java.net.SocketException: socket failed: EPERM (Operation not permitted)，这是什么导致的呢？

**Comment by shifujun** [comment]
估计是宿主没有网络请求权限的关系。

注意下目前所有插件技术都不能使manifest的任何内容动态更新，所以由manifest控制的app权限只能由宿主声明。

再注意shadow设计逻辑是：插件只是宿主代码的一部分。

**Comment by withyi9223** [comment]
是的 ，解决了 ，唉，大意了，thanks
