### ISSUE TITLE
宿主apk32位升级到64位的时候，由于插件没变，使用的还是之前32位的so，导致崩溃；

### ISSUE THREAD

**Issue by a5533348** [Tencent/Shadow#971]
宿主apk是32位的，使用了我们的插件，在第一次初始化的时候会把32位的so解压拷贝到内部目录；
这时候宿主apk升级64位了，而且是覆盖安装升级，由于插件没有变，进入插件使用的还是32位的so，这就会有问题了

**Comment by shifujun** [comment]
我先考虑了一下正常app安装，正常app也是在安装时确定ABI，复制出so的。所以插件目前也是安装时确定ABI和复制so应该是合理的。

那么这个问题我觉得应该理解成，宿主做了一个和插件不兼容的版本升级。就像本来插件依赖宿主的一个Java接口，添加到访问宿主类的白名单里了。但是宿主在某个版本升级时去掉了这个接口。这时插件也是不能正常工作的。这和此issue的问题，我理解是一样的。

所以在这种场景下，可以通过更新Manager的`com.tencent.shadow.core.manager.BasePluginManager#getName`值，让新版本宿主使用一个全新的manager存储，然后下载对应新版本的插件就可以了。

如果考虑本地依然有旧版本插件包缓存可用，可以考虑在manager的下载逻辑中进行复用。

**Comment by a5533348** [comment]
ok

**Comment by dtdeng** [comment]
![image](https://github.com/Tencent/Shadow/assets/9609581/48a4c033-d822-402e-a287-15b941cb9d50)
![image](https://github.com/Tencent/Shadow/assets/9609581/bb6b3f57-ceb8-4eb7-86b9-2b7e5315849c)
该问题可以这样修复，后面有踩这个坑的同学可以看看。

**Comment by dtdeng** [comment]
> 

简单来说就是解压so的时候根据cpu架构解压到对应目录，安装时该so路径默认会插入到插件表里面，后续创建classloader时也会使用该so路径作为classloader的librarySearchPath
