### ISSUE TITLE
插件项目中build.gradle的productFlavors配置问题

### ISSUE THREAD

**Issue by Melody916** [Tencent/Shadow#975]
你好，在插件开发时，都需要在build.gradle中定义一个productFlavors，在这里修改applicationId为宿主的applicationId。如
productFlavors {
        plugin {
            applicationId "XXXXXXXXXXX"
        }
}

这里一定要按照这个格式来定义吗？是否可以去掉外层的括号，直接在android 节点里定义
applicationId "XXXXXXXXXXX"

然后将pluginCompileOnly的地方，修改为compileOnly，是否可以这样处理。

**Comment by shifujun** [comment]
当一个问题是“可不可以？“时，建议先自己试一试。如果发现不可以，可以自己调试一下实现代码。如果无法理解为什么不可以，可以把代码push上来公开给大家。这样其他人才能有和你相同的代码进行调试，才能比较准确的解答为什么不可以。

否则面对一个模糊的描述，只能给出一个模糊的回答：”应该不行吧。“
