### ISSUE TITLE
请问目前框架是否支持插件内部Activity相互跳转时的「ActivityOptions」转场动画？

### ISSUE THREAD

**Issue by yumdao** [Tencent/Shadow#976]
我在runtime定义的activity中，设置进行了如下调整：

```kotlin
class PluginStandardActivity : PluginContainerActivity() {

    override fun onCreate(arg0: Bundle?, arg1: PersistableBundle?) {
        

        with(window) {
            requestFeature(Window.FEATURE_ACTIVITY_TRANSITIONS)

            enterTransition = Slide(Gravity.RIGHT)
            exitTransition = Slide(Gravity.BOTTOM)
        }
        super.onCreate(arg0, arg1)
    }

    override fun startActivityForResult(intent: Intent?, requestCode: Int, options: Bundle?) {
        val newOptions = ActivityOptions.makeSceneTransitionAnimation(this).toBundle()
        super.startActivityForResult(intent, requestCode, newOptions)
    }
}
```
但是动画效果无法生效，是目前还未做支持吗？

**Comment by shifujun** [comment]
`PluginContainerActivity`是普通的`android.app.Activity`，所以它不是一个插件Activity，它的转场动画特性和其他宿主中的Activity是一样的，不需要特别支持。

你这里的代码看起来不像是写在了插件框架启动`PluginContainerActivity`的路径上，我的意思是，你写的代码可能就没有执行过。建议你写在sample中，然后debug调试一下。

sample中启动`PluginContainerActivity`的代码在这里：
https://github.com/Tencent/Shadow/blob/87d721947f1f05d31ed983037ca8c8e9ea7f8555/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L140

**Comment by yumdao** [comment]
> `PluginContainerActivity`是普通的`android.app.Activity`，所以它不是一个插件Activity，它的转场动画特性和其他宿主中的Activity是一样的，不需要特别支持。
> 
> 你这里的代码看起来不像是写在了插件框架启动`PluginContainerActivity`的路径上，我的意思是，你写的代码可能就没有执行过。建议你写在sample中，然后debug调试一下。
> 
> sample中启动`PluginContainerActivity`的代码在这里：
> 
> https://github.com/Tencent/Shadow/blob/87d721947f1f05d31ed983037ca8c8e9ea7f8555/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L140

`mPluginLoader.startActivityInPluginProcess(intent); `如果我理解的没错的话，该方法是宿主拉起插件后打开插件的Activity的方法吧。
我的意思是，在插件中Activity相互跳转的时候，因为插件Activity是被`PluginContainerActivity`代理的，所有我直接把转场动画加到`PluginContainerActivity`的子类`PluginStandardActivity `上，并且在debug时，是能访问到我设置动画和跳转的代码的，而且该设置是有效果的，只不是不是设置转场动画预期的效果，ε=(´ο｀*)))唉。

**Comment by shifujun** [comment]
为什么不在插件代码中正常用`ActivityOptions.makeCustomAnimation`然后`startActivity`呢？

Shadow的目标是让可以正常安装运行的代码可以编译成插件运行。

按我的理解，`ActivityOptions`这套转场动画的API会从传入的context中获取资源，所以Shadow应该是支持的。不像是过去的`overridePendingTransition` API，是系统从另外的进程向已安装的宿主获取资源，所以Shadow无法支持它从插件中获取动画资源。

**Comment by yumdao** [comment]
> 为什么不在插件代码中正常用`ActivityOptions.makeCustomAnimation`然后`startActivity`呢？
> 
> Shadow的目标是让可以正常安装运行的代码可以编译成插件运行。
> 
> 按我的理解，`ActivityOptions`这套转场动画的API会从传入的context中获取资源，所以Shadow应该是支持的。不像是过去的`overridePendingTransition` API，是系统从另外的进程向已安装的宿主获取资源，所以Shadow无法支持它从插件中获取动画资源。

因为理解的是插件中Activity在打包成插件后继承的是ShadowActivity，而这个ShadowActivity是被PluginContainerActivity所代理的，PluginContainerActivity才是真正打开的Activity，所以我直接在PluginContainerActivity里面进行了过场动画的设置。

我现在尝试在插件Activity中设置过场动画，看能否达到想要的效果。

**Comment by yumdao** [comment]
> 为什么不在插件代码中正常用`ActivityOptions.makeCustomAnimation`然后`startActivity`呢？
> 
> Shadow的目标是让可以正常安装运行的代码可以编译成插件运行。
> 
> 按我的理解，`ActivityOptions`这套转场动画的API会从传入的context中获取资源，所以Shadow应该是支持的。不像是过去的`overridePendingTransition` API，是系统从另外的进程向已安装的宿主获取资源，所以Shadow无法支持它从插件中获取动画资源。

我试过，在插件中的Activity添加ActivityOptions是行不通的，因为
`ActivityOptions.makeSceneTransitionAnimation`或`ActivityOptions.makeCustomAnimation`方法需要以android.app.Activity作为入参，而插件打包之后android.app.Activity被修改为ShadowActivity。

因此无法直接在插件的Activity中定义转场动画。

**Comment by yumdao** [comment]
> 

哦对，`makeCustomAnimation `是需要资源Id，这样的话会怕是会和`overridePendingTransition `有同样的资源的问题。

我在插件的Activity onCreate方法的super调用之前设置转场动画：
```kotlin
//插件内的activity
class UserActivity : BaseActivity(R.layout.activity_user) {

    override fun onCreate(savedInstanceState: Bundle?) {
        with(window) {
            requestFeature(Window.FEATURE_ACTIVITY_TRANSITIONS)

            enterTransition = Slide(Gravity.TOP)
            exitTransition = Slide(Gravity.BOTTOM)
        }

        super.onCreate(savedInstanceState)
    }
}
```

然后再runtime的`PluginContainerActivity`重写`startActivityForResult`，如下：
```kotlin
    override fun startActivityForResult(intent: Intent?, requestCode: Int, options: Bundle?) {
        val newOptions = ActivityOptions.makeSceneTransitionAnimation(this).toBundle()
        super.startActivityForResult(intent, requestCode, newOptions)
    }
```
可以实现预期转场动画效果，这样不用修改框架源码。

但是为什么在`PluginContainerActivity`重写的onCreate方法中设置转场动画，却没有效果，这点我尚未弄清楚，还需要再研究一下。

感谢大佬，Thanks♪(･ω･)ﾉ
