### ISSUE TITLE
关于Shadow中广播的一些疑问？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#986]
1. 宿主发送广播，插件中注册静态广播是否支持？ （我测试了下没有成功。）
2. 现在静态广播要求必须是定向广播，那么在发送广播时
```
        findViewById<Button>(R.id.btn_test_receiver).setOnClickListener {
            Log.d(TAG,"click btnTestReceiver")
            val intent = Intent("com.leelu.shadow.TEST_RECEIVER").apply {
                putExtra("TestData","这是一个测试广播，测试在插件中广播的调用方式")
                component = ComponentName("com.leelu.plugin_app","com.leelu.plugin_app.TestReceiver")
            }
            sendBroadcast(intent)
        }
```
ComponentName() ，里面的包名和类名称怎么填写？  填宿主的包名，还是插件的包名？ 填插件的类名还是？

**Comment by shifujun** [comment]
静态广播和动态广播都支持，这有一个自动化测试的：
https://github.com/Tencent/Shadow/blob/aa7dcf4b834fccb3d024f2c87b8a7485a2366545/projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_main/PluginBroadcastReceiverTest.java#L13-L16

支持的原理就是简单的包装一层进行转换：
https://github.com/Tencent/Shadow/blob/f208e8be245e165f9753094fd2f6ef02f5208135/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/ShadowContext.java#L274

> ComponentName() ，里面的包名和类名称怎么填写？ 填宿主的包名，还是插件的包名？ 填插件的类名还是？

Shadow的设计目的是使插件代码可以正常编译安装的，所以写代码时不应该考虑宿主的概念。如果插件正常安装运行一切正常，而编译成插件时不正常，那么就是有Shadow的Bug。如果有这样的问题，可以在自动化测试用例上修改复现，然后push上来我调试一下看看。

**Comment by lks6123** [comment]
修改了下代码。宿主发送，插件接收到了静态广播了。  当插件的 application 初始化完成，即在mananger 中的 callApplication() 调用完成之后。插件中注册的静态广播就能收到了。
