### ISSUE TITLE
com.tencent.shadow.core:gradle-plugin:2.2.1下载不了

### ISSUE THREAD

**Issue by lodqc** [Tencent/Shadow#987]
![image](https://user-images.githubusercontent.com/53686290/172321145-f4562fe3-305f-454a-b203-2e3fc3c66190.png)。没有修改,maven/plugin-project中的任何代码。

**Comment by shifujun** [comment]
可以看到你的Gradle在访问`github.com`时解析到`127.0.0.1`了。

可以配置下代理，像这样：`./gradlew -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8080 clean`。
