### ISSUE TITLE
这个框架能直接当做webview来加载H5吗

### ISSUE THREAD

**Issue by createBean** [Tencent/Shadow#99]
这个框架能直接当做webview来加载H5吗

**Comment by shifujun** [comment]
不能。

但是我不是很确定听懂了你为什么这么问。H5本来就是Web页面，可以动态加载，要Android的插件技术干嘛？

**Comment by myth2loki** [comment]
> 不能。
> 
> 但是我不是很确定听懂了你为什么这么问。H5本来就是Web页面，可以动态加载，要Android的插件技术干嘛？

应该是指的hybrid的吧，这样可以动态增加原生功能

**Comment by shifujun** [comment]
> > 不能。
> > 但是我不是很确定听懂了你为什么这么问。H5本来就是Web页面，可以动态加载，要Android的插件技术干嘛？
> 
> 应该是指的hybrid的吧，这样可以动态增加原生功能

可是插件框架技术本来就是在做动态修改原生功能的事情了啊。

**Comment by myth2loki** [comment]
> > > 不能。
> > > 但是我不是很确定听懂了你为什么这么问。H5本来就是Web页面，可以动态加载，要Android的插件技术干嘛？
> > 
> > 
> > 应该是指的hybrid的吧，这样可以动态增加原生功能
> 
> 可是插件框架技术本来就是在做动态修改原生功能的事情了啊。

我的意思是他会不会是想问动态修改原生功能供js调用的这种功能
