### ISSUE TITLE
ShadowPluginLoader 实现细节的一个疑问？

### ISSUE THREAD

**Issue by lks6123** [Tencent/Shadow#990]
ShadowPluginLoader 中有一段代码
```
abstract class ShadowPluginLoader(hostAppContext: Context) : DelegateProvider, DI,
    ContentProviderDelegateProvider {

    protected val mExecutorService = Executors.newCachedThreadPool()

    open val delegateProviderKey: String = DelegateProviderHolder.DEFAULT_KEY

    /**
     * loadPlugin方法是在子线程被调用的。而getHostActivityDelegate方法是在主线程被调用的。
     * 两个方法需要传递数据（主要是PluginParts），因此需要同步。
     */
    private val mLock = ReentrantLock()

    /**
     * 多插件Map
     * key: partKey
     * value: PluginParts
     * @GuardedBy("mLock")
     */
    private val mPluginPartsMap = hashMapOf<String, PluginParts>()

```
我这边在使用的时候遇到一个问题。 为了优化打开页面的速度。 插件的加载我们在启动的时候会通过并发的形式进行提前加载。
当插件 A 加载过程中，会把mLock 锁住。 此时加载B插件, 当通过 mPluginLoader.getLoadedPlugin().containsKey(partKey)。来判断插件B 是否已加载时，此时 A 还没加载完，mLock 还没释放。 在ShadowPluginLoader中获取mPluginPartsMap时，会被mLock 卡住，等mLock  释放了之后，才能拿到mPluginPartsMap，从而判断插件B是否已加载，导致B插件加载时间会变长很多。 

 这里有什么办法优化吗？ 比如把 mPluginPartsMap 改为 concurrentHashMap。 不通过 ReentrantLock 来加锁。  还是说 必须这样设计，当 插件A加载时，mPluginPartsMap 不能读取，只有完成了才能读取？

正常使用中也有可能遇到这个情况，A 插件已经加载过了，但是此时启动B插件，然后马上启动A插件。 此时，在B插件加载过程中，A插件判断A是否已被加载的过程会被卡住，得等B插件加载完成才能判断到A已加载。才能把A启动。

**Comment by shifujun** [comment]
肯定是能优化的。这里使用ReentrantLock是因为我们当初的使用场景没有遇到你说的问题，那么按照先正确实现再优化的原则，直接选择ReentrantLock是最安全的实现。

简单review了一下现有代码，看起来这个锁同时保护了3部分数据:`ComponentManager`,`PluginPartInfoManager`,`mPluginPartsMap`，所以肯定不能简单的替换为ConcurrentHashMap。

因为`ComponentManager`中同时融合了多个插件中的数据，所以我们只能先排除按`partKey`加锁的方案。

然后就是看一下锁的范围是不是太大了。比较容易优化的应该是`LoadApkBloc.loadPlugin`这里的锁。可以缩小锁的范围到其中查找dependsOn的部分。

`componentManager.addPluginApkInfo`看起来也可能因为插件组件较多而比较慢。但简单看这里加锁是必须的。如果要优化的话，就必须重构`addPluginApkInfo`的过程，将其中forEach插件信息构造ComponentName的过程和修改其各种map状态的过程分开，从而将锁的范围缩小到状态修改的短暂部分。

你可以针对你目前的情况，先看一下mLock锁住的时候主要是卡在哪个方法中了。可以提个PR优化一下。我可以帮忙CR。

**Comment by lks6123** [comment]
> 

对 LoadApkBloc.loadPlugin 这里的耗时做了下测试统计，最大的耗时在
```
if (dependsOn == null || dependsOn.isEmpty()) {
            val startTime1 = System.currentTimeMillis()
            mLogger.debug("countTime shadow loadPlugin 1 start, startTime = $startTime1")
            val result = PluginClassLoader(
                apk.absolutePath,
                odexDir,
                installedApk.libraryPath,
                hostClassLoader,
                hostParentClassLoader,
                loadParameters.hostWhiteList
            )

            val endTime1 = System.currentTimeMillis()
            mLogger.debug("countTime shadow loadPlugin 1 end, endTime = $endTime1 , temp = ${endTime1 - startTime1}")
            return result
        } else if (dependsOn.size == 1) {
```
创建 PluginClassLoader() 对象这里。 在首次加载时，能达到4000多毫秒。 看你的意思是 loadPlugin 这里只需要对 查找dependsOn 这一块儿进行加锁。 也就是说，在loadPlugin方法中，将锁传入， 涉及到 dependsOn 相关的进行加锁就可以了是吧？

**Comment by lks6123** [comment]
> > 也就是说，在loadPlugin方法中，将锁传入， 涉及到 dependsOn 相关的进行加锁就可以了是吧？
> 
> 是的。注意锁要保护的是`pluginPartsMap`，所以涉及它的代码加锁就行了。

#994  你RV一下，看看这样修改可以么

**Comment by lks6123** [comment]
> > 也就是说，在loadPlugin方法中，将锁传入， 涉及到 dependsOn 相关的进行加锁就可以了是吧？
> 
> 是的。注意锁要保护的是`pluginPartsMap`，所以涉及它的代码加锁就行了。

您好，我想问下，
1. 创建 PluginClassLoader() 对象这段代码为什么 首次 创建时时间会很长，我在 一个老机器上测试的时候，能到 4000+ ms，而二次启动创建只需要 700+ ms  。 是因为首次需要做对本地dex文件做某些工作嘛？
2. 单独创建一个的时候4000多毫秒，但是假如4个插件并发加载，创建PluginClassLoader，时间能到9000毫秒，这是什么原因？

**Comment by shifujun** [comment]
ClassLoader构造器在低版本API系统上执行的慢应该主要是odex过程慢。所以有一个单独odex的方法，试图在更新插件时后台静默提前完成这一过程

https://github.com/Tencent/Shadow/blob/e7988d6d26d4804d598fc64e5e9e9c852edbb2d2/projects/sdk/core/manager/src/main/java/com/tencent/shadow/core/manager/installplugin/ODexBloc.java#L43
