### ISSUE TITLE
支持arouter启动插件吗

### ISSUE THREAD

**Issue by lidongdong139** [Tencent/Shadow#991]
宿主中要想scheme方式启动插件activity,通过arouter方式实现，但是找不到路由地址。
看之前的回复可以arouter实现https://github.com/Tencent/Shadow/issues/778#issuecomment-1014084620
代码地址https://github.com/lidongdong139/Shadow/tree/arouter

**Comment by shifujun** [comment]
我在你的diff页面：https://github.com/Tencent/Shadow/compare/master...lidongdong139:arouter
中搜索`convertPluginActivityIntent`。只看到你把`convertPluginActivityIntent`调用去掉了，但是我没看到你在哪里实现的ARouter调用`convertPluginActivityIntent`。

所以你应该研究一下ARouter怎么定义它的`navigation`方法的行为，加入一个`convertPluginActivityIntent`的过程就应该可以了。
