### ISSUE TITLE
ShadowPendingIntent 实现 getService()和getBroadcast()

### ISSUE THREAD

**Issue by code-czh** [Tencent/Shadow#992]
请问ShadowPendingIntent 怎样实现 getService()和getBroadcast()？
用于插件中调用AlarmManager.setExact(int type, long triggerAtMillis, PendingIntent operation)

**Comment by shifujun** [comment]
插件内部的Service的start或者bind是没有经过宿主中Service转调的，是ShadowContext转调ComponentManager直接管理的。
因此如果要生成一个PendingIntent给系统，让系统可以通过这个Intent访问插件的Service，就需要新增一个宿主中Service转调的能力。这个能力可以由PPS来提供。

插件的Broadcast并不需要通过ShadowPendingIntent转调，用原本的PendingIntent就可以了。BroadcastReceiverWrapper存在的意义是，插件的Receiver都是通过宿主context向系统注册的，因此BroadcastReceiverWrapper需要在回调onReceive时把context换回shadowContext还给插件代码。

**Comment by code-czh** [comment]
@shifujun 
改造成插件之前在宿主AndroidManifest中注册的静态广播，改造成插件后变成在插件的AndroidManifest中注册。
对于手机厂商的APP，通过静态广播是可以拉起进程的。Shadow会把插件的AndroidManifest注册的静态广播在ShadowApplication中转换成动态广播。

问题1：插件进程没启动，广播如何生效？
问题1：插件进程启动后挂掉，广播何时重新注册？

**Comment by shifujun** [comment]
只能在AndroidManifest注册才能生效的，可以启动进程的静态广播，Shadow基于公开API自动重构业务代码肯定是无法实现的。
所以Shadow只能把它们重构为注册为以ShadowApplication为context的动态广播。

所以插件进程不启动，这些广播是无法生效的。要让这些广播生效，至少需要调用到callApplicationOnCreate。

在思考上述问题时，应该注意插件经过Shadow重构和加载后，其实只是宿主App的一部分动态加载的普通代码而已。因此Shadow可以做到的事，完全都可以被手工重构代码替代的。

**Comment by shifujun** [comment]
大概是因为receiver有一层wrapper类的关系。应该算bug吧。看起来这种intent需要做一下转换。

**Comment by code-czh** [comment]
@shifujun 能提供下思路吗？为什么XxxReceiver注册成功了，指定它作为接收广播的组件，却收不到呢？

**Comment by shifujun** [comment]
你把那个component name换成这个类应该就能收到了：https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/runtime/src/main/java/com/tencent/shadow/core/runtime/BroadcastReceiverWrapper.java

所以这里shadow应该把这个intent自动转换一下。

**Comment by code-czh** [comment]
@shifujun 
情景1改成：
Intent intent = new Intent();
intent .setPackage(context.getPackageName());
intent .setComponent(new ComponentName(context,com.tencent.shadow.core.runtime.BroadcastReceiverWrapper.class)); 
context.sendBroadcast(intent);
结果：BroadcastReceiverWrapper 仍收不到广播

**Comment by shifujun** [comment]
我也调试了一下：https://github.com/shifujun/Shadow/commit/c3e4c5d68133212763533337fe8f5729db3188bc

首先setComponent和setClassName是一样的，ComponentName本身也只是存储一个String类型的类名。所以没必要用.class去构造，这个跟ClassLoader关系不大，用.class构造只是方便一些。

通过实验发现这种指定了ComponentName的Intent发送的广播确实只会去AndroidManifest中查找注册的静态广播。所以对于插件来说，这种方式发送广播是行不通的。

本来广播这个机制应该就是同时发送给多个接收者的，所以它才叫广播嘛。

**Comment by code-czh** [comment]
@shifujun 多谢解答广播问题。我这边还遇到一个很奇怪的问题，请教下你：

**Comment by code-czh** [comment]
@shifujun 麻烦有空看下哈

**Comment by shifujun** [comment]
没看明白和ShadowPendingIntent有什么关系。

**Comment by code-czh** [comment]
@shifujun 是我没说清楚，这个问题跟ShadowPendingIntent没关系，是一个全新的问题。
