### ISSUE TITLE
约束布局失效

### ISSUE THREAD

**Issue by chenlin139** [Tencent/Shadow#995]
插件中使用了宿主的view，view中有constraintlayout.宿主中view的约束效果失效，如图1
如果在白名单加上约束布局的包名，就会出现2图插件view的约束效果失效
图1
![image](https://user-images.githubusercontent.com/10593455/173533584-43a841d3-c2ca-4b06-a147-a44ca4f5a76e.png)
图2
![image](https://user-images.githubusercontent.com/10593455/173533623-e8c65d48-154b-40a7-858f-6f08bae00c63.png)

https://github.com/lidongdong139/Shadow/tree/constraintlayout

**Comment by shifujun** [comment]
大概看了一下你的代码，无关的修改有点多。比如为什么跑去改slidingmenu，又为什么又改了test又改sample。

但我大概是能猜到原因。看起来MyGameView和ConstraintLayout都是宿主中的代码。然后你在插件里的xml中添加了MyGameView。这是不行的。因为ConstraintLayout带有自定义资源，比如`app:layout_constraintTop_toBottomOf`。
所以要构造这种宿主里的View需要用宿主的Context来构造。

View的Context，也就是它的上下文，决定了它该从哪里获取资源，适配什么样的设备环境。插件的宿主的Context主要区别就在于它们的资源来自于不同的apk。xml在inflate时是使用Inflater绑定的context的，所以xml中的view都是同一个context构造的。你可以尝试用代码指定宿主的context构造这个MyGameView，然后再把它添加到xml Inflater出的ViewGroup中。
