### ISSUE TITLE
宿主打开插件activity,插件activity中调用插件的service 没有反应

### ISSUE THREAD

**Issue by hslandlsh** [Tencent/Shadow#996]
宿主打开插件activity,插件activity中调用插件的service 没有反应

**Comment by lks6123** [comment]
> 宿主打开插件activity,插件activity中调用插件的service 没有反应

要不给你算一卦？

**Comment by hslandlsh** [comment]
插件内隐式启动service 失败

**Comment by hslandlsh** [comment]
发现隐式启动失败是因为包名 给错了，但是隐式启动想要成功调起service需要 现在手机上下载好 插件 的apk 包，这时候又失去了插件化的特点，有大佬可以帮忙看看吗？

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/e7988d6d26d4804d598fc64e5e9e9c852edbb2d2/CONTRIBUTING.md#issue
