### ISSUE TITLE
与Tinker使用的问题

### ISSUE THREAD

**Issue by xiongping** [Tencent/Shadow#999]
具体错误：
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory

分析：
Tinker在加载dex时会使用DelegateClassLoader，导致宿主ClassLoader的继承关系变为：
PluginClassLoader->DelegateClassLoader->Runtime所在的ClassLoader->PathClassLoader
正常情况下是：
PluginClassLoader->PatchClassLoader->Runtime所在的ClassLoader

具体原因为：
正常情况：
PluginClassLoader.loadClass中会优先从其specialclassLoader（就是runtime）中加载，正常是无法加载，
因为runtime中没有这个类，就会走PluginClassLoader自己的加载逻辑，加载插件中的AppComponentFactory，
因为插件中的这个类的父类被改成了ShadowAppComponentFactory，从而可以强转
Tinker中的情况：
specialClassLoader的parent的PathClassLoader，所以直接加载了宿主的AppCompoentFactory，所以强转失败。

目前想到的是需要修改Runtime的hack点：
1、现有的Runtime的classLoader是默认改为宿主classLoader的parent，tinker这种修改了宿主classLoader就出问题了，应该是要将runtime设为宿主的pathclassLoader的parent，所以要从宿主的classLoader一直往上找到PathClassLoader
2、LoadApkBloc中会将宿主classLoader的parent设为PluginClassLoader的specialClassLoader，在Tinker那种classLoader关系下就会是PathClassLoader,其实也应该是找到PathClassLoader的parent

**Comment by shifujun** [comment]
感觉问题描述的还是有点不清楚，不过不太重要，大概也明白你在说什么了。

首先判断需求是否合理。我认为有两点不合理的地方：
1. Tinker和Shadow两种动态更新代码逻辑的技术混用是没有必要的。
2. 多种涉及ClassLoader定制的SDK混用。

这两种场景都是通用代码很难满足的。所以如果不管你为什么这么用，修复方案应该也只是适合你的场景的，而不会是通用的。

你遇到到问题大概就是说有另外的SDK致使Shadow所需的多个ClassLoader的parent关系出现了Shadow代码预期外的情况。Shadow代码对它们的关系是hardcode的，固定的认为它们之间隔着几层parent，或者谁持有谁。而这种关系被另外的代码修改了。确实可以修改这种hardcode的实现，通过一些动态逻辑查找ClassLoader，但这不是很有必要。因为相互不了解的代码都去修改ClassLoader，肯定是很难协同工作好的。

如果你在修改Shadow代码上有遇到具体的问题，我可以解答或者改进代码注释。如果交流代码，你最好把代码push上来，否则尽管你认为你已经描述的很清楚了，但实际上还是要靠猜的。
